### ISSUE TITLE
Select Tracks by Language Code

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1108]
**Original reporter**: *TonyPh12345*

Feature Request:

After spending hours removing non-English tracks from a newly ripped DVD TV Series Collection with a varying number of subtitle tracks and languages per episode (consisting of 200+ episodes) using traditional method like:

mkvmerge -o 'Show.S06E01.mkv1' -s '!3,4,5' --default-language eng 'Show.S06E01.mkv'

(where subtitle tracks 3,4,5 are non-English, determined after examining every file individually with mkvinfo first), I was wishing there'd be a syntax with something like this:

mkvmerge -o 'Show.S06E01.mkv1' -a 'eng|und' -s 'eng|und' 'Show.S06E01.mkv'

Meaning:  Merge the input, selecting only English (or undetermined) audio and subtitles to the output file.

Even without the "OR" (|) syntax, it'd be useful -- just would mean I'd have to make darn sure there's a language ID assigned to every track! :)

Hopefully this can make it into the future.

Thanks!

**Comment by TonyPh12345** [comment]
Hey!  Just noticed this was implemented.  THANKS!   It took me about 10 minutes to scrape through another series of 200 files that had tons of foreign subtitle tracks.

**Comment by mbunkus** [comment]
You're welcome :)
