### ISSUE TITLE
Changing the audio track language in mkvmerge GUI doesn't seem to work

### ISSUE THREAD

**Issue by tholmir** [mbunkus/mkvtoolnix#1110]
1. Which MKVToolNix version are you using? Have you also tried the latest release?
I'm using mkvmerge GUI v7.5.0.

2. Which operating system and architecture (32bit vs 64bit) are you using?
Windows 7 Home Premium SP1 (64bit)

3. What did you try to do? 
The audio file (AC3) in the mkv is flagged as being in English, but it should be French.
So, I open the mkv in mkvmerge GUI, change the "Language" field to "fre (French)", and press the "Start muxing" button.
If I reopen the file in mkvmerge, the audio track is flagged as being in French, but if I open the same file in MediaInfo (https://mediaarea.net/en/MediaInfo) or in Plex (https://plex.tv), the audio track is still flagged as English.

4. What was the expected result?
The audio track should be flagged as being in French.

5. What happened instead?
The audio track is being flagged as being in English.

I'm attaching a screenshot of mkvmerge, and a screenshot from MediaInfo.

![ici louis-jose houde - s01e01 - fabienne larouche](https://cloud.githubusercontent.com/assets/10710720/5902549/5e6ebabc-a549-11e4-8c93-5032c41c8dc8.png)
![mediainfo - ici louis-jose houde - s01e01 - fabienne larouche](https://cloud.githubusercontent.com/assets/10710720/5902615/e0a54096-a549-11e4-90f5-25119728b258.png)

**Comment by mbunkus** [comment]
If mkvmerge recognizes the audio as French then it is French. Anything else that MediaInfo reports is most likely a bug in MediaInfo – or you accidentally opened the original file in MediaInfo again.

Anyway, this is not a bug in mkvmerge. Sorry.

**Comment by tholmir** [comment]
I'm sorry to insist.
Plex also reports it has being in English.
So, I would be really surprised if there is the same bug in 2 separate applications.
![plex - ici louis-jose houde - s01e01 - fabienne larouche](https://cloud.githubusercontent.com/assets/10710720/5902939/af6900f0-a54c-11e4-98cb-d15559f3864f.png)

And I'm 100% sure I'm using the right file, because I deleted the original file that was in English.

**Comment by mbunkus** [comment]
If you want me to take a look then please upload the remuxed file (the one that mmg reports having a French audio track) to my [FTP server](https://trac.bunkus.org/wiki/FtpServer). Thanks.

**Comment by tholmir** [comment]
I don't currently have the necessary bandwidth to do that. I'm reaching the limit of what my IPS is allowing me for the month. It's a 400 MB file.

I though of using mmg to remove all the files from the mkv, keeping only the audio track.
The result is a 32 MB mka file.
When I open it in MediaInfo, the try is in French.

Do you see why it would be ok now?
![mediainfo audio only - ici louis-jose houde - s01e01 - fabienne larouche](https://cloud.githubusercontent.com/assets/10710720/5903424/98a3422e-a54f-11e4-9377-ab8dc5f20fdb.png)

**Comment by mbunkus** [comment]
No. Like I said: I highly suspect a bug in MediaInfo or user error. You could also check with VLC which has its own Matroska implementation instead of relying on libraries like MediaInfo (which I'm guessing Plex is using as well).

**Comment by tholmir** [comment]
I opened it in VLC.
It is reporting it as being in French.
![vlc - ici louis-jose houde - s01e01 - fabienne larouche](https://cloud.githubusercontent.com/assets/10710720/5904584/a837d65c-a557-11e4-9183-268cd28807fd.png)

If I remux the audio track from the mka into the original mkv (and removing the original audio track), the problem is gone. MediaInfo says that the track is in French.
But doing that manually for all my files would take too long.
Do you have an idea for automating all of this?

Thanks a lot for your quick responses.

**Comment by mbunkus** [comment]
mkvmerge is a command-line program that can be used to do anything. All you need is some logic for telling it which files to use. See e.g. https://trac.bunkus.org/wiki/FAQ%3ABatchMuxingWithMMG

**Comment by tholmir** [comment]
Thanks for the info.
I might try something to automate the process.

And I'll try to fill a bug in Plex about the language.
