### ISSUE TITLE
Freeze and Jump after uncheck the Statistics

### ISSUE THREAD

**Issue by Royal-star** [mbunkus/mkvtoolnix#1111]
Wen unchecking  the Source Statistics in mmg(v 7.5.0 64bit) “Tracks, chapters and tags”-Display
And simultaneous adding in the “Add Command line Options” ”Global output control”
The “ --disable-track-statistics-tags “ – Command.
The Video output will in some Cases Jump or freeze but the Audio will continue.

**Comment by mbunkus** [comment]
This sounds like a bug in your player. So please file a bug report with your player. I cannot do anything about this.

**Comment by Royal-star** [comment]
Thank you for the prompt answer Mbunkus
I have try in different Player like VLC/MPC-HC/Potplayer. The same Video output, having the same Issue.

**Comment by Royal-star** [comment]
By the Way a merge with an older Version of mmg  (v6.1.0 Old Devil).Runs without
any issue.

**Comment by mbunkus** [comment]
If you want me to take a look at this then I need files that show the aforementioned behavior. Please upload two files to [https://trac.bunkus.org/wiki/FtpServer](my FTP server): the one before remuxing (the original source file you've used) and the one after having remuxed it with 7.5.0.

**Comment by Royal-star** [comment]
I very appreciate your prompt answer mbunkus and I will collect the needed Footage and send it to the address you have given to me.
Thank you for your Time
