### ISSUE TITLE
Adding audio delay is not a lossless process

### ISSUE THREAD

**Issue by BizkitBoy** [mbunkus/mkvtoolnix#1112]
When adding a delay to an audio track (be it lossless TrueHD/DTS-HD MA or lossy AC3/DTS) the resulted track after muxing is not identical to the original one regarding audio peaks shown in an audio editor (such as Audacity or Sony SoundForge Pro).
For example, I've taken a TrueHD track from a Blu-Ray disc and muxed it video from a different Blu-Ray for the same movie, adding -169ms delay in MKVmerge. Then converted audio track from remux to .w64 and compared it to the one from the original Blu-Ray, also converted to .w64
1. These are audio peaks of the audio track from the Blu-Ray: http://www.imagebam.com/image/b78120386413284
2. These are audio peaks of the audio track from the remux: http://www.imagebam.com/image/6500de386413295
3. Note that trying to set a positive delay for the video track didn't work either, it still messed with the audio: http://www.imagebam.com/image/bca74d386413306
I would also like to note that when applying the negative delay for audio track (printscreen from point 2) it does not apply the correct delay of 169ms, but when applying the positive delay for video track (printscreen from point 3) the delay is correct.
As mentioned in the beginning, this happens for lossy audio tracks too.

What I'm trying to say is that it's not normal for an audio track to differ when adding delay to it.
Audio peaks should be identical, only difference should be regarding delay.

P.S. All this was tested with version 7.5.0

**Comment by mbunkus** [comment]
As Matroska doesn't have a header field for audio delay the only way to adjust audio delay is to drop packets (for negative delay). This is nothing that I will fix.

If you only change the video delay then the audio data is not changed at all. So what you're seeing is either a bug in the program you're using for analysis or it is a user error.

**Comment by BizkitBoy** [comment]
Can you please explain what exactly happens when setting a positive delay for video?
Are there blank frames inserted at the beginning of video track in order to match the delay you want?

**Comment by mbunkus** [comment]
Using any kind of positive delay (no matter the track type) only adds that value to the timecodes. No encoded data is added, changed or removed.

With a negative delay the same thing happens (subtracting the value from the timecodes). The only difference is that all packets/frames whose timecodes end up negative are simply dropped. Even here no existing packets are modified in any way. Obviously this will not work too well with video tracks if the first frame is not a key frame.
