### ISSUE TITLE
Possible bug in Mkvtoolnix v7.5.0

### ISSUE THREAD

**Issue by host47** [mbunkus/mkvtoolnix#1114]
Program version: 7.5.0
Operating system: Windows XP SP3 32 bits

Unexpected result when used the function crop in GUI and also in the command line:

@echo off
cls
for %%a in (*.mkv) do (
	"mkvmerge" --cropping 0:112,2,112,2 "%%~na.mkv" -o output.mkv
	goto END
)
: END

The output video is incorrect.
Crop value chosen for to the left of the video, it is applied in the video right.

Thankful

**Comment by mbunkus** [comment]
This is not a bug in mkvmerge. The cropping values are only stored in the Matroska header; the video track is not modified by this.

If your player applies the »left« cropping on the right side then that's a bug in the player.
