### ISSUE TITLE
Invalid UID error when deleting chapters

### ISSUE THREAD

**Issue by slamdance** [mbunkus/mkvtoolnix#1116]
Since updating from 7.5.0 to version 7.6.0 64-bit on Windows x64, I am experiencing the following behavior:

When loading chapters into the chapter editor, I delete one chapter, and the GUI moves to the next chapter, but all options are grayed out.  Previously all options would be active so I could just delete the next chapter if desired.  To re-enable the options I have to click on another chapter, which prompts this error message:
"Input error: Invalid UID. This chapter UID is already in use. The original UID has not been changed."
![invalid uid](https://cloud.githubusercontent.com/assets/11014563/6202691/2d0ab754-b4f9-11e4-87a9-8f03ac953b63.jpg)
It does not appear to cause any behavior other than the error message.  The error is repeated for each operation as described above. Needless to say the error did not occur in the previous version.

**Comment by mbunkus** [comment]
Most likely due to the new version of the wxWidgets library that 7.6.0 has been built against. Please try the latest build from https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/ which has been built against an older version again (the same one 7.5.0 was built against).

**Comment by slamdance** [comment]
That was a fast reply! I confirm that the later build corrects the error. Thanks!

**Comment by mbunkus** [comment]
You're welcome. I'll add this information to the [FAQ page of known issues](/mbunkus/mkvtoolnix/wiki/Troubleshooting).
