### ISSUE TITLE
Freeze during manage jobs

### ISSUE THREAD

**Issue by JonSnow73** [mbunkus/mkvtoolnix#1117]
In MKV Toolnix 7.6.0 for Mac OS X and in the previous versions too, when using the batch processing in Muxing-> Manage jobs, at the end of a muxing job it's impossible to close the application neither forcing the exit.. the only one way is to make a forced reboot of the entire system.

**Comment by mbunkus** [comment]
I'm sorry, but I don't support Mac OS X. See the [FAQ entry about Mac OS X support](/mbunkus/mkvtoolnix/wiki/Mac-OS-X-support).
