### ISSUE TITLE
mkvpropedit and mmg's header editor incorrectly compute length of EbmlVoid elements, corrupting mkv files

### ISSUE THREAD

**Issue by mbevand** [mbunkus/mkvtoolnix#1121]
I tracked down a bug in mkvtoolnix 7.6.0 where the code miscalculates the length of an EbmlVoid element (off by 1). I encountered the bug when editing an mkv file with mkvpropedit, which leaves the file corrupted (mkvinfo reports "Error in the Matroska file structure...").

How to reproduce the bug:

- I have a test file ("2m.mkv") which is the first 2MB of a full length mkv file. Having the first 2MB is sufficient to demonstrate the bug since mkvpropedit only accesses the first few tens of kB.

- Run "mkvinfo 2m.mkv" to check the file is valid: mkvinfo outputs no error.

- Run "mkvpropedit 2m.mkv --edit track:s1 --set flag-default=0" (this corrupts one of the EbmlVoid elements... more info below)

- Now "mkvinfo 2m.mkv" reports corruption:
  2m.mkv: Error in the Matroska file structure at position 1185. Resyncing to the next level 1 element.
  Resyncing successful at position 4890.

- You can verify the corruption with a hex editor:
  $ xxd 2m.mkv
  [...]
  0000420: 8101 ecfd 0000 0000 0000 0000 0000 0000  ................
  0000430: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  0000440: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  0000450: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  0000460: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  0000470: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  0000480: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  0000490: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  00004a0: 0000 1549 a966 4083 2ad7 b183 0f42 404d  ...I.f@.*....B@M

  At offset 0x423 is the length of an EbmlVoid: 0xfd (variable int encoding for 125). But this is invalid, the length should be 0xfe (126) to match the start of the next element (1549a966 = Segment Information). Changing this single byte from 0xfd to 0xfe fixes the corruption.

In private discussion with mbunkus, he says this is caused by MKVToolNix miscalculating how many bytes are used by the variable-length integer encoding the length of EbmlVoid elements.

**Comment by mbevand** [comment]
According to mbunkus, this bug is triggered only in certain edge cases, for example when processing Matroska files that result in EbmlVoid elements having a length value that switches from 127 to 128 (or vice versa), the total size of the EbmlVoid changes from 129 (1(id)+1(len)+127(data)) to 131 (1(id)+2(len)+128(data)) bytes. In order to encode an EbmlVoid element of exactly 130 bytes total, one would have to use a length value of 127 but encoded as 2 bytes instead of 1 byte, and I guess the code does not take such edge cases into account.

**Comment by mbunkus** [comment]
Fixed in 8d78387b09f76143b0425af01ca30370a9c92618.
