### ISSUE TITLE
Padding missing when extracting PCM data with mkvextract

### ISSUE THREAD

**Issue by matsp888** [mbunkus/mkvtoolnix#1122]
When extracting a track with PCM data to RIFF WAVE format, as in "mkvextract tracks file.mkv 0:file.wav", if a chunk is an uneven number of bytes, it should be padded with a zero byte. From "Multimedia Programming Interface and Data Specifications" by IBM and Microsoft: "If the chunk size is an odd number of bytes, a pad byte with value zero is written after ckData." Note that this does NOT affect the ckSize field in the chunk header, since if it did, it would be impossible to know whether the actual data is an even or odd number of bytes.

**Comment by mbunkus** [comment]
It's highly unlike that I'll ever get the motivation to fix this. Sorry.

**Comment by matsp888** [comment]
Moritz Bunkus <notifications@github.com> skrev: (4 juni 2016 16:02:10 CEST)
>It's highly unlike that I'll ever get the motivation to fix this.
>Sorry.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mbunkus/mkvtoolnix/issues/1122#issuecomment-223757261

Long time no see. Well, it's an elementary thing that should be correct and ought to be pretty easy to fix. Never mind then.

Mats
-- 
Mats Peterson
http://matsp888.no-ip.org/~mats/
