### ISSUE TITLE
Bits per pixel in extracted AVIs with 8 bpp video data incorrectly set to 24

### ISSUE THREAD

**Issue by matsp888** [mbunkus/mkvtoolnix#1123]
When extracting the video track from a Matroska file with V_MS/VFW/FOURCC codec ID and 8 bpp video data, the biBitCount member of the BITMAPINFOHEADER in the 'strf' stream format chunk in the produced AVI file is incorrectly set to 24 instead of 8. Not the highest priority, I gather, but it should work in my book, without having to resort to using mencoder or something else for this. I managed to make it work by changing the bpp in the AVI with a hex editor, so I know this is the problem.

**Comment by mbunkus** [comment]
With `V_MS/VFW/FOURCC` video tracks the BITMAPINFOHEADER is contained in the Codec Private element. All mkvextract does is copying that structure into the AVI file. The fields aren't modified. So if the bit count field is wrong after extraction then it has already been wrong inside the Matroska file.

The analog argument can be made about mkvmerge; it copies the BITMAPINFOHEADER 1:1 into the Codec Private element and doesn't modify it.

Additionally there's no color bit depth header field in Matroska that mkvextract could use for correcting that field in the first place.

So this is not a bug in mkvextract, nor in mkvmerge.

**Comment by matsp888** [comment]
That was a bit quick, wasn't it. Take a look at the byte at offset 0x0e of the private data (i.e. the BITMAPHEADER structure) in the attached file. It is the biBitCount member, and it is 0x08 for this 8 bpp file as expected. No problem. But it will be 0x18 in the saved AVI file, so something is definitely happening when mkvextract is saving it, Moritz. I wouldn't write about this if I wasn't totally sure of it.
Mats
-- 
Mats Peterson
http://matsp888.no-ip.org/~mats/

**Comment by matsp888** [comment]
I think I've found the problem. It seems like the bpp is hardcoded to 24 in lib/avilib-0.6.10/avilib.c. At line 900:

OUTSHRT(1); OUTSHRT(24);     /* Planes, Count */

So in conclusion, the BITMAPINFOHEADER is NOT copied 1:1 to the AVI file when saving it.

**Comment by mbunkus** [comment]
You're right; my recollection of mkvextract's source code was wrong. Only the private codec data located after the `BITMAPINFOHEADER` structure is copied 1:1. avilib doesn't provide a function for using an existing `BITMAPINFOHEADER` directly.

If you want you can provide a patch that fixes this: add a function to avilib that allows the caller to specify the bit depth; fix avilib's initialization to store 24 as the default value for the bit depth; modify avilib to write the given bit depth and not the hard coded value; modify mkvextract to call that new function with the value from the `BITMAPINFOHEADER` in Codec Private. The same should probably be done for the other fields (`planes`, `size_image`, `x_pels_per_meter`, `y_pels_per_meter`, `clr_used`, `clr_important). Or simply implement a function in avilib that allows the caller to provide the whole `BITMAPINFOHEADER`.

I don't consider this issue a high priority.

**Comment by matsp888** [comment]
Well, I know this isn't high priority, but I'm at least glad that you have aknowledged the problem. I don't feel 100% confident in making a patch, since I don't want to break things.

Mats
 -- 
Mats Peterson
http://matsp888.no-ip.org/~mats/

**Comment by matsp888** [comment]
It wasn't too hard to fix. I've sent patches for the relevant files to you.

**Comment by mbunkus** [comment]
Thanks again for the patches. I've applied them, fixed a couple of style issues, added a test case, added entries to AUTHORS and ChangeLog in your name and committed everything naming you as the author.

**Comment by matsp888** [comment]
Thanks Moritz. Regarding the style issues, I normally don't write stuff like "width*height*(AVi->bpp>>3)" but I thought I should match the rest a bit ;) Not that it's very readable. One would have to fix more things in that file regarding readability. Anyway, I have a new little patch and some questions on the way. More later.
Mats
 -- 
Mats Peterson
http://matsp888.no-ip.org/~mats/
