### ISSUE TITLE
Backward Spliting not supported

### ISSUE THREAD

**Issue by snowflaxgit** [mbunkus/mkvtoolnix#1125]
Hi,

I tried this:-
mkvmerge -o new_file.ogg --split parts:0s-104s,+94s-208s,+8s-12s,+312s-410s,+17s-21s 500.ogg

Thrown this error: "The start time must be bigger than or equal to the previous part's end time"
because 94<104
I see in code backward spliting point not allowed.
if (!requested_split_points.empty() && (start < std::get<1>(requested_split_points.back()))) {
      if (frames_fields)
        throw format_x{boost::format(Y("Invalid start frame/field number for '--split' in '--split %1%' (current part: %2%). The start number must be bigger than or equal to the previous part's end number.\n")) % arg % part_spec};
      else
        throw format_x{boost::format(Y("Invalid start time for '--split' in '--split %1%' (current part: %2%). The start time must be bigger than or equal to the previous part's end time.\n")) % arg % part_spec};
    }

Can you please guide how to split randomly in entire stream. I want to split some portion backward , some upward, anywhere random between stream anytime..

Does it possible?

**Comment by mbunkus** [comment]
No, sorry. mkvmerge processes the content exactly once and can therefore write one section into one output file only. There's no way to go back and write that part to somewhere else, too.
