### ISSUE TITLE
mkvmerge doesn't recognize an E-AC3 (DD+) track in MPEG transport stream

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1126]
Hi Mosu!

I'm using MKVToolNix v.7.6.0 (pre-build version: build20150215-660-bfa01eb-setup). 

First of all: I'm not sure if this is a bug or not — I suspect you (probably) haven't added support for that so far.....

All right: one of my many movies on BD (»Transformers«, 2007, CEE release) contains 8 audio tracks. One of them is an E-AC3 (Dolby Digital Plus) that isn't recognized by mkvmerge at all. 

Here you can see that MPC recognizes correctly 8 audio tracks: 
![mpc 8 audio tracks](https://cloud.githubusercontent.com/assets/10992208/6332154/fbac38f4-bb83-11e4-833f-911f293692f7.png)

Second screenshot shows you only 7 audio tracks which are recognized by mkvmerge (E-AC3 track isn't recognized!): 
![mkvmerge recognizes only 7 audio tracks](https://cloud.githubusercontent.com/assets/10992208/6332278/834fab38-bb84-11e4-8767-754d25d8dba6.png)

To be absolutely sure that mkvmerge doesn't recognize the E-AC3 track, I had decided to extract it using tsMuxeR and then I added that track to mmg. The result is: 
![mkvmerge no tracks found](https://cloud.githubusercontent.com/assets/10992208/6332391/45172e8a-bb85-11e4-8d3e-dab72111fc60.png)

It is important to note that tsMuxeR doesn't have any problem to recognize that track correctly:
![tsmuxer](https://cloud.githubusercontent.com/assets/10992208/6332437/b443bba2-bb85-11e4-9960-e0de1f01962d.png)
Only mkvmerge has a problem.

Summarizing: 

1) What do you need to reproduce this issue? Should I upload full BD structure (43GB :D) or a raw (.m2ts) stream only? I think that the raw stream will be enough for you unless you want something much bigger :)
2) Can I count on you to get it fixed for the next (7.7.0) release, please? I know that it's not major, but would be very nice to fix it quickly. Currenty I cannot create an .mkv file with DD+ track from MPEG TS.
3) Could you confirm please if this is a bug or not? Is it possible that you didn't implement support for E-AC3 tracks in MPEG TS in the past? If so: I'm really surprised because of it ☺. I didn't expect that mkvmerge may have a problem with the DD+ tracks. If you want, you can treat that issue as »feature request« ☺.

Thank you for your help and regards!

**Comment by mbunkus** [comment]
mkvmerge does support EAC3 in MPEG TS. If such a track is not recognized then that may be a bug. Please upload a sample file; the M2TS will suffice.

I don't make any promises if or when I will fix this. I cannot even tell yet if it's a bug in the first place.

**Comment by remuxer32** [comment]
A sample file has just been uploaded to your FTP. Good luck.

**Comment by mbunkus** [comment]
Thanks for the sample. This does indeed look like a bug.

**Comment by mbunkus** [comment]
A new [pre-build](https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/) including the fix has been uploaded (build number 668).

**Comment by remuxer32** [comment]
Thank you for a quick fix, but build number 668 is 64-bit version. I use Windows 32-bit so it's not for me. Could you create a new (32-bit) build for me? Thank you.

**Comment by mbunkus** [comment]
Already done & uploaded.

**Comment by remuxer32** [comment]
Thanks for the upload. I've just checked that track — everything works great :)
