### ISSUE TITLE
feature request: support for .WMV files [Windows Media (ASF/WMV)]

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1127]
http://en.wikipedia.org/wiki/Windows_Media_Video

I noticed that mkvmerge doesn't support .WMV files:
![default wmv file](https://cloud.githubusercontent.com/assets/10992208/6334237/bce6f496-bb93-11e4-8c4a-d5f817d1e7f3.png)

Maybe would you like to implement support for that in the far future, please? As always, I offer you my help: If you don't have any .WMV files then I can upload them to your FTP. I know that .WMV files are not popular, but in the past you added support for formats which are also not popular (e.g. LPCM tracks which are not supported on BDs currently, because DTS-HD MA & Dolby TrueHD won the »competition«). I realize that there are many versions of .WMV files (e.g. v7, v8, v9), but it shouldn't be difficult for me to find various .WMV files and upload them for you.

Thank you.

**Comment by mbunkus** [comment]
No, sorry. I've long ago decided not to support WMV.

**Comment by remuxer32** [comment]
Okay, but could you explain me please your intention to not to support WMV? I know they are rare, but there are people who use WMV files. Just I would like to know your point of view.

**Comment by mbunkus** [comment]
They were much more common ten years ago. I also disliked how MS used to come down hard on programs that implemented WMV support. I also don't have an endless amount of time to spend.

**Comment by remuxer32** [comment]
Thank you for your explanation. BTW: Microsoft decided to implement support for .mkv files and HEVC only now (Windows 10) :D Our companions from MS are really »fast« :):)
