### ISSUE TITLE
avilib: Incorrect 'strf' chunk size handling in extracted AVI files

### ISSUE THREAD

**Issue by matsp888** [mbunkus/mkvtoolnix#1128]
The chunk size output at lines 897 and 1357 in avilib.c shouldn't be "40 + xd_size_align2", but "40 + xd_size", since once again, the padding byte shouldn't be included in the chunk size field of the chunk header. I've sent a patch to you.

**Comment by mbunkus** [comment]
Thanks for the patch. I've applied it.

**Comment by matsp888** [comment]
Thanks, Moritz.
