### ISSUE TITLE
avilib: Should be able to read all the relevant data in the 'strf' chunk

### ISSUE THREAD

**Issue by matsp888** [mbunkus/mkvtoolnix#1129]
In avilib.c, the number of bytes read from the 'strf' chunk is so far only what's in the biSize member of the BITMAPINFOHEADER (BIH) structure. It should use the 'strf' chunk size if biSize is not greater than the size of the BIH. It's really against the specs to put anything else than the size of the BIH in its biSize member, but it seems common practice to do so nowadays. In spite of that, older files that adhere more closely to the specs only have the BIH size in its biSize member, regardless of any extra data following the BIH (like the palette for 8 bpp video data), so one will have to use the 'strf' chunk size to read this extra data . I will send you a patch that fixes this. Please consider applying it.

**Comment by mbunkus** [comment]
Thanks for the patch. I've applied it.

**Comment by matsp888** [comment]
Thanks, Moritz.
