### ISSUE TITLE
feature request: one button to deselect and select (turn off & turn on) all tracks

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1130]
This is probably one of the most important and useful features that you can implement in the new GUI (well, if you want, you could also add that option in the old GUI, but I know that you don't want to support it anymore). What do I mean? Just look here:  
![tsmuxer](https://cloud.githubusercontent.com/assets/10992208/6375134/7219c078-bd15-11e4-8271-003701a9de5b.png)

Yes, I would like to choose »via one click« if all tracks are selected or deselected. Believe me: it's really annoying and painful for me and other users when we have to every time to mark off manually each of one of the unnecessary tracks; especially when a file contains massive audio tracks and subtitles (look here, it's horrible: http://poral.eu/robocop_1987.php <====== plenty of tracks!).

Please, don't reject my request. Think about it fully. You could make our work much faster and easier. 

Thank you for your agreement and regards!

**Comment by remuxer32** [comment]
7.7.0 milestone? Fantastic! Does it mean that you will implement it in the old GUI too? Oh, thank you very much Mosu! I'm truly grateful for that. Cheers!

**Comment by mbunkus** [comment]
Yes, I'm planning on adding it in the old GUI for the next release. It'll most likely be a button on the right below the »up« and »down« buttons.

**Comment by mbunkus** [comment]
Implemented. I will create new [pre-builds](https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/) and upload them as soon as they're ready. The build numbers will be 674 and higher.
