### ISSUE TITLE
feature request: nice sound when muxing is finished

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1131]
My next idea is to implement a nice sound when muxing process is finished. As we know the muxing process may take even 2 or 3 hours (it depends on how many files you are going to mux etc.). Because of a fact that many people are busy (e.g. making coffee, sleeping, watching movies, playing etc.), I propose you to add something like an »alert« (it may be long and loud) that will inform the users about completed process. Of course that option shouldn't be forced; just individual choice. You could add that feature to the »options«. Note that there are programs which contain such a feature (e.g. tsMuxeR and its »magic« sound) so my request isn't »weird«. I will be very glad if you agree with my point of view.

Thank you and regards!

**Comment by mbunkus** [comment]
No, sorry. Sound effects is something I long ago decided not to implement.
