### ISSUE TITLE
mkvinfo GUI doesn't have *.webm in the open file dialog

### ISSUE THREAD

**Issue by robUx4** [mbunkus/mkvtoolnix#1133]
Although it's supported.

**Comment by mbunkus** [comment]
This has already been fixed in 6ae9df2b2842d11590116634bd10d7073f6e14e8.

**Comment by mbunkus** [comment]
That was the day you reported it on IRC. I just forgot to tell you that I had done it already :)

**Comment by robUx4** [comment]
Perfect :)
