### ISSUE TITLE
mkvtoolnix this application has requested the Runtime to terminate it in an unusual way

### ISSUE THREAD

**Issue by Caradecuica** [mbunkus/mkvtoolnix#1135]
Hello,
I was using mkvtoolnix for some time without any problem, until yesterday. I finished muxing a video with subtitles and when tried to do the same process with another video, started receiving the message "This application has requested the Runtime to terminate it in an unusual way". 
I tried to uninstall and reinstall, but the problem persists. I also tried to restore my computer, but wasn't able to do so.
I use Windows 7 professional ed with 16GB memory.
My program is on drive C. I have access to c:\USER. 
Thanks for your time.

**Comment by mbunkus** [comment]
Which program crashes in that way? Which exe are you running?

**Comment by Caradecuica** [comment]
MKVToolNix-GUI.exe

**Comment by remuxer32** [comment]
Hmmm, I suspect that it's something like this:
![mkvtoolnix gui](https://cloud.githubusercontent.com/assets/10992208/6428600/b8b40e6c-bfa9-11e4-8693-79e30c4fab17.png)

What have I done? I have moved one track up using left key of my mouse (it doesn't matter which track you move; you can move it up or down — you will always see such error).

Ah, something else you should see:
![mkvtoolnix gui 2](https://cloud.githubusercontent.com/assets/10992208/6428707/7a716724-bfab-11e4-9331-8751d4446d89.png)

Yes, it's definitely a serious issue.

**Comment by Caradecuica** [comment]
Yes, the message is the same, but I'm not able even to open the program. 
It stops before.

**Comment by remuxer32** [comment]
In my case I can open easily the program, but when I want to move any track up or down then I see such errors; when I click »OK« the program is closed of course. My system is Windows 7 Ultimate 32-bit.

**Comment by Caradecuica** [comment]
The strange in this case is that everything was working fine and then, error. No Windows update in between, nothing. I finished one video and when started the other, and booom!

**Comment by mbunkus** [comment]
Don't use mkvtoolnix-gui.exe. The dialog box shown when you start that exe states pretty clearly that it is a preview version of an incomplete re-write of the existing GUI, mmg.exe. It is most definitely NOT meant for every day use yet. I also don't accept bug reports about it yet.

See https://github.com/mbunkus/mkvtoolnix/wiki/MKVToolNix-GUI-status

**Comment by markv80** [comment]
Just for the record. The same error happened to me when I tried to add an attachment (a .jpg cover).
I discovered that what the cause was the an accent in the folder's name where I've installed MKVTollNix.
Removing that accent in the folder's name worked fine.
