### ISSUE TITLE
Audio desync when converting to mkv

### ISSUE THREAD

**Issue by HappyCerberus** [mbunkus/mkvtoolnix#1136]
I get this error on some tracks: "This MPEG audio track contains 384 bytes of non-MP3 data at the beginning. This corresponds to a delay of 504ms. This delay will be used instead of the garbage data."

Unfortunately this desynchronizes the audio (by 504ms). I cannot find any way to prevent this behaviour.

**Comment by mbunkus** [comment]
Use the sync option (on the command line: `--sync …`; in the GUI: the input box labeled »Delay (in ms)«).

**Comment by HappyCerberus** [comment]
Yeah, that options is completely ignored. The audio still ends up shifted by the same amount.
