### ISSUE TITLE
Audio desync when converting to mkv

### ISSUE THREAD

**Issue by HappyCerberus** [mbunkus/mkvtoolnix#1137]
I get this error on some tracks: "This MPEG audio track contains 384 bytes of non-MP3 data at the beginning. This corresponds to a delay of 504ms. This delay will be used instead of the garbage data."

Unfortunately this desynchronizes the audio (by 504ms). I cannot find any way to prevent this behaviour as both the `--sync` and gui option are ignored.

Command I'm using:
`mkvmerge -o file.mkv file.avi --default-language cze --sync 1:0,1.0`

**Comment by mbunkus** [comment]
Please don't open multiple tickets for the same issue.

The order of the command line options you're using is wrong, BTW. Track-specific options like -`-sync` apply to the following input file.

See https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvmerge.html#mkvmerge.option_order

**Comment by HappyCerberus** [comment]
Christ, than don't close it immediately as invalid without giving me a chance to respond. This is ridiculous.

And as I said, both the GUI and the command line option is ignored.

And this command:
`mkvmerge -o file.mkv  --sync 1:0,1.0 file.avi --default-language cze`

Produces the same exact problem.

**Comment by mbunkus** [comment]
You can simply respond to the closed issue like you've done here. I will reopen a ticket if it turns out that I was wrong.

This doesn't apply in this case yet, though, because the values you've used on the command line are basically a no-op. Look for the description of [--sync in the docs](https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvmerge.html) and you'll see that you've used `0` as the value for the parameter `d` (the fixed displacement; 0 resulting in no change at all) and 1.0 for the parameter `o` (the linear drift; with 1.0 meaning that all timecodes will be multiplied by 1.0 – not changing anything).

You could try something like `--sync 1:1000` (1000 meaning 1000ms meaning one second of adjustment).

**Comment by HappyCerberus** [comment]
At least please read what my problem is before you dismiss it. All of your responses are completely unrelated.

Again, the problem is that the audio gets desynchronized and I want to prevent that. The correct values are `0:1.0`. The problem is that mkvmerge automatically decides that `0:1.0` isn't correct and shifts the audio by 504ms. I want to prevent this, because this desynchronizes the audio.

**Comment by mbunkus** [comment]
mkvmerge has no magical switch »always do the right thing«. Sometimes mkvmerge's interpreation of the relative audio/video timecodes is not what the user expects. That's why the options I'm talking about exist; they allow you to fix that.

Try `--sync 1:504` (or `--sync 1:-504` depending on which way they're shifted against).

**Comment by HappyCerberus** [comment]
Well. OK. `--sync 1:-504` actually works.

However this is extremely fiddly as this option now depends on a specific file and needs to be tuned on a file-per-file basis.

If I specify sync it should mean exactly what I specify in the option (i.e. no offset in my case), not what I specify plus some magic number mkvmerge decides on file-per-file basis.

**Comment by mbunkus** [comment]
In general mkvmerge keeps sync out of the box. There are cases (e.g. in which the source file is damaged, contains unrecognized garbage) where mkvmerge gets this wrong, and that's what the `--sync` option is there for.

You won't need to specify `--sync` for the vast majority of files. Keeping A/V synchronized automatically if at all possible is already the default.

**Comment by HappyCerberus** [comment]
Well, that's the problem. I don't want the automation because it breaks my files. That's what my initial issue was. The automation is desynchronizing my correctly synchronized files and there is no way to prevent this.

**Comment by mbunkus** [comment]
It's not a choice of enabling or disabling anything. Frames in Matroska files require timestamps. AVI files do not have timestamps, therefore mkvmerge has to calculate them, deriving them from the data in the source file. You cannot turn that off; it's simply not how Matroska works.

**Comment by HappyCerberus** [comment]
But there is clearly some algorithm calculating the time offset. There simply needs to be way to override the calculation (not offset it back, because then you need the result of the calculation in the first place).

I'm pretty sure that in my case I have files that have garbage on the beginning of the audio track, but this garbage is correctly skipped over by all video players and simply ignored. Mkvmerge deduces that this garbage mandates a time shift in the track (which is incorrect in this case).

**Comment by mbunkus** [comment]
Alright, I'll take a look at your file if you upload it to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server).

**Comment by mbunkus** [comment]
Note that prefixing audio tracks with garbage is the only way of adjust audio/video sync inside AVI files (there are no timecodes, nor are there header values with some kind of adjustment). Garbage has been used like that for over 15 years (well, that's as long as I can remember anyway). That's why mkvmerge calculates the intended offset, just like a video player does.

**Comment by HappyCerberus** [comment]
I'm not disputing that. However there is certainly some disparity in how media players and mkvmerge handles this case. And the currently available flags for mkvmerge don't allow a one-pass conversion of such files.

The file is there (happy-cerberus-testfile.avi).

**Comment by mbunkus** [comment]
Thanks for the sample. mkvmerge does indeed seem to do something wrong here. I will look into how to fix this.

**Comment by mbunkus** [comment]
The first of the two changes fixes the formula used for calculating the delay. For your file the new (and most likely correct) delay that mkvmerge calculates is 24ms.This seems to be correct for your file; other tools like ffmpeg and formulas around the internet about this topic arrive at the same value for the amount of garbage and the codec involved.

The second change implements an option for turning this calculation off entirely.

Having a delay of 24ms or one of 0ms ( = no delay) is an amount that humans can often not distinguish. Watching both variants the variant that keeps the 24ms delay seems (!) to be just a tad bit better in sync – but like I said, this is near the threshold for where humans can notice a delay. So your impression may be different.

**Comment by HappyCerberus** [comment]
Awesome, thanks.

**Comment by mbunkus** [comment]
You're welcome. Thanks for reporting the issue and providing the information + the file.

**Comment by spider-borg** [comment]
I'm having a similar issue while using mkvtoolnix gui (also mkvmerge gui).  Is this something that has to be done through the command line or is it an option that I'm just not seeing or understanding? 

Forgive me, I know nothing about using the command line.  If using the command line is required to mux my avi into an mkv without causing audio sync problems, could you please type out a step by step instruction on what to do?  Sorry for being a noob :)

**Comment by aprilia1k** [comment]
I realize that some may view this as inappropriate, but I felt a need to comment.  
Although there were some early communication issues in this thread - the level of assistance, the explanations and the follow-up - including a commit that corrected a new problem detected - exhibited by mbunkus is simply outstanding.  There are thousands of corporate support groups that could learn from this example of pure helpfulness.  KUDOS to you.  I've worked dev and support/bugfix-engineering in some pretty big companies - and THIS is how it should be done.
