### ISSUE TITLE
Split mode problem

### ISSUE THREAD

**Issue by starlight-tu** [mbunkus/mkvtoolnix#1138]
It never splits exact time I command. For example, I have a video file with 20 minutes length. I use **split by parts based on timecodes** with the timecode part look like this ***00:10:00-00:11:00**. As you can see, the new length video's supposed to be 1 minutes (*60 seconds*). However, it only has *54 seconds*. I try splitting into many timecode parts, but seem like it always **lose** or **extra** a **few second**.
I'm using **version 7.7** (Six Voices) in *UI mode*.

Can you fix it? Please?

**Comment by mbunkus** [comment]
This is a conscious design decision. Please see [this FAQ  entry](https://github.com/mbunkus/mkvtoolnix/wiki/Splitting-imprecise).
