### ISSUE TITLE
8 channel audio lost

### ISSUE THREAD

**Issue by bradycl** [mbunkus/mkvtoolnix#1139]
Using makemkv 1.9.1 and mkvtoolnix 7.70 on Fedora 20.

If I extract just the video and 7.1 DTS-HD audio from my blu-ray, I get a file that reads as follows from mkvinfo:
| + A track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 2
|  + Track type: audio
|  + Default flag: 1
|  + Lacing flag: 1
|  + Codec ID: A_DTS
|  + Language: eng
|  + Default duration: 10.667ms (93.750 frames/fields per second for a video track)
|  + Name: Surround 7.1
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 8
|   + Bit depth: 24

But if I then run that audio track through mkvmerge, I lose 7.1 audio.
If I run mkvmerge, simply add the file and click start muxing, the resulting file shows the following:
| + A track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 2
|  + Track type: audio
|  + Codec ID: A_DTS
|  + Default duration: 10.667ms (93.750 frames/fields per second for a video track)
|  + Name: Surround 7.1
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 6

XBMC reads the first file as having 7.1 audio, the second as 5.1.

Is this expected behavior?  If it is, I'm curious what the issues are?

If not, let me know how I can help troubleshoot!

**Comment by vidarak** [comment]
I think I've seen this too... but my receiver decodes it like 7.1 still from what I remember.
A bit annoying to see Kodi details telling it is 5.1 though :)

**Comment by mbunkus** [comment]
I will need a sample file in order to fix it. Please upload one to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server) (preferably into a folder called `issue-1139`). Thanks.

**Comment by bradycl** [comment]
When I get home tonight I'll see if I can figure out how to make a small
enough file with the 8 channel audio included to upload.

Thanks!

**Comment by bradycl** [comment]
Small issue.  MakeMKV will not extract clips, only entire titles, and
doesn't compress.  So to get you a sample mkv with 8-channel audio still
included, it would be in the neighborhood of 25-30GB.

I don't mind uploading, although it will take several days, but I don't
know if you want me to do that?

Alternatively I could send you one of the smaller .m2ts files from the same
blu-ray that has 8-ch audio.  (135MB or so) Running it directly through
mkvtoolnix also results in a 6-channel DTS track as reported by mkvinfo
instead of an 8-channel.  Would this be preferred?

**Comment by bradycl** [comment]
Okay, I managed to find a 1GB clip.  However, I am getting connection
refused attempting to connect to connect to ftp.bunkus.org via either ftp
or sftp.  Please advise when the ftp server is up and I will upload the
clip.

Thanks!

**Comment by mbunkus** [comment]
The server should be up again. Sorry for that.

The file in question wouldn't have to be too long. You should even be able to split a m2ts file down into smaller parts (e.g. 100 MB) and run MakeMKV against the very first 100 MB part only.

**Comment by bradycl** [comment]
Thank you!

I've uploaded 2 files:
Test_Clip.mkv is an mkv with 8-channel DTS-MA
Test_Clip_2.mkv is an m2ts also with 8-channel DTS-MA

Both process through mkvmerge 7.70 on my Fedora 20 server (and my Fedora 21
laptop) to result in mkv files that report only 6-channel audio.

Please let me know if I can assist further!

**Comment by mbunkus** [comment]
Interestingly ffmpeg reports the DTS audio to be 5.1 channels as well (after extracting the DTS tracks from the Matroska file). Looks like ffmpeg doesn't count the extra channels contained in the Master Audio extensions. I'm not sure what the right thing to do would actually be in such a case.

**Comment by bradycl** [comment]
It looks like ffprobe only reports what is in the core because that is all
ffmpeg can decode/transcode, regardless of the fact that if you do ffmpeg
-acodec copy, you should still be getting the full 7.1 stream in your
output.

Short of ffmpeg fixing this upstream (which I'm not holding my breath for,
since people seem to have been asking about this since 2009), could you
allow the expert, in a case where he/she knows that the track is 7.1 (for
instance when I am mkvmerging it into an .mkv file from the original .mpls
from a blu-ray that I know is 7.1), to specify that the number of channels
on the resulting track will be 8 or does that just open too many
potentially bad cans of worms?

**Comment by mbunkus** [comment]
I'm not a big fan of providing such an option. mkvmerge already contains a plethora of options, and people are rightfully complaining about the complexity of it all.

You can definitely use mmg's header editor of mkvpropedit in order to change the channels element for such tracks after muxing. This is a workaround that you can use right now.

I haven't decided yet how to resolve this. It's quite possible that I will add parsing the extensions for this information. Parsing the extensions to some extent is already required by another feature request (#1109) anyway.

If I decide to do this I will probably not implement it in time for the next release, though.

**Comment by mbunkus** [comment]
The actual patch is very small, but it's only so small because all of the refactoring and all of the new HD extension parser code has been committed in separate revisions prior to this one. Meaning no, it wasn't trivial to fix, but it's done now.

**Comment by bradycl** [comment]
This will be in place in 7.8 then?  :-D

**Comment by mbunkus** [comment]
Sure.
