### ISSUE TITLE
mkvextract with VOBSUB: filenameissue

### ISSUE THREAD

**Issue by ursau** [mbunkus/mkvtoolnix#1140]
Hi,

with v7.7.0 on a debian wheezy system I have the following issue:

    $ mkvextract -V
    mkvextract v7.7.0 ('Six Voices') 32bit gebaut am Mar  1 2015 01:00:22
    $ mkvextract tracks test.mkv 5:test_05
    Die Spur 5 mit der CodecID »S_VOBSUB« wird in die Datei »test_05« extrahiert. Container-Format: VobSubs
    Die VobSub-Index-Datei »test_05« wird geschrieben.
    Fortschritt: 100%
    $ ls
    test_05  test.mkv
    $ rm test_05 
    $ mkvextract tracks test.mkv 5:test_05.sub
    Die Spur 5 mit der CodecID »S_VOBSUB« wird in die Datei »test_05.sub« extrahiert. Container-Format: VobSubs
    Die VobSub-Index-Datei »test_05« wird geschrieben.
    Fortschritt: 100%
    $ ls
    test_05  test.mkv

The file `test_05` contains the index. No other file is created by `mkvextract`. With v6.7.0 on another system two files `test_05.idx` and `test_05.sub` are created (as expected).

Thanks!

**Comment by mbunkus** [comment]
Thanks for the report. I cannot reproduce it on my Arch Linux development system, but I can reproduce it on Debian wheezy. Therefore it looks like the Boost::Filesystem library mkvextract uses for file name manipulation has changed significantly in this regard.

**Comment by mbunkus** [comment]
Yep, this is due to a bug in Boost: https://svn.boost.org/trac/boost/ticket/5118

**Comment by ursau** [comment]
Thanks a lot, for the very fast fix!
