### ISSUE TITLE
Can't tag webm files with mkvmerge

### ISSUE THREAD

**Issue by leni536** [mbunkus/mkvtoolnix#1143]
I get the following error when I try add tags to webm files:

> Warning: Tags are not allowed in WebM compliant files. No tags will be written into any output file.

This is the same warning whenever I use --tags or --global tags. However AFAIK that "Tags are not allowed in WebM compliant files" is not true: http://www.webmproject.org/docs/container/#tagging

**Comment by mbunkus** [comment]
I wasn't aware that WebM allows tags now. Hasn't always been the case.
