### ISSUE TITLE
[Feature request] Chapter generator from appended medias in mmg

### ISSUE THREAD

**Issue by kobayashison** [mbunkus/mkvtoolnix#1144]
I think mka would be the perfect format for audiobooks (since it supports chapters, "subtitles"...).
I tried to do an audiobook in mka format concatenating a bunch of mp3, one per chapter. It would be nice to have a button/menù item (maybe in the Chapter Editor or the main view) to generate a chapter list from the list of concatenated files. Maybe using the titles of the names of the files.

**Comment by mbunkus** [comment]
The thing is that mkvmerge's internal routines for handling appending of files are pretty hard to predict from the outside. First of all, mmg would have to know the total duration of each appended track in advance. Second command-line parameters like `--sync` or `--timecodes` have great influence over the actual timecodes when files will be appended as well. And the list goes on and on.

The gist is that it's practically impossible to predict the timecodes. They're only known the moment a file is actually appended (when mkvmerge does its work). It may work for very simple constellations, but I will not implement a feature that works correctly only under the best circumstances.

Therefore I will not implement such a feature.

**Comment by kobayashison** [comment]
Thanks for the answer.
Maybe would be possible to add an option in mkvmerge to create automatically the chapter list, since it knows the timecodes?
