### ISSUE TITLE
Remuxing an MPEG2/AC3 VOB from a DVD using mkvmerge ends up with blank video

### ISSUE THREAD

**Issue by dvds** [mbunkus/mkvtoolnix#1145]
**Description**
As the title, when I try to remux a vob extracted from a DVD (using mplayer -dumpstream) using mkvmerge then the resulting mkv file seems to have a video stream that is just blank. This is most obvious as the mkv file is much smaller in size than the vob file.

I have uploaded a cut-down vob which is 10 seconds long to the FTP server, along with the output mkv file.

**mkvmerge version:**
mkvmerge v7.7.0 ('Six Voices') 64bit built on Mar  1 2015 02:30:06

**Operating System:**
Ubuntu 14.04 (Linux N4030 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux)

**mkvmerge command line:**
mkvmerge --output TB.en.10s.mkv --no-audio --default-track 0:1 TB.en.10s.vob --no-video --language 1:en --default-track 1:1 TB.en.10s.vob

**Expected result:**
An mkv containing both unchanged video and audio streams from the vob.

**Actual result:**
Audio stream seems to be fine, but video stream is just blank.

**Comment by mbunkus** [comment]
You're most likely stumbling across a known bug in the MPEG 1/2 video handling code. Unfortunately  earlier investigations have shown that fixing this bug would require almost a complete re-write of the MPEG 1/2 video handling code. This is something that has zero priority for me, and I have long ago decided not to invest any time into such an endavour. Meaning: I won't fix this bug.

In your case you should be able to use the [vobcopy tool](http://vobcopy.org/) for ripping DVDs.

**Comment by dvds** [comment]
Thanks for looking at this all the same. I wasn't sure if this was an issue with mkvmerge or a badly mastered (or somehow copy-protected) MPEG2-PS file TBH.

However, through some tinkering I have discovered that by removing the first 2.04 seconds (51 frames) of the vob produces a new vob that will remux without issue in mkvmerge.

e.g.
avconv -i TB.en.vob -ss 2.04 -map 0:v -c:v copy -map 0:a -c:a copy TB.en.trimmed.vob

At this point I am inclined to blame the particular vob file rather than mkvmerge, as this is the first time I have encountered this particular issue.

**Comment by mbunkus** [comment]
It's quite possible that this has been fixed. Unfortunately I don't have the same file anymore that you've uploaded, therefore I cannot verify it myself. If you want to give it a try you can [create an Ubuntu package from git](https://www.bunkus.org/videotools/mkvtoolnix/source.html#debian_ubuntu_package) yourself.

**Comment by dvds** [comment]
Thanks for reopening this issue and committing a fix.

I've followed the detailed instructions you've provided for building a deb file but am unable to get a package to build. The last few lines are as follows:

```
     CXX src/common/dts.cpp
     CXX src/common/version.cpp
     CXX src/common/extern_data.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[1]: *** [override_dh_auto_configure] Error 4
make[1]: Leaving directory `/home/dvds/mkvtoolnix-git'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

I had to install package libboost-date-time-dev in addition to the other dependencies, but I must be missing something else in order to get it compiled and packaged.

If you have any ideas about what I might be doing wrong then please let me know. Otherwise I will just have to wait until 7.9.0 is released and update via apt.

Thanks again for you continued support.

**Comment by mbunkus** [comment]
Well, an »internal compiler error« pretty much always means either a bug in gcc or a hardware issue on your side. You're probably not doing anything wrong.

**Comment by mbunkus** [comment]
I've just released v7.9.0. Like I said it should fix your issue as well. So please give it a try.

**Comment by dvds** [comment]
Thanks for the release of v7.9.0.

This version does seem to have fixed the problem with the video being blank, but unfortunately in the process has produced an MKV file that refuses to play.

I have uploaded the source file to your FTP site:
**TB.en.10s.vob**

And remuxed it using the following command line:
**mkvmerge --output TB.en.10s.mkv --no-audio --default-track 0:1 TB.en.10s.vob --no-video --language 1:en --default-track 1:1 TB.en.10s.vob**

I have also uploaded the output from this command for both v7.8.0 and v7.9.0, for comparison.

I know MPEG 1/2 is not in any way a priority for you, but if you could take a look at these files and advise what might be causing this, and whether it might ever be fixed in mkvmerge then I'd be grateful.

As the observed effect here is now a bit different from the issue title, if you'd prefer I create a new issue then I will naturally oblige.

Thanks

**Comment by mbunkus** [comment]
Two observations:

1. The file you've uploaded that's been muxed with 7.9.0 plays just fine here with VLC.
2. Why are you adding the same file twice instead of just once? Just use the following command line:

    mkvmerge --output TB.en.10s.mkv --default-track 0:1 --language 1:en --default-track 1:1 TB.en.10s.vob

That file plays fine here, too; therefore I consider the issue fixed.
