### ISSUE TITLE
mkvmerge producing invalid video file

### ISSUE THREAD

**Issue by fidian** [mbunkus/mkvtoolnix#1146]
I am using mkvmerge the git repository.

Merging seems to work.  Upon playing the video, the place where the two videos are joined is corrupt.  Running mkvalidator on the two source files works and it reports errors on the merged video:

Many of these errors:

```
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722070
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722091
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722114
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722135
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722158
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722179
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722202
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722223
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722246
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722267
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722290
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722311
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722334
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722357
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722378
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722401
```

Many of these:

```
WRN0C0: First Block for video track #6 in Cluster at 1340260871 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1341201897 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1342492216 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1343632714 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1344832338 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1345857624 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1346893358 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1347642079 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1348648097 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1352459303 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1354114071 is not a keyframe
WRN0C0: First Block for video track #6 in Cluster at 1355023812 is not a keyframe
```

One of these at the very beginning, but Google tells me that it's a problem with the version of mkvalidator I am using (`mkvalidator v0.4.2, Copyright (c) 2010-2012 Matroska Foundation`).

```
ERR009: The read DocType version 2 is higher than the Doctype version 4
```

I have the files hosted and will email you the download URL separately upon request - email me at fidian@rumkin.com.

Is there anything else I can provide or do in order to avoid the problems with the merged files?

**Comment by fidian** [comment]
I was doing the append wrong.  Took me a day to figure that out, but I found the answer moments after I filed this bug report.  Sorry for the hassle!

**Comment by fidian** [comment]
Well, I got the merge to work and it plays just fine, but the exact same errors are displayed by mkvalidator.  Reopening to see what could be the problem.

To merge I simply did `mkvmerge -o output.mkv in1.mkv + in2.mkv`

**Comment by rautamiekka** [comment]
What player ? Open up in VLC, but before starting playback open 'Messages' window (CTRL+M) and set verbosity to '2 (debug)' by clicking the Down Arrow once, assuming it's at '0 (errors)'.

**Comment by fidian** [comment]
Nothing interesting was shown there.

The messages I was talking about were from `mkvalidator`, version 0.4.2.

**Comment by fidian** [comment]
Full output at https://gist.github.com/fidian/fd00815c54a98183aad7

**Comment by rautamiekka** [comment]
Just copypaste it here, devs will know if something is interesting.

**Comment by fidian** [comment]
It's lengthy and so I created the gist -> https://gist.github.com/fidian/fd00815c54a98183aad7

**Comment by mbunkus** [comment]
I do indeed need those files in order to debug it.

**Comment by fidian** [comment]
Sent URL via email.

**Comment by mbunkus** [comment]
There is no problem.

These messages

```
ERR201: Invalid 'CueRelativePosition' for profile 'matroska v2' in CueTrackPositions at 1616722091
```

are a result of the bug in mkvalidator. I've just [written a FAQ entry about it explaining the issue](/mbunkus/mkvtoolnix/wiki/mkvalidator-ERR201-Invalid-CueRelativePosition-for-profile-matroska-v2-in-CueTrackPositions).

These messages

```
WRN0C0: First Block for video track #6 in Cluster at 1341201897 is not a keyframe
```

aren't an issue either. I've just written [another FAQ entry with an explanation](/mbunkus/mkvtoolnix/wiki/mkvalidator-WRN0C0-First-Block-for-video-track-in-Cluster-not-a-keyframe).

You are correct that this message

```
ERR009: The read DocType version 2 is higher than the Doctype version 4
```

is indeed due to a bug in mkvalidator. There's a third [FAQ entry with an explanation](/mbunkus/mkvtoolnix/wiki/mkvalidator-ERR009-read-doc-type-version-higher-than-doc-type-version).

**Comment by fidian** [comment]
Thanks for doing the research on this.  Maybe you'd want to write your own mkvalidator tool to help work around the issues with the official one?

**Comment by mbunkus** [comment]
I have no interest in providing my own validation tool. However, I've fixed the two bugs mentioned above in the official source and am in the middle of preparing a new release of mkvalidator, v0.5.0.

I'm not mkvalidator's main maintainer (that's Steve Lhomme), but I do have access to the source code.

**Comment by fidian** [comment]
Oh, that's an even better solution!

**Comment by mbunkus** [comment]
The new release [has been uploaded](http://www.matroska.org/downloads/mkvalidator.html).
