### ISSUE TITLE
--default-duration + appending + HEVC bug

### ISSUE THREAD

**Issue by ChrisK2** [mbunkus/mkvtoolnix#1147]
I'm appending multiple raw HEVC streams. When I use ``--default-duration 0:24000/1001p`` on the first or on all segments (doesn't matter), then first segment plays fine, but all following ones play at half speed in the resulting mkv file.

mkvmerge v7.7.0

Let me know if you need sample files.

**Comment by mbunkus** [comment]
Sample files would be appreciated. Please upload them to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server).

**Comment by ChrisK2** [comment]
Okay, I uploaded the files ("default-duration_bug" Folder). The *.hevc files are the source streams, and dd_24 was muxed with ``--default-duration 0:24000/1001p`` (plays incorrectly) and no_dd without (plays correctly).

**Comment by mbunkus** [comment]
Thanks, I can reproduce the issue. This should work (it does for e.g. h.264/AVC), and is therefore a bug that I'll fix.
