### ISSUE TITLE
No Traditional Chinese language option in track language

### ISSUE THREAD

**Issue by czm97176** [mbunkus/mkvtoolnix#1149]
Hi, 

i found there has zho (Traditional Chinese / Big5 ) has missing in Language selection which under the track option.

Please advise. 

http://www.loc.gov/standards/iso639-2/php/code_list.php

Thanks
Gordon

**Comment by mbunkus** [comment]
Nothing I can fix. See [this FAQ entry](/mbunkus/mkvtoolnix/wiki/Chinese-not-selectable-as-language).

As for `chi` vs. `zho`: Matroska uses the bibliographic versions of the ISO 639-2 codes, not the terminology ones. Therefore `chi` is the one that's used for Chinese.
