### ISSUE TITLE
Use of boost.math completely breaks support for FreeBSD

### ISSUE THREAD

**Issue by RobotsOnDrugs** [mbunkus/mkvtoolnix#1150]
The standard c libraries in FreeBSD don't support long double (well enough) for boost.math, and compilation of 7.8.0 fails:
/usr/local/include/boost/math/tools/promotion.hpp:141:10: fatal error: static_assert failed "Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented."
         BOOST_STATIC_ASSERT_MSG((0 == ::boost::is_same<type, long double>::value), "Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.");

FreeBSD 10.1-STABLE amd64
clang 3.4
boost-libs 1.55.0 (which does compile)
mkvtoolnix 7.8.0

7.7.0, which does not use boost.math, compiles without issue.
A full build log is available upon request.
This is somewhat outdated, but still may be useful: https://wiki.freebsd.org/Numerics
Up-to-date, but I'm not sure how useful: https://www.freebsd.org/cgi/man.cgi?query=math&sektion=3&apropos=0&manpath=FreeBSD+10.1-RELEASE

**Comment by mbunkus** [comment]
MKVToolNix does not use long doubles. Therefore you could try defining `BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS` during compilation; e.g. something like this:

```
export CXXFLAGS=-DBOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS
./configure …
```

**Comment by RobotsOnDrugs** [comment]
I'm glad to hear that mkvtoolnix doesn't need them, but adding that to CXXFLAGS unfortunately does not change anything.

Build log:
https://candace.robotsondrugs.com/poudriere/data/101x64-default/2015.03.28_09:02:36/logs/errors/mkvtoolnix-7.8.0.log

**Comment by mbunkus** [comment]
Yeah, not really surprising. I mis-read the source.

**Comment by mbunkus** [comment]
I can reproduce your issue on Linux if I define `BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS` myself. Ooops, I was wrong. MKVToolNix *does* use `long double`s, albeit accidentally: I have a few literals with an `l` suffix, e.g.

```
… = boost::math::llround(samples_left * 1000000000.0l / get_uint32_le(&header.sample_rate));
```

As I said this is accidental. I will fix them to be normal doubles. This is easy enough.

However, I will also remove the dependency on Boost::Math again and use `std::llround` instead. Currently the rounding functions are the only ones that MKVToolNix uses from Boost::Math, and as there's an equivalent in the standard I don't really need Boost::Math.

You can try to compile MKVToolNix after removing the `l` suffix from two places:

1. `src/common/tta.h` line 21 (`#define TTA_FRAME_TIME…`) and
2. `src/input/r_tta.cpp` line 132 (`PTZR0->process(new packet_t(mem, -1, boost::math::llround(samples_left * 1000000000.0l…`).

After changing those two lines I can compile successfully even with `BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS` defined.

**Comment by mbunkus** [comment]
Hmmm OK I also use `boost::math::gcd` and have been for quite some time, so I cannot drop the dependency on Boost::Math. As a matter of fact it has been required for quite some time now; the issue you're experiencing only came to light due to me starting to use `boost::math::llround()`, too.

I'll still convert the use of `boost::math::llround()` to `std::llround()` as it's the right thing to do.
