### ISSUE TITLE
mkvtoolnix-gui.exe is no longer contained in mkvtoolnix installer or portable since v7.6

### ISSUE THREAD

**Issue by darkred** [mbunkus/mkvtoolnix#1151]
I've noticed that `mkvtoolnix-gui.exe` is no longer contained in mkvtoolnix installer or portable version since v7.6 (using windows).

Why is that?
(and I haven't found any relevant entry in changelog nor any relevant issue)

**Comment by mbunkus** [comment]
mkvtoolnix-gui.exe is a preview of the complete re-write of the existing, old but fully functional GUI. See  [its status page](/mbunkus/mkvtoolnix/wiki/MKVToolNix-GUI-status) for details.

Unfortunately the new GUI is not even remotely complete regarding feature parity. Even worse it is quite unstable. The issue with the portable version is that a lot of users looked at the available exes and figured that `mkvtoolnix-gui.exe` sounded like the right thing to start – and not `mmg.exe`. I admit that `mmg.exe` is not an intuitive name.

The result was that those users started `mkvtoolnix-gui.exe`, completely ignored the big fat warning popup and then came to me complaining that features are missing or that the GUI is unstable.

Therefore I opted to remove that source of confusion.

The installer still includes the new GUI and creates start menu entries. The big difference is that the start menu entries are named somewhat more intuitively than the exes, and users generally don't have a problem running the working GUI from the start menu.

**Comment by darkred** [comment]
Thank you very much for the answer.

**Comment by mbunkus** [comment]
You're quite welcome.
