### ISSUE TITLE
HEVC conformance_window_flag is ignored when detecting resolution

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1152]
The cropping parameters in the HEVC SPS seem to be ignored. I have uploaded samples to your ftp. In the sample correct height would be 1080 lines but is detected as 1088 lines. (mkvmerge 7.8.0 pre 685)

Source file SPS:
chroma_format_idc 1
pic_width_in_luma_samples 1920
pic_height_in_luma_samples 1088
conformance_window_flag 1
conf_win_left_offset 0
conf_win_right_offset 0
conf_win_top_offset 0
conf_win_bottom_offset 4

chroma_format_idc 1 means 4:2:0 and "SubHeightC" = 2.
conformance_window_flag 1 means cropping is used

Calculation for correct height:
pic_height_in_luma_samples − ( SubHeightC * conf_win_bottom_offset + 1 ) (see HEVC spec 7.4.3.2 )

**Comment by mbunkus** [comment]
I don't have the HEVC specs, so I'll have to rely on your word. I'll investigate.

**Comment by sneaker2** [comment]
HEVC specs can be downloaded for free:
http://www.itu.int/rec/T-REC-H.265-201410-I/en

**Comment by mbunkus** [comment]
Huh… I didn't know that; thanks.

**Comment by mbunkus** [comment]
If I understand the specs correctly then your formula would be wrong, too, wouldn't it? The conformance window takes the top cropping into account, too.

So if the top cropping is 0 then your formula is accurate, but not for the general case.

The following should be the general fomula:
```
pixel_height = pic_height_in_luma_samples
  - (SubWidthC * conf_win_bottom_offset + 1)
  - (SubWidthC * conf_win_top_offset)
```

**Comment by mbunkus** [comment]
Uhm without that +1 there. That pixel is inclusive, so we must not subtract it :)

**Comment by sneaker2** [comment]
Yes, sorry. I copy-pasted it from the spec. I though it would be obvious from the sample and looking at the spec.

**Comment by mbunkus** [comment]
A new [pre-build](https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/) is currently being built and uploaded. Build numbers 687 and higher will contain the fix.

**Comment by mbunkus** [comment]
Thanks for the report & the sample.

**Comment by sneaker2** [comment]
Thank you, it seems to be working fine. (No idea how you managed to work on HEVC without the specs until now...)

**Comment by mbunkus** [comment]
The original implementation was provided by the DivX/Rovi guys. The implementation was based on my h.264/AVC code, so it is pretty familiar to me even if I didn't write it.

From there on out I simply compared the code in MKVToolNix with other decoders, mostly ffmpeg's. That way I've fixed one or two bugs already. Even without the spec :)
