### ISSUE TITLE
Track info appears after clusters after running mkvpropedit

### ISSUE THREAD

**Issue by matsp888** [mbunkus/mkvtoolnix#1154]
I have uploaded an archive "seginfo-test.tar.gz" (it should really be called trackinfo-test.tar.gz") to your FTP server with a shell script 'setdisp' and a test file 'test.mkv'. After running the script, which sets the display width and height, the track info will be located after the clusters, which is incorrect according to http://www.matroska.org/technical/order/index.html, which states: "And the Segment Info and Track Info must always be found before the Clusters." Why this happens is probably because there simply isn't enough space in the track info to add the display width/height, which isn't defined in the original file. In any case, the track info shouldn't be placed after the clusters. Instead a warning should be issued that a remux is needed (in case there is no other way to do it).

**Comment by mbunkus** [comment]
I've already explained to you why this is a) sometimes necessary and b) that this does not violate the Matroska specs. I've even clarified the specs so that this is more obvious. Players that cannot find the tracks located after the clusters *even if they're properly referenced from meta seek elements* are buggy, and I won't circumvent buggy players in my tools – that would be a losing game.

This is nothing I can fix or have any intention of changing.

If a warning was issued each time a file was produced that might not be playable by one player or another then mkvmerge and mkvpropedit would have to emit one each and every time they're run. This would be completely nonsensical.

Therefore I won't change anything.

**Comment by mbunkus** [comment]
More productive would be if you filed a bug report with ffmpeg asking for them to write a void element after the tracks element so that such modifications would have a better chance of being able to keep the tracks in front of the clusters.

**Comment by matsp888** [comment]
I don't agree, Moritz. If you read the specs at the page that I mentioned they explicitly mention that the track info has to appear before the clusters. And it's not up to FFmpeg to fix anything. The specs don't mention anything about having to use void data here and there, it's just a "feature" of mkvtoolnix. If you can't add the data to the track info, give the user a message instead of creating an invalid file.

**Comment by mbunkus** [comment]
No, the player has to be able to _find_ the tracks by the information present before the first cluster. If a meta seek element is present before the cluster and if that meta seek element references the tracks (or a second meta seek element and that second element references the tracks) then that is sufficient. Not optimal, but sufficient.

And I'm not saying ffmpeg is doing something wrong; they just might make such modifications easier for tools like mkvpropedit. And mkvpropedit isn't the only one affected by such limitations. So it might be a nice enhancement for ffmpeg.

Anyway, mkvpropedit's behavior will stay the way it is.

**Comment by mbunkus** [comment]
See also https://github.com/mbunkus/mkvtoolnix/wiki/All-tracks-vanished-after-mkvpropedit-or-header-editor

**Comment by matsp888** [comment]
Yes OK. That answers the question I just posted. Thanks.
Mats
 -- 
Mats Peterson
http://matsp888.no-ip.org/~mats/

**Comment by matsp888** [comment]
Having the track info after the clusters isn't exactly ideal for streaming anyway. I hope you'll agree on that at least.

**Comment by mbunkus** [comment]
Absolutely, but if you want to employ streaming then run the files through mkvmerge and not mkvpropedit. mkvmerge guarantees good file layout. mkvpropedit doesn't but it is way faster than mkvmerge. That's your trade-off.

**Comment by matsp888** [comment]
Right. Thanks, Moritz.
