### ISSUE TITLE
mkvmerge strips DTS track bit-depth property

### ISSUE THREAD

**Issue by KonaBlend** [mbunkus/mkvtoolnix#1155]
mkvmerge will strip (or not populate) the bit-depth property for DTS audio tracks. Sample command:

`mkvpropedit --track:2 -s bit-depth=24 in.mkv`
`mkvmerge -o out.mkv in.mkv`

**in.mkv:**
```
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 6
|   + Bit depth: 24
```

**out.mkv:**
```
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 6
```

**Comment by mbunkus** [comment]
Thanks for the patch, but there's no need for the bit-depth information at the container level for decoding purposes. Therefore mkvmerge doesn't write it for codecs like DTS, only for raw PCM. I have no intention of changing that.

If you want to attach arbitrary information to a track that's always kept by mkvmerge use tags; that's what they're there fore.
