### ISSUE TITLE
feature request: a more detailed description for DTS-ES audio tracks which are shown as »DTS«

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1157]
Hello Mosu!

It's the similar matter like in the #1109 issue, but this time I've got something special for you: I have found very interesting audio tracks which name is: DTS-ES. This type of DTS is very popular on DVDs, but also you can find it on BDs (I've found a one :D). The good news is that mkvmerge recognizes them correctly, but the bad news is that they are shown/displayed as »DTS« which is an unclear description and may cause some confusions. I've made a screenshot, look here: 
![dts-es](https://cloud.githubusercontent.com/assets/10992208/6976019/f5716b06-d9a3-11e4-9bd7-440a49c38aae.png)

That's why I strongly urge you to implement a more itemized description for this kind of audio tracks: DTS-ES. If you are interested, you can read about them here ====> http://en.wikipedia.org/wiki/DTS_%28sound_system%29#DTS-ES
As you can read, this IS NOT a plain DTS. It contains the extended variant of a DTS sound; it's much better and purer. 
Exclusively for you I have prepared 9 (nine!) sample files; among them the three which are very exciting because they contain additional channels. For example look here:
![dts-es 2](https://cloud.githubusercontent.com/assets/10992208/6976304/24e60dde-d9a8-11e4-89bd-443b6286eceb.png)

The sample files (one .m2ts, four .vobs and four raw files) will be uploaded to your FTP soon. Please: do not reject my request. Think about it carefully. I know that this is not something major, but maybe you could implement it in a free time. I (and other users) will be very grateful for that enhancement.

Thank you for considering it.

**Comment by remuxer32** [comment]
The sample files have just been uploaded. Have fun :)

**Comment by mbunkus** [comment]
A new [32bit pre-build](https://www.bunkus.org/videotools/mkvtoolnix/win32/pre/) has been uploaded as well.

**Comment by remuxer32** [comment]
Thank you for a quick implementation and a pre-build version. I've just checked it: works perfect :).
