### ISSUE TITLE
Bugs when muxing the two "sub-streams"  from a TrueHD track with MkvMerge 

### ISSUE THREAD

**Issue by r0lZ** [mbunkus/mkvtoolnix#1158]
When trying to mux a TrueHD track (extracted from a blu-ray) and keep the two "sub-streams" (TrueHD and AC3 core), MkvMerge (and mmg) have several bugs.

For example, consider this command (generated by mmv):

"mkvmerge.exe" -o "TrueHD_test.mka"  "--language" "0:fre" "--track-name" "0:TrueHD" "--default-track" "0:yes" "--forced-track" "0:no" "--language" "1:fre" "--track-name" "1:THD Core" "--default-track" "1:no" "--forced-track" "1:no" "-a" "0,1" "-D" "-S" "-T" "--no-global-tags" "--no-chapters" "(" "THD_stream.ac3" ")" "--track-order" "0:0,0:1"

The two sub-tracks should be considered as totally independent, and therefore it should be possible to give independent parameters to the two streams.  For example, in the command above, the track names and the default flags have different values.

First bug: When the mux operation starts, there is a wrong warning:
Warning: Another default track for audio tracks has already been set. The 'default' flag for track 0 of 'THD_stream.ac3' will not be set.
However, the default flags are correctly set in the output MKA: on for the THD track and off for the core.
I have also tried to remove the --default-track 1:no arguments but the warning is still displayed.  Therefore, it is currently impossible to define one of the two tracks as default without a (false) warning.

Second bug: The track name of the second sub-stream is not correct in the output MKA: It's the name provided for the first stream that is used.  Therefore, the two streams in the output MKA have the same name.

I have not tested with different values for the language, forced, delay and stretch parameters, because it doesn't make much sense to give different values to these parameters, but I guess that they have the same bug.

Third bug: As a workaround, I have also tried to generate the output MKV with the correct names with this command:

"mkvmerge.exe" -o "TrueHD_test.mka"  "--language" "0:fre" "--track-name" "0:TrueHD" "--default-track" "0:yes" "--forced-track" "0:no" "-a" "0" "-D" "-S" "-T" "--no-global-tags" "--no-chapters" "(" "THD_stream.ac3" ")" "--language" "1:fre" "--track-name" "1:THD Core" "--default-track" "1:no" "--forced-track" "1:no" "-a" "1" "-D" "-S" "-T" "--no-global-tags" "--no-chapters" "(" "THD_stream.ac3" ")" "--track-order" "0:0,1:1"

That command should work perfectly, but again there are many problems.  It seems that ALL arguments for the second stream (the core) are ignored.  The track name is blank, the language is undefined, and so on.  (The default flag is correct, but I suppose that it must be "no" since there is already a track with the value "yes".)
Anyway, it is a pity to have to process the same input file twice, so this method is not a good solution to bugs 1 and 2.

So, currently, it is impossible to mux the two sub-streams of a TrueHD input file and provide different values for some parameters.

**Comment by mbunkus** [comment]
Thanks for posting it here, too.
