### ISSUE TITLE
MPEG-2 video file not recognized

### ISSUE THREAD

**Issue by adminio** [mbunkus/mkvtoolnix#1162]
Error on opening file test.m2v in mkvmerge: the error message is "the file ..\test.m2v" is of unknown type.
Add the mkvinfo report on file:

General
Complete name               : C:\test.m2v
Format                      : MPEG Video
Format version              : Version 2
File size                   : 5.95 MiB
Duration                    : 12s 320ms
Overall bit rate            : 4 054 Kbps

Video
Format                      : MPEG Video
Format version              : Version 2
Format profile              : Main@Main
Format settings, BVOP       : Yes
Format settings, Matrix     : Custom
Format settings, GOP        : M=3, N=12
Format settings, picture st : Frame
Duration                    : 12s 320ms
Bit rate                    : 4 054 Kbps
Maximum bit rate            : 4 000 Kbps
Width                       : 720 pixels
Height                      : 576 pixels
Display aspect ratio        : 16:9
Frame rate                  : 25.000 fps
Standard                    : PAL
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Interlaced
Scan order                  : Top Field First
Compression mode            : Lossy
Bits/(Pixel*Frame)          : 0.391
Time code of first frame    : 00:00:00:00
GOP, Open/Closed            : Closed
Stream size                 : 5.95 MiB (100%)

**Comment by mbunkus** [comment]
Can you please upload the file to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can take a look?

**Comment by adminio** [comment]
ok, i have just uploaded it.
