### ISSUE TITLE
subtitle merge issue

### ISSUE THREAD

**Issue by ryan010** [mbunkus/mkvtoolnix#1163]
Hi, I'm really a big fan of your application, and I made a lot of reviews on my youtube channel explaining how the application works. But recently I just noticed that When I merge the subtitle with the movie it works well But when I upload the video on any online service like youtube or MyWorld the subtitle with vanish and will not be exist any more.!! I tried everything to find a solution but I couldn't. Any idea please

**Comment by mbunkus** [comment]
That's a limitation of the video services you're using. They don't support subtitles. I cannot help you with such services.

**Comment by ryan010** [comment]
But it doesn't work everywhere, I mean when I stream it to my TV I can't
see any subtitle, when I put it on USB and stick it on my TV even thogh I
can't. And from hundreds of videos that I convert couple of them works, but
I couldn't find the reason.!! So Believe that the problem is beyond The
online Service.

**Comment by mbunkus** [comment]
Then your TV doesn't support subtitles in Matroska either. I cannot help you with such problems.

**Comment by ryan010** [comment]
Believe me it does, because when I use another application it works smoothly without any problem. But still your apps is intersted for alot of pepole and I am sure there is a such solution here.

**Comment by mbunkus** [comment]
Those other apps might produce other file types than Matroska. Or those other apps might render the subtitles into the video (which mkvmerge doesn't, it keeps them as a separate track).

But believe me, I cannot help you here!

**Comment by ryan010** [comment]
Oh, ok now I get you. Thank you for explaing.
