### ISSUE TITLE
Trouble with joining two .mkv files

### ISSUE THREAD

**Issue by BP1970** [mbunkus/mkvtoolnix#1165]
mkvmerge GUI v7.8.0 ('River Man') 64 bit
Mac OS X Yosemite 10.10.2

Tried merging two .mkv files ripped from blu ray disks by adding the two .mkv files in the "Input files", and clicked on "Start mixing" button.  I get the following warnings:

Warning: matroska_reader: Could not keep the track UID 1 because it is already allocated for the new file.
Warning: matroska_reader: Could not keep the track UID 2 because it is already allocated for the new file.
Warning: matroska_reader: Could not keep the track UID 3 because it is already allocated for the new file.

mkvtoolnix does its magic despite the above warnings, and the output file size seems about right (sum of two .mkv file sizes).  However, when playing back the merged file in VLC (2.1.5), the video ends per first .mkv file.  The video of second .mkv file is not present in the merged file.

What could I be doing wrong?  Thanks for your help.

**Comment by mbunkus** [comment]
Use the »append« functionality for the second file, not the »add« functionality.

About the duplicate track UIDs: that's the fault of the software that created those source files. Those UIDs are supposed to be unique across multiple files and not simply sequential numbers starting at 1.

**Comment by BP1970** [comment]
It works... thank you for your quick response!

**Comment by ovizii** [comment]
Similar problem, tried the above solution but then getting:

`Error: The track number 0 from the file '/Volumes/Ovi/_temp storage/STREAM/00001.mkv' cannot be appended to the track number 0 from the file '/Volumes/Ovi/_temp storage/STREAM/00000.mkv'. The track parameters do not match.
`

Not sure about track #0 - I have track 1+2 (audio, is track 0 the video stream?) they are absolutely identical, any idea what to check for?
