### ISSUE TITLE
mkvmerge: AVC ES recognized as AAC - muxing aborted

### ISSUE THREAD

**Issue by basicmaster** [mbunkus/mkvtoolnix#1166]
Hi,

I have the case of an MPEG-4 AVC ES file which is recognized by mkvmerge as AAC, leading to:
`Error: aac_error_proection_specific_config.`

The used commandline was:
`mkvmerge -o tshdcut_test.mkv tshdcut_5121.264`
I uploaded the regarding file to your FTP server; it is from a DVB-S2 recording and the first frame is an I-frame.

The used mkvtoolnix version is v7.8.0, but the latest Git version is affected, too. As I don't have really knowledge of AAC, this time I abstain from making a patch by myself ;-)

**Comment by mbunkus** [comment]
Thanks for the report & the test file.

**Comment by basicmaster** [comment]
Thanks for the fast fixing!
