### ISSUE TITLE
wxWidgets alert when doing batch muxing

### ISSUE THREAD

**Issue by Ivan2016** [mbunkus/mkvtoolnix#1167]
Hi. I've found strange thing while doing batch muxing. This "Yes/No/Cancel" dialog window appears each time the new job is started: ![mkvmerge wxwidgets](https://cloud.githubusercontent.com/assets/11991040/7198374/6ce1f83a-e4f4-11e4-896a-dec709408b98.jpg).
If I press "Cancel" button - the process continutes and the output is produced.
I have couple of questions:
1) Is it safe to ignore this alert?
2) What can be the source of this problem? Could it be related to non-ASCII characters used for the file/folder names?

I'm using version 7.8.0 on Win7 x64 and mmg to make/run batches.

TIA, Ivan.

**Comment by mbunkus** [comment]
I cannot answer this question. mmg is also not developed anymore as it will be replaced by [a new GUI](https://github.com/mbunkus/mkvtoolnix/wiki/MKVToolNix-GUI-status) within the next couple of releases.

**Comment by mbunkus** [comment]
Just try ignoring it; if everything works: great.
