### ISSUE TITLE
DTS debug code visible with mkvmerge --identify

### ISSUE THREAD

**Issue by paavoris** [mbunkus/mkvtoolnix#1168]
(This is a really small issue, only cosmetic)

It looks like you have some (maybe not needed anymore?) debug code printing, when using mkvmerge with --identify parameter. It's printing extra line "kax i, am at nnnn", but only when input file has a DTS(-HD) audio track. 

Sample screenshot below, where mkvmerge --identify was called in a batch against four different matroska files.

![mkvmerge](https://cloud.githubusercontent.com/assets/1580135/7198683/498dc3b6-e4f7-11e4-96af-8eb48a4df988.png)

**Comment by mbunkus** [comment]
This has already been fixed in 669a2768a0ae608a7e1e20377f202a117f1b55e9.
