### ISSUE TITLE
Specific Replay/Duplication on File Merge

### ISSUE THREAD

**Issue by fuzzycobalt** [mbunkus/mkvtoolnix#1169]
Hello! I just started using this program today and I am trying to take the audio track off of one .mkv and put it into another .mkv file. They are the same duration, same episode and everything, so technically I should just be able to add the ripped audio from one version to the other. However, whenever I merge the files together after placing the audio from one with the rest of the file of another .mkv, it plays back specifically and exclusively the introduction portion of the show twice, once in its normal timeframe, and then one more time immediatly afterwards. This causes the rest of the audio to be delayed by a minute or two for the rest of the show. I have no clue why it is doing this.... Thank you for any help!

**Comment by mbunkus** [comment]
Can you provide a screenshot of the GUI right before you started merging? I have a hard time guessing what you've done and where you might have made a mistake.

**Comment by fuzzycobalt** [comment]
Yeah!

So here is a screenshot. I have selected to only keep the subtitles and the audio from the lower quality version, and mic it with the rest of the higher quality version, while leaving the video and other sub/audio tracks from the lower quality version out.

![example shot](https://cloud.githubusercontent.com/assets/12002472/7217410/64b24514-e5e6-11e4-9875-021dd66e4a3c.png)

Here is an quick/rough example of what happens when I mix them. The audio for both lines up perfectly, but when I mix them it plays only a specific section twice, then continues on as normal.
The light blue is the section that is replayed. As you can see it duplicated when mixed. numbers are a rough reference as to the time in the video.

![example](https://cloud.githubusercontent.com/assets/12002472/7217419/0da0d12c-e5e7-11e4-9a89-6ab39092cb09.png)

This is an example in VLC of the video BEFORE mixing. The section in the red bars (between the two ticks on the VLC time bar) is what is duplicated, as represented by the blue bars.

![example 2](https://cloud.githubusercontent.com/assets/12002472/7217425/34a4b4a0-e5e7-11e4-856e-a43025579f0a.png)

**Comment by mbunkus** [comment]
Hmm, I honestly have no idea what's happening and why. If you want to have an answer I'll need access to both source files. Can you upload them to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server), please?

**Comment by fuzzycobalt** [comment]
Sure! Before that though; after messing around with it further I found this out:

Both the HD and Normal versions have opening sequences and end credits at the same time.

When I extract the audio from the Normal version it plays exactly as it was heard before it was ripped from the video.

However, when I extract the audio from the HD version, the opening sequence and the end credit sounds are missing. It simply skips the entire duration and goes right to the next part of the video. There is no empty space, it just cropped it out of the audio entirely.

When I put the Normal sound with the opening and ending still inside the audio to the HD video, the opening and ending audio of the HD video is somehow still there, and this is what causes it to double, it plays the Normal audio until it hits the opening, then it plays the somehow still attached HD audio for about a minute right exactly at the opening, then when it is done goes back to playing the normal audio I added, thereby replaying the opening since that was the next part of the audio to be played on the track I added.

Also, if I take just the HD video and deselect everything except for the Video output, the resulting exported file is missing everything (such as audio and subs) as well as the opening and ending present in the source file is also missing. If I do the same thing, but leave the Chapters and Video checked, but deselect everything else in the resulting exported file there is no audio or subtitles, which makes since because I did not select them to be in the export file, but the opening and ending ARE present with full audio, subtitles and everything. They are somehow bound to the chapters.

**Comment by mbunkus** [comment]
Oh, the file uses ordered chapters (those are control structures telling a player to play this short audio track first, then that other audio track). The observed behavior is not a bug, then.

Unfortunately I cannot help you with ordered chapters as I don't use them myself. Please post this problem somewhere else, e.g. on [Doom9's forum](http://forum.doom9.org/forumdisplay.php?f=74), where there might be people who have used ordered chapters.
