### ISSUE TITLE
Subtitle's delay doesn't work

### ISSUE THREAD

**Issue by rootsandculture** [mbunkus/mkvtoolnix#1171]
Hi, I'm trying to adjust the existing delay from my subtitle, but when I make the new mkv it doesn't apply the new 1000ms offset. I need in this case makes the subtitles appears 1 sec after the current time. I tried manually offset from vlc and it works, but I wish to make it permanent in a .mkv.
I'm on Win7 64 bits and latest build of Mkvtoonix (7.8.0.).

Regards

![untitled-1](https://cloud.githubusercontent.com/assets/12083250/7295803/f4f43090-e98f-11e4-93b7-0df31cdba8f0.jpg)

**Comment by mbunkus** [comment]
I cannot reproduce this. I've created a Matroska file with the same track types as yours, set the delay to 1000, muxed, and the timecodes of the subtitle track in the resulting file are offset just as expected. Check your output file `Les Chose De La Vie (1) (1).mkv` with mkvinfo for the first timecode of that SRT track and compare it with the timecode from the source file.

Don't just rely on a player like VLC! Check with mkvinfo.

**Comment by rootsandculture** [comment]
Thanks for the reply. How should I check that, sorry but I'm not familirized with this :(

![untitled-2](https://cloud.githubusercontent.com/assets/12083250/7296074/c7f00148-e992-11e4-943d-be334f438b0c.jpg)

**Comment by mbunkus** [comment]
Run `mkvinfo -s -r info.txt yourfile.mkv`. This will create a (rather big) file called `info.txt` which contains one line per frame. The track you're looking for should be track number 3.

Do this for both files (before and after remuxing) and compare the timecodes of the subtitle track.

**Comment by rootsandculture** [comment]
You mean this difference shows that it must be working?
![untitled-3](https://cloud.githubusercontent.com/assets/12083250/7296378/7bd92a48-e995-11e4-8307-bba325ba2780.jpg)

**Comment by mbunkus** [comment]
Correct. The checksum at the end of the line shows that it's the same frame, and it's been delayed by 1s, exactly as you asked mkvmerge to do. So either you're doing something wrong (e.g. you've played the source file in your player and not the output file created by mkvmerge), or it might be a bug in your player.

**Comment by rootsandculture** [comment]
Thanks for your time, really don't know what's happening. Obviosly I'm playing the new .mkv, will try if it's a bug in vlc, the latest build has many reported problems.
Regards
