### ISSUE TITLE
Fails to build against boost 1.58

### ISSUE THREAD

**Issue by foutrelis** [mbunkus/mkvtoolnix#1172]
Building against boost 1.58 results in the following error:

    In file included from src/common/utf8_codecvt_facet.cpp:22:0:
    src/common/../../lib/boost/utf8_codecvt_facet/utf8_codecvt_facet.cpp:174:5: error: 'int mtx::utf8_codecvt_facet::do_length' is not a static data member of 'struct mtx::utf8_codecvt_facet'
         BOOST_CODECVT_DO_LENGTH_CONST std::mbstate_t &,

This seems to be caused by a change in the upstream `boost/detail/utf8_codecvt_facet.hpp` file (see https://github.com/boostorg/detail/commit/1fef8494fec86d23e557007343036c3d8a5b0ace).

**Comment by mbunkus** [comment]
Thanks for the report.
