### ISSUE TITLE
feature request: »disable compression for all track types«

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1174]
I'm a user who doesn't use compression at all. I really hate this. 
To be absolutely sure that my ''stuff'' (.mkv file) is ''untouched'' and ''pure'', I have to always set compression as »none« for all track types (videos, audios, and even subtitles: yes, I always disable ''zlib'' compression).

The problem is that I have to do it every time manually for all tracks which is very annoying and wasting time. 

That's why I have a special request to you. Could you please add a following feature to the ''Options'' (or to the different right place; maybe a new checkbox?): **»disable compression for all track types«**. I mean a permanent exclusion of course.

I (and other users who don't like/don't need compression like me) will be very grateful for that. Thanks to this my (and not only mine) work will be much faster and easier.  

Thank you very much for an effective implementation of my idea.

**Comment by sneaker2** [comment]
AFAIK recent mkvmerge does not use any compression for video or audio by default anymore. For subtitles there are actually players that don't work without the zlib compression. Are you sure you actually need this option?

**Comment by remuxer32** [comment]
> mkvmerge does not use any compression for video or audio by default anymore.

That's true. I know about it, but, anyway, I prefer to disable compression for video & audio, too. Why? For the sake of certainty; just in case. I want to be sure 100% that my .mkv file is ''pure''.

> For subtitles there are actually players that don't work without the zlib compression.

What kind of players do you mean exactly? Any examples? I hope you don't mean DVD/Blu-ray players because such a type of players is not intended to open/play .mkv files. They may have problems with a correct recognition of Matroska. The best type of players to open Matroska (and not only) is professional/advanced media player. Three random examples of good media players:

► Dune HD Base 3D
► Popcorn Hour A-410
► Xtreamer Prodigy Black 

Such players shouldn't have any problems with Matroska files (even if the zlib compression is disabled). As is interesting to add that I read someday about a man who had a problem with subtitles in an .mkv file. Why? Because the zlib compression was enabled. The player couldn't recognize subtitles because of that. As you can see there is no universal rules. Some players have the problem, some not.

> Are you sure you actually need this option?

Yes, I am. Like I wrote before: I don't want & need any compression in my .mkv files. It's absolutely unnecessary for me. Also: I like to have a choice. 

*@Mosu*:

I have reconsidered it. In my opinion the best way to implement my idea is to add it to the »Command line options«. Thanks to this I (and other users) wouldn't have to remember to disable  compression manually every time. The only question is: Is it possible? If not, then a new checkbox would be welcome, but I (still) will have to select the new checkbox every time, anyway. That's why the »Command line options« is the most comfortable and logical solution.
BTW: In the new GUI, in contrast to the old GUI, I can disable compression for all tracks very easy in two steps:
1) Select all tracks
2) Click on »no extra compression«   

But, in spite of all, I still think that a new option is definitely needed. I don't like wasting my time for selecting tracks etc. so I hope you understand my point of view. Thank you.

**Comment by sneaker2** [comment]
> What kind of players do you mean exactly?

WD TV for example.
I didn't know there were any players not supporting zlib subtitles. Mkvmerge has been using it since forever and is de-facto the reference implementation of mkv and very widespread so vendors tend to build their software around it.

**Comment by remuxer32** [comment]
> WD TV for example.

Indeed. Well, I'm not surprised that WD TV doesn't work without the zlib compression because this player is very cheap, low-class and not advanced of course. It doesn't support many useful formats (e.g. .SSIF files, ISO images etc.). We can say that such players like WD TV are obsolete right now (in a certain sense of course). Only the premium players (listed above) are able to »eat« everything what you serve. Anyway, the future definitely belongs to the 4K media players (e.g. Xtreamer Prodigy 4K).
