### ISSUE TITLE
Linking fails if older libMatroska is installed but internal one is used for compilation

### ISSUE THREAD

**Issue by ryandesign** [mbunkus/mkvtoolnix#1177]
Hello, building mkvtoolnix 7.8.0 fails with libmatroska 1.4.0:

```
Undefined symbols for architecture x86_64:
  "libmatroska::KaxCodecDelay::ClassInfos", referenced from:
      kax_reader_c::read_headers_tracks(mm_io_c*, libebml::EbmlElement*, long long) in libmtxinput.a(r_matroska.o)
      generic_packetizer_c::set_codec_delay(basic_timecode_c<long long> const&) in libmtxmerge.a(generic_packetizer.o)
      generic_packetizer_c::set_headers() in libmtxmerge.a(generic_packetizer.o)
  "libmatroska::KaxSeekPreRoll::ClassInfos", referenced from:
      kax_reader_c::read_headers_tracks(mm_io_c*, libebml::EbmlElement*, long long) in libmtxinput.a(r_matroska.o)
      generic_packetizer_c::set_track_seek_pre_roll(basic_timecode_c<long long> const&) in libmtxmerge.a(generic_packetizer.o)
      generic_packetizer_c::set_headers() in libmtxmerge.a(generic_packetizer.o)
  "libmatroska::KaxDiscardPadding::ClassInfos", referenced from:
      cluster_helper_c::render() in libmtxmerge.a(cluster_helper.o)
      kax_reader_c::process_block_group_common(libmatroska::KaxBlockGroup*, packet_t*) in libmtxinput.a(r_matroska.o)
ld: symbol(s) not found for architecture x86_64
```

These symbols were added in libmatroska 1.4.1. Building mkvtoolnix 7.8.0 with libmatroska 1.4.1 works fine.

Perhaps you could update your configure script to detect a too-old version of libmatroska and advise the user to upgrade. In fact, it looks like you're trying to do that, since you're using `pkg-config` to test for libmatroska 1.4.2 or later. But libmatroska 1.4.1 and earlier did not include support for `pkg-config`, and even though the configure script detected `checking for MATROSKA... no`, libmatroska still somehow got used. So if libmatroska is optional, then you should additionally make sure that when libmatroska is not detected, you don't attempt to use it.

**Comment by mbunkus** [comment]
Your premise is wrong. libMatroska is neither optional, nor is the installed version arbitrary. Current MKVToolNix requires libMatroska 1.4.2 or newer as stated in both the ChangeLog and the README.md file.

The configure check is supposed to chose the internal version if pkg-config cannot find an installed v1.4.2. Logically this seems completely fine to me: MKVToolNix requires libMatroska 1.4.2, it's a must-have dependency. As pkg-config is included in 1.4.2 I can very well use pkg-config for detection.

**Comment by ryandesign** [comment]
Ah, I see. I was guessing as to some of the specifics, and I didn't realize there was an internal copy of libmatroska to use when there is not already one installed. However, I do not consider the ticket invalid, because I did encounter a build failure of mkvtoolnix when libmatroska 1.4.0 was installed on the system, and it would have been good to either get an error message from configure stating that the installed version is too old, or for the internal copy to be silently used in that case.

**Comment by mbunkus** [comment]
The latter is what is supposed to happen. As a matter of fact the include files from the internal version must have been used, otherwise you would have gotten a compiler error long before the linker error.

As to the linker error: what is the content of `MATROSKA_LIBS` in `build-config` in that case? Because that setting should include `-Llib/libmatroska/lib`, and then the library from directory should be used.

**Comment by ryandesign** [comment]
That's true:

```
MATROSKA_LIBS = -Llib/libmatroska/src -lmatroska
```

But when building with `V=1` I see that the command that gets run is:

```
ccache /usr/bin/clang++ -L/opt/local/lib -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -arch x86_64 -L/opt/local/lib -Llib/avilib-0.6.10 -Llib/librmff -Lsrc/common -Llib/pugixml/src -o src/mkvmerge src/merge/mkvmerge.o -Lsrc/merge -lmtxmerge -Lsrc/input -lmtxinput -Lsrc/output -lmtxoutput -Lsrc/merge -lmtxmerge -lmtxcommon -lmagic -lz -Llib/libmatroska/src -lmatroska -Llib/libebml/src -lebml -lz -lpugixml -liconv -lintl -L/opt/local/lib -lcurl -lboost_regex-mt -lboost_filesystem-mt -lboost_system-mt -lavi -lrmff -Lsrc/mpegparser -lmpegparser -lFLAC -logg -lm -lvorbis -logg
```

I see `-L/opt/local/lib` appears three times before `-Llib/libmatroska/src -lmatroska`, so any libmatroska in /opt/local/lib will be used before any in lib/libmatroska/src.

If I understand your build system correctly, it looks like the first instance of `-L/opt/local/lib` is from `EXTRA_LDFLAGS`, because we are configuring mkvtoolnix with `--with-extra-libs=${prefix}/lib --with-extra-includes=${prefix}/include`. The second instance is from `USER_LDFLAGS`, because MacPorts sets several environment variables, including `LDFLAGS="-L/opt/local/lib" CPPFLAGS="-I/opt/local/include"`. The third is from `BOOST_LDFLAGS`, because we configure with `--with-boost=${prefix}`. If these `-L/opt/local/lib` appeared after the `-Llib/libmatroska/src -lmatroska` the problem shouldn't occur but I haven't looked at your build system thoroughly enough to see how difficult that would be to change.

**Comment by mbunkus** [comment]
Your analysis sounds about right. I will probably have to list the library and include flags first for all the libaries that I bundle. pugixml and UTF8cpp are probably affected as well.

**Comment by mbunkus** [comment]
Meh, auto close by Github. Anyway, I've pushed a commit that hopefully fixes this issue. I've given it a try with all three possible situations:

* no libEBML/libMatroska installed at all,
* installed libEBML/libMatroska are up to date (and therefore used),
* installed libEBML/libMatroska are too old, and the internal versions are used.
