### ISSUE TITLE
Possible bug: using frame rate instead of source time codes during mux

### ISSUE THREAD

**Issue by archivisth** [mbunkus/mkvtoolnix#1179]
I ran into a peculiar problem multiplexing Tomoe ga Yuku from an H.264 avi (yeah, I know). The source worked fine in Aegisub for typesetting. However, after muxing, the signs and the source were desynchronized, particularly at the end of the episode, by up to two frames.

Turns out that the frame rate in the source was not quite right. Based on extracted timecodes, the source frame rate was a tad high: 29.9709, or about 0.003%..During the mux, mkvmerge regenerated the timecodes based on the stated frame rate. This caused a gradual desynchronization as the video progressed.

I solved the problem by forcing mkvmerge to use the avi's timecodes during the mux, but shouldn't there be a simpler solution than (a) extracting timecodes and (b) adding the file to mkvmerge? In general, shouldn't mkvmerge believe the timecodes in the source, rather than the frame rate, so that its actions  mimic Aegisub?

In any case, it would be nice to have a simpler way of forcing mkvmerge to adhere to the source's timecodes. You could call it the S*ar Wars switch: "Use the source, Luke!"

Timecode files illustrating the problem are at https://www.mediafire.com/?j97og8abyk45jqw . Unfortunately, the GitHub issues system won't allow arbitrary attachments.

**Comment by mbunkus** [comment]
AVI files don't contain timecodes. They only contain a frame rate along with frame numbers. mkvmerge calculates the timecodes to use in the output file by multiplying the frame rate with the frame number.

About forcing the frame rate without a timecode file: that's what the `--default-duration` option is there for.

I don't know what Aegisub does in order to calculate the timecodes. Maybe it rounds differently than mkvmerge?

**Comment by archivisth** [comment]
I'm not familiar with internal formats. I thought perhaps it had to do 
with putting h.264 in an AVI wrapper, which is sort of non-standard.

The problem is in the source H.264 AVI file, one way or another. A more 
recent encode from the same encoder does not show the same problem - the 
AVI file and the MKV mux of it yield exactly the same timecodes. Yet 
both the failing encode (Tomoe) and the recent one (Lensman) say that 
the frame rate is exactly 29.970. So both should work and produce 
similar timecode files, if frame rate is the only variable in 
calculating time codes. But they don't.

The problem could be in Aegisub, of course. I'll ask from that end as well.

**Comment by archivisth** [comment]
The problem occurs only at 29.97 fps. I suspect Aegisub's calculation algorithm accumulates errors due to roundoff, because the mkvmerge-generated timecode file works out to 29.97 fps exactly. This can be closed; thanks for your help. Maybe 29.97 fps and AVI source should generate a warning for now...
