### ISSUE TITLE
Possible Bug: subtitle on ordered chapter was missing when remuxing from dual audio to single audio

### ISSUE THREAD

**Issue by B3H3M0T** [mbunkus/mkvtoolnix#1180]
when i try re-muxing from dual audio to single audio all subtitle for opening and ending was missing.
it happen on some ordered chapter video.
sample :  http://hi10anime.com/hataraku-maou-sama/hataraku-maou-sama/
note: please login to download the sample, ep 01 and 12 wasnt OC

**Comment by mbunkus** [comment]
I'm sorry, but I'm not going to create yet another account in yet another forum only to download a sample file. If you want me to take a look then please upload the file to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by sneaker2** [comment]
Note 2 things:
1. The common players supporting mkv file linking via ordered chapters require all files to have exactly the same number, types and order of tracks. If you remove one track from one file you have to remove it from all the other files as well or playback will become erratic.
2. When remuxing mkvmerge sets new unique segment ids. You can use the header editor to assign the old ids back into the new files after removing the track. (Or set the segment id while muxing. See mkvmerge doc for that.)

**Comment by mbunkus** [comment]
As you're not responding and as I consider it likely that you've encountered the points sneaker2 made I'm going to close this bug as invalid.
