### ISSUE TITLE
MKVInfo 7.8.0 returns wrong exit code

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1182]
When executing mkvinfo (v.7.8.0) with a non-existent mkv file, it displays the error statement
"*(MKVInfo) Error: Couldn't open input file does_not_exist.mkv (open file error)*."

However, the exit code mkvinfo returns in this situation is 0, although the correct exit code should be **2**.

mkvmerge, mkvpropedit and mkvextract do indeed return the correct exit code 2 when given the name of a non-existent mkv file. Only mkvinfo seems to be affected by this issue.

My environment:
MS Windows 7 Pro x64
MKVtoolnix 7.8.0 x86 (32-bit)

**Comment by mbunkus** [comment]
Thanks for the report.
