### ISSUE TITLE
Error messages go to standard output instead of standard error

### ISSUE THREAD

**Issue by matsp888** [mbunkus/mkvtoolnix#1185]
I have noticed that error messages from mkvextract and mkvpropedit go to standard output instead of standard error. I haven't checked mkvmerge, but I suppose it's the same there. What's the rationale behind this behaviour?

**Comment by matsp888** [comment]
Well, the main issue is that for example mkvextract doesn't differentiate between the tags output with 'mkvextract tags <file>', and error messages. They will both go to the same stream.

**Comment by mbunkus** [comment]
Way back when I decided not to use `stderr` as it makes parsing for frontends somewhat easier. Or so I thought. Nevertheless, it's not »wrong« per se, it's just not following standard Unix conventions.

Anyway, this won't change as it would break every tool out there that parses the output of one of the MKVToolNix tools.

**Comment by matsp888** [comment]
Yes, Moritz, I can see why you won't change the behaviour. Thanks for the reply.
