### ISSUE TITLE
icons/desktop entries/etc... do not install unless wxwidgets is enabled

### ISSUE THREAD

**Issue by codyopel** [mbunkus/mkvtoolnix#1188]
If compiling with configure options `--enable-qt --disable-wxwidgets` icons, desktop entries, etc... aren't installed.  I guess this is because the `Rakefile` was written in such a way that it assumes if wxwidgets is disabled the GUI is disabled (pre QT interface).

**Comment by mbunkus** [comment]
Thanks for your report. Your guess is pretty much spot-on.
