### ISSUE TITLE
Cannot extract Speex streams

### ISSUE THREAD

**Issue by marillat** [mbunkus/mkvtoolnix#1190]
Hi,
From bug report https://bugs.debian.org/764168

mkvtoolnix fails to extract Speex streams.

Example is this recording:
http://talks.copyninja.info/debian/bangalore-meetup/4th_October/

Extension for that file is spx but really it is a Matroska file, created
on a Jolla phone using Gstreamer (as is hinted as metadata in the file).

$ mkvextract tracks recording-20141004145141.spx 0:audio.spx 
Error: Extraction of track ID 0 with the CodecID 'A_SPEEX' is not supported.

**Comment by mbunkus** [comment]
Speex is currently not supported at all. I don't have any plans on adding support for this any time soon.

**Comment by sneaker2** [comment]
What would you extract it to, anyways? Ogg container?

**Comment by mbunkus** [comment]
I don't know; I haven't looked at Speex at all yet. I'd chose the method that Speex usually uses; it that is Speex-on-Ogg then that's what I'd chose. But like I said: a lot of other stuff to do.

**Comment by mbunkus** [comment]
I'm sorry, but I've decided not to work on this. Speex is outdated technology (even [Xiph](http://www.speex.org/) advises to switch to Opus), its storage in Matroska has never been specified nor implemented by anything but GStreamer. I don't see the value of spending my time here.
