### ISSUE TITLE
--default-language odd behavior

### ISSUE THREAD

**Issue by marillat** [mbunkus/mkvtoolnix#1191]
Hi,
From bug report https://bugs.debian.org/776651

As per mkvmerge man page:

[...]
       --default-language language-code
           Sets the default language code that will be used for all
tracks unless overwritten with the --language option. The default
language code is 'und' for 'undefined'.
[...]

However it does not seems to actually do anything. Steps:

$ wget http://downloads.dvdloc8.com/trailers/divxdigest/simpsons_movie_trailer.zip
$ unzip simpsons_movie_trailer.zip
$ mkvmerge --default-language fre -o /tmp/bla.mkv  The\ Simpsons\
Movie\ -\ 1080p\ Trailer.mp4
$ mkvinfo /tmp/bla.mkv | grep Lan
|  + Language: und
|  + Language: und

I would have expected the behavior to be equivalent to:

$ mkvmerge --language 0:fre --language 1:fre -o /tmp/bla.mkv  The\
Simpsons\ Movie\ -\ 1080p\ Trailer.mp4
$ mkvinfo /tmp/bla.mkv | grep Lan
|  + Language: fre
|  + Language: fre

So there is either a bug in mkvmerge or a man page issue.

**Comment by mbunkus** [comment]
The man page is wrong. The language set via `--default-language` is the one that's used if the source container doesn't its own language and if there's no corresponding `--language` command-line option. It's basically the fall-back option.

I'll fix the description.
