### ISSUE TITLE
New GUI, property window show scroll-bar without reason

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1193]
The properties window in the Input tab shows a scroll-bar, even if the window is maximized and there is no reason to scroll as all options are visible.

Sure, a very minor annoyance.

**Comment by mbunkus** [comment]
This has already been fixed :) But thanks for reporting it anyway.

**Comment by bastik-tor** [comment]
Well, I tried ```mkvtoolnix-64bit-7.9.0-build20150511-729-d7e14f0``` which apparently did not include the fix, as it was still shown to me.

**Comment by mbunkus** [comment]
That's the build that should contain the fix. My problem was that I couldn't test it as even in maximized state the input panel was higher than my desktop resolution allowed for.

**Comment by mbunkus** [comment]
Can you actually make the MKVToolNix GUI window so high that you cannot scroll in the input tab anymore?

**Comment by bastik-tor** [comment]
I think I am able to do so. The resolution is 1920x1080 (That's a 16:9 resolution if anyone cares).

To clarify, I added a screenshot. On the far left at the very bottom, the thingy that has been captured is part of the windows start button, not glitch in MKVToolNix. BTW. It also shows the black bar being longer, but that's beside the point.

As you can see all options are visible, but the scroll-bar is still there. Please note that the property window can be scrolled up and down for a pixel or two. (When not maximized it can be scrolled up and down, too, but then I have to, if I want to reach the option at the bottom)

![mkvtoolnix gui v7 9 0 birds 64bit_2015-05-12_20-06-22](https://cloud.githubusercontent.com/assets/1449429/7594670/8b89114a-f8e2-11e4-8fab-ea2d9cce5a05.png)

**Comment by mbunkus** [comment]
Try scrolling with the mouse wheel up and down, please. If the panel moves then the scroll bar being shown is correct. If it doesn't move at all then the scroll bar shouldn't be shown, obviously :)

**Comment by mbunkus** [comment]
I've just given this a try on Linux by creating a VNC server with a height of 2048 pixels. If I make the window large enough then the scroll bar does indeed disappear – just as it's intended. I therefore consider the issue fixed.
