### ISSUE TITLE
add option for selecting all tracks of a specific type

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1197]
Currently it is possible to select them all, enable or disable them all.

It would be nice to see "enable/disable all of this type". Maybe even more, depending on what is useful.

**Comment by mbunkus** [comment]
So far I haven't had any requests in this direction at all. I'm therefore closing the issue for the time being and will investigate it again if requests do come in.

**Comment by mbunkus** [comment]
Oh wait, the »select all of specific type« option is one I actually want to implement. I'll re-open and change the title accordingly.

**Comment by remuxer32** [comment]
> So far I haven't had any requests in this direction at all.

Well, it doesn't mean that there are no users who favour (furtively) such ideas. So: they are. Aye! :)

**Comment by bastik-tor** [comment]
> So far I haven't had any requests in this direction at all.

This issue could be one reason for it. I'm not sure how most people handle this, but if a project has a bug-tracker with feature requests I usually check there, before requesting something. (This works only well for lists that aren't too long and if I understand the request correct.) Here it seems that there is an issue that asks for something and if I hadn't opened it I would have waited to see what comes out of it. Maybe I'd left a comment, but if I had to register first the likelihood that I wouldn't have is much lower.

I wouldn't have replied, since you re-opened it already, but first I was confused to see that it got closed and then I was not sure if I had forgotten to include an actual example, since it was just based on your reply to my email, which had more details.

»select all of specific type« seems really useful.

**Comment by mbunkus** [comment]
My experience is that no matter how many bug reports there are people will always open yet another one or email me directly, even though there are bugs for that already. What I'm saying is that there has been no suggestion here in this bug, no additional bugs have been opened, no one's posted on Doom9's forum (where a lot of in-detail Matroska discussion takes place) about such functionality, no one has commented on my blog and no one has sent me an email asking for specific functionality. This is usually a pretty solid indicator that it isn't that important to people.

Another possibility I see is that people would like to see »select all of specific type« and that that would be sufficient; as this functionality is the only one actually listed in this issue it might have been enough for them.

Like I said: I will implement »select all of specific type«, then I'll close it. Of course there are tons of schemes for track selection I could theoretically implement, but that doesn't mean that those would actually be all that useful; therefore I won't invest any more time than I think is necessary at this point.

**Comment by mbunkus** [comment]
Implemented in c29482a4ec17ed327ca2066cf6accd53dc4eeb27.
