### ISSUE TITLE
Decide on having a status bar

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1199]
There is still space to inform users about things to note, like a successful merge, warnings or errors. Or like you already said, Jobs pending execution and the like.

**Comment by mbunkus** [comment]
The status bar is already present, it just isn't used much yet (apart from the muxing progress indicators on the right). The solution to #1196 will probably involve the status bar, too.

**Comment by mbunkus** [comment]
See also [GUI: show number of warnings/errors in the status line](/mbunkus/mkvtoolnix/commit/a6c5f22ba99ceeb9c80cd96b48fefd444331ab86), [GUI: context menu entries for acknowledging warnings and errors](/mbunkus/mkvtoolnix/commit/ded994b34388c3e304983385ecd16472657d67bc)

**Comment by bastik-tor** [comment]
By the looks of it everything here is done:
- (Successful) merge indicator -> Check (Progress bar stays at 100%)
- Warnings & Errors -> Check
- Pending jobs -> Check

For me the ticket could be closed, unless there is something more for what the status bar should be used. Things like the estimated time to complete the current and/or all jobs, name of the current job, could be useful, although it might be a fine line between presenting reasonable information and cluttering the interface with too much of it.

**Comment by mbunkus** [comment]
Those two are the main issues that I'm still undecided on. I have given thought to both, but so far I'm leaning towards not implementing them and leaving some room for non-static messages.

**Comment by mbunkus** [comment]
Closing this for the time being. The status bar should be good as it is right now, at least for the next release.
