### ISSUE TITLE
mmg.exe can't be run on WinXP

### ISSUE THREAD

**Issue by GCRaistlin** [mbunkus/mkvtoolnix#1201]
mmg.exe can't be run on WinXP. The following error is displayed:
The procedure entry point RegGetValueA could not be located in the dynamic link library ADVAPI32.dll.

**Comment by mbunkus** [comment]
Duplicate of #1187 .

**Comment by mbunkus** [comment]
Huh… issue 1187 has been delete. Unfortunately.

Windows XP is not supported anymore and hasn't been for close to a year now. That older versions of MKVToolNix still ran was incidental.

See the [list of supported operating systems and versions](/mbunkus/mkvtoolnix/wiki/Officially-supported-operating-systems-and-versions).

**Comment by GCRaistlin** [comment]
I believe it's worth to reflect this in the changelog.
