### ISSUE TITLE
After trying to clear default-flag for subtitles using mkvpropedit mkvinfo shows EbmlVoid

### ISSUE THREAD

**Issue by andwe** [mbunkus/mkvtoolnix#1202]
I used the following cammand line:
mkvpropedit --edit track:s1 --set flag-default=0

After that I checked the result with mkvinfo. 
But instead of getting a set of data starting with
  |+ Segment tracks
I got only one line with
  |+ EbmlVoid (size: 1501)

It seems to be the same problem as in this issue:
https://github.com/mbunkus/mkvtoolnix/issues/1121

I tried it with the folling program versions:
   mkvpropedit V7.9.0 ('Birds') 32 bit and 64bit
   mkvinfo V7.9.0 ('Birds')     32 bit and 64 bit

**Comment by mbunkus** [comment]
This is not a bug, it's just how the Matroska file format works. Please read https://github.com/mbunkus/mkvtoolnix/wiki/All-tracks-vanished-after-mkvpropedit-or-header-editor
