### ISSUE TITLE
.SRT easy extraction

### ISSUE THREAD

**Issue by g3672353** [mbunkus/mkvtoolnix#1203]
Could you set an option in mkvmergeGUI to extract .SRT/Audio/Video by right clicking on the track? Several subtitles are only found inside the .mkv

Muxing is taking almost 50 minutes to complete 7gb files. Is it normal, since it doesn't re-encode the file? My computer is not the best out there and I would just like to know if it takes so long on fast computers.

**Comment by mbunkus** [comment]
No, sorry. mkvmergeGUI is not developed any more. The new GUI, MKVToolNix GUI, will most likely receive an extraction mode, but that is still a while off. 

Yes, muxing such large files may take that long.

**Comment by hurda** [comment]
50 minutes for 7GB comes down to about 3MiB/s.
Either g3672353 is reading from and writing to a horribly slow flash-drive, or there are bigger issues with the machine.
