### ISSUE TITLE
feature request: add a setting to let mkvtoolnix-gui use system's native ui style or make this default

### ISSUE THREAD

**Issue by hrzhu** [mbunkus/mkvtoolnix#1205]
I'm using Xfce4 and I always prefer qt programs to use gtk+ style ui. mkvtoolnix-gui currently doesn't provides such a setting. I can run mkvtoolnux-gui with `export QT_STYLE_OVERRIDE=gtk+` and  `export XDG_CURRENT_DESKTOP=xfce` to let it use gtk+ sytle ui and gtk+ style file dialog. But adding these two line in `~/.profile` causes some icons missing in my DE. It would be nice if mkvtoolnix can have such setting or even make this behavior default. I know VLC has such setting but it uses qt4. Not sure if this can be done in qt5.

**Comment by mbunkus** [comment]
Hmm, maybe. As I'm not using XFCE myself this has a pretty low priority for me.

If someone else were to provide a patch I'd happily merge it, though. I'm just not going to spend time on it myself any time soon.

**Comment by mbunkus** [comment]
Some more information. The GUI only forces a particular style on Windows but not on Linux. There it just leaves the choice to Qt. Therefore I'm pretty sure that it's a matter of your Qt configuration which style is used, and it's not the application's job to get involved in this decision. Global configuration for Qt's style is there for exactly your use case: to have all Qt 5 applications look identical and according to your preference without having to configure each application separately.

The [Arch Linux Wiki](https://wiki.archlinux.org/index.php/Uniform_Look_for_Qt_and_GTK_Applications#Qt5_styles) pretty much states the same thing; Qt 5 should already do all that's required automatically if the application doesn't interfere (which my GUI doesn't), and setting `QT_STYLE_OVERRIDE` is the appropriate answer if Qt 5 itself gets it wrong.

I will therefore close this issue as invalid.

**Comment by mbunkus** [comment]
Also note that the value is supposed to be `gtk` and not `gtk+` according to the Arch Wiki. You should also be able to execute `mkvtoolnix-gui -style gtk` if you don't want to set that environment variable.

**Comment by hrzhu** [comment]
Yeah, you're right. I can confirm that if I run mkvtoolnix-gui in XFCE session it uses native gtk style and gtk file dialog. I usually use awesome WM and only log into XFCE when I want to play games that doesn't run well in awesome. 

For the sake of information, if Qt doesn't recognise your WM/DE, you can set `QT_STYLE_OVERRIDE=gtk`  or run mkvtoolnix-gui with `-style gtk`(gtk+ probably also do) to let mkvtoolnix use native gtk sylte. You might also need to set `XDG_CURRENT_DESKTOP` to make mkvtoolnux use native file dialog.  I set it to `xfce` at first and it does the job but later I log into XFCE sesstion and find some icons missing. I remove the setting in `~/.profile` and check the environment variable. It should be `XFCE`. So putting `export QT_STYLE_OVERRIDE=gtk` and `export XDG_CURRENT_DESKTOP=XCFE` in my `~/.profile` make mkvtoolnix look consistent with other gtk programs and doesn't affect XFCE sessions.
