### ISSUE TITLE
Ensuring output file name uniqueness does not always work

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1206]
As reported via email: if »make output file name unique« is checked then the output file name is not (always?) made unique by postfixing it with a running number.

**Comment by bastik-tor** [comment]
Can you give a little context to when this is happening?

When I load ```abc.mp4``` the new GUI suggest ```abc.mkv```. If I start muxing, the file is written. If I start muxing again, the file is overwritten. (Sure it is, prompting on overwriting is not implemented).

When I load ```abc.mp4```, mux it to ```abc.mkv```, create a new job, load abc.mp4 again the new GUI suggests ```abc (1).mkv```.

**Comment by mbunkus** [comment]
Unfortunately I cannot. All I've received via email is that short description that I've posted above. I haven't investigated this myself yet, though, so it's quite possible that the user was wrong and the function is working normally.

**Comment by bastik-tor** [comment]
When I use the job queue with two files from some source that have the same name and the destination is set to  "previously used.." the GUI suggests the same name for both files. If I run both jobs the first file gets overwritten. Would you consider that a bug?

I'm not sure when "Ensure the file name is unique" should apply. If it applies to writing the file than it is not working as expected by me. If it applies to the suggestion it makes while creating jobs, it seems to be working.

**Comment by mbunkus** [comment]
The old GUI worked the same way. The uniqueness is checked each time the configuration is modified (when you add or remove a file in the merge tool, or if you toggle WebM mode, for example). The old GUI's job queue didn't verify uniqueness the moment the job is started, nor where the file names in the queue checked – only files existing on the hard drive at the moment the output file name was modified.

I don't consider this a bug but rather a limitation of what such a feature can realistically do without becoming extremely confusing for the user.

**Comment by bastik-tor** [comment]
I think the tooltip is clear enough on what it is supposed to do. Though the word ```Ensure``` seems quite strong and may makes believe that it would actually ensure uniqueness.

Mainly I was just curious about what triggers this issue, if anything. I'll wait for more input from the reporter, if any.

**Comment by mbunkus** [comment]
I cannot reproduce this and will therefore close the issue.
