### ISSUE TITLE
Header Editor: Communicate that the reset button applies to the current value

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1212]
When a file is loaded in the header editor (new GUI) upon selecting any entry a button with the label ```reset``` is shown. I had assumed this button would reset all changes (to all values).

Options I see:
- WONTFIX (Maybe it is easy to understand, it is just me who doesn't.)
- Label it "Reset [this] value". (Where [this] is optional)
- Add a tooltip "Resets the currently selected value".
- Add another button with the label "Reset all" (I am not in favor of having another button for this purpose)

The options are not mutually exclusive.

**Comment by mbunkus** [comment]
You've got a point; thanks. I was just copying the old GUI where the button is labeled »Reset« as well, but that's no reason not to improve upon it. I will likely chose a more descriptive label.

I will not add another button »reset all«. For such functionality there's a menu entry already, »reload«, and I consider that menu entry to be the correct place for such an option – in close proximity to »load«/»save«.

**Comment by bastik-tor** [comment]
(I was replying to another issue. Luckily, because I could have created two more issues.)

As I said I am not in favor of adding a button for that purpose

I planned to open a ticket to ask for a button in the header editor to save the changes to file. (I was aware about it being in the menu.)

Further I planned to open a ticket to ask for a button in the Chapter Editor to save, although that seems even harder to place somewhere and there are more options.

The reason for it being two issues is that one could be dismissed without killing of the other. Do you see any chance for this to happen? If, yes I create the desired amount of issues. If no, at least one issue that doesn't have to be opened and closes as WONTFIX.

**Comment by mbunkus** [comment]
I intentionally decided against having many buttons. I will not implement »save« buttons in either editor for the time being. Having some functions available as buttons will make users wonder why those functions are available as buttons and others only as menu entries.

If I decide to add some kind of buttons for all those menu entries one day it will most likely be in the form of traditional button tool bars – but at the moments I have no such plans.

**Comment by mbunkus** [comment]
To make this clearer: I'm afraid adding buttons similar to the merge tool's buttons will make the GUI more confusing to use instead of easier.
