### ISSUE TITLE
Multipule DTS-HD MA issues observed... files uploaded to FTP.

### ISSUE THREAD

**Issue by RBDaniel** [mbunkus/mkvtoolnix#1213]
So I have two test cases...

1: A merge job using a custom compressed video stream + a custom SRT + the raw DTS track from the original Blu-Ray. All tracks are loaded direct except for the audio track which is selected via the imported play list feature. (BDMV\PLAYLIST) dir.

Result:
The DTS-HD MA track is intact

Supporting Files uploaded:
Playlist-DTS-HD MA (OK).JPG
Playlist-DTS-HD MA (OK)-001.mkv

2: Is a duplicate of # 1 except that the audio track is selected directly from the m2ts stream. (BDMV\STREAM) dir.
Supporting Files uploaded:
Stream-DTS-HD MA (Not OK).JPG
Stream-DTS-HD MA(Not OK)-001.mkv

Result:
The DTS-HD MA track is removed leaving only the DTS Core.

----------------------------------------------------------------------------

Troubleshooting steps I've tried:

1. I've also uploaded a TXT file with the: mkvmerge.exe --output-charset UTF-8 --identify-for-mmg for each test MKV - DTS-HD MA (OK & Not OK).txt - both audio tracks seem to match.

2. In both cases I've double checked my command line variables:
--disable-track-statistics-tags --clusters-in-meta-seek --engage no_cue_duration --engage no_cue_relative_position --disable-lacing --engage no_simpleblocks

3. And I made sure the box under "Format specific options --> Reduce to audio core" is UNCHECKED.

4. I've de-mux the DTSHD audio track with tsMuxer and HDBR Stream Extractor and verified that it was intact with Mediainfo and it plays in VLC. I tried merging these tracks into my MKV with the same result as in test case # 2 both times.

----------------------------------------------------------------------------

Observations:

I believe that mkvmerge is confused by both DTS-HD MA and Core tracks being in 5.1 and can't distinguish or doesn't know how to properly identify the individual streams so it chooses the Core and drops the HD-MA. Other movie titles work fine as long as Core is 5.1 or 6.1 and the HD-MA is 7.1 channels.

----------------------------------------------------------------------------

Other thoughts:

Yes, I could just merge this title using the test case in #1 however, this brings me to an off topic point and I don't know if it's related or not but I'm sure some performance monkey will point it out if it already hasn't been. In test case # 1 the merge times are in excess of 40min where as in test case # 2 it's roughly on average 15min. That's too big a difference to ignore. These times are highlighted in my screenshots.

**Comment by RBDaniel** [comment]
Well I guess I should have let it run it's course before saying something. I let the merge finish using the settings from test case # 1. The "estimated" timer stay at around 40 min and then started counting down normally. I walked away from my computer. When I came back it said that the merge took only 15min. hahaha... so my "other thoughts" are irrelevant.

**Comment by mbunkus** [comment]
If you want me to do anything about this at all (including guessing what happens) I will need access to the Blu-ray disc. Neither the screenshots nor the resulting Matroska files are really helpful for debugging.

**Comment by RBDaniel** [comment]
I would be more then happy to debug anything you'd like and provide the details. Seems a better alternative than trying to upload a 40Gb bluray image to your FTP server. :)

**Comment by mbunkus** [comment]
That won't work. I have no idea what the problem might be, and in order to get an idea I will need to examine both the m2ts input files as well as the play list files and compare how and why mkvmerge acts differently depending on which file is used – and for that I'll need to run it in a debugger. Hence me asking for access to the disc.

I can understand that you don't want to upload so large an amount, but I really cannot help you without access to the disc.

**Comment by RBDaniel** [comment]
Actually I thought I was helping you by reporting this issue. :) I really have no idea why it's doing it. By submitting screen shots, and uploading samples of things you've asked for in other bug reports I actually hoped that maybe I was doing something wrong or overlooking something stupid. I don't have a problem uploading a copy of the disk if it helps you make this product better.

**Comment by mbunkus** [comment]
Well, if you compare the screenshots you can see that, when you use the play list file, mkvmerge reads not only 00074.m2ts but also 00073.m2ts and 00075.m2ts – and 00073.m2ts is the first one to be processed. If you want to have comparable results then your actions will have to be comparable, meaning if you don't use the play list file then you have to »add« the 00073.m2ts and »append« the other two files.

Please try that before actually uploading.

**Comment by RBDaniel** [comment]
Bleh... you're absolutely right. This is the first time I've had to do it this way. I've merged together other bluray sourced movies using my method but this is the first title to exhibit this kind of behavior.

Thanks for the help!

**Comment by mbunkus** [comment]
You're welcome. Any particular reason you're preferring to use the .m2ts directly instead of the play list? I have a lot of discs which split their main feature across multiple .m2ts, sometimes twenty or more .m2ts files…

Anyway, I'm closing this as invalid.

**Comment by RBDaniel** [comment]
I'm a creature of habit I guess... the playlist import feature was only added about 2 years ago? I've been buying and digitally ripping movies into my media archive shortly after getting my first DVD player about 15 years ago. :P

**Comment by mbunkus** [comment]
Yeah, it hasn't been available for long.Since 2013-02-03, to be exact.

Anyway, I strongly suggest you always use play lists from now on :)
