### ISSUE TITLE
failure trying to build on OpenBSD

### ISSUE THREAD

**Issue by brad0** [mbunkus/mkvtoolnix#1215]
Trying to build mkvtoolnix 7.9.0 on OpenBSD I am seeing a build failure of..

```
c++ -Wall -Wno-comment -Wfatal-errors -Wlogical-op -D_FILE_OFFSET_BITS=64 -DMTX_LOCALE_DIR=\"/usr/local/share/locale\" -DMTX_PKG_DATA_DIR=\"/usr/local/share/mkvtoolnix\" -DMTX_DOC_DIR=\"/usr/local/share/doc/mkvtoolnix\" -I/usr/X11R6/include -I/usr/local/include -fPIC -std=c++11 -Wnon-virtual-dtor -Woverloaded-virtual -Wextra -Wno-missing-field-initializers -I/usr/local/include/X11/qt5/QtWidgets -I/usr/local/include/X11/qt5 -I/usr/local/include/X11/qt5/QtPlatformSupport -I/usr/local/include/X11/qt5/QtGui -I/usr/local/include/X11/qt5/QtCore -I/usr/local/include -O2 -pipe -I. -Ilib -Ilib/avilib-0.6.10 -Isrc -Ilib/utf8-cpp/source -Ilib/pugixml/src -c -MMD -MF ./rake.d/dependency.d/tmp/src_merge_mkvmerge_o.d -o src/merge/mkvmerge.o -x c++ src/merge/mkvmerge.cpp
In file included from src/common/strings/formatting.h:22:0,
                 from src/merge/mkvmerge.cpp:53:
src/common/strings/editing.h:46:35: error: 'va_list' has not been declared
 int get_varg_len(const char *fmt, va_list ap);
                                   ^
compilation terminated due to -Wfatal-errors.
```

**Comment by mbunkus** [comment]
As I don't have OpenBSD I cannot really help you with compilation. Try to find out which header file includes `va_list` on OpenBSD and include it. If it works then please provide a patch.

**Comment by brad0** [comment]
It looks like the header that should be included for va_list is stdarg.h.

http://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdarg.h.html

Adding that header in and the build is continuing.

**Comment by brad0** [comment]
Oh, not being familiar with C++ maybe the header that should be included is cstdarg.

**Comment by mbunkus** [comment]
Have you actually tried adding cstdarg and compiling? Does it work with just that one include, or does it abort somewhere else?

**Comment by brad0** [comment]
I have added the header to src/common/strings/editing.h and the build is still going right now.

**Comment by mbunkus** [comment]
As a matter of fact I have an even better solution: remove the line declaring `get_varg_len()` from `editing.h`. I've just checked and that function isn't used anymore, neither is it implemented in `editing.cpp`. I'll also remove the line on my end in a bit.

**Comment by brad0** [comment]
Ok, I will use that instead and update the ticket with the results. I have restarted the build.

**Comment by brad0** [comment]
Next issue...

```
c++ -Wall -Wno-comment -Wfatal-errors -Wlogical-op -D_FILE_OFFSET_BITS=64 -DMTX_LOCALE_DIR=\"/usr/local/share/locale\" -DMTX_PKG_DATA_DIR=\"/usr/local/share/mkvtoolnix\" -DMTX_DOC_DIR=\"/usr/local/share/doc/mkvtoolnix\" -I/usr/X11R6/include -I/usr/local/include -fPIC -std=c++11 -Wnon-virtual-dtor -Woverloaded-virtual -Wextra -Wno-missing-field-initializers -I/usr/local/include/X11/qt5/QtWidgets -I/usr/local/include/X11/qt5 -I/usr/local/include/X11/qt5/QtPlatformSupport -I/usr/local/include/X11/qt5/QtGui -I/usr/local/include/X11/qt5/QtCore -I/usr/local/include -O2 -pipe -I. -Ilib -Ilib/avilib-0.6.10 -Isrc -Ilib/utf8-cpp/source -Ilib/pugixml/src -c -MMD -MF ./rake.d/dependency.d/tmp/src_common_dts_o.d -o src/common/dts.o -x c++ src/common/dts.cpp
src/common/dts.cpp: In function 'bool mtx::dts::detect(const void*, int, bool&, bool&)':
src/common/dts.cpp:917:61: error: 'swab' was not declared in this scope
       swab((char *)buf[cur_buf], (char *)buf[cur_buf^1], len);
                                                             ^
compilation terminated due to -Wfatal-errors.
```

**Comment by brad0** [comment]
The declaration for swab() comes from unistd.h. Not sure what header would be an appropriate place to add unistd.h at the moment.

**Comment by mbunkus** [comment]
Just put it into the affected .cpp file(s).

**Comment by brad0** [comment]
Ok, so I added

```
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
```

to src/common/dts.cpp, src/input/r_dts.cpp and src/input/r_wav.cpp.

**Comment by mbunkus** [comment]
Anything else, or did compilation succeed after those changes?

**Comment by brad0** [comment]
Also src/common/common.cpp for the use of nice(3). That is all.

**Comment by mbunkus** [comment]
Alright, thanks. I've pushed a potential fix. Can you please pull and re-compile the whole package?

Also: are you compiling with/without the following features:

- wxWidgets
- Qt
- libmagic

**Comment by mbunkus** [comment]
Damn, I made a mistake… will push a fix in a moment.

**Comment by mbunkus** [comment]
Done.

**Comment by brad0** [comment]
At the moment I am building with libmagic, Qt and only the new UI.

I could at least build test with wxWidgets and the current / "old" UI to make sure any build issues are dealt with.

**Comment by brad0** [comment]
Ok, with the wxWidgets support enabled I did not need any additional patches for the build to complete.

Thanks for commiting all of these bits so far.

BTW, I also had this patch in my port / package that I found from the FreeBSD port / package....

```
--- Rakefile.orig	Sun May 10 05:04:26 2015
+++ Rakefile	Wed May 27 03:12:35 2015
@@ -56,7 +56,7 @@ def setup_globals
   $application_subdirs     =  { "mmg" => "mmg/", "mkvtoolnix-gui" => "mkvtoolnix-gui/" }
   $applications            =  $programs.collect { |name| "src/#{$application_subdirs[name]}#{name}" + c(:EXEEXT) }
   $manpages                =  $programs.collect { |name| "doc/man/#{name}.1" }
-  $manpages                << "doc/man/mkvtoolnix-gui.1" if !$build_mkvtoolnix_gui
+  $manpages                << "doc/man/mkvtoolnix-gui.1" if $build_mkvtoolnix_gui
 
   $system_includes         = "-I. -Ilib -Ilib/avilib-0.6.10 -Isrc"
   $system_libdirs          = "-Llib/avilib-0.6.10 -Llib/librmff -Lsrc/common"
```

My understanding of the code is that the man page is currently installed only if the GUI is not enabled instead of only being installed if it is enabled, no?

**Comment by mbunkus** [comment]
Oh, you're quite right. Thanks for pointing it out; I'll fix it.
