### ISSUE TITLE
merge file with different resolutions

### ISSUE THREAD

**Issue by drakkan** [mbunkus/mkvtoolnix#1216]
Is this supported?

Here are two files:

http://195.250.34.59/temp/1_1.mkv
http://195.250.34.59/temp/1_2.mkv

the first one is 640x480 h264, the second one is 800x600 h264 the wanted result is one file with a duration calculated as sum of the first + second file and that play the first file and the second one. mkvmerge produce a file with wrong duration and all tested player show only one track

**Comment by mbunkus** [comment]
No, this is not supported as it isn't allowed by the Matroska file format.
