### ISSUE TITLE
Error Code 2: does not contain a track with the ID 268435456

### ISSUE THREAD

**Issue by KirkMartin** [mbunkus/mkvtoolnix#1218]
I've used mkvmerge on a few dozen different DVD's, but lately I've been getting the error above (error code 2: does not contain a track with the ID 268435456) on several discs.  It's always the same track ID on different disc's.  Any thoughts on what could be causing it?  I tried cleaning the DVD's and copying the files to mkv again, but get the same errors on the same discs.

I use  Win 7 (64-bit) and use MakeMKV to rip the file from the DVD; then have been using MergeMkv to combine the various episodes of a TV season into one mkv file.  I thought perhaps it was a bad disc, but I've gotten the exact same error (down to the same track ID) and multiple files.

Thanks for your help,
Kirk

**Comment by mbunkus** [comment]
What's the command line you've used? If you're using one of the GUIs: they can show you the equivalent command line; look for a corresponding menu option.

**Comment by KirkMartin** [comment]
I don't believe I used any command line options - I just used the stock settings. But I'll double check that when I get home this evening.

On May 31, 2015 1:30 PM, Moritz Bunkus <notifications@github.com> wrote:
What's the command line you've used? If you're using one of the GUIs: they can show you the equivalent command line; look for a corresponding menu option.

---

**Comment by mbunkus** [comment]
Then I will need access to the source file(s) in order to track it down. Can you please upload them to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server)? Thanks.

**Comment by mbunkus** [comment]
Closing due to lack of feedback and not being able to reproduce it locally. If you want to continue working on this then please upload the files as requested and post here. Thanks.
