### ISSUE TITLE
language drop downs not updated after change in common languages preferences

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1224]
After changing the »common languages« in the preferences the GUI should update the corresponding drop-down boxes immediately. Currently they're only filled when starting the GUI.

The common countries and character codes are most likely affected in the same way.

**Comment by mbunkus** [comment]
Not fixed yet.

**Comment by remuxer32** [comment]
It seems that we overlooked one drop down box that doesn't update automatically when changing language interface. I mean the »Stereoscopy« position. See: 

![stereoscopy](https://cloud.githubusercontent.com/assets/10992208/8889919/2b794964-32ee-11e5-9a88-6fee227cbd82.png)

I have to restart a program if I want to see the »Stereoscopy« drop down box in a proper language. So: will you reopen this issue or should I create a new one for that?

**Comment by mbunkus** [comment]
Thanks for pointing it out. No need to create a new issue for it. We'll handle it here.
