### ISSUE TITLE
mkvmerge loses last chapter from BD playlist (mpls)

### ISSUE THREAD

**Issue by clburch1** [mbunkus/mkvtoolnix#1226]
I recently upgraded to 7.9.0 from 6.9.1 64bit. Have noticed that when using anything from 7.6.0 on (the next one i tested against) that the number of chapters is off by one which is always the last chapter at end of movie or at least should be. For example one movie has 43 chapters and in 6.9.1 is shows 43. But when using 7.9.0 is shows 42 chapters instead and after muxing the mkv will have only 42 chapters in it instead of 43 as defined in the playlist. It also happens even if the playlist shows 2 chapters, this version only shows 1 chapter (the beginning). 

This on Windows 7 64bit and using the mkvmerge GUI. MKVToolNix shows the same missing chapter which makes sense.

I know i can use the workaround of using an imported xml file if i want to override or add new chapter stops but should be working regardless which method i use.

**Comment by mbunkus** [comment]
Thanks for your report.

mkvmerge is actually designed to remove the very last chapter if that last chapter entry is within five seconds of the end of the whole movie. A lot of Blu-ray discs have one such chapter entry at the very end, and from a usage perspective such chapter entries don't make much sense – if you jump to it all you usually see is one or two seconds of black screen followed by the end of the movie.

Please check whether the dropped entry matches this description. If so this is working as intended and not going to change.

**Comment by clburch1** [comment]
Thanks for quick response. I can see your point in doing this however there are times for example that you wish it was there. Depending on the player you are using when the request for the next chapter stop comes it won't advance because that last chapter stop is not there. I have seen movies that the last stop and the previous chapter stop was almost 20 to 30 minutes away from the end of the movie and that did not include a chapter at the end credits before the end of the movies. 

Another issue that surfaces is most of the marvel movies have one or more extra clips during the end credits. One of them even had a chapter stop within the last few seconds for an extra clip which i think was Avengers as they were all sitting around a table drinking beer looking at each other but not speaking (they were all tired & worn out looking). If that last chapter stop had been removed then you could not advance to it automatically.

In addition this was extra code that had to be put into the logic and maintained to handle the removal of the last chapter stop under those conditions when in reality in my opinion nothing of real value was added  as depending on the player you are using if it defaults to do nothing when you hit the next chapter button and there are none it does not advance to end of movie and does nothing or it just goes to the end of the movie which is player dependent. With the last chapter stop not being removed works regardless of player quirks.

There are times when i mux some of the special features, a lot of these will have only two chapters but i have seen that a 2 chapter feature lasted for 40 to 60 mins. Guess they want to force you to watch the whole thing. Now is there a workaround? Sure there is i could just go back to using 6.9.1 when i don't need to hassle with creating my own external chapter file to be imported or use external chapters from the .xml format with the new version. But if im muxing 10 of these files, then i need to create 10 chapter xml files to be imported with the new version so the player goes to the end to the last chapter.

**Comment by mbunkus** [comment]
Like I said, the last chapter is supposed to be dropped **only if** the chapter's timecode is within five seconds of the play list's total length. This feature was a user request.

If you have a case in which the last chapter in a Blu-ray play list and the play list's end are more than five seconds apart and where said chapter is removed by mkvmerge then that is bug. Otherwise it is a feature that's working as inteded, and the cases you've mentioned above shouldn't be affected by this at all. Players that don't allow you to advance to the last chapter in a Matroska file are simply buggy, and I don't cater to buggy players as that would be a losing game. Sorry.

**Comment by mbunkus** [comment]
Hmm, I think I'll add an `--engage` option for not dropping that last entry for people that really want or need such a feature.

**Comment by clburch1** [comment]
thanks that would be greatly appreciated, this way for folks that want it, they can enable this option and both sides of the fence are covered. Once that feature is made available please make it known how to implement it. 

It's like Insurance even though we hate making the payments, it's better to have it and not need it, than to need it and not have it.

**Comment by clburch1** [comment]
sorry hit the wrong button by mistake, and also thank you for your assistance

**Comment by mbunkus** [comment]
It hasn't been implemented yet, hence me re-opening the issue :)

**Comment by mbunkus** [comment]
No problem at all, and you're welcome.

**Comment by clburch1** [comment]
thanks
