### ISSUE TITLE
Feature Request - Default selection of tracks to same as Preferred Language Automatically

### ISSUE THREAD

**Issue by clburch1** [mbunkus/mkvtoolnix#1227]
mmg gui should default to select only tracks in the user's preferred language and if no track in the preferred language then either default all tracks to all on or all off and let user use the Toggle button and select which tracks wanted. This a great time saver if a source has a whole lot of tracks versus just a couple you want in your preferred language.

**Comment by mbunkus** [comment]
Thanks for your suggestion.

First of all the old GUI (mmg) is not developed anymore; see [here](/mbunkus/mkvtoolnix/wiki/MKVToolNix-GUI-status) for details.

However, such a feature makes sense for the new GUI as well. I will likely implement something like this, but not soon as I still have a lot of other things to work on that I consider of higher importance.
