### ISSUE TITLE
Menu for the job queue

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1228]
Every implemented section in the new GUI has a second menu entry at the top, where you are supposed to do things like opening files and saving etc. The job queue does not have such a menu, but it seems to be useful to have one.

For example, starting all jobs pending execution. The idea behind this you add all the jobs, may already start the first, add more jobs and tell mkvmerge to process the rest without having to select individual jobs for automated processing.

(To be honest, I am not such a power-user that I'd have to rely on the job queue anyway. Maybe actual power-users won't use the GUI at all.)

If automated execution of jobs from the queue is not of great concern, it might be possible to add a new entry in the merge menu. The current "Add to job queue" turns to "Add to job queue (manual)" and the new entry could be "Add to job queue (automatic)". That way newly added jobs can be processed automatically if desired by the user and a new menu for the job queue is not required.

Of course already exiting options could go into the new job queue menu, which would be consistent with the rest of the GUI.

**Comment by mbunkus** [comment]
Thanks for the suggestions.

You're actually talking about three different things/features. I'll number them for future reference:

1. An extra menu in the menu bar for the job queue
2. An option for starting all jobs pending manual start
3. Different ways of adding jobs to the queue (manual/automatic)

Regarding 1.: Currently all available actions are placed in the context menu. One thing that might make sens is to separate the actions into ones that operate on the currently selected jobs (e.g. »remove selected jobs«) and ones that operate independent of a selection (e.g. »start pending jobs« or »remove all jobs«). The independent options could then be put into such a job queue menu.

Regarding 2.: That sounds useful, and I will likely implement this.

Regarding 3.: Such a differentiation is already implemented. Clicking »Start muxing« will add a job to the queue that starts automatically while clicking »Add to job queue« will add a job that is pending a manual start.
