### ISSUE TITLE
Change how the GUIs check if they should run in portable mode

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1229]
From the bug report about the non working GUIs under Windows XP I got aware that the registry is used to check whenever it is an installation or if it is a portable version.

Based on the registry entry it is determined where the settings are stored. This could be an issue when mkvtoolnix gets installed first, but they user tries a portable version later, maybe to test new features or to check if a mis-function is related to the current settings.

I had assumed that if I run a freshly unpacked portable version, it would have fresh settings. It appears to be not too important because there are not that many options that could be changed, although default command-line switches could be used which lead to unexpected results.

Some other applications check for a ```portable.dat``` in the same folder as their binary to determine if they are supposed to be portable or not. Others have an entry within the settings of config file.

**Comment by mbunkus** [comment]
Thanks for the suggestion. Such a change sounds useful. I will likely use the »magic file in same directory« variant.
