### ISSUE TITLE
Can error messages be changed so that they can be copied?

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1230]
The only pop-up error MKVToolNix GUI throw at me was as file parsing failed in the chapter editor, because the file does not contain any chapters.

I am not sure how the pop-up error is created but under Windows 7, the text of the message can not be selected and copied. (To be pasted somewhere, e.g looking up errors on the Internet.)

Is the new GUI flexible enough to allow (partial) selection and coping the (error) messages?

(LibreOffice changed its interface as well and they made it possible to select text from their dialog windows.)

**Comment by mbunkus** [comment]
Thanks for the suggestion. I'm using Qt's built-in functions for error and warning dialogs. I currently don't have any plans for implementing my own dialogs just for such a use case even though I can see that it may be useful.

Maybe I'll do this sometime in the future, but not any time soon.

**Comment by mbunkus** [comment]
Well, that wasn't so difficult.
