### ISSUE TITLE
New GUI: add minimize & maximize button to the »playlists dialog«

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1231]
Yes, it's the similar matter like in the #1204, but this time my interest is more serious. So: could you add minimize & maximize button to the »playlists dialog«, please?

**My substantiation:**

I have been working with Blu-ray Discs for a long time. I always scan directory for other playlists. Because of the fact that there are a lot of Blu-rays that contain tons of playlists (.m2ts files), I have to always maximize window in order to navigate/select playlists as comfortable as possible. The problem is that in the new GUI, due to lack of the maximize button, I must use plenty of annoying arrows to maximize the whole window; it's very painful and, first of all, wasting my valuable time! Please note that in the old GUI those buttons are inherent:

![buttons](https://cloud.githubusercontent.com/assets/10992208/7985634/6a2bad62-0ad2-11e5-9137-707a144c27bd.png)

As you can see there are tons of playlists; that's why those inconspicuous buttons (in particular: maximize button) are so needed. Without a doubt: those buttons are very useful to save a time.

I'll be very grateful if you add them for the next (8.0.0) release. Thank you very much Mosu.

BTW: I would not mind if you would like to add them to the »MKVToolNix preferences dialog« as well. If you want, of course ☺.

**Comment by mbunkus** [comment]
Thanks for the suggestion. I'll definitely add them to the »select play list« dialog and possibly to the »preferences« dialog as well.

**Comment by mbunkus** [comment]
No minimize buttons as the dialogs are modal. Even with such a minimized dialog the rest of the application couldn't be used anyway.

**Comment by remuxer32** [comment]
Ok, I understand. Thank you very much for a quick implementation.
