### ISSUE TITLE
New GUI: set »Same directory as the first input file« as default

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1234]
First time when you install a program and go to the **»preferences«** dialog, you can see something like this:

![preferences](https://cloud.githubusercontent.com/assets/10992208/8007725/1da157b8-0b9e-11e5-8b42-1ec3d27c2119.png)

As you can see there is **»Previously used output directory«** marked as default. What does it mean? Well, it means that ALL .mkv files are/will be saved in the installation folder (usually: **C:\Program Files\MKVToolNix**). I've muxed two files and this is the proof:

![mkvtoolnix directory](https://cloud.githubusercontent.com/assets/10992208/8007961/6b667b3a-0b9f-11e5-9808-a0aeb65310f4.png)

With all due respect, but in my opinion such a situation, where output files are saved in the installation folder, is little ridiculous and even very dangerous! Why? Read my arguments please:

► Users who are not advanced may accidentally remove the whole installation folder and thereby lose ALL .mkv files that were saved in that folder
►There are very dangerous/invasive programs like »CCleander« or (in particluar) »Revo Uninstaller Pro« that are able to remove completely the whole installation folder including .mkv files as well
► Similar programs like MakeMKV or tsMuxeR never offer the installation folder as default. Usually »same directory as the first input file« is offered as default
► **And the underlying argument:** Please note that in the old GUI **»Same directory as the first input file«** is set as default (»for ages« ☺):

![old gui](https://cloud.githubusercontent.com/assets/10992208/8008883/2260ee4c-0ba5-11e5-9b5c-845e94daae52.png)

It means that experienced users, who have been using the old GUI for many years, are accustomed that their files are always saved to the same directory as the first input file. They will be in »SHOCK« when they discover that all .mkv files are placed in the installation folder. And believe me: »But they can change it in the preferences« shouldn't be considered as an argument because the basic principle should be always: **»The new GUI as friendly as possible for all«**☺.

That's why please: **set »Same directory as the first input file« as default**. Thank you very much Mosu.

**Comment by mbunkus** [comment]
»Same directory« should have been the default… I don't know why it isn't. Not on purpose. I'll change it. Thanks.

**Comment by remuxer32** [comment]
Thanks for the quick fix ☺.
