### ISSUE TITLE
The new GUI shows ZERO automatic jobs to execute if at least one job pending automatic start

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1236]
I have added two jobs to job queue and then selected them both and finally clicked on »Start selected jobs automatically«. The result is horrific:
 
![jobs](https://cloud.githubusercontent.com/assets/10992208/8018867/e0aa0eac-0c30-11e5-9a07-acecf8452514.png)

As you can see the new GUI shows ZERO automatic jobs to execute, even though one job pending automatic start. In addition, the new GUI shows 1 manual job to execute which is a nonsense because there are NO manual jobs to execute as the correct job is running already.

**Comment by mbunkus** [comment]
Meh, the numbers aren't updated when you use that function. I'll fix it. Thanks.

**Comment by remuxer32** [comment]
But that's not all ☺. There are more bugs that I will show in a couple of minutes/hours :).

**Comment by mbunkus** [comment]
Can you please try [pre-build 772](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/)? It should fix this issue.

**Comment by remuxer32** [comment]
The current status is: 

![jobs 2](https://cloud.githubusercontent.com/assets/10992208/8019192/b11f706c-0c41-11e5-94b4-790c30d0fe67.png)

So yes, everything works fine ☺. Thank you very much Mosu.
