### ISSUE TITLE
MP2 shown as "MP3"

### ISSUE THREAD

**Issue by hurda** [mbunkus/mkvtoolnix#1242]
I was testing the newly fixed support for MPEG2-Video in 7.9.0, and discovered a bug:
When adding a TV-recording, both mmg and the new GUI show MP2-audiotracks as "MP3".
Demuxing these streams and adding those to the GUIs show them as MP2.

I haven't discovered any issues during playback, so it seems to be only a cosmetic bug.

**Comment by hurda** [comment]
![mkv_mp3](https://cloud.githubusercontent.com/assets/3539609/8036354/95486e0e-0df7-11e5-8fef-c43b2f1973a4.png)

Testfiles uploaded to the FTP.

**Comment by hurda** [comment]
Output of ffprobe:
![mkv_mp3_ffprobe](https://cloud.githubusercontent.com/assets/3539609/8036840/9466f2d2-0dfa-11e5-883a-5ceb109b836f.png)

**Comment by mbunkus** [comment]
Thanks for the report & the test file. As this only affects informational display and not the muxing process itself I don't consider it to have a high priority. It will be fixed one day, but I can't say when that'll be.

**Comment by hurda** [comment]
As I discovered that .mpg files show the same behavior, I was able to test older mmg-versions, and I narrowed the regression-window down to between 6.6 (last good) and 6.7 (first bad).
https://github.com/mbunkus/mkvtoolnix/compare/release-6.6.0...release-6.7.0

Maybe the bug is in any of these:
[MP3 reader: use codec_c for common codec names ](https://github.com/mbunkus/mkvtoolnix/commit/ceafc2f53e92f5bc8427585736ae1b4b146946bb)
[MPEG ES reader: use codec_c for common codec names](https://github.com/mbunkus/mkvtoolnix/commit/bb27df4d69ddea28fb9353826489b35541a245d9)
[MPEG PS reader: use codec_c for common codec names ](https://github.com/mbunkus/mkvtoolnix/commit/f56a0d0459f4682fbbd77c057f32ae175c602e3e)
[MPEG TS reader: use codec_c for common codec names ](https://github.com/mbunkus/mkvtoolnix/commit/dc9da0fadd48a0bda8941b30021c2c5dce4a2a80)

**Comment by mbunkus** [comment]
This is the case for other container formats as well, e.g. MPEG PS or raw .MPx files.
