### ISSUE TITLE
mkvpropedit doesn't edit track properties when also changing the tags of the same track

### ISSUE THREAD

**Issue by thierer** [mbunkus/mkvtoolnix#1247]
When I try to edit both the tags and some properties of a track, like so

    mkvpropedit --tags track:v1:video.tags -e track:v1 --set display-width=1234 video.mkv

I get this warning 

    Warning: The edit specifications 'v1' and 'track:v1:video.tags' resolve to the same track with the UID ...

and mkvpropedit seems to ignore the second operation. So in this case only the tags are updated, but display-width is not set. If I change the order of the commands, the property is set but the tags are not.

Am I doing something wrong? I only found the `--tags` command to edit the tags; I don't think it's possible with the `--edit` command?

This is using mkvpropedit v7.9.0 on Linux.

**Comment by mbunkus** [comment]
Thanks for the report. This looks like a bug, or rather like two bugs.
