### ISSUE TITLE
mkvmerge/mmg/mkvtoolnix-gui crash when attaching file (minor)

### ISSUE THREAD

**Issue by wiiaboo** [mbunkus/mkvtoolnix#1249]
It looks similar to #891 but I've tried without building a GUI and it happens with `mkvmerge` too.
It's a minor issue because it's probably some issue within the compilation, since the official builds don't crash.

Example command: `mkvmerge --attach-file DejaVuSans.ttf -o test.mkv`
results in
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

System is Windows 8.1 64-bits. mkvtoolnix compiled using [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/media-suite_compile.sh#L2077-L2101) (based on Msys2)
[config.log](https://gist.github.com/wiiaboo/8c77ffeb1287cb16004e)

**Comment by mbunkus** [comment]
Can you reproduce it with the Windows binaries that I provide?

**Comment by wiiaboo** [comment]
No.
That's why I linked to the compiling script. Maybe you could tell any missing or wrong option?
Here's [build-config](https://i.fsbn.eu/pkk.txt) too.

**Comment by mbunkus** [comment]
Those options look fine. I'm sorry, but I cannot really help you. I only support the Windows binaries that I provide myself. You'll have to debug it yourself, e. g. via a debugger or by inserting debug output statements in appropriate places.
