### ISSUE TITLE
Spanish subs incorrect characters

### ISSUE THREAD

**Issue by rootsandculture** [mbunkus/mkvtoolnix#1250]
I have the original .iso image from a BD, and when tried to make an .mvk of the movie and add custom spanish subs, it add some changes in the characters, as you can see in the snapshot. But if I load the same sub into the VLC is shows correctly, as it shows when loaded in text editor. Any ideas?

![screenshot from 2015-06-19 11 10 19](https://cloud.githubusercontent.com/assets/12083250/8255150/3ed0285c-1674-11e5-8916-4dc5311093b6.png)

**Comment by mbunkus** [comment]
The subtitle file uses a different character encoding than what mkvmerge expects. You'll have to set the encoding manually in such cases in the track's properties. See https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvmerge.html#mkvmerge.text_files_and_charsets for more information.

**Comment by rootsandculture** [comment]
Fixed!. Used ISO_8859-1 as I'm using Linux and it works, thanks a lot!

**Comment by mbunkus** [comment]
You're welcome. Glad you succeeded.
