### ISSUE TITLE
Debian/Ubuntu packages missing desktop files for the GUIs

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1255]
The Debian/Ubuntu packages are missing .desktop files for mmg and mkvtoolnix-gui.

**Comment by darealshinji** [comment]
This should provide a temporary solution for it:
``` diff
--- a/debian-upstream/mkvtoolnix-gui.install
+++ b/debian-upstream/mkvtoolnix-gui.install
@@ -1,6 +1,6 @@
 src/mmg/mmg-gui                       usr/bin
 src/mkvinfo-gui                       usr/bin
 src/mkvtoolnix-gui/mkvtoolnix-gui-tmp usr/bin
-usr/share/applications/*.desktop
+share/desktop/*.desktop               usr/share/applications
 usr/share/doc/mkvtoolnix-gui
 usr/share/icons/hicolor/*/apps/mkvtoolnix-gui.png
--- a/debian-upstream/rules
+++ b/debian-upstream/rules
@@ -37,7 +37,7 @@
 	./drake install 'install:translations:guides' 'install:shared' DESTDIR=$(CURDIR)/debian/tmp docdir='$${datarootdir}/doc/mkvtoolnix-gui'
 	./drake 'install:manpages' DESTDIR=$(CURDIR)/debian/tmp USE_QT=yes BUILD_MKVTOOLNIX_GUI=yes docdir='$${datarootdir}/doc/mkvtoolnix-gui'
 
-	dh_install --fail-missing -Xmkvtoolnix.xml
+	dh_install --list-missing -Xmkvtoolnix.xml
 
 	mv debian/mkvtoolnix/usr/bin/mkvinfo debian/mkvtoolnix/usr/bin/mkvinfo-text
 	mv debian/mkvtoolnix-gui/usr/bin/mmg-gui debian/mkvtoolnix-gui/usr/bin/mmg
```
But apparently the GUI's desktop files aren't installed by the rakefile in the first place.

**Comment by mbunkus** [comment]
Thanks for the patch. The desktop files are installed by the »install« task, but only if the package is currently configured to be built with the GUIs. As the Debian build script configures twice (once for the package without the GUIs, once for the package with them) my guess is that the installation happens at the wrong moment. The RPM packages don't have this problem; they use »rake install« and they do contain all three desktop entries (mkvinfo, the old GUI, the new one).

I have to admit that I'm somewhat pissed about having to be a package maintainer at the same time as being a developer. Yes, I could simply not provide binaries for Linux distributions, but that would be a disservice to the users and is therefore not really an option. The Debian packages are especially annoying due to that separation of packages and the required two builds. I will likely simply use your patch as it seems to be the easiest way to get this done.

**Comment by uNiversaI** [comment]
Will that patch solve the open with issue? Since v8 you cant open with mkvmerge or mkvtoolnix as no such software show up in the list of know installed software. Linux mint 17 64bit

Have reverted back to 7.8.0 since atm it is also unusable sorry to say.

**Comment by mbunkus** [comment]
I'm currently building and uploading new packages for Debian/Ubuntu that use this patch. I don't use Ubuntu myself, so I cannot really test if the entries really do show up in the menu, but I have verified that the new packages do contain the desktop files from which the menu entries are generated. I'm therefore quite positive that the patch does fix the issue.

The new packages will have version 8.0.0-0~bunkus02.

**Comment by mbunkus** [comment]
The packages have been uploaded.

**Comment by uNiversaI** [comment]
Well it does work, but open with is broken here, if I select a mkv and open with mkvmerge-gui when mkvmerge opens the file is already inserted. (you do get a deprecation warning sadly as mkvmerge is far more user friendly on simple remux tasks)

If I select open with and set mkvtoolnix-gui as a knwo application, only the program opens, the file isnt actually already loaded ready to remux.

Its function rich mkvtoolnix-gui, but it is indeed more cumbersome and not as user friendly to use.

Anyway on pointwith open with - I can open a separate issue for the open with issue if you like.

**Comment by mbunkus** [comment]
That's due to the command line options not having been implemented yet. There's already an issue for it, #1209, and that is on my TODO list for the next release.

**Comment by uNiversaI** [comment]
excellent, thank you,
