### ISSUE TITLE
Not Attaching Files to Output

### ISSUE THREAD

**Issue by pokeguru87** [mbunkus/mkvtoolnix#1260]
I try to merge a set of source files and the attachments are not on the resulting output. This includes a HEVC Video Track, FLAC Audio Track, SSA Subtitle Track and 4 True Type Fonts. When watching the video outputted the fonts are obviously not used, and when inspecting the file it appears none of the fonts were actually attached. This is with version 8.0.0 with the MKVToolNix GUI, however the old MKVMergeGUI attaches the files just fine.

**Comment by mbunkus** [comment]
Thanks for the report. That's definitely a bug. I'll fix it for the next release at the latest.

**Comment by mbunkus** [comment]
Those true type fonts, are they part of/embedded in the SSA file or are they separate files that you've added manually on the »attachments« tab?

**Comment by mbunkus** [comment]
Hmmm… I cannot reproduce this yet. Can you please give me more details? What kind of files were you adding? Did you add attachments on the »attachments« tab?

Can you please also try to re-create the situation and if you succeed then please send me the command line that the GUI outputs when you select »show command line« from the »merge« menu.

Thanks.

**Comment by Abs62** [comment]
Add tracks, mux mkv. Then add fonts in the attachments tab, mux again. Mkwmerge ignore changes on attachments tab. But if to use "show command line" command, changes will be accepted.

PS. How to remove some attachments from mkv via mkvtoolnix-gui?

**Comment by mbunkus** [comment]
Thanks for the info.

Existing attachments are listed on the »input« tab in the »tracks, chapters, tags and attachments« list. You can disable them like you disable tracks: by changing »mux this« to »no« (or by double-clicking on them in the list).

**Comment by Abs62** [comment]
Mkvtoolnix-gui don't show attached fonts on this tab although ones are presented, mmg list it.

**Comment by mbunkus** [comment]
Well, that's how it's supposed to work, but you're right, it currently doesn't, at least not for certain files. I'll re-open the corresponding issue #1256.

**Comment by mbunkus** [comment]
A very interesting but – but I can reproduce it, which is great as that makes fixing so much easier.

**Comment by erundil** [comment]
Just wanted to confirm that the new GUI totally hates attachments in every way possible.
For example it doesn't see the attachments in MKV files that I opened with it.
Let's say I have a movie that uses a custom font (attached TTF file).
In old GUI it shows the attachment properly. I can uncheck it, or leave it, whatever.
In new GUI the list of attachments is empty.
Thanks to that even though there is 8.3.0 out, I'm still stuck with 7.9.0.
Because it works and does the job.

**Comment by mbunkus** [comment]
Existing attachments in a source file are listed on the »input« tab in the »tracks, attachments and chapters« list. This has been working just fine since 8.1.0:

![existing-attachments](https://cloud.githubusercontent.com/assets/414282/9315957/97894fd6-4532-11e5-84a5-eddea3d12273.png)
