### ISSUE TITLE
jobs aren't removed automatically

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1262]
As reported via email:

> I've checked 'Remove job from queue after completion (Even if there were warnings)', but jobs remain in queue after being completed with OK.

**Comment by bastik-tor** [comment]
On Windows 7 64bit with 8.0.0 (release), only the option ```Even if there were warnings``` seems to be not working correctly.

- ```Only if the job completed successfully``` results in the job being removed if everything was alright.
- ```Always remove the job afterwards``` results in the job being removed, after its execution.
- ```Even if there were warnings``` results in the job not being removed if there were no warnings. The job does get removed if there have been warnings.

**Comment by mbunkus** [comment]
Thanks for the triage.
