### ISSUE TITLE
Drag and drop source file onto application icon (MKVToolNix GUI)

### ISSUE THREAD

**Issue by JKAussieSkater** [mbunkus/mkvtoolnix#1267]
In the now defunct mkvmerge GUI, you could drag and drop a source file onto the application shortcut. This would launch the app, and automatically add the source file to the "Input files" list.

I would like to see the same functionality in the MKVToolNix GUI. i.e. drag and drop source files onto the application icon.

**Comment by mbunkus** [comment]
This is due to the command line options not having been implemented yet. It is on my TODO list for the next release though, and there's already an issue for it: #1209.

**Comment by JKAussieSkater** [comment]
Whoops! When checking the existing tickets, I didn't realise the command line options encapsulated this . . . But of course it does! Sorry about the duplicate request.

Also, my computer loves the new application . . . Windows Explorer doesn't seem to 'lock up' like it used to with mkvmerge :)
