### ISSUE TITLE
Dolby Digital Plus streams are not recognized

### ISSUE THREAD

**Issue by dxhelios** [mbunkus/mkvtoolnix#1272]
Hello, 

I tried to remux MP4 with Dolby Digital Plus (DDP) streams into MKV and noticed that MKVToolNixGUI does not recognize this DDP streams. I used reference video streams from dolby. Here is URL: http://developer.dolby.com/support.aspx#video. Popular tsmuxer tool recognizes H264+DDP files correctly and indicates that it is DD+ streams.
![dolby](https://cloud.githubusercontent.com/assets/12989024/8272291/75bc6060-1845-11e5-8290-b7776cc79bdf.PNG)
Popular eac3to tool recognizes this streams without any problems.

**Comment by mbunkus** [comment]
Thanks for the report.

**Comment by dxhelios** [comment]
thx
