### ISSUE TITLE
Make it possible to import jobs from mmg

### ISSUE THREAD

**Issue by AW-UC** [mbunkus/mkvtoolnix#1273]
I'd like to see the old jobs done by `mmg.exe` in `mkvtoolnix-gui`. I guess, I would need to include them in `mkvtoolnix-gui.ini`, but the syntax has changed. Any way to this, without lots of fiddling around?

**Comment by mbunkus** [comment]
Not really. There are two issues:

1. The structure. The old job files were written in a format similar to the new one, but slightly different. Escaping rules are different, the handling of sub-groups is different etc.
2. The key names are different.

About 1: I'm simply using the functions provided by the GUIs for writing INI-like setting files. I haven't written a parser for those formats myself.

For both reasons mentioned above converting between the two formats would require quite a lot of time and effort, especially for testing. It's not something I'm willing to do myself. Sorry.
