### ISSUE TITLE
mkvmerge FAILED with a return code of -1073741819 (Only in last versions)

### ISSUE THREAD

**Issue by Maal656** [mbunkus/mkvtoolnix#1278]
I'm trying to convert my DVDs to MKV files, without any recompression (just audio and video passthrough), so I follow the next steps:
- Video (.m2v file) and audio (usually .ac3 files) are extracted with MEGUI (Tools --> File indexer).
- Subtitles are extracted (in .idx and .sub files) with VobSub Ripper Wizard.
- Chapters are extracted with ChapterXtractor.

Then, I've been using the program mmg.exe to mux all these parts together in a .mkv file.

The problem is that, in last versions (at least since v7.4.0) during the process I use to get the following error message: "mkvmerge FAILED with a return code of -1073741819"

However, if I use a previous version (I use v7.0.0), the process is always correct and I get a perfect .mkv file with the movie.

I don't know what has changed since this version, but it would be great to be able to use the last versions of the program.

Thank you in advance and regards.

**Comment by mbunkus** [comment]
Thanks for the report. As I don't have any such problems with my files here I will need access to the files you're trying to mux if you want me to investigate. Please upload one such set of files (the files as they are right before you add them to mmg) to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by Maal656** [comment]
Thank you for your answer. I've uploaded as a sample an .ac3 file and a .m2v file in the FTP server provided, together with three screenshots with the output in different versions of mmg.

Just to complete the information, I have this problem in two different compurters (home and office), so I guess it is not related with hardware.

If you need any further information, just contact me.

Best regards.

**Comment by Maal656** [comment]
Hello... Just to provide you a bit more information, I thing that the problem has been caused by a change between versions v7.3.0 and v7.4.0 (at least with v7.3.0 all the merges are OK).

**Comment by mbunkus** [comment]
I can reproduce, but only with the 32bit executables, not the 64bit ones. Are you using 32bit binaries, too? Your screenshots don't show.

**Comment by Maal656** [comment]
In the computer of my office the executable is 32bits (Windows 8.1 32bits is installed). In the computer of my home the executable is also 32 bits, but I can install the 64 bits, so I will check it with different movies.

**Comment by mbunkus** [comment]
Running the whole thing inside valgrind (a memory access error detection tool) I can see the error happening on 64bit Linux as well. No need for you to run additional tests; I can reproduce it, it's due to faulty program logic (accessing a pointer to a memory region after it's been freed), and I'll fix it.

**Comment by mbunkus** [comment]
As a reminder for myself and so that I don't have to run valgrind on that huge file again:

    ==13849== Invalid read of size 1
    ==13849==    at 0x8D1654: MPEGFrameRef::TryUpdate() (M2VParser.cpp:32)
    ==13849==    by 0x8D30B9: M2VParser::UpdateFrame(MPEGFrame*) (M2VParser.cpp:246)
    ==13849==    by 0x8D21B4: M2VParser::TimestampWaitingFrames() (M2VParser.cpp:287)
    ==13849==    by 0x8D32A2: M2VParser::OrderFrame(MPEGFrame*) (M2VParser.cpp:268)
    ==13849==    by 0x8D3A27: M2VParser::PrepareFrame(MPEGChunk*, long, MPEG2PictureHeader) (M2VParser.cpp:355)
    ==13849==    by 0x8D1D3C: M2VParser::FillQueues() (M2VParser.cpp:440)
    ==13849==    by 0x8D238C: M2VParser::WriteData(unsigned char*, unsigned int) (M2VParser.cpp:92)
    ==13849==    by 0x6E5243: mpeg1_2_video_packetizer_c::process_unframed(std::shared_ptr<packet_t>) (p_mpeg1_2.cpp:214)
    ==13849==    by 0x6E4E15: mpeg1_2_video_packetizer_c::process(std::shared_ptr<packet_t>) (p_mpeg1_2.cpp:182)
    ==13849==    by 0x599B10: generic_packetizer_c::process(packet_t*) (generic_packetizer.h:138)
    ==13849==    by 0x59B2C2: mpeg_es_reader_c::read(generic_packetizer_c*, bool) (r_mpeg_es.cpp:196)
    ==13849==    by 0x55DDF9: generic_packetizer_c::read() (generic_packetizer.cpp:1195)
    ==13849==  Address 0xdfdb2c0 is 112 bytes inside a block of size 120 free'd
    ==13849==    at 0x4C2B6D0: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==13849==    by 0x4EC474: operator delete(void*, unsigned long) (in /home/mosu/prog/video/mkvtoolnix/src/mkvmerge)
    ==13849==    by 0x5B151D: std::_Sp_counted_ptr<MPEGFrame*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (in /home/mosu/prog/video/mkvtoolnix/src/mkvmerge)
    ==13849==    by 0x4F07F6: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (shared_ptr_base.h:150)
    ==13849==    by 0x4F079C: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (shared_ptr_base.h:659)
    ==13849==    by 0x5B309B: std::__shared_ptr<MPEGFrame, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (in /home/mosu/prog/video/mkvtoolnix/src/mkvmerge)
    ==13849==    by 0x5AE364: std::shared_ptr<MPEGFrame>::~shared_ptr() (in /home/mosu/prog/video/mkvtoolnix/src/mkvmerge)
    ==13849==    by 0x6E55C5: mpeg1_2_video_packetizer_c::process_unframed(std::shared_ptr<packet_t>) (p_mpeg1_2.cpp:237)
    ==13849==    by 0x6E4E15: mpeg1_2_video_packetizer_c::process(std::shared_ptr<packet_t>) (p_mpeg1_2.cpp:182)
    ==13849==    by 0x599B10: generic_packetizer_c::process(packet_t*) (generic_packetizer.h:138)
    ==13849==    by 0x59B2C2: mpeg_es_reader_c::read(generic_packetizer_c*, bool) (r_mpeg_es.cpp:196)
    ==13849==    by 0x55DDF9: generic_packetizer_c::read() (generic_packetizer.cpp:1195)
    ==13849==
