### ISSUE TITLE
New GUI: feature request: implement an alternative way for moving tracks

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1279]
In the new GUI....

**1)** If we want to add source files we can use:

► a proper button (»add source files«)
► a context menu
► drag & drop functionality

Result: 3/3 = **delicious!**

**2)** If we want to append or add files as additional parts we can use:

► a context menu
► drag & drop functionality

Result: 2/2 = **very good!**

**3)** If we want to remove files we can use:

► a context menu
► the delete or backspace key on the keyboard 

Result: 2/2 = **very good!**

**4)** If we want to enable or disable a single track or many tracks (toggle »mux this«) we can use:

► a context menu
► a drop-down box
► a scroll wheel on a mouse (but first we have to select a track(s) and focus the mouse cursor on a proper drop-down box) 
► double click (via the left mouse button)
► the Enter key on the keyboard
► a simple check box 

Result: 6/6 = **outstanding!** 

Summarizing: we have **MASSIVE** options to add/change/toggle/navigate etc. our favourite tracks (files).

But now....

If we want to move a track up or down we can **ONLY** use the left mouse button (via drag & drop). There is no second (at least), third or even fourth way to change the track order. There is NO alternative! We are absolutely limited and we must count on our mouses (they cannot let us down!). Such a situation is very uncomfortable because we have to be (always) very focused when dragging & dropping a track. We have to do it very precisely. One mistake and we have to start again. I don't know like other users, but I would like to have a choice. 

That's why I strongly urge you to implement an alternative way for moving tracks. Two famous buttons known from the old GUI (up & down) would be very nice, but as I know that you don't want to implement them, then maybe you could implement »the keyboard trick«:

(left) **Ctrl +** (arrow) **up/down** or (left) **Alt +** (arrow) **up/down**.... or something similar.   

I don't know if it's possible, but would be a good candidate, I think. Also: a keyboard navigation would be a salvation if a mouse breaks down one sunny day. I hope you will not reject my ticket automatically, but at least think over it very deeply.

Thank you very much for considering my idea.

**Comment by mbunkus** [comment]
I'm leaving this one as undecided for the time being.

**Comment by mbunkus** [comment]
Someone else has requested buttons, too. I will likely implement them, but only as an optional feature that defaults to off.

**Comment by remuxer32** [comment]
Great! Thank you very much for your decision, Mosu.

**Comment by remuxer32** [comment]
Hmmm, I still cannot decide which option would be better: buttons or keyboard shortcuts. It's a hard nut to crack ☺. On the one hand buttons (up & down) that are very familiar for long-time users who are accustomed with the old GUI, and easy-to-use of course. But on the other hand the new GUI shouldn't be »clogged« by too many buttons, I think. 

At the other extreme we have keyboard shortcuts (Ctrl + up/down): such a solution would be really amazing and fast: users could be able to move tracks very quickly and enjoyably. And also: they wouldn't have to worry if a mouse breaks down one day: it's very important, I think.

Summarizing: Is there a golden mean? Yes, it is. What would you say to implement both (buttons + keyboard shortcuts) of them? I think it's the best idea. Such a denouement will certainly reconcile the two groups of people: conservative (who like buttons) and progressive (who would like to use the keyboard keys only). Is it too much? No, it's not, honestly [please note that users can use even **SIX** ways for toggling tracks (»mux this«) listed above]. There is an unrivalled opportunity to give users the three ways for moving tracks:

► via drag & drop (using the left mouse button; it works)
► buttons (up & down)
► keyboard shortcuts (Ctrl + up/down)*

Result: 3/3 = **delicious!** 

I'm sure they will be satisfied because of these three options.

Thank you for considering my idea.

BTW: Shift + up/down would be definitely the best, but it's reserved for selecting tracks, though.

**Comment by remuxer32** [comment]
Thank you for the quick implementation. I've just downloaded a new pre-build; new features work perfectly ☺.

**Comment by LotusFlower1** [comment]
Hi, I have a problem with the new GUI.
I can't move the tracks :(
If I use the Drag & Drop the GUI crashes, and the Ctrl+Up/Down doesn't work on my mac keyboard.
What can I do please ?
Thanks

**Comment by mbunkus** [comment]
You can try using the buttons for moving tracks up & down. You'll have to enable them in the preferences first.

**Comment by LotusFlower1** [comment]
Sorry but I don't see any preferences tab

![untitled](https://cloud.githubusercontent.com/assets/14893361/10185712/f157a030-6742-11e5-8a19-f8ac8018d86d.png)

Is it the last version ?

**Comment by mbunkus** [comment]
It's a menu entry, not a tab. »MKVToolNix« menu → »Preferences«.

**Comment by LotusFlower1** [comment]
But where is the menu ?
I tried everything but I can't find it :(
Sorry I'm blond and I'm completely lost with this new GUI ;)

**Comment by mbunkus** [comment]
From the screenshot it looks like you're using… Ubuntu maybe? Doesn't Ubuntu show a program's menu at the top of the screen instead of inside the program's window?

**Comment by LotusFlower1** [comment]
Yes it's Ubuntu but I have nothing :(
Look at the full screen :
![untitled](https://cloud.githubusercontent.com/assets/14893361/10188075/8430e9dc-6754-11e5-933c-24a097b58125.png)

**Comment by mbunkus** [comment]
Uhm… I'm sorry, but I have no idea why the menu bar isn't shown. That seems to be a Ubuntu/Unity thing because the program definitely provides one. On KDE on my Arch Linux the menu bar is shown normally within the program window, same on Windows. I cannot really help you with such issues as it's a Unity thing, like I said. Googling for »ubuntu unity qt5 menu bar« shows several known issues, e.g. [this one](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1302084). Maybe you're hitting one of those issues, too.

You can open the preferences by hitting Ctrl+P as well, but there are several functions in the program for which only menu entries exist but no keyboard shortcuts.

**Comment by LotusFlower1** [comment]
Ok thanks for the infos. I'm going to investigate and try to find a fix.
