### ISSUE TITLE
Regression: Attached jpg file can't be seen as cover anymore in 8.0.0

### ISSUE THREAD

**Issue by igor2x** [mbunkus/mkvtoolnix#1280]
Hi,
MKVToolNix GUI 8.0.0. on Ubuntu 14.04.

1. Merge master tab at left | Input tab | right click in Files field and select Add.
2. Select mp4 file.
3. Output tab | type in some title like My_title in General | File title
4. Attachment tab | right click in Attachment field and select Add.
5. Select jpg file.
6. Start muxing button at bottom.
7. Jub output  master tab on left and wait Progress gets to 100%.
8. Close MKVToolNix GUI.
9. Open VLC Player 2.1.6 (default program from repository in Ubuntu 14.04).
10. Menu Media | Open file | select mkv file.
What happens. File is displayed but there is no movie cover (it should be from jpg file - step 5).

This was working fine using MKVToolNix GUI 7.9 on Ubuntu 14.04 with VLC Player 2.1.6.
So it looks like a regression.

**Comment by mbunkus** [comment]
Thanks for the report. This is due to a bug that's been fixed already: #1260. The next release (which will likely happen within the next two weeks) will contain the fix.
