### ISSUE TITLE
8.0.0 open dialog has way less options then 7.8.0 on Ubuntu

### ISSUE THREAD

**Issue by igor2x** [mbunkus/mkvtoolnix#1282]
1. mkvtoolnix-gui 8.0.0 on Ubuntu 14.04. Merge left tab | Input tab | right click on Files field and Add.
compare with
2. mkvtoolnix-gui 7.8.0 on Ubuntu 14.04. Input tab | Add button.

New 8.0.0 has way less options to select from and is less useful. See print-screen:
https://i.imgur.com/PXCbdd0.png

Can you please add back 7.8.0 Open dialog.

**Comment by mbunkus** [comment]
The file dialogs are the ones provided by the respective toolkits (wxWidgets for the old GUI, Qt for the new one). I cannot (don't want to, as it's a huge amount of work) change how they work.

You can, however, add any folder/location to the left list in that dialog by dragging & dropping a folder from the right onto the list on the left.
