### ISSUE TITLE
Open dialog in 8.0.0 in Ubuntu 14.04 has menus

### ISSUE THREAD

**Issue by igor2x** [mbunkus/mkvtoolnix#1283]
Mkvtoolnix 8.0.0 on Ubuntu 14.04:
- Merge | Input | File - right menu Add
In Open file dialog are menus? This is strange, no other program in Ubuntu has this menus in Open dialog.

Mkvtoolnix 7.8.0 on Ubuntu 14.04:
- Input | Add button
No menus in Open file diloag

See print-screen:
https://i.imgur.com/RjpFU17.png

**Comment by mbunkus** [comment]
Like I've written in #1282 the file dialogs are provided by the toolkit library. Nothing I can do about it.
