### ISSUE TITLE
tests/unit/common/list_utils.cpp fails to link

### ISSUE THREAD

**Issue by rathann** [mbunkus/mkvtoolnix#1284]
It looks like commit 6f80025fe67cc3cf68ca700967e6920285fbd9da broke compilation. In particular lines 16 and 21 of mkvtoolnix-8.0.0/tests/unit/common/list_utils.cpp cause link errors:

[mockbuild@d8c8cb1ef6f046dfaa14398a59ec5d16 mkvtoolnix-8.0.0]$ ./drake V=1
g++ -Wall -Wno-comment -Wfatal-errors -Wlogical-op -D_FILE_OFFSET_BITS=64 -DMTX_LOCALE_DIR=\"/usr/share/locale\" -DMTX_PKG_DATA_DIR=\"/usr/share/mkvtoolnix\" -DMTX_DOC_DIR=\"/usr/share/doc/mkvtoolnix\" -std=gnu++14 -Wnon-virtual-dtor -Woverloaded-virtual -Wextra -Wno-missing-field-initializers -Wno-maybe-uninitialized -I/usr/lib64/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread -I/usr/include -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I. -Ilib -Ilib/avilib-0.6.10 -Isrc -c -MMD -MF ./rake.d/dependency.d/tmp/tests_unit_common_list_utils_o.d -o tests/unit/common/list_utils.o -x c++ tests/unit/common/list_utils.cpp
g++ -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/lib64 -Llib/avilib-0.6.10 -Llib/librmff -Lsrc/common -o tests/unit/common/common tests/unit/common/codec.o tests/unit/common/option_with_source.o tests/unit/common/construct_equality.o tests/unit/common/bit_cursor.o tests/unit/common/ebml_chapters_converter.o tests/unit/common/fourcc.o tests/unit/common/list_utils.o tests/unit/common/basic_timecode_c.o tests/unit/common/ebml_tags_converter.o tests/unit/common/strings_formatting.o tests/unit/common/checksums.o tests/unit/common/ebml_segmentinfo_converter.o tests/unit/common/endian.o tests/unit/common/math.o tests/unit/common/mm_io.o tests/unit/common/common.o -Ltests/unit -lmtxunittest -lmtxcommon -lmagic -lz -lmatroska -lebml -lz -lpugixml -lboost_regex -lboost_filesystem -lboost_system -lgtest -lpthread
tests/unit/common/list_utils.o: In function `void testing_internal::DefaultPrintNonContainerTo<boost::optional<void*> >(boost::optional<void*> const&, std::ostream*)':
/usr/include/gtest/gtest-printers.h:245: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& boost::operator<< <char, std::char_traits<char>, void*>(std::basic_ostream<char, std::char_traits<char> >&, boost::optional<void*> const&)'
tests/unit/common/list_utils.o: In function `void testing_internal::DefaultPrintNonContainerTo<boost::optional<int> >(boost::optional<int> const&, std::ostream*)':
/usr/include/gtest/gtest-printers.h:245: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& boost::operator<< <char, std::char_traits<char>, int>(std::basic_ostream<char, std::char_traits<char> >&, boost::optional<int> const&)'
collect2: error: ld returned 1 exit status

I'm not sure if this is a bug in mkvtoolnix or gtest or gcc. This is bug https://bugzilla.redhat.com/show_bug.cgi?id=1234405 .

**Comment by mbunkus** [comment]
I've just verified that building and running the unit tests works fine here on Arch Linux with clang 3.6.1, gcc 5.1.0, gtest 1.7.0. This is revision fa2baa0.

I can also confirm that revision fa2baa0 builds and runs the unit tests just fine on my buildbot server running clang 3.3, gcc 4.8.4, gtest 1.6.0.

Therefore I don't really know what the error might be on your end…

**Comment by rathann** [comment]
Could you retry with gcc-5.1.1?

**Comment by mbunkus** [comment]
Not until it hits Arch's repos, and I'm currently in the middle of working on other things; I definitely won't have time to build a custom gcc at the moment. Sorry.

**Comment by rathann** [comment]
No problem, thanks for testing. Confirmed this is not occurring on Fedora 21 (gcc-4.9.2), so it's probably a bug in gcc-5.1.1.

**Comment by rathann** [comment]
Which boost versions are you testing against? I got a reply from our gcc maintainers that this looks like a bug in mkvtoolnix that was revealed by recent changes in boost:
https://svn.boost.org/trac/boost/ticket/2103
https://svn.boost.org/trac/boost/ticket/10825

**Comment by rathann** [comment]
For comparison, Fedora 21 has boost-1.55 and Fedora 22 and rawhide (where the issue is occurring) have both boost-1.57.

**Comment by mbunkus** [comment]
I'm using Boost 1.58 on my Arch and 1.54 on my Ubuntu buildbot.

**Comment by mbunkus** [comment]
Looking at https://svn.boost.org/trac/boost/ticket/10825 they suggest that including that other header might fix the issue. Could you give that a try? Meaning… add `#include <boost/optional/optional_io.hpp>` to tests/unit/common/list_utils.cpp.

**Comment by rathann** [comment]
I replaced the existing include with the one you suggested, because optional_io.hpp includes optional.hpp already and it does fix this issue. The code compiles and links successfully, and tests pass.

**Comment by mbunkus** [comment]
Well, the proper fix should be to include `optional_io.hpp` in `tests/unit/common/list_utils.cpp` and to not change `src/common/list_utils.h`. The actual code in `src/common` does not require nor use I/O operators. Only the test cases do; therefore the test cases should include the required file(s) in order not to increase the compile time for everything else unnecessarily.

I'll commit and push such a change in a moment. Could give that a spin as well, please?

**Comment by rathann** [comment]
It works just fine: http://koji.fedoraproject.org/koji/taskinfo?taskID=10234995 . Thank you!

**Comment by mbunkus** [comment]
Thanks for the verification.
