### ISSUE TITLE
Remove all does not remove global file/segment title in some movies not all

### ISSUE THREAD

**Issue by NMD91935** [mbunkus/mkvtoolnix#1285]
if you have worked on one file and click on remove all to start another file the global file/segment title may have the previous files name in it - not always

**Comment by mbunkus** [comment]
It should keep the title if the user has changed the title manually. It should remove the title if it was set automatically from an input file. I'll see if it works as intended.

**Comment by mbunkus** [comment]
8.1.0 works as I intend it to work.
