### ISSUE TITLE
New Gui Select Chapter File

### ISSUE THREAD

**Issue by onedot3** [mbunkus/mkvtoolnix#1290]
New Gui Select Chapter File
In old gui when you Selected  Browse it takes  you to the folder that the MKV was in.
In the new GUI this does not happen could this be changed
Also in the requester it is only set for .xml and not for all supported chapters

**Comment by mbunkus** [comment]
Currently the chapter editor remembers its last used directory separately from the merge tool. The idea is that chapter files may reside in different directories than your Matroska file. But I'll think about using the same directory.

As for the extension in the file dialog: I cannot reproduce that; for me it lists all types by default. See #1269. If you mean the »save« dialog: you have to chose whether you want to save the chapters to an existing Matroska file (in which case only Matroska files are listed) or to an XML file (in which case only XML files are listed). The reason these two are separate function is that both do very different things. If you save to an XML file then an existing with the same name is completely overwritten while saving to a Matroska file only adds the chapters to that file. You also have to select an existing Matroska file (you cannot create a new Matroska file with that functionality) while you can write the chapters to a non-existent XML file.
