### ISSUE TITLE
mkvmerge GUI v8.0.0: serious bug found: program shuts down automatically without warning

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1292]
Watch this film please: https://youtu.be/MrClJKvLCQI

Summarizing: mmg v8.0.0 shuts down automatically when right-clicking on empty field (Output filename). Earlier releases (7.9.0, 7.8.0 etc.) work fine.

**Comment by mbunkus** [comment]
Bugs in mmg won't be fixed anymore, and this particular issue is due to the wxWidgets toolkit and nothing I could do about it anyway.

**Comment by remuxer32** [comment]
Ok, I understand. It seems that other (conservative) users would have to use earlier versions of the old GUI, if necessary ;)
