### ISSUE TITLE
Removing existing file title in MKVToolNix GUI does not remove the title

### ISSUE THREAD

**Issue by CheesyWiggles** [mbunkus/mkvtoolnix#1294]
When removing the existing file title in MKVToolNix GUI it does not add the "--title" "" option to actually remove the title. Changing the title correctly sets the --title option but removing the title does not set the --title option at all so the output file retains the title of the input file.

![image](https://cloud.githubusercontent.com/assets/13039955/8342354/6008d106-1ac3-11e5-9d6f-55f55612ad52.png)

![image](https://cloud.githubusercontent.com/assets/13039955/8342417/d4478da0-1ac3-11e5-9e6f-1ceb109e5d56.png)

**Comment by mbunkus** [comment]
Thanks for the report. This has already been addressed, see #1264.
