### ISSUE TITLE
New GUI: Forward-slashes used throughout the program (Windows)

### ISSUE THREAD

**Issue by hurda** [mbunkus/mkvtoolnix#1298]
![mkv_slashes](https://cloud.githubusercontent.com/assets/3539609/8361816/890b03b4-1b75-11e5-9fda-97a399f04372.png)

PS: Are the circumflexes used for escaping all the quotes a bug or intended?

**Comment by mbunkus** [comment]
This is simply how Qt works. Forward slashes are fully supported in Windows, so there's no problem either. It's nothing I will change.

Yes, the circumflexes are intended. See [this exhaustive description](http://blogs.msdn.com/b/twistylittlepassagesallalike/archive/2011/04/23/everyone-quotes-arguments-the-wrong-way.aspx).

**Comment by hurda** [comment]
QT offers a function to convert the slashes to the system's default:
http://doc.qt.io/qt-5/qdir.html#toNativeSeparators

**Comment by mbunkus** [comment]
I know, but I don't care enough about it to fix it. Like I said: Windows can deal with forward slashes just fine, even with mixed slashes in the same path, and therefore I don't consider this to be anything more than a nice-to-have visual thing.

If someone else wants to contribute a fix for it I'd be happy to merge it, though. I just don't want to spend time on it myself.
