### ISSUE TITLE
New GUI: The ‘Show command line’ command doesn't work correctly with multiple tabs.

### ISSUE THREAD

**Issue by Androiala** [mbunkus/mkvtoolnix#1301]
I’m using MKVToolNixGui 8.0.0    64bit   on windows.

Creating a job on the first tab and pressing ‘Show command line’ gives me exactly what I expect. Now I create with ‘new’ a second tab and create there a job as well, ‘Show command line’ again gives what I expect.

Now I switch back to tab 1 and press ‘Show command line’. What happened is that I see the commands of the context of tab 2 again. Expected is the context of tab 1.
When I now close tab 2, ‘Show command line’ does nothing at all, no window appears.

This bug is always reproducible for me.

**Comment by mbunkus** [comment]
Thanks for the report. I'll get it fixed soonish.
