### ISSUE TITLE
Append a file doesn't work

### ISSUE THREAD

**Issue by ttplayer** [mbunkus/mkvtoolnix#1302]
Appending an mkv to an existing other mkv don't work with the new gui.
This is my commandline (WIN 8.1, 64bit)

^"F:/Video\MKVtoolnix\mkvmerge.exe^" ^"--output^" ^"E:/DVDRoot/Test.mkv^" ^"--language^" ^"0:und^" ^"--language^" ^"1:eng^" ( ^"E:/DVDRoot/1.mkv^" ) ^"+^" ( ^"E:/DVDRoot/2.mkv^" ) ^"--track-order^" ^"0:0,0:1^" ^"--append-to^" ^"1:0:0:0,1:1:0:1^"

![zwischenablage01](https://cloud.githubusercontent.com/assets/13061527/8373345/46495a36-1bec-11e5-9460-52a0f2eca4c1.jpg)

**Comment by mbunkus** [comment]
Thanks for the report. This has already been fixed; see #1271.
