### ISSUE TITLE
optional stacked layout for input tab of merge tool

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1304]
Some users prefer not to have the track properties on the right. An optional stacked layout (file list on top, track list in the middle, properties at the bottom), to be enabled via the preferences, would help them.

**Comment by remuxer32** [comment]
This is absolutely fantastic idea! I'm a big fan of it. Personally I don't like to have the track properties on the right, too. Currently I have to use a scroll wheel to go down which is very uncomfortable and wasting time for me, of course. Definitely I would like to have properties at the bottom like in the old GUI. I look forward to seeing this feature soon, I hope. It will help me immensely.

**Comment by mbunkus** [comment]
Definitely not soon as it's very, very complex to implement and test, as I've found out when making the output file name be relocatable…

**Comment by functionalex** [comment]
Please bring vertical layout back to the GUI. With version 8.4.0 you do not deliver mmg anymore, so I have to make a complain at this point. This is my use case:
I am always docking mkvtoolnix to the right side and the explorer with files to the left. (using WinBtn + <- ->, which for me is the fastest way) Each occupies 50% of width this way and I can easily drag & drop files to GUI.

Having the new horizontally layout means, that the reading space of all elements is being halved, additionally to already halved space through property sidebar on the right and the the sidebar on the left. => I have to use the horizontal scrollbar all the time.

The only way to maintain usability is to have a vertical layout, as the height remains the same (100%). I do not care about the prettiness as some other users complain. But I really need the old vertical layout as the current one is wasting a lot of my time.

**Comment by mbunkus** [comment]
I will bring back such a layout, but not in the near future (read: likely not within the next two releases at least).

**Comment by mbunkus** [comment]
And the reason is that it requires an incredible amount of work to implement and to support in the future. I've done this already for the output file name control which can be shown on the output tab or globally beneat the tab widget. This has taken several hours to implement for two simple controls.

This is due to Qt simply not supporting alternative layouts, not in its classes and especially not in QtCreator. This means I have to do all the layouting for  both cases by hand and cannot really use QtCreator anymore. It's a bitch to implement and even worse to maintain.

**Comment by mbunkus** [comment]
Well, sometimes all you have to do is to sleep on it for a couple of nights and you think of a way to do something with less effort than initially estimated. Turns out this is one of those things.

New pre-builds are up. [Build numbers 929 and higher](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) contain the feature. I'd appreciate some testing.

**Comment by functionalex** [comment]
Now this is something I could really work with. Glad that we do not have to wait that long, really appreciated.

**Comment by remuxer32** [comment]
@Mosu

Thank you for your fast work. I and other users are very grateful because of that feature. Now we have the real freedom of choice. I've just downloaded a new pre-build and confirm that everything works great. So far I haven't noticed any extraordinary behaviours so it seems that there are no bugs. You can be proud of yourself. It was a good job :) Chapeau bas!
