### ISSUE TITLE
Move to other job and create new job per Drag and Drop

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1308]
Within the merge tool, wherever I drop a file I dragged from someplace it gets added to the currently selected job. It would be nice if I could drag it over a tab to add it to that job and when I drag it above the tab bar (in the whitespace) that it creates a new job.

Maybe achievable with modifier-keys like CTRL or ALT.

**Comment by mbunkus** [comment]
Thanks for the suggestion. I don't really like such magic drop zones as they're very hard to discover for the average user… I do think such functionality can be useful, but I'll have to think about how to make this feature work well. One thing that might work is to switch to the tab as soon as you hover over it while dragging.

I consider this to be of secondary importance, meaning it will probably not be implemented for 8.2.0.

**Comment by remuxer32** [comment]
Aye! I fully support bastik-tor's idea. I think it's really cool. It will be very useful for me, too. I look forward to testing that feature ☺.

**Comment by mbunkus** [comment]
I've given this a try today. After spending more than three hours on it I've now decided not to implement this after all. It's pretty hard to implement with how the GUI currently works, and it's simply not worth the effort for me.

How much time would it save a user? Not a lot, in my opinion; it's only a minor inconvenience to browse the file system again for a file. Additionally how often does a user add a file to the wrong tab in the first place? Not that often, I'd wager, again reducing the amount of time such a feature would save a user.

Therefore: won't fix/implement.
