### ISSUE TITLE
Combobox labels for default track flag not useful when trying to select a flag label by pressing a letter on keyboard

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1309]
Using English as interface language in MKVToolNix GUI 8.1.0 it is not possible to select the default track flag (for a track while being in merge mode) by typing the letter **D**/**Y**/**N** on the keyboard. In mkvmerge GUI this is possible. The reason seems to be that the "default track flag" combobox in the MKVToolNix GUI uses different text labels than the mkvmerge GUI.

mkvmerge GUI uses the following text labels
* default
* yes
* no

But MKVToolNix GUI uses these labels:
* determine automatically
* set to "yes"
* set to "no"

If the combobox has keyboard focus, pressing the key which equals the start letter of a combobox item will select this item in the combobox. While this works fine in mkvmerge - each combobox item starts with a different letter there -, it is not possible anymore in MKVToolNix GUI to select each item by a single keystroke because two items start with "s".

I would suggest to use the following labels for the "default track flag" combobox:
* determine automatically
* yes
* no

**Comment by mbunkus** [comment]
Thanks for the suggestion. I'll go over the combo box entries again and try to improve this.

The initial intention was to make it clearer to the user what selecting a specific option would do. But I also agree that it makes keyboard navigation a bit too annoying.
