### ISSUE TITLE
Comboboxes for track properties do not show hatched rectangle when having the keyboard input focus

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1310]
In MKVToolNix GUI's merge mode, the comboboxes used for track properties do not show a hatched rectangle when they have obtained the keyboard input focus.

(On the other hand, the comboboxes used in the "Output" tab do show the hatched box correctly when they have the keyboard input focus.)

MKVToolNix version: 8.1.0
OS: Windows 7 Pro x64 english

**Comment by mbunkus** [comment]
Thanks for the report, but this isn't a bug. It's simply how Qt renders combo boxes. The difference between the two types is that the ones for which you can edit the text manually (e.g. the split parameters) show it because they also allow you to open that drop-down menu, while the ones that only allow a fixed set of strings don't need such a hint (I guess – I'm not a Qt developer myself).

**Comment by elgonzo** [comment]
I guess you misunderstood me. I was not talking about a combobox that appears like a text field. I was talking about the hatched/dotted rectangle that is drawn in or around a control (like a non-editable combobox or button, for example) which has the keyboard input focus

Here is a screenshot showing the "Output" tab of the "Merge" mode. Note that dotted rectangle around the "Split mode" combobox which indicates that the combobox has the keyboard input focus.
![outputtab](https://cloud.githubusercontent.com/assets/6129198/8392765/a59ec43a-1cf5-11e5-9215-89b892f1ba33.png)

This is what i was talking about and what the comboboxes used for the track properties are missing.
Look at this screenshot showing the "Input" tab with the track property comboboxes.
![inputtab](https://cloud.githubusercontent.com/assets/6129198/8392783/52998972-1cf6-11e5-8fb2-91d3a428b517.png)

Well, you can't see, but trust me that the "Language" combobox is having the keyboard input focus. Note that there is no dotted rectangle :-(

First i thought it was due to the comboboxes for the track properties perhaps being drawn somewhat smaller vertically and therefore not having enough 'real estate' for the dotted rectangle. But that is not the case - the track property comboboxes are exactly the same height as the comboboxes used in the "Output" tab, also the fonts used are identical. Unfortunately, my experience with Qt is also very limited, so i have really no clue what is going on there...

P.S.:
I just noticed that the output file path is set to C:\Program Files (x86)\MkvToolNix\... Erm, this is not what is supposed to happen. I opened the source MKV file by drag&drop. The path of the source file is a UNC path like \\server\share\directory\mkvfile.mkv. I will check whether this issue has already been reported, and if not i will file a new issue for that.

**Comment by mbunkus** [comment]
Ah, now I understand what you mean. Thanks for the explanation. I do have an idea why it happens, but I have no idea yet how to solve it. Don't expect a quick fix.

**Comment by mbunkus** [comment]
PS: UNC paths work just fine for me here, with drag & drop, too: the output file name is set to a UNC path as well. Check the preferences which output file name generation mode is active; maybe it's »use previous directory« and you haven't muxed something yet.

**Comment by elgonzo** [comment]
Thanks for the feedback with regard to my "P.S. problem". In the mean time, I found issue #1234, saw its comments and that it has been fixed already. Still thanks so much for your response (o.o)_h
