### ISSUE TITLE
MKVToolNix GUI 8.0: Videoproperties --> Stereoscopy --> Set value "3, TAB" results in "4" in output file

### ISSUE THREAD

**Issue by infinity85** [mbunkus/mkvtoolnix#1311]
Hi,
I noticed that if I set the stereoscopy flag for videostream in MKVToolNix GUI to 3 (for TAB), the outputfile shows the value 4. I tried it a few times and it was always 4.

If I do this setting via old "mmg.exe"  in "Format specific options", it works right away and stays on 3 TAB.

Weird bug, but wanted to let you know about it before you exclude mmg.exe out of your distribution.

**Comment by mbunkus** [comment]
Thanks for the report. Sounds like a bug. I'll investigate and fix it if it really is one.
