### ISSUE TITLE
Tiny "niggle" with Chapter Editor > Save to Matroska file

### ISSUE THREAD

**Issue by Andy-ABTec** [mbunkus/mkvtoolnix#1312]
Hi, million thanks for a magic tool, I'm loving the new gui (64 bit Windows)...

I'm slowly working my through my DVD library adding "proper" chapter titles to mkv's, loading chapter.xml files and saving them to the relevant mkv file. Loading isn't an issue but "Save to Matroska file" is greyed out until I either make changes to the content or switch to say "Merge" and then back to "Chapter Editor" at which point I can save as expected.

I can understand disabling "Save" until the content has changed but "Save to..." a format that isn't the format that was opened doesn't seem to make sense.

Shouldn't "Save to Matroska file" if the file that was opened was an xml file, and "Save as XML file" if the chapters were imported from an mkv file be available even if the content hasn't changed?

Just a thought...

**Comment by mbunkus** [comment]
Thanks for the report. I'll look into it.
