### ISSUE TITLE
MKVToolNix GUI v8.1.0 - Appending of more than one file does not work

### ISSUE THREAD

**Issue by highway101** [mbunkus/mkvtoolnix#1313]
Hi there
I tried to append two files to one other (Windows 7 - 64bit):
![mkvtoolnix gui v8 1 0](https://cloud.githubusercontent.com/assets/13083920/8395422/b659865a-1d6f-11e5-8091-9075cd9dc5f1.jpg)

Got the following error:
--- Output of job 'merging to file »new.mkv« in directory »C:/Work/Convert/new.mkv«' started on 2015-06-28 07:57:36 ---
mkvmerge v8.1.0 ('Psychedelic Postcard') 64bit
'C:/Work/Convert/6a.mkv': Using the demultiplexer for the format 'Matroska'.
'C:/Work/Convert/6b.mkv': Using the demultiplexer for the format 'Matroska'.
'C:/Work/Convert/6c.mkv': Using the demultiplexer for the format 'Matroska'.
'C:/Work/Convert/6a.mkv' track 0: Using the output module for the format 'MP3'.
'C:/Work/Convert/6a.mkv' track 1: Using the output module for the format 'AVC/h.264'.
'C:/Work/Convert/6b.mkv' track 0: Using the output module for the format 'MP3'.
'C:/Work/Convert/6b.mkv' track 1: Using the output module for the format 'AVC/h.264'.
'C:/Work/Convert/6c.mkv' track 0: Using the output module for the format 'MP3'.
'C:/Work/Convert/6c.mkv' track 1: Using the output module for the format 'AVC/h.264'.
More than one track is to be appended to the track 0 from file no. 0 ('C:/Work/Convert/6a.mkv'). The argument for '--append-to' was invalid.

Commandline:
^"C:/Program Files\MKVToolNix\mkvmerge.exe^" ^"--priority^" ^"highest^" ^"--output^" ^"C:/Work/Convert/new.mkv^" ^"--language^" ^"0:und^" ^"--default-track^" ^"0:yes^" ^"--language^" ^"1:und^" ^"--default-track^" ^"1:yes^" ( ^"C:/Work/Convert/6a.mkv^" ) ^"+^" ( ^"C:/Work/Convert/6b.mkv^" ) ^"+^" ( ^"C:/Work/Convert/6c.mkv^" ) ^"--track-order^" ^"0:0,0:1^" ^"--append-to^" ^"1:0:0:0,2:0:0:0,1:1:0:1,2:1:0:1^"

Comment:
Worked in old GUI.

**Comment by mbunkus** [comment]
Meh… thanks for the report. I'll fix it.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) fixing the bug are available.
