### ISSUE TITLE
MKVToolnix 8.1 window too large

### ISSUE THREAD

**Issue by Kermu** [mbunkus/mkvtoolnix#1314]
With the new look, and on my computer (Windows 7 french, screen 1280X1024), when the name of a video file is rather long, the window of the merging results pops very very large, exceeding greatly the screen.  Please look at the attached picture. Nothing to do to reduce this width. I return to an older tool.

**Comment by mbunkus** [comment]
No attached picture yet :)

**Comment by mbunkus** [comment]
No need for a screenshot, I can see what you mean.
