### ISSUE TITLE
MKVToolNix GUI doesn't work normally with symlink on Windows 8.1 x64

### ISSUE THREAD

**Issue by fatalistt** [mbunkus/mkvtoolnix#1315]
I've NTFS partition D.
There is symlink (not shortcut or junction, or hardlink) D:\user which point to D:\users\fatalist.
When i launch "mkvtoolnix-gui.exe" from "D:\user\...\mkvtoolnix\", it launched, but when i tried to add any file for merging it rashed with runtime error. (If i wanna to edit chapters or header, it doesn't crash but show error "The file you tried to open (...) could not be read succesfully.")
When i launch "mkvtoolnix-gui.exe" from "D:\users\fatalist\...\mkvtoolnix\" (realpath of this file) it works normally.

mmg works normally in both cases
![image](https://cloud.githubusercontent.com/assets/3428774/8397095/956953c2-1dc8-11e5-8107-022533362311.png)
![image](https://cloud.githubusercontent.com/assets/3428774/8397101/af1b872c-1dc8-11e5-89c6-f686362fc7c5.png)

**Comment by mbunkus** [comment]
Thanks for the report. Symlinks on NTFS aren't tested at all, and I currently have no plans on making them work in the near future. I may get around to this some time, but not any time soon. Sorry.

**Comment by mbunkus** [comment]
I've implemented a fix for the GUI crashing when adding a file. [Pre-builds 912, 913](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) contain that fix.

I cannot reproduce any problem with opening files from a symlinked folder in the header or chapter editors, though. I consider this issue resolved unless you can still get it to fail with the aforementioned pre-builds.

Note that the operation may fail if the file is currently open in another application, e.g. a video player. Additionally the file must not have its read-only attribute set as it is opened for writing.

**Comment by plastikat** [comment]
I've tested the pre-builds and confirm these run just fine from symlink folders (which is very expected due to the nature of the fix).

Thanks for your (unexpectedly) quick resolution of this issue!
