### ISSUE TITLE
Tests still not building on Cygwin

### ISSUE THREAD

**Issue by drstacey** [mbunkus/mkvtoolnix#1318]
I'm not sure that my patch for #1232 was applied correctly - did you apply it manually, or use patch(1)? Apologies if my original bug report wasn't clear. Anyway, the '+ c(:EXEEXT)' needs to be removed from line 12 and added to line 8. If you're using patch(1), then the following patch should sort it out:

```
--- origsrc/mkvtoolnix-8.0.0/rake.d/gtest.rb	2015-06-19 15:07:10.000000000 +0100
+++ src/mkvtoolnix-8.0.0/rake.d/gtest.rb	2015-06-21 08:52:24.685281700 +0100
@@ -5,11 +5,11 @@ $gtest_internal = c(:GTEST_TYPE) == "int
 
 namespace :tests do
   desc "Build the unit tests"
-  task :unit => $gtest_apps.collect { |app| "tests/unit/#{app}/#{app}" }
+  task :unit => $gtest_apps.collect { |app| "tests/unit/#{app}/#{app}" + c(:EXEEXT) }
 
   desc "Build and run the unit tests"
   task :run_unit => 'tests:unit' do
-    $gtest_apps.each { |app| run "./tests/unit/#{app}/#{app}" + c(:EXEEXT) }
+    $gtest_apps.each { |app| run "./tests/unit/#{app}/#{app}" }
   end
 end
 
```

With this change, mkvtoolnix-8.1.0 will be available in the Cygwin distribution shortly. Apologies once again if this confusion was my fault.

**Comment by mbunkus** [comment]
Thanks. The thing with inline-posted patches is that they're fragile to get out of the site. Therefore I didn't use patch. In future please either create a pull request or send me an email with the patch as an attachment or post the patch on gist.githumb.com – all those methods allow for reliable transmission of patches.

You don't have to send a patch for this issue, though, I'll take care of it.
