### ISSUE TITLE
Cannot edit text boxes

### ISSUE THREAD

**Issue by Tochete** [mbunkus/mkvtoolnix#1319]
I'm on a Linux system, version:
3.2.0-64-generic #97-Ubuntu SMP Wed Jun 4 22:04:21 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

When I try to edit a text box in MKVToolnix-GUI, I can add text but I cannot delete it with backspace or delete. It happens at least in the output file text box and the track name text box. Also, my language is set to Spanish in preferences, FYI.

**Comment by mbunkus** [comment]
I have no such problems whatsoever: both backspace and delete work just fine in the line edit controls on my Arch Linux (also on my Windows installation). I don't do anything with the key presses in those controls – that's solely up to the GUI library (Qt). If that doesn't work for you then there's nothing I can do about it. Sorry.
