### ISSUE TITLE
Cannot shift-click to select a range of tracks

### ISSUE THREAD

**Issue by jtanx** [mbunkus/mkvtoolnix#1320]
It would be really handy if it was possible to click on one item in the track list and then shift-click to another item to select a range of items to not mux. This is particularly useful if the file has a lot of attachments that need to be removed.

**Comment by mbunkus** [comment]
That works just fine on my Windows and on my Arch Linux installation – I just verified it. Both of the following methods work:

1. Click on a track with the mouse. Press and hold shift. Click on another track with the mouse. Now all tracks between those two (including them) are now selected.
2. Click on a track with the mouse. Press and hold shift. Use the up/down cursor keys. The selection grows/expands accordingly.

If that's not working for you then I cannot really help you with it, unfortunately.

**Comment by mbunkus** [comment]
See https://youtu.be/QET-MifgJLM for example.

**Comment by jtanx** [comment]
Hmm I guess I should have explained myself better - I was trying to shift-click between the checkboxes so that it would uncheck the checkboxes as you shift-clicked. 

I know you can shift-click and select `Mux this track: no` but it seems more intuitive to me to be able to shift-click the checkboxes to uncheck them.

**Comment by mbunkus** [comment]
I see. No, that won't be implemented; for at least two reasons: it would be functionality that diverges from the paths users are used to and users expect making it hard to discover and understand; it would require a lot of hacking around Qt's handling of multi-selection mode. Sorry.

**Comment by jtanx** [comment]
Ah, okay - I thought it was standard behaviour (all the web email clients e.g. gmail/hotmail etc allow this) but I guess not.

Thanks for having a look anyway :)
