### ISSUE TITLE
New GUI: showing "date finished" when job is not finished

### ISSUE THREAD

**Issue by fatalistt** [mbunkus/mkvtoolnix#1323]
I start the job. It finished with error, "date finished" show normal time. (not enough space on drive)
Then i restart this job and "date finished" still show the previous value.
I expect that it will be null when i restart job.
![image](https://cloud.githubusercontent.com/assets/3428774/8438468/a5df35f8-1f6e-11e5-8874-67c48402ced3.png)

**Comment by mbunkus** [comment]
Thanks for the report. This looks indeed like a bug.
