### ISSUE TITLE
Merging m2ts files to mkv using the additional parts option

### ISSUE THREAD

**Issue by mauerman** [mbunkus/mkvtoolnix#1324]
Hello

I have ripped my bluray edition of The Lord of The Rings trilogy, and have gotten the m2ts files out. They work fine by themselves, but when I try merging them with mkvmerge, first picking the part 1 file, and then using additional parts to select part 2 so I will end up with one whole mkv file with the entire movie in it. I have tried tis multiple times, with different versions of the program, 7.5.0 and 8.1.0. I get the same result, and that is one mkv file with the length of both files, but when the first part is done, it plays the credits, and then the rest of the movie, with only the video fucked up. It plays the full length, close to 4 hours, but it always ends up screwing up about halfway in. I don't know what is going wrong, and I was hoping somebody might know something. Each m2ts file is about 30 gb in size, I don't know if that has anything to do with it.

Any help is appreciated,

Mauerman

**Comment by mbunkus** [comment]
First off don't use »add as additional parts« with Blu-ray .m2ts files. Second, don't use the .m2ts directly but add .mpls playlists instead. Please see [this FAQ entry](/mbunkus/mkvtoolnix/wiki/Appending-files-vs.-adding-as-additional-parts) for details and the reasoning behind this advice.

**Comment by Maal656** [comment]
...Reading your FAQ entry I've discovered that it is possible to load DVD .VOB files, which are automatically added "as additional parts".

By means of this method it is possible to control the audio and video of the DVD... ¿Is there any option to control also the subtitles, which I believe are stored in the .IFO file?

Sorry if the question is out of the topic of the original comment, but as it is just a question I didn't want to open a "new issue"...

**Comment by mbunkus** [comment]
No, mkvmerge cannot read DVD .IFO files.

**Comment by mbunkus** [comment]
I'm closing the issue due to lack of feedback from the original poster.
