### ISSUE TITLE
GUI: Add back the ability to automatically delete merge job on addition to job queue

### ISSUE THREAD

**Issue by tjackson0** [mbunkus/mkvtoolnix#1326]
8.1.0 64-bit

There was a check box to enable deleting a merge job (input job) when it was added to the job queue.  Please re-implement that feature.

**Comment by mbunkus** [comment]
I'm not sure what you mean as the old GUI doesn't have an option that's labeled »delete merge/input job«. There is an option called »clear inputs after adding a job to the job queue«. If you mean that entry then you'll find that option in MKVToolNix in v8.1.0 as well. Open the preferences, go to the »merging« tab and look at the »clear settings automatically« option.

f you mean something else then please describe what you meant, preferably by providing a screenshot highlighting the option you're missing.

**Comment by tjackson0** [comment]
I didn't have access to the old UI, so I was going off memory.  That was what I was looking for.  I passed by "Clearing settings automatically" when going through the preferences...  that doesn't make me think of removing input files.
Thanks for the assist.
