### ISSUE TITLE
New GUI: layout proposal: move status bar text right and let progress bars expand

### ISSUE THREAD

**Issue by tjackson0** [mbunkus/mkvtoolnix#1327]
Currently the status bar allocates a very small area to the progress bars.  I would propose that you move the text to the right and let the two progress bars expand equally to take up any space on the right.  Please see the images 
![current](https://cloud.githubusercontent.com/assets/7431203/8445801/f32a9eac-1f5e-11e5-8887-9f7eb5f1ae98.PNG)
![proposed](https://cloud.githubusercontent.com/assets/7431203/8445805/0cad683c-1f5f-11e5-9229-e5e76914272b.png)

**Comment by mbunkus** [comment]
No, sorry. The left part is left for arbitrary messages. They can have any length. Letting the progress bars expand automatically would mean that they would be resized each time a message is shown or hidden. That would be highly irritating and confusing.
