### ISSUE TITLE
Feature Request: Default Field on Track Selection

### ISSUE THREAD

**Issue by pokeguru87** [mbunkus/mkvtoolnix#1330]
In the old tool when you selected a track it would automatically put the cursor into the "Track Name" field. This would allow me to record macros with my Logitech Keyboard for common settings I would use. I have a standard set of settings I use for particular types of tracks (i.e. I do a lot Dual Audio tracks and for English I have one set of settings and for the other language another, same for subtitle tracks). Even without the use of macros, this would be a good quality of life feature.

Ideally, it would be nice if we could create profiles of settings and then be able to apply them to a track using the context menu, a drop down in the track list, a drop down in the Properties section or better yet all 3 of the previous options.

**Comment by mbunkus** [comment]
Thanks for the feedback.

The problem with setting the focus into an input field is that it totally destroys keyboard navigation in the track list. Yes, there are people who use the keyboard for such things, especially handicapped people with difficulties using a mouse (#1279 is about that topic, too).

The track name input is one of the few ones that actually has a keyboard shortcut assigned to it (Alt+k with an English locale). Can't you start your keyboard macros with that and go from there?

I will not implement track setting profiles at the moment or in the foreseeable future. It's a lot of work (you'll have to be able to manage them somehow, you have to be able to say »set this field but not that one« etc.). And as you've pointed out already there are other ways of automating such things, e.g. with Logitech's tools or with something like AutoIt or AutoHotKey (and corresponding programs on non-Windows platforms).

**Comment by pokeguru87** [comment]
I did not know, about the Alt-K shortcut, I can modify my macros to take advantage of that, while it isn't my ideal solution, it is much better than doing it manually like I was.

**Comment by mbunkus** [comment]
Yeah.... Windows doesn't underline the keyboard shortcuts by default anymore. You can press and hold Alt, then the shortcuts should be visible.
