### ISSUE TITLE
Feature Request: Chapter File as Source File

### ISSUE THREAD

**Issue by pokeguru87** [mbunkus/mkvtoolnix#1332]
If you could drag and drop a Chapter file (XML or OGM formats, but I feel XML would be the more common of the two) like you do with video/audio/subtitle tracks.

**Comment by mbunkus** [comment]
Thanks for the feedback. mkvmerge does not support treating pure chapter files as input files. Therefore the GUI cannot treat them as normal input files either. Changing this would require a lot of work on both mkvmerge and some work on the GUI and the associated documentation for little gain, and I will not do that.

However, your point is likely mostly that you would like to be able to drag & drop (or maybe even add via the button) chapter files in the GUI. Maybe something like this might work for you:

- When dragging & dropping chapter files the GUI will not add the file to the list of input files but instead insert the chapter file's name in the appropriate input control on the »output« tab.
- If there's a chapter file name present in that control then the GUI will warn you/ask you what to do (ignore, replace).

If that would suffice for you then that's something I can implement.

**Comment by pokeguru87** [comment]
Yes, drag and drop would be perfect. I wasn't even thinking about listing it as a Track, more of just in the source file list or something similar, but if it just put it into the Chapter File box on the Output tab automatically, that would be immensely useful to me at least.

**Comment by mbunkus** [comment]
Alright, I'll put it on my TODO for 8.3.0 for the time being.

**Comment by bastik-tor** [comment]
(I hadn't wasted a second on realizing that chapters are in the output tab, although I'd consider it an input file. The old GUI had it in a separate tab as well, but it's different because the GUI was structured like that.)

The initial reason I wanted to reply to this issue is to ask if the same can be done for tags (tags.xml) and if so if that requires another issue.

**Comment by mbunkus** [comment]
The problem with dragging & dropping tags is that you might want to add tags for a specific track and not global tags. That the GUI would have to ask you, something that would likely be somewhat confusing. This is different from the chapters as there can only be global chapters but not chapters per track (unlike tags: there can be both global tags and tags for each track).

Therefore I'm not sure if I'm willing to implement this for tags, too.

**Comment by bastik-tor** [comment]
> The problem with dragging & dropping tags is that you might want to add tags for a specific track and not global tags.

The idea was to drag it into the "input" field, where you'd enter the path to the tags.xml (which I wouldn't consider a hidden drop target).

(That global tags and tags for a specific track have different use cases is something I am aware of.)

**Comment by mbunkus** [comment]
That's not what this issue has been about, though, it was about dragging any chapter file anywhere in the input tab and its file name would be put into the corresponding text input on the output tab.

Dragging & dropping files directly onto text inputs and having their file name appear therein is something that actually works out of the box in Qt. Unfortunately this got broken somehow when I implemented drag & drop support for adding input files in general. I don't know how to restore the original behavior, though I'd like to have that working again…

Your request is different enough from this issue that you should probably open a new issue for it. Generally two different issues would be useful: 1. dropping tag files anywhere and having them treated as global tags and 2. making dropping file names directly on text inputs work again like it used to.
