### ISSUE TITLE
tool selector background color

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1333]
Several people don't like the tool selector background. They'd prefer something else, e.g. the default window background color.

**Comment by remuxer32** [comment]
>Several people don't like the tool selector background.

Me too. Especially black colour which disrupts a cheerful mood (as we know the new GUI is bright so black colour is an antagonist). Black vs white = fire vs water. That's why I'm very glad because of this idea. I look forward to seeing a new colour. It will be »delicious« for me :)

**Comment by remuxer32** [comment]
Fantastic! You're very fast. Thank you very much Mosu. Now I'm waiting for a new pre-build :)

**Comment by mbunkus** [comment]
*sigh*

Today another user emailed me and had this to say:

> I installed build 816 yesterday and I saw that you changed
> background color for tool selector :(
>
> I was surprised to see that the reason for this change is that some
> users don't like black background. I must say that now I have to
> voice my opinion too and say that I really prefer black color with
> white letters (plus gray gradient for selected tool) instead the
> opposite. I think usability wise it's much better solution and it
> looks better and more pleasing.
>
> Also, that sharp thin vertical line that separates tool selector
> just looks very distracting from the rest of the GUI and also looks
> like the status bar is now part of the tool selector.
>
> Is it possible for you to least add the option for black background
> as a preference in .ini file or is that impossible? I see that in
> .ini there's some window geometry settings so maybe it's possible?
>
> I know this is just cosmetics but the identity of the new GUI for me
> is now completely changed and I already started to use
> mkvtoolnix-gui every day.

Really. OK, so beauty is in the eye of the beholder, and I've reached
the end of my patience with such issues. I will now revert the change
as the original look was what I originally intended.

If someone cares about this enough then (s)he should provide a patch
that makes this whole thing configurable. I won't spend another minute
on this.
