### ISSUE TITLE
Cannot found tracks in some big m2ts files

### ISSUE THREAD

**Issue by lazyeugene** [mbunkus/mkvtoolnix#1336]
'00001.m2ts': Using the demultiplexer for the format 'MPEG transport stream'.
Error: No streams to output were found. Aborting.

However, tracks are present and tsmuxes works fine. Size of 00001.m2ts is about 30G

Example to download: http://rutracker.org/forum/viewtopic.php?t=3875703

**Comment by mbunkus** [comment]
I do not download from random forums, especially not if they require registration before downloading and use a language I don't speak. Sorry.

If you want me to take a look then please upload the first 100 MB of that file to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by lazyeugene** [comment]
File "howls_moving_castle.m2ts" on your ftp. As you ask: fisrt 100MB.

**Comment by mbunkus** [comment]
Thanks, I can confirm the issue and will look into it.

**Comment by mbunkus** [comment]
The file is badly mastered. All PATs (program associataion tables) and PMTs (program mapping tables) have a wrong CRC. I've adjusted mkvmerge to handle those cases, too.
