### ISSUE TITLE
New GUI "append" files end with error

### ISSUE THREAD

**Issue by ilyadan** [mbunkus/mkvtoolnix#1340]
I am new to this, please exuse me if this is inappropriate.
I use version 8.1.0 x64 on Windows 7 x64. The same issue exists also in version 8.0.0.
To repeat the bug please open one MKV file in the new GUI (mkvtoolnix-gui.exe). Then click it and choose "Append Files". Add more then one file. (2 files or more). Click "start muxing" and get error: 
"More than one track is to be appended to the track 0 from file no. 0 ('anyfile.mkv'). The argument for '--append-to' was invalid."
Same works well in the old GUI.

**Comment by mbunkus** [comment]
This has already been fixed in #1313.
