### ISSUE TITLE
ability to order track in mkvtoolnixgui

### ISSUE THREAD

**Issue by littlenunu** [mbunkus/mkvtoolnix#1343]
I use mkvmergegui since a long time and i wanted to switch to mkvtoolnixgui because the first one seems to disappear for the next version.
In mkvmerge, i could up/down the tracks/chapters/tags but i can't find this option in mkvmergetoolnix.

**Comment by mbunkus** [comment]
You can simply drag & drop tracks (even more than one at the same time).

One additional option will be added in the future: moving by key presses and optional buttons (though both are much less convenient than simply dragging & dropping). See #1279.
