### ISSUE TITLE
Dropping tagfiles onto the GUI should treat them as global tags

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1345]
Currently MKVToolnix GUI rejects XML files that contain tags when they are just dropped onto the GUI, because they are treated different from input files.

This issue asks to treat them as they were intended to be global tags, when they are just dropped onto the GUI.

**Comment by mbunkus** [comment]
Thanks for opening the two issues.

**Comment by mbunkus** [comment]
Implemented in 74881cd64c576e73739d714d266c88b9d618c366.
