### ISSUE TITLE
PCM streams detected as video streams

### ISSUE THREAD

**Issue by dxhelios** [mbunkus/mkvtoolnix#1346]
Hi,

I noticed that when I add w64, pcm files to mkvtoolnix GUI, streams are marked as video streams instead of audio.
![capture](https://cloud.githubusercontent.com/assets/12989024/8579941/48da66d6-25c0-11e5-89ce-5f610eed32c5.PNG)
Uncompressed RAW audio is in the list of importable files. eac3to detects files normally.

**Comment by mbunkus** [comment]
Those are WAV files with special chunks, aren't they? Those are currently not supported and mis-detectetd, as it seems, yes.

I'd need a sample file to work with if you want me to look into it. Please upload one to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by mbunkus** [comment]
Thanks for the upload. Now I know what you mean: raw PCM streams without any file header. Such files are not supported and will never be supported as they cannot be recognized unambiguously.

The WAV you've uploaded is recognized just fine. WAVs are supported.

**Comment by dxhelios** [comment]
Hello, Moritz,


I see. Exactly. You know, I noticed that in the open dialog there was "uncompressed PCM audio", on the same line as WAV.


If I may, I would like to do small feature request: I would be nice to see source file audio channels configuration. Something like that:

7.1/48000Hz/24bit


Thanks.






Sent from Windows Mail





From: Moritz Bunkus
Sent: ‎Saturday‎, ‎July‎ ‎11‎, ‎2015 ‎11‎:‎17‎ ‎AM
To: mbunkus/mkvtoolnix
Cc: dxhelios





Thanks for the upload. Now I know what you mean: raw PCM streams without any file header. Such files are not supported and will never be supported as they cannot be recognized unambiguously.

The WAV you've uploaded is recognized just fine. WAVs are supported.

**Comment by mbunkus** [comment]
There's already a feature request open for this, see #1295.

**Comment by dxhelios** [comment]
Oh. Great. Thank Moritz.


Have a great weekend!






Sent from Windows Mail





From: Moritz Bunkus
Sent: ‎Saturday‎, ‎July‎ ‎11‎, ‎2015 ‎12‎:‎48‎ ‎PM
To: mbunkus/mkvtoolnix
Cc: dxhelios





There's already a feature request open for this, see #1295.
