### ISSUE TITLE
Merging Files - resulting file is bigger but not "longer"/Windows 64-bit 8.1.0

### ISSUE THREAD

**Issue by Krawk** [mbunkus/mkvtoolnix#1347]
Am attempting to merge two MKV files - tried mkvmerge gui and toolnix gui interfaces, get same results.
File 1 is 4.4GB at 2:58:31
File 2 is 1.49GB at 1:09:24

The new file is 5.90GB but still only 2:58:31. When I reach the chaptered end of where the first file would have been, instead of going to the next chapter, it loops back to the beginning. Looking at video 3 (the result) is this just adding another angle or something?

Windows 7/64
mkvmergegio/toolnix 8.1.0

(According to mpc-ht)
Video 1 details:
Video: MPEG4 Video (H264) 636x480 29.97fps [V: h264 high L3.0, yuv420p, 636x480 [default]]
Audio: Dolby AC3 48000Hz stereo 192kbps [A: English [en] (ac3, 48000 Hz, stereo, 192 kb/s) [default]]

Video 2 details:
Video: MPEG4 Video (H264) 636x480 29.97fps [V: h264 high L3.0, yuv420p, 636x480 [default]]
Audio: Dolby AC3 48000Hz stereo 192kbps [A: English [en] (ac3, 48000 Hz, stereo, 192 kb/s) [default]]

Merged Video details:
Video: MPEG4 Video (H264) 636x480 29.97fps [V: h264 high L3.0, yuv420p, 636x480 [default]]
Video: MPEG4 Video (H264) 636x480 29.97fps [V: h264 high L3.0, yuv420p, 636x480]
Audio: Dolby AC3 48000Hz stereo 192kbps [A: English [eng] (ac3, 48000 Hz, stereo, 192 kb/s) [default]]
Audio: Dolby AC3 48000Hz stereo 192kbps [A: English [eng] (ac3, 48000 Hz, stereo, 192 kb/s)]

Command Line parameters:
"C:\Program Files\MKVToolNix\mkvmerge.exe" -o "D:\\Dvd Rips\\Video\\DINOTOPIA\\DINOTOPIA.Title3 (1).mkv"  "--default-track" "0:yes" "--forced-track" "0:no" "--display-dimensions" "0:636x480" "--language" "1:eng" "--default-track" "1:yes" "--forced-track" "1:no" "-a" "1" "-d" "0" "-S" "-T" "--no-global-tags" "(" "D:\\Dvd Rips\\Video\\DINOTOPIA\\DINOTOPIA.Title3.mkv" ")" "--forced-track" "0:no" "--display-dimensions" "0:636x480" "--language" "1:eng" "--forced-track" "1:no" "-a" "1" "-d" "0" "-S" "-T" "--no-global-tags" "(" "D:\\Dvd Rips\\Video\\DINOTOPIA_DISK_2___ROM\\DINOTOPIA_DISK_2___ROM.Title3.mkv" ")" "--track-order" "0:0,0:1,1:0,1:1" "--title" "DINOTOPIA.Title3"

**Comment by mbunkus** [comment]
You have to »add« the first file and »append« the second one (right-click on the first file, then select »append« from the context menu).
