### ISSUE TITLE
Chapter Editor's "Save to Matroska file" option greyed out

### ISSUE THREAD

**Issue by DarthWong** [mbunkus/mkvtoolnix#1350]
After loading a chapter file into the chapter editor, the "Save to Matroska file" option is greyed out and cannot be selected.  This condition can be fixed by creating a new tab in the chapter editor and then closing the empty tab.  After doing that and returning to the previous tab, the "Save to Matroska file" potion is now selectable.

**Comment by mbunkus** [comment]
Thanks for the report. This has already been fixed; see #1312.
