### ISSUE TITLE
mkvmerge -I doesn't show statistic tags

### ISSUE THREAD

**Issue by dr-schanker** [mbunkus/mkvtoolnix#1351]
When analyzing a .mkv with mkvmerge, track statistic tags are not shown. I tested the portable windows build 8.1.0 (32bit and 64bit variant) with Windows7 64bit.

- Example command line:
"C:\Users\drs2\Downloads\mkvtoolnix-32bit-8.1.0\mkvtoolnix\mkvmerge.exe -I C:\Users\drs2\Desktop\sintel_trailer-720p.mkv"

- Result for mkvtoolnix-32bit-8.1.0:
File 'C:\Users\drs2\Desktop\sintel_trailer-720p.mkv': container: Matroska [duration:52209000000 segment_uid:9ed3d5a125cd1841b169ab682138438c is_providing_timecodes:1]
Track ID 0: video (MPEG-4p10/AVC/h.264) [number:1 uid:5516246490188700852 codec_id:V_MPEG4/ISO/AVC codec_private_length:42 codec_private_data:0164001fffe100196764001fac34e6014016e840000003004000000c03c60c668001000668e9784cb22c language:eng track_name:AVC\s720p pixel_dimensions:1280x720 display_dimensions:1280x720 default_track:1 forced_track:0 enabled_track:1 packetizer:mpeg4_p10_video default_duration:41666665]
Track ID 1: audio (AAC) [number:2 uid:9023791364632589184 codec_id:A_AAC codec_private_length:2 codec_private_data:1190 language:eng track_name:AAC\s2ch default_track:1 forced_track:0 enabled_track:1 default_duration:21333333 audio_sampling_frequency:48000 audio_channels:2]

- Result for mkvtoolnix-32bit-7.8.0:
File 'C:\Users\drs2\Desktop\sintel_trailer-720p.mkv': container: Matroska [duration:52209000000 segment_uid:9ed3d5a125cd1841b169ab682138438c is_providing_timecodes:1]
Track ID 0: video (MPEG-4p10/AVC/h.264) [number:1 uid:5516246490188700852 codec_id:V_MPEG4/ISO/AVC codec_private_length:42 codec_private_data:0164001fffe100196764001fac34e6014016e840000003004000000c03c60c668001000668e9784cb22c language:eng track_name:AVC\s720p pixel_dimensions:1280x720 display_dimensions:1280x720 default_track:1 forced_track:0 enabled_track:1 packetizer:mpeg4_p10_video default_duration:41666665 tag_bps:1033703 tag_duration:00\c00\c52.209000000 tag_number_of_frames:1253 tag_number_of_bytes:6746078 tag__statistics_writing_app:mkvmerge\sv8.1.0\s('Psychedelic\sPostcard')\s32bit tag__statistics_writing_date_utc:2015-07-11\s09\c26\c35 tag__statistics_tags:BPS\sDURATION\sNUMBER_OF_FRAMES\sNUMBER_OF_BYTES]
Track ID 1: audio (AAC) [number:2 uid:9023791364632589184 codec_id:A_AAC codec_private_length:2 codec_private_data:1190 language:eng track_name:AAC\s2ch default_track:1 forced_track:0 enabled_track:1 default_duration:21333333 audio_sampling_frequency:48000 audio_channels:2 tag_bps:126696 tag_duration:00\c00\c51.946000000 tag_number_of_frames:2435 tag_number_of_bytes:822671 tag__statistics_writing_app:mkvmerge\sv8.1.0\s('Psychedelic\sPostcard')\s32bit tag__statistics_writing_date_utc:2015-07-11\s09\c26\c35 tag__statistics_tags:BPS\sDURATION\sNUMBER_OF_FRAMES\sNUMBER_OF_BYTES]
Tags for track ID 0: 7 entries
Tags for track ID 1: 7 entries

**Comment by mbunkus** [comment]
This was an intentional change. Track statistics tags are now dropped when reading a file. I currently don't have any plans for changing this behavior. You can get the tags out of a Matroska file with mkvextract.

**Comment by mbunkus** [comment]
I've just committed b6d8b0de92b805f4dbdbcee74cba5c8d8de48f7e in which I've added an additional option that causes mkvmerge to keep those tags for identification purposes. It's called `--engage keep_track_statistics_tags` to be used in combination with `--identify-verbose yourfile.mkv`.

**Comment by dr-schanker** [comment]
Brilliant, thanks a lot. The [FAQ] (https://github.com/mbunkus/mkvtoolnix/wiki/Automatic-tag-generation) was updated as well. :thumbsup:

**Comment by mbunkus** [comment]
Actually I was answering another user and told him to check the FAQ entry on how to get the statistics tags, and when I read it I remembered this particular change. So I decided to go ahead and implement this workaround.
