### ISSUE TITLE
Problem with timestamps on FLAC files extracted with mkvextract

### ISSUE THREAD

**Issue by alweekes** [mbunkus/mkvtoolnix#1352]
I've been putting together a bash script to simplify the ripping of audio tracks from BluRay audio disks to FLAC files.

I use MakeMKV to create the original rip, resulting in an MKV file with the audio track (2ch LPCM in most cases) embedded in FLAC format. I choose the audio track to embed using the MakeMKV GUI.

I then use 'mkvmerge --split-chapters:all' to produce a number of individual MKV files, the splitpoints of which represent the audio tracks on the disk.

Finally I use 'mkvextract tracks' to loop over the MKV files and produce the final FLAC files.

The problem I'm experiencing is that the resultant files have timecodes (not sure if this is the correct terminology) that means every file shows as having the same length, i.e. that of the original source MKV file, before splitting.

Also track start times are the chapter start positions within the original MKV file.

This obviously makes perfect sense in the context of video, but for audio it throws most players off, confusing them; for example, the second track might start at 5m39s, but has a length of over an hour.

I haven't been able to find an option to change this behaviour, what is desirable is for every track to have a start time of zero, with the length of the track (or chapter in the context of the source file).

Is this possible? If so I'd be hugely grateful if you could you throw some enlightenment my way please.

If it helps this is the script I'm developing, the idea is to simplify the extraction and tagging workflow of BluRay audio discs: -

http://pastebin.com/6eDJuzzJ

**Comment by mbunkus** [comment]
Splitting and appending FLAC tracks is not supported. This is a known limitation that won't be fixed. Please see #953 for details.
