### ISSUE TITLE
GUI: Feature Request: Show »default track language« in the table overview (Tracks, chapters, tags and attachments)

### ISSUE THREAD

**Issue by AnselmD** [mbunkus/mkvtoolnix#1353]
Hi,
In the table overview (Tracks, chapters, tags and attachments), it is not recognizable which track ( video, audio and subtitle) is the default one. 

Solution can be: new default column, mark default rows bolt (or mark them in another way), put default rows to the top.

**Comment by mbunkus** [comment]
Thanks for the suggestion. I may implement this, maybe together with #1268.

**Comment by mbunkus** [comment]
Implemented in 643af866a6034363c4fc75e86787da532eec12ae.
