### ISSUE TITLE
Remove Attachments

### ISSUE THREAD

**Issue by pokeguru87** [mbunkus/mkvtoolnix#1357]
When trying to remove multiple attachments, fonts in this case, it doesn't remove all selected attachments. It will remove a number of them and then the rest is left, and they are still selected. In my case I have 24 fonts and with all them selected I have to right click and choose "Remove" four times before all of the fonts are gone.

Also a Remove All would be helpful on the Attachments screen.

**Comment by mbunkus** [comment]
Thanks for reporting it. It has already been fixed. See be286bc1851a6bdb9767674f4c051a2ad788f013.

If you have many attachments you should seriously think about just creating new mux settings, that's as easy as pressing Ctrl+N or selecting »new« from the »merge« menu. Alternatively select all attachments by pressing Ctrl+A (only works if the attachment list is currently focussed).
