### ISSUE TITLE
Regression: Merge | New and tabs three dots instead of name of the tab

### ISSUE THREAD

**Issue by igor2x** [mbunkus/mkvtoolnix#1360]
On Ubuntu 14.04 I just updated packages and new version 8.2.0 of "MKVToolNix GUI" has been installed from http://www.bunkus.org/ubuntu/trusty/ Ubuntu PPA.

I see tab names corrupted. Instead of real names there are just three dots displayed. It looks like some feature to truncate tab's names was implemented.

The attached image is result of menu selection Merge | New:
![tab_names](https://cloud.githubusercontent.com/assets/10895030/8765091/0a80fb94-2dfd-11e5-817f-0df0c3e9903a.png)
 
I am sure this is a regression problem, that appeared in 8.2.0 version.

**Comment by mbunkus** [comment]
Thanks for the report. Huh… yes, tab names are supposed to be truncated now, but only those of the settings themselves. This became necessary as people were using really long file names without spaces in them leading to excessively wide tab names which in turn lead to an excessively wide GUI.

However, the three tabs inside the settings aren't supposed to be truncated, or at least they should not have to be as there's more than enough space available in your screenshot. It may also be a bug in the Qt version used on Ubuntu 14.04 as I don't see such behavior on Arch Linux, Windows nor on Mac OS.

I'll look into this, but most likely not that soon as it's purely cosmetic and doesn't affect all platforms.

**Comment by mbunkus** [comment]
Should be fixed by the commit linked above. If not then shout (I haven't actually tried it as I don't have a Ubuntu 14.04 system with X installed, only my build-root environment).

**Comment by igor2x** [comment]
Today I installed v8.3.0 and problem is fixed. Thanks a lot.
![names](https://cloud.githubusercontent.com/assets/10895030/9292369/abd6f324-43f4-11e5-831f-e8b33df8420a.png)

**Comment by igor2x** [comment]
By the way I looked through "Change Log" and I can't see this fix listed. According to commit about it should be listed in 2015-07-19, but at that date there is no fix listed. See: http://mkvtoolnix-releases.bunkus.org/doc/ChangeLog

**Comment by mbunkus** [comment]
It's quite possible that I forgot to add an entry for it.

**Comment by igor2x** [comment]
... or maybe you were not 100% sure if this is really fixed, because you don't use Ubuntu to test the problem.

Thanks for fixing the problem.

**Comment by mbunkus** [comment]
That's certainly another possibility :) You're welcome.
