### ISSUE TITLE
New GUI much less efficient than the old one

### ISSUE THREAD

**Issue by astaroth63** [mbunkus/mkvtoolnix#1362]
In the last version (8.2.0), MKVToolNix GUI took 1 minute and 6 seconds to perform the same job that mkvmerge GUI took 13 seconds.

![mkvtoolnix-gui](https://cloud.githubusercontent.com/assets/13417776/8776345/b0e32a4c-2ec6-11e5-9224-0662a113a041.png)
![mmg](https://cloud.githubusercontent.com/assets/13417776/8776346/b0e41ec0-2ec6-11e5-88ef-9d2fd8f54dc2.png)

**Comment by mbunkus** [comment]
Both GUIs are only frontends for mkvmerge. mkvmerge is the tool that does the actual work. Therefore the new GUI cannot be slower than the old one.

I'm pretty sure that what you're seeing here is the operating system cache at work. You've probably merged with the new GUI first and later with the old one. Therefore a significant portion of the files has already been present in the cache and didn't have to be read from the hard drives again.

If you want to compare numbers then mux the same files with the same settings two times with each GUI (e.g. new GUI, new GUI, old GUI, old GUI) and only compare the numbers achieved by the second run for each GUI.

If you can find significant differences in those second runs then please shout, but I'll close this issue as invalid until then.
