### ISSUE TITLE
Feature request: use segment uid from existing file

### ISSUE THREAD

**Issue by demifiend9** [mbunkus/mkvtoolnix#1363]
I'm remuxing a bunch of mkvs which uses ordered openings and endings. Right now, I have to either manually enter the old segment uid when remuxing OP and EDs or Edit the chapter information of all mkvs according to the segment uid of remuxed OP and EDs.

A new global option, something like "--use-segment-uid FID" to use the segment uid from the existing file would make remuxing ordered mkvs much easier.

**Comment by mbunkus** [comment]
Thanks for the suggestion. The subject is not quite correct, though, is it? You want to re-use a segment UID from a file, not from a track.

I will likely implement something like this, though it will likely not be with a new option but by extending `--segment-uid` with a different syntax.

**Comment by demifiend9** [comment]
Yes, I meant file, not track. sorry.

**Comment by mbunkus** [comment]
No problem at all.
