### ISSUE TITLE
MKVToolNix GUI: bug found: duplicating entries via drag & drop + APPCRASH

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1365]
See: https://youtu.be/LokbOU_8_JM

**Comment by mbunkus** [comment]
This turned out to be the same underlying issue as #1221. I couldn't reproduce any of your four examples here, but I am going to push a potential fix for you to test.

**Comment by mbunkus** [comment]
I've uploaded a new pre-build and would appreciate some testing.

**Comment by mbunkus** [comment]
Well, I didn't want to close this one just yet…

**Comment by remuxer32** [comment]
Thanks for your pre-build. I will be testing it intensively and inform you soon about the results.

**Comment by remuxer32** [comment]
Breaking news: I've just installed that pre-build and have started testing. My first conclusion: it seems that you've broken something because the GUI doesn't remember my own settings at all! For example: I've changed language interface from Polish to English, and checked e.g. »Always use a default description........«. Then I've run a program again, and language interface is in Polish instead of English etc. That check box is uncheck of course. Please try it on your Windows 8.1. You should see the same behaviour. Just change language interface from English to German, and run the program again.

More conclusions soon.

**Comment by mbunkus** [comment]
Yep, happens here, too.

Please test the drag & drop issue, it should be completely independent of the settings issue.

**Comment by mbunkus** [comment]
A new pre-build is up that should fix the »loading preferences fails« issue.

**Comment by remuxer32** [comment]
About »attachments« tab: duplicating entries + APPCRASH still exist:

![crash](https://cloud.githubusercontent.com/assets/10992208/8835294/dcc84828-30b9-11e5-9ddb-ebc69e0ccd74.png)

About »Input tab«: duplicating entries this time (theoretically) no longer exists, but when I clicked on »Remove files« (two files), then.....this is the result: 

![crash 2](https://cloud.githubusercontent.com/assets/10992208/8835344/349f2ff8-30ba-11e5-9288-9639e2e1acaf.png)

So: pre-build 829 is bad definitely.

I need to check chapter editor & job queue else........

**Comment by mbunkus** [comment]
*sigh*

I cannot reproduce it. It seems that if I cannot reproduce it I won't be able to fix it. Giving up for now.

Thanks for testing.

**Comment by mbunkus** [comment]
I've just uploaded [pre-build 831](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) with another try at a fix. Note that this fix has only been applied to the attachments view in the merge tool, not yet to the other views!

Again I'd appreciate some testing of the attachments functionality.

**Comment by remuxer32** [comment]
All right. Thanks for your pre-build Mosu. I've been testing it (831) intensively for over a dozen minutes. Here are my conclusions:

1) About »Attachments« tab: it seems that your fix works because duplicating entries no longer exists, but I've noticed something strange: one of attachmensts....has gone! To be precise: it disappeared while dragging/dropping. I've added four .mkv files, and one of them disappeared. Of course I've been doing it very, very fast and intensively so maybe that's the reason? Anyway: such behaviour is very rare and seems to be harmless, but appears sometimes. I'm sure that most users won't notice such extraordinary behaviours (they would have to be very patient and do the same like me; very fast and intensively).

2) About »Input« tab: I confirm that APPCRASH sitll exists as above, but duplicating entries doesn't (theoretically) exist. So: how is it possible to cause APPCRASH? Here are my steps:

► I've appended one .mkv file with another
► I've been dragging & dropping tracks very fast and intensively
► And finally: I've clicked on »Remove files«, and booom! — APPCRASH!

3) About chapter editor: I confirm that duplicating entries no longer exists! That's a good news of course, but I've noticed that dropping entries is more difficult now than before. For example: I cannot move (change the entry order) e.g. Chapter 01 with Chapter 02 etc. To be precise: sometimes it works, sometims not; it's a lottery. Maybe my mouse is bad or such a behaviour is intentional? I have no idea. But as duplicating entries has been fixed, then I'm changing the main title of this issue now........

4) About job queue: it's the same case like in the first point: duplicating entries no longer exists, but sometimes one of jobs disappears while dragging & dropping tracks (very fast and intensively of course). Again: very rare behaviour and very hard to notice by most users. To be precise: I've added three jobs to queue, and one of them has disappeared via drag & drop.

Summarizing: I will create a new film for you in a couple of hours as a summary of all those points. You will see how the GUI behaves.

**Comment by bastik-tor** [comment]
Just for feedback. I tested this with the release version of 8.2.0 and I can't get it to crash, but I was able to reproduce the visual glitch where it appears that at least one entry moved one column to the right.

You can see this in one video at around 1:20: https://youtu.be/loVW4gFJ4HQ?t=1m21s

However I can't reproduce this reliably, so I won't be able to tell if a pre-release would have fixed it or if I just happen to not trigger it.

**Comment by remuxer32** [comment]
**@Mosu**

As I promised, I have created a new film for you (summary) that shows you how the GUI (pre-build 831) behaves. I was testing: »Input« & »Attachments« tab, chapter editor and job queue. Here is the direct link: https://www.youtube.com/watch?v=8_lXfHe8jKM
The film is very long (almost 20 minutes), but you should watch it very carefully to understand all issues.
The most interesting is definitely job queue where you can see extraordinary problems (disappearing entries). I'm interested in your opinion. Thanks.

**Comment by mbunkus** [comment]
Thanks for the feedback & the video. I haven't watched the video as I'm solely focusing on the attachments view at the moment and haven't changed the other views yet. Therefore it's expected to see the other views still being vulnerable.

I have been able to reproduce the issue that rows can simply vanish. I've created a fix for that, and for the time being I cannot get the attachments view to behave badly. There's even an upside: you can now drop on the other columns as well, not just on the first column (before you had to drop on the first column).

[Pre-build 832](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) is up. Again, this build only fixes the attachments view, not the other ones. Please give it a try.

If you can still make the attachments view misbehave then I need some further debugging information. Please do the following:

1. Download [Debug View](https://technet.microsoft.com/en-us/library/bb896647.aspx) from Microsoft. It's a simple tool showing debug messages generated by programs.
2. Start Debug View. Go to the options menu and enable the two options »clock time« and »show milliseconds«.
3. Now start MKVToolNix GUI and try to make the attachments view misbehave.
4. As soon as you see a bug (e.g. a line has vanished, or the entries end up in the wrong column like the attachment name being in the description column) stop and go back to Debug View.
5. In Debug View save the messages to a file (»File« menu → »Save«) and send me that log file.

Thanks.

**Comment by remuxer32** [comment]
Thanks for the feedback and the pre-build. I have decided to download the newest pre-build (833) instead of 832. I don't know what is the difference between them, but I suspect that 833 is better.

And now the most important: your fix works absolutely great! There are no bugs in the attachments view at all; no duplicating, no vanishing, no wrong columns! To be precise: I have added four attachments (.mkv files) and have started dragging & dropping tracks very fast and intensively for a long time — no issues at all :). I also confirm that dropping tracks on the other columns works absolutely fantastic; it's really nice and useful. Is it possible to implement such an extension for other views/tools (e.g. »Input« tab, chapter editor, job queue) for the next release? It will be really amazing if users could drop tracks for all columns instead of one.

But there is also something strange for me in the attachments view. So: I have selected all files and then I chose: »only to the first output file«. The result is that the only one (first) attachment has been set to that instead of all. Is it intentional or a minor bug? In my opinion all attachments should have been set to »only to the first output file« and vice versa. The same case if I choose one of tons options from »MIME type«; only one file is set instead of all. 

Thanks for clarification.

**Comment by mbunkus** [comment]
Thanks for testing. I definitely plan to implement similar changes for all the other list/tree views that support drag & drop. I only wanted to get it right for one of the views before I start modifying the other ones.

About multiple selection and changing properties: yes, changing a property should change it for all selected entries, not just the first one. Please open a new issue for it; it needs to get fixed.

**Comment by mbunkus** [comment]
I've now implemented similar fixes to all the remaining list views. I'd appreciate it if you could give it a try again.

The ones that you have NOT verified to be OK yet and for which I would appreciate some testing are:

- Merge tool: files, tracks
- Chapter editor: chapter/edition list, name list

The following ones have already been tested and found to be OK by you and do not need additional testing:

- Merge tool: attachments
- Job queue

Thanks.

[Pre-build 842](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) contains all the fixes.

**Comment by remuxer32** [comment]
Thank you for the fixes and the new pre-build. I will be testing it intensively. But I have to correct you about job queue: I have only verified the attachments view as positive fully, but not job queue. About job queue I wrote that duplicating entries no longer exists, but VANISHING entries happens sometimes. Please read my posts above again (especially point number 4). And finally: did you watch my long film that I have uploaded for you to watch? There you can see problems in the job queue tool. If you haven't watched it yet, then do that please now. Here is the direct link: https://www.youtube.com/watch?v=8_lXfHe8jKM
If you don't want to watch the whole movie, then at least start watching from 12:05 to the end; you will see issues in the job queue tool.

Thanks.

**Comment by mbunkus** [comment]
Hmmm you're right, I remember. I was in the middle of fixing the job queue… please leave the job queue be for the moment, I'll have to check it first.

**Comment by mbunkus** [comment]
I've added another fix to the job queue drag & drop mechanism. It's included in [pre-build 843](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/).

**Comment by remuxer32** [comment]
Thanks for the new pre-build. I will check that.

**Comment by remuxer32** [comment]
I've got good news. All tests have just been finished successfully; I've checked merge tool, chapter editor, and job queue. The result is that there are no bugs at all: no duplicating entries, no crashing, no vanishing, no strange behaviours = everything works great ☺.

It seems that you can close the issue now.

**Comment by mbunkus** [comment]
Thank you very much for testing!

**Comment by remuxer32** [comment]
You're welcome.
