### ISSUE TITLE
Merge tool: bug found: duplicating tracks via drag & drop + APPCRASH

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1366]
See: https://www.youtube.com/watch?v=AJEqTY5aeTM

Summarizing:

1) I have added two .mkv files to the merge tool
2) I have duplicated tracks via drag & drop
3) Finally I have clicked on »Enable all tracks«, and.......booom! — APPCRASH!

**Comment by mbunkus** [comment]
Same underlying issue as #1365.
