### ISSUE TITLE
Job queue: serious bug found: 3 in 1: duplicating entries via drag & drop + APPCRASH + cannot run application!

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1368]
This time I've found a serious bug in Job queue. Watch this film very carefully: https://youtu.be/loVW4gFJ4HQ

Summarizing: 

1) I have added three jobs to Job queue.
2) I have duplicated entries via drag & drop.
3) I have clicked on »Close« button, and......... booom! — APPCRASH!

And finally I have clicked on shortcut on my desktop. The result is: 

![bug](https://cloud.githubusercontent.com/assets/10992208/8831628/e5c9edd4-30a3-11e5-91e3-4cba9300f7e9.png)

That's why that bug is really serious. I cannot run application because of that! Whenever I click on shortcut, then I see that warning. I had to uninstall MKVToolNix and install it again! It's really annoying.

**Comment by mbunkus** [comment]
Thanks. A workaround for not being able to start the application: you can remove the »jobQueue« sub-tree of the HKEY_CURRENT_USER\Software\bunkus.org\mkvtoolnix-gui tree in the registry. That way you should not have to reinstall.

Not saying that this is a solution; just a workaround to make testing easier.

**Comment by remuxer32** [comment]
Thanks for your tip. Maybe I will try it next time during testing new pre-builds/releases.

**Comment by mbunkus** [comment]
Same underlying issue as #1365.
