### ISSUE TITLE
GUI enhancement - Autoswitch to job stats dialog

### ISSUE THREAD

**Issue by pdzugas** [mbunkus/mkvtoolnix#1376]
Please implement option that would allow GUI to switch automatically to current job stats dialog once user clicked Start muxing button. Details were discussed here http://forum.doom9.org/showthread.php?p=1732195#post1732195

**Comment by mbunkus** [comment]
Thanks for posting this.

**Comment by remuxer32** [comment]
I only hope that such an option will not be forced, but optional only. Users should have a choice if they want to switch automatically to the job output tool or not. That's why a new check box in the preferences would be nice :). Thanks.

**Comment by mbunkus** [comment]
It will definitely be optional.
