### ISSUE TITLE
Job warning/error messages displaying directory paths include file name as part of the directory path

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1378]
When merging mkv files, the warnings and error text boxes (on the "Job Output" panel) display messages like:

> --- Warnings emitted by job 'merging to file »test.mkv« in directory »x:/SomeFolder/test.mkv«' started on 2015-08-01 19:10:24 ---

Note that the output `directory »x:/SomeFolder/test.mkv«` erroneously contains the name of the mkv file (test.mkv).

**Comment by mbunkus** [comment]
Thanks for reporting it. You're right, of course, that looks like a minor bug.
