### ISSUE TITLE
When during start of MkvMergeGUI another running instance is detected, bring the window of that instance to the foreground

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1379]
I noticed that when starting MkvMergeGUI, it checks whether an instance of MkvMergeGUI is already running. If another running instance is detected, it does not start MkvMergeGUI again.

So far so good. But it should also bring the already running MkvMergeGUI to the foreground -- which it currently doesn't do. (Since the already running instance could be minimized or behind another window, it can be slightly confusing when trying to start MkvMergeGUI and nothing seems to happen...)

OS: Windows 7 Pro x64
Tested with mkvtoolnix 8.2.0 and with mkvtoolnix-32bit-8.2.0-build20150724-833-1bd8b01

**Comment by mbunkus** [comment]
Thanks for the suggestion. This sounds sensible. I'll implement it.

**Comment by mbunkus** [comment]
Huh… this is actually not possible on Windows. I didn't know that.

Microsoft doesn't allow applications that aren't currently in the foreground to be raised to the foreground programmatically. Both the [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646311(v=vs.85).aspx) and [Qt's documentation](doc.qt.io/qt-5/qwidget.html#activateWindow) agree on that.

Sorry.

**Comment by elgonzo** [comment]
You looked at the wrong place ;) It is possible: [SetForegroundWindow)(http://msdn.microsoft.com/en-us/library/windows/desktop/ms633539%28v=vs.85%29.aspx)

**Comment by mbunkus** [comment]
I didn't know that either ;) Thanks for pointing it out.

**Comment by mbunkus** [comment]
Well, it's really not possible to programmatically bring a window to the foreground. What happens, even if I use `SetForegroundWindow()` and not just the corresponding functions from Qt, is that the taskbar icon for the running instance will start to flash, it the window itself will stay in the background.

That's the best I will be able to do; more Windows doesn't allow.

**Comment by mbunkus** [comment]
I think that such a flashing indicator would be enough to solve the issue of the user becoming confused it no new window is shown. That's the point you raised in your original request.

**Comment by elgonzo** [comment]
Flashing is fine. The problem was that there was no response, but flashing certainly gives proper feedback.

Just as a side note about SetForegroundWindow (not intending to keep this issue alive; sorry for ranting), i wonder what is going on there.

SetForegroundWindow must bebe executed by the 2nd instance (the one that is detecting the first running instance) to "lift" the original 1st instance to the foreground -- the 1st instance cannot "lift" itself to the foreground. Maybe there is also some weird interference with QT which in your case prevents this from functioning... i don't know. But it is not a Windows issue per-se (there are plenty of programs out there capable of doing exactly that without any problems, Total Commander being one of them...). Anyway, flashing is totally fine and i consider this issue resolved :)

**Comment by mbunkus** [comment]
Hmm you're right, I'm calling `SetForegroundWindow` in the task that's currently in the background.

I'll leave it like this for now; if more users complain and ask for proper »bring to the front« then I'll re-open it.
