### ISSUE TITLE
Feature request: extend the number of jobs shown in the status bar

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1381]
According to discussion on Doom9's forum: http://forum.doom9.org/showthread.php?p=1732267#post1732267

I also agree that extending the number of jobs would be nice for users, too.

**Comment by mbunkus** [comment]
Thanks for opening tickets for those two issues from Doom9.

**Comment by remuxer32** [comment]
You're welcome, but, to be be precise, I have only opened one ticket about the second issue from Doom9's forum — number 1381. The previous one (number 1380; opened by me) applies to your blog, not Doom9's forum. I'm sure you mean a ticket number 1376 that applies the first issue from Doom9's forum, but it has been opened by **pdzugas**, not me.

**Comment by mbunkus** [comment]
The number of running jobs is now shown since commit ee8dae5da5b0c7244bb29d8593ec5da49beaf01c.
