### ISSUE TITLE
"Extra bytes" in a track make mkvtoolnix audio mux "go crazy" (out of synch)

### ISSUE THREAD

**Issue by giopgiop** [mbunkus/mkvtoolnix#1382]
Running Windows 7 ultimate. / 64bit
Playing file AVI "Ex Machina (2015).ita.eng.multisub.MIRcrew"
(I uploaded it in your FTP server) and it  plays OK as avi (via VLC player)

I load it in MKVToolnix GUI 8.2.0
I reencode it  it as mkv
and, in the log, appears this message:
Track 1: This AC3 track contains at the beginning 1847999 bytes of data not AC3.
This corrisponds to a 38528 ms delay. This delay is used instead of non-AC3 data

remux goes OK but audio is out of sync.
How is possible that only mkvtoolnix detects those extra bytes and shifts audio?

**Comment by mbunkus** [comment]
Thanks for the report. I'll investigate it. It sounds like a bug; the calculation of the delay is probably wrong.

**Comment by mbunkus** [comment]
[Pre-builds 870 & 871](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) for Windows are available. They include the fix.
