### ISSUE TITLE
A problem after Muxing!!

### ISSUE THREAD

**Issue by unixfx** [mbunkus/mkvtoolnix#1383]
Greeting.
First thank you for this great software ^^, secondly excuse my poor English because my mother language is Arabic.

Actually I Added HEVC video to convert it to MP4, KMV or to same format(HEVC) with indexing option (for all frames),to toggle between elapsed and remaining time freely,  as sneaker_ger said, the "raw" HEVC stream does not contain any kind of index, so when I used index option (add indexing for all frames) I got disruption for video exactly when I turned the time forward . it continuous around 6 seconds. 

check this link: http://im63.gulfup.com/TMo0qb.png

**Comment by unixfx** [comment]
I solved the issue .. thank you =)

**Comment by mbunkus** [comment]
Great. The thing is that you simply cannot seek to every frame. There are special frames (often called »key frames« or »I frames«), and you can only start decoding from such frames.

Even if the container has each and every frame listed in its index (that's what you did if I understand your initial post correctly) decoding can still only start successfully from those key frames.
