### ISSUE TITLE
GUI does not start on Windows 10

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1384]
As reported by at least two users: the GUI doesn't seem to start on Windows 10.

[HassID reported](https://www.bunkus.org/blog/2015/07/mkvtoolnix-v8-2-0-released/#comment-25034):
> hello and thanx for the quick reply. i made clean install of windows 10 (64-bit). i download the latest version again (8.2.0), 64-bit, uninstall it, and install it again – but it still not work. maybe because it 64 bit and not 32 bit?

and

> OK. i try install 32 bit, 64/32 bit portable, compatibility mode (windows 8) – but it still not work. when i open the file, i see the little spinning circle (near the arrow) for a second and nothing else. no message or anything else.

[RDF](http://forum.doom9.org/showthread.php?p=1733166#post1733166) has the same problem.

**Comment by RDF2050** [comment]
I forgot I could make an issue about this. I will do this next time.

**Comment by mbunkus** [comment]
Don't worry about it.

**Comment by mbunkus** [comment]
Stating what I've written on Doom9, too:

I've installed both the 32bit and 64bit versions of Windows 10 Professional (you can get ISO images legally directly from Microsoft without a problem, BTW). I've tried both the 32bit and the 64bit version of MKVToolNix. Here are the results:

    |                           | Windows 10 32bit | Windows 10 64bit |
    |---------------------------+------------------+------------------|
    | 8.2.0 release 32bit       | ✓                | ✓                |
    | 8.2.0 release 64bit       | –                | ✓                |
    | 8.2.0 current devel 32bit | ✓                | ✓                |
    | 8.2.0 current devel 64bit | –                | ✓                |

Meaning that for me, at least, all possible combinations run just fine, and I cannot reproduce the issue locally.

**Comment by RDF2050** [comment]
What about making something that can make a log if the program can't be open?

**Comment by mbunkus** [comment]
That's why I asked you to contact me via email on Doom9 ;) I haven't added the debug output yet, though.

**Comment by RDF2050** [comment]
The problem is that it doesn't open at all. I am unable to even make a log report. :(

**Comment by mbunkus** [comment]
Alrighty. Please do the following steps:

1. Download the [»debug view« utility from Microsoft](https://technet.microsoft.com/en-us/library/bb896647.aspx). It's a single exe, no need to install anything fancy.
2. Dowload [pre-build 845](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/mkvtoolnix-32bit-8.2.0-build20150808-845-bb290fa.7z) from bunkus.org. Unpack it into a directory of your choice. Don't run it yet.
3. Start debug view. Open the »options« menu and make sure that the two entries »clock time« and »show milliseconds« are enabled.
4. Start the MKVToolNix GUI. You should see a couple of lines appearing in debug view's window.
5. Wait a couple of seconds. Then, in debug view, save the lines via »FIle« → »Save«.
6. Send me that log file [via email](mailto:moritz@bunkus.org) (please don't post it in public, it may contain sensitive information, not necessarily from MKVToolNix but also from other applications).

Thanks.

**Comment by RDF2050** [comment]
I found a solution to the problem.  I got a similar problem with another application, ShareX, where it was denied access by Windows 10 system to read and write.  The solution to this problem was to change the rights of the mkvtoolnix folder. More information about this solution can be found here: https://github.com/ShareX/ShareX/issues/884#event-377064440

**Comment by mbunkus** [comment]
Just to make sure I understand what you think happened:

1. Back before Windows 10 you did have MKVToolNix located in some directory (either via the installer or the portable version, probably the portable version).
2. You upgraded to Windows 10
3. Now the already-existing MKVToolNix stopped working from that folder.
4. After changing the folder permissions you can now run MKVToolNix again?

That sounds like a bug in the Windows 10 upgrade routine…

**Comment by RDF2050** [comment]
Actually, I upgrade from Windows 7 Ultimate to Windows 10 Pro.   I didn't make a clean installation but rather an upgrade.  I wanted to keep my configurations and files.

**Comment by mbunkus** [comment]
That's what I meant, too. Thanks for the confirmation. I'll close this issue as invalid, then, as it's not a fault in MKVToolNix.
