### ISSUE TITLE
Translate!

### ISSUE THREAD

**Issue by unixfx** [mbunkus/mkvtoolnix#1389]
Greeting! 
I just came back, How are you sir?

Actually it's really sad that Arabic language is not within available languages in this tool, so I would like to translate this great tool into Arabic language, it's possible?

Thank you.

**Comment by mbunkus** [comment]
Thank you for the offer. Having more translations would be great.

Can you please contact me [via email](mailto:moritz@bunkus.org)? Then I'll send you some instructions along with the file containing all the untranslated entries. Thanks.
