### ISSUE TITLE
MkvToolNixGui: Setting "Warn before overwriting existing items" is disabled and its default state is unchecked

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1390]
In the preferences dialog of MkvToolNixGUI, the setting "Warn before overwriting existing items (files, jobs etc.)" is disabled and thus cannot be changed.

![warnoverwriting](https://cloud.githubusercontent.com/assets/6129198/9154010/0a685b76-3e7d-11e5-89a5-cc4098e2acc8.jpg)
Also note that the default state of the setting is unchecked, which means MkvToolNixGUI allows overwriting files without warning or confirmation. I think the default state of this setting should be checked.

MkvToolNixGui version: 8.2.0
OS: MS Windows 7 Pro x64

**Comment by mbunkus** [comment]
That's correct. This functionality hasn't been implemented yet.
