### ISSUE TITLE
adding 2 files create a file that might be weird.  need to add first file and then "append" the second file

### ISSUE THREAD

**Issue by jianlin** [mbunkus/mkvtoolnix#1391]
The description is in https://forum.handbrake.fr/viewtopic.php?f=11&t=32918&p=153396#p153385

I am not sure if this is a bug or a feature, but I don't understand what file this will create: basically, if we "add" 2 files, either 2 VOB files, or 2 mp4 files and merge them, the resultant file will only play the content of the first file in VLC player, and the file size is a combined file size.  We need to first "add" the first file, and then "append" (not add) the second file.  Is this a feature or a bug, and what does "adding 2 files" create?  Can file 2's content be viewable in such case?

**Comment by mbunkus** [comment]
All files that you »add« will be laid out in parallel in the file. This is a very useful feature that allows you to combine e.g. a video file together with one or more external subtitle file. The result is a file containing more than one subtitle track. Players will usually let the user chose which track to play.

This works for audio and video tracks, too.

»Appended« files on the other hand are laid out sequentially and do not result in any additional tracks being created for the appended files.

This is working exactly as intended.

**Comment by jianlin** [comment]
so if we have 3 video files, file01.mp4, file02.mp4, and file03.mp4, then after we append file2.mp4 to file1.mp4, now should we append file3.mp4 to file2.mp4, or append file3.mp4 to file1.mp4 (so that file1 is the head, and this program is longer and longer)?

It turned out that either way, the listed structures in MKVToolNix are the same, and the resultant files are the same.  Is one way different from another?  I suppose if we extend a rope, we can say, lay down rope 1, now place rope 2 to the right side of rope 1, and now, either place rope 3 to the right side of rope 2, or go to rope 1, find the new right side, and place rope 3 there, and the result is the same.

**Comment by mbunkus** [comment]
In the GUI there's no difference as both will simply insert the »appended« file as the last file for the »added« file.

The important thing is the order in which you add them. If you add 01, append 02 and then append 03 then that is different than adding 01, appending 03 and appending 02. Of course you can use drag & drop afterwards in order to fix the order.
