### ISSUE TITLE
MkvToolnixGUI [Feature Request] Add new merge settings for all files

### ISSUE THREAD

**Issue by Black-Light** [mbunkus/mkvtoolnix#1397]
This would make muxing multiple files at once much quicker by only having to drag the files in once rather then having to drag one in at a time and pressing "Create New Merge Settings And Add To Those" for each file.

**Comment by Black-Light** [comment]
Never mind I see that someone already opened this, since I posted it on the blog I didn't think this would be on here yet.
https://github.com/mbunkus/mkvtoolnix/issues/1380

**Comment by mbunkus** [comment]
Yeah, it's already been reported. Anyway, thanks for thinking about it.
