### ISSUE TITLE
Experimental Mac build of mkvtoolnix GUI does not properly change language

### ISSUE THREAD

**Issue by maki-chan** [mbunkus/mkvtoolnix#1402]
Whenever you try to choose a different interface language in the preferences windows in the Mac build of mkvtoolnix GUI (currently tested on 8.3.0), then it doesn't change at all. Restarting the GUI doesn't work either. It stays in English all the time (tested with German, French and Spanish).

**Comment by mbunkus** [comment]
Thanks for the report. I'll have to look into it, but Mac OS has a [very low priority](/mbunkus/mkvtoolnix/wiki/Mac-OS-X-support) for me. Therefore don't expect too timely a fix, please.

**Comment by maki-chan** [comment]
No problem to me at all, I am aware of the English language ;)
Just something I encountered. There are other little problems with the Mac GUI as well, maybe I should take a look into it myself for some of the things I saw. I have a Mac to test and develop with, maybe I get into the source code a bit more in a few weeks.

**Comment by mbunkus** [comment]
Any help with the Mac port would be highly appreciated, to be sure!

**Comment by mbunkus** [comment]
I've just build a DMG with the current development sources, and with that DMG changing the interface language works just fine. Therefore I consider this issue closed, although I'm not sure which change is actually responsible for it :)

Anyway, [here](https://www.bunkus.org/videotools/mkvtoolnix/macos/pre/) is a new pre-build DMG if you want to give it a try.

**Comment by maki-chan** [comment]
Could be fixed by this one? 1478d36b8427e07b2af6e1b96d953855c27b0b97
I don't know exactly. If you want I could go through the commit history since 88deb3626abd021859034d28f350b4ab2a546b64 which is release-8.3.0

**Comment by mbunkus** [comment]
That commit only affects the translation files for Qt's own strings (e.g. the file dialogs). The bulk of the programs including most of the GUI use gettext, and that commit doesn't touch that mechanism.

Thanks for the offer, but I don't think finding out which commit fixed is really necessary.

**Comment by maki-chan** [comment]
Just checked with current build https://www.bunkus.org/videotools/mkvtoolnix/macos/pre/MKVToolnix-8.4.0-build20151006-957-2800cb9.dmg

The error occurs again. I will try to compile the current sources tomorrow and maybe also debug it to see what happens when I try to change the language.

**Comment by mbunkus** [comment]
Thanks for the feedback. Well, if you figure out what the problem is and can provide a fix (or at least information how to fix it) then please let me know and I'll integrate it. All I can say is that it works for me, and that's as far as I'm willing to spend time on it. Like I said, I don't really support MacOS. Sorry.

**Comment by maki-chan** [comment]
Oh, don't worry about the support. I will try to support Mac OS and contribute to bug reports when I have time again for coding in one to two weeks. It's just that the semester begins next Monday and I have to check some organizational stuff, but then I will do my best to figure out this bug and maybe others if they occur.

**Comment by mbunkus** [comment]
That would be great! Thanks for the offer.
