### ISSUE TITLE
mkvinfo and MKVTOOLNIX_OPTIONS

### ISSUE THREAD

**Issue by 2011** [mbunkus/mkvtoolnix#1403]
Just made a big upgrade from 6.6.0 to 8.2.0 (don't know why gentoo is so far behind).

That fixed another (serious) issue I was having, and I also like the environment variables and the ability to disable track statistics tags (thanks).

So I did:

export MKVTOOLNIX_OPTIONS=--disable-track-statistics-tags

That (of course) works fine for mkvmerge, but unfortunately, it messes up mkvinfo.

Now, if I do:

mkvinfo file.mkv

I get:

Error: Only one input file is allowed.

If I unset MKVTOOLNIX_OPTIONS, then it works again as it should.

Thanks, again.

**Comment by mbunkus** [comment]
`MKVTOOLNIX_OPTIONS` is evaluated for all tools. This will obviously only work with options common to all tools. Use `MKVMERGE_OPTIONS` instead.

**Comment by 2011** [comment]
@mbunkus 

MKVMERGE_OPTIONS is not listed in the man page, and in fact doesn't work.

If I do:

MKVMERGE_OPTIONS=--disable-track-statistics-tags mkvmerge -o output.mkv input.mkv

I still get the track statistic tags.

**Comment by mbunkus** [comment]
Meh, you're right. Only `…_DEBUG` is available separately for each application (even though it isn't documented). Anyway, the idea is to have `MKVTOOLNIX_*` apply to all tools and `TOOLNAME_*` apply to one tool only.

I'll fix that. For the time being you cannot set that environment variable. What you can do is create a shell script called mkvmerge and place it somewhere in your `$PATH` prior to /usr/bin.

**Comment by mbunkus** [comment]
I was slightly wrong. Both `*_DEBUG` and `*_ENGAGE` were already working with the tool's name as the prefix. For `*_OPTIONS` I've implemented this with the first of the two commits linked above. The second one brings the documentation up to date regarding those environment variables in the four affected tools.

**Comment by mbunkus** [comment]
…and thanks for pointing it out, BTW; I was pretty sure this had already been implemented long ago.
