### ISSUE TITLE
mkvmerge GUI, opening files via command line doesn't respect mkvtoolnix.ini anymore

### ISSUE THREAD

**Issue by ggms** [mbunkus/mkvtoolnix#1404]
I know mmg.exe is deprecated, but you introduced bug in last two releases, 8.2.0 and 8.3.0
How to duplicate bug:
- delete every mkvmergeGUI trace from registry, just to be sure
- run mmg.exe with mkvtoolnix.ini created in same path as mmg.exe = everything is working
- run mmg.exe and load mkv with command line where that mkv is in the same path as mmg.exe = everything is ok, mkvtoolnix.ini is used, for example: C:\Test\mmg.exe C:\Test\video.mkv
- BUG: run mmg.exe and load mkv with command line *but where mkv is not in the same path as mmg.exe* = mkvmergeGUI will create registry entries and completely ignore it's mkvtoolnix.ini
fore example, this command will ignore mkvtoolnix.ini
C:\Test\mmg.exe C:\SomeOtherDir\video.mkv

Seems to me that if command line is used to load mkv file ->  mkvtoolnix.ini is searched in path of loaded mkv instead path where mmg.exe resides.

Regards

**Comment by mbunkus** [comment]
mmg.exe is not supported anymore and has already been removed. Bugs won't be fixed anymore. Sorry.

**Comment by mbunkus** [comment]
I've also verified that the new MKVToolNix GUI does not suffer from what you've described.
