### ISSUE TITLE
Start application after muxing

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1406]
I think it would be nice if MKVToolnixGUI could start another application after mkvmerge has muxed a file or is done with the queue.

I'm thinking about starting mkvalidator or a player.

(If that's too much work for too less 'good' close this issue.)

**Comment by mbunkus** [comment]
Thanks for the suggestion. This is something that I had planned to implement in the new GUI way back when I thought about creating a new GUI. I don't know how exactly, but it will probably be something like this:

- Running program if a) job completes successfully b) if job completes successfully or with warnings c) whenever a job is finished no matter its status
- Select a program to run
- Edit the arguments given to the program including the output file name, the job's exit status and potentially more properties
