### ISSUE TITLE
bug: mkvmerge gui v8.3.0 crashed with run time C++ error when ading attachment 

### ISSUE THREAD

**Issue by zenoaghaz** [mbunkus/mkvtoolnix#1412]
in  latest release (or any above version 8.0.0) on Windows8 or windows10 (x86 or x64)
mkvmerge GUI v8.3.0 (32bit portable) crashed with run time C++ error when adding any attachment when drag and drop or select in other way.
in blow v8.0.0 that's work nicely.
thanks for attention.

**Comment by mbunkus** [comment]
Please verify that the folder you run mkvmerge-gui.exe from also contains a sub-folder »data« with the file »magic.mgc« inside it. That »magic.mgc« must be 3.865.992 bytes big.

**Comment by zenoaghaz** [comment]
thanks for reply
re-downloading "magic.mgc" of v8 and placing in "Data" folder solved problem.
exactly what is "magic.mgc" and why in older version dos not required.

**Comment by mbunkus** [comment]
magic.mgc is used for MIME type detection. That's done by the `libfile` library; if it fails if the file isn't present then that's a problem in libfile.

I don't support installations with mixed content or taking apart the packages I provide. I only support the two packaged variants that I do provide.
