### ISSUE TITLE
Renumber chapters with hidden chapters

### ISSUE THREAD

**Issue by Maal656** [mbunkus/mkvtoolnix#1414]
In #1355 the renumbering of chapters was added in the Chapter Editor.

Currently, when there are hidden chapters, these are also renumbered:

    XX1 --> Chapter 1
    XX2 [Hidden] --> Chapter 2
    XX3 --> Chapter 3

It would be great if we had the possiblity of not assigning a chapter number to hidden chapters, leaving their name empty:

    XX1 --> Chapter 1
    XX2 [Hidden] --> (No name)
    XX3 --> Chapter 2

Thank you and regards!

**Comment by mbunkus** [comment]
Thanks for the suggestion. This sounds useful. I'll implemented.
