### ISSUE TITLE
Default encoding for subtitle seems to overwrite encoding of a subtitle from mkv file

### ISSUE THREAD

**Issue by marco44** [mbunkus/mkvtoolnix#1416]
Hi,

I've set a default encoding for subtitles. It works great for srt files. But when my subtitle comes from another mkv (like when I'm merging a re-encoded mkv with the original, to get its subtitles), those seem to be using the default encoding (instead of the encoding coming from the mkv file, which would seem more logical to me).

**Comment by mbunkus** [comment]
Thanks. Yeah, that's a minor bug. It doesn't have any affect, though, as mkvmerge disregards that argument for subtitles coming from Matroska files. So it doesn't do any harm.

I'll fix it nevertheless.

**Comment by marco44** [comment]
Ah, ok. I had a corrupted subtitle (accents in the wrong encoding), and thought it might come from this.
