### ISSUE TITLE
Warning message about audio track (omitted data)

### ISSUE THREAD

**Issue by Maal656** [mbunkus/mkvtoolnix#1420]
Sometimes during proccess appears a warning messages as follows: "xxxx track 0: This AC3 track contains xxx bytes of information which are not AC3 data, so they will be ommited. Audio/video synchronization may be lost"

Most times this message is caused due to a corruption in the movie, which is shown also in the video. In order to check the movie it would be great if the previous message could contain information about the time where the failure has been detected. I mean, something similar to "In time 56:15 this AC3 track contains xxx bytes of information which are not AC3 data"

I don't know if it is possible. In any case, thank you for this great program.

**Comment by mbunkus** [comment]
Thanks for the proposal. It's not that trivial to do as the code in question doesn't have access to last written timecode (yet), but I'll look into it.
