### ISSUE TITLE
After start muxing in MkvToolnix. Why i see this 

### ISSUE THREAD

**Issue by Royal-star** [mbunkus/mkvtoolnix#1422]

**Comment by Royal-star** [comment]
After start muxing in MkvToolnix. Why i see this..
--- Warnings emitted by job 'merging to file »TW-1 (1).mkv« in directory »C:/1«' started on 2015-09-08 15:33:05 ---
--- Errors emitted by job 'merging to file »TW-1 (1).mkv« in directory »C:/1«' started on 2015-09-08 15:33:05 ---
I tryed out with different Mkv Files. Its always there.
![mkvtoolnix](https://cloud.githubusercontent.com/assets/10728504/9735622/b7b7e01a-5644-11e5-9fe0-a5338edeff62.png)

**Comment by mbunkus** [comment]
Those are separators, nothing more. The job output tool will contain the output of all the jobs you've run in your session. If one of them outputs a warning then the user must be able to identify during which job that warning occurred. Hence the separators.

**Comment by Royal-star** [comment]
Mbunkus I thank you for your prompt answer and the explanation of my
Request.
Also I feel it is necessary to thank you for your selfless,  hard working for us, so we can have an such precious Application and for free.
Beyond the fact that you are an Men who wants to give, it appears that you are an prominent
Scientist.
So in this spirit I wish you Courage and god bless you and your family.
