### ISSUE TITLE
Open input files with MediaInfo from within MKVToolNix GUI

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1423]
Due to the following quote I thought that the information provided by MediaInfo might still be useful for the user that is about to set-up the merge process.
> MKVToolNix is not MediaInfo and never will be.
(see #1295)

So instead of being like MediaInfo it would be nice if MKVToolNix GUI would allow to open input files from within the GUI in MediaInfo. That way, users can check their files, if they require more information than #1295 will give them.

Adding a link to the Input-lists' right click menu for files which already have been added that reads 'Open with MediaInfo'? (or similar) would do the trick. This should be more convenient than opening MediaInfo first, then the file(s).

The simplest way for this to work would be to add a MKVToolNix GUI setting where users can specify the path to the MediaInfo binary. By having it that way it is possible to use a portable version of MediaInfo.

MKVToolNix GUI could also try to detect the MediaInfo binary in its default installation path.

**Comment by mbunkus** [comment]
Thanks for the suggestion. I will likely implement this in the mid-term.

**Comment by remuxer32** [comment]
It's definitely a good idea. I fully support bastik-tor's concept. Such a feature will help me, too.
