### ISSUE TITLE
I have play back issues after muxing a “ interlaced pal 25 fps avc MKV “ 

### ISSUE THREAD

**Issue by Royal-star** [mbunkus/mkvtoolnix#1424]
I have play back issues after muxing a “ interlaced pal 25 fps avc MKV “ with playback speed jumping and sometime stuck. Is there a possibility to manage this in MkvToolnix, or must I deinterlace the File firs?
Here the media info of the input file:
===================== General =====================
Count                       : 284
Stream count                : 1
Kind of stream              : General
Kind of stream              : General
Kind of stream Id           : 0
UniqueID                    : 172483220926193666100655699770848499872
UniqueID/String             : 172483220926193666100655699770848499872 (0x81C30F5CB970140386C169CCD10AD8A0)
Video count                 : 1
Audio count                 : 2
Video formats               : AVC
Video_Format_WithHint_List  : AVC
Video codecs                : AVC
Video_Language_List         : English
Audio formats               : AC-3 / DTS
Audio_Format_WithHint_List  : AC-3 / DTS
Audio codecs                : AC3 / DTS
Languages                   : English / English
Complete name               : C:\TAKI-SUPPORT\Firefox-Downloads\Through the Wormhole Season 3\TW-1.mkv
Folder name                 : C:\TAKI-SUPPORT\Firefox-Downloads\Through the Wormhole Season 3
File name                   : TW-1
File extension              : mkv
Format                      : Matroska
Format                      : Matroska
Format URL                  : http://packs.matroska.org/
Format extensions           : mkv mk3d mka mks
Format comercial name       : Matroska
Format version              : Version 4 / Version 2
Codec                       : Matroska
Codec                       : Matroska
Codec URL                   : http://packs.matroska.org/
Codec extensions            : mkv mk3d mka mks
File size                   : 4090396816
File size                   : 3.81 GB
File size                   : 4 GB
File size                   : 3.8 GB
File size                   : 3.81 GB
File size                   : 3.809 GB
Duration (ms)               : 2615040
Duration (ms)               : 43mn 35s
Duration (precise)          : 43mn 35s 40ms
Duration                    : 43mn 35s
Duration                    : 00:43:35.040
OverallBitRate_Mode         : VBR
OverallBitRate_Mode/String  : Variable
Total bitrate               : 12513451
Total bitrate               : 12.5 Mbps
Stream size (bytes)         : 81398851
Stream size                 : 77.6 MB (2%)
Stream size                 : 78 MB
Stream size                 : 78 MB
Stream size                 : 77.6 MB
Stream size                 : 77.63 MB
Stream size                 : 77.6 MB (2%)
Stream proportion           : 0.01990
Encoded date                : UTC 2014-06-13 10:48:54
Created date (UTC)          : UTC 2015-06-24 22:20:35.898
Created date                : 2015-06-25 01:20:35.898
Modified date (UTC)         : UTC 2015-06-25 14:25:01.943
Modified date               : 2015-06-25 17:25:01.943
Encoded application         : mkvmerge v6.2.0 ('Promised Land') built on Apr 28 2013 12:22:01
Encoded library             : libebml v1.3.0 + libmatroska v1.4.0
Encoded library             : libebml v1.3.0 + libmatroska v1.4.0

===================== Video =====================
Count                       : 272
Stream count                : 1
Kind of stream              : Video
Kind of stream              : Video
Kind of stream Id           : 0
StreamOrder                 : 0
Id                          : 1
Id                          : 1
UniqueID                    : 1992486277
Format                      : AVC
Format info                 : Advanced Video Codec
Format URL                  : http://developers.videolan.org/x264.html
Format comercial name       : AVC
Format profile              : High@L4.1
Format settings             : CABAC / 4 Ref Frames
Use of CABAC                : Yes
Use of CABAC                : Yes
RefFrames                   : 4
RefFrames                   : 4 frames
Internet media type         : video/H264
Codec Id                    : V_MPEG4/ISO/AVC
Codec URL                   : http://ffdshow-tryout.sourceforge.net/
Codec                       : V_MPEG4/ISO/AVC
Codec                       : AVC
Codec family                : AVC
Codec info                  : Advanced Video Codec
Codec URL                   : http://ffdshow-tryout.sourceforge.net/
Codec profile               : High@L4.1
Codec settings              : CABAC / 4 Ref Frames
Use of CABAC                : Yes
RefFrames                   : 4
Duration (ms)               : 2615040
Duration (ms)               : 43mn 35s
Duration (precise)          : 43mn 35s 40ms
Duration                    : 43mn 35s
Duration                    : 00:43:35.040
Bitrate mode                : VBR
Bitrate mode                : Variable
Bitrate                     : 11753433
Bitrate                     : 11.8 Mbps
Bitrate maximum             : 24999936
Bitrate maximum             : 25.0 Mbps
Width                       : 1920
Width                       : 1 920 pixels
Height                      : 1080
Height                      : 1 080 pixels
Pixel aspect ratio          : 1.000
Aspect ratio                : 1.778
Aspect ratio                : 16:9
Framerate mode              : CFR
Framerate mode              : Constant
Framerate                   : 25.000
Framerate                   : 25.000 fps
Frame count                 : 65376
Standard                    : PAL
Resolution                  : 8
Resolution                  : 8 bits
Colorimetry                 : 4:2:0
Colorimetry                 : YUV
Colos space                 : 4:2:0
Bit depth                   : 8
Bit depth                   : 8 bits
Scan type                   : Interlaced
Scan type                   : Interlaced
ScanOrder                   : TFF
ScanOrder/String            : Top Field First
Interlacement               : TFF
Interlacement               : Top Field First
Bits/(Pixel*Frame)          : 0.227
Delay                       : 0
Delay                       : 00:00:00.000
Delay_Source                : Container
Delay_Source/String         : Container
Stream size (bytes)         : 3841962285
Stream size                 : 3.58 GB (94%)
Stream size                 : 4 GB
Stream size                 : 3.6 GB
Stream size                 : 3.58 GB
Stream size                 : 3.578 GB
Stream size                 : 3.58 GB (94%)
Stream proportion           : 0.93926
Language                    : en
Language                    : English
Language                    : English
Language                    : en
Language                    : eng
Language                    : en
Default                     : Yes
Default/String              : Yes
Forced                      : No
Forced/String               : No
BufferSize                  : 25000000 / 25000000
colour_description_present  : Yes
colour_primaries            : BT.709
transfer_characteristics    : BT.709
matrix_coefficients         : BT.709

===================== Audio #1 =====================
Count                       : 245
Stream count                : 2
Kind of stream              : Audio
Kind of stream              : Audio
Kind of stream Id           : 0
StreamKindPos               : 1
StreamOrder                 : 1
Id                          : 2
Id                          : 2
UniqueID                    : 1906107193
Format                      : AC-3
Format info                 : Audio Coding 3
Format comercial name       : AC-3
Format profile              : Dolby Digital
Format settings mode extens : CM (complete main)
Format_Settings_Endianness  : Big
Codec Id                    : A_AC3
Codec                       : AC3
Codec                       : AC3
Codec family                : AC3
Codec info                  : Dolby AC3
Codec profile               : Dolby Digital
Duration (ms)               : 2615040
Duration (ms)               : 43mn 35s
Duration (precise)          : 43mn 35s 40ms
Duration                    : 43mn 35s
Duration                    : 00:43:35.040
Bitrate mode                : CBR
Bitrate mode                : Constant
Bitrate                     : 256000
Bitrate                     : 256 Kbps
Channel(s)                  : 2
Channel(s)                  : 2 channels
ChannelPositions            : Front: L R
ChannelPositions/String2    : 2/0/0
ChannelLayout               : L R
Sampling rate               : 48000
Sampling rate               : 48.0 KHz
Sampling count              : 125521920
Resolution                  : 16
Resolution                  : 16 bits
Bit depth                   : 16
Bit depth                   : 16 bits
Compression_Mode            : Lossy
Compression_Mode/String     : Lossy
Delay                       : 0
Delay                       : 00:00:00.000
Delay_Source                : Container
Delay_Source/String         : Container
Delay                       : 0
Delay                       : 0
Stream size (bytes)         : 83681280
Stream size                 : 79.8 MB (2%)
Stream size                 : 80 MB
Stream size                 : 80 MB
Stream size                 : 79.8 MB
Stream size                 : 79.80 MB
Stream size                 : 79.8 MB (2%)
Stream proportion           : 0.02046
Language                    : en
Language                    : English
Language                    : English
Language                    : en
Language                    : eng
Language                    : en
Default                     : Yes
Default/String              : Yes
Forced                      : No
Forced/String               : No
bsid                        : 6
dialnorm                    : -31
dialnorm/String             : -31 dB
compr                       : -0.28
compr/String                : -0.28 dB
dsurmod                     : 2
dsurmod/String              : Dolby Surround encoded
acmod                       : 2
lfeon                       : 0
dialnorm_Average            : -31
dialnorm_Average/String     : -31 dB
dialnorm_Minimum            : -31
dialnorm_Minimum/String     : -31 dB
dialnorm_Maximum            : -31
dialnorm_Maximum/String     : -31 dB
dialnorm_Count              : 2
compr_Average               : -0.28
compr_Average/String        : -0.28 dB
compr_Minimum               : -0.28
compr_Minimum/String        : -0.28 dB
compr_Maximum               : -0.28
compr_Maximum/String        : -0.28 dB
compr_Count                 : 2

===================== Audio #2 =====================
Count                       : 222
Stream count                : 2
Kind of stream              : Audio
Kind of stream              : Audio
Kind of stream Id           : 1
StreamKindPos               : 2
StreamOrder                 : 2
Id                          : 3
Id                          : 3
UniqueID                    : 3082907522
Format                      : DTS
Format info                 : Digital Theater Systems
Format comercial name       : DTS
Format settings mode        : 16
Format_Settings_Endianness  : Big
Codec Id                    : A_DTS
Codec                       : DTS
Codec                       : DTS
Codec family                : DTS
Duration (ms)               : 2615040
Duration (ms)               : 43mn 35s
Duration (precise)          : 43mn 35s 40ms
Duration                    : 43mn 35s
Duration                    : 00:43:35.040
Bitrate mode                : CBR
Bitrate mode                : Constant
Bitrate                     : 255000
Bitrate                     : 255 Kbps
Channel(s)                  : 2
Channel(s)                  : 2 channels
ChannelPositions            : Front: L R
ChannelPositions/String2    : 2/0/0
ChannelLayout               : L R
Sampling rate               : 48000
Sampling rate               : 48.0 KHz
Sampling count              : 125521920
Resolution                  : 24
Resolution                  : 24 bits
Bit depth                   : 24
Bit depth                   : 24 bits
Compression_Mode            : Lossy
Compression_Mode/String     : Lossy
Delay                       : 0
Delay                       : 00:00:00.000
Delay_Source                : Container
Delay_Source/String         : Container
Delay                       : 0
Delay                       : 0
Stream size (bytes)         : 83354400
Stream size                 : 79.5 MB (2%)
Stream size                 : 79 MB
Stream size                 : 79 MB
Stream size                 : 79.5 MB
Stream size                 : 79.49 MB
Stream size                 : 79.5 MB (2%)
Stream proportion           : 0.02038
Language                    : en
Language                    : English
Language                    : English
Language                    : en
Language                    : eng
Language                    : en
Default                     : No
Default/String              : No
Forced                      : No
Forced/String               : No

**Comment by mbunkus** [comment]
What are the muxing settings you're using? Please show the corresponding command line (you can get the command line from the »Merge« menu, entry »Show command line«).

Have you tried other players? VLC, MPC-HC…

**Comment by Royal-star** [comment]
^"C:/Program Files ^(x86^)\MKVToolNix\mkvmerge.exe^" ^"--output^" ^"H:/TW-1 ^(1^).mkv^" ^"--language^" ^"0:eng^" ^"--default-track^" ^"0:yes^" ^"--language^" ^"1:eng^" ^"--default-track^" ^"1:yes^" ^"--language^" ^"2:eng^" ( ^"C:/TAKI-SUPPORT/Firefox-Downloads/Through the Wormhole Season 3/TW-1.mkv^" ) ^"--disable-track-statistics-tags^" ^"--track-order^" ^"0:0,0:1,0:2^"
All of them plus Potplayer. Same problem on the same positions. Original plays over all without any problem.

**Comment by mbunkus** [comment]
Hmm, unfortunately that doesn't tell me much yet. If you want me to take a look at the issue then I'll need the source file you're trying to remux. Please upload it to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

BTW: don't use the »close and comment« button if you don't want to close the issue ;)

**Comment by Royal-star** [comment]
Ok Thank you, I’m new here, so sorry for the button.
I have never upload, so I will try to figure it out.

**Comment by Royal-star** [comment]
Hi Mr. Mbunkus, good morning and greetings from Hellas.
Sorry for my bad English, but I will try with the help of god and googleTranslate
to give you the right picture of this case.
I have upload the source file like you requested and so much footage I can
to make it so easy it is possible for you.
TW1 is the Source file.
The corresponding command line here:
^"C:/Program Files ^(x86^)\MKVToolNix\mkvmerge.exe^" ^"--output^" ^"H:/TW-1 ^(2^).mkv^" ^"--audio-tracks^" ^"2^" ^"--language^" ^"0:eng^" ^"--default-track^" ^"0:yes^" ^"--language^" ^"2:eng^" ( ^"C:/TAKI-SUPPORT/Firefox-Downloads/Through the Wormhole Season 3/TW-1.mkv^" ) ^"--disable-track-statistics-tags^" ^"--track-order^" ^"0:0,0:2^"
And a screenshot  Attachment of the Error how it appears when it stucks in MPC-HC.
![tw-1 errorscreenshut](https://cloud.githubusercontent.com/assets/10728504/9783307/0c1330e8-57ac-11e5-963e-4ae22f7ef95b.png)
In Potplayer it jumps around and in WMP it stocks and shows nothing. All this in the first 2 Minutes.
After that I tried to remux with MkvToolnix the broken MKV .
The result. Here appears sync errors.
Here is a screenshot of the MkvToolnix Output-Window with the Errors and the log-Text from the remuxing of the broken MKV.
![tw-1 2 1 errorwindow](https://cloud.githubusercontent.com/assets/10728504/9783339/436675b4-57ac-11e5-8e11-25fc98c73b59.png)
--- Output of job 'merging to file »TW-1 (2).mkv« in directory »H:/«' started on 2015-09-10 00:27:47 ---
mkvmerge v8.3.0 ('Over the Horizon') 32bit
'C:/TAKI-SUPPORT/Firefox-Downloads/Through the Wormhole Season 3/TW-1.mkv': Using the demultiplexer for the format 'Matroska'.
'C:/TAKI-SUPPORT/Firefox-Downloads/Through the Wormhole Season 3/TW-1.mkv' track 0: Using the output module for the format 'AVC/h.264'.
'C:/TAKI-SUPPORT/Firefox-Downloads/Through the Wormhole Season 3/TW-1.mkv' track 2: Using the output module for the format 'DTS'.
The file 'H:/TW-1 (2).mkv' has been opened for writing.
The cue entries (the index) are being written...
Muxing took 2 minutes 32 seconds.
--- Output of job 'merging to file »TW-1 (2) (1).mkv« in directory »H:/«' started on 2015-09-10 06:43:52 ---
mkvmerge v8.3.0 ('Over the Horizon') 32bit
'H:/TW-1 (2).mkv': Using the demultiplexer for the format 'Matroska'.
'H:/TW-1 (2).mkv' track 0: Using the output module for the format 'AVC/h.264'.
'H:/TW-1 (2).mkv' track 1: Using the output module for the format 'DTS'.
The file 'H:/TW-1 (2) (1).mkv' has been opened for writing.
H:/TW-1 (2).mkv: Error in the Matroska file structure at position 84126756. Resyncing to the next level 1 element.
The last timecode processed before the error was encountered was 00:00:57.180000000.
Resyncing successful at position 84958103.
The first cluster timecode after the resync is 00:00:58.640000000.
H:/TW-1 (2).mkv: Error in the Matroska file structure at position 105384568. Resyncing to the next level 1 element.
The last timecode processed before the error was encountered was 00:01:07.980000000.
Resyncing successful at position 121853395.
The first cluster timecode after the resync is 00:01:30.400000000.
The cue entries (the index) are being written...
Muxing took 4 minutes 30 seconds.
Then I tried to create a 10 minutes split Part of the output  using the Source-file, for sending to you, so I do not need toy upload another 10 hours for the output file.
And hallo, there was no stocking or jumping any more.
I don’t now if it matters, but I experience also that wen I remux the Source-file to an TS-file first
using TS-Muxer and then take this TS-file as source to remux it with MkvToolnix to an MKV-file.
The resulting MKV-file runs without any problem.
I try it out several times but no problems any more.
For now this is all I have. I thank you for spending your precious time for my problem.
So I am available for any further information.
Have a nice day. Dimitrios

**Comment by mbunkus** [comment]
Thanks for the upload. I will look into it, but it will take a couple of days as I'm busy with other things at the moment.

**Comment by Royal-star** [comment]
Of course . I thank you very much mr. bunkus.

**Comment by Royal-star** [comment]
Hi Mr. Bunkus,
I have researched this case to find a sense in all this and maybe to help solve
It. I’m not an expert in programing but I worked for many years in past decades as computer operator, on diverse major frame systems and so I have become with the years the sense for this kind of things. Please don’t misunderstand me, I will not purport an all knower.
But I try to help you to make this world better.
So in this spirit I have make some tests to find out where the problem appearance.
I take the source file, this one I upload to your server, and run it with an appl. named
MakeMkv to remux it again to an MKV file..
During the remux- process there appears the following Message:
AV synchronization issues were found in file 'C:/Bunkustest/TW1sourcetooutput1_t00.mkv' (title #1)
AV sync issue in stream 1 at 0:00:03.029 with duration of 10.666ms : broken timecode, apparent audio  
skew is -21.333ms
AV sync issue in stream 1 at 0:00:03.114 with duration of 10.666ms : broken timecode, apparent audio  
skew is -21.666ms
AV sync issue in stream 1 at 0:00:03.200 with duration of 10.666ms : broken timecode, apparent audio  
skew is -21ms
AV sync issue in stream 1 at 0:00:04.032 with duration of 10.666ms : broken timecode, apparent audio  
skew is -21.333ms
AV sync issue in stream 1 at 0:00:04.117 with duration of 10.666ms : broken timecode, apparent audio  
skew is -21.666ms
and so on……..
The resulting MKV output file seems to be fixed on the fly from the App. during the remux-process.
The resulting MKV file runs without any issues. I have rerun it many times with the same
results.
To verificate this I   change on this mkv-file only the audio, replacing them with the source Audio,
using Mkvtoolnix to remux. And ouala there was the issue again, like before (jumping and stocking after some seconds).
To make a second verification I try then to remux this broken Mkv file again with MakeMkv
And it appears the following Message:
The source file 'H:/1/TW-1 ac3a.mkv' is corrupt or invalid at offset 4048635904, attempting to work around
AV synchronization issues were found in file 'C:/3/TW-1Test_t00-AC3_t00.mkv' (title #1)
AV sync issue in stream 0 at 0:02:08.600 : video frame timecode differs by +80ms
AV sync issue in stream 0 at 0:02:08.620 : video stream has 1 frames with invalid timecodes
1 titles saved.
And now some very weird. Some time there appears footage from other Media files stored on the same HDD by playing simultaneously the source audio, then after some seconds appears  the source video again playing fast until thy reached the audio and then playing normal until the next gap.
So my conclusion, if it helps, is that the central problem is an AV sync issue in the source MKV-file that MkvToolnix not recognizes and simply to an broken MKV file remuxes using apparently foreign files to fill the resulting gap’s in the video stream.
This hears maybe crazy, but this is the picture for now.
I now that you spend your free time with this Application removing it from your family, but I think it is worth to check this issue for an application from this level and popularity. 
Left to say , it would be nice when MkvToolnix could rekognise AV issues (like in the tiny App MakeMkv) and report it in the Error-Window and maybe during the remux-Process able to fix it.
Or maybe for the future a ability to check a mkv file of structure issues like a parser or an
Gopfixer or something like that.
Regards Dimitrios Samaras

**Comment by mbunkus** [comment]
Well, if your file is badly damaged then there's not a lot mkvmerge can do about it. It tries to recover as much as possible. However, mkvmerge is not a dedicated tool for error recovery, therefore it uses rather naive approaches. This is nothing I'm going to change, though. Sorry.

**Comment by Royal-star** [comment]
I thank you for your answer Mr Bunkus. With this i have much learn about Container and how they
works with time-stamps and so on. Continue your good and hard working for us. 
For this i will thank you to.
Regards Dimitrios Samaras
