### ISSUE TITLE
"Shift start and end timecodes by the following amount" doesn't work with negative amounts

### ISSUE THREAD

**Issue by TheJacuzzi** [mbunkus/mkvtoolnix#1425]
What the title says. I tried with both formats, HH:mm:ss.nnn and a number followed by a suffix. Neither works with negative values.

I'm using this build on Windows 10 x64: mkvtoolnix-32bit-8.3.0-build20150905-902-6585032

**Comment by mbunkus** [comment]
Thanks for the report. Interestingly the function works just fine on Linux while it always sets the timecodes to 0 on Windows.

**Comment by TheJacuzzi** [comment]
I tried with this other build (mkvtoolnix-64bit-8.3.0-build20150829-895-883b10a) and it seems to work fine.

**Comment by mbunkus** [comment]
So it's probably an issue of 32bit vs. 64bit, not of Linux vs Windows (my Linux is 64bit). I'll investigate.
