### ISSUE TITLE
PCM with different number of samples in packets re-muxed wrong

### ISSUE THREAD

**Issue by aviolo** [mbunkus/mkvtoolnix#1426]
Hello,

I have a audio file not encoded encapsuled in mkv.
The audio file is clean, but after a trimming the audio file is noisy.
Here are the command line : mkvmerge -o "audio_trimming.mkv" "audio_original.mkv" --split parts:00:00:21-00:01:44.
Mkvtoolnix version is v8.2.0, my system is ubuntu 10.04 32 bits.
You can find in your ftp server source audio file and result file in /09_11_15
I hope you have all information

**Comment by mbunkus** [comment]
Thanks for the report & the upload. I will look into it, but it will take a couple of days as I'm rather swamped at the moment.

**Comment by mbunkus** [comment]
Your source file uses a very, very strange way to package PCM audio data. Normally for PCM there's a fixed number of bytes in each Matroska block. In your file that number varies wildly. mkvmerge currently assumes that it's a fixed number and doesn't deal well with such fluctuation.

I will fix it in time, but it doesn't have such a high priority for me as it's just PCM and PCM isn't used widely. In addition such strange way of packaging isn't common either.

As a workaround you should be able to extract the PCM to a WAV first with mkvmextract. Then you can re-mux that WAV to Matroska if you want and apply splitting in this second step.

**Comment by aviolo** [comment]
Thank you for your answer, I will look for the cause of this problem on source file.
