### ISSUE TITLE
move lines with chapters and attachments by mouse

### ISSUE THREAD

**Issue by fuel1986** [mbunkus/mkvtoolnix#1429]
Hello.
Why in merge in the field "Tracks, chapters, tags and attachments" i can't move lines with chapters and attachments by mouse? I think it would be nice if to do this.
Sorry for my english.

**Comment by mbunkus** [comment]
mkvmerge itself doesn't support the re-ordering of chapters and attachments. Therefore the GUI doesn't allow the user to move those lines in order not to give the impression that that would have any effect.

I have no plans for changing this. Sorry.
