### ISSUE TITLE
Subtitles wasn't apply on video by MKVmerge

### ISSUE THREAD

**Issue by samerlol** [mbunkus/mkvtoolnix#1430]
Hello,

I downloaded the latest version of mkvmerge and i tried to add subtitles to a movie, but the result is the movie converted from MP4 to MKV and no subtitles added...

I followed all the steps and this is not my first time in merge subtitles via MKVmerge.. i merged more than 50 films and almost of these films i merged were merged successfully..

but now i tried all ways but same results, no subtitles merged to video..

My windows: windows 7 ultimate sp1
32 bit
is this my first time got this message? no

**Comment by mbunkus** [comment]
Those MP4 file probably contain timed text subtitles (TTXT). That format is not supported, and I don't have any plans for implementing support for it. You can check the format with tools like MediaInfo.

**Comment by samerlol** [comment]
Thanks you for replaying... 

MP4 has no problem in adding sutitles, right ?

and the problem is not caused with mp4 only, it's also from avi, MPEG-4 and MKV it's selfs..

I mean when i get MKV(has no subtitles) and add subtitles using mkvmerge it's will create mkv file with subtitles, right? but it's not... some causes i don't see subtitles on my mkv files

**Comment by mbunkus** [comment]
I need detailed info on what you're doing. Please do the following:

- start the GUI,
- add the source files the way you want them, especially the subtitle file(s)
- take a screenshot of the GUI in that state and
- post the screenshot here.

**Comment by samerlol** [comment]
Ok... here an example for the what i do..
I have latest version 8.3


http://imgur.com/uuRWzL2
http://imgur.com/uuRWzL2

I don't know what to say.. but i think now it's working O.o
I will try another file and see..(Please let this issue open till i do another merge and see if it's done)

With all due respect

**Comment by mbunkus** [comment]
OK, and how do you determine whether or not the resulting output file contains the subtitles? Please use the GUI or mkvinfo's GUI for that and don't rely on the result of your media player.

**Comment by samerlol** [comment]
I don't know how to do what you told me. but i have this mediainfo maybe you can see.

The output file info:
"General
Unique ID                   : 228567879825214842756634003349150107995 (0xABF49289557807A082A14DAC6810095B)
Complete name               : E:\Videos\Teenage Mutant Ninja Turtles (2014) [1080p]\Teenage.Mutant.Ninja.Turtles.2014.1080p.BluRay.x264.YIFY.mkv
Format                      : Matroska
Format version              : Version 4 / Version 2
File size                   : 1.63 GiB
Duration                    : 1h 41mn
Overall bit rate            : 2 310 Kbps
Encoded date                : UTC 2015-09-16 12:28:50
Writing application         : mkvmerge v8.3.0 ('Over the Horizon') 32bit
Writing library             : libebml v1.3.1 + libmatroska v1.4.2
DURATION                    : 01:40:55.110000000
NUMBER_OF_FRAMES            : 1283
NUMBER_OF_BYTES             : 59375
_STATISTICS_WRITING_APP     : mkvmerge v8.3.0 ('Over the Horizon') 32bit
_STATISTICS_WRITING_DATE_UT : 2015-09-16 12:28:50
_STATISTICS_TAGS            : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.1
Format settings, CABAC      : Yes
Format settings, ReFrames   : 4 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 1h 41mn
Nominal bit rate            : 2 215 Kbps
Width                       : 1 920 pixels
Height                      : 800 pixels
Display aspect ratio        : 2.40:1
Frame rate mode             : Constant
Frame rate                  : 23.976 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.060
Writing library             : x264 core 142 r2479 dd79a61
Encoding settings           : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-3 / threads=48 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=2215 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=31250 / vbv_bufsize=31250 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default                     : Yes
Forced                      : No
Color range                 : Limited
Color primaries             : BT.709
Matrix coefficients         : BT.709

Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : A_AAC
Duration                    : 1h 41mn
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 48.0 KHz
Compression mode            : Lossy
Language                    : English
Default                     : Yes
Forced                      : No

Text
ID                          : 3
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Language                    : Arabic
Default                     : Yes
Forced                      : No
"


about input file info:
"General
Complete name               : E:\Videos\Teenage Mutant Ninja Turtles (2014) [1080p]\Teenage.Mutant.Ninja.Turtles.2014.1080p.BluRay.x264.YIFY.mp4
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom
File size                   : 1.64 GiB
Duration                    : 1h 41mn
Overall bit rate mode       : Variable
Overall bit rate            : 2 312 Kbps
Encoded date                : UTC 2014-11-25 18:33:11
Tagged date                 : UTC 2014-11-25 18:33:11

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.1
Format settings, CABAC      : Yes
Format settings, ReFrames   : 4 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 1h 41mn
Bit rate                    : 2 215 Kbps
Maximum bit rate            : 32.0 Mbps
Width                       : 1 920 pixels
Height                      : 800 pixels
Display aspect ratio        : 2.40:1
Frame rate mode             : Constant
Frame rate                  : 23.976 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.060
Stream size                 : 1.57 GiB (96%)
Writing library             : x264 core 142 r2479 dd79a61
Encoding settings           : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-3 / threads=48 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=2215 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=31250 / vbv_bufsize=31250 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Encoded date                : UTC 2014-11-25 18:33:11
Tagged date                 : UTC 2014-11-25 18:33:20
Color range                 : Limited
Color primaries             : BT.709
Matrix coefficients         : BT.709

Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : 40
Duration                    : 1h 41mn
Bit rate mode               : Variable
Bit rate                    : 93.7 Kbps
Maximum bit rate            : 110 Kbps
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 48.0 KHz
Compression mode            : Lossy
Stream size                 : 67.9 MiB (4%)
Language                    : English
Encoded date                : UTC 2014-11-25 18:33:19
Tagged date                 : UTC 2014-11-25 18:33:20"

**Comment by mbunkus** [comment]
Your paste shows clearly that the subtitle track is present (track 3 of type text). Therefore there is no issue in mkvmerge. If you don't see subtitles during playback then this is an issue in your player.

**Comment by samerlol** [comment]
here is a little more information...
I made outputted file to input file(which is MKV file) and it was able to see the subtitles
[img]http://i.imgur.com/kjlh4ow.png[/img]
http://i.imgur.com/kjlh4ow.png

**Comment by samerlol** [comment]
No, it's not issues in my player...
cuz when i play the outputted file on all players i had all of them were same results which is no one show subtitles inside, just if i added the subtitles manual, then it's load normally.. Also i was put the video on my TV and no subtitles loaded on it and when i was checking on TV, the TV says no subtitles contained.

**Comment by mbunkus** [comment]
Like I said, the MediaInfo output clearly shows that there is a subtitle track. As does your latest screenshot. So the track is there, and I cannot help you any further with this as I'm not the author of your players. Sorry.

**Comment by samerlol** [comment]
I understand you.. Now my video plays with subtitles contained..

**Comment by samerlol** [comment]
I tried to play videos witch contains subtitles on my TV, but no subtitles loaded?!! just on my PC plays well ?

**Comment by mbunkus** [comment]
That is a bug or limitation in your TV.

**Comment by samerlol** [comment]
Ok. I will see if it's only on my TV..

**Comment by samerlol** [comment]
I caught another problem, maybe i forgot to mention to you, thats when i play the video i was converted it. it's don't reconize the subtites(as arabic subtitles) so it's give me unknown aphabet or language.

![new bitmap image](https://cloud.githubusercontent.com/assets/11778006/9918713/0e3aff02-5cd1-11e5-923e-4fa4ba76e40e.png)

**Comment by mbunkus** [comment]
Then you'll have to set the correct character set for the subtitles when muxing. The character set of text files (and SRT are plain text) cannot be determined automatically.
