### ISSUE TITLE
Feature request: implement a more detailed description for »DTS 96/24« audio tracks

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1431]
About **DTS 96/24**: https://en.wikipedia.org/wiki/DTS_%28sound_system%29#DTS_96.2F24

Currently mkvmerge recognizes those tracks as a plain DTS which is very general. It would be very nice to implement a more detailed description for them: **DTS 96/24**, in order to show the users a correct definition. Thanks to that they will be able to distinguish many DTS audio tracks that may differ from each other. 

So far I've found only two sample files: .mkv & .dts, but I couldn't find any VOB files with DTS 96/24 as they're very rare and difficult to find, of course. Therefore if any of you, guys, have such VOB files or some other, then please upload them to Mosu's FTP server: https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server

Thanks for any help.

**Comment by remuxer32** [comment]
All right. Both sample files have been uploaded successfully to your FTP server :)

**Comment by mbunkus** [comment]
Thanks.

**Comment by remuxer32** [comment]
I've got a fantastic news! Finally I have found a .VOB file that contains the DTS 96/24 audio track. A proper sample file (»Depeche Mode«) has been uploaded successfully to your FTP server.

Summarizing: now you have three sample files:
► Raw DTS 96/24
► DTS 96/24 in .MKV
► DTS 96/24 in .VOB

So: mission complete :) [Unless you need more sample files with DTS 96/24 then I can try to find them for you, of course, but I think that these three files should fully suffice].

Good luck!

**Comment by remuxer32** [comment]
Thanks for the quick implementation. I've used tsMuxeR to mux a VOB file into .ts & .m2ts file. I confirm that mkvmerge recognizes the DTS 96/24 audio track correctly in the both MPEG transport stream files. So: everything works fine. Good job, Mosu.

**Comment by mbunkus** [comment]
You're welcome, and thanks for the feedback/confirmation.
