### ISSUE TITLE
mkvtoolnix-gui.exe (windows binary): no audio delay option

### ISSUE THREAD

**Issue by colomboj** [mbunkus/mkvtoolnix#1432]
Please implement an audio delay option, unless there's another way to produce the same result.
Entering say 1:300 in 'output/misc/additional options' seems to produce an error.

Thank you.

**Comment by mbunkus** [comment]
That option already exists. On the »input« tab, select the track. Then scroll down the right-side panel until you see the »Timecodes and default duration« box. Within you'll find »Delay (in ms)«.
