### ISSUE TITLE
Feature request: Qt4 support

### ISSUE THREAD

**Issue by zaps166** [mbunkus/mkvtoolnix#1436]
Explanation: Qt4 is:
- much more stable from Qt5,
- slightly faster than Qt5,
- is more lightweight than Qt5.
I know that Qt5 has more classes and better C++11 integration than Qt4, but it will be awesome to use it with Qt4 especially on Linux.
It is a pity that wxWidgets GUI has been abandoned especially for Windows and OSX, because it uses native controls.

**Comment by mbunkus** [comment]
Uh… no, sorry. Qt4 is deprecated, and it would require quite some code. Sorry.
