### ISSUE TITLE
Requesting option to turn off acknlowledgement requirements

### ISSUE THREAD

**Issue by psychonaut25** [mbunkus/mkvtoolnix#1437]
Hi there, new to GitHub.  Currently the software requires the user to acknowledge warnings and errors.  I am requesting an option to turn off this requirement.  Thanks!

**Comment by mbunkus** [comment]
What exactly do you want turned off? What are the actions you have to take that annoy you?

**Comment by psychonaut25** [comment]
The requirement to acknowledge warnings and errors after the muxing process has concluded.  At the bottom of the GUI, to the left of the progress bar, there's a tally of the warnings and errors that occurred during the muxing process, and a button to acknowledge these errors.  The option I'm looking for would be to turn off the requirement that we hit the acknowledge button when errors or warnings have occurred, such that when the software was closed and re-started the tally would be re-set to zero.

There could be an option in preferences to turn this requirement on or off

**Comment by psychonaut25** [comment]
Also, it would be nice if we could go straight to the output menu simply by clicking on "1 warning" or "1 error" at the bottom of the GUI

**Comment by mbunkus** [comment]
FYI: You can already right-click on the warnings/errors in the status bar and acknowledge them from a context menu. I'm planning on adding more options to those context menu; see #1396 for that.

**Comment by psychonaut25** [comment]
Oh, I wasn't aware of that.  Thanks

**Comment by mbunkus** [comment]
If you want to give it a try and you're using Windows then grab [one of the pre-builds](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) (build numbers 963 or higher).
