### ISSUE TITLE
2.40:1 fix

### ISSUE THREAD

**Issue by RandQalan** [mbunkus/mkvtoolnix#1439]
Some 1920x800 work some do not and could be added to drop down on list set aspect ratio

**Comment by mbunkus** [comment]
You can already enter any value you want. The values in the drop-down list are only suggestions.

**Comment by RandQalan** [comment]
Yes I know just added to say it could be added
But why some work fine while other fill the screen?
Maybe my render but should do all that way

**Comment by mbunkus** [comment]
Well I cannot tell you the why. I don't develop players.

**Comment by RandQalan** [comment]
Thanks love this tool thou handy :)

**Comment by mbunkus** [comment]
You're welcome :)
