### ISSUE TITLE
mkvmerge does not split subtitles by time as expected

### ISSUE THREAD

**Issue by fingershop** [mbunkus/mkvtoolnix#1442]
When splitting segments from a single original mkv file (with AVC, AC3, & SRT) the subtitles are being split in an unexpected fashion, which when the segments are joined together again results in large audio sync issues, and possibly other issues. Using v8.4.0 32bit on XPsp3.

Here's a more detailed description of the issue:

When a subtitle's display duration goes past the end time of a split segment, I expected that the subtitle's display duration would get truncated as needed, but instead the entire duration is preserved in the segment.

When joining such segments with a bunch of other related segments, this results in equivalent time offsets in the audio tracks, and also causes chapters to seek to the wrong position.

As a test, if I don't include the subtitle track at all during the split, then joining the segments works normally.

I uploaded a file called sj-source.mkv, and you can duplicate the issue with these commands:
mkvmerge.exe -o split.mkv sj-source.mkv --split timecodes:00:00:01,00:00:10.2
mkvmerge.exe -o join.mkv --default-duration 0:24000/1001p split-001.mkv + split-003.mkv

If you listen to join.mkv, you'll see that the sound of the man thumping the mask on his knee is being delayed, and also that the last few seconds of audio were truncated by the same amount.

If you extract the subs from the split-001.mkv and split-002.mkv files, you can see that the 001 sub is over 2.7s long, but it should only be 1s long, same as the video in that segment. Also, you'd expect the 001 sub to continue into the 002 segment, but it doesn't, leaving no subs for the start of that segment. (btw, i've included the english ac3 track instead of the japanese one, which is where the eng subs would normally be needed)

Edit: Forgot to mention, if you re-join the 3 segments in their original order, the same issues are also present.

Let me know if you need any more info, and thanks!

**Comment by mbunkus** [comment]
This is a known limitation if mkvmerge's design. It will likely never get fixed due to the amount of work required. I'll leave this open for the time being, but don't expect any work to go into it. Sorry.

**Comment by fingershop** [comment]
Aww shucks. Maybe some day then.

**Comment by mbunkus** [comment]
After thinking some more about it I've decided not to work on this and to leave it as it is right now. Apart from the technical difficulties of implementing such functionality there's also the question which kind of behavior would actually be better.

Whenever splitting is involved I always have to think about its reversal: appending the split-up files again. And here's where it gets really complicated for subtitles.

1. If I cut the subtitle's duration at the split point then appending two resulting files will result in an entry that's too short. Additionally the second part of the split doesn't contain the subtitle entry at all.
2. If I decide to split the subtitle entry's duration and re-create the part in the second part of the split then appending them again results in two subtitle entries which might flicker on screen. One could imagine some kind of detection whether such two entries are the result of splitting and merging them back into a single entry, but that process is fragile and would break with almost any modification of one of the split parts (e.g. delaying the track in the second part). On top of that it's not so easy to split subtitles. For text subs this is trivial, but for bitmap subs this may be more involved again adding to the amount of work required to implement this properly.

Sorry.
