### ISSUE TITLE
Request variable to rename chapters including start timecode in the chapter's name automatically

### ISSUE THREAD

**Issue by kuabba82** [mbunkus/mkvtoolnix#1445]
As I asked to Moritz by email, I will appreciate a lot if it is possible to have a variable to put the start timecode of a chapter in the chapter's name automatically. Thanks

**Comment by mbunkus** [comment]
Thanks for opening an issue for it. I'll likely implement it.

**Comment by kuabba82** [comment]
I've send you a donation because I've noticed that you implemented this
variable, so I kept my word to donate you something ;-) Thanks a lot for
your job and for this fantastic tool.

2015-10-04 11:59 GMT+02:00 Moritz Bunkus <notifications@github.com>:
