### ISSUE TITLE
MKVToolNix GUI 8.4.0 opens one superfluous, empty merge tab

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1446]
Choosing the new options `When dropping files: Create one new merge settings tab and add all files there` or `When dropping files: Create one new merge settings tab for each file` from the merge preferences dialog (introduced with v8.4.0, i guess) can cause the creation of a superfluous, empty merge tab.

Starting MKVToolNix GUI and passing an mkv file on the command line, like:

    mkvtoolnix-gui.exe something.mkv

will result in two merge tabs being created when one of the two aforementioned options is being used.

The first merge tab will be empty and is titled "&lt;no output file&gt;".
The second merge tab is getting assigned the mkv file which has been specified on the command line.

I think the creation of the empty merge tab is not intentional and should not happen. However, i view this issue as being more or less 'cosmetic' since it does not really impact user experience.

**Comment by mbunkus** [comment]
Thanks for the report. Hmm yeah, for this particular case no extra tab should be opened. I agree that it's solely cosmetic, though.
