### ISSUE TITLE
Trackname not adopted

### ISSUE THREAD

**Issue by MauriceMelius** [mbunkus/mkvtoolnix#1448]
Hej,

1. Which MKVToolNix version are you using? Have you also tried the latest release?
MKVToolNix v8.4.0 (that is the latest release)

2. Which operating system and architecture (32bit vs 64bit) are you using?
Windows 10 (64-Bit) [http://www.sysprofile.de/id32515]

3. What did you try to do? If possible include the command line if the problem is not strictly limited to the GUI part of one of the programs.
My toolchain is: DVDFab (ripping in MKV) -> MKVToolNix (track-renaiming)
I ripped the BluRay 'Password: Swordfish' and imported the MKV into MKVToolNix. 

4. What was the expected result?
Correct names for the video- and audio-tracks.

5. What happened instead?
The names for the audio-tracks are correct - the one for the video sadly not. It hasn't changed neither.
I get a warning and an error (the messages are the same): "--- Fehler ausgegeben von Job »merge in Datei »original (1).mkv« im Verzeichnis »C:/Users/maurice/Desktop«« gestartet am 2015-09-28 13:14:32 ---"

Is it a bug or a wrong setting in the new GUI I havn't seen yet?

- Maurice

**Comment by mbunkus** [comment]
Please verify whether or not the track names have been changed by opening the output file you've created with the GUI's header editor or with mkvinfo's GUI.

Note that there are no warnings nor errors; those two lines are only separators so the user can actually associate warnings/errors that might occur with the correct job (the first job output tab will contain the output of all jobs run within the GUI, not just of the current one).

**Comment by MauriceMelius** [comment]
Hm, strange. It seems nothing has changed. I can't find the track-names - even with the GUI's header editor or with mkvInfo's GUI.

It's strange, because the VLC-player recognizes the audio-tracks correctly but failed at the video-track.

Is this there something wrong on my side or maybe a known bug?

- Maurice

**Comment by MauriceMelius** [comment]
Both, the GUI's header editor and the mkvInfo's GUI, identify the track-names right.

It's strange, because the VLC-player recognizes the audio-tracks correctly but failed at the video-track.

Is this there something wrong on my side or maybe a known bug?

- Maurice

**Comment by mbunkus** [comment]
That would be a bug/missing feature/whatever in VLC then. MKVToolNix is obviously doing the right thing.
