### ISSUE TITLE
MKVToolnix-GUI can't be started

### ISSUE THREAD

**Issue by Ilya87** [mbunkus/mkvtoolnix#1449]
My OS is Arch Linux x86_64, MKVToolnix-GUI version is 583e5296987ff5d4c10437e0d94497eadfdd370d.
Compilation command line
  ./configure --prefix=/usr --with-boost-libdir=/usr/lib \
   --enable-qt --without-curl CC=clang CXX=clang++

As a result every time I want to start MKVToolnix-GUI (without parameters as I did in 8.1.0 version) it shows an error:

![screen](https://cloud.githubusercontent.com/assets/1446573/10184590/3d0fcdaa-6747-11e5-90eb-0cdea5dd8838.png)

mkvtoolnix-gui --help command gives me the following output

mkvtoolnix-gui [options] [file names]

 Использование:
mkvtoolnix-gui <configuration file names>
mkvtoolnix-gui [--merge|--edit-chapters|--edit-headers] <file names>
Listing configuration file names with the extension.mtxcfg causes the GUI to load the those configuration files in the
appropriate tool. Любое другое имя файла добавляется в качестве исходного
файла для слияния и открывается в редакторе главы или в редакторе
заголовка в зависимости от текущего режима. The current mode can be changed with
--merge, --edit-chapters or --edit-headers. The default mode is adding files for merging.

Maybe I am missing something?

**Comment by mbunkus** [comment]
This particular error message only occurs when you're trying to add a file whose type is not recognized. Are you 100% sure you're starting MKVToolNix GUI without any parameters?

Note that running mkvtoolnix-gui with additional parameters that it doesn't recognize as known options (like `--help`) causes the GUI to treat those additional parameters as file names to add.

**Comment by Ilya87** [comment]
Yes, the error appears when I run simply mkvtoolnix-gui command from command line.

**Comment by mbunkus** [comment]
And are you 100% sure that what you're executing is the raw mkvmerge-gui executable and not e.g. a shell script of the same name that adds some parameters?

Please don't be offended that I'm asking again. I've looked into the only two places where that particular message is used. And those code paths can only be called in two cases:

1. If you add or append files in the GUI (e.g. via drag & drop or by using the context menu).
2. When the mkvtoolnix-gui executable is started with command-line arguments.

Additionally I cannot reproduce such behavior at all, and Arch Linux is my main development platform.

**Comment by Ilya87** [comment]
I' m so sorry! I maybe lost my sight. I tried to run newly installed version while instance of old one was already opened (minimized).

**Comment by mbunkus** [comment]
Hehe :) No problem at all.

FYI: The GUI can only have one instance running at the same time. If you run another one then the arguments passed to that second one will be handled by the first one (with the exception of `--help`). This is done so that you can add more files to an existing instance by using the »send to« feature in Windows (or by associating the GUI with certain file types on both Windows and Linux).
