### ISSUE TITLE
Several minor issues in translatable strings (typos, etc)

### ISSUE THREAD

**Issue by DonghuiLi-81** [mbunkus/mkvtoolnix#1451]
Here are some minor issues I spotted in the process of translation.

1. src/common/qt_kax_analyzer.cpp:75:    finding the this
2. src/mkvtoolnix-gui/merge/input.cpp:366:    a trailing '/' after the second instance of 'h.264'.  
end of this line: allow_avc_in_vwf_mode --> vfw
3. src/merge/mkvmerge.cpp:112    'Use' shouldn't be capitalized
4. src/propedit/propedit_cli_parser.cpp:242:    extra 'e' in 'interEpreted' (also in the following line)
5. src/common/chapters/cue_parser.cpp:411:    should it be a stop after '%3%' instead of the comma?
6. src/input/r_real.cpp:571:    the 'len_check' before '%2%' probably shouldn't be there.

Line numbers are as of 583e5296987ff5d4c10437e0d94497eadfdd370d

**Comment by mbunkus** [comment]
Thank you very much.
