### ISSUE TITLE
negative delay from m4a not actually resulting in aac samples being deleted

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1452]
Sample:
https://www.sendspace.com/file/p1syzo

This is a mono aac sample. The input.m4a is created by Nero with iTunSMPB tag to signal encoder delay. Encoder delay is be 54,66.. ms so mkvmerge should delete 3 frames and delay the fourth one by 9ms. (21.3ms *  3 - 9ms ~= 54)
What actually happens:
While the first timecode is set to 9ms no packets are deleted at all. So now sync is off by 54ms+9ms.

(I wonder if this is broken in general for non-stereo aac?)

**Comment by mbunkus** [comment]
Uhm… no, mkverge does drop those three packets. I've created two files: one with the normal mkvmerge executable and one with mkvmerge in which the handling of ITunSMPB encoder delay handling has been disabled. Then I've run `mkvinfo -s …` on both files and compared the checksums of the first frames. Here's the output:

    [0 mosu@sweet-chili /ftp/pub/rip/mkv/bugs/1452_negative_delay_from_m4a_not_actually_resulting_in_aac_samples_being_deleted] mkvinfo -s no-delay-handling.mka|head
    Track 1: audio, codec ID: A_AAC, mkvmerge/mkvextract track ID: 0, default duration: 21.333ms (46.875 frames/fields per second for a video track), language: und, sampling freq: 48000
    I frame, track 1, timecode 0 (00:00:00.000), size 11, adler 0x19ff04bd
    I frame, track 1, timecode 21 (00:00:00.021), size 11, adler 0x192d0456
    I frame, track 1, timecode 43 (00:00:00.043), size 6, adler 0x06ed0213
    I frame, track 1, timecode 64 (00:00:00.064), size 6, adler 0x06ed0213
    I frame, track 1, timecode 85 (00:00:00.085), size 6, adler 0x06ed0213
    I frame, track 1, timecode 107 (00:00:00.107), size 6, adler 0x06ed0213
    I frame, track 1, timecode 128 (00:00:00.128), size 39, adler 0x5caf12aa
    I frame, track 1, timecode 149 (00:00:00.149), size 47, adler 0x9be112b0
    I frame, track 1, timecode 171 (00:00:00.171), size 56, adler 0x885e1844
    [0 mosu@sweet-chili /ftp/pub/rip/mkv/bugs/1452_negative_delay_from_m4a_not_actually_resulting_in_aac_samples_being_deleted] mkvinfo -s with-delay-handling.mka|head
    Track 1: audio, codec ID: A_AAC, mkvmerge/mkvextract track ID: 0, default duration: 21.333ms (46.875 frames/fields per second for a video track), language: und, sampling freq: 48000
    I frame, track 1, timecode 9 (00:00:00.009), size 6, adler 0x06ed0213
    I frame, track 1, timecode 31 (00:00:00.031), size 6, adler 0x06ed0213
    I frame, track 1, timecode 52 (00:00:00.052), size 6, adler 0x06ed0213
    I frame, track 1, timecode 73 (00:00:00.073), size 39, adler 0x5caf12aa
    I frame, track 1, timecode 95 (00:00:00.095), size 47, adler 0x9be112b0
    I frame, track 1, timecode 116 (00:00:00.116), size 56, adler 0x885e1844
    I frame, track 1, timecode 137 (00:00:00.137), size 59, adler 0xa34d180b
    I frame, track 1, timecode 159 (00:00:00.159), size 91, adler 0xa6eb2676
    I frame, track 1, timecode 180 (00:00:00.180), size 99, adler 0x60232867

As you can see the file `no-delay-handling.mka` contains three frames that aren't present in `with-delay-handling.mka`.

I can see no bug here.

**Comment by sneaker2** [comment]
Sorry, you are right. I think I accidentally muxed the extracted aac/adts from output.mkv again instead of the aac extracted from the m4a file.

**Comment by mbunkus** [comment]
No problem :) I'll close the issue.
