### ISSUE TITLE
Merge tool feature request: move »File title« field from the output tab to the »General options« in the input tab

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1453]
I have been working with Blu-ray & DVD discs for many years. The »File title« field, which is located in the output tab, is one of the most important fields for me as I always fill it in order to create the title for my movie which is shown by my movie player. When I was using the old GUI, I used to always switch to the global tab in order to type my movie title. In the new GUI, which should be much friendly and enjoyable than the old one, I do not accept such a location which is strongly uncomfortable for me because of wasting time that I have to spend for manual switching to that tab. Yesterday evening, when I remuxed FIVE! huge Blu-rays, I lost my patience. I said: enough! I'm not going to waste my time anymore for switching to the field that should be always visible for the user and located in the input tab. 

That's why, Mosu, I beg you to implement my special request: please move »File title« field from the output tab to the »General options« in the input tab. I strongly need this feature. Thanks to that I and other users will save a lot of time during working with many Blu-ray/DVD discs at the same time. If you're not convinced yet to my new idea then read the following arguments, please:

**1)** First of all: this is definitely NOT »one man feature«. There are a lot of users (especially professional Blu-ray muxers who share MKV files with other people via p2p) who always fill that field (I can show you proper websites where you can read detailed info from MediaInfo that shows that field filled).

**2)** What if somebody forgets to fill that field before muxing and will discover that lack after muxing completion? Then (s)he will have to add such a file to the GUI again, fill that forgotten field, and finally: start muxing again = amazing wasting time! (especially if the file size is really huge). The second possibility is to open the file in the header editor and fill/edit that field accordingly, but many users may don't know about it or may just completely forget. Please note that it's very easy to forget about that field as it's located in the output tab and therefore it's not visible for the user. From my own experience I can tell you that in the past I forgot to fill that field many times = I had to edit my file in the header editor or even mux it again, if there was a need. Anyway: wasting time.

**3)** What if somebody gives you a file that contains the movie title with many spelling mistakes? I'm sure that you would like to fix it. But in order to do that you have to switch manually to the output tab where that field is situated. Or, if you don't want to mux it again, edit the file in the header editor. Again: it's wasting valuable time and very frustrating. And also: please note that if that field would be placed in the input tab then the users could see such an incorrect title very quickly and fix it immediately, obviously = saving time.

**Summarizing:** I hope that my arguments will convince you to implement this feature which is truly very useful for many users and will allow to make our life much easier and faster. Personally I would like to move that field to the »General options« in the input tab permanently, but IF, for some reason, you don't want to move it there forever, then at least please implement a corresponding checkbox in the preferences dialog that I could enable at ease. It can be disabled (or enabled ☺) by default, if you want. 

Thank you very much for considering. I and other users will be very grateful.

**Comment by mbunkus** [comment]
No, sorry. The input tab contains controls that apply to one or more tracks but not the controls of settings that apply to the whole file. Moving the _file_ title field to the input page doesn't make any sense.

About your other arguments:

1. 
2. What if somebody forgot to mux the chapters? Same issue, therefore I don't consider this to be a strong point in favor of doing this.
3. What if you have a file with a lot of spelling errors in the chapters? Same issue, therefore I don't consider this to be a strong point in favor of doing this.

**Comment by remuxer32** [comment]
>Moving the file title field to the input page doesn't make any sense.

I respect your point of view, but I totally disagree with you. It DOES make a sense if you want to save a time. As we know: time is money. Although: I can agree that »General options« category is not suitable probably as there are the controls that apply to the tracks, but maybe you could, as an exception, create a new category: »File title« that would be located above »General options«?. I could enable it via the preferences dialog (it can be disabled by default, of course). Thanks to that I and other guys will save a lot of time. But I suspect that you will not do it and therefore I will have to switch to the output tab to the end of my life ;(. It's very uncomfortable for me.

**Comment by remuxer32** [comment]
All right. I've just discovered a new way that will help me to save a time. I've noticed that I can switch between many tabs (and sub-tabs) using the keyboard keys like left & right. I knew about it before, but I had to completely forget. Anyway: now I have an altenative way that I can easily use. But there is also one problem that teases me (and not to me only) strongly. I mean that I cannot close all open tabs at the same time in the merge tool. Believe me: closing so many tabs one by one via the left mouse button is truly agonizing. Maybe casual muxers, who mux only one or two files, don't see any problem, but professional muxers, like me, who mux five or more huge Blu-ray files, cannot stand such an inconvenience anymore. Therefore I've got two ideas that you could implement someday:

1) A new context menu with the following entry: »close all open tabs«.
2) A keyboard shortcut: e.g. Ctrl+C (you know: C = Close ☺).

Both of these ideas are very good, and I'm sure that will be very useful for many »hardcore« users who need to close a lot of tabs immediately → according to the philosophy: »time is money«. If you want, you can implement both of them or just only one — it's your choice, of course. And also: such a feature is very needed in the merge tool, obviously, but, if you want, you could extend it for all corresponding tools like header & chapter editor or job output, etc. Again: your decision, naturally ☺.

I hope you will think about it very deeply. Thank you very much.

**Comment by mbunkus** [comment]
You can already close the current tab with Ctrl+W. So closing all tabs means you just have to press and hold Ctrl+W.

Additionally you can just close MKVToolNix GUI and re-start it. You can even assign it a global hot key in Windows to make this even faster.

So introducing yet another menu entry for this would be save only a marginal amount of time if any (you do spend time looking for the correct menu entry to click on, too, you know).

So whenever someone says »time is money« they usually mean »my time is money, please spend your time so I don't have to«. I always find this offensive, doubly so if the perceived savings are so small. So your time is money, but mine isn't? I have to spend sometimes hours to implement and test a feature and later to support it, translators have to spend time translating new/changed strings etc. Is your time worth something and mine isn't? Is your worth more than mine? Do you think I own so much money (have so much free time) that I should really spend it on you?

Therefore: no, sorry, I won't spend time on such a feature. It's not really needed as there are viable ways to achieve the same outcome with almost as little effort as your proposed solution.

**Comment by remuxer32** [comment]
@Mosu

I have read your response very carefully and I have to say that you interpreted my words very literally. Please let me explain you my point of view. I would like to make my words very clearly to understand.

So: 

> So whenever someone says »time is money« they usually mean »my time is money, please spend your time so I don't have to«. I always find this offensive, doubly so if the perceived savings are so small.

First of all: whenever I discuss with you (here or on IRC) my intention is NOT to hurt you. My goal is always a constructive debate, not a foul play. »Time is money« is a metaphor. As is known, metaphors may have a lot of meanings, and many people may interpret such words completely different. When I say: »time is money« I mean that I can do something much faster than at present = I can save a lot of time (money). For example: when you are using a car then you have to spend some or more money for it (petrol, repair, inspection, etc.), but then you feel comfortable while driving and, of course, you can get from A to B much faster. An alternative is a bike that allows you to save much money, but unfortunately your trip from A to B is much slower = wasting time. Summarizing: car > bike; if you want to save a time, but bike > car; if you want to save money. Which one of them will you choose? Well, it's your choice of course ☺. Therefore:

> »my time is money, please spend your time so I don't have to«.

is NOT true in my case because this is NOT my intention. I'm NOT a lazy & selfish man so I never ask anyone e.g. »just do it because I don't want to«. Therefore I kindly ask you: please do not treat my words (metaphors) as offensive. This is not an attack against you. And also: please do not treat my words very literally. Just always try to find the deeper meaning. If you felt resentful due to my words then please accept my apologies, but, like I said, my intention was not to hurt you.

Moving on......

> So your time is money, but mine isn't? I have to spend sometimes hours to implement and test a feature and later to support it, translators have to spend time translating new/changed strings etc. Is your time worth something and mine isn't? Is your worth more than mine?

Of course that your time is as valuable as mine is. There is no inequality. I want you to know that I have a great respect for your hard and selfless work. I'm always very grateful and I truly appreciate your effort & patience for me and other users. It's very glorious. You are a fantastic man who created the greatest software for working & creating with Matroska files in the digital world. MKVToolNix is absolutely unique. There is no such a good program like yours (well: MakeMKV is good as well, but its destination is little different).
But remember please that I spend sometimes many hours to translate strings from one language to another as well. Translating so many sophisticated strings from English into Polish is not easy, but I'm doing this because it's my passion (pleasure for me). Your passion is programming, my passion is translating (to be precise: English language as a language). Also: I'm an author of many useful ideas (requests) that you implemented in the past (e.g. TrueHD and its cores). Again: I'm doing this (creating new ideas) because I want to make your program better and better for all of us. Approving them is always your choice, not a compulsion. And finally: reporting bugs. I've reported tons of them. I always try to find any bugs in your software and then report them to you. As you know, finding (testing your software) them requires a lot of my time, but again: I'm doing this because I really love your program and I want it to be without any bugs.
Summarizing: we both spend a lot of time in order to improve & fix our beloved software. We do that completely disinterestedly as it's our passion, not an order.

>Do you think I own so much money (have so much free time) that I should really spend it on you?

Again: I do NOT think in this way at all. Whenever I invent a new idea I always share with you as you're very good programmer. Unfortunately: I'm not a coder so I cannot implement my favourite ideas. If I were him, I would implement many tasks on my own. Of course that your time is limited and I perfectly understand that you can't implement some of my ideas always when I want. It's okay and I don't have a problem with that. I fully respect it. 

Going back to the beginning:

>You can already close the current tab with Ctrl+W. So closing all tabs means you just have to press and hold Ctrl+W.

Meh, you're right. To be honest: I completely overlooked that keyboard shortcut ;(. It's my mistake. You know: I'm used to use a mouse very often so I don't focus my attention for many »hidden« shortcuts. It seems that I have to change my habits and start using my keyboard more often than now. Thank you for your hint, Mosu. I will remember about it. And also: I have to admit that you managed to convince me that such a feature is not really needed. I agree with you now. Thank you for this lesson very much.

I hope you are not angry with me right now.

Best regards.

**Comment by mbunkus** [comment]
I'm not angry with you. I know that you do a LOT of work to improve MKVToolNix and I highly appreciate it, always have. »Time is money« is just something that really gets on my nerves as the people using that as an argument seldom think about that fact that implementing something takes time, just not theirs. Again, I don't really mean you personally, it's more a general dislike of that phrase.

Anyway. Another keyboard shortcut that might help you: you can switch between the input and output tabs with Alt+<letter> where <letter> depends on the translation. For English it's Alt+O for the output tab and Alt+I for the input tab. For Polish it's currently… checking pl.po… Alt+W for the output tab and Alt+W for the input tab, too. You might want to look into those and change them to be unique :)

**Comment by remuxer32** [comment]
Hmmm, thanks for your new tips, Mosu. They're sound very useful. I need to check them :)

Good to know you're not angry with me. Peace :)

**Comment by mbunkus** [comment]
You can see which letters are shortcuts by pressing and holding Alt, BTW. Unfortunately this doesn't work for context menus, though, as pressing Alt will close the context menu. But it does for all the other windows. Makes it a bit easier when looking for duplicates.
