### ISSUE TITLE
save chapters into txt file

### ISSUE THREAD

**Issue by fuel1986** [mbunkus/mkvtoolnix#1455]
Hello! MKVToolNix GUI may open txt files with chapters. Please add opportunity save chapters in txt file.

**Comment by mbunkus** [comment]
No, sorry. The simple OGM-style text format doesn't support all the features that Matroska chapters can use.

**Comment by DandyClubs** [comment]
i use chapterEditor

MKVToolNix save only xml

ogg format editer save
