### ISSUE TITLE
MKVToolNix GUI: forward slashes instead of backslashes

### ISSUE THREAD

**Issue by heebijeebi** [mbunkus/mkvtoolnix#1456]
Since MKVToolNix GUI v8.4.0 it automatically uses forward slashes on Windows 7 x64 instead of backslashes in the file output. Therefore all files get saved in the root folder if someone doesn't manually correct it.

**Comment by mbunkus** [comment]
That's not correct. Windows supports forward and backward slashes the same way. Therefore `C:/some/where/file.mkv` is the same location as `C:\some\where\file.mkv`.

See also #1298.
