### ISSUE TITLE
remuxing files in MKVtoolnix 8.4.0 doesnt work

### ISSUE THREAD

**Issue by un1versal** [mbunkus/mkvtoolnix#1457]
Thers not much to this Bug, Linux Ubuntu 14.04LTS MKVtoolnix 8.4.0 64bit

Open a file (any file) with UI and then click start muxing, in 2 seconds error happens and thers no way to do this via UI. Haven't tested command line.

```
--- Errors emitted by job 'merging to file »The. Happening.mkv« in directory »/home/user/Desktop/linux«' started on 2015-10-06 17:57:07 ---
There is no translation available for ''.
```
All files no matter what finish with this error, this build as a result is unusable

**Comment by un1versal** [comment]
OK, since the error was related to translation I had a look at settings which were fine before in previous versions...

Turns out 8.4.0 upgrade must have somehow glitched and changed the Interface Language from English to Catalan **No idea why** as it was set to English before.

Changing it back to English Works.

**Comment by mbunkus** [comment]
I have already investigated this in #1434, but ultimately I wasn't able to determine the root cauase. I've since implemented a workaround so that this shouldn't happen again. If it does in one of the upcoming releases then re-open this issue, please. In that case it would be great to have the `mkvtoolnix-gui.ini` file from before the upgrade, too. See [this wiki page](/mbunkus/mkvtoolnix/wiki/Settings-location) for its location.

**Comment by un1versal** [comment]
unless mkvtoolnix makes a backup of the mkvtoolnix-gui.ini (is this even in Linux) then there wont be much chance of getting anything from previous to upgrade.

looking at #1434 its All Windows files anyway. Im not in Windows. 

In any case next upgrade here is a file of my conf file now after I made it work (sorry didnt know). (just in case  forget to backup next time.

```
[defaults]
defaultAdditionalMergeOptions=--disable-track-statistics-tags
defaultChapterCountry=gb
defaultChapterLanguage=eng
defaultSubtitleCharset=
defaultTrackLanguage=eng

[info]
guiVersion=8.2.0

[jobQueue]


[splitterSizes]
mergeFilesTracksSplitter=1, 1
mergeInputSplitter=1, 1
mergeOutputSplitter=1, 1

[windowGeometry]
mtx__gui__MainWindow=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\0\x81\0\0\0\xe9\0\0\x5w\0\0\x3\xa5\0\0\0\x8b\0\0\x1\v\0\0\x5m\0\0\x3\x9b\0\0\0\0\0\0)
mtx__gui__PreferencesDialog=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x1\x39\0\0\x1\xe\0\0\x4\xd0\0\0\x3\xc1\0\0\x1\x43\0\0\x1\x30\0\0\x4\xc6\0\0\x3\xb7\0\0\0\0\0\0)
```

**Comment by mbunkus** [comment]
Thanks for the config, but are you sure this is your whole `~/.config/bunkus.org/mkvtoolnix-gui/mkvtoolnix-gui.ini` file? There are tons of settings missing, especially the whole `[settings]` and `[features]` sections. Additionally the `guiVersion` parameter indicates that this file has been created with 8.2.0, not 8.4.0.

**Comment by un1versal** [comment]
thats what I have, and for the second time Im on Linux, this is the ONLY config I have in

**Comment by mbunkus** [comment]
I did hear you that you're on Linux, that's why I wrote to check `~/.config/…` instead of `C:\Users\…`.

Anyway, the configuration is stored in the directory `~/.config/bunkus.org/mkvtoolnix-gui`, not directly in `~/.config/bunkus.org`. I've fixed the wiki page accordingly.

**Comment by un1versal** [comment]
> Thanks for the config, but are you sure this is your whole ~/.config/bunkus.org/mkvtoolnix-gui/mkvtoolnix-gui.ini file?

You keep mentioning the ini file, ini is Windows :smile: even if the path s Linux path. :smiling_imp: 

Yep I see the correct one now... ``` ~/.config/bunkus.org/mkvtoolnix-gui ```

```

[defaults]
defaultAdditionalMergeOptions=
defaultChapterCountry=us
defaultChapterLanguage=eng
defaultSubtitleCharset=
defaultTrackLanguage=eng

[info]
guiVersion=8.4.0

[jobQueue]
order={422fbbac-7ee2-4368-ae7d-aeec8cb652bc}

[settings]
autoSetFileTitle=true
chapterNameTemplate=Chapter <NUM:2>
clearMergeSettings=0
disableAnimations=false
disableCompressionForAllTrackTypes=false
disableDefaultTrackForSubtitles=false
dropLastChapterFromBlurayPlaylist=true
enableMuxingAllAudioTracks=false
enableMuxingAllSubtitleTracks=false
enableMuxingAllVideoTracks=true
enableMuxingTracksByLanguage=false
enableMuxingTracksByTheseLanguages=@Invalid()
fixedOutputDir=.
jobRemovalPolicy=0
lastConfigDir=.
lastOpenDir=.
lastOutputDir=/home/nss/Desktop/Sharelinux/incoming
mergeAddingAppendingFilesPolicy=1
mergeAlwaysShowOutputFileControls=true
minimumPlaylistDuration=120
oftenUsedCharacterSets=ISO-8859-15, MS-ANSI, US-ASCII, UTF-8, WINDOWS-1250, WINDOWS-1252
oftenUsedCountries=cn, fr, jp, pt, se, gb, us
oftenUsedLanguages=chi, eng, fre, jpn, por, swe, und
outputFileNamePolicy=4
priority=2
relativeOutputDir=.
scanForPlaylistsPolicy=0
setAudioDelayFromFileName=true
showMoveUpDownButtons=false
showOutputOfAllJobs=true
showToolSelector=true
switchToJobOutputAfterStarting=false
tabPosition=0
uiLocale=en_US
uniqueOutputFileNames=true
updates\checkForUpdates=true
updates\lastUpdateCheck=@Variant(\0\0\0\x10\0%~\xd6\x3\xd9O\xf0\xff)
updates\version_8_4_0=true
useDefaultJobDescription=false
warnBeforeAbortingJobs=true
warnBeforeClosingModifiedTabs=true

[splitterSizes]
mergeFilesTracksSplitter=1, 1
mergeInputSplitter=1, 1
mergeOutputSplitter=1, 1
sOutput=1, 1
sWarningsErrors=1, 1

[windowGeometry]
mtx__gui__MainWindow=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\0\x88\0\0\0g\0\0\x4M\0\0\x3#\0\0\0\x92\0\0\0\x89\0\0\x4\x43\0\0\x3\x19\0\0\0\0\0\0)
mtx__gui__PreferencesDialog=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\0\x8d\0\0\0t\0\0\x4$\0\0\x3'\0\0\0\x97\0\0\0\x96\0\0\x4\x1a\0\0\x3\x1d\0\0\0\0\0\0)
```

**Comment by mbunkus** [comment]
Thanks for the content; looks good to me now. That'll help if it happens again.

The Qt library (and therefore by extension the MKVToolNix GUI) uses the same file format for storing its settings on both Windows and Linux; they're not just Windows-only. The file is even called `mkvtoolnix-gui.ini` on both platforms. So it's quite correct to talk about INI files, even if you're on Linux.

To be really anal about it: it's a file containing the GUI's settings or configuration options, and that file's format is something that is similar to but not quite the same as the format used by Windows for its INI files. I usually abbreviate this rather convoluted description to »Windows-style INI files«. However, like I said above, they're used by the GUI on all platforms, not just Windows.

**Comment by un1versal** [comment]
yea, the 8.2.0 one was a conf file... but thats doesnt matter what matters is we now have the correct one. Still no idea why that ended up there so in between 8.2.0 and 8.4.0 something happened with the storage path.

**Comment by un1versal** [comment]
> Also have a feeling if ou change the interface language to Catalan this bug will happens. -> testing it now.

No, Seems not, I changed it back to what it was (best as I could remember as I removed languages and countries from the often used list as well) when I noticed the bug and still worked. 

Idle like to try downgrading back to 8.2.0 configuring it and taking if from there to check.

**Comment by un1versal** [comment]
Got it

This is what I discovered.

**8.2.0** Stored config in ~/.config/bunkus.org/mkvtoolnix-gui**.conf**

It worked just fine.... On my tests I 8.3.0 worked OK also and upgrading to 8.4.0 worked just fine.

However. In reality I must have skipped 8.3.0 mkvtoolnix-gui and was probably using the mkvmerge, this is important because there was absolutely no config file in ``` ~/.config/bunkus.org/mkvtoolnix-gui ``` so by the time 8.4.0 came it created one and that new config produces this bug.

This means is if you are a brand new user in 8.4.0 for mkvtoolnix-gui you probably see this bug.

None The less here is a copy of the buggy initial mkvtoolnix-gui.ini for 8.4.0

Hope this helps.
```
[defaults]
defaultAdditionalMergeOptions=
defaultChapterCountry=
defaultChapterLanguage=und
defaultSubtitleCharset=
defaultTrackLanguage=und

[info]
guiVersion=8.4.0

[jobQueue]
order={e4944222-7589-4fdb-bc27-1a674e02fe49}, {ddf9c2fc-c081-4697-af7f-f51cf4d08247}

[settings]
autoSetFileTitle=true
chapterNameTemplate=Chapter <NUM:2>
clearMergeSettings=0
disableAnimations=false
disableCompressionForAllTrackTypes=false
disableDefaultTrackForSubtitles=false
dropLastChapterFromBlurayPlaylist=true
enableMuxingAllAudioTracks=false
enableMuxingAllSubtitleTracks=false
enableMuxingAllVideoTracks=true
enableMuxingTracksByLanguage=false
enableMuxingTracksByTheseLanguages=@Invalid()
fixedOutputDir=.
jobRemovalPolicy=0
lastConfigDir=.
lastOpenDir=.
lastOutputDir=/home/nss/Desktop/Sharelinux/incoming/1.Planet.Earth.EP01.From.Pole.to.Pole
mergeAddingAppendingFilesPolicy=0
mergeAlwaysShowOutputFileControls=true
minimumPlaylistDuration=120
oftenUsedCharacterSets=ISO-8859-15, MS-ANSI, US-ASCII, UTF-8, WINDOWS-1250, WINDOWS-1252
oftenUsedCountries=cn, de, es, fi, fr, gb, it, jp, nl, no, pt, ru, se, us
oftenUsedLanguages=chi, dut, eng, fin, fre, ger, ita, jpn, nor, por, rus, spa, swe, und
outputFileNamePolicy=4
priority=2
relativeOutputDir=.
scanForPlaylistsPolicy=0
setAudioDelayFromFileName=true
showMoveUpDownButtons=false
showOutputOfAllJobs=true
showToolSelector=true
switchToJobOutputAfterStarting=false
tabPosition=0
uiLocale=
uniqueOutputFileNames=true
updates\checkForUpdates=true
updates\lastUpdateCheck=@Variant(\0\0\0\x10\0%~\xd7\x2\x41\xa8\xc2\xff)
useDefaultJobDescription=false
warnBeforeAbortingJobs=true
warnBeforeClosingModifiedTabs=true

[splitterSizes]
mergeFilesTracksSplitter=1, 1
mergeInputSplitter=1, 1
mergeOutputSplitter=1, 1
sOutput=1, 1
sWarningsErrors=1, 1

[windowGeometry]
mtx__gui__MainWindow=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\xff\xff\xff\xf7\xff\xff\xff\xf8\0\0\x3\xbc\0\0\x2\xb4\0\0\0\x1\0\0\0\x1a\0\0\x3\xb2\0\0\x2\xaa\0\0\0\0\0\0)
```

**Comment by mbunkus** [comment]
Thanks for the investigation. Brand new 8.4.0 users do not see the issue, I've just checked that, but it's quite possible that my upgrade progress which migrates the configuration file to a new location is somewhat broken. This is nothing that I'm going to invest time in, though.

**Comment by un1versal** [comment]
I think the bug is caused by an initially empty ```uiLocale=``` field.

With no previous config files I can reproduce this bug now at will.

The current Linux release produces that exactly on first use.

**Comment by mbunkus** [comment]
Like I've written in #1434, I've taken precautions against empty locale fields. That commit will be part of 8.5.0, but it isn't part of 8.4.0 yet.

**Comment by un1versal** [comment]
Sure, anyway this investigation helped me understand somewhat the madness behind your genius.
