### ISSUE TITLE
Cannot swap left-right stereo images

### ISSUE THREAD

**Issue by niente0** [mbunkus/mkvtoolnix#1458]
Hi, I tried to swap left and right images in a 3D movie but it seems that mkvtoolnix doesn't care if I select "side by side left first" or "side by side right first". Output after muxing is always identical to input. Do I miss something? Thanks

**Comment by mbunkus** [comment]
That selection only sets a certain header field to a certain value; it doesn't alter the video content. This is by design and exactly how it should be handled. If your player doesn't support the information stored in that field then it's a missing feature in that player.
