### ISSUE TITLE
new gui - opening a network drive to write to takes minutes to complete

### ISSUE THREAD

**Issue by abigmeanie** [mbunkus/mkvtoolnix#1459]
the new gui is extremely slow to open a network drive to select an output folder.  it literally takes minutes to gain access to folders on any network drive.  the old gui opened them just like they were a local drive within seconds.

**Comment by mbunkus** [comment]
Hmm. I cannot reproduce the issue. I'm developing on Linux and all of my audio/video files are located on the Linux server as well. So each and every time I use or test the Windows version of the GUI I'm accessing the files via a network share. I've also just tried it again, and access is almost instant both with mapped network shares as well as with UNC paths.

Searching for possible issues in Qt with respect to slow network share access led me to one particular option that one could set. I've implemented that option in [pre-build 960](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/). Please give it a try. If it fixes the issue for you: great! If it doesn't then there's nothing I can do about it as all file dialogs are handled solely by the Qt library, and that aforementioned option is the only one possibly affecting the performance.

**Comment by abigmeanie** [comment]
On 10/8/2015 5:09 PM, Moritz Bunkus wrote:
>
> Hmm. I cannot reproduce the issue. I'm developing on Linux and all of
> my audio/video files are located on the Linux server as well. So each
> and every time I use or test the Windows version of the GUI I'm
> accessing the files via a network share. I've also just tried it
> again, and access is almost instant both with mapped network shares as
> well as with UNC paths.
>
> Searching for possible issues in Qt with respect to slow network share
> access led me to one particular option that one could set. I've
> implemented that option in pre-build 960
> <https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/>. Please
> give it a try. If it fixes the issue for you: great! If it doesn't
> then there's nothing I can do about it as all file dialogs are handled
> solely by the Qt library, and that aforementioned option is the only
> one possibly affecting the performance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbunkus/mkvtoolnix/issues/1459#issuecomment-146685414>.
>

thanks.  whatever you changed worked.  it's back down to seconds rather
than minutes to open the network fileservers here!

mike colligan

**Comment by mbunkus** [comment]
Thanks for the confirmation.
