### ISSUE TITLE
mkvmere raw m2v not recognized

### ISSUE THREAD

**Issue by Selur** [mbunkus/mkvtoolnix#1462]
using latest portable 64bit version from fosshub I get:

    mkvmerge --ui-language en -o "H:\Output\1.mkv" --disable-track-statistics-tags --global-tags "H:\Temp\1_07_31_12_7210__05.xml" -d 0 --default-track 0:yes --default-duration 0:25fps --aspect-ratio-factor 0:1.200 --no-chapters --compression -1:none --forced-track 0:yes --no-audio --no-subtitles "H:\Temp\07_31_12_7210_04.m2v" --default-track 0:yes --sync 0:-33 --forced-track 0:no -a 0 --compression -1:none --no-video --no-subtitles --no-chapters "H:\Temp\iId_1_aid_0_DELAY_-33ms_07_31_12_7210_02.aac"
    mkvmerge v8.4.0 ('A better way to fly') 64bit
    Error: The file 'H:\Temp\07_31_12_7210_04.m2v' has unknown type. Please have a look at the supported file types ('mkvmerge --list-types') and contact the author Moritz Bunkus <moritz@bunkus.org> if your file type is supported but not recognized properly.

Seeing that you fixed a few of the mpeg-2 muxing problems since I last reported an issue with m2v, I uploaded the m2v file to:
https://drive.google.com/file/d/0B_WxUS1XGCPAczc4ZlhreDlJYUE/view?usp=sharing

Cu Selur

**Comment by mbunkus** [comment]
Thanks. It's not a crash, it's mkvmerge not recognizing the file type. MPEG-2 video still doesn't have a high priority for me; therefore I don't know when I'll take a look at it.

**Comment by basicmaster** [comment]
The reason here is that the m2v file does not immediately begin with the start code prefix `0x000001` - which is a requirement of the detection in `mpeg_es_reader_c::probe_file`. If you in this case remove the first 23 bytes, the file fulfills the condition and is detected.

**Comment by mbunkus** [comment]
Thanks for the analysis, @basicmaster. This has helped me find some motivation to fix it :)
