### ISSUE TITLE
Let the GUIs detect if magic.mgc is present

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1467]
Apparently it happens that the ```magic.mgc``` file gets missing. This leads to the programs failing depending on it.

At least the GUIs could check if the file is present during start and warn the user if it is missing.

I'm unaware if it is difficult to check if a file has the correct version, but since the wrong version can still cause issues it might be worth it.

**Comment by mbunkus** [comment]
No, sorry. Are you deleting/omitting random files from a Microsoft Office installation? Most likely not. So why do users think they can omit files from the MKVToolNix package?

Programs usually don't check if their installation is complete or if it has been tempered with by the user. If the user wants to shoot himself/herself in the foot then it's his/her own fault.

**Comment by Krzysiu** [comment]
Well, maybe I'll answer why users, at least me, thinks that. Office don't come portable so there's no way to choose before install. The point is that indeed not all files are needed. Like ico files - it's easy to misclick ico file, thinking it's exe. Or locales - I don't think I need all locales. And the last reason - it was working well without magic.mgc in past versions. 

All I want is to point that it's not so obvious, like you are telling. The argument that it's user fault could be extended to checking if file is really MKV. Why your tool should do it? If somebody wants to open non-mkv file then tool would crash and that's all, user fault. Why to check if user input is something we need (like integer)? It's all to help users to fix their faults. Also most apps will tell something like "cannot access x.dat", not crash without reason.

I'm not asking you to change behavior. I'm just telling what I think about application reaction in case of wrong user's action.

**Comment by mbunkus** [comment]
The _installation_ is a completely different thing compared to the _data the program is supposed to work on_. Of course I need to check the data the program processes. That's a given. But the installation? Nope, sorry.

Additionally I'm not even using `magic.mgc` directly. I'm using a library that uses `magic.mgc`. That library segfaults if the file is not present or if its version isn't the one it's expecting. It's not my job to make sure that the libraries are bug free; that's the library author's job.

**Comment by mbunkus** [comment]
BTW, "portable" doesn't mean "you can pick the files you want" but "will run from any folder as long as the relative structure is kept intact".
