### ISSUE TITLE
New GUI: error if translation not available

### ISSUE THREAD

**Issue by Jiehong** [mbunkus/mkvtoolnix#1468]
Hello,

Software: Archlinux, mkvtoolnix 8.4.0.

I started the application, and in preferences the language was set to Catalan, and when I tried to merge a file, I got the following error:

```
--- Errors emitted by job 'merging to file »filename.mkv« in directory »/home/user/directory«' started on 2015-10-11 23:59:27 ---
There is no translation available for ''.
```

In preferences, going switching language to English solves the issue, and the merge works correctly.

Could you please have a look at it?

**Comment by mbunkus** [comment]
See #1434 and #1457.
