### ISSUE TITLE
mkvmerge.exe → This application has requested the Runtime to terminate it in an unsual way.

### ISSUE THREAD

**Issue by Anime4000** [mbunkus/mkvtoolnix#1469]
I copied `mkvextract.exe` and `mkvmegre.exe` and run via command-line script, after long run encoding, it crash and left this message...
![runtime](https://scontent-kul1-1.xx.fbcdn.net/hphotos-xlp1/v/t1.0-9/12063395_10207720671557467_70312961038130320_n.jpg?oh=ae5916a56f22ace7f5f8ec96f328f93e&oe=56D02C4F)

may I know which Runtime that I need to install?

**Comment by mbunkus** [comment]
Ripping apart the packages like this is not supported. At the moment you need more files than than those two, especially `data/magic.mgc`, but this may change again in the future.

See e.g. #1464.

**Comment by Anime4000** [comment]
`mkvmerge.exe` search `data/magic.mgc` through **Working Directory** or root of `mkvmerge.exe` is located?

**Comment by mbunkus** [comment]
Installation path.
