### ISSUE TITLE
MKVToolnix 8.4.0 and older broke qaac AAC-LC 8 Channel

### ISSUE THREAD

**Issue by anana93** [mbunkus/mkvtoolnix#1470]
MKVToolnix broke the audio when I mux it

here's my original sample
https://www.sendspace.com/file/u73q12

**Comment by mbunkus** [comment]
What exactly is broken? Please give me some more details what to look for.

**Comment by anana93** [comment]
the muxed file never can play...
you can try, btw

**Comment by anana93** [comment]
here's the source (wav) file
https://www.sendspace.com/file/si010t

**Comment by mbunkus** [comment]
Your sample plays just fine here with VLC after remuxing it to Matroska. Hence me asking what your problem is.

If you have problems with a hardware player then that's most likely an issue in the hardware device and not in mkvmerge.

**Comment by anana93** [comment]
it can play with vlc, but the audio is broken
you can compare with the wav file

My hardware support 7.1 channel...

**Comment by anana93** [comment]
it can't demux using ffmpeg, and the mediainfo says
Channel(s)                  :  channel0

**Comment by mbunkus** [comment]
Ah, I can see now that mkvmerge writes 0 channels. That's obviously not so nice :)

**Comment by anana93** [comment]
Ok, thx for the confirmation...

**Comment by mbunkus** [comment]
Well, no reason to close this, I guess that was accidental.

**Comment by mbunkus** [comment]
This file has a channel count of 0 in its ADTS headers. This means that the channel count is signalled via inband PCE elements. mkvmerge does not support decoding that much of the AAC data in order to be able to parse those PCE elements, and it most likely never will. Therefore I'm closing the issue as won't fix. Sorry.
