### ISSUE TITLE
Slow write speeds on MKV Merge

### ISSUE THREAD

**Issue by Christopher379** [mbunkus/mkvtoolnix#1471]
For some reason, it's taking 20 minutes to remove subtitles from a single 1 hour long tv show (1.3GB file size)

**Comment by Christopher379** [comment]
version 8.4.0

**Comment by mbunkus** [comment]
Way to ask for help…

Alright, so I'll need some more information:

1. How big is the file you're re-muxing?
2. Are you reading and writing to the same drive?
3. What kinds of speeds to real benchmarks show for that drive?
4. What kind of drive is it in the first place (locally connected normal hard disk, SDD, USB thumb drive, USB-connected hard drive, network share…)?

**Comment by Christopher379** [comment]
Sorry, didn’t mean to sound offensive! And thank you for the help.

The files are 1.3GB each +/-

Yes , read and write using the same drive

Normally, with previous versions of MKVmerge it only takes about 2 minutes to remove the subtitles from a file that size. It seriously was only at about 30% after 10 minutes on a 1.3GB file.

Locally connected normal hard disk

 

Thanks,

Chris

**Comment by Christopher379** [comment]
Please note that I batch loaded the whole season into mkvmerge 

The results I just explained to you was the first file out of 13 files

**Comment by Christopher379** [comment]
Please be advised that I added only the single file to the job queue and it muxed INCREDIBLY FAST.

**Comment by mbunkus** [comment]
Well, YOUR SHOUTING-STYLE SUBJECT and the "come on, guys" was definitely not well received. I understand blowing off steam, but please keep in mind that while you may feel better afterwards the recipient often does not. But let's drop this.

Are you maybe mistaking the overall queue progress for the progress of a single file? Or have you forcefully started muxing all jobs at once?

**Comment by Christopher379** [comment]
I had the target folder open and it had only crated one new file during the process, which the first first file in the job queue.

I’m pretty positive that it was not on the total job as only one new file had been created. Although the file size was LARGE. 8+ GB…. Am I missing something here?

**Comment by mbunkus** [comment]
Sounds like you've added all input file to a single muxing job. That way you'll end up with a single file containing the content of all the 13 input files.

If you want to have 13 output files then you need to create 13 distinct mux settings, one for each output file. MKVToolNix GUI does't have batch muxing capabilities and never will.

**Comment by Christopher379** [comment]
good to know, thank you

**Comment by Christopher379** [comment]
I used to drag files over and into the GUI, one at a time, each having their own separate window and the jobs would complete accordingly. Now when I try this, it used the same window and I’m ending up with six different copies of the same file name (S01E01) even though I’ve dragged different and separate files over.

**Comment by mbunkus** [comment]
The GUI supports several ways of treating dropped files. It defaults to adding all files to the current muxing job. You can change this behavior in the preferences; look for the option "when dropping files" on the "Merging" tab. I suggest you set it to "ask the user" for the time being; that way you can get a feel for the different options available to you. You can even drop all 13 files in one go and then let the GUI create a single mux job for each dropped file.
