### ISSUE TITLE
GUI: add "forced track" column to track list

### ISSUE THREAD

**Issue by Ivan2016** [mbunkus/mkvtoolnix#1472]
Hi folks. Can you consider the folowing features in on of the next releases:
1) Add "Forced track" attribute column to the track list table.
2) It would be great if double-click on the track list table row will change attribute under the mouse. Currently double-click will result in "process track" attribute switch. But it might be convenient to take into account column under the mouse. E.g.:
- when the mouse is over "default track" column double-click will change "default track" value (default->yes->no);
- double-click over the name column will allow to change track name directly in the table (Return key will commit the change while Escape key will discard it).

3) Usually "forced track" flag is not set but "default track" is used instead of this. It might be useful to recognize forced tracks via track name. Gui global option to mark tracks containing "Forced" in their names as "forced tracks" shoud work.

TIA, Ivan.

**Comment by mbunkus** [comment]
Thanks for the suggestion. I may think about 1., but it's a no to 2. and 3. Double-clicking already has the problem of de-selecting all but one entry, so you cannot change multiple tracks at the same time with double-clicking. Therefore I don't want to expand on the functionality. And trying to coax meaning from free-form text is at best error-prone and at worst highly annoying to users. Sorry.

**Comment by Ivan2016** [comment]
Ok. Basically, I want to minimize the number of clicks to change flag properties.
What about converting drop-downs for "process track", "default track" and "forced track" to check-boxes or radio-buttons in the properties list on the right side? AFAIK these are 0-1 flags so this sounds feasible. Flags having extra "Detect automatically" option in the gui can be implemented via tri-state check-box.

**Comment by mbunkus** [comment]
No, sorry, too many changes for a minor improvement. I'm open to contributed patches, though.
