### ISSUE TITLE
Feature request: the Delete key for removing attachments

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1473]
Currently the users can use the Delete/Backspace key for removing entries in the following sections:

► Chapter editor
► Job queue
► And finally: Merge tool — but in the »Input« tab only

So: what about the »Attachments« tab? No, we can't use that key. Therefore it would be very nice to implememt the Delete/Backspace key for removing attachments as well. If such a keyboard shortcut exists in other sections then should exist in the »Attachments« tab, too. There shouldn't be any strange exceptions. All sections/tabs should be symmetrical in this regard. Also: such a feature is very useful for users because removing attachments via the Delete key is much faster than the context menu. Summarizing: many pros, no cons :)

Thank you very much.

**Comment by mbunkus** [comment]
Hmm, you're quite right about that :) Should be easy to implement.

**Comment by remuxer32** [comment]
Thanks for the quick implementation. Could you update your ChangeLog, please? I've noticed that there is lack of the information about that. Unless it's not necessary to mention...............
