### ISSUE TITLE
GUI: show chapters with higher precision in chapter editor tree view

### ISSUE THREAD

**Issue by PegasusRider** [mbunkus/mkvtoolnix#1474]
I would find it quite handy to have chapter times shown in the list out to the thousandths. Could an option for this be added to the GUI?

I see that you can get the thousandths info by chapter in the side window, but you have to select each chapter individually to get that.

Maybe I'm doing it the hard way, by using excel to calculate new times for merging files and entering the times by hand isn't the most efficient way, but... that's what I'm doing.  And having to select each chapter to get the .xxx info forces more window swapping than necessary.

Thanks :)

**Comment by mbunkus** [comment]
Thanks for the suggestion. Sounds reasonable, though I won't make it configurable. I'll probably just always use nanosecond precision (the highest Matroska itself supports).

**Comment by PegasusRider** [comment]
Wow!  That was pretty amazing.  Thanks :)

**Comment by mbunkus** [comment]
Well, it was trivial to implement :)

I've uploaded new [pre-builds](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/). Builds 971-7d622e2 and newer include the feature.

**Comment by PegasusRider** [comment]
I think a lot of my "suggestions" are trivial, but that tends to also push them way down on the priority list at the same time.  So, yeah, it may be weird but I'm still really impressed and appreciative.
