### ISSUE TITLE
Don't ask what to do when (starting with one file in command line) && (only the default tab is opened in the GUI)

### ISSUE THREAD

**Issue by tophf** [mbunkus/mkvtoolnix#1476]
Don't ask whether we want to append/add/new tab in case:

* When starting with one file specified on command line 
* AND only the empty default tab exists even in an already running GUI instance or this is the first `mkvtoolnix-gui` instance (in which case the tab is also empty)

Regardless of the option `When dropping files: ...`.

**Comment by mbunkus** [comment]
This has already been implemented in 94f4329174c9edbbde9acd0b93889afdc20997cd; see also #1446.
