### ISSUE TITLE
mkvtoolnix-gui remember last location (directory) on drag'n'drop

### ISSUE THREAD

**Issue by plastikat** [mbunkus/mkvtoolnix#1477]
mmg behaved in a very convenient way - when I drag'n'dropped a file onto it, it remembered the location (directory) the file was dragged from. So when I pressed the "Add" button right after dragging, it opened the directory of the last dropped file.
mkvtoolnix-gui currently only remembers the location visited using GUI (e.g. "Add" button), but not the location of drag'n'dropped files. I would really appreciate if mkvtoolnix-gui would behave the way mmg did. Thanks in advance.
Also It would be just perfect if GUI would step back one directory at a time (*not* visually, of course) when trying to open the path that doesn't exist anymore, thus finding the nearest (longest) still existing path and opening it. This behavior is implemented by some software I use and I find it very convenient too.

**Comment by mbunkus** [comment]
I'll think about the first request.

The second one has recently been implemented; see #1438.
