### ISSUE TITLE
Allow MKVPropedit type selectors in MKVMerge

### ISSUE THREAD

**Issue by ndjamena** [mbunkus/mkvtoolnix#1478]
3.2. Track headers
Track headers can be selected with a slightly more complex selector. All variations start with 'track:'. The track header properties include elements like the language code, 'default track' flag or the track's name. 

Track:n 
If the parameter n is a number then the nth track will be selected. The track order is the same that mkvmerge's --identify option outputs. 
Numbering starts at 1. 
 
track:tn 
If the parameter starts with a single character t followed by a n then the nth track of a specific track type will be selected. The track type parameter t must be one of these four characters: 'a' for an audio track, 'b' for a button track, 's' for a subtitle track and 'v' for a video track. The track order is the same that mkvmerge's --identify option outputs. 
Numbering starts at 1. 
 
track:=uid 
If the parameter starts with a '=' followed by a number uid then the track whose track UID element equals this uid. Track UIDs can be obtained with mkvinfo(1). 
 
track:\@number 
If the parameter starts with a '@' followed by a number number then the track whose track number element equals this number. Track number can be obtained with mkvinfo(1). 

It's the second one I'm mostly interested in.  It's to do with batch processing of directories without having to worry about examining every single track in every single file and building unique command lines for each.

Say you have a TV show in a directory, some of them have commentaries with accompanying subtitles and you want to remove them while muxing into a new mkv.  You can add something like this to the command line:

--audio-tracks A1 --subtitle-tracks S1

And that will remove all the extras if they happen to exist.

As an addition, would it be possible to add "track:ad" or the like to both programs to select the current default track?  For containers without any kind of default in the headers it would be the first track.  MKVPropEdit already allows selection by Track Number and Track UID which aren't exactly static values.

This is also a possibility:
--audio-tracks eng1 --subtitle-tracks eng1

with maybe:
--audio-tracks all1 --subtitle-tracks all1

It doesn't matter how it's formatted, just as long as it functions.

(Forced would be more difficult, you'd need to specify a language as well...  I'm not sure how this is supposed to work but MKVToolNix allows multiple audio tracks of the same language to be forced... and is the "default forced" supposed to be the same as the "default"?  I thought that just indicated which forced track to use by default, which would seem to be different then indicating which normal track to use by default...  shouldn't you be able to have both a "default" track AND a "default forced" track in the same file...?)

Being able to use a wildcards in --track-order would be nice too.  Something like:

--track-order -1:V\*,-1:A\*,-1:S\*

to organise with all the video tracks from all the input files first, then the audio and subtitles.  Maybe -1:V0 could select all of the video tracks instead of using an asterisk.

Being able to specify actions IF a particular track exists without throwing errors if it doesn't would be nice too.

**Comment by mbunkus** [comment]
I can understand the sentiment but that would literally require days of work as each and every input module would need code to deal with all of those selectors. I'm not willing to invest that kind of work, even though I agree that such selectors would be awesome.
