### ISSUE TITLE
No default filename in "Output"-SaveAs dialog

### ISSUE THREAD

**Issue by FCrane** [mbunkus/mkvtoolnix#1480]
Hi!

In v8.5.0 the file "file name" field in the "Select output file name" dialog is empty and contains no default filename. It used to be preset with the file name of the "Output file" edit box in the main dialog, which was very convenient. Now it's just empty.

Please fix that, because it's very annoying.

Thanks!

**Comment by mbunkus** [comment]
The output file name selection dialog only contains the value that's present in the "output file" control. If there's no value yet then the dialog won't contain anything.

The "output file" is only set if that feature is activated. So please open the preferences, select the "Merging" tab and check whether or not "automatically set the output file name" is checked.

**Comment by mbunkus** [comment]
Ah wait, I see now what you mean. I'll fix it.

**Comment by FCrane** [comment]
Great, thanks a lot!

**Comment by mbunkus** [comment]
Wrong button? :)

**Comment by mbunkus** [comment]
If you're using Windows then you can get new [pre-builds from here](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/). Build numbers 983 and higher contain the fix. I'd appreciate some feedback. Thanks.

**Comment by FCrane** [comment]
Yes, works again in build 987! Thanks a lot!

**Comment by mbunkus** [comment]
Thanks for the confirmation, for the report & you're welcome.
