### ISSUE TITLE
bug with manpages rendering (XML tags?)

### ISSUE THREAD

**Issue by bellaperez** [mbunkus/mkvtoolnix#1482]
An example (see the screenshot, too):

   Sintaxi: &lt;option&gt;--split&lt;/option&gt; &lt;literal&gt;frames:

seems XML tags generates a problem.

Regards
Toni
![man_mkvmerge](https://cloud.githubusercontent.com/assets/15173549/10614530/25618b16-775b-11e5-93e9-4d9e3a5a7aff.png)

**Comment by mbunkus** [comment]
No, there is no such bug. As you can see e.g. in the English and German translations of the man pages in HTML form contained in the latest Windows release that same section looks just fine:

![split-frames-de](https://cloud.githubusercontent.com/assets/414282/10614909/1bfd0a30-775d-11e5-9e0e-51d36e285313.png)
![split-frames-en](https://cloud.githubusercontent.com/assets/414282/10614911/1f15fee8-775d-11e5-9261-5130c0206153.png)

Can we please do this via email? You're creating a new translation, not modifying an existing one. Problems are to be expected, but the issue tracker is not the right tool for the discussion. Thanks.
