### ISSUE TITLE
Windows: Visible content

### ISSUE THREAD

**Issue by woerki** [mbunkus/mkvtoolnix#1484]
With my solution of 1440x990px (on Windows 7 x64) is the content of the window ranging outside of the displaying area. It's not possible to shrink the window width because it's fixed. 

![1](https://cloud.githubusercontent.com/assets/13499601/10635627/69db61aa-77fa-11e5-9795-63e20edb30e9.png)

-----

Only one workaround is existing when i change to full window mode. Than the right side isn't complete visible, too.

![2](https://cloud.githubusercontent.com/assets/13499601/10635631/6dc0ea4c-77fa-11e5-87e0-326c50589fd1.png)

-----

I think that users with a lower screen resolution have more problems than me with that.

**Comment by mbunkus** [comment]
Uhm, the GUI's minimum size with German translation active is currently 994x638 pixels which should fit nicely in your native resolution. This works on both Windows 7 and Windows 10 with the default themes. Therefore I'm pretty sure it's something on your end, most likely some issue with (custom?) themes.

See also #1349.

![gui-de-minwidth](https://cloud.githubusercontent.com/assets/414282/10635821/c4774286-77fb-11e5-8a82-d04f74a5a928.png)

**Comment by woerki** [comment]
You're right, after changing the skin it's working.

![3](https://cloud.githubusercontent.com/assets/13499601/10635987/d3b45c10-77fc-11e5-97af-4a8c4520e623.png)

Thanks!

**Comment by mbunkus** [comment]
You're welcome.
