### ISSUE TITLE
My HEVC raw file, which can be muxed with v8.5.0, failed muxing with v8.5.1.

### ISSUE THREAD

**Issue by jfcherng** [mbunkus/mkvtoolnix#1485]
Environment: mkvtoolnix v8.5.1 x64 Portable, Windows 7 SP1 x64

Here's a small [testcase](https://drive.google.com/file/d/0Bxtm7JFesIabWnYwbmN2UHYyZ2s/view?usp=sharing).
I had tried `mkvtoolnix-gui.exe` on 2 computers and both failed.
After the job starts, the output file just keep growing and possibly eat all disk spaces.

**Comment by mbunkus** [comment]
Thanks for the report & the test case. I can reproduce it here and will fix it.

**Comment by jfcherng** [comment]
Best MKV muxer ever ;D

**Comment by mbunkus** [comment]
I've uploaded [new pre-builds](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/). Build numbers 990 and higher include the fix.
