### ISSUE TITLE
Feature request: drop chapters.txt file into merge box

### ISSUE THREAD

**Issue by FCrane** [mbunkus/mkvtoolnix#1487]
Hi!

When dropping a chapters file into the merge box to the other source files, the GUI complains that this is not possible and should be done with the chapter editor instead, where I then have to save it to an MKV file in an extra step. Doesn't seem logical to me - it'd be great if I'd just could add the chapters file to the other source files to integrate them in the MKV file in one step.

Thanks!

**Comment by mbunkus** [comment]
This has already been implemented in v8.5.0. See #1332.
