### ISSUE TITLE
Why are the executables compiled in the src folder ?

### ISSUE THREAD

**Issue by louisabraham** [mbunkus/mkvtoolnix#1489]
Hi, after some troubles to make ./configure find my macports installation of Qt5, I finally launched ./drake.
I have been able to find the four files compiled using the LINK instruction, but why are they installed in the /src folder ? I do not think this is either logical, nor convenient, because it doesn't install the files in a location that could be found in the $PATH.
Is my installation method wrong ?

**Comment by mbunkus** [comment]
The command `drake` only compiles the binaries, it doesn't install them. That's what `drake install` is there for.
