### ISSUE TITLE
GUI: re-ordering tracks via ctrl+up/down or GUI button resets column widths

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1492]
If you move a track up or down in the track list using ctrl+up/down or the green GUI buttons the widths of the columns will be reset to the default values. (It does not happen if you move via drag&drop.) I would expect them to remain the same so I can fit all important info into it without scrolling.

Before moving:
![before](https://cloud.githubusercontent.com/assets/8726180/10814533/e1a72962-7e26-11e5-833f-2048bead6339.png)

After moving:
![after](https://cloud.githubusercontent.com/assets/8726180/10814534/e1a74bd6-7e26-11e5-8ca8-5fd267bc77f5.png)

**Comment by mbunkus** [comment]
Thanks for the report.
