### ISSUE TITLE
Muxing bug in mkvmerge v8.5.1

### ISSUE THREAD

**Issue by Barough** [mbunkus/mkvtoolnix#1493]
When muxing a HEVC file into a Matroska (mkv) container so does it just keep on running and never completes. When using v8.5.0 so does it work perfectly.

v8.5.1
http://i.imgur.com/FZmucp2.png

v8.5.0
Running - http://i.imgur.com/ZkzyHuV.png
Complete - http://i.imgur.com/pHKZlDW.png

**Comment by mbunkus** [comment]
This has already been fixed; see #1485.
