### ISSUE TITLE
split by parts based on timecodes to a single file writes wrong duration track-statistics-tag

### ISSUE THREAD

**Issue by hurda** [mbunkus/mkvtoolnix#1494]
![mkvmerge duration](https://cloud.githubusercontent.com/assets/3539609/10828411/613fdc12-7e74-11e5-808a-4b79489aa78a.png)

**Comment by mbunkus** [comment]
The file's duration is the difference between the maximum timestamp + duration of the whole file and the minimum timestamp of the whole file. That's what MediaInfo outputs as `Duration`.

However, the `DURATION` that MediaInfo outputs is the the tag for one of the tracks. A track's duration is the difference between the maximum timestamp + duration of that track and the minimum timestamp of that track. It doesn't have to match the file's duration at all.

Unfortunately MediaInfo's output looks highly confusing (no mention that all those things like `DURATION` and `NUMBER_OF_FRAMES` are track specific tags, and those tags are only listed for one track, not for all of them), but that's MediaInfo's issue.
