### ISSUE TITLE
Weird player's behavior

### ISSUE THREAD

**Issue by seiya-git** [mbunkus/mkvtoolnix#1495]
Hi, it seems to be a bug, but I don't know where it fall actually. When I mux subtitles which is longer than actual video, player (MPC-HC) prints out a subtitle's length instead of video one, though it stops after video stream finishes. Please check that behavior and fix it if there is a mkvmerge's issue. Thanks.

**Comment by mbunkus** [comment]
Neither is at fault here. The duration mkvmerge writes is the segment's duration which is defined as the difference between the highest timestamp+duration and the lowest timestamp found in that segment. If you have overly long subtitles then that content will affect the segment duration; that's just how it is. You'll have to cut your subtitles yourself if you really want the file to show the video track's duration.
