### ISSUE TITLE
dpkg-genchanges: secret key not available

### ISSUE THREAD

**Issue by simonbcn** [mbunkus/mkvtoolnix#1496]
When I compile the mkvtoolnix 8.5.1 source code with the instructions in here: https://www.bunkus.org/videotools/mkvtoolnix/source.html#debian_ubuntu_package
it compiles and it generates the `.deb` packages well but then, when it generates 2 `.changes` files, it shows an error with keys:
```
....
dpkg-deb: building package `mkvtoolnix' in `../mkvtoolnix_8.5.1-0~bunkus01_amd64.deb'.
dpkg-deb: building package `mkvtoolnix-gui' in `../mkvtoolnix-gui_8.5.1-0~bunkus01_amd64.deb'.
 dpkg-genchanges -b >../mkvtoolnix_8.5.1-0~bunkus01_amd64.changes
dpkg-genchanges: binary-only upload - not including any source code
 signfile mkvtoolnix_8.5.1-0~bunkus01_amd64.changes
gpg: skipped "Moritz Bunkus <moritz@bunkus.org>": secret key not available
gpg: [stdin]: clearsign failed: secret key not available

 dpkg-source --after-build mkvtoolnix-8.5.1
dpkg-source: info: using options from mkvtoolnix-8.5.1/debian/source/options: --compression=xz
dpkg-source: info: unapplying mkvinfo-path-in-desktop-file.patch
dpkg-buildpackage: binary only upload (no source included)
dpkg-buildpackage: warning: failed to sign .changes file
```

Is it necessary generates those `.changes` files?

**Comment by mbunkus** [comment]
The `.changes` files are generated. The warning just means that you cannot create a cryptographic signature for those `.changes` files which would prove that the packages you've just built have been built by me instead.

If you only want to install the packages yourself this doesn't concern you; just install the `.deb`s.
