### ISSUE TITLE
splitting with segment-linking and non-continuous timecodes references inextistent segments

### ISSUE THREAD

**Issue by hurda** [mbunkus/mkvtoolnix#1497]
When using mkvtoolnix-gui's "splitting by parts based on timecodes" and segment-linking in a way to cut out commercials from a recording, the segments are referencing the "cut out" and inexistent segments as previous and next segments, and the players can't link the files.

good:
00:00-01:00,01:00-02:00,02:00-03:00

![split_good](https://cloud.githubusercontent.com/assets/3539609/10886661/77c1a2e2-8183-11e5-8c8f-d98eab5523b5.png)

bad:
00:00-01:00,02:00-03:00,04:00-05:00

![split_bad](https://cloud.githubusercontent.com/assets/3539609/10886664/7f16fe66-8183-11e5-8b1d-37e4c72ea6ea.png)

**Comment by mbunkus** [comment]
Thanks for the report. That's definitely a bug.
