### ISSUE TITLE
Hevc stream muxing error

### ISSUE THREAD

**Issue by shinchiro** [mbunkus/mkvtoolnix#1498]
This error look like occur in some random hevc stream as it only happen to me today even after dozens of time muxing hevc with mkvmerge. Happen since v8.5.0 (Error: Re-rendering track headers: data_size != 0 not implemented yet) and unable to open the output files. With v8.5.2, it can play the file but it still has error (Error reading from the file 'output.mkv')

Here's sample:
https://d.maxfile.ro/omfqdvweug.mkv 

What I do:
1. Extract hevc & opus stream from the sample.mkv `mkvextract tracks sample.mkv 0:sample_video.hevc 1:sample_audio.opus`
2. Mux with following cli: `mkvmerge -o muxed.mkv sample_video.hevc -T --no-chapters --no-global-tags sample_audio.opus -D -A -T sample.mkv`

**Comment by mbunkus** [comment]
Thanks for the report. I won't have time to look into it for a couple of days, though, so please be patient.

**Comment by mbunkus** [comment]
I can reproduce the issue and will fix it. Thanks again.

**Comment by mbunkus** [comment]
Judging from that you're writing about the CLI I guess you aren't using Windows. But just in case you are I've created new [pre-builds (build numbers 01005 and higher)](https://www.bunkus.org/videotools/mkvtoolnix/windows/pre/) for you that include the fixes.

**Comment by shinchiro** [comment]
Sorry for late reply I guess. The pre-build are working fine & produce valid mkv but I got error ```Error reading from the file 'output.mkv``` Judging from multiple occurences of that error, it coming from attachments related stuff

**Comment by mbunkus** [comment]
I… don't really understand what you mean. Which application is emitting that error?

**Comment by shinchiro** [comment]
using command as 1st post when muxing:
```mkvmerge -o muxed.mkv sample_video.hevc -T --no-chapters --no-global-tags sample_audio.opus -D -A -T sample.mkv```

Here I got:
![error](https://cloud.githubusercontent.com/assets/9623615/11338302/414b30fa-922e-11e5-99b1-213deb35e656.png)

**Comment by mbunkus** [comment]
I see. I cannot reproduce it on Linux at the moment, but I'll try on Windows when I get home later tonight.

**Comment by mbunkus** [comment]
Yeah, it happens for me, too, but only on Windows. Seems this issue hasn't been fixed yet after all.

**Comment by mbunkus** [comment]
I've fixed that problem. The cause lay indeed somewhere inside Windows-specific code.

I'm currently compiling new [pre-builds](https://mkvtoolnix.download/windows/pre/). Build numbers 1014 and higher will contain the fix. Should be done in 15 minutes.

**Comment by shinchiro** [comment]
Yeah that fixed it
