### ISSUE TITLE
Default additional command line options not working?

### ISSUE THREAD

**Issue by seemsnice** [mbunkus/mkvtoolnix#1499]
I have used the earlier versions of mkvtoolnix for some time now and came across the problem that appeared after v5.8 covered in the "Improving playback compatibility with players" page. Back then after updating to v6 I had this problem with mkvs played on my LG Bluray player with fast forward and rewind not working and seek to XX:XX:XX mins taking many minutes not seconds. Research here gave the solution which I have used since successfully of adding default command line options of "--engage no_cue_duration" and "--engage no_cue_relative_position".

Until tonight when I updated to v8.5.2 and the new GUI for the first time from v7.8.0 So after a while looking at the preferences (CTL P) I found the "Default additional command line options for mkvmerge". I tried the menu options no_cue_duration and no_cue_relative_position. Merged a file and tested but it did not play correctly. So I deselected them and tried entering the full command line --engage no_cue_duration --engage no_cue_relative_position in the window. I merged and tested again and still not fixed. When displaying the cammand line log the required commands were not there.

After some searching on here and Doom9 I found a tip to enter the command on the output tab / miscellaneous / additional commands field. So tried this, merged and tested and this time all was working on the LG player OK. I found if I entered the menu from the Output Tab/Misc/Additional options section it had the same options as in the CTL P menu but with the addition of a "Save as default" tickbox. I tried this and now it seems to work OK and does show the command correctly in the display commands log and also retains as a default if the program is closed and reopened.

However, CTL P preferences default command line option is not working. I displayed the command line and the --engage etc command is not listed there. If I enter it in the misc additional commands field and then display command line it is there and does make files which play correctly.

I tried ticking other options in your CTL P default additional commands menu such as --disable-lacing and --enable-durations and again displayed the command line but none of these appeared either. Again if I set the options in the options tab they do save and appear in the command line log too. So unless I am doing something wrong this additional command option does not appear to work when set JUST in the CTL P options.

If it isn't a bug and I am just missing something please advise.

Sorry this is long but it is difficult to explain accurately but if you need more info or cannot reproduce this issue let me know.

**Comment by mbunkus** [comment]
The default additional command line options entered in the preferences only apply to mux settings created afterwards. They're not applied to mux settings that are currently opened or that are loaded from setting files.

Therefore I consider this issue to be invalid.

**Comment by seemsnice** [comment]
I understand your point but because the new additional default commands do not appear in the display command line and are not used even if you create and run several new mux jobs I find this confusing and unlike many other programs that incorporate settings changes immediately.

In fact after further testing tonight I found that any modified command line settings only start to be used if the program is closed and reopened. Then the commands become defaults and appear in the display command line log.

Just a thought maybe you could add some text to the CTL P Preferences Menu to say changes only take place after program closed and reopened?

Thanks again for your program and work.

**Comment by mbunkus** [comment]
The additional command line parameters are properties of the mux settings. They aren't global and don't apply to all settings. You can see the mux settings' additional CLI parameters on the "output" tab.

My policy is that changes in the preferences must not modify existing mux settings, neither ones stored on disk nor the ones currently open in the GUI. For example, changing the "default subtitle language" in the preferences doesn't affect subtitle tracks already added to mux settings. Anything else would be highly confusing to the user.

That's the reason that changing the default additional command line parameters in the preferences doesn't affect the currently open mux settings.

BTW: You can create new mux settings without restarting the program; use "New" from the "Merge" menu.

**Comment by hurda** [comment]
Just wanted to add that the deprecated mmg was adding additional commandline-options to the current merge-settings without the need to start a new merge-job.
I guess that was due to mmg being a "single job"-program, whereas mkvtoolnix-gui can have multiple merge-settings open at any given time.

**Comment by mbunkus** [comment]
In mmg the additional command line options weren't part of the merge settings. Instead they were part of the global configuration. As it may make sense to use different additional command line options for different jobs MKVToolNix GUI associates them with the merge settings now. Hence changes in defaults not affecting existing configurations.
