### ISSUE TITLE
Split by Chapter splits too early, includes name of 1st chapter in next file

### ISSUE THREAD

**Issue by 73ChargerFan** [mbunkus/mkvtoolnix#1500]
Thank you for this feature. I'm using it to split a whole-dvd video into the 3 TV episodes.  (MPEG 2, AC3)  However, the 2nd split is 0.8 seconds early, and the first two episodes list the first chapter of the following episode.

Source is the original dvd VOB files (additional parts added), with output option "Split mode before chapters" 5, 9 using MKVToolNix GUI x64 v8.5.4, Windows 7 x64, tested with MPC-BE v 1.4.2 build 677.  Chapters.txt & MediaInfo v0.7.69 reports listed below (I don't have permission to attach files.)

Episode 1 is 0:23:19.465 long and lists chapters 1 through 5, but it should only be 1 through 4.  Even Chapter 5's time code is beyond the end of the video.  MPC-BE reports 41942 frames @ 29.970, but MediaInfo says 43749 frames.  I'm not sure if that means anything.

Episode 2 is 0:23:37.583 long which means it was split 0.819 seconds early at 0:46:57.048 and lists chapters 5 through 9, but shouldn't include chapter 9.  MPC-BE reports 42485 frames @ 29.970, while MediaInfo says 44313 frames.

Episode 3 correctly lists chapters 9 through 12, although it was split too early and so includes a bit of ending credits music of episode 2.

Note:  I don't know why MediaInfo reports a different number of frames than MPC-BE, but I can investigate that separately with the appropriate developers.

```
==========================================================================
Chapters.txt
---------------

CHAPTER01=00:00:00.000
CHAPTER01NAME=Lane Change
CHAPTER02=00:01:02.600
CHAPTER02NAME=Part 1
CHAPTER03=00:12:04.933
CHAPTER03NAME=Part 2
CHAPTER04=00:22:46.400
CHAPTER04NAME=End Credits
CHAPTER05=00:23:19.600
CHAPTER05NAME=Blue Man Down
CHAPTER06=00:24:21.367
CHAPTER06NAME=Part 1
CHAPTER07=00:36:56.533
CHAPTER07NAME=Part 2
CHAPTER08=00:46:24.500
CHAPTER08NAME=End Credits
CHAPTER09=00:46:57.867
CHAPTER09NAME=The 21 Inch Sun
CHAPTER10=00:47:59.834
CHAPTER10NAME=Part 1
CHAPTER11=00:56:39.867
CHAPTER11NAME=Part 2
CHAPTER12=01:09:07.867
CHAPTER12NAME=End Credits

==========================================================================
MediaInfo Episode 1
-------------------------

General
Unique ID                                : 170628908236020834603798755077267244067 (0x805DEEB020861013A8114206C4D9C423)
Complete name                            : J:\1\2x13  Lane Change.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 1.28 GiB
Duration                                 : 23mn 19s
Overall bit rate mode                    : Variable
Overall bit rate                         : 7 824 Kbps
Encoded date                             : UTC 2015-11-07 19:37:32
Writing application                      : mkvmerge v8.5.2 ('Crosses') 64bit
Writing library                          : libebml v1.3.3 + libmatroska v1.4.4
DURATION                                 : 00:23:19.968000000
NUMBER_OF_FRAMES                         : 43749
NUMBER_OF_BYTES                          : 67198464
_STATISTICS_WRITING_APP                  : mkvmerge v8.5.2 ('Crosses') 64bit
_STATISTICS_WRITING_DATE_UTC             : 2015-11-07 19:37:32
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Video
ID                                       : 1
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings, BVOP                    : No
Format settings, Matrix                  : Custom
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 23mn 19s
Bit rate mode                            : Variable
Bit rate                                 : 7 284 Kbps
Maximum bit rate                         : 9 204 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 29.970 fps
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.703
Time code of first frame                 : 00:59:59;15
Time code source                         : Group of pictures header
Stream size                              : 1.19 GiB (93%)
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 23mn 19s
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 64.1 MiB (5%)
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : en:Lane Change
00:01:02.600                             : en:Part 1
00:12:04.933                             : en:Part 2
00:22:46.400                             : en:End Credits
00:23:19.600                             : en:Blue Man Down

==========================================================================
MediaInfo Episode 2
-------------------------

General
Unique ID                                : 244702958015936869363565625170495113758 (0xB818134F880879278449CE31534D8A1E)
Complete name                            : J:\1\2x14  Blue Man Down.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 1.30 GiB
Duration                                 : 23mn 38s
Overall bit rate mode                    : Variable
Overall bit rate                         : 7 873 Kbps
Encoded date                             : UTC 2015-11-07 19:37:32
Writing application                      : mkvmerge v8.5.2 ('Crosses') 64bit
Writing library                          : libebml v1.3.3 + libmatroska v1.4.4
DURATION                                 : 00:23:38.016000000
NUMBER_OF_FRAMES                         : 44313
NUMBER_OF_BYTES                          : 68064768
_STATISTICS_WRITING_APP                  : mkvmerge v8.5.2 ('Crosses') 64bit
_STATISTICS_WRITING_DATE_UTC             : 2015-11-07 19:37:32
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Video
ID                                       : 1
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings, BVOP                    : No
Format settings, Matrix                  : Custom
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 23mn 38s
Bit rate mode                            : Variable
Bit rate                                 : 7 332 Kbps
Maximum bit rate                         : 9 204 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 29.970 fps
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.708
Time code of first frame                 : 01:23:19;12
Time code source                         : Group of pictures header
Stream size                              : 1.21 GiB (93%)
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 23mn 38s
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Delay relative to video                  : 3ms
Stream size                              : 64.9 MiB (5%)
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : en:Blue Man Down
00:01:01.402                             : en:Part 1
00:13:36.568                             : en:Part 2
00:23:04.535                             : en:End Credits
00:23:37.902                             : en:The 21 Inch Sun

==========================================================================
MediaInfo Episode 3
-------------------------

General
Unique ID                                : 219362708581899572101837265016017463313 (0xA507B88DD182FD258DD1667AF9892811)
Complete name                            : J:\1\2x15  The 21 Inch Sun.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 1.25 GiB
Duration                                 : 22mn 42s
Overall bit rate mode                    : Variable
Overall bit rate                         : 7 881 Kbps
Encoded date                             : UTC 2015-11-07 19:37:32
Writing application                      : mkvmerge v8.5.2 ('Crosses') 64bit
Writing library                          : libebml v1.3.3 + libmatroska v1.4.4
DURATION                                 : 00:22:42.560000000
NUMBER_OF_FRAMES                         : 42580
NUMBER_OF_BYTES                          : 65402880
_STATISTICS_WRITING_APP                  : mkvmerge v8.5.2 ('Crosses') 64bit
_STATISTICS_WRITING_DATE_UTC             : 2015-11-07 19:37:32
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Video
ID                                       : 1
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings, BVOP                    : No
Format settings, Matrix                  : Custom
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 22mn 42s
Bit rate mode                            : Variable
Bit rate                                 : 7 341 Kbps
Maximum bit rate                         : 9 204 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 29.970 fps
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.709
Time code of first frame                 : 01:23:36;12
Time code source                         : Group of pictures header
Stream size                              : 1.16 GiB (93%)
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 22mn 42s
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Delay relative to video                  : 2ms
Stream size                              : 62.4 MiB (5%)
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : en:The 21 Inch Sun
00:01:01.852                             : en:Part 1
00:09:41.885                             : en:Part 2
00:22:09.885                             : en:End Credits

==========================================================================
MediaInfo - entire file muxed with "split by chapters"
turned off for comparison purposes
------------------------------------------------------

General
Unique ID                                : 220457485019491783000751343166326669779 (0xA5DA91331FA322A5A213528333B181D3)
Complete name                            : J:\1\all.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 3.83 GiB
Duration                                 : 1h 9mn
Overall bit rate mode                    : Variable
Overall bit rate                         : 7 860 Kbps
Encoded date                             : UTC 2015-11-07 20:52:14
Writing application                      : mkvmerge v8.5.2 ('Crosses') 64bit
Writing library                          : libebml v1.3.3 + libmatroska v1.4.4
DURATION                                 : 01:09:40.544000000
NUMBER_OF_FRAMES                         : 130642
NUMBER_OF_BYTES                          : 200666112
_STATISTICS_WRITING_APP                  : mkvmerge v8.5.2 ('Crosses') 64bit
_STATISTICS_WRITING_DATE_UTC             : 2015-11-07 20:52:14
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Video
ID                                       : 1
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings, BVOP                    : No
Format settings, Matrix                  : Custom
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 1h 9mn
Bit rate mode                            : Variable
Bit rate                                 : 7 319 Kbps
Maximum bit rate                         : 9 204 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 29.970 fps
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.707
Time code of first frame                 : 00:59:59;15
Time code source                         : Group of pictures header
Stream size                              : 3.56 GiB (93%)
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 9mn
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 191 MiB (5%)
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : en:Lane Change
00:01:02.600                             : en:Part 1
00:12:04.933                             : en:Part 2
00:22:46.400                             : en:End Credits
00:23:19.600                             : en:Blue Man Down
00:24:21.367                             : en:Part 1
00:36:56.533                             : en:Part 2
00:46:24.500                             : en:End Credits
00:46:57.867                             : en:The 21 Inch Sun
00:47:59.834                             : en:Part 1
00:56:39.867                             : en:Part 2
01:09:07.867                             : en:End Credits

==========================================================================
```

**Comment by mbunkus** [comment]
Thanks for the report. Please be aware that mkvmerge can only split on key frames. If there is no video key frame at the timestamp of the requested split point (chapter's timestamp) then mkvmerge will select the following video key frame for splitting. Of course in such a case the chapter entry will be included in the previous file because it does indeed belong there (from the point of view of the content).

If you don't have key frames on chapter timestamps then you'll have to specify the split point timestamps manually instead of using the "split by chapters" functionality.

So please verify where the key frames are in the file you're trying to split, e.g. with mkvinfo (e.g. `mkvinfo -s -r output.txt yourfile.mkv`) or with mkvextract (by extracting the timestamps for the video track).

**Comment by 73ChargerFan** [comment]
And thank you for looking at this.  Bug reports are how I can give back to open source projects like mkvmerge, and I totally rely it so I wanted to help.  And this feature is really useful. 

The first thing I noticed was that, from a conceptual view point, "split before chapter xxx" shouldn't include "chapter xxx" in the resulting file (that is the chapter listing.)  However, I think the time code of the extra chapter in the first episode is even past the end of the file, as determined by MPC-BE.

The timing issue came second, and I'm aware that key frames, AC3 frame size, etc. will limit where a split can occur.  I'm not an expert, though the second split is 800ms early, which I thought was kind of large.

I don't expect key frames to be at chapter time codes, because they were determined by the author of the DVD.

I used MKVToolNix GUI to convert the VOB files directly into mkv files.  One was "all.mkv", then I turned on the "split by chapters" feature but with all other options identical.  Attached is the MediaInfo report of the first VOB file which was used as the source, and a trimmed down copy of the timing file (mkvinfo -s -r) for "all.mkv" which shows I B & P frames near the time of the desired splits.

Have a great week!

- Anthony Maffia

----- Original Message -----From: Moritz Bunkus <notifications@github.com>To: mbunkus/mkvtoolnix <mkvtoolnix@noreply.github.com>Cc: 73ChargerFan <anthony_maffia@comcast.net>Sent: Sun, 08 Nov 2015 17:50:55 -0000 (UTC)Subject: Re: [mkvtoolnix] Split by Chapter splits too early, includes name of 1st chapter in next file (#1500)

Thanks for the report. Please be aware that mkvmerge can only split on key frames. If there is no video key frame at the timestamp of the requested split point (chapter's timestamp) then mkvmerge will select the following video key frame for splitting. Of course in such a case the chapter entry will be included in the previous file because it does indeed belong there (from the point of view of the content).
If you don't have key frames on chapter timestamps then you'll have to specify the split point timestamps manually instead of using the "split by chapters" functionality.
So please verify where the key frames are in the file you're trying to split, e.g. with mkvinfo (e.g. mkvinfo -s -r output.txt yourfile.mkv) or with mkvextract (by extracting the timestamps for the video track).
&mdash;Reply to this email directly or view it on GitHub.





﻿Track 1: video, codec ID: V_MPEG2, mkvmerge/mkvextract track ID: 0, default duration: 16.683ms (59.940 frames/fields per second for a video track), language: und, pixel width: 720, pixel height: 480, display width: 640, display height: 480
Track 2: audio, codec ID: A_AC3, mkvmerge/mkvextract track ID: 1, default duration: 32.000ms (31.250 frames/fields per second for a video track), language: und, sampling freq: 48000, channels: 6


...
... Lots of lines deleted
...


I frame, track 2, timecode 1398976 (00:23:18.976), size 1536, adler 0x4422f261
I frame, track 2, timecode 1398976 (00:23:18.976), size 1536, adler 0x9ef3fd5f
P frame, track 1, timecode 1399064 (00:23:19.064), duration 33.000, size 288, adler 0x319d1af1
B frame, track 1, timecode 1398998 (00:23:18.998), duration 33.000, size 288, adler 0x253f2456
B frame, track 1, timecode 1399031 (00:23:19.031), duration 33.000, size 288, adler 0x521d2397
P frame, track 1, timecode 1399164 (00:23:19.164), duration 33.000, size 288, adler 0xebea1ab2
B frame, track 1, timecode 1399098 (00:23:19.098), duration 33.000, size 288, adler 0xdf8c2417
B frame, track 1, timecode 1399131 (00:23:19.131), duration 33.000, size 288, adler 0x266c2457
I frame, track 2, timecode 1399232 (00:23:19.232), size 1536, adler 0x5dbafe5e
I frame, track 2, timecode 1399232 (00:23:19.232), size 1536, adler 0xfc720431
I frame, track 2, timecode 1399232 (00:23:19.232), size 1536, adler 0x44e5ec11
I frame, track 2, timecode 1399232 (00:23:19.232), size 1536, adler 0x8907ea1c
I frame, track 2, timecode 1399232 (00:23:19.232), size 1536, adler 0x01ede383
I frame, track 2, timecode 1399232 (00:23:19.232), size 1536, adler 0x5a52e075
I frame, track 2, timecode 1399232 (00:23:19.232), size 1536, adler 0xf1f0de08
I frame, track 2, timecode 1399232 (00:23:19.232), size 1536, adler 0x3750dd9b
P frame, track 1, timecode 1399265 (00:23:19.265), duration 33.000, size 288, adler 0xc0391b72
B frame, track 1, timecode 1399198 (00:23:19.198), duration 33.000, size 288, adler 0x99e823d8
B frame, track 1, timecode 1399231 (00:23:19.231), duration 33.000, size 288, adler 0xe0b92418
P frame, track 1, timecode 1399365 (00:23:19.365), duration 33.000, size 288, adler 0x7a951b33
B frame, track 1, timecode 1399298 (00:23:19.298), duration 33.000, size 288, adler 0x54442399
B frame, track 1, timecode 1399331 (00:23:19.331), duration 33.000, size 288, adler 0x9b1523d9
I frame, track 1, timecode 1399465 (00:23:19.465), duration 33.000, size 7645, adler 0xff42173e
B frame, track 1, timecode 1399398 (00:23:19.398), duration 33.000, size 288, adler 0x50f02396
B frame, track 1, timecode 1399431 (00:23:19.431), duration 33.000, size 288, adler 0x97c123d6
I frame, track 2, timecode 1399488 (00:23:19.488), size 1536, adler 0x45cef5a6
I frame, track 2, timecode 1399488 (00:23:19.488), size 1536, adler 0x4fb3e9de
I frame, track 2, timecode 1399488 (00:23:19.488), size 1536, adler 0xb915eefa
I frame, track 2, timecode 1399488 (00:23:19.488), size 1536, adler 0x007ddd8d
I frame, track 2, timecode 1399488 (00:23:19.488), size 1536, adler 0xfa4de091
I frame, track 2, timecode 1399488 (00:23:19.488), size 1536, adler 0x6e79dea6
I frame, track 2, timecode 1399488 (00:23:19.488), size 1536, adler 0xaa32e95f
I frame, track 2, timecode 1399488 (00:23:19.488), size 1536, adler 0xd26af68e
P frame, track 1, timecode 1399565 (00:23:19.565), duration 33.000, size 288, adler 0x319d1af1
B frame, track 1, timecode 1399498 (00:23:19.498), duration 33.000, size 288, adler 0x253f2456
B frame, track 1, timecode 1399531 (00:23:19.531), duration 33.000, size 288, adler 0x521d2397
P frame, track 1, timecode 1399665 (00:23:19.665), duration 33.000, size 288, adler 0xebea1ab2
B frame, track 1, timecode 1399598 (00:23:19.598), duration 33.000, size 288, adler 0xdf8c2417
B frame, track 1, timecode 1399632 (00:23:19.632), duration 33.000, size 288, adler 0x266c2457
I frame, track 2, timecode 1399744 (00:23:19.744), size 1536, adler 0x4d13f462
I frame, track 2, timecode 1399744 (00:23:19.744), size 1536, adler 0x96b7dc41
I frame, track 2, timecode 1399744 (00:23:19.744), size 1536, adler 0x8647ec45
I frame, track 2, timecode 1399744 (00:23:19.744), size 1536, adler 0x8530e7ea
I frame, track 2, timecode 1399744 (00:23:19.744), size 1536, adler 0x2a56dd28
I frame, track 2, timecode 1399744 (00:23:19.744), size 1536, adler 0xbf9a0176
I frame, track 2, timecode 1399744 (00:23:19.744), size 1536, adler 0x9274e2b1
P frame, track 1, timecode 1399765 (00:23:19.765), duration 33.000, size 288, adler 0xc0391b72
B frame, track 1, timecode 1399698 (00:23:19.698), duration 33.000, size 288, adler 0x99e823d8
B frame, track 1, timecode 1399732 (00:23:19.732), duration 33.000, size 288, adler 0xe0b92418
P frame, track 1, timecode 1399865 (00:23:19.865), duration 33.000, size 288, adler 0x7a951b33
B frame, track 1, timecode 1399798 (00:23:19.798), duration 33.000, size 288, adler 0x54442399
B frame, track 1, timecode 1399832 (00:23:19.832), duration 33.000, size 288, adler 0x9b1523d9
I frame, track 1, timecode 1399965 (00:23:19.965), duration 33.000, size 7645, adler 0x39f616d7
B frame, track 1, timecode 1399898 (00:23:19.898), duration 33.000, size 288, adler 0x50f02396
B frame, track 1, timecode 1399932 (00:23:19.932), duration 33.000, size 288, adler 0x97c123d6
I frame, track 2, timecode 1399968 (00:23:19.968), size 1536, adler 0xa5abed38
I frame, track 2, timecode 1399968 (00:23:19.968), size 1536, adler 0x766cf26e
I frame, track 2, timecode 1399968 (00:23:19.968), size 1536, adler 0x2493eb69
I frame, track 2, timecode 1399968 (00:23:19.968), size 1536, adler 0x8190e804
I frame, track 2, timecode 1399968 (00:23:19.968), size 1536, adler 0xb453e7ab
I frame, track 2, timecode 1399968 (00:23:19.968), size 1536, adler 0x176fef02
I frame, track 2, timecode 1399968 (00:23:19.968), size 1536, adler 0xa8ebfc41
I frame, track 2, timecode 1399968 (00:23:19.968), size 1536, adler 0x0022f32e
P frame, track 1, timecode 1400065 (00:23:20.065), duration 33.000, size 288, adler 0x319d1af1
B frame, track 1, timecode 1399999 (00:23:19.999), duration 33.000, size 288, adler 0x253f2456
B frame, track 1, timecode 1400032 (00:23:20.032), duration 33.000, size 288, adler 0x521d2397
P frame, track 1, timecode 1400165 (00:23:20.165), duration 33.000, size 288, adler 0xebea1ab2



...
... Lots of lines deleted
...



I frame, track 2, timecode 2817248 (00:46:57.248), size 1536, adler 0x293ae9d6
I frame, track 2, timecode 2817248 (00:46:57.248), size 1536, adler 0xbd32dfa3
I frame, track 2, timecode 2817248 (00:46:57.248), size 1536, adler 0xf394d553
P frame, track 1, timecode 2817281 (00:46:57.281), duration 33.000, size 31343, adler 0x9779c6cf
B frame, track 1, timecode 2817214 (00:46:57.214), duration 33.000, size 12368, adler 0xb0db6b48
B frame, track 1, timecode 2817248 (00:46:57.248), duration 33.000, size 16194, adler 0xf76f1b02
P frame, track 1, timecode 2817381 (00:46:57.381), duration 33.000, size 32431, adler 0x3e0d8a15
B frame, track 1, timecode 2817314 (00:46:57.314), duration 33.000, size 13705, adler 0x5b0bf050
B frame, track 1, timecode 2817348 (00:46:57.348), duration 33.000, size 8466, adler 0x13c49652
I frame, track 1, timecode 2817481 (00:46:57.481), duration 33.000, size 146533, adler 0x4672d274
B frame, track 1, timecode 2817415 (00:46:57.415), duration 33.000, size 13565, adler 0xc83dc93d
B frame, track 1, timecode 2817448 (00:46:57.448), duration 33.000, size 5915, adler 0x0eae335a
I frame, track 2, timecode 2817504 (00:46:57.504), size 1536, adler 0x0d5ee48c
I frame, track 2, timecode 2817504 (00:46:57.504), size 1536, adler 0x6bd3d082
I frame, track 2, timecode 2817504 (00:46:57.504), size 1536, adler 0x047bdc9d
I frame, track 2, timecode 2817504 (00:46:57.504), size 1536, adler 0x63bce160
I frame, track 2, timecode 2817504 (00:46:57.504), size 1536, adler 0x589ac4c5
I frame, track 2, timecode 2817504 (00:46:57.504), size 1536, adler 0xbbc2dff1
I frame, track 2, timecode 2817504 (00:46:57.504), size 1536, adler 0xed3ee873
I frame, track 2, timecode 2817504 (00:46:57.504), size 1536, adler 0x0334e89f
P frame, track 1, timecode 2817581 (00:46:57.581), duration 33.000, size 31742, adler 0x58dff65b
B frame, track 1, timecode 2817515 (00:46:57.515), duration 33.000, size 12685, adler 0x56f69446
B frame, track 1, timecode 2817548 (00:46:57.548), duration 33.000, size 12186, adler 0x22f504f9
P frame, track 1, timecode 2817681 (00:46:57.681), duration 33.000, size 31754, adler 0xed621fce
B frame, track 1, timecode 2817615 (00:46:57.615), duration 33.000, size 15040, adler 0xed6a9a4d
B frame, track 1, timecode 2817648 (00:46:57.648), duration 33.000, size 14591, adler 0x8201d260
I frame, track 2, timecode 2817760 (00:46:57.760), size 1536, adler 0x8631e3c9
I frame, track 2, timecode 2817760 (00:46:57.760), size 1536, adler 0xdb45e115
I frame, track 2, timecode 2817760 (00:46:57.760), size 1536, adler 0x8a91dfac
I frame, track 2, timecode 2817760 (00:46:57.760), size 1536, adler 0xfd28d6f5
I frame, track 2, timecode 2817760 (00:46:57.760), size 1536, adler 0xcc22fb32
I frame, track 2, timecode 2817760 (00:46:57.760), size 1536, adler 0xed20e62a
I frame, track 2, timecode 2817760 (00:46:57.760), size 1536, adler 0x220ceb0f
P frame, track 1, timecode 2817782 (00:46:57.782), duration 33.000, size 104738, adler 0x9ca67bec
B frame, track 1, timecode 2817715 (00:46:57.715), duration 33.000, size 13124, adler 0xcf9e8250
B frame, track 1, timecode 2817748 (00:46:57.748), duration 33.000, size 1422, adler 0xd06d1b50
P frame, track 1, timecode 2817882 (00:46:57.882), duration 33.000, size 9933, adler 0x15e4ce0d
B frame, track 1, timecode 2817815 (00:46:57.815), duration 33.000, size 1866, adler 0x56f60070
B frame, track 1, timecode 2817848 (00:46:57.848), duration 33.000, size 1455, adler 0x93ffd6d1
I frame, track 1, timecode 2817982 (00:46:57.982), duration 33.000, size 7867, adler 0x5bac5d8c
B frame, track 1, timecode 2817915 (00:46:57.915), duration 33.000, size 955, adler 0x55787a84
B frame, track 1, timecode 2817948 (00:46:57.948), duration 33.000, size 990, adler 0x319d98ac
I frame, track 2, timecode 2817984 (00:46:57.984), size 1536, adler 0xc0b7def7
I frame, track 2, timecode 2817984 (00:46:57.984), size 1536, adler 0x891fe79d
I frame, track 2, timecode 2817984 (00:46:57.984), size 1536, adler 0xbeeafb5e
I frame, track 2, timecode 2817984 (00:46:57.984), size 1536, adler 0xa456fe76
I frame, track 2, timecode 2817984 (00:46:57.984), size 1536, adler 0x7aeeeaf9
I frame, track 2, timecode 2817984 (00:46:57.984), size 1536, adler 0x94f3ed22
I frame, track 2, timecode 2817984 (00:46:57.984), size 1536, adler 0x9fe5efdb
I frame, track 2, timecode 2817984 (00:46:57.984), size 1536, adler 0x91a5e636
P frame, track 1, timecode 2818082 (00:46:58.082), duration 33.000, size 994, adler 0x02257e28
B frame, track 1, timecode 2818015 (00:46:58.015), duration 33.000, size 1247, adler 0x747c062d

General
Complete name                            : D:\stuff\VIDEO_TS\VTS_01_1.VOB
Format                                   : MPEG-PS
File size                                : 1 024 MiB
Duration                                 : 17mn 32s
Overall bit rate mode                    : Variable
Overall bit rate                         : 8 163 Kbps

Video
ID                                       : 224 (0xE0)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=3, N=15
Duration                                 : 17mn 32s
Bit rate mode                            : Variable
Bit rate                                 : 7 425 Kbps
Maximum bit rate                         : 9 204 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 29.970 fps
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.717
Time code of first frame                 : 00:59:59;15
Time code source                         : Group of pictures header
Stream size                              : 931 MiB (91%)

Audio #1
ID                                       : 189 (0xBD)-128 (0x80)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Muxing mode                              : DVD-Video
Duration                                 : 17mn 31s
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 48.1 MiB (5%)

Audio #2
ID                                       : 189 (0xBD)-129 (0x81)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Muxing mode                              : DVD-Video
Duration                                 : 17mn 31s
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 24.1 MiB (2%)

Text
ID                                       : 189 (0xBD)-32 (0x20)
Format                                   : RLE
Format/Info                              : Run-length encoding
Muxing mode                              : DVD-Video

Menu

**Comment by mbunkus** [comment]
Unfortunately attachments sent via email to Github won't show up here (as Github doesn't support arbitrary attachments), neither are they included in the notification email Github has sent me. Can you please upload those attachments to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server)? Thanks.

**Comment by 73ChargerFan** [comment]
I uploaded to your FTP site all text files as "anthony_maffia_1500.zip"

----- Original Message -----From: Moritz Bunkus <notifications@github.com>To: mbunkus/mkvtoolnix <mkvtoolnix@noreply.github.com>Cc: 73ChargerFan <anthony_maffia@comcast.net>Sent: Mon, 09 Nov 2015 08:02:25 -0000 (UTC)Subject: Re: [mkvtoolnix] Split by Chapter splits too early, includes name of 1st chapter in next file (#1500)

Unfortunately attachments sent via email to Github won't show up here (as Github doesn't support arbitrary attachments), neither are they included in the notification email Github has sent me. Can you please upload those attachments to my FTP server? Thanks.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by mbunkus** [comment]
Thanks.

**Comment by mbunkus** [comment]
Well, there's not a lot I can reasonably do about this.

The split point is 23:19.600, but there's no key frame at that position. The surrounding key frames are at 23:19.465 (too early) and at 23:19.965 (the one chosen by mkvmerge).

As 23:19.965 is located after the chapter timestamp the chapter will be included in the earlier file.

Note that the first file's duration is NOT 23:19.465 even if your player says so. 23:19.465 is just the location of the last key frame in the file. There are, however, more non-key frames afterwards, and they determine the file's length, not only the key frame. The duration more like 23:19:968 (and MediaInfo agrees with that).

Unfortunately changing all this to make it more human-friendly would require a lot of time and result in a more or less brittle process, time I'm not currently willing to invest. Therefore I'm closing this as WONTFIX. Sorry.
