### ISSUE TITLE
--without-gettext doesn't prevent libintl.so from being linked with

### ISSUE THREAD

**Issue by yurivict** [mbunkus/mkvtoolnix#1501]
Seeing this in FreeBSD port.

mkvtoolnix-8.5.2

**Comment by mbunkus** [comment]
If you configure `--without-gettext` then configure will not use `pkg-config` and query for libintl. However, other libraries used by MKVToolNix may very well use libintl, and that's nothing that I can prevent.

So please `grep -- -lintl build-config` after configuring in order to see where that dependencies creeps in.

**Comment by yurivict** [comment]
No, the executable itself still links to libintl.so.

**Comment by yurivict** [comment]
The file build-config still has LIBINTL_LIBS = -lintl.
And config.log still has this:
```
configure:10863: checking for gettext in -lintl
configure:10888: clang -o conftest -O2 -pipe -fno-omit-frame-pointer  -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing -I/usr/local/include -fno-omit-frame-pointer -I/usr/local/include -DLIBICONV_PLUG -I/usr/local/include  -L/usr/local/lib -fstack-protector -L/usr/local/lib conftest.c -lintl  -liconv   >&5
configure:10888: $? = 0
configure:10897: result: yes
configure:10911: checking libintl.h usability
configure:10911: clang -c -O2 -pipe -fno-omit-frame-pointer  -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing -I/usr/local/include -fno-omit-frame-pointer -I/usr/local/include -DLIBICONV_PLUG -I/usr/local/include conftest.c >&5
configure:10911: $? = 0
configure:10911: result: yes
configure:10911: checking libintl.h presence
configure:10911: clang-cpp -fno-omit-frame-pointer -I/usr/local/include -DLIBICONV_PLUG -I/usr/local/include conftest.c
configure:10911: $? = 0
configure:10911: result: yes
configure:10911: checking for libintl.h
configure:10911: result: yes
```

**Comment by mbunkus** [comment]
Hmm yeah, you're right. Please give [this patch a try](https://www.bunkus.org/misc/issue-1501-001.diff). You'll need autoconf/automake and run `autogen.sh` after applying and before running `configure`.

**Comment by yurivict** [comment]
Yes, this patch causes libintl to disappear in all places.

**Comment by mbunkus** [comment]
Thanks for the confirmation.

**Comment by remuxer32** [comment]
**@Mosu**

A little reminder: you forgot to add a label [**res:fixed/implemented**] for this issue which was successfully fixed.
