### ISSUE TITLE
MKV MERGE Gui ?

### ISSUE THREAD

**Issue by InternalKing** [mbunkus/mkvtoolnix#1502]
Why new version not added mkv merge gui ?

We want an addition in the new versiyons =)

and thx for this software.. :)

best regards

**Comment by hurda** [comment]
mmg has been replaced by mkvtoolnix-gui.

**Comment by remuxer32** [comment]
**@InternalKing**

As hurda said: the old GUI (mkvmerge GUI) has been replaced by the new successor and will never come back. Here you can read more details: https://github.com/mbunkus/mkvtoolnix/wiki/MKVToolNix-GUI

**Comment by mbunkus** [comment]
What remuxer32 said :)

**Comment by 3F** [comment]
> ... powerful MKVToolNix GUI

hmm., the mmg is more flexible, or ok, simply a more convenient.

the new GUI is much more heavy for the most popular operations (for me of course :)) such as the Splitting or removing/adding tracks from single or different media files :( 

Moreover, I see the all same features. But now it's not a compact with strange animation effects, still uncomfortable managing of queue and completely uncomfortable `Job output` (for single task at least)

I loved mmg for quick and powerful managing of media containers... well, I still love this project :)

**Comment by mbunkus** [comment]
You can turn the animations off in MKVToolNix GUI's preferences. Also in the preferences you can configure it to switch to the job output tool automatically when you start a job in the merge tool. Yet another thing you can change there is the layout from a "properties on the right" one to "properties at the bottom".

Those settings (and others!) will get you closer to how mmg worked.

**Comment by 3F** [comment]
ahah :) I did not noticed the "`Предпочтения`" with my selected lang by default (in most cases it's the 'Опции' or 'Настройки' or 'Конфигурация' etc.)

ok, I disabled animation & the right selector of tool, +added switching to the job output.
however the `job output` (alt + 8) & Properties from `merge tool` (alt + 1) still are uncomfortable in comparison with mmg

for example:
*I'm stuck... the 'Input' tab from 'merge tool' where are you ?*

![job_output_small](https://cloud.githubusercontent.com/assets/3246589/11868771/671f070c-a4cb-11e5-9541-2126880ee759.png)

ah where you are - `alt + 1` :)

and Properties from here:

![input_small](https://cloud.githubusercontent.com/assets/3246589/11868445/e2d4be94-a4c8-11e5-8dd5-ea8f074ee8d3.png)

the right side pyramid - just wow :) 
In the most cases I don't want use the Properties of tracks, but this requires ~54% unnecessary of width and in most cases this always is inactive - dead zone. Yes, I also see the new output properties from next tab, but... I don't know -_-

anyway, thanks for project!
