### ISSUE TITLE
Opening mtxcfg file opens the GUI in a non-empty window

### ISSUE THREAD

**Issue by LeMoiFR** [mbunkus/mkvtoolnix#1504]
If I open a .pdf document or .doc document without the original program being opened, it just opens the program in a single window or tab with the opened file.
When I do the same with mtxcfg file, it opens the MKVToolnixGUI with an empty tab AND the mtxcfg file in another tab. Would it be possible to only have one tab opened in this paritcular case?
Thanks in advance

**Comment by mbunkus** [comment]
Thanks for opening an issue for it.
