### ISSUE TITLE
Feature request: Show attachments in the Attachments tab, not in the track listing (GUI)

### ISSUE THREAD

**Issue by Varshnyar** [mbunkus/mkvtoolnix#1505]
I think the attachments tab could be more useful if attachments contained in a pre-muxed mkv loads directly in there, thus the user could edit the settings for each attachment.

Another adventage of this: The track listing might look cleaner and not so confusing when there are a lot of attachments.

**Comment by mbunkus** [comment]
Thanks for the suggestion, but this is a design decision that I've made deliberately. All existing content from input files is supposed to be located on the "input" tab. This won't change.

**Comment by ndjamena** [comment]
Assuming letting users know they're there is the goal, how about an option to shift all attachments to the attachment tab manually.

**Comment by mbunkus** [comment]
No, sorry. I don't want to spend any time on that.
