### ISSUE TITLE
Subtitle Language Recognition

### ISSUE THREAD

**Issue by duiveldoder** [mbunkus/mkvtoolnix#1506]
When I use mkvtoolnix to extract vob subtitles, it recognizes the language and writes down the filename like: *_eng or *_ger or *_rus 

Now when I convert the picture to srt, the filename remains with the *_ger, *_eng, *_rus

When I import these files back into MKVtoolnix GUI to merge the srt files back into the mkv, the program doesn't recognize the language.

I think, since this language information is a specific format of the extraction process of this software package, it should recognize it's own extract formatting and use this also to regain language information upon importing.

Thank you for considering this.

**Comment by mbunkus** [comment]
mkvmerge/the GUI doesn't detect the language from the file names and never will, sorry. For several reasons, most of them are listed [here](/mbunkus/mkvtoolnix/wiki/Detecting-track-language-from-filename).

VobSub subtitles contain the language as a property inside their .idx file. Therefore mkvmerge/the GUI do recognize the language, but in that case it's derived from the file content, not from the file name.

SRT subtitle files do not have the language stored inside as part of the file format. Therefore mkvmerge/the GUI doesn't try to detect the language for those.

Note further that mkvextract doesn't have any notion at all about default file names. It doesn't encourage or mandate that the language is part of the file name. If you're some kind of third-party GUI for mkvextract that always includes the language in the file name then that's a policy decision by the author of that GUI, not mine (and therefore not one of the MKVToolNix package).

**Comment by duiveldoder** [comment]
Fair enough.
