### ISSUE TITLE
Ask what to do when file is drag'n'dropped via right mouse button

### ISSUE THREAD

**Issue by tophf** [mbunkus/mkvtoolnix#1508]
Currently when a file is dropped onto the MKVToolnix GUI window it can either *always* ask what to do or silently do the previously chosen action. In the former case the choice is likely to be the same in the majority of operations which makes the menu a nuisance. In the latter case the user can't use drag'n'drop to perform an alternative action (at least in the current task tab).

It would be great if MKVToolnixGUI would follow the lead of some popular programs like Windows Explorer (and CorelDRAW and I guess many others) that show a menu when the object is drag'n'dropped with the right mouse button.

**Comment by mbunkus** [comment]
Thanks for the suggestion. I like it and will look into it.
