### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by fuel1986** [mbunkus/mkvtoolnix#1509]
Hi, the program has a few names that have not been translated into Russian. I can help with it.
![image](https://cloud.githubusercontent.com/assets/14252393/11097795/4350ffae-88b2-11e5-9fec-8bd460aa54fb.png)

**Comment by mbunkus** [comment]
Thanks for the offer, much appreciated. Please contact me via email as I prefer to handle everything related to translations that way. Thanks.

**Comment by mbunkus** [comment]
See [here](https://www.bunkus.org/videotools/mkvtoolnix/contact.html) for the address, BTW.
