### ISSUE TITLE
--previous-segment-uid could not be opened for reading: open file error

### ISSUE THREAD

**Issue by rakudaniku** [mbunkus/mkvtoolnix#1511]
While using the GUI for Mac from the experimental binaries (8.4.0 and 8.5.2) I get the following error when trying to mux a file that I want to link to a previous segment UID:

> The file '--previous-segment-uid' could not be opened for reading: open file error.

 I can use `--link-to-previous` in the CLI to get the intended results, and it also works fine in the 6.9.1 GUI.

---
> Operating system: OS X 10.10.5
> GUI versions tested: 6.9.1 (no bug present), 8.4.0 and 8.5.4 (bug present) from fosshub.com.
> CLI versions tested 8.0.0 and 8.5.4 (no bug present) (from HomeBrew)
> CLI used: --link-to-previous

**Comment by mbunkus** [comment]
Thanks for the report. The GUI uses the wrong command line options, unfortunately. I'll fix them.

**Comment by rakudaniku** [comment]
Awesome, thanks!

**Comment by mbunkus** [comment]
I've created a new [pre-build for MacOS](https://www.bunkus.org/videotools/mkvtoolnix/macos/pre/) that includes the fix.
