### ISSUE TITLE
Unable to drag and drop to v8.5.2

### ISSUE THREAD

**Issue by ghdbpnw** [mbunkus/mkvtoolnix#1520]
I have tried mkv and avi, unable to drag and drop either.  Drag and drop worked fine in previous version. I am able to DnD in other applications and have restarted computer..

Windows 7 x64, fully patched, 16 GB RAM

Thank you

**Comment by mbunkus** [comment]
I need more information. What are you dragging? Where are you dragging from, exactly? Where are you dropping them exactly? What exactly happens when you drop? While dragging does the drop indicator show that you can drop where you're trying to drop?

**Comment by ghdbpnw** [comment]
Dragging from Windows Explorer. 

As I wrote in my bug report, I have tried dragging mkv and avi as I always have in previous versions. 

I am dropping them into the Files: field on the Input tab in the MKVToolNix GUI v8.5.2 as I always have in previous versions. 

I can't drop because the cursor changes to a circle with a line thru it. Normally, the cursor would reflect a + symbol indicating the dropping is possible. 



----- Original Message -----

**Comment by mbunkus** [comment]
Are you running the GUI with administrative privileges (on purpose or accidentally)? Because Windows doesn't allow you to drag from applications without admin privileges to applications with admin privileges and vice versa.

For me dragging & dropping with 8.5.2 the way you're trying to do it works just fine.

**Comment by ghdbpnw** [comment]
Ahh, for some reason the shortcut properties was set to run as administrator. Removed that checkmark and DnD is working normally now. 

Thank you for pointing out the admin privileges clue. 

David 

----- Original Message -----

**Comment by mbunkus** [comment]
You're welcome :)
