### ISSUE TITLE
HEVC duplication in the job output

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1522]
I've got an .mkv file that contains:

► one video track (HEVC)
► four audio tracks (2x AC-3 + 1 plain DTS + 1 DTS-HD Master Audio 7.1)
► two subtitle tracks (SubRip/SRT)
► and.... chapters :)

Total = 8.

**First problem**:

mkvmerge shows (probably) an incorrect number of channels for the DTS-HD MA audio track in my original source file (.mkv). See: http://s7.postimg.org/kngzul3tn/An_incorrect_number_of_channels.png

But after muxing completion mkvmerge shows the correct number of channels: http://s14.postimg.org/hympbgzjl/The_correct_number_of_channels.png

So: who is right? mkvmerge or MediaInfo? That's the question :)

**Second problem**:

Now something more serious. mkvmerge shows two output modules for the HEVC format in the job output during muxing process. See: http://s7.postimg.org/giqax4vbv/HEVC_duplication.png
Question is: how is it possible as my .mkv file contains only 1 HEVC stream, not 2. It's definitely a bug. Of course: muxing went fine, just the output is wrong.

All necessary sample files will be uploaded to your FTP server soon.

Thanks for the investigation.

**Comment by mbunkus** [comment]
About the first problem: mkvmerge only reports the number of channels written in the Matroska track headers for that track. And that's 6, obviously. Meaning the data in the source MKV is probably wrong. If the file wasn't created with mkvmerge then this is not a bug in mkvmerge.
