### ISSUE TITLE
Version 8.60 can't download on oficial mirror in FossHub - always download only spam

### ISSUE THREAD

**Issue by VictorVG** [mbunkus/mkvtoolnix#1525]
Version 8.60? Yor link on http://www.fosshub.com/MKVToolNix.html result - Information is only loaded script. And so on to infinity. With such problems your site has never been, and with Foss Hub in recent years is common. Good thing they have not tightened "free" installation of hundreds - another partner programs and adware-passing the consent of the user as their colleagues from MediaGet putting their software using rootkits.

Now download them from using Qt Web Browser, but in order to download the file from their site each time it is necessary to open a new browser window, and not only at the first attempt, they will give it. I for friends to download the x86/x64 Windows assembly had 347 open browser windows, and in addition to the four of them the rest of the copies as twin brothers.

[mkvtoolnix-64bit-8.6.0-setup.exe.html.txt](https://github.com/mbunkus/mkvtoolnix/files/46629/mkvtoolnix-64bit-8.6.0-setup.exe.html.txt)

I watched what was going on - from any channel is loaded only this garbage. Or do I have no luck, or techies FossHub hands of the well-known place to grow. :)

**Comment by mbunkus** [comment]
Please have a look at the [FossHub FAQ](http://www.fosshub.com/faq.html) regarding download problems. What usually works is not to right-click on a donwload link but to left-click on it. In case the same page is loaded again just click on the download link once more and it should work.

If you cannot get it to work then please contact their staff.
