### ISSUE TITLE
Feature request: show the properties panel in two columns instead of a huge single column

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1526]
According to the post from Doom9's forum: http://forum.doom9.org/showthread.php?p=1745441#post1745441

I fully agree with the author who suggested that idea. I don't like scrolling the properties panel up and down therefore such a feature will be very useful for me as well.

This is an example of how the new feature may look like: http://savedonthe.net/image/2456/example.png

I have decided to open this Issue as I don't want you to forget about it. It will be really helpful for the users as the optional in the »Preferences« dialog. A new checkbox will be nice.

Thank you very much on behalf of myself and the author.

**Comment by remuxer32** [comment]
Thank you for the new feature, Mosu. I've got some hints for you:

1) If I enable a scrollable column, I can't resize it to the right side. To be preicse: cannot reduce its size. I'm trying to do it via the splitter, but it doesn't work. I can only extend it to the left side. I remember that I always could resize it to the right side; hence my astonishment.

2) If I enable "two fixed columns" then I can extend the panel to the left side, but cannot resize to the right side. But in this case I suppose it's normal, right?

3) ChangeLog should be updated :)

**Comment by mbunkus** [comment]
Thanks for the feedback. I'll fix 1 and update the ChangeLog.

The two fixed column layout has a pretty high minimum size, that's the way it is.

**Comment by mbunkus** [comment]
Fixed both. New pre-builds are on their way.

**Comment by remuxer32** [comment]
Thanks for the fast fix. Resizing works correctly now :)

**Comment by remuxer32** [comment]
I've just detected a strange behaviour that only occurs if you enable the properties panel in two fixed columns. It's a cosmetic issue, nothing serious, but stings the eyes, anyway.

Here the steps to reproduce that issue:

1) Go to the preferences dialog, and do two things:
 
a) enable buttons for moving list view entries up and down
b) enable the properties panel in two fixed columns

2) Add an .mkv file that contains a lot of tracks and start moving tracks up & down using the buttons.

The result: you should be able to see that the output filename will be »blue selected« each time during moving tracks up and down via the buttons. Like I wrote: that behaviour occurs only if: 
► the properties panel is enabled in two fixed columns
► the user moves tracks up & down using the buttons

Interestingly: if you use the keyboard shortcuts (left Ctrl + up/down) everything is fine. 

BTW: Are you sure that the properties panel in two fixed columns enabled by default is a good idea? Because earlier a single scrollable column was always enabled by default so many users are accustomed to that form of the layout.

**Comment by mbunkus** [comment]
I really have no idea why that's happening. I have implemented a workaround for it, though.

About the default: I have definitely not decided yet. See also [this post on Doom9](http://forum.doom9.org/showthread.php?p=1751917#post1751917).

**Comment by remuxer32** [comment]
I'm trying now your new pre-build with the workaround. Well, the output filename is not selected anymore, but seems that this workaround caused a new issue: moving tracks via the keyboard shortcuts does not work correctly. I cannot move my tracks up & down sometimes. I got stuck. No matter if the buttons are enabled or not. Try to move tracks via the keyboard shortcuts, and you will see that behaviour.

**Comment by mbunkus** [comment]
Fixed.

**Comment by remuxer32** [comment]
Yes, everything works fine now. Thanks.

**Comment by remuxer32** [comment]
As I don't have an account on Doom9's forum at the moment, I would like to share my thoughts about the best default position for the track properties here.

For me the best option is "two fixed columns" as it gives me the best overview for all of the properties; so it's definitely my favourite as I don't need to scroll the panel anymore. Unfortunately, that layout has a one big disadvantage for me: the two windows (panes) are definitely too small for me, then. Due to a fact that I often work with Blu-ray Discs that usually contain tons of audio tracks and subtitles, I need as huge panes as possible. Therefore, if I want to use my favuorite layout (two fixed columns) and keep the panes in an acceptable size at the same time, I must hide the tool selector and disable some of the columns in order to receive the best track structure (meaning: without needing to move the track layout from the left to the right side). Hiding the tool selector is something that I don't like because its lack deprives me a quick access to the other tools; instead I have to use a drop down menu which is located on the top (menu bar). Of course I know that I can also use the keyboard shortcuts (Alt + 1,2,3 etc.) for switching between the tools. Anyway, despite of these drawbacks, I still prefer the two fixed columns as they give me the best overview for manipulating the track properties.

About a scrollable column: this layout gives me the greatest size of the panes, but the only disadvantage is that I have to scroll the properties panel up & down, of course, which is truly painful if you have to do it several times during the day (meaning: have to mux many Blu-rays + modify their properties).

And finally: the properties panel located below the files and tracks. Well, this layout is definitely not for me as the two panes are EXTREMELY narrow (tight) so, as you might guess, I have to always scroll tons of tracks (Blu-rays) up & down. The same situation was in the old GUI, but in the old GUI those panes (windows) were much larger/wider.

Summarizing: as we can see each of those layouts has pros and cons, but if I had to decide which one of them to set as default, I would choose a scrollable column as it's well known for most users, and they are already accustomed, in a certain sense, to that form of the layout so...... »Let It Be« :)

Thank you for reading this.
