### ISSUE TITLE
v8.6.1 Removed Ability To Drag Codec's Up or Down

### ISSUE THREAD

**Issue by thejester77** [mbunkus/mkvtoolnix#1529]
v8.6.1 Removed Ability To Drag Codec's Up or Down.  Last version we were able to drag Codecs, SRT's, AC3/DTS Tracks around.  This version we can no longer prioritize what goes in what order... Please fix.

**Comment by mbunkus** [comment]
See [here](https://www.youtube.com/watch?v=r3b8EaBjeSk) for three different ways of moving tracks around. I've just verified that they still work fine with v8.6.1.
