### ISSUE TITLE
Only the first video is played of the merged mkv video

### ISSUE THREAD

**Issue by chic06** [mbunkus/mkvtoolnix#1531]
I try to merge mp4/mkv videos into one mkv using MKVToolNix GUI 8.6.1 64 bits (Win 7 pro).
Result: I get one (big) mkv video file; So the merge is perfomed okay, but my player (VLC media player 2.2.1) just only plays the first video.

I have tried different kind of video types/format, but get the same 'bad' result.
Wrong settings? 

Regards,

Chic06

**Comment by mbunkus** [comment]
You've probably "added" two videos instead of "appending" the second one.

**Comment by chic06** [comment]
Hi mbunkus,

Thanks for your quick respose,
Can you give me a hint how to do a "append".
I, now drag and drop the file into the dialog and click the merge button. -> so this is wrong?

Chic06

**Comment by mbunkus** [comment]
Right-click on the "files" list and select "append" from that menu.

You should also watch [this short video](https://www.youtube.com/watch?v=hrm-SFA0SC8) showing multiple ways of adding multiple files at once as it also shows you some other things you can do (e.g. configure the GUI to actually ask you what you want to do with the files you've just dropped – adding isn't the only thing possible).
