### ISSUE TITLE
Add --select-attachment option to MKVPropEdit to allow renaming/redescribing/reUIDing of attachments

### ISSUE THREAD

**Issue by ndjamena** [mbunkus/mkvtoolnix#1532]
MKVPropEdit --attachment-name "newname.jpg" --attachment-description "An attachment with a new name and description" --attachment-uid 123 --select-attachment 1 File.mkv

Self explanatory really.

or

MKVPropEdit -e attachment:1 -s "name=newname.jpg" -s "description=An attachment with a new name and description" -s "attachment-uid=123" File.mkv 

If you prefer.

**Comment by mbunkus** [comment]
Thanks, that does sound useful. I'll think about the syntax.

**Comment by ndjamena** [comment]
Of all people, I should have remembered the UID...

**Comment by mbunkus** [comment]
The syntax I've gone with is the same as for `--replaceme-attachment`; the option is just named `--update-attachment`. Example: `mkvpropedit file.mkv --attachment-name Whatever.txt --attachment-mime-type text/plain --update-attachment 1`
