### ISSUE TITLE
vobsub timecodes totaled during append

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#1535]
Hello, mkv is a great format, thank you for it.  When appending vobsub pieces using mkvmerge (I tested v7.4.0 ('Circles') 64bit and v8.3.0 ('Over the Horizon') 64bit), time codes are totaled, giving a ~22 minute video a total run time of 1 hour 7 minutes and the subtitles do not play accurately.  Video and audio play normally.  The command line used is...

$ mkvmerge -o ep1.mkv --default-language ja op.h264 +ep1.vob.h264 +ed.h264 +ed1.vob.h264 \ 
-D -a 2 op.vob -D -a 2 +ep1.vob -D -a 2 +ed.vob -D -a 2 +ed1.vob \
--language 0:en op.subtitles.idx +ep1.subtitles.idx +ed.subtitles.idx +ed1.subtitles.idx \
--chapters ep1.chapters

The subtitles from the first vobsub display accurately; however, the second vobsub plays at about the ~3 minute mark instead of 1:31:658, etc. The start and end times for each vobsub being appended do not overlap...

$ for e in *idx; do grep -H timestamp $e |head -n 1; grep -H timestamp $e |tail -n 1; done

op.subtitles.idx:timestamp: 00:00:10:744, filepos: 000000000
op.subtitles.idx:timestamp: 00:01:18:611, filepos: 00000e000
ep1.subtitles.idx:timestamp: 00:01:31:658, filepos: 000000000
ep1.subtitles.idx:timestamp: 00:21:09:635, filepos: 000118800
ed.subtitles.idx:timestamp: 00:21:18:010, filepos: 000000000
ed.subtitles.idx:timestamp: 00:22:16:635, filepos: 00000e000
ed1.subtitles.idx:timestamp: 00:22:31:850, filepos: 000000000
ed1.subtitles.idx:timestamp: 00:22:31:850, filepos: 000000000

As mentioned before, the audio and video portions are correct and play normally, only the vobsub portion is out of sync and lists a wrong duration in the mkv output...

$ ffprobe -i ep1.mkv 
Input #0, matroska,webm, from 'ep1.mkv':
Stream #0:0(jpn): Video: h264 (High), yuv420p, 720x480 [SAR 32:27 DAR 16:9], SAR 186:157 DAR 279:157, 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
    DURATION        : 00:22:37.356000000
Stream #0:1(jpn): Audio: ac3, 48000 Hz, stereo, fltp, 224 kb/s (default)
    DURATION        : 00:22:37.088000000
Stream #0:2(eng): Subtitle: dvd_subtitle (default)
    DURATION        : 01:07:17.121000000

The vobsub files above have been uploaded to your SFTP server.  Please advise, thank you.

**Comment by sneaker2** [comment]
This is by design. The timecodes of each appended file are always shifted by the sum of the durations of all the preceding files.

**Comment by mbunkus** [comment]
What @sneaker2 said is correct. Sorry, but this is how mkvmerge works.

**Comment by optimiz** [comment]
That's understandable, thanks for the information @sneaker2 and @mbunkus.  Thankfully the -y option worked around this; hopefully, the following example will help others, like @seiya-git who described very similar playback *symptoms* in #1495.

$ mkvmerge -o ep1.mkv --default-language ja op.h264 +ep1.vob.h264 +ed.h264 +ed1.vob.h264 \
-D -a 2 op.vob -D -a 2 +ep1.vob -D -a 2 +ed.vob -D -a 2 +ed1.vob \
--language 0:en op.subtitles.idx -y 0:-81000 +ep1.subtitles.idx -y 0:-1261500 +ed.subtitles.idx -y 0:-1351500 +ed1.subtitles.idx \
--chapters ep1.chapters

The offset milliseconds in the example were calculated using the first timestamp for each subsequent vobsub as a starting point, then adjusted as needed until the first subtitle matched the first spoken line perfectly. No timing changes to the actual vobsub timestamps was necessary. And more importantly, no need to convert vobsubs to a different subtitle format or change workflow.
