### ISSUE TITLE
cueDuration is not written for PGS subtitles

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1536]
As the title says: mkvmerge does not seem to write cueDuration elements for PGS subtitles at all.

[no cueDuration for PGS.zip](https://github.com/mbunkus/mkvtoolnix/files/59182/no.cueDuration.for.PGS.zip)

Note that in raw PGS every second subtitle picture is just to signal the end time of its predecessor, i.e. it should not need cueDuration (or duration should be set to 0). Maybe they should even be dropped completely because we don't need them outside the raw format? Not sure how players would like that.

**Comment by mbunkus** [comment]
That's correct. mkvmerge doesn't know the duration of a PGS subtitle frame as there is no such information inside the packet. Basically it's displayed until the next PGS frame comes around.

I currently have no plans for implementing some kind of intelligence. I'm leaving this open, but don't expect any action on it.

**Comment by mbunkus** [comment]
It is unrealistic that I'll ever change the current way of storing PGS subtitles. I do indeed not know what players would do if the "stop display" packets were removed in favor of using solely frame durations, and I simply don't have that much free time on my hands. Therefore things I don't consider all that important will have to fall by the wayside.
