### ISSUE TITLE
Closing "Preferences" with "OK" resets "Split Mode"-selection in mkvtoolnix-gui

### ISSUE THREAD

**Issue by hurda** [mbunkus/mkvtoolnix#1539]
mkvtoolnix 8.6.1

- Load any file into mkvtoolnix-gui.
- Go to "Output".
- Change to "Split Mode"-dropdownmenu to any non-default value.
- Open the Preferences and close them again by clicking "OK"

The "Split Mode"-dropdownbox will be reset to "Do not split".

**Comment by mbunkus** [comment]
Thanks for the report. Without having looked into it this is likely due to the re-initialization of all controls after a potential change to the interface language which is done each time the preferences are closed with the "OK" button. I'll look into it.

**Comment by mbunkus** [comment]
I can reproduce the issue and will fix it.

**Comment by mbunkus** [comment]
[Pre-builds 1043 (32bit), 1044 (64bit)](https://mkvtoolnix.download/windows/pre/) contain the fix.

**Comment by hurda** [comment]
Thanks!
