### ISSUE TITLE
unable to merge the same mkv file to the newly created mkv file

### ISSUE THREAD

**Issue by oolongmen** [mbunkus/mkvtoolnix#1540]
Hi,
I have 2 mkv files that I could merge fine using mkvmerge. However when I tried to merge the same mkv files with the newly created mkv file, I got this error "The track number 1 from the file 'test1.mkv' cannot be appended to the track number 1 from the file 'test_new.mkv'. The track parameters do not match."

`mkvinfo` of `test1.mkv`

```
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ EBML maximum ID length: 4
|+ EBML maximum size length: 8
|+ Doc type: matroska
|+ Doc type version: 2
|+ Doc type read version: 2
+ Segment, size 614847
|+ Seek head (subentries will be skipped)
|+ Segment information
| + Timecode scale: 1000000
| + Muxing application: asustor
| + Writing application: asustor
| + Segment UID: 0x09 0x75 0xa6 0xdc 0x67 0x2a 0xef 0x05 0x14 0x4e 0x3f 0x69 0x7e 0x9d 0xa0 0xd3
| + Duration: 60.953s (00:01:00.953)
|+ Segment tracks
| + A track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 1
|  + Lacing flag: 0
|  + Language: und
|  + Codec ID: V_MPEG4/ISO/AVC
|  + CodecPrivate, length 34
|  + Track type: video
|  + Video track
|   + Pixel width: 640
|   + Pixel height: 352
|   + Display unit: 0 (pixels)
|   + Display width: 640
|   + Display height: 352
|   + Aspect ratio type: 0 (free resizing)
| + A track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 2
|  + Lacing flag: 0
|  + Language: und
|  + Codec ID: A_AAC/MPEG4/LC
|  + Track type: audio
|  + Audio track
|   + Sampling frequency: 8000
|   + Channels: 1
|+ Cluster
```

`test_new.mkv`

```
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ EBML maximum ID length: 4
|+ EBML maximum size length: 8
|+ Doc type: matroska
|+ Doc type version: 4
|+ Doc type read version: 2
+ Segment, size 1225994
|+ Seek head (subentries will be skipped)
|+ EbmlVoid (size: 4029)
|+ Segment information
| + Timecode scale: 1000000
| + Muxing application: libebml v1.3.3 + libmatroska v1.4.4
| + Writing application: mkvmerge v8.6.1 ('Flying') 64bit
| + Duration: 122.106s (00:02:02.106)
| + Date: Wed Dec 16 10:07:19 2015 UTC
| + Title: test_new
| + Segment UID: 0x94 0xf9 0x02 0x84 0xe9 0xe7 0x61 0xf9 0xa7 0x9d 0x47 0xdf 0x41 0x5d 0x1a 0x5f
|+ Segment tracks
| + A track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 1
|  + Track type: video
|  + Lacing flag: 0
|  + Codec ID: V_MPEG4/ISO/AVC
|  + CodecPrivate, length 34 (h.264 profile: Unknown @L0.0)
|  + Language: und
|  + Video track
|   + Pixel width: 640
|   + Pixel height: 352
|   + Display width: 640
|   + Display height: 352
| + A track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 2
|  + Track type: audio
|  + Codec ID: A_AAC
|  + CodecPrivate, length 2
|  + Default duration: 128.000ms (7.812 frames/fields per second for a video track)
|  + Language: und
|  + Audio track
|+ EbmlVoid (size: 1106)
|+ Cluster
```

Thanks

**Comment by mbunkus** [comment]
Thanks for the report. Can you upload the original file before re-muxing  to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server), please? I don't need the whole file if it's big; the first 20 MB or so should suffice. Just abort the upload after that amount.

Thanks.

**Comment by oolongmen** [comment]
Thanks for reply. I have uploaded both files to your ftp server, test1.mkv and test2.mkv.

**Comment by mbunkus** [comment]
Thanks for the upload, but I cannot reproduce your problem with the two files you've uploaded. I've tried it both ways: add `test1.mkv` and append `test2.mkv` and the other way around. In both cases muxing goes fine; no error message is shown.

Are you sure you've uploaded the correct files for testing? Can you also please show me the command line (if you're using the GUI: "Merge" menu → "Show command line")? Thanks.

**Comment by oolongmen** [comment]
Sorry for not explain it clearly. Actually what I did is merge test1.mkv and test2.mkv to test_new.mkv. Then I tried to merge test1.mkv to test_new.mkv.

test1 + test2 (ok)
test_new + test1 (failed)

Below are the commands
merge test1.mkv and test2.mkv:
C:/Users/oolong/Downloads/mkvtoolnix-64bit-8.6.1/mkvtoolnix\mkvmerge.exe ^"--ui-language^" ^"en^" ^"--output^" ^"//172.16.12.35/Home/test/test_new.mkv^" ^"--language^" ^"0:und^" ^"--default-track^" ^"0:yes^" ^"--language^" ^"1:und^" ^"--default-track^" ^"1:yes^" ( ^"//172.16.12.35/Home/test/test1.mkv^" ) ^"+^" ( ^"//172.16.12.35/Home/test/test2.mkv^" ) ^"--track-order^" ^"0:0,0:1^" ^"--append-to^" ^"1:0:0:0,1:1:0:1^"

merge test_new.mkv and test1.mkv:
C:/Users/oolong/Downloads/mkvtoolnix-64bit-8.6.1/mkvtoolnix\mkvmerge.exe ^"--ui-language^" ^"en^" ^"--output^" ^"//172.16.12.35/Home/test/test_new2.mkv^" ^"--language^" ^"0:und^" ^"--default-track^" ^"0:yes^" ^"--language^" ^"1:und^" ^"--default-track^" ^"1:yes^" ( ^"//172.16.12.35/Home/test/test_new.mkv^" ) ^"+^" ( ^"//172.16.12.35/Home/test/test1.mkv^" ) ^"--track-order^" ^"0:0,0:1^" ^"--append-to^" ^"1:0:0:0,1:1:0:1^"

Error I got:
--- Errors emitted by job 'merging to file "test_new2.mkv" in directory "//172.16.12.35/Home/test"' started on 2015-12-18 10:54:23 ---
The track number 1 from the file '//172.16.12.35/Home/test/test1.mkv' cannot be appended to the track number 1 from the file '//172.16.12.35/Home/test/test_new.mkv'. The track parameters do not match.

Thanks.

**Comment by mbunkus** [comment]
Thanks. I can reproduce it now. I'll look into it.
