### ISSUE TITLE
Output format stream identifiers for mp4 format (and any others missing) in verbose identification.

### ISSUE THREAD

**Issue by ndjamena** [mbunkus/mkvtoolnix#1541]
Mastroska has track number and track uid, both of which are output by MKVMerge -I.

Would it be possible to output the internal identifiers for mp4 and any other formats that have them?  MP4 has a track number, MediaInfo shows it, mp4 box shows it, it's in all the track reference atoms and scattered through the file.

I'm trying to match track information taken from MediaInfo to track info taken from MKVMerge -I and MKVMerge isn't giving me much to work with...

So far I have the order or the streams and I can try to find MediaInfos Format field inside MKVMerges Codec Name, but I can't bring myself to believe that that method could be infallible.

**Comment by ndjamena** [comment]
OK then.  m2ts and mpls both output their ts_pid, it's just mp4 that doesn't show ids, the container that's most likely to have streams missing and be in incomprehensible orders.

**Comment by mbunkus** [comment]
I can add the internal IDs, but I make no guarantees whatsoever that those IDs are what MediaInfo uses. If MediaInfos uses those same IDs then that's great, but if it uses some other kind of numbering scheme then I won't implement that on my side.

**Comment by ndjamena** [comment]
```
<TrackHeaderBox CreationTime="3523028670" ModificationTime="3523028734" TrackID="2" Duration="5943820" AlternateGroupID="2" Volume="1.00">
<BoxInfo Size="92" Type="tkhd"/>
<FullBoxInfo Version="0" Flags="0xF"/>
</TrackHeaderBox>
```

Are these numbers not mandatory in mp4?

**Comment by mbunkus** [comment]
That's the number that I've already patched mkvmerge to output for MP4, yes. If that's the same number MediaInfo outputs: great.

**Comment by mbunkus** [comment]
I still have to check the other input formats for possible internal IDs to output. You've already correctly spotted the (sub) stream IDs in MPEG TS, so that format is covered. But others (RealMedia, MPEG PS, Ogg?…) may need work, too.

**Comment by ndjamena** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/dd318189(v=vs.85).aspx

AVI is just like TrackID except with no chance it will skip a track.

MediaInfo just adds all these number to a single field called "ID".

http://wiki.multimedia.cx/index.php?title=RealMedia#RealMedia_file_header_.28.RMF.29

Realmedia seems to have a "Stream number" right after the chunk version.  That might be it.

**Comment by ndjamena** [comment]
Vob is covered already.  Isn't that MPEG PS?

**Comment by mbunkus** [comment]
It is. Looks like I didn't remember outputting the stream IDs for program streams as well :)

**Comment by mbunkus** [comment]
AVI doesn't really have track numbers, BTW. What it has is a list of streams and they're simply numbered from 0 on upwards, but they don't have a separate field for a track/stream number. Pretty much the same way mkvmerge handles them.

**Comment by ndjamena** [comment]
Is it possible MKVMerge might skip an avi stream, or can it just copy the entire AVI stream wrapper and anything in it?

**Comment by mbunkus** [comment]
It only copies audio codecs it knows.

**Comment by ndjamena** [comment]
https://en.wikipedia.org/wiki/Ogg
https://en.wikipedia.org/wiki/Ogg_page

Bitstream serial number?

**Comment by mbunkus** [comment]
[Pre-builds 1043 (32bit), 1044 (64bit)](https://mkvtoolnix.download/windows/pre/) contain the implementation.
