### ISSUE TITLE
mkvmerge does not mark HEVC CRA frames from MP4 as keyframes

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1543]
There has been (or will be) a change to the mp4 specs (ISO/IEC 14496-15) that demands only HEVC "Clean Random Access (CRA) picture without associated Random Access Skipped Leading (RASL) pictures" can be "SyncSampleEntry". If you create a HEVC stream using x265 it will by default use OpenGOP which will create lots of CRA pictures *WITH* RASL thus cannot be SyncSampleEntry anymore. It seems mkvmerge only marks SyncSampleEntrys as keyframes which results in basically unseekable files. MP4 has an extra 'rap ' sample group and these pictures are of sap type 3 so mkvmerge should probably gather that information from there on top of using the SyncSampleEntrys.

Note that I do not have access to the ISO/IEC 14496-15 specs myself and all my information is gathered from the developers of l-smash and gpac so I cannot be of greater assistance in solving this. (even if I had the specs I would probably not understand them)
I will upload samples to your ftp.

**Comment by mbunkus** [comment]
Thanks. I don't have access to that document either. I don't know when I'll get around to looking into this.

**Comment by sneaker2** [comment]
I could fill up some of my knowledge gaps using ISO/IEC 14496-12 which is freely available here:
http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html
It does not have all the HEVC specific details I assume can be found in ISO/IEC 14496-15, but it helps anyways because the basic syntax and semantic are explained and seem to be valid for HEVC still.

In the mp4 sample we find the following boxes somewhere down the track box:
```
[sgpd: Sample Group Description Box]
    position = 16360
    size = 25
    version = 1
    flags = 0x000000
    grouping_type = rap 
    default_length = 1 (constant)
    entry_count = 1
    entry[0]
        num_leading_samples_known = 0
        num_leading_samples = 0
[sbgp: Sample to Group Box]
    position = 16385
    size = 148
    version = 0
    flags = 0x000000
    grouping_type = rap 
    entry_count = 16
    entry[0]
        sample_count = 249
        group_description_index = 0 (not in this grouping type)
    entry[1]
        sample_count = 1
        group_description_index = 1
    entry[2]
        sample_count = 35
        group_description_index = 0 (not in this grouping type)
    entry[3]
        sample_count = 1
        group_description_index = 1
    entry[4]
        sample_count = 92
        group_description_index = 0 (not in this grouping type)
    entry[5]
        sample_count = 1
        group_description_index = 1
    entry[6]
        sample_count = 174
        group_description_index = 0 (not in this grouping type)
    entry[7]
        sample_count = 1
        group_description_index = 1
    entry[8]
        sample_count = 245
        group_description_index = 0 (not in this grouping type)
    entry[9]
        sample_count = 1
        group_description_index = 1
    entry[10]
        sample_count = 249
        group_description_index = 0 (not in this grouping type)
    entry[11]
        sample_count = 1
        group_description_index = 1
    entry[12]
        sample_count = 95
        group_description_index = 0 (not in this grouping type)
    entry[13]
        sample_count = 1
        group_description_index = 1
    entry[14]
        sample_count = 200
        group_description_index = 0 (not in this grouping type)
    entry[15]
        sample_count = 1
        group_description_index = 1
```
We should use the entries from the "rap" (=random access point) group to get our seekable frames. Note that we won't have the IDR frames here, these remain SyncSampleEntrys.

The first entry says 249 frames are not part of the group. The next 1 frame is part of the group, the next 35 aren't, the next 1 is etc.

I hope this is correct. With no access to ISO/IEC 14496-15 and neither l-smash nor ffmpeg having implemented this (yet) this is mainly relying on gpac/mp4box having done the job correctly.

**Comment by sneaker2** [comment]
Some additional notes:
1. I said "rap" group but it's actually "rap " with a space at the end
2. While the issue title says HEVC this seems apply to all formats in mp4 including AVC (if the format has the concept discussed in the first place)
3. There seem to be even more possible ways to mux OpenGOP in mp4:
    sdtp; sbgp with "roll" group
Should I open separate issues for those?

**Comment by mbunkus** [comment]
No, let's leave it all together in a single issue for the time being, please.

**Comment by mbunkus** [comment]
I've only implemented support for the `rap ` sample grouping so far. I'm currently building and uploading new [pre-builds (build numbers 1064 for 32bit, 1065 for 64bit)](https://mkvtoolnix.download/windows/pre/).

If you have samples for the other types and if they aren't handled properly by those new pre-builds then I'd appreciate it if you opened new issues for those. I'll also need samples then :) Thanks.
