### ISSUE TITLE
Please Help 

### ISSUE THREAD

**Issue by Nelson-P** [mbunkus/mkvtoolnix#1544]
Using MKToolNix GUI v8.6.1 merging multiple .vob files and although they do merge into one large output file my VLC and Windows Media Players stop after the length of the 1st .vob file in the output .mkv file and will play no more of the much larger file. Can anyone explain why this is happening?  Site notes I've seen explain adding multiple .vob files in sequential order will work using the 'add source files' option but it does not.  In the version of MKToolNix I have I see no other options for adding files to merge other than 'add source files'.  I use a Windows 10 32bit operating system.  Please help,  thanks Nelson

**Comment by mbunkus** [comment]
"Add" the first file, "append" the others. See [this short intro video](https://www.youtube.com/watch?v=hrm-SFA0SC8) for multiple ways how to add/append files.

**Comment by Nelson-P** [comment]
Thanks mbunkus.  Merged 15 .vob's OK except the 2nd .vob got this error.  Played output file past the start of 2nd and except for brief blackout (less than a sec.) 2nd section plays.  All the rest of the output file looks OK as well.  I brought the 1st input over then brought remaining 14 over at once.  The option menu popped up automatically and I chose 'append' at that point.  Any further advice would be appreciated. Thanks and Happy Holidays. Nelson
error:  
The track number 0 from the file 'C:/Users/Jeanie/Desktop/wrestlemania xxvII/2.VOB' can probably not be appended correctly to the track number 0 from the file 'C:/Users/Jeanie/Desktop/wrestlemania xxvII/1.VOB': The codec's private data does not match (lengths: 0 and 22). Please make sure that the resulting file plays correctly the whole time. The author of this program will probably not give support for playback issues with the resulting file.

**Comment by mbunkus** [comment]
If you get that message then you cannot append those tracks due to incompatibilities in the track's data. Nothing you can do about it.

**Comment by Nelson-P** [comment]
Ok thanks.
