### ISSUE TITLE
Right click  to add files

### ISSUE THREAD

**Issue by don544** [mbunkus/mkvtoolnix#1546]
When hovered over on the input page of the GUI, tabs have a popup that says to right click too add, append and remove files. However when right clicked a menu comes up to reset all columns.
![mkv right click](https://cloud.githubusercontent.com/assets/13720091/12006065/3ac4b156-ab93-11e5-9241-31490310082b.gif)

![mkv1](https://cloud.githubusercontent.com/assets/13720091/12006067/4d0807be-ab93-11e5-858a-0a99e9b8be50.gif)

**Comment by ndjamena** [comment]
I think that pop-up is applied to the entire control, if you right click bellow the tabs you actually get the correct context menu.

It's up to the toolset Mosu is using as to whether it allows separate pup-ups for different child elements.

The same problem happens for all table controls, including the tracks and the job queue.

**Comment by mbunkus** [comment]
What @ndjamena said is spot-on. The tool tip is set for the whole control. Please just right-click on the view area, not on the headers.

**Comment by don544** [comment]
Thank you for the response
