### ISSUE TITLE
mkvmerge creates wrong timestamps for raw h264 streams

### ISSUE THREAD

**Issue by hauskat** [mbunkus/mkvtoolnix#1548]
I uploaded a sample file on ftp.bunkus.org (wrong_timestamps.264) that demonstrates the wrong behaviour. The file contains 3 video sequences with a total of 280 frames. The problem occurs on frame 129 (IDR frame - `idr_pic_id` 4095 - start of the second video sequence). The frame gets the timestamp 0:00:05.839 but it should get the timestamp 0:00:05.339. This causes vlc and other video players to drop frames.
I investigated the problem and found that the slice info of the frame extracted by mkvmerge contains a wrong `pic_order_cnt_lsb` value (12 instead of 0). The wrong value is caused by a missing unescape of the slice nalu block which leaves a forbidden byte sequence of 0x00 0x00 0x03 in the slice header. I added the following code to `mpeg4::p10::avc_es_parser_c::handle_slice_nalu`:

```
  nalu_to_rbsp(nalu); // added
  
  if (!parse_slice(nalu, si))
    return;
  
  rbsp_to_nalu(nalu); // added
```

This fixed the problem.

Regards,
Torsten Hauska

**Comment by mbunkus** [comment]
Very nice analysis. Thank you very much. I'll investigate it.

**Comment by mbunkus** [comment]
Turned out this also fixed #918. Nice :)

**Comment by hauskat** [comment]
Thanks a lot for the fast fix.

Am Montag, 28. Dezember 2015, 04:51:37 schrieb Moritz Bunkus:

**Comment by mbunkus** [comment]
Well, you did all the heavy lifting ;) Thanks again for that.
