### ISSUE TITLE
MKV with AC3 track muxed with mkvtoolnix GUI loses audio sync when seeking with iOS app GoodPlayer but not if muxed with ffmpeg.

### ISSUE THREAD

**Issue by sinister333** [mbunkus/mkvtoolnix#1549]
Using the latest and previous versions of mkvtoolnix and its GUI, whenever I mux something with AC3 audio, the synchronization is lost whenever I seek playing the MKV with the iOS app GoodPlayer. I can take that same MKV however and merely remux it with the latest and previous versions of ffmpeg using "-c copy" and the problem is gone, the audio stays in sync. What is the default ffmpeg doing that the default mkvtoolnix GUI isn't?

**Comment by mbunkus** [comment]
How should I know? I'm not an ffmpeg developer.

Have you tried playing the file created by mkvmerge with other players, especially ones that are known to have good Matroska support like VLC and MPC HC?

**Comment by sinister333** [comment]
I didn't think this would require anyone to be one. Perhaps I should have better phrased my question. I thought this would have just required comparing both of their outputs and sniffing out the difference between them with regards to synchronization. And yes, I have. VLC for example handles it as it should.

**Comment by mbunkus** [comment]
As I don't have access to your files I cannot compare them myself. Matroska is a very flexible format, and different muxers use different features.

If VLC handles the file correctly and as I haven't had a single report regarding AC-3 synchronization issues for ages (besides yours, of course) I'm strongly thinking that this is a bug in GoodPlayer. I'm therefore closing this issue again.

However, what you can do is head over to my [wiki page about improving compatibility with players that don't support all of Matroska's features](/mbunkus/mkvtoolnix/wiki/Improving-playback-compatibility-with-players). It's likely that using one of more of the features mentioned therein will produce files that GoodPlayer works better with. Just as a hunch I'd start with `--disable-lacing` as that's one that affects timestamps the most.

**Comment by sinister333** [comment]
That did it. Thank you.

**Comment by mbunkus** [comment]
You're welcome.
