### ISSUE TITLE
Handling existing Language Country information

### ISSUE THREAD

**Issue by ndjamena** [mbunkus/mkvtoolnix#1550]
I know MKVMerge support for County in languages isn't happening, but I just discovered MKVPropEdit will happily write eng-uk or eng-us into a tracks language and MediaInfo is happy to display it as such.

If I remux the file with MKVMerge the language is reverted to plain "eng" as expected, but if I load the file into the MKVToolNix Header Editor, it converts it to "und".  If I then change the name of the track and save it, the GUI will save the language as "und" and the language information will therefore be lost entirely.

**Comment by mbunkus** [comment]
Thanks. I will fix this by making mkvpropedit check the language for validity before writing. I will not modify mkvmerge and the GUI to cope with such entries, though, as that would amount to a lot of effort and time that I'm just not willing to spend. That's the reason I closed #958.

**Comment by ndjamena** [comment]
Understood, and that WILL prevent the problem from coming up again.

**Comment by mbunkus** [comment]
At least for my tools. Other applications may still write such language/country pairs, of course, but I'll deal with that if and only if they start cropping up.

**Comment by ndjamena** [comment]
OH, right, that was the point.  Can you at least have the header editor default "eng-uk" or "eng-us" or whatever to "eng" rather than "und".  That way if it ever comes up again, whoever's doing the reporting will have that little bit less to complain about.

**Comment by mbunkus** [comment]
Well, mkvmerge would revert to `und`, too, and I'd have to fix that, too, for all places where language tags can occur. At which point I'm halfway into implementing full support for that. So… no, not for the time being. Sorry.

**Comment by ndjamena** [comment]
Oh, sorry.  I've configured MKVToolNix GUI to default all tracks with no language to "und" rather than "eng" and thought it was just ditching the country data.

**Comment by mbunkus** [comment]
No. The country part of the language element isn't handled at all yet – in none of the tools. Hence my estimate that it would take quite a lot of time to implement properly.
