### ISSUE TITLE
Add a button next file title in Output for title selection

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1555]
Since version 8.7.0 one can copy the file title from the source or destination file name.

(It already read the file title from the source file if that was included within the file.)

Previously it had not crossed my mind to copy it from any of the file names, but now that it exists, a button, next to the input field that opens a pop-up menu for selecting from which file to copy the file title, seems to be useful.

I right -clicked there to see if that would do anything, then I consulted the change-log to see how I get to do it.

(Back then, when Firefox showed a menu, I was using it. As they hid it, I re-activated it again. Nowadays I rarely use its menu. Thanks to Mozilla and Microsoft I am not used to click on menus by default.)

Honestly, if this will be a wont-fix, I could not complain either.

**Comment by mbunkus** [comment]
Thanks for your thoughts. My design goal with the GUI is to have as few buttons as possible, especially for seldom-used options. Instead the GUI makes extensive use of menus, both the ones in the main menu bar as well as context menus.

Putting buttons everywhere has the distinct disadvantage of making the GUI much more crowded and confusing. Additionally it increases the GUIs minimum size, and people are already complaining that the (new) GUI requires too much space.

For these reasons I'm not going to add buttons.
