### ISSUE TITLE
M2V detected as TrueHD

### ISSUE THREAD

**Issue by basicmaster** [mbunkus/mkvtoolnix#1559]
The recent move of the M2V recognition within `get_file_type_internal`towards the end unfortunately triggers a false positive TrueHD recognition of an in fact M2V. This leads to a SIGSEGV crash of `mkvmerge false_positive_truehd.m2v -o test.mkv`. I uploaded the mentioned file (which in fact came from a DVD) to your FTP.

**Comment by mbunkus** [comment]
Thanks. I'll look into it.

**Comment by basicmaster** [comment]
Thanks for the fix!

And at this point: Thank you for the great support, which is always sophisticated and fast. And for the precise changelog - I look forward to every new release of mkvtoolnix!

**Comment by mbunkus** [comment]
Thanks for your kind words & you're welcome :)
