### ISSUE TITLE
Automatic delay

### ISSUE THREAD

**Issue by diegov18** [mbunkus/mkvtoolnix#1563]
Nothing to explain.

Audio #2
ID                          : 3
Format                      : AC-3
Format/Info                 : Audio Coding 3
Mode extension              : CM (complete main)
Format settings, Endianness : Big
Codec ID                    : A_AC3
Duration                    : 1h 52mn
Bit rate mode               : Constant
Bit rate                    : 640 Kbps
Channel(s)                  : 6 channels
Channel positions           : Front: L C R, Side: L R, LFE
Sampling rate               : 48.0 KHz
Frame rate                  : 31.250 fps (1536 spf)
Compression mode            : Lossy
Delay relative to video     : -83ms
Stream size                 : 514 MiB (7%)
Title                       : Surround
Language                    : English
Default                     : No
Forced                      : No

**Comment by mbunkus** [comment]
Unfortunately you're wrong. I have no clue whatsoever what you're trying to tell me.

**Comment by mbunkus** [comment]
You haven't provided any description of what you think is wrong, even after pointing that out to you. I'm therefore closing this issue due to lack of feedback.
