### ISSUE TITLE
I can't drag and drop files

### ISSUE THREAD

**Issue by Naboum** [mbunkus/mkvtoolnix#1566]
Hi,
I have noticed this since a few versions earlier ; I can't drag and drop files into the input files.
I tried with .srt and .mkv files, and it doesn't seem to work. This is what happens when I try to : 
![dotn69k](https://cloud.githubusercontent.com/assets/15255201/12213426/293e1446-b678-11e5-99b7-7ffbf26e9a1f.png)

I am currently using v8.7.0 with Windows 10 64 bits.

**Comment by mbunkus** [comment]
You've probably started the GUI with admin privileges and the file manager without or vice versa. Windows simply doesn't allow drag & drop operations between programs where one program has admin privileges and the other one doesn't.

**Comment by Naboum** [comment]
That was exactly the problem, thank you !

**Comment by mbunkus** [comment]
You're welcome.
