### ISSUE TITLE
Muxing fails immediately

### ISSUE THREAD

**Issue by bearass** [mbunkus/mkvtoolnix#1567]
I have tried the current release and uninstalled and reinstalled the last 2 release for windows 64bit. 

I am trying to merge a 2 part file, each time i try to merge the files it fails immediately saying the parameters do not match. Any help would be appreciated. The only thing i can see is the Frame width/height is slightly off between to the 2 files file 1 is 720x364 file 2 is 720x366, if this is a known issue, is there a way for me to alter it in handbrake if i re-rip one of the dvds?

**Comment by mbunkus** [comment]
The Matroska container doesn't support tracks whose properties like its pixel size change mid-stream. Therefore mkvmerge doesn't allow operations which would result in something like that.
