### ISSUE TITLE
Regression for DTS-HD streams in 8.7.0

### ISSUE THREAD

**Issue by nikola** [mbunkus/mkvtoolnix#1568]
Between 8.6.1 and 8.7.0, Windows 7 64-bit, a regression was introduced in handling DTS-HD streams.

When I add a certain DTS-HD stream (7.1 24bit 48kHz), either via drag-and-drop or "Add files", MKVToolNix GUI will display an error "The mkvmerge executable was not found."

With 8.6.1, using the exact same steps for the same DTS-HD file in the same location, everything works as expected.

**Comment by mbunkus** [comment]
Already fixed; see #1559 for the actual reason and for #1556 for a longer explanation.
