### ISSUE TITLE
Green progress bar stays at 100%

### ISSUE THREAD

**Issue by FCrane** [mbunkus/mkvtoolnix#1571]
Hi!

I want to report a very annoying detail that has bugged me since the last few major version updates:

The green progress bar (the right one of the two) stays green and at 100% when the queue is finished. That is very misleading, because I never know when the queue is really finished - sometimes it takes a few moments (or longer on a slow network drive) to finish the file and so the progress bar does stay at 100% for a longer time when there is still activity. However, when it's finished, it does not disappear as it should to indicate that theree is no more activity!

Unfortunately, there is no audio notification either when a job has finished (and the current implementation of executing programs at that event is buggy beyond belief - see my other ticket), so there is no way to quickly check if the merging is done or not.

Please remove the green progress bar when the queue has finished to avoid confusion!

Thanks!

**Comment by mbunkus** [comment]
I'm sorry, but no, this is actually intentional to signal that something has actually been done. This is important especially for small jobs.
