### ISSUE TITLE
Feature request: visual indicator when adding "chapters.txt" file

### ISSUE THREAD

**Issue by FCrane** [mbunkus/mkvtoolnix#1572]
Hi!

When I drag & drop a chapters file to MKVToolNix Merge tool, it automatically adds it to the "Output" tab to be included in the MKV file. This works and it's ok. However, there is no visual indication that the file has been added on the "Input" tab, where all other files added are shown.

It would be nice if there was any kind of indicator on the input tab telling me that I already have added the chapter file. Now I always have to switch to the output tab and back just for checking that.

Thanks!

**Comment by mbunkus** [comment]
Yeah it would be nice, but I'm not going to spend time on this. I'm sorry. I'm open to patches though; if someone else wants to implement better visual hints (not only for this) then I'd welcome such work.

**Comment by mbunkus** [comment]
I should probably have thought about this for more then ten seconds. Sorry.

I won't implement a visual hint, but I will implement a popup stating what happened to such a file. It will only shown once in order not to annoy the user too much.

**Comment by FCrane** [comment]
Please make that popup optional, because generally I don't want to have to click away any popups during the process of adding files. As you mentioned, this is annoying...

Maybe a temporary tooltip that fades by itself or something like that?

Ideal would be to include it in the list of input tracks, of course. The chapters are listed in the tracks if  I open an MKV that contains chapters, so that would be most consistent!

Thanks!

**Comment by mbunkus** [comment]
Like I said, the popup will only be shown once (not once per start of the GUI but once in total).

I don't like fading popups; they always tend to stay around too long or too short, and if it's too short then the user has no way of getting them back again.

Chapters aren't treated like other input files in mkvmerge, therefore I won't put them there.

**Comment by mbunkus** [comment]
I just noticed that there is already such a popup explaining things when you add a chapter file. You must have seen it already. If you want to see it again remove the entry `mergeChaptersDropped` from the [INI file](/mbunkus/mkvtoolnix/wiki/Settings-location).

I'm therefore closing this issue. Like I said I don't like auto-fading popups, and I'm not interested in implemented other visual cues myself.
