### ISSUE TITLE
feature request: Ability to force write of default values

### ISSUE THREAD

**Issue by eriksperling** [mbunkus/mkvtoolnix#1573]
I'd like the ability to force writing the "eng" language code to tracks, even though it is the default value. This is primarily for scripting purposes - I'm automatically finding and fixing common errors in a large library, and the lack of a language code causes a bunch of special case handling that (to me) isn't worth the minimal space saving.

**Comment by mbunkus** [comment]
Sorry, but I won't implement such a switch. A couple of years ago I did write default values and it wreaked havoc with players as suddenly a lot of elements who they'd never seen before were present in a file. Hardware devices were especially bad.

About your use case. From what you're writing it

**Comment by mbunkus** [comment]
Sorry, but I won't implement such a switch. A couple of years ago I did write default values and it wreaked havoc with players as suddenly a lot of elements who they'd never seen before were present in a file. Hardware devices were especially bad.

About your use case. From what you're writing it sounds like you're using mkvinfo. I highly suggest you use mkvmerge instead for two reasons:

1. It has a JSON output mode for its identification result. This makes its output trivial to use in other tools as JSON parsing libraries are available for pretty much every language under the sun.
2. mkvinfo is only supposed to present the structure as it is actually present, but mkvmerge acts more like a player would. This means that mkvmerge always outputs the language information even if the element is not present in the file.

Here's an example in Ruby:

```ruby
#!/usr/bin/env ruby

$-w = true

require "json"

result = JSON.parse(`mkvmerge -F json -i ~/prog/video/data/v.mkv`)
result["tracks"].each do |track|
  if track["properties"]["language"] == "eng"
    puts "Track ID #{track["id"]} is English"
  end
end
```

**Comment by mbunkus** [comment]
Another advantage: the track IDs output by mkvmerge are guaranteed to be the same track IDs you would need for further invocation of mkvmerge. mkvinfo tries to guess the same IDs but there are corner cases where this doesn't work correctly. mkvinfo simply doesn't have all the information mkvmerge has in order to determine these IDs correctly.

**Comment by eriksperling** [comment]
I'll stick to my current mkvinfo -> mkvmerge -> mkvpropedit setup then, I was hoping to skip the mkvpropedit step.
