### ISSUE TITLE
Strange error: "Error executing mkvmerge: The mkvmerge executable was not found"

### ISSUE THREAD

**Issue by FCrane** [mbunkus/mkvtoolnix#1574]
Hi!

For some .h264 files (created by eac3to and playable fine in MPC-HC), I get this error message when trying to add the track to MKVMergeGUI (lates v8.7.0). I never got this error with other versions of the program. 

The executable is in place, of course, and it works fine with about 90% of all video tracks. Just some seem to trigger this strange error!

What seems to be the problem?

Thanks!

**Comment by FCrane** [comment]
Here's the first MB of that file (original is 18 GB). Produces the same error...
[Video_2.zip](https://github.com/mbunkus/mkvtoolnix/files/90534/Video_2.zip)

**Comment by mbunkus** [comment]
This has already been fixed. Upgrade to 8.8.0.

**Comment by FCrane** [comment]
That's another thing: the update check seems to have stopped working since 8.6.0! I am not notified of new versions anymore (although the option is on) and when I check for updates manually, I just get the attached dialog and nothing happens.
![update dialog](https://cloud.githubusercontent.com/assets/14123400/12327896/27181666-bad9-11e5-92f1-66bbc35a2491.png)

The update function used to wokr fine until v8.6.0 (I think) and then stopped working...

**Comment by FCrane** [comment]
Update: after quite a while, the status changes to "There was an error querying the update status."

Internet connection is fine and I can access the download manually.

**Comment by mbunkus** [comment]
Works just fine for me, both on Windows and on Linux (tested with 8.7.0 on each). Don't know what's wrong on your end. The update check tries to read https://mkvtoolnix.download/latest-release.xml and the changelog dialog reads https://mkvtoolnix.download/releases.xml – so you should check proxy settings, anti-virus/firewall tools, external firewalls etc.

Anyway, this has nothing to do with the originally reported issue, so let's stop here with your update problems.
