### ISSUE TITLE
Trouble with CodecID

### ISSUE THREAD

**Issue by Tim666** [mbunkus/mkvtoolnix#1575]
I'm not sure that It's a bug...
When I try to convert avi file with Codec ID="XVID" to mkv It produces mkv with Codec ID="V_MS/VFW/FOURCC / XVID" that can be played by TV.
But TV can plays mkv files and also perfectly plays source avi file.
Actually CodecID from mkv file looking a bit strange in hex view.
                                                                        56 5F 
4D 53 2F 56 46 57 2F 46 4F 55 52 43 43 63 A2 A8
28 00 00 00 80 02 00 00 E0 01 00 00 01 00 18 00
58 56 49 44 00 10 0E 00 00 00 00 00 00 00 00 00 
Does exist command line parameter for mkvmerge to prevent changing CodecID or setup custom value for CodecID?
[mkvinfo_source.txt](https://github.com/mbunkus/mkvtoolnix/files/91088/mkvinfo_source.txt)
[mkvinfo_target.txt](https://github.com/mbunkus/mkvtoolnix/files/91089/mkvinfo_target.txt)

**Comment by mbunkus** [comment]
No, it cannot be changed. It can also not be kept. AVI uses a completely different system for identifying the codec: the so-called FourCC (four-byte character code, `XVID` in your case). 

Matroska uses identifiers such as `V_THEORA` (for a video track with the codec Theora). XviD and DivX are stored in AVI-compatibility mode, meaning the appropriate codec ID is `V_MS/VFW/FOURCC`, and inside the CodecPrivate element the original FourCC as present in the AVI is stored (`XVID`). MediaInfo conflates both pieces of information in that single line.

If your TV doesn't play the file then it doesn't support Matroska properly.
