### ISSUE TITLE
GUI: Cannot mux a file with chapters only (no "real" streams)

### ISSUE THREAD

**Issue by BrotherJohn** [mbunkus/mkvtoolnix#1576]
The new GUI does not allow creating chapter-only files without any media streams of their own. Instead the GUI shows an error dialog stating _You have to add at least one source file_. However using mkvmerge directly such files are created without problems and work as expected.

Personally I use chapter-only files to make a complete TV show season appear as a single movie when I have separate files for each episode. That’s very handy for binge watching to avoid repeating Theme/Credits/Previously sequences over and over again.

**Comment by mbunkus** [comment]
Thanks. I'll take out that check.
