### ISSUE TITLE
GUI: Wrong spelling in German translation

### ISSUE THREAD

**Issue by susnux** [mbunkus/mkvtoolnix#1577]
In the german .po file this line:

    #: src/mkvtoolnix-gui/forms/main_window/preferences_dialog.h:1208
    msgid "Always use a &default description when adding a job to the queue"
    msgstr "Immer die Standard&bescrhreibung beim Hinzufügen von Jobs zur Warteschlange nutzenn"

Is wrong, it should be:

    msgstr "Immer die Standard&beschreibung beim Hinzufügen von Jobs zur Warteschlange nutzen"

**Comment by mbunkus** [comment]
Thanks for the heads-up.
