### ISSUE TITLE
Exception parsing aac with custom PCE

### ISSUE THREAD

**Issue by jesgdev** [mbunkus/mkvtoolnix#1578]
I have an aac track in an m4a container with a PCE in the ASC,  mkvmerge throws an exception parsing...

cmd:
mkvmerge.exe --debug aac_full -o merged.mkv --language 0:eng -T -A -S -B -M --no-chapters --no-global-tags movie.mkv --language 0:eng -T --no-global-tags movie.m4a

output:
mkvmerge v8.8.0 ('Wind at my back') 64bit
'movie.mkv': Using the demultiplexer for the format 'Matroska'.
'movie.m4a': Using the demultiplexer for the format 'QuickTime/MP4'.
Debug> src/common/aac.cpp:1034: aac::parse_audio_specific_config: size 9, data: 0x11 0x80 0x04 0xc4 0x04 0x00 0x21 0x10 0x00
Debug> src/common/aac.cpp:1021: aac::parse_audio_specific_config: exception: end of file error
Warning: Track 0: The AAC information could not be parsed.
Warning: Quicktime/MP4 reader: The AAC track 0 is missing the esds atom/the decoder config. Skipping this track.
'movie.mkv' track 0: Using the output module for the format 'HEVC/h.265'.
Warning: 'movie.m4a': A track with the ID 0 was requested but not found in the file. The corresponding option will be ignored.
The file 'merged.mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Muxing took 18 seconds.

Poking around the code it looks like the issue is in aac.cpp, line 946 where it reads the comment field.  The comment length byte is read moving the bit_reader to eof, but skip bits is called which throws the exception(in set_bit_position).  

[movie.zip](https://github.com/mbunkus/mkvtoolnix/files/102285/movie.zip)

**Comment by mbunkus** [comment]
Thanks for the report & the sample file. I'll look into it.

**Comment by jesgdev** [comment]
Thanks for the fix!  That was quick :)

**Comment by mbunkus** [comment]
You're welcome.
