### ISSUE TITLE
Wrong characters displayed if subtitle character set is ISO-8859-2

### ISSUE THREAD

**Issue by deadhorse** [mbunkus/mkvtoolnix#1579]
I've added an srt subtitle file which definitely has the character set ISO-8859-2 and assigned this set to it on the input tab.  When pressing the button with the two accent letters to verify the conversion in a popup everything seems perfect.  Yet in while playing the resulting mkv file all accent letters will be displayed as "?".

If however the character set WINDOWS-1252 is selected for the same file most accent letters but a few get displayed correctly.  The preview in the popup and the result in the mkv are consistent.  ISO-8859-2 addresses exactly those few that I would like to have displayed correctly as well, notably "ő", "ű", "Ő" and "Ű".

I am sure that in this case ISO-8859-2 is the actual character set of the file.  I usually convert the srt files manually to UTF-8 by executing the command "iconv -f iso-8859-2 -t utf-8".

I didn't test any other character set as they don't apply in my case anyway.

(Other than that this tool is awesome!)

**Comment by deadhorse** [comment]
Sorry, I forgot to mention that this occurs in the version 8.7.0 under OS X.

**Comment by mbunkus** [comment]
Thanks for the report. Can you please upload the SRT file in question together with the mux settings you're using to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server)? Or send them via [email](mailto:moritz@bunkus.org); they shouldn't be too big. Thanks.

**Comment by deadhorse** [comment]
Thanks for getting back so quickly to me!  I'm sorry that I didn't start with the latest version first, it seems that the bug is gone/fixed in 8.8.0.  Applying the same set of input files and the same mux settings the result is pristine.  I guess you won't need the srt file any longer; let me know if you still do nevertheless.  I'm closing this issue.

**Comment by mbunkus** [comment]
You're welcome. If it's working for you already then I don't need the file, that's right.
