### ISSUE TITLE
Enable/Disable the execution of certain programs

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1581]
I would like to see a way to easily enable or disable the execution of certain programs.

That way I can add entries to the programs that can be executed, but have them disabled until I need them. Just an on and off switch.

**Comment by mbunkus** [comment]
Hmm… you can already disable it by unchecking all of the check boxes in the "when to execute" section. But I see your point; I'll think about adding a "enabled" check box.

**Comment by remuxer32** [comment]
Very good idea. I fully support it.
