### ISSUE TITLE
In "Merge" name of text attachement is shown wrong.

### ISSUE THREAD

**Issue by fuel1986** [mbunkus/mkvtoolnix#1583]
Hello!
In "Edit headers" name of text attachment is shown correct. In "Merge" name of text attachement is shown wrong.
![01 edit headers correct](https://cloud.githubusercontent.com/assets/14252393/12700584/60dc9722-c7fa-11e5-81e6-0e7b2dcf16fe.jpg)
![02 merge wrong](https://cloud.githubusercontent.com/assets/14252393/12700585/60df40ee-c7fa-11e5-9317-27c860830d20.jpg)

**Comment by mbunkus** [comment]
Thanks, I'll fix that.
