### ISSUE TITLE
Automatic chapter generation when merging

### ISSUE THREAD

**Issue by isidroco** [mbunkus/mkvtoolnix#1586]
I'm always merging small video fragments into bigger ones. And I couldn't find a way to automatically have one chapter mark per appended video. It would be great if each chapter would have original AVI name. Another useful thing would be the oposite (generate one MKV per chapter). Thanks.

**Comment by mbunkus** [comment]
You can already split by chapters.

About generating chapters: I won't implement such a feature as it's very difficult to nearly impossible to implement this correctly and unambiguously. See [this post on Doom 9](http://forum.doom9.org/showthread.php?p=1743489#post1743489) for a list of some of those difficulties.

**Comment by mbunkus** [comment]
I've reconsidered.

**Comment by isidroco** [comment]
Thanks! This might help for instance to backup a full CD to a single MKV and to be able to regenerate original songs. (Would be great to be able to generate/import CUE CD files, but probably will program that myself.

**Comment by mbunkus** [comment]
mkvmerge has supported reading `.cue` and turning that information into chapters and tags since November 2003, seven months after its initial public release.
