### ISSUE TITLE
default additional command line options for tracks

### ISSUE THREAD

**Issue by mica** [mbunkus/mkvtoolnix#1589]
I assume it's because the commands are being placed after the input file. Here's my command (`--aspect-ratio 0:16/9`) as produced using "default additional command line options":

    "mkvmerge.exe" ^"--ui-language^" ^"en^" ^"--output^" ^"Output.mkv^" ^"--language^" ^"0:eng^" ^"--language^" ^"1:eng^" ( ^"Input.mp4^" ) ^"--aspect-ratio^" ^"0:16/9^" ^"--track-order^" ^"0:0,0:1^"

And here it is when using the "properties" panel:

    "mkvmerge.exe" ^"--ui-language^" ^"en^" ^"--output^" ^"Output.mkv^" ^"--language^" ^"0:eng^" ^"--aspect-ratio^" ^"0:16/9^" ^"--language^" ^"1:eng^" ( ^"Input.mp4^" ) ^"--track-order^" ^"0:0,0:1^"

The first fails to have effect on the output file, the second works fine.

**Comment by sneaker2** [comment]
This is by design. The additional commands you can enter in the output tab or settings are for global options only. Track-specific options are to be entered in the track property tab.

The reason is that you can have multiple input files. Then Mkvtoolnix GUI would not know which input file your "--aspect-ratio 0:16/9" command belongs to. Also, it could not automatically extend "--aspect-ratio <TID>:16/9 " to "--aspect-ratio 0:16/9" because it would not know the trackID either.

**Comment by mica** [comment]
In this case, I need to have this setting applied to a large number of files. There's no way I'm going through each tab to set this up. There ought to be some way to achieve this via the GUI.

**Comment by sneaker2** [comment]
Why don't you write a batch script?

```
for %%a in (*.mp4) do mkvmerge -o "%%~na.mkv" --aspect-ratio 0:16/9 --language 0:eng --language 1:eng ^( "%%a" ^)
```

**Comment by mica** [comment]
Yeah, that's what I'll do for now. But this kind of option would sure be nice to have in the GUI. 

I suppose this is a feature request then...

**Comment by mbunkus** [comment]
I won't implement default args for track-specific options. There are several _global_ options which make sense to require each and every time, especially regarding the compatibility with certain players and hardware devices (e.g. disabling lacing or disabling cue duration elements). Therefore there's the option for setting those for all mux settings by default.

The situation with track-specific options is different. There are only very few track-specific options that apply to all tracks. Among them are the track language and the extra compression, but for those two there are dedicated preferences available already, and those are partially track-type specific (e.g. you can set the default language for all subtitle tracks differently from the language for video tracks). This makes sense.

But a use case like yours, while being perfectly valid, is not an often encountered situation for users. Not all video tracks will always have the same aspect ratio. On top of that you only need to adjust the aspect ratio manually if mkvmerge's default handling of the aspect ratio fails for you.

So if there was such an option to set the default track-specific command-line arguments then it would solve this one particular use case, but it would be almost useless to almost all other use cases out there. It can even be confusing if you set track-specific options and forget about that only to discover that you've muxed several files with the wrong aspect ratio.

Sneaker2 has already shown you a simple batch file that can achieve what you want. You could also script something similar around mkvpropedit (getting the current pixel width/height from mkvmerge's [JSON identification output](https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.description.identification_format) first) if you don't want to re-write all the files.

**Comment by mica** [comment]
This sort of option could go in a different place, perhaps in the form of a preset templating system that could be applied to multiple files. Use cases where groups of identically encoded files need to be likewise remuxed in bulk aren't all too uncommon.

**Comment by mbunkus** [comment]
True, but implementing such profiles would require a huge amount of work to make it a useful feature. I'm not willing to invest that much time. Sorry.
