### ISSUE TITLE
DPI issue

### ISSUE THREAD

**Issue by Kelsett** [mbunkus/mkvtoolnix#1591]
Hello,

I've just updated from 8.6.x to 8.8.0 and I see you've tried to make some enhancements to the GUI on high DPI displays but it isn't quite working correctly here... (screenshot attached)

Pc: DELL XPS 15 9550 (laptop)
Display resolution: 3840x2160
Scaled up by 200%
Windows 10

![screenshot](https://cloud.githubusercontent.com/assets/11406670/12848001/59c1d3c8-cc17-11e5-8fc2-013ccf5e3ec8.png)

**Comment by mbunkus** [comment]
Please adjust the font size in the preferences.

**Comment by Kelsett** [comment]
Thank you, but should it not figure out the font size by itself like any other windows application ?

**Comment by mbunkus** [comment]
It tries to, but the algorithm is obviously not perfect. I currently don't have any plans on investing time in fixing it, especially as I lack displays with high resolution for testing.
