### ISSUE TITLE
add support for VTT subtitles

### ISSUE THREAD

**Issue by Klaus1189** [mbunkus/mkvtoolnix#1592]
Can you please add support for vtt subtitles?

**Comment by mbunkus** [comment]
Thanks. I currently don't have any plans for implementing support for WebVTT subtitles; nor for the foreseeable future. Sorry. See also #936.

**Comment by Klaus1189** [comment]
Aww, these are quite similar to srt ...

**Comment by mbunkus** [comment]
I've reconsidered.

**Comment by mbunkus** [comment]
*sigh* WebVTT is much more complex than simple SRT. I'll have to find a way to store e.g. the styling options. I will also have to decide how to deal with (or maybe completely drop) the cue information.

As it's much more than simple SRT I won't promise that I'll have it done in time for 9.0.0.

**Comment by Klaus1189** [comment]
OK, how are you doing with that issue?

MPC-BE developers have kindly added support of WebVTT subtitles:
Browse for r1207 [here:](https://sourceforge.net/p/mpcbe/code/commit_browser)

**Comment by mbunkus** [comment]
Well, looking at the commit it seems they're removing a lot of WebVTT features including cue information and included timestamps. That's not really supporting it, that's supporting a very reduced sub-set of it.

I'm not currently working on this. Don't expect me to either; I have enough more important things to do for the next couple of weeks.

**Comment by Klaus1189** [comment]
Yeah, you're right, YouTube only uses very simple version of WebVTT, very similar to srt, that's the reason why I thought it would be easy to add, but now I know, that the spec is very complex and will take some time to implement this.

**Comment by mbunkus** [comment]
Implemented in commits c0c8ea01aa6f4af2314c9f1f9ba566cedb4eed4b and 65e4d9c0820bf3cabba8152e8ea2a97c129b943d.
