### ISSUE TITLE
Impossible to save mkv after chapters have been removed

### ISSUE THREAD

**Issue by zak333** [mbunkus/mkvtoolnix#1593]
In mkvtoolnix-gui if you remove all chapters in a file the option to save is disabled.
Are matroska files supposed to have at least one chapter?

**Comment by mbunkus** [comment]
Thanks for the report. It's currently not possible to remove chapters from a file with the GUI, that's correct.

I'll think about how to implement it – removing all entries and then saving to a file seems kind of counter-intuitive for me. I'll likely add a separate menu entry for it.

**Comment by mbunkus** [comment]
I've implemented both: saving empty chapters to a Matroska file will remove the chapters from them. Additionally there's a new menu entry for selecting an existing Matroska file and removing all chapters from it.

**Comment by zak333** [comment]
Great! Thank you for your quick response and implemented solutions!

**Comment by mbunkus** [comment]
You're quite welcome.
