### ISSUE TITLE
MKVToolnix GUI header editor with a read-only file should display a less obscure error message

### ISSUE THREAD

**Issue by tophf** [mbunkus/mkvtoolnix#1594]
When a read-only file is drag'n'dropped onto header editor in MKVToolnixGUI it displays quite an obscure generic error message:

```
File parsing failed
---------------------------
The file you tried to open (.......) could not be read successfully.
```

This is misleading because a read-only file can still be read and parsed.
It would be better to warn that the file has a read-only attribute and any changes can't be saved but still show the data.

**Comment by mbunkus** [comment]
Thanks. I'll look into it.

**Comment by mbunkus** [comment]
I've improved the error messages and changed the GUI to open Matroska files in read-only mode by default. Only when the user tries to save are the files re-opened for writing.
