### ISSUE TITLE
corruption at file split for certain .ts files

### ISSUE THREAD

**Issue by kstathem** [mbunkus/mkvtoolnix#1595]
My satellite receiver (Geosatpro HD) splits its files at 1GB. The append and "add as additional parts" options both result in corruption at the split. I investigated with a hex editor and discovered that each file repeats the last 47KiB (exactly) of the previous file. After one copy of this duplicate information is removed, the "add as additional parts" option works correctly. I'm including ~200kb on both sides of each split along with all the other files in the folder.
[ts folder.zip](https://github.com/mbunkus/mkvtoolnix/files/131921/ts.folder.zip)

**Comment by mbunkus** [comment]
I'm sorry, but this is not a bug in mkvmerge. The "additional parts" feature is designed to work with files that have been split at arbitrary points (as they are on DVDs, for example, or if you use tools like Unix `split` or `WinSplit`), not for files that have some kind of overlap.

I won't implement functionality for dealing with such overlap either as in general you cannot simply try to detect arbitrary amounts
