### ISSUE TITLE
Add icons to right mouse menu in Attachments

### ISSUE THREAD

**Issue by igor2x** [mbunkus/mkvtoolnix#1596]
Hi,
using MKVToolNix GUI v8.8.0 on Ubuntu 14.04.

Compare:
- Merge outer tab | Input tab | Source files window | right mouse menu
- Merge outer tab | Attachments tab | Attachments window | right mouse menu
there are icons in front of right menu options in Input tab, but no icons in Attachments.

Enhancement request: Add icons to right mouse menu in Attachments.

Thanks

**Comment by mbunkus** [comment]
Thanks for the suggestion. Sure, why not? :)
