### ISSUE TITLE
Make the same right menu names in Attachments like it is already in Input tab right mouse menu

### ISSUE THREAD

**Issue by igor2x** [mbunkus/mkvtoolnix#1597]
Hi,
using MKVToolNix GUI v8.8.0 on Ubuntu 14.04.

Compare:
- Merge outer tab | Input tab | Source files window | right mouse menu
- Merge outer tab | Attachments tab | Attachments window | right mouse menu
the naming of menu options are different. In Input tab is "Add files", "Remove files" etc, but in Attachment there is only "Add", "Remove" etc.

Enhancement request: Make the same right menu names in Attachments like it is already in Input tab right mouse menu.

Thanks

**Comment by mbunkus** [comment]
Thanks for the suggestion. I'm not entirely sure whether or not I like such a change, but I'll think about it.

**Comment by igor2x** [comment]
Maybe additional argument to change this is like now only "Add" label it is unclear what is adding (files, labels, anything else?) and also it is unclear that multiple objects (files) can be selected. You know in Input tab there is "Add files" (so plural) and it is immediate clear that multiple files can be selected at once.

In my humble opinion when inconsistencies appear in program GUI design some strong argument should be placed to justify additional complexity end user has to deal with. So from end-user perspective this is most of the time highly important, more then adding tons of additional features.

But anyway, what ever decision you will make I will fully respect it, you are project maintainer. Thanks to listen to my humble suggestions.
