### ISSUE TITLE
Add "Remove completed jobs" option to "job queue" tab

### ISSUE THREAD

**Issue by igor2x** [mbunkus/mkvtoolnix#1598]
Hi,
using MKVToolNix GUI v8.8.0 on Ubuntu 14.04.

In "job queue" tab I suggest to add righ mouse menu option "Remove completed jobs", this option should appear ALSO if no job is selected. I have plenty of "completed OK" jobs and plenty o "running", so one mouse click to clear all of completed jobs would be wonderful. It would be nice if this option is also available during "running" of some of the jobs, so I could clear "completed jobs" with one simple click.

Enhancement request: Add "Remove completed jobs" option to "job queue" tab.

Thanks

**Comment by mbunkus** [comment]
Thanks for the suggestion, but no. That option already exists in the "job queue" menu in the menu bar. The reason that there are two separate menus is that the context menu's options only work on the selected jobs whereas the global "job queue" menu contains actions that work on the whole job queue regardless of which jobs are actually selected.
