### ISSUE TITLE
Frame rate change

### ISSUE THREAD

**Issue by EugeneF35** [mbunkus/mkvtoolnix#1600]
When I convert AVI file (H264) with fixed frame rate 59.94 fps to MKV file, the MKV file gets a variable frame rate  59.651 fps. It is not normal. It doesn't happened in old versions. MediaInfo of both files are attached. (MKVToolNix 8.8.0  x64)

[AVI.txt](https://github.com/mbunkus/mkvtoolnix/files/135296/AVI.txt)
[MKV.txt](https://github.com/mbunkus/mkvtoolnix/files/135297/MKV.txt)

**Comment by mbunkus** [comment]
I'm sorry, but this is not a bug in mkvmerge but an inaccuracy in how MediaInfo works. See [this wiki entry](/mbunkus/mkvtoolnix/wiki/Wrong-frame-rate-displayed) for an in-depth explanation why Matroska doesn't have a concept of a frame rate in the first place.
