### ISSUE TITLE
mkvtoolnix-gui header edit crash (program exits without message) and results in corrupt file

### ISSUE THREAD

**Issue by mykohsu** [mbunkus/mkvtoolnix#1601]
I have two MKV files that played fine.

However, I edited them to add default track flag and/or language tags for the embedded subtitles. GUI closes immediately upon saving. Re-opening the file shows all tracks are lost (but attachments are still available). Mkvinfo confirms the same.

1. VLC can no longer play the file. However, MPC still can after reading the whole file.
2. mkvextract can see streams but cannot extract the contents (only stream headers or partial content) even with -f.
```
Extracting track 0 with the CodecID 'V_MPEGH/ISO/HEVC' to the file '0'. Container format: hEVC/h.265 elementary stream
Extracting track 1 with the CodecID 'A_AAC' to the file '1'. Container format: raw AAC file with ADTS headers
Extracting track 2 with the CodecID 'S_TEXT/ASS' to the file '2'. Container format: SSA/ASS text subtitles
Progress: 100%
```
3. mkvmerge cannot see anything in the file: `No streams to output were found. Aborting.`

Because the issue happened on two different files, I believe it should be reproducible with the originals.

**Comment by mbunkus** [comment]
Thanks for the report. I've worked with the header editor a lot just today and have not had a single crash. It is therefore not a general problem that happens with all files, and I will need a sample file with which it happens in order to look into it.

Please try to re-create the crash (with copies of your good files only, of course!). If you find a file for which it happens then please upload the unmodified/original file to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can take a look at it. Thanks.

**Comment by mbunkus** [comment]
BTW: Which version of MKVToolNix GUI is this? And on which operating system?

**Comment by mykohsu** [comment]
Oh, it's definitely not a common problem - today is the first time I've ever had any issues. It looks like I don't have the original files anymore because I converted from original to HEVC. I am going to redo the conversion and see if it is reproducible.

Interestingly this was 2 out of 3 files converted together and the remaining one is fine.

This was with 8.8 on Windows 10 - the file is accessed over a network connection.

**Comment by mbunkus** [comment]
Thanks. I appreciate it.

**Comment by mykohsu** [comment]
Well, looks like good news or bad news :)

I re-encoded the files, with Handbrake 10.2.7286; with different settings, apparently, because the output is smaller. But the same issue happens to both files.

Just tested with v8.9.0 and still the same issue.

**Comment by mbunkus** [comment]
That is indeed good news. Bugs are an unfortunate reality, and being able to trigger them reliably is definitely great :) Thanks.

**Comment by mbunkus** [comment]
I can reproduce it here. Thanks again for the file. I'll look into it, but as I'm kind of busy at the moment I cannot say when it'll be fixed.

**Comment by mbunkus** [comment]
The issue is triggered by HandBrake using a special value meaning »unknown element size« for its last cluster. That is spec-compliant, but the file modification code shared by the header editor and mkvpropedit cannot deal with that yet. I'll fix it.
