### ISSUE TITLE
Mkvtoolnix GUI scaling problems on UHD screens

### ISSUE THREAD

**Issue by mcleinn** [mbunkus/mkvtoolnix#1602]
I'm running Mkvtoolnix-GUI.exe 8.8.0 on my 15" 3840x2160 UHD screen under Windows 10. The system scaling is set to 200% (otherwise app windows would by miniscule and unusable). The default font size of Mkvtoolnix is (at least) twice bigger as standard Windows fonts and thus creates the effect of wrong scaling. The problem disappeared after changing the settings. Please see the attached screenshot.

![mkvtoolnix](https://cloud.githubusercontent.com/assets/3145561/13197659/1cf34a16-d7fd-11e5-82e0-12551f1fe0d3.jpg)

**Comment by mbunkus** [comment]
You can change the font size in the preferences.

I know the default font size calculation has its problems, but I don't have ANY high-DPI displays available. Not even at work. So experimenting and getting this right is kind of hard. I know that Qt page, but I don't find it all that helpful.

I'd appreciate patches that improve the situation. I won't work on this any time soon due to the reason stated above.

**Comment by mbunkus** [comment]
Can you please do me a favor? I've created a small exe that opens a small window and displays a couple of basic parameters about your screen (logical dots per inch, physical dots per inch, default font etc.). Can you please [download it](https://bunkus.org/misc/qt-screen-props.7z), run it and attach a screenshot of the values it shows here? Thanks.

**Comment by mcleinn** [comment]
Hallo!

ich denke ein Copy & Paste tut es auch:

geoemtry: 1920x1080

logicalDPI: 96

physicalDPI: 141.175

default font family: MS Shell Dlg 2

default font size pixels/points: -1/8

device pixel ratio: 2


Grüße! Tobias

2016-02-21 17:52 GMT+02:00 Moritz Bunkus <notifications@github.com>:

**Comment by mcleinn** [comment]
Falls ein echter Screenshot doch für Vergleichszwecke benötigt wird,
befindet sich dieser im Anhang.

2016-02-21 21:56 GMT+02:00 Tobias Weihmann <tobias@weihmann.se>:

**Comment by mbunkus** [comment]
Thanks, but the text suffices, of course. Initially I wasn't quite sure whether or not the application allowed copying the text at all, hence me requesting a screenshot before editing that comment.

**Comment by mcleinn** [comment]
By the way, the MS Shell Dlg 2 font mentioned indeed turns out to be much
more readable  than the default Segoe. And 8 point is also a good choice
for my setup.



2016-02-21 22:37 GMT+02:00 Moritz Bunkus <notifications@github.com>:

**Comment by mcleinn** [comment]
However, even at that setting. the font rendering is still sub-optimal.
Maybe it's possible to change the rendering mode.

2016-02-21 23:00 GMT+02:00 Tobias Weihmann <tobias@weihmann.se>:

**Comment by mbunkus** [comment]
I don't set anything regarding the font rendering, and I highly doubt there IS anything to set in this regard inside Qt itself…

**Comment by mcleinn** [comment]
Did you see the two red arrows in the attached picture which I added in my
last message? (it is visible from the Bug tracker at least). If you do a
quick search for Qt Text Redering you will see there are several switches
for influencing text rendering, but I am not sure if this is the solution.


2016-02-22 10:12 GMT+02:00 Moritz Bunkus <notifications@github.com>:

**Comment by mcleinn** [comment]
I found several links to command line parameters and this:
http://doc.qt.io/qt-4.8/qpainter.html#RenderHint-enum - but I am not sure
if it effects kerning.

2016-02-22 11:06 GMT+02:00 Tobias Weihmann <tobias@weihmann.se>:

**Comment by mcleinn** [comment]
There is some stuff here, too. http://doc.qt.io/qt-4.8/qfont.html#setKerning
- but I agree that it can be too much of a hazzle, if you don't see the
issue yourself. So maybe better leave it for the future.

2016-02-22 11:10 GMT+02:00 Tobias Weihmann <tobias@weihmann.se>:

**Comment by mbunkus** [comment]
I do see the issue in your screenshot but not on my Windows, for example. I use Qt's defaults everywhere in this regard. I also don't see the use in experimenting with those settings as changing them will most likely make the situation worse for some people/on some installations even if it improves them for you. Sorry.

**Comment by mcleinn** [comment]
Ok, no problem. In case there are more reports about UHD one might try
QFont::setLetterSpacing(*QFont::PercentageSpacing, 200). *

2016-02-22 11:22 GMT+02:00 Moritz Bunkus <notifications@github.com>:

**Comment by mbunkus** [comment]
I've released v8.9.0 yesterday. Right before the release I've deactivated the automatic font size calculation that I've introduced a while ago due to this issue. Can you please give 8.9.0 a try?

In order for this to work you'll have to remove the `uiFontPointSize` setting from the [stored settings](/mbunkus/mkvtoolnix/wiki/Settings-location) first (make sure the GUI isn't running at that point). Then start v8.9.0. The font size should now be the default for Windows, 8 points. Thanks.

**Comment by mcleinn** [comment]
Thank you. The font size is correct now. 
![win1](https://cloud.githubusercontent.com/assets/3145561/13222929/e782cade-d98a-11e5-905e-499b8567ea6b.jpg)

For future optimization, I'd suggest to use the MS Shell Dlg 2 font instead of the default "Segoe UI" font, which looks very inconsistent to other Windows applications.
![win2](https://cloud.githubusercontent.com/assets/3145561/13222979/2a594c7a-d98b-11e5-87a1-653cfa63b657.png)

Other than that, I'm suspecting that something is causing the font to be "narrow", which might be solved by the mentioned QFont::setLetterSpacing(*QFont::PercentageSpacing, 200) - but I agree that it might be risky to implement this based only on one test system.

Thank you.

**Comment by mbunkus** [comment]
Then I consider this to be solved for the time being. Thanks.
