### ISSUE TITLE
MKVToolNix GUI: Cosmetic issue with tabs and file names containing ampersands (&)

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1603]
Wherever tabs show file names (merge, edit headers, edit chapters), an issue exists when the file path contains an ampersand (&). The tab control interprets the ampersand as a mnemonic for a key shortcut/accelerator, thus rendering the file name in the tab incorrectly as well as setting up a new keyboard shortcut.

For example, if you choose an output file name "Red&Green" in the merge mode, the associated tab will show "RedGreen" with the letter G being underlined. Also, this tab will now react to the Alt+G keyboard shortcut.

Note that this issue does not affect the operation of MKVToolNix; however, for users accustomed to keyboard shortcuts it can lead to some confusion and unexpected GUI behavior when a file path with an ampersand results in a mnemonic for a keyboard shortcut that is already used by MKVToolNix GUI (such as Alt+G in my example above, which is the keyboard shortcut for the "MkvToolNix GUI" main menu entry).

I guess one possible fix would be to replace all occurrences of an ampersand (&) with a double ampersand (&&) in the tab title strings (&& is the 'encoding' for a literal ampersand character used by controls parsing for keyboard shortcut mnemonics -- at least on Windows it is).

I am not sure whether this issue is specific to Windows only or whether it also occurs on other OS's, since i don't know whether QT itself or the underlying OS is doing the ampersand parsing.

MKVToolNix 8.8.0
MS Windows 7 Pro x64 english

**Comment by mbunkus** [comment]
Thanks for the report. I'll fix it.
