### ISSUE TITLE
mkvextract Opus file extension should be .opus

### ISSUE THREAD

**Issue by repaxan** [mbunkus/mkvtoolnix#1606]
Hi, very minor issue here, but extracting an Opus audio track creates a opus-in-ogg file with extension .ogg where it should be .opus instead:

https://wiki.xiph.org/index.php/MIME_Types_and_File_Extensions#.opus_-_audio.2Fogg

**Comment by mbunkus** [comment]
mkvextract does NOT do anything with file names. It writes into the very file name you specify on the command line, be it `.ogg`, `.opus` or `.bubbles`.

In case you're actually using and talking about mkvextract-gui: that program is not part of MKVToolNix; it's not one of my programs.
