### ISSUE TITLE
attachment crash !

### ISSUE THREAD

**Issue by bunreet** [mbunkus/mkvtoolnix#1608]
hi i am mkvtolnix 32 bit v8.9.0 (Father Daughter) portable version user I attachments function added any file but the program crashes setup version not crashes is working.Please let me thank you for this bug.
![ekran alintisi](https://cloud.githubusercontent.com/assets/17417280/13234379/03ea7d8a-d9c1-11e5-8551-c026f9df2b81.PNG)

**Comment by mbunkus** [comment]
This is most likely your fault for using the .exe without its accompanying files. See #1464 for example.

"Portable" doesn't mean that you can simply take only the exe and remove everything else. It means that you can use the exe with its accompanying files from anywhere. Additionally it means that everything (e.g. settings) is stored in the same folder the exe itself is located it.
