### ISSUE TITLE
extract simple chapter names in a given language - only half of names extracted

### ISSUE THREAD

**Issue by zootie** [mbunkus/mkvtoolnix#1610]
Trying with v8.9.0 on windows 10 x64.

I made a chapter list and added multi-language chapter names (in English and Spanish).

When I try and use _mkvextract chapters --simple <pathtomkv>_, I get a list of chapters in both languages, that gets cut off "halfway" (it mixes both languages and stops when it hits the total number of chapters). I tried using the -_-ui-language code_ parameter, to see if it would use a specific translation then, but it doesn't seem to apply (didn't see any other parameters that would specify the chapter names language to extract).

For "Love Never Dies" (see attachments), The chapter list has 33 chapters on the first level, and many have a second level (for a total of 53 chapters overall). The generated simple output has 53 chapters, almost alternating English and Spanish names (it doesn't always alternate one after the other, it might be the order in which I added /edit them). 

Also in "Love Never Dies", the last chapter name exported is named Entr'acte, unsure if the quote is causing the exit, or if it just halfway the generation (ie, it exports half the names because that is the number of chapters, but since there are 2 versions, it ends before exporting all the names). Considering that it behave similarly with the other case (exports half the names, mixing both languages), it seems to be the number of chapters (and it being unaware of multiple languages when extracting with the names).

I'm trying to export the files as simple so I can try and load them with ChapterGrabber and upload them to ChapterDB (which is the only service I know of where you can share chapter names). I'm mostly considering simple extraction in a given language for this, but it might be a good idea to also support extraction in a given language for XML format (ie, for SW that is XML aware, but doesn't support multi-lingual chapter names).

As additions/suggestions:

- It would be nice to be able to specify the depth of chapters to extract (at least when doing simple extraction, could apply to XML extraction too). For example, with a few of the movies I've seen, they tend to have a small number of chapters, with little detail, but for a collector, you might want to have a more refined chapter list (as sub-chapters of the "canonical" chapters), yet still be able to export them resembling the original chapter structure. 
- Also, when trimming to a given depth (for simple or XML), an option would be to append children chapter names to the parent's name (ie, to be able to name generate a flat chapter list, yet have the children names). There could be an option of delimiter to use (/) and maybe to include all sub-chapter names or just the last child (as a name range).
- Another possible feature would be to be able to resync chapter timecodes (ie, resync using the first level chapters from a different XML file, assuming that both files have the same number of chapters on the first level.
- While functionally similar to a chapter, it might be useful to flag a timecode as a bookmark rather than a chapter mark (ie, indicate an important event, not necessarily "breaking" the chapter - or maybe should use yet another sub-level). Being able to have a bookmark flag could allow to allow for cross-edition references (ie, not having to have all the chapters synched for different editions/distributions, just key moments)
- Being able to flag specific chapters as critical or key (unsure if this would be more about a different edition, but most players don't seem aware of editions - tried MPC-HC and VLC, VLC seemed to identify a second edition as a title, but wouldn't respect it, and would revert to the original chapter list -maybe because I flagged the original edition as default)
- Probably out of scope: Upload to ChapterDB (or other chapter sharing service you might recommend). ChapterGrabber seems like abandonware (unsure if the API is functional enough to allow for editing of a given chapter list, to correct own mistakes on ChapterDB - ChapterGrabber doesn't seem to support this - and given that the save is tied with the upload, there are many chapter lists halfway done, some probably due to ChapterGrabber confusing UI)
- Probably out of scope: Export to Handbrake CSV (which doesn't seem to handle tabs and quotes very well). - In truth, Handbrake should support XML formatted chapters (or the user should use mkvtoolnix, but it can be daunting to begin using it - it is easier than I expected, with a good UI, but it requires the user taking a leap to begin using it - I've been using Handbrake for about 4 years, and didn't start using mkvtoolnix until a few months ago - after seeing references about it for years, just feeling it would be too much work for a pass time activity).

Thanks

(rename .xml.txt back to just .xml for the XML chapters version - used mkvpropedit to inject back into MKV and then used mkvextract to generate the simple txt)

[Love Never Dies (2012).chapters.xml.txt](https://github.com/mbunkus/mkvtoolnix/files/144092/Love.Never.Dies.2012.chapters.xml.txt)
[Love Never Dies (2012).chapters.txt](https://github.com/mbunkus/mkvtoolnix/files/144090/Love.Never.Dies.2012.chapters.txt)

[The Phantom of the Opera 2004.fixed.chapters.xml.txt](https://github.com/mbunkus/mkvtoolnix/files/144101/The.Phantom.of.the.Opera.2004.fixed.chapters.xml.txt)
[The Phantom of the Opera 2004.fixed.chapters.txt](https://github.com/mbunkus/mkvtoolnix/files/144105/The.Phantom.of.the.Opera.2004.fixed.chapters.txt)

**Comment by mbunkus** [comment]
Thanks for the extensive report. I'll look into it.

**Comment by mbunkus** [comment]
I'm fixing the bug present here and I'm implementing selecting which chapter names to output by their language in simple extract mode only. I won't implement any of your additional suggestions as I consider those to be of very limited use to a very limited number of users. The amount of time required for implementing those options is simply way out of line for the potential gain. I'm sorry.

I also don't want to spend any more time than necessary on the simple chapter format. It is very limited in what it can express; therefore only basic support will be given for it. mkvextract will only extract the top-most atoms, for example; there won't be any handling of nested atoms.
