### ISSUE TITLE
Muxing (HEVC + AAC) does not start

### ISSUE THREAD

**Issue by hydra44** [mbunkus/mkvtoolnix#1611]
I've encoded a cartoon using the latest x265.exe (ver. 1.9_15 64bit 10bit-color)
Now I tried to mux it with its AAC audio part.
This worked fine, but I noticed a shift in the Audio sync ... which seems impossible to correct by a simple "Delay". 
So I extracted the Audi timecodes using mkvextract: mkvextract.exe" timecodes_v2 "org movie.mkv" 1:audio_timestamps.txt

Afterwards I want to multiplex all the stuff together again using the MkvToolnixGUI.exe ver. 8.9.0 
So I add the vid and aud part and select the audio_timestamps.txt in the "timestamp file" section.
But now - when pressing mux-start" - nothing happens 
No error message,
No warnings
No indication in the progress bar
But job is running ...
I canceled the process after 10 min ...

Can you please have a look

**Comment by mbunkus** [comment]
Have you actually looked at the "job output" tool after pressing "start muxing"?

**Comment by hydra44** [comment]
yes.
All looked perfectly fine ... like ok, I'm gonna start muxing any minute ... No Errors, no (muxing related) warnings - only the "--aac-is-sbr 0" arn poped up.

However, so after a couple of tries I thought about giving up. I had one last job and then I went off to lunch.
When I came back the "job output" said:
Das Muxen dauerte 16 Minuten 22 Sekunden. - Muxing took 16 min.

So, can we say: it works, but is extremely slow ? 
Muxing without the timecodes would finish the file in aprox 1:30 min ... (aprox. 105k frames)

I was gone, so I'm not sure if the progress bar shows anything ... however it doesn't for at least 10 min.

**Comment by mbunkus** [comment]
If a warning was shown then at least a couple of normal information lines must have been shown as well. That warning is only triggered after the file(s) have been opened, after the packetizer have been created. All those events cause a line to be output. Therefore what you're writing doesn't really make sense to me yet.

I also cannot reproduce anything like this here. If you want me to investigate then I'll need access to the source files (the .h264, the audio file and the timecode file) before muxing. You can upload some to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by hydra44** [comment]
Bear in mind this happens with HEVC -> .h265 Files.
My file is a bit big (1.4 GB), but I'll try to reproduce it with another clip and upload this one

**Comment by mbunkus** [comment]
I know. I've tried this with HEVC files with external timecode files. Yes, mkvmerge takes a couple of seconds with HEVC files until it actually starts (that's normal as HEVC detection is fragile and very far down in the list of file formats to try to detect), but even reading from a network share this is done in ~3 seconds here in my case with a 2.2 GB test file. The status bar starts its progress then, and the »job output« tab shows several lines in the »normal output« section. Hence me asking you for a file.

**Comment by mbunkus** [comment]
Have you made any progress in reproducing the issue with a smaller file?

**Comment by mbunkus** [comment]
I'm closing this issue due to lack of feedback.
