### ISSUE TITLE
Duplicated hotkeys

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1614]
**P r e f a c e**

A few days ago I decided to implement a very important change in my Polish translation. So: I have placed hotkeys (keyboard shortcuts) in the parentheses/brackets; e.g. **(&A)**. Such a solution is very controversial for some users, but in my opinion it's absolutely fantastic and has many underrated advantages. For example: 

► The keyboard users don't have to read the whole text (especially if it's very long) to find a proper letter (hotkey) as the letter is exhibited in the parenthesis = fast access
► It allows maintainer(s) to avoid many bugs related to duplicated hotkeys because the letters in the parentheses are very clear (big) so it's very easy to compare them (looking on the GUI) and then choose a proper (unique) character
► Even a person who has a problem with an eyesight (e.g. Myopia) may notice them easily (as they're big and placed in the parentheses) etc..........

But let's go back to the issue :)

So: in order to avoid unnecessary problems in my Polish translation, I decided to make hotkeys exactly the same (equal) like in the original text (English). E.g.: **&Help = Pomoc (&H)**. Unfortunately [but thanks to my solution :)] I have found some bugs (duplicated hotkeys) in the original text (English). Here are four examples to fix:

1) http://s10.postimg.org/rrohi45qh/Header_editor.png

2) http://s10.postimg.org/t466k0361/Chapter_editor.png

3) http://s10.postimg.org/q15ggmo7d/Job_queue.png

4) http://s10.postimg.org/rdn5iilmx/Executing_programs.png

Make them unique, please, but be careful about other letters (hotkeys).

BTW: here's my humble (but important) request to you: http://s7.postimg.org/ewlgtdgh7/Hotkeys_to_add.png

Thank you very much in advance.

**Comment by sirdanielk** [comment]
Comment on "preface".
Why to put **main** menu hotkeys buttons into translation? I think none of applications show **main** menu keyboard shortcuts, i didnt encountered any recently. And if was used, then was dropped long ago. 
Windows has feature of underlining hotkeys (Ease of acces settings), and mkvtoolnix is compatible with it. I guess any person with eye sight problem should have preconfigured system. Rest of people sure have no problem with reading sentences and catching underline letter, so if they want use more keyboard than mouse, then they can turn appropiate option in Windows OS too.
I think more professionally would be to leave in translation shortcuts in brackets that occur only in dropdown menu, and thats only because mkvtoolnix has already some dropdown menu shortcuts visible like Ctrl+N or Ctrl+W.
I would recommend **main** menu shortcuts like Pomoc (H) to remove.

**Comment by remuxer32** [comment]
**@ sirdanielk**

As we both speak Polish, then please let me reply in our native language. Thanks to that my reply will be more more understandable for you.

Tak jak napisałem na samym początku: jest to rozwiązanie bardzo kontrowersyjne dla niektórych użytkowników, ale dokładnie przeze mnie przemyślane i w końcu — wdrożone. 

Napisałeś, że, jak sądzisz, żadna z aplikacji nie pokazuje głównych skrótów klawiaturowych (oczywiście chodzi o to, że są w nawiasach). Otóż mylisz się: jest taka jedna aplikacja (i to bardzo popularna), gdzie zastosowano takie rozwiązanie: odtwarzacz VLC. Uruchom go, proszę, rozwiń któreś z rozwijalnych menu (tych na górze) i zobaczysz, że polski tłumacz(e) zastosował tam takie rozwiązanie. Jedyna różnica to taka, że tam zastosowano małe litery w nawiasach, a ja zastosowałem duże. Oczywiście nie we wszystkich miejscach napotkasz tam "hotkejsy" w nawiasach, ale jest ich bardzo dużo. No i oczywiście języki azjatyckie: tam tłumacze stosują oryginalne "hotkejsy" w nawiasach. Tak, wiem, że języki azjatyckie to inne litery/znaki, więc takie coś jest niejako konieczne, ale, mimo to, jest to warte odnotowania.

A teraz przejdźmy do naszego kochanego MKVToolNix. Główna idea w przypadku stosowania skrótów klawiaturowych jest taka, że KAŻDY taki skrót musi być unikalny — to znaczy, że nie może się powtarzać. W przeciwnym razie dojdze do konfliktu, jeśli jakiś użytkownik zechce coś uruchomić za pomocą klawiatury. Otóż przed wprowadzeniem mojego rozwiązania w polskim tłumaczeniu, MNÓSTWO skrótów klawiaturowych (które nie były w nawiasach) było zduplikowanych — powtarzało się). Jednym z głównych powodów takiej sytuacji był fakt, iż w języku polskim nie stosuje się takich liter, jak: **Q, X, V**, a które to są obecne w języku angielskim. Tak się składa, że Moritz w bardzo wielu miejscach umieścił skrót (&) obok takiej litery właśnie, której nie ma w j. polskim. Dla przykładu niech będzie słowo "Exit" (E&xit). W takiej sytuacji dla mnie, jako polskiego tłumacza, powstał problem typu: obok której litery umieścić skrót (ampersand) skoro nie ma jej (X) w języku polskim. No to powiedzmy, że umieszczę ją obok byle jakiej litery. Cóż, w takiej sytuacji właśnie powstał problem duplikacji skrótów — to znaczy, że dwa (lub więcej nawet) różne słowa/zdania miały ten sam skót = oczywisty konflikt. Tak więc zacząłem się zastanawiać, jak temu zaradzić: czy mam przeglądać WSZYSTKIE linie/zdania i poprawiać skróty tak, aby były unikalne w języku polskim i aby nie trzeba było stosować oryginalnych skrótów (co się wiąże z bardzo długą pracą przed kompem) czy też zastosować inne — trochę szybsze i bardziej kontrowersyjne — rozwiązanie, czyli oryginalne skróty umieszczone w nawiasach. Wybrałem właśnie tę drugą opcję z pełną świadomością zalet (jest ich bardzo wiele), ale również wad (trochę brzydki i długi wygląd zdań, na końcu których są te litery w nawiasach właśnie). 

Zauważ proszę, że ten "Issue", który tutaj założyłem, a który dotyczy zduplikowanych "hotkejsów" w jezyku oryginalnym (angielskim), został założony tylko dlatego, że ja sam wprowadziłem właśnie takie rozwiązanie w polskim tłumaczeniu (skróty w nawiasach, które łatwo zauważyć i porównać) i dzięki temu błyskawicznie wykryłem (porównałem) kilka zduplikowanych "hotkejsów", a następnie zgłosiłem je tutaj w formie screenshotów. Gdyby nie mój pomysł (skróty w nawiasach), to Moritz prawdopodobnie nigdy nie odkryłby tego problemu, bo ja sam (ani chyba nikt inny) bym tego nie zauważył bez nawiasów. Ale na szczeście zostało to odkryte (dzięki DUŻYM i WIDOCZNYM literom w nawiasach) i naprawione. Tak więc sam widzisz: z pozoru kontrowersyjny pomysł może przynieść bardzo wiele zalet w postaci wykrycia błędów i zgłoszenia ich autorowi. Uważam, że należy to docenić i zapisać jako kolejną zaletę dla mojego pomysłu.

Przejdźmy dalej. Napisałeś, że system Windows posiada możliwość podkreślania skrótów i że działa to w przypadku MKVToolNix. Tak, owszem, działa, tylko zauważ, że w przypadku bardzo długich/rozbudowanych zdań, zawierających takie skróty, trzeba się naszukać (przeczytać całe zdanie) zanim znajdzie się taki podkreślony skrót. W przypadku skrótów w nawiasach nie ma potrzeby czytania całego zdania, ponieważ skrót jest od razu widoczny w nawiasie (można rzecz, iż jest "oczojebny" ☺). Dla osoby, która bardzo często używa GUI i pamięta, do czego służy dana opcja bez czytania, a która lubi korzystać z klawiatury, takie rozwiązanie jest bardzo przydatne, bo pozwala zaoszczędzić czas na wpatrywanie się w tekst i wyłapywanie danego skrótu — bo wystarczy spojrzeć na literę w nawiasie ☺.

Odnośnie osób, które mają problemy ze wzrokiem i pre-konfigurowanego systemu dla nich: otóż wady/choroby wzroku są różne i nie każda taka przypadłość wymaga specjalnie przygotowanego systemu. Istnieją bardzo lekkie wady (jak wspomniana przeze mnie "Myopia", czyli z greki: krótkowzroczność), które (jeśli nie są zaawansowane) wymagają zaledwie korekty w postaci okularów (szkieł), aby móc swobodnie pracować przed komputerem. Sam mam wadę wzroku (noszę okulary), więc wiem, o czym piszę. I wierz mi: naprawdę nie potrzeba specjalnie przygotowanego systemu, aby móc pracować wydajnie. A takie skróty w nawiasach mogą tylko pomóc jeszcze lepiej (to znaczy: szybciej) obsługiwać program.

W ostatnim akapicie napisałeś, że bardziej profesjonalnie byłoby pozostawić te skróty w nawiasach, ale tylko w menu rozwijanych. A resztę skrótów co? Usuwamy? Otóż nie, nie zgadzam się. Nie po to poświęciłem tyle czasu naprawiając problem ze zduplikowanymi skrótami w polskim tłumaczeniu (które nie były w nawisach rzecz jasna), aby teraz to wszystko zniszczyć (usuwać). Jeśli jednak odważysz się to zrobić i powrócić do tego co było, to wiedz, że istnieje duże prawdopodobieństwo, że znowu wystąpi ten sam problem, czyli zduplikowane sktóty w polskim tłumaczeniu (na 99% tak właśnie będzie). Naprawdę tego chcesz? Bo ja nie. Właśnie dlatego te skróty (tak jak w oryginale) są w nawiasach, aby uniknąć problemu z ich duplikacją. Wiadomo w końcu, że litery w nawiasach o wiele łatwiej jest porównać i naprawić, niż gdyby były podkreślone (wpatrywanie się w tekst i ich wyłapywanie). I oczywiście różnice między angielskim a polskim (wspomniane litery: Q, X, V, których nie ma w polszczyźnie pisanej), które zadecydowały o umieszczeniu oryginalnych skrótów w nawiasach.

Reasumując: stanowczo nie zgadzam się na jakąkolwiek ingerencję w skróty. Wszystko ma zostać tak, jak jest. To, że, być może, GUI będzie wygląć trochę brzydziej i "nieprofesjonalnie" nie jest powodem, aby zabierać użytkownikom możliwość błyskawicznego dostępu do nich (w nawiasach są bardziej wyraziste i łatwiej je porównać, a także — bez wątpienia — można szybciej uruchomić jakąś opcję bez konieczności czytania długo zdania).  

Pozdrawiam.

**Comment by sirdanielk** [comment]
I really regret you wrote such reply in polish. Unfortunately none but us can understand that.
You mix in your above reply such cases as: duplicated hotkeys in english translation, duplicated hotkeys in polish translation and nonexistent issue with assigning polish letters to hotkeys.
This issue - #1614 might be added value. Lets leave this as is.

I still see no point of adding hotkey letters next to the buttons in main menu (in translation). Theese just strikes me in the eye. You make "solution" to what exists already - mentioned Ease of access settings. 
I said already that dropdown menu is ok to displaying hotkeys, just as other hardcoded hotkeys in mkvtoolnix. It would be nice that mkvtoolnix code could display localized hotkeys in dropdown menu, but lets not add more work for program's author.
VLC is a bad example. Its polish translation was half-mashine translated last time i used this player, now it may be better. But even this player has no hotkeys displaying next to the main menu buttons. Only some hotkeys in dropdown menu.
Why just not let be consistent with the rest part of the world? Is uglier, unprofessional front program view that really better because has some "solution"?
I will add to your knowledge, that assigning "polish" letter (in fact latin) after & sign, makes it hotkey, so virtual issue of duplicating polish hotkeys does not exist, because translator has ability to assign any letter he wants. So i see no point in keeping equivalents of hotkeys from english translation. Polish letter should be underlined and that is enough for it.
I really once more recommend to remove hotkeys in brackets from front view as it just strikes into eye and recommend bring back polish hotkeys (unduplicated), as there is no point in making "solutions" for problems that already has a solution. 
I never said about removing hotkeys from the program funcionality, only from the translation (program front-view).
Thanks.

**Comment by remuxer32** [comment]
>I really regret you wrote such reply in polish. Unfortunately none but us can understand that.

I wrote my reply in Polish because the topic you started applies to, in fact, our Polish translation (original hotkeys in brackets). Also: you and I = we are both Polish translators of MKVToolNix, and we speak Polish perfectly; hence I decided to reply in our native language in order to give you my point of view very clear. You should be proud of that — I did it exclusively for you. 
About other guys who won't understand my last comment in Polish: so what? This topic is special as it applies to the particular issue. They don't need to know anything about our deliberation. Believe me: most people don't care about such minor things/topics at all. Furthermore: many people are lazy = if they see very long text, then they don't read it at all. Sloth is deeply hidden in the human nature. Anyway: if you prefer my replies in English, then I'm OK with it.

>I still see no point of adding hotkey letters next to the buttons in main menu (in translation). Theese just strikes me in the eye. 

Striking in the eyes is something that I understand very well — it's indeed a serious disadvantage of my idea. I've implemented the original hotkeys everywhere (next to the buttons in the main menu, too) because in my life I don't accpet any half-measures. I always go all out.

>I said already that dropdown menu is ok to displaying hotkeys, just as other hardcoded hotkeys in mkvtoolnix. It would be nice that mkvtoolnix code could display localized hotkeys in dropdown menu, but lets not add more work for program's author.

I perfectly know what you said (to be precise: wrote). You want me to remove the hotkeys in brackets next to the buttons (main menu), but leave them in the drop-down menus only.

>VLC is a bad example. Its polish translation was half-mashine translated last time i used this player, now it may be better. But even this player has no hotkeys displaying next to the main menu buttons. Only some hotkeys in dropdown menu.

VLC **is** a very good example because it shows that you can find hotkeys in brackets in a popular application. I don't know if it was half-mashine translated or not (I'm using the latest version), but the main fact is absolutely clear: Polish guys used **original** hotkeys in translation. Yes, I know that VLC has no hotkeys next to the main menu buttons, but it has many (yes: many, not some) hotkeys in the drop-down menu, and some in the........ context menu; yes, in the context menu — I've just checked it.

>I will add to your knowledge, that assigning "polish" letter (in fact latin) after & sign, makes it hotkey, so virtual issue of duplicating polish hotkeys does not exist, because translator has ability to assign any letter he wants. So i see no point in keeping equivalents of hotkeys from english translation. Polish letter should be underlined and that is enough for it.

I know very well how to make a hotkey. And yes, I know that there is a possibility to assign any letter I want, but making all of the letters unique (unduplicated) in the Polish translation would require a lot of work as I would have to find an alternative letter for strings where Moritz used such hotkeys (letters) like: **Q, X, V** which do not exist in a Polish language. Some examples for you: E&xit, Mu&x this track, Add &variable, Add to job &queue, etc. Simply I would have to be very careful when adding the ampersand (**&**) into the Polish words in order not make a mistake (duplicated hotkeys in the Polish translation). Hence I decided to implement the original hotkeys in brackets: that solution seemed to be much safer & faster for me.

Summarizing: I have a good news for you. I guess you'll be surprised. So: I have re-considered my point of view and decided to take into consideration your arguments. The irrevocable decision is: I will completely revert (remove) all of my changes (hotkeys in brackets). It means that you won't see any hotkeys in brackets next to the string(s). It also applies to the drop-down menu: many of entries have a keyboard shortcut visible (e.g. CTRL + W) so I don't want to leave a second one in a bracket. Therefore I will return to the "classical" form of putting hotkeys (**&**) = at the beginning or in the middle of the word (depends on the situation of course). Yes, I know it will take tons of my time to make them unique, but, anyway, I'm willing to do it myself. Don't worry: there won't be any duplicated hotkeys in the Polish translation anymore. I'll care about it.

Regards.

**Comment by sirdanielk** [comment]
Thank you Jan for rethinking that case. Any new translation you add is valuable. Im sure we or other users value a slick and clean user interface too.

I strongly belive that hotkeys do not have to be unique. I mean they have to be different at given menu level or on the page. But in different places on different levels of the menu, you can assign the same letter. If you later turn on in windows option of "permament uderline hotkeys" in ease of access settings, then you can very easy scan menu of mkvtoolnix for keys assignment and find duplicates. It would take minute or two. Also dont worry about q, v, x letters, use any other letter from the translated polish word, it usually is the first, the second or the third letter.
Thanks.

**Comment by remuxer32** [comment]
>If you later turn on in windows option of "permament uderline hotkeys" in ease of access settings, then you can very easy scan menu of mkvtoolnix for keys assignment and find duplicates.

Yes, yesterday I enabled that option in the control panel on my Windows 7. I'm going to definitely use that in order to find possible duplicates. It will help me to save some time when assigning letters.

Thanks.

**Comment by remuxer32** [comment]
**@ Daniel**

Mission complete. I completely removed hotkeys in brackets, and returned to the classical method. Now the letters are underlined :)

See also: 2d503dd

**Comment by sirdanielk** [comment]
Hey, good job :)

Hint just for the future. 
We talked about readability. Some letters are too short to make them hotkeys/accelerators. Theese are i or j or l letters for example (but kapital J would be ok like in Język). So usually if not first letters, we can use second ones. Or letter from "key" word when we deal with long sentence. 
Just like in front menu: Wejście and Wyjście. More cleaner would be to use e and y letters instead of small i and j. E and y do not occure on any other tab i believe, so no duplicates. But thats just cosmetics.

**Comment by remuxer32** [comment]
>Some letters are too small to make them hotkeys/accelerators. Just like in front menu: Wejście and Wyjście. More cleaner would be to use e and y letters instead of small i and j. E and y do not occure on any other tab i believe, so no duplicates. But thats just cosmetics.

Hey, thanks for the hint. Yes, I know that such small letters like **i** or **j** look really bad (especially underlined on Windows), but I made them hotkeys exactly as in the original text. Anyway: you're right, it would be cleaner for users to use **e** & **y** for W**e**jście and W**y**jście. Fortunately these two letters are "free" so I can easily use them ☺. I'll do it in the future.

**Comment by remuxer32** [comment]
Done. See: 0d76035
