### ISSUE TITLE
Werid chars in start of srt merged files

### ISSUE THREAD

**Issue by latot** [mbunkus/mkvtoolnix#1615]
Hi all, well this bug consist in when we merge an srt file mkvmerge add this characters to the start of the file breaking the reproduction of the file:

Initial File:
```
1
00:01:05,703 --> 00:01:07,038
Hola. Me llamo Heather.
```

merged and extracted srt file:
```
ï»¿1
00:01:05,703 --> 00:01:07,038
Hola. Me llamo Heather.
```

i'm using Linux Gentoo 64 with mkvtoolnix 8.9.0

**Comment by mbunkus** [comment]
mkvextract writes a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) for UTF-8 during extraction. That's the intended behavior.

**Comment by latot** [comment]
okis thx the help :D
