### ISSUE TITLE
Issue with AAC 5.1 Audio

### ISSUE THREAD

**Issue by PresidioSF** [mbunkus/mkvtoolnix#1616]
mbunkus,

I have a problem with trying to play AAC 5.1 Audio on a number of older devices. The devices should downmix the AAC to 2.0 Stereo if they cannot handle 5.1, but they are failing to do this because of something (I can't fully determine what, possibly an incorrect filesize length?) in the AAC header.

After using MKVMerge I had hoped this would fix the MKV but still seems to be an issue.

When I strip the extraneous data from the AAC header (using a hex editor) and mux again using MKVMerge I am then able to play the file(s) using 2.0 Stereo yet still retain the 5.1 ability for devices that can handle it.

Is it possible that MKVMerge could handle the stripping/correcting without me having to do it manually?

I cannot determine exactly what part of the AAC header is the offender.

Maybe it is necessary to look more closely at what the differences are between the file that plays successfully and a file that is unsuccessful?

To help out, here are 2 samples for comparison:

**1. Not Working**
https://www.dropbox.com/s/4ad3mrnpk0vonho/Test-HB0.10.3_Normal_Profile_AAC_5.1.mkv

**2. Working** _(only after I remove extraneous bytes in header and then remux with MKV Merge and ticking Audio is SBR box)_
https://www.dropbox.com/s/xtro7eryx4z27yt/Test-HB0.10.3_Normal_Profile_AAC_5.1-Demuxed_AAC_Header_Data_Removed_Then_Remuxed.mkv

Note: If I skip the step of removing the extraneous bytes in the AAC header, remuxing with MKVMerge still produces an unplayable result. I must remove the offending header bytes to enable the file to be playable.

Any help is appreciated, wondering if you know what exactly could be causing it.

PS - I thought it may be something to do with zlib audio header compression, but checked that also and it does not seem to be.

**Comment by mbunkus** [comment]
I'm sorry, but I won't implement something like that. mkvmerge is not in the business of fixing/stripping/improving codec data. That's not its scope.

**Comment by PresidioSF** [comment]
Any idea of something that can handle this?

It is the AAC header that is obviously the problem.

**Comment by PresidioSF** [comment]
I don't think I explained this so well in my original comments...

I have noticed that what MKVExtract is doing _may_ actually be part of what I am trying to do.

I cannot yet get it working, but there is an option in MKVExtract to extract the raw track and when I mentioned above fixing/stripping codec data this is what I was myself doing (I was manually removing the header bytes to first make the AAC audio RAW before feeding it to MKVMerge).

I see there is some kind of option to make RAW in MKVExtract using the --raw switch, and I think the problem may be with the CodecPrivate field so I am reading that the --raw switch removes the CodecPrivate field.

So effectively (maybe) running MKVExtract to get the RAW audio and then remuxing with MKVMerge and the AAC is SBR switch is similar to what I am doing already.

So what I was asking above is/was effectively the ability for MKVMerge to process the audio track as RAW on its own before processing.

I hope this makes more sense?

**Comment by mbunkus** [comment]
It doesn't, not without really investigating such an issue including looking at sample files. And as I've already said I simply lack the time and the motivation to spend time on your particular issue with your particular player. I'm sorry.

**Comment by PresidioSF** [comment]
No investigation required. 

I have solved the problem already using 2 of your tools - MKVExtract, then MKVMerge.


However, right now, it must be performed in 2 steps.

1. This extracts the audio
CMD Line: **mkvextract tracks video.mkv 1:audio.aac**

2. New audio muxed with MKVMerge
**Use MKVMerge GUI and mux the new audio file audio.aac (extracted above) into the remux**
(there is a command line for this, but too long and irrelevant)


Is it possible to do this in one step, using only MKVMerge? 
For example, maybe using an option file or some kind of checkbox that parses the audio in the same manner that MKVExtract already does?

Is it possibe for MKVMerge to process the audio (AAC) in the same manner as MKVExtract already does?


Maybe I am just not yet using the full power of MKVMerge.

**Comment by mbunkus** [comment]
No.

AAC as stored in Matroska doesn't have headers. mkvextract adds ADTS headers during extraction so that other software can actually understand and read that AAC data. (This is the same with MP4, BTW).

mkvmerge in turn reads that AAC-with-ADTS-headers file, removes the ADTS headers and stores the headerless AAC data inside Matroska.

So the way to »do what those two programs do together« is to simply copy the AAC data as it is stored inside the source Matroska file over to the destination Matroska file. That's what mkvmerge is already doing, though.

Adding some kind of switch to make mkvmerge do what it is doing already doesn't make any sense.

So yes, investigation would very much be required in order to determine what exactly triggers your issue (or what makes it go away). And as I've said two times already I'm not going to spend any more time on this. I'll now ignore this issue.

**Comment by PresidioSF** [comment]
> "the way to »do what those two programs do together« is to simply copy the AAC data as it is stored inside the source Matroska file over to the destination Matroska file. That's what mkvmerge is already doing, though."

If this is the **expected** behavior - that in your determination, using MKVExtract+MKVMerge _or _using MKVMerge only >>should<< result in >>**exactly**<< **the same result **- then my only conclusion is that there must be a bug with MKVMerge (and also, MKVToolnix).



As explained already, **I have actually solved the issue but >>must<< use 2 steps** - by first using MKVExtract, then secondly using MKVMerge.

If you indicate the result should be >>exactly<< the same using >>only<< MKVMerge instead of using 2 steps, I can confirm that the result is >>not the same<<.


Using MKVMerge >>alone<< does not work, because - as you indicated already - all MKVMerge does is copy the AAC data as it is stored in the source directly to the destination.


However, by using MKVExtract **>>first<<** to extract the AAC, and **>>then<<** using MKVMerge to mux the new AAC, on close inspection with MKVInfo it can be seen that 2 fields have changed under Audio/AAC:

UID and
CodecPrivate


...and it is the change of the CodecPrivate field in particular that makes the MKVextract+MKVMerge output file work successfully (but the 'MKVMerge only' output file, does not).



I have tested this using versions 8.30, 8,50, 8.70 and the latest 8.9.0 and the result is the same **>>every<<** time for each version.
