### ISSUE TITLE
Request: automatically include font depends

### ISSUE THREAD

**Issue by latot** [mbunkus/mkvtoolnix#1617]
Hi all, i wanna request this feature, the idea is an option for detect font's depends and merge it automatically in the file. ¿what do you think?

**Comment by PresidioSF** [comment]
Do you mean hardcoding of subtitles?

**Comment by latot** [comment]
attach the files, like, i have an .ass and need the A font, so the option recognize it and when it merge the sub, attach the font to the mkv.

sorry ask this but what means hardcoding in this context?

**Comment by latot** [comment]
may be expand the concept to others depends...

**Comment by mbunkus** [comment]
Thanks for the suggestion. I won't implement such a feature, though, for multiple reasons. For one it's far from trivial to determine the font file path for any given font in a cross-platform way. Another point is that this seems to be a niche feature, especially as ASS files can already contain fonts, and mkvmerge supports keeping those fonts. I'm also pressed for time making such niche features a very low priority for me; hence my decision not to implement it.

I'm open to accepting patches that implement such a feature, but I won't do it myself; Sorry.
