### ISSUE TITLE
Bom ignored with sub-charset

### ISSUE THREAD

**Issue by phate89** [mbunkus/mkvtoolnix#1620]
Hi.. I have a script that mux some subtitle with my own video automatically in linux.
Since the subtitles are usually from windows I set --sub-charset as windows-1252 to every subtitle to mimic the windows behavior. 
But when I pass to this script a subtitle in utf-8 with bom (according to sublime text) I get wrong characters because mkvmerge do the conversion from windows-1252 to utf8.
According to the docs if the text file has a bom sub-charset should be ignored:
https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.text_files_and_charsets.byte_order_markers.
Of course this isn't a problem in windows because I don't have to enforce windows-1252 so it automatically use utf8 for that file with bom but it is in linux...

**Comment by mbunkus** [comment]
Thanks for posting it. The documentation states how mkvmerge should handle files with BOMs; if it doesn't then that's a bug. I'll investigate it.
