### ISSUE TITLE
Major Bugs/Regressions regarding HDR HEVC encoded videos, SEI/NAL units removed during muxing

### ISSUE THREAD

**Issue by J1Man** [mbunkus/mkvtoolnix#1621]
Dear Moritz,
 
I would like to report a bug regarding mkvtoolnix 8.9.0 that did not exist in the previous mkvtoolnix 8.4.0.  This bug is related to muxing High Dynamic Range (HDR) HEVC raw streams into mkv.
 
**Mkvtoolnix 8.9.0 removes all HEVC HDR related messages (color volume information, content light level info, some proprietary unregistered HDR related SEI messages specific to display vendor Samsung, etc.) from raw HDR HEVC files and mixes-up the HEVC HDR NAL units during muxing.**  I confirmed this bug by analyzing MKV files by using Intel Video Pro Analyzer that displays NAL units.
 
I am using Windows 7 Ultimate Edition 6bit and 64bit GUI and command line versions of Mkvtoolnix.  I also use MKVtoolnix via Staxrip encoding application.
 
**This bug only happens when muxing raw HDR HEVC streams into MKV.**  It does not happen when you are muxing from MP4 to MKV.  Since all encoding applications (such as Staxrip, Handbrake, etc.) send raw HEVC streams to mkvtoolnix, this bug is very serious.
 
I initially discovered this bug visually when I played re-encoded and remuxed HDR HEVC video files on my Samsung UHD TV (colors were very off) and confirmed it using Intel Video Pro Analyzer that can analyze HEVC video in MKV containers.  If you do not have these tools at your disposal, you can follow the step by step procedure that I outlined below.

In order to reproduce the bug, please download the HDR trailer of Life of Pi from the following link:
http://demo-uhd3d.com/files/uhd4k/Life_of_%20Pi_draft_Ultra-HD_HDR.mp4
 
Demux the raw hevc stream from this file using MP4box ver 0.6.1 rev18:
`mp4box -raw 1 -out "Life_of_ Pi_draft_Ultra-HD_HDR.hevc" "Life_of_ Pi_draft_Ultra-HD_HDR.mp4"`
 
The size of the raw hevc stream generated by MP4box will be 304,421,210 bytes.
On a separate note, TsMuxer v2.6.12 also produces a demuxed raw hevc file with identical 304,421,210 bytes size.
 
Now remux this raw hevc stream into mkv files using the GUIs of mkvtoolnix 8.9.0 and mkvtoolnix 8.4.0. Name the files:
`Life_of_ Pi_draft_Ultra-HD_HDR_MuxedBy_MKVtoolnixVer840.mkv`
`Life_of_ Pi_draft_Ultra-HD_HDR_MuxedBy_MKVtoolnixVer890.mkv`
 
Now demux the files, this time using mkvextract included in mkvtoolnix 8.9.0 and mkvtoolnix 8.4.0.
`mkvextract tracks "inputname.mkv" 0:"outputname.hevc"`
Name the files:
`Life_of_ Pi_draft_Ultra-HD_HDR_MuxedAndDemuxBy_MKVtoolnixVer840.hevc`
`Life_of_ Pi_draft_Ultra-HD_HDR_MuxedAndDemuxBy_MKVtoolnixVer890.hevc`
 
I wrote the sizes of the demuxed raw hevc files below
 
`Life_of_ Pi_draft_Ultra-HD_HDR_MuxedAndDemuxBy_MKVtoolnixVer840.hevc`  is  304,419,613 bytes
`Life_of_ Pi_draft_Ultra-HD_HDR_MuxedAndDemuxBy_MKVtoolnixVer890.hevc`  is  304,386,090 bytes
 
In order to confirm MKVtoolnix bug, you can do one of the following:
 
- You can open the output mkv produced by MKVToolnix 8.9.0 in Intel Video Pro Analyzer and see that NAL units are mixed up and color volume information is gone. This is how I discovered and confirmed the bug.
 - You can use mkvextract to extract the hevc stream from the output mkv produced by MKVToolnix 8.9.0 and compare it to the original raw hevc file extracted by MP4box and see that its size is not the same.  The missing size is due to the missing HDR SEI messages and NAL units (which are very small, just a couple of kilobytes, but carry a lot of color information).
 
**There is one more thing that I want to bring to your attention.  The size of the raw hevc file demuxed by Mkvtoolnix 8.4.0 is also smaller than the raw hevc generated by MP4box.**  I couldn't figure out what's missing in the output of Mkvtoolnix 8.4.0 but there might be a bug in there as well and some SEI/NAL information might be thrown away by MKVtoolnix 8.4.0 during the muxing process as well.
 
Please let me know what you think.
 
Best Regards

**Comment by mbunkus** [comment]
Thanks for posting it here, too.

**Comment by mbunkus** [comment]
I've debugged the issue and know why it happens and which commit caused this (8a1e641762241fb7047af1abb2384612c22fbbd9). I've also implemented a fix and a proper solution for what 8a1e641762241fb7047af1abb2384612c22fbbd9 was attempting to do in the first place.

However, I'm not entirely confident in it yet. I'd appreciate it if you could give it a try. New pre-builds are available that include the fix (build numbers [01148 32bit](https://mkvtoolnix.download/windows/pre/32bit/), [01149 64bit](https://mkvtoolnix.download/windows/pre/64bit/)).

**Comment by J1Man** [comment]
Thanks for fixing this bug quickly.  I did several tests and confirmed that the bug is fixed.

I did the following to test the 64bit pre-build 01149:
1) I visually tested the MKV files that were muxed from raw High Dynamic Range HEVC streams on my UHD TV.  Colors were accurate.
2) I used open source HEVC analysis tool HEVCESBrowser to confirm that number of NAL units in the input stream is the same as the number of NAL units in the muxed&demuxed output stream generated by MKVtoolnix.

Please note that there are a lot of SEI message types defined in HEVC specs.  Unfortunately I don't have test cases that cover all SEI message types.  But all the ones that I could test were accurately muxed & demuxed by MKVtoolnix.

On a separate note, open source HEVC analysis tool HEVCESBrowser (https://github.com/virinext/hevcesbrowser) got updated yesterday with full support for HDR HEVC streams.  It is now a very strong competitor to Intel Video Pro Analyzer.  You can use this free tool to debug HEVC related issues that you might face in the future.  You can also request new features (on Github/Issues page of this tool) to get more features that might help you to debug HEVC related issues.

Please let me know if you have any other questions.  Thanks again for fixing this serious bug very quickly.

**Comment by mbunkus** [comment]
Thanks for testing, and especially for pointing out HEVCESBrowser. I wasn't aware of that tool, and it sounds hella useful.

mkvmerge now keeps all SEI NALUs again, no matter their type. I'll push the commits in a minute, and you can read more about what was changed in the commit message that'll be linked to this issue.
