### ISSUE TITLE
Teletext to subtitle convertion fails for AVC video

### ISSUE THREAD

**Issue by kefiros** [mbunkus/mkvtoolnix#1623]
In AVC video. MKVToolnix converts the teletext to subtitiles but, as confirmed with Subtitle Edit, nearly all texts are of 0.04 sec duration. So the subtitle just momentarily flashes/blinks on the screen.

Video
Format                                   : MPEG-TS
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format version                           : Version 2
Format profile                           : High@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Text
ID                                       : 579 (0x243)-801
Menu ID                                  : 1106 (0x452)
Format                                   : Teletext Subtitle
Language                                 : English

![capture](https://cloud.githubusercontent.com/assets/7994428/13729129/a70341a2-e97d-11e5-80d4-38d53aa8a7f1.PNG)
[Gravity (2013)_avc sample.zip](https://github.com/mbunkus/mkvtoolnix/files/171026/Gravity.2013._avc.sample.zip)

Texletex->Subtitle conversion works fine with Mpeg2 streams that I record from TV.

**Comment by mbunkus** [comment]
Thanks for the report and the sample file, but I will actually need a sample file before it's muxed into a Matroska file if you want me to investigate this problem. You can upload one to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by kefiros** [comment]
Hi, thanks for picking it up so quickly, I have have uploaded a small sample from the same TV channel, (i.e. with the same stream characteristics) to your ftp. The name is 
Australias Got Talent - Encore_20160314_12581500.ts
Thanks

**Comment by mbunkus** [comment]
Thanks for the sample. I can reproduce the issue here and will look into it.

**Comment by kefiros** [comment]
Much appreciated.

**Comment by mbunkus** [comment]
I've implemented a fix that works well with the file you've provided. I've also created debug builds for you to test: [build 01153 (32bit)](https://mkvtoolnix.download/windows/debug/32bit/), [build 01152 (64bit)](https://mkvtoolnix.download/windows/debug/64bit/).

If these builds don't work well for you then I'll need some more sample files for which they fail to produce an adequate result. I'd also like some feedback if they do work. Thanks.

**Comment by kefiros** [comment]
I have tested using build 01152 (64bit) provided, It works on the short segment I uploaded before (Australias Got Talent - Encore_20160314_12581500.ts)
But it fails on a longer (2h) recording. I am uploading it now.

**Comment by mbunkus** [comment]
Thanks. I don't necessarily need the whole file. If the issue is already showing up at the start then a partial upload would suffice.

**Comment by kefiros** [comment]
Here is the file https://drive.google.com/file/d/0B17p_qRmkrL6N2p1bXV1LVNKbkE/view?usp=sharing

**Comment by mbunkus** [comment]
Thanks, I'll look into it.

**Comment by mbunkus** [comment]
[Pre-builds 1158 and 1159](https://mkvtoolnix.download/windows/pre/) contain a proper fix.
