### ISSUE TITLE
Window too big, can't downsize

### ISSUE THREAD

**Issue by KAMiKAZOW** [mbunkus/mkvtoolnix#1625]
The GUI window does not fit on a 720p screen.

**Comment by mbunkus** [comment]
Sorry, but I only support a height of 800 pixels and higher. You can play around with the various layout-related settings in the preferences if you want. The most promising is lowering the font size and moving the tab widget headers to the left or to the right. Additionally you can disable that the output file name is always shown on the bottom (it will be shown on the »output« tab instead).

With those settings and a 8pt font size I've just gotten the GUI down to a height of 666 pixels.

![screenshot_20160317_091420](https://cloud.githubusercontent.com/assets/414282/13840130/b2be93a2-ec20-11e5-9ee4-c489e05cc0cb.png)
