### ISSUE TITLE
System icons not used

### ISSUE THREAD

**Issue by KAMiKAZOW** [mbunkus/mkvtoolnix#1626]
The icons appear to be hardcoded instead of using the system icons.
If mkvtoolnix-gui used the DE's icons, the look and feel would improve.

**Comment by mbunkus** [comment]
I've chosen the icons based on their actual content, not based on their file name (and therefore their semantics). If I made them match a user-chosen theme then that would most likely be confusing as other themes often have vastly different presentation of the same semantic topic. I also chose Oxygen on purpose – I actually want my application to look like this. It is a cross-platform, cross-desktop environment application.

Those are two reasons why I won't change this.
