### ISSUE TITLE
Split mode: before chapters - splitting time issue

### ISSUE THREAD

**Issue by ARKaMAN** [mbunkus/mkvtoolnix#1628]
I have a MKV that has chapters built in. I want to split it into separate files.  When I set it up to split before chapters it sometimes does not split in the right spot.  It sometimes splits 10 - 15 seconds later.  When I open the split files I can see where it was supposed to split by the chapter that is still in the file. Any ideas? Thanks!

MKVToolNix GUI v8.9.0 x64

**Comment by bastik-tor** [comment]
I think [this wiki entry](https://github.com/mbunkus/mkvtoolnix/wiki/Splitting-imprecise) explains it.

It has to do with where key-frames are located and that MKVToolNix does not contain video decoder and encoder.

Though it still might be a bug, since the option is called ```before chapters```, so mkvmerge might have to use the last keyframe before the chapter.

**Comment by mbunkus** [comment]
@bastik-tor is right; mkvmerge can only split on key frames, and in chapter mode it uses the chapter's timestamp as the reference point. The first key frame at or after the chapter's start timestamp will be the first frame in the new file.

I've thought long and hard about trying to use a key frame located _before_ the chapter start point, but that's a thing a program will never be able to get 100% right. Chapters often occur on scene changes, and it's not unlikely to have several key frames in close proximity. The question would be how to deal with situations in which there's a key frame 500ms before the chapter and one 200ms after the chapter. Which one to take? Either can look pretty bad to a user, and a program cannot make a proper decision.

I've therefore decided long ago not to implement some kind of smart detection. Instead mkvmerge will always work the same way (using the first key frame at or after the chapter's start timestamp). This makes it much easier for the user to reason about what is happening.

I'm closing this issue again as I'm almost certain that your chapter start timestamps simply don't align well with key frame distribution. You can check the former with MKVToolNix GUI's chapter editor and the latter with mkvinfo's GUI.

**Comment by mbunkus** [comment]
If you have some proof that mkvmerge is not actually doing what I've described above then please post it here and I'll re-open the issue.
