### ISSUE TITLE
MKV Extract Broken v9 & 9.0.1

### ISSUE THREAD

**Issue by WidowCranky** [mbunkus/mkvtoolnix#1640]
Versions 9.0.0 and 9.0.1 seem to have broken MKV Extract. Some sort of conflict with mkvinfo.exe.
MKVInfo is fine if it's opened independently and a file is dragged into it but, when a file is dragged into MKV Extract, it says "Executing mkvinfo..." at the bottom of the window but then hangs.
Re-installation of v8.9.0 fixes the issue.

EDIT: X64 version.

**Comment by bongiovi** [comment]
Same here.

**Comment by mbunkus** [comment]
See #1636.
