### ISSUE TITLE
Chinese subtitles not working

### ISSUE THREAD

**Issue by jhuang11** [mbunkus/mkvtoolnix#1641]
So for the mkvmerge program I merged a video with a chinese subtitle but when I turned on the chinese subtitle, I get something like this:
![image](https://cloud.githubusercontent.com/assets/18150689/14120491/0a813938-f5c1-11e5-8c87-409c316c1941.png)
It seems like the program doesn't read the chinese srt file correctly even though if I were to play the unmerged file separately say on PowerDVD and add the subtitle separately without merging it works normally. 
I want this to work so I can play the video on my blu-ray player via external hard drive with subtitles. 
Thanks!

**Comment by mbunkus** [comment]
Please read and follow [this FAQ entry](/mbunkus/mkvtoolnix/wiki/Characters-(e.g.-Umlauts)-aren't-shown-correctly).
