### ISSUE TITLE
Bug or feature - or only my problem ...

### ISSUE THREAD

**Issue by ahab666** [mbunkus/mkvtoolnix#1644]
well, sorry to bother you but with the 9.0 and the 9.01 versions i have the following issue:

every time i start mkv toolnix i am getting the standard presets - so if i need to do serevral jobs i have to set them properly again ... can you give me a hint where theese settings are stored (file or registry) so i might investigat security and program execute settings on my x64 win 10 ...

cheers - ahab

**Comment by mbunkus** [comment]
[This FAQ entry](/mbunkus/mkvtoolnix/wiki/Location-of-settings-and-the-job-queue) lists in detail where the settings are stored for the installed and the portable versions.

**Comment by ahab666** [comment]
hello,

deleting the old ini file was of no use ... i opened it and it had the
version number 0.8.9 in it.
unínstalling and reinstalling versiob 0.8.9. did the trick - now my
preferences are stored again ....

what do you recommend when updating - uninstall -> new install or just
install over the previouzs version

cheers - alex   (geht auch in deutsch)



2016-04-01 12:56 GMT+02:00 Moritz Bunkus <notifications@github.com>:

**Comment by mbunkus** [comment]
Uninstalling means that your stored settings are removed as well. So usually just installing a new version without uninstalling the older one is the right thing to do.

**Comment by ahab666** [comment]
danke - werde es versuchen ... falls der fehler (???) weiterhin besteht
melde ich mich wieder ...

nfg alex


2016-04-02 13:33 GMT+02:00 Moritz Bunkus <notifications@github.com>:
