### ISSUE TITLE
Problem of v.9.0.0 with MKVExtractGUI2 v.2.2.2.9

### ISSUE THREAD

**Issue by Ebleep** [mbunkus/mkvtoolnix#1645]
Installing the 9.0.0 and 9.0.1 versions blocks the operation of "MKVExtractGUI2 v.2.2.2.9"... loading the file crashes reading file "mkvinfo".
I solved by replacing the "mkvinfo" files after installation with the installation of the previous version (mkvtoolnix-64bit-8.9.0-setup).
Do you plan to solve it by the next versions?
Thank you.
Regards, Paolo.

- Original message in Italian. -
Installando le versioni 9.0.0 e 9.0.1 blocca il funzionamento di "MKVExtractGUI2 v.2.2.2.9"... caricando il file si blocca nella lettura del file "mkvinfo".
Ho risolto sostituendo il file "mkvinfo" dopo l'installazione con quello dell'installazione della versione precedente (mkvtoolnix-64bit-8.9.0-setup).
Pensate di risolverlo dalle prossime versioni?
Vi ringrazio.
Saluti, Paolo.

**Comment by mbunkus** [comment]
See #1636.
