### ISSUE TITLE
Colon use in output file field

### ISSUE THREAD

**Issue by omgdyl** [mbunkus/mkvtoolnix#1647]
Not a bug per say, but It'd be nice if mkvtoolnix would automatically remove any colons(:)  in the output name. I will usually manually delete or substitute with a hyphen but when I forget, it completely crashes mkvtoolnix.

Actually, if at all possible it may be good to just disallow any reserved characters in windows that are not allowed in a file name:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following reserved characters:

"<" (less than)
">" (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
"*" (asterisk)

**Comment by mbunkus** [comment]
Thanks for the report. I'll implement something like that. Note that I cannot remove/disallow forward and backward slashes as the output file name contains a complete path and file name and I couldn't distinguish between wanted slashes as directory separators and unwanted ones as part of the file name. The file name is simply the part after the last forward or backward slash.

**Comment by omgdyl** [comment]
Sure that makes perfect sense. The colon has mostly been the only issue for me but I figure if you're going to remove that may as well remove some of the other special characters from being allowed in that field as well.

Thanks for getting back so quick. Great app and appreciate you putting the time in to maintain and improve.

Cheers,

**Comment by mbunkus** [comment]
New [pre-builds](https://mkvtoolnix.download/windows/pre/) including the functionality are available. Build numbers 01195 and higher include it.
