### ISSUE TITLE
S_DVBSUB support

### ISSUE THREAD

**Issue by muzena** [mbunkus/mkvtoolnix#1648]
I try to extract subtitle from video file Last_Patrol.mkv from linux terminal and I get this error:

mkvextract tracks Last_Patrol.mkv --output-charset CP1250 2:Last_Patrol.sup
Error: Extraction of track ID 2 with the CodecID 'S_DVBSUB' is not supported.

Can you add support for extracting S_DVBSUB subtitles?

**Comment by mbunkus** [comment]
I'm sorry, but no. S_DVBSUB is not one of the [official Matroska Codec IDs](https://www.matroska.org/technical/specs/codecid/index.html). It was invented by an unknown person who never got in contact with the Matroska team about it. I also know nothing about its storage format, nor about how such an external format `.sup` looks like. I have no intention of investing time on this.

**Comment by muzena** [comment]
This is video record made with Tvheadend: https://github.com/tvheadend/tvheadend.
This command I found googling, on that way I extracted S_HDMV_PGS subtitle type.

**Comment by hurda** [comment]
> It was invented by an unknown person who never got in contact with the Matroska team about it. 

What about https://lists.matroska.org/pipermail/matroska-devel/2011-February/003946.html ?

>I also know nothing about its storage format, nor about how such an external format .sup looks like.

If I'm reading the [tvheadend-code](https://github.com/tvheadend/tvheadend/blob/42c9423d8aaf6834ea122c57039d39286eecaae8/src/parsers/parsers.c#L1691) (being called in line 210) correctly, it's parsing the stream of the image-pased DVB-subtitles, and muxes them into mkv. AFAIK that subtitle format is very similar to BluRay-subs.

TV-stations using that kind of subtitles are ARD and ZDF, alongside Teletext-subtitles.
I have sample-TS-recordings not made by tvheadend, if that would help.

**Comment by mbunkus** [comment]
I'm aware of that discussion. It petered out without ending in any kind of formal definition/specification. No one else cared to take up the work.

Sorry, my stance remains as-is. I won't spend time on this. I've got enough to do already.
