### ISSUE TITLE
Starting merge or adding to queue creates blank tab called <no output file>

### ISSUE THREAD

**Issue by hmgnsd** [mbunkus/mkvtoolnix#1650]
Starting merge or adding to queue creates blank tab called "no output file", say if I dragged 10 files in to merge in sequence, every time I add a file to the queue the actual merge tab closes but leaves a "no output file" tab in its place, 10 times over. See attached screenshot of one such tab.
![mkvtoonnix no output file](https://cloud.githubusercontent.com/assets/18248954/14234153/cd75a7a6-f9d3-11e5-8b5c-5ed3eb103ab3.jpg)

**Comment by mbunkus** [comment]
Open the preferences, go to the "merge" section and change the setting "clearing settings automatically" to something else. You like have it set to "remove input files".

**Comment by hmgnsd** [comment]
Ah, I had it set to 'create new settings'. Changing it to 'no' doesn't create a "no output file' tab as you say. Is there a setting that will close the input tab after I add that merge job to the queue?

Thanks for the response ;)

**Comment by mbunkus** [comment]
No, there isn't. But that shouldn't worry you overly much. As long as you don't change the settings after having started muxing (or after adding them to the queue) the GUI won't ask whether you want to save changes. What I'm trying to say is: just ignore the tab. Press Ctrl+W for closing it afterwards, of just hit Ctrl+N for a new tab, or just close the application – the GUI shouldn't hassle you and ask for confirmation.
