### ISSUE TITLE
Discard (# of) errors when mkvtoolnix gui is closed

### ISSUE THREAD

**Issue by EvanVanVan** [mbunkus/mkvtoolnix#1655]
If I'm muxing a file and errors occur, I never remember to right-click and acknowledge them.  When I open the program a few days later and start muxing a file, I notice the error counter and am momentarily confused about whether or not an error occured with my current file.

Could you reset the errors/counter when the program closes, so that it always starts at 0 when it's reopened?

Thanks

**Comment by mbunkus** [comment]
Thank you for the suggestion. I'll think about it.

**Comment by remuxer32** [comment]
@EvanVanVan 

>Could you reset the errors/counter when the program closes, so that it always starts at 0 when it's reopened?

Well, this feature actually exists ☺. See, please: https://s15.postimg.org/lo2hu2q3f/Resetting+errors+&+warnings.png

I think you can close the issue now :)

**Comment by mbunkus** [comment]
Meh, you're right, of course. Seems the GUI's customizability has grown to the point where even I don't remember all of the options I've implemented :)

**Comment by mbunkus** [comment]
And thanks for pointing it out, @remuxer32.

**Comment by EvanVanVan** [comment]
Whoops, thank you!

**Comment by remuxer32** [comment]
>And thanks for pointing it out, @remuxer32.

You're welcome :)

@EvanVanVan 

>Whoops, thank you!

You're welcome, and remember: always read the preferences dialog very carefully :)
