### ISSUE TITLE
mkvmerge hangs muxing certain AVIs

### ISSUE THREAD

**Issue by jeabon** [mbunkus/mkvtoolnix#1657]
Hello

I'm using mkvmerge to convert avi files to mkv files. The video is H264 and audio is PCM. With some files mkvmerge is frozen before the end of the convertion without error. I can repoduce the issue with mkvtoolnix_gui.
If I select H264 track and PCM Track, I have the same issue.
If I select H264 track only the convertion works fine.
I will put 2 avi files underPCM issue folder on your FTP sites in order to reproduce the issue.

OS: Windows 7 x64
MKV toolnix release: 9.0.1
Thanks for for help.

regards

Jean-Luc Bonnet

**Comment by mbunkus** [comment]
Thanks for the report & the test files. I can reproduce it and will look into it.

**Comment by mbunkus** [comment]
I'm currently compiling new [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/). It'll take about 10 minutes until they'll be uploaded. Build numbers 01186 and higher will contain the fix.

**Comment by jeabon** [comment]
Hi Moritz,

                Thanks for your quick fix.  It works fine now.

Regards

Jean-Luc Bonnet

De : Moritz Bunkus [mailto:notifications@github.com]
Envoyé : 13avr.16 19:41
À : mbunkus/mkvtoolnix
Cc : Jean-Luc Bonnet
Objet : [EXTERNAL] Re: [mbunkus/mkvtoolnix] mkvmerge hangs muxing certain AVIs (#1657)


I'm currently compiling new pre-builds for Windows<https://urldefense.proofpoint.com/v2/url?u=https-3A__mkvtoolnix.download_windows_pre_&d=CwMCaQ&c=0hKVUfnuoBozYN8UvxPA-w&r=3XFFEif9Py38PEs0FFH8jAYw83O__O1W1utDvwu8QzA&m=lXviaDJR_o6qSMoJyNLwG_xDOC3SKxttr9Cn7RieZec&s=iutcXtVcqyPcqgH16Et0w9UbRtZHeEYjv2xME_CXAW8&e=>. It'll take about 10 minutes until they'll be uploaded. Build numbers 01186 and higher will contain the fix.
