### ISSUE TITLE
Problem with default duration during muxing of VOB-files

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1658]
Hello,

today I noticed a weird issue during remuxing of a DVD. I uploaded one of the VOB's (the last and smallest) to your ftp-server as fps.vob. It's an NTSC DVD with progressive content; every second of video has 12 frames of length 50ms and 12 frames of length 33.3666 ms (the length corresponding to 29.97fps). Mediainfo also tells me that it has in reality a framerate of 23.976 and 2:3 pulldown as scan order so I presume it is one of the DVDs in which the DVD player (or maybe the TV, but we needn't care about this) has to do the interlacing during playback and that the longer 50ms frames are designated to be used as source for three fields whereas the shorter frames are only used for two fields.
Somehow mkvmerge thinks that this is a interlaced DVD with a frame rate of 29.97 and therefore uses a default duration corresponding to 59.94 fields per second. This results in zero simple blocks being used for the video stream. This behaviour seems to be a result of the fix to [https://github.com/mbunkus/mkvtoolnix/issues/479](bug 479). Mkvmerge 3.2 uses a default duration of 33366666ns (29.97fps) in this case whereas 3.3 uses half that value.
Simply remuxing the mkv-file a second time (with version 9.0.1) doesn't fix this: Mkvmerge simply keeps the default duration. But I found a hack: Given that the default duration is actually not used I can simply change it in the header without messing with the timestamps. Remuxing it with mkvmerge now results in a file with simple blocks and a smaller filesize; using 50ms as default duration even results in a slightly smaller file so there seem to be more 50ms frames. 
This leads me to the following conclusions:
1. Please fix the detection of progressive/interlaced material.
2. Given that the detection will probably never be 100% accurate and that even 33366666ns led to a slightly larger file than necessary I propose a new feature: Letting the user determine the default duration without overwriting the timecodes (so that the default duration only determines which frames are simple blocks and which are block groups). Maybe it is even possible to give the user feedback after muxing if a different default duration would have resulted in a smaller file (or maybe you can add something to mkvinfo to do that.). This would be advantageous for a lot more files than those coming from DVDs.
Last but not least let me thank you for all the hard work that you have (and probably will) put into MkvToolNix, Moritz.

Greetings
Andi

PS: The file created by mkvmerge 3.2 is even smaller than the one created by 9.0.1 (330.430.047 B (3.2) vs 330.497.913 B (9.0.1) for the file with default duration 50ms). It seems that the fact that 9.0.1 writes many more clusters is responsible for this. Is there a way to make 9.0.1 write as few clusters as 3.2? (I know that this might adversely affects seeking, but the file created by 3.2 can nevertheless easily be seeked.)

**Comment by mbunkus** [comment]
Thanks for the good bug report. However, I've long ago decided not to spend significant time on the MPEG-1/2 code anymore. That code wasn't written by me in the first place and numerous earlier attempts at fixing several things have resulted in huge investments of time for little gain. I'm therefore not investigating or fixing this. Sorry.

**Comment by mkver** [comment]
Thanks for the quick reply, even if it wasn't the reply I was hoping for. But can you at least let the user choose the default duration? That's definitely not MPEG-1/2 code and will benefit more files with variable frame rates. I am not an expert on your code, but this shouldn't be that difficult, or? Currently you read the default duration of the input streams (if they are mkv-streams) and if you change this, mkvmerge would simply use whatever the user supplied.

**Comment by mbunkus** [comment]
I won't implement such an option either. Sorry. As you know there is already an option `--default-duration` which serves a very distinct purpose. Adding another option that only modifies the header element without affecting the timestamps would be highly confusing to users. When should they use which option? What are the consequences? Such an option would only be applicable in niche cases, and for those niche cases only a small minority of users like yourself would actually care. It's simply not worth the effort. It's not just the implementation, it's also the documentation and all the time I'll have to spend on explaining things to users afterwards.
