### ISSUE TITLE
MkvToolnix GUI forgets the file title when remuxing

### ISSUE THREAD

**Issue by r0lZ** [mbunkus/mkvtoolnix#1659]
When a MKV file is created with a specific file title, and then remuxed with mkvtoolnixgui, the original file title is not shown in the Merge -> Output -> File Title field, and if you don't type it again, it is not present in the remuxed MKV.  (The old MkvMerge GUI did not have that problem.)

Not a big bug, but an annoyance anyway.

**Comment by mbunkus** [comment]
Thanks for the report. I'll look into it.

**Comment by mbunkus** [comment]
I cannot reproduce this behavior. Note that populating the title field with the data from the source file is optional. Please check your preferences: "MKVToolNix GUI" → "Preferences" → "Merge" → "Default values" → "Automatically set the file title from source files". Is that option enabled or disabled for you?

**Comment by r0lZ** [comment]
Oops, you're right.  I haven't noticed the preference.  It was disabled here.  Problem solved.

However, I wonder if that option is really enabled by default.  I don't remember having turned it off, and anyway, I have not modified much the options.  IMO, the file title should be kept by default.  But even if it's not the case, it's not a bug.  Sorry.

(Sorry also for replying so late.  I have had some problems with my email provider.)

**Comment by mbunkus** [comment]
It is the default. You can (and I just did) verify this by installing the portable version into a fresh directory, starting the GUI from there and looking at the preferences.
