### ISSUE TITLE
merge: splitting broken if first split point before first block in track

### ISSUE THREAD

**Issue by r0lZ** [mbunkus/mkvtoolnix#1660]
When muxing a file with the option to split the video after specific time codes, several files are created.  So far so good.
Then, a new project is created, with the first file as the basis, and the other files are then added with the option "Append to an existing input file".  The GUI accepts them normally.
But when the final MKV file is created (with "Start muxing"), a very small file is created with the first part and a portion of the second file (but not the beginning!) and the following error message is displayed:

kax_file_c::read_next_level1_element(): an exception occurred (message: end of file error / Unknown error; type: N3mtx5mm_io13end_of_file_xE). This usually indicates a damaged file structure. The file will not be processed further.

As far as I know, that issue is recent, and previous versions worked well.

**Comment by r0lZ** [comment]
Maybe the cause of the bug is the particular structure of the file.  An audio track begins only after 26 seconds, and was muxed in the original file with a delay of 25942 ms.  The first timecode for the split operation is 00:00:24.  Therefore, the part 1 of the split MKV does not contain the audio track at all.  Could it be the reason?  If yes, is it possible to issue a better error message?

**Comment by mbunkus** [comment]
Thanks for the report & the additional analysis. That'll definitely be helpful in tracking it down. I'll look into it.

**Comment by mbunkus** [comment]
I'm sorry, but I cannot reproduce this behavior, even with your additional information. If you want me to look into it further I'll need access to the file you're trying to split. Please upload it to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by r0lZ** [comment]
Well, it's embarrassing.  I can't reproduce it any more.  I've kept the original MKV file, but when I cut it to create a sample small enough to be uploaded, there is no problem.  I've tried to reproduce again the problem with the original file, and now it works as expected.

I suppose you can close this bug.  I'll reopen it if I encounter it again.

**Comment by mbunkus** [comment]
Alright. Don't worry, happens to me, too, when I report bugs in other people's software :)
