### ISSUE TITLE
Movie UHD (3840 x 2160) finish in 42%

### ISSUE THREAD

**Issue by jovanyatondo** [mbunkus/mkvtoolnix#1663]
I have a some movies in UHD (3840 x 2160) in MKV format, and I needed add or remove some track of audio but only work until 42%, I do it this same operation with movies in 720p or 1080p without problems, I hope you can help me. Thanks for the answer. 
Sincerely Jovany Atondo

**Comment by mbunkus** [comment]
Sounds like your source file is damaged at that point. If you want me to take a look at it then please upload the source file to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by mbunkus** [comment]
I'm closing this issue due to lack of feedback.
