### ISSUE TITLE
MKVToolNix GUI v9.0.1 Problem

### ISSUE THREAD

**Issue by gonwk** [mbunkus/mkvtoolnix#1665]
Hi,
I combine an MP4 with SRT the outcome MKV file is fine and works using VLC.
But when I play it on my stand-alone TV Media Player (Netgear EVA9100), I have 2 problems ...
1) if I Fast Forward or Rewind it, it plays again, but No Audio, so I have to Stop it and Re-start the file again.
2) Once in a while the file can NOT be Fast Forward at the highest speed only 1X.
Thanks!:)

**Comment by mbunkus** [comment]
In general this is a shortcoming in your player. See [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/Improving-playback-compatibility-with-players) for ways to tune mkvmerge's output to your player's idiosyncrasies.
