### ISSUE TITLE
GUI: treeview in header editor isn't defaulting to its full size at first use

### ISSUE THREAD

**Issue by hurda** [mbunkus/mkvtoolnix#1667]
With a fresh install of mkvtoolnix, the treeview in the GUI's Header Editor isn't set to its full size, but to it's smallest possible size.

![header_editor_tree-width](https://cloud.githubusercontent.com/assets/3539609/14739593/d6f8d73a-0888-11e6-95e6-e9a103acacb7.png)

**Comment by mbunkus** [comment]
Know issue that won't be fixed due to technical reasons. I'm sorry.

Note that the tree remembers its size over restarts. So you only have to enlarge it once.
