### ISSUE TITLE
Suggestion: Use invisible flag to improve cutting

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1669]
Hello,

in your wiki page about [splitting](https://github.com/mbunkus/mkvtoolnix/wiki/Splitting-imprecise) you write cutting at arbitrary positions is impossible without reencode of a small part. And up until today I concurred with you. But then I read the matroska specifications and both the [block structure](https://www.matroska.org/technical/specs/index.html#block_structure) and the [simple block](https://www.matroska.org/technical/specs/index.html#simpleblock_structure) structure have an invisible flag that tells the decoder to decode a frame but not to display it. This could be used to implement precise splitting/cutting. It would have the drawback that some portions of video would exist in both files so that the file size is slightly larger, but it would be perfect if you do not intend to store both files (I'm thinking about cutting commercials (which is where I'd love to apply it)). It also has the advantage that the actual cutting still takes place right before an IDR frame, given that you already [indicated](https://github.com/mbunkus/mkvtoolnix/issues/1088) that you do not intend to enable splitting anywhere but IDR frames. The main hurdle I see is that right know mkvmerge only processes the input files once whereas in the case you implemented this feature a part will be processed twice. Would this imply a lot of work?
I of course do not propose to remove the splitting feature as it is know, but rather to add a new way for those who want to use it. Given that I have never ever knowingly seen a mkv file with invisible flag (pun not intended) I assume that a lot of decoders will have problems so that a lot of users would be upset if mkvtoolnix' default way of splitting/cutting were changed. (By the way the introduction of header removal compression despite widespread lack of compability signals that you are ready to enter unchartered territorities that maybe are unsupported by a lot of players. Just as with header removel compression, this is another feature which is in the specifications for a long time (it's in the [oldest specifications I could find](https://www.matroska.org/node/1/revisions/1/view) without being used.)
Thanks in advance.

Andi

PS: [This wiki page](https://github.com/mbunkus/mkvtoolnix/wiki/Characters-%28e.g.-Umlauts%29-aren't-shown-correctly) is outdated: "If you want to give this feature a try then download one of my new [pre-builds](https://mkvtoolnix.download/windows/pre/). Pre-build numbers 961 and higher contain said feature as will releases 8.5.0 and later." The link does not lead to any pre-build at all and the reference to pre-builds is outdated anyway.

**Comment by mbunkus** [comment]
The idea is interesting, but I won't implement it. Sorry.

Header removal compression _had_ been used for quite a long time. But as there have always been hardware devices which didn't implement it I decided not to use it by default anymore. This is unlike the invisible flag which has never been used by any software.

Thanks for the hint about the wiki page; I'll fix it.
