### ISSUE TITLE
No video (black screen) when playing output file

### ISSUE THREAD

**Issue by caffeinedreamer** [mbunkus/mkvtoolnix#1670]
Hi. I've been using this tool to cut and add audio tracks to some of my video files. Occasionally, the output file is of the size I'd expect (100-300MB smaller if extracting an audio track), but the video track doesn't show at all. The file will play with audio and subtitles working; just not the video track itself. Am I missing a setting or something like that?

**Comment by mbunkus** [comment]
Have you tried other players (VLC, MPC-HC)? Have you made sure with mkvinfo that there is a video track and that there are video frames present in the file?

**Comment by mbunkus** [comment]
I'm closing this issue due to lack of feedback.
