### ISSUE TITLE
Windows command line is not accepting -r

### ISSUE THREAD

**Issue by DJDoena** [mbunkus/mkvtoolnix#1674]
I tried -r before and after the mkv file, I tried--redirect-output before and after the mkv file

It always opens the GUI instead

When I try to use the option file it never finds the mkv file because it removes all the backslashes. If I double them in the options file it still opens the GUI.

**Comment by mbunkus** [comment]
Are you talking about mkvinfo? If so you'll have to add `--no-gui` in order not to start the GUI.

**Comment by DJDoena** [comment]
Thanks. That did the trick. 
This parameter is not mentioned here:
https://mkvtoolnix.download/doc/mkvinfo.html
There it sounds more like you actively have to enable the GUI

**Comment by mbunkus** [comment]
The option `--no-gui` and the change to start the GUI by default is a recent change in v9.0.0. Thanks for pointing out that I've forgotten to add it to the documentation. I'll fix that.
