### ISSUE TITLE
MkvInfo: Feature Request: Output as XML?

### ISSUE THREAD

**Issue by DJDoena** [mbunkus/mkvtoolnix#1676]
The text output is OK for what I'm intending (i.e. I will find the line I'm looking for)

But: Would it be possible to export the mkvinfo info to an XML file as well?

**Comment by mbunkus** [comment]
No, I won't add XML output (or any other kind of structured output) to mkvinfo.

You should take a look at mkvmerge's JSON identification mode and see if the property you're looking for is already output by mkvmerge: `mkvmerge --identification-format json --identify yourfile.mkv` or short `mkvmerge -J yourfile.mkv`
