### ISSUE TITLE
.SRT files return error

### ISSUE THREAD

**Issue by psychonaut25** [mbunkus/mkvtoolnix#1677]
In previous versions I would often mux mp4 files together with .srt subtitle files.  After updating to 9.1.0 "Little Earthquakes", upon clicking & dragging the .srt file from Windows Explorer I get the following error message:
"The file was not recognized as a supported format (exit code: 0)."

I'm on Windows 7 Professional x64

**Comment by mbunkus** [comment]
An SRT file is a plain text file that can be opened with any capable text editor (don't use Windows' Notepad). It consists of groups of at least four lines each:

1. the line with the running number,
2. the line with the start and end timecode,
3. one or more lines of text and
4. one blank line as a separator.

Here's an example of how a valid file could look:

    1
    00:00:04,700 --> 00:00:06,736
    where are you going so early?

    2
    00:00:06,900 --> 00:00:09,494
    Don't record any more messages
    on my alarm clock.

Your file probably violates one of those rules mentioned above at the start. Open it in a text editor and take a look; you can likely figure out what's wrong pretty quickly.

If you can't then sed me the file to moritz@bunkus.org and I'll take a look.

**Comment by psychonaut25** [comment]
I don't know why I didn't think of this, haha.  Opened it in Notepad++ and found a completely empty file, devoid of any text.  This issue is now closed.  Thanks Moritz

**Comment by mbunkus** [comment]
You're welcome :)
