### ISSUE TITLE
mkvifno-gui overrides xdg-open somehow

### ISSUE THREAD

**Issue by cryptofuture** [mbunkus/mkvtoolnix#1678]
`xdg-mime  query default video/x-matroska`
smplayer.desktop
`xdg-mime  query default video/x-matroska`
smplayer.desktop
xdg-mime shows same values before and after mkvtoolnix install. But xdg-open runs videos in mkvinfo-gui instead smplayer after mkvtoolnix install. (videos opened in file manager respects mime settings). 
Same thing happens both with last package from default package and with last package from mkvtoolnix.download repository. After removing mkvtoolnix-gui package xdg-open works as intended.
Could be something with alternatives mechanism? Any ideas?

**Comment by mbunkus** [comment]
All my packages do is install [these](https://github.com/mbunkus/mkvtoolnix/blob/master/share/desktop/mkvtoolnix-gui.desktop) [two](https://github.com/mbunkus/mkvtoolnix/blob/master/share/desktop/mkvinfo.desktop) pretty standard desktop files. It doesn't run any postinstall script or does anything else to mess with your settings.

Why `xdg-open` starts a different program than what `xdg-mime` says I really cannot say, and I cannot help you with this problem. You should ask the developers of the `xdg-*` tools.

**Comment by cryptofuture** [comment]
Well, I was able to fix this problem. After understanding how xdg-open really works.

xdg-open just decides what wm/de tool to run. In my case that was gvfs-open (fixed after installing gvfs-bin package). I had gnome-open installed already (it runs mimes correctly). But xdg-open selects gvfs-open in my case, but since gvfs-bin package was not installed it fallbacks to itself (xdg-open) and xdg-open itself likes use global mime setting generated from /usr/share/applications, mime settings from this two desktop files, in my case. Hope it will help somebody in future.
