### ISSUE TITLE
GUI enhancement: Show filename in title column and taskbar for mkvinfo

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1679]
Hello,

I often find myself in the position of running multiple instances if mkvinfo GUI (the Windows version; I don't know much about the versions for other OS) and all just appear as "mkvinfo" in the taskbar. Could this please be replaced with the filename of the file just opened by this instance of mkvinfo (or by "filename - mkvinfo"; "mkvinfo - filename" is not good because with multiple running programmes, only the first part is shown in the taskbar)?
Thanks in advance.

Andi

**Comment by mbunkus** [comment]
Sounds useful.
