### ISSUE TITLE
Audio Bit Depth is not preserved when merging a DTS-HD stream

### ISSUE THREAD

**Issue by Thrahin** [mbunkus/mkvtoolnix#1680]
Hello,

I have encountered an issue where after merging a source with DTS-HD audio track, it loses the "Audio Bit Depth" property. The property was properly set before the merge (in this case it had a value of 24). The output file had the copied audio track without this property, causing other applications (like foobar2000) to fall back to treating the file as a 16-bit source. If I added the value manually in the header editor, it started to be recognized properly.
The first time I have used this functionality and encountered this issue was in MKVToolNix GUI v8.6.1, but this bug is still present in current v9.1.0 (I'm using the software on Windows if it may have any impact).

Thank you for creation and continued development of this useful piece of software.

**Comment by mbunkus** [comment]
mkvmerge simply doesn't set the bit depth for AC-3 tracks as that property is simply not required at the container level for decoding. I'll think about adding it.

**Comment by kashmirix** [comment]
@mbunkus: OP asked about DTS?

**Comment by mbunkus** [comment]
Oops, right. However, what I said applies to DTS as well, not just AC-3.
