### ISSUE TITLE
Dolby Digital + (E-AC3) not recognized

### ISSUE THREAD

**Issue by Wario77** [mbunkus/mkvtoolnix#1684]
Hello,
new french TNT HD audio not recognized by any version of MKVToolnix but there are in MediaInfo
![mediainfo](https://cloud.githubusercontent.com/assets/19212533/15054240/a4d43302-1306-11e6-9f7d-c8b153978a1c.jpg)
![mkvtoolnix](https://cloud.githubusercontent.com/assets/19212533/15054239/a4d34d20-1306-11e6-8c7d-02d831a58f8d.jpg)
Thanks in advance for your response

**Comment by mbunkus** [comment]
I will need sample files in order to do anything about this. Please upload some somewhere, e.g. to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by Wario77** [comment]
Hi Moritz,
done by FTP
File: Issue 1684 - test.mpg

Will it be ok for linux version too ?
I'm using it in a script for MythTV Server...

Thanks for the good job, Marc

**Comment by mbunkus** [comment]
That file should do fine, thanks. I'll look into it.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) are up. Build numbers 01211 and higher contain the fix.

**Comment by Wario77** [comment]
Hi Moritz
Great job !

It workd perfectly on all my mpg files...

Thanks a lot !

**Comment by basicmaster** [comment]
The mentioned stream_type `0x87`is not unknown: It is indeed the official type used for E-AC-3 in ATSC (see ATSC A/52, annex G, clause 3.1) - though TNT is broadcasted in DVB (BTW it is very annoying that ATSC and DVB use different ways of signalling (E-)AC-3 streams).
So I'm also wondering where the `0x84` used for E-AC-3 in the code comes from...

**Comment by mbunkus** [comment]
It comes from "Blu-ray Disc Read-Only Format Part 3: Audio Visual Basic Specifications" table 5-16 in section 5.4.4.3.2 "StreamCodingInfo – Semantics".
