### ISSUE TITLE
mkvmerge not merging

### ISSUE THREAD

**Issue by BigEBankston** [mbunkus/mkvtoolnix#1687]
When I try to merge some mkvs that have the same parameters (1280x720, H264, AAC) it makes an error and says "The track number 1 from the file 'C:/test/File1.mp4' cannot be appended to the track number 1 from the file 'C:/test/File2.mkv' the tracks parameters do not match."

**Comment by mbunkus** [comment]
Yep. Such files cannot be appended without re-encoding the parts so that their parameters match as Matroska doesn't support changing parameters (e.g. changing resolution or changing number of audio channels) in the same track. There's nothing to be done about it from mkvmerge's side.

**Comment by BigEBankston** [comment]
I don't understand? Both of the files are encoded using the same settings yet it still comes up with that error.

'C:/test/File1.mkv': Using the demultiplexer for the format 'Matroska'.
'C:/test/File2.mkv': Using the demultiplexer for the format 'Matroska'.
'C:/test/File1.mkv' track 0: Using the output module for the format 'AVC/h.264'.
'C:/test/File1.mkv' track 1: Using the output module for the format 'AAC'.
'C:/test/File2.mkv' track 0: Using the output module for the format 'AVC/h.264'.
'C:/test/File2.mkv' track 1: Using the output module for the format 'AAC'.

**Comment by BigEBankston** [comment]
The only thing different is that they have different subs hardcoded to them. They are the same resolution

**Comment by BigEBankston** [comment]
Or do I have to reconvert them to mp4s everytime I should append?

**Comment by mbunkus** [comment]
The track parameters that are checked aren't just the codec; they're also the pixel resolution, the sampling frequency, the number of channels and for AAC the profile.

If you have different subtitle types then try leaving them out.

**Comment by BigEBankston** [comment]
Ah thank you for the help, still very new to this so I didn't know about that.

**Comment by BigEBankston** [comment]
Alright so I reencoded the videos with the right sampling frequency, although this comes up in the warnings when I try to append them "The codec's private data does not match (lengths: 41 and 43)" What does this mean and how would I fix it? Also no idea how to check the number of channels, each video has 1 video and 1 audio channel if that is what it means? No idea how to the profile for AAC.

**Comment by BigEBankston** [comment]
I appreciate your help

**Comment by BigEBankston** [comment]
I used ffmpeg to edit the sample freq if that matters

**Comment by mbunkus** [comment]
I don't recode video myself; I cannot really help you with it. Sorry.

**Comment by BigEBankston** [comment]
Alright well thanks for the help anyway.

**Comment by mkver** [comment]
Two points from me:
1. According to the description you gave, the problem is with track 1, i.e. the audio streams. So you shouldn't need to reencode the video.
2. You can use e.g. mediainfo (already included into MPC-HC if you use it: Open the properties windows for the file you are playing and switch to the mediainfo tab) to get some information about your audio stream to see what's wrong. If you already used ffmpeg, you can also use ffprobe.

**Comment by BigEBankston** [comment]
Alright so I checked the mediainfo of the output video, a video I appended in it but didnt change freq of, a video I appended in it and changed freq of and a video of before I changed the freg to append: http://pastebin.com/hWsimVfA

No idea what to look for there, the one thing I see is that teh codec id is A_AAC for the output video and 40 for the videos before I appended them

I don't understand why the audio would make this corruption though: http://puu.sh/oIrCz/aa690b2e62.jpg

**Comment by mkver** [comment]
You're infos are confusing me. The "output file" is 53mn 8s long; yet all the three other files combined are way shorter than this. I don't know if your audioreprocessing includes stretching the file (by an enormous factor, way higher than PAL speedup (or it's inverse)), but I know one thing: This is a bug database for MkvToolNix, not a support forum for MkvToolNix and not a forum for general audio/video questions. In other words, you should look elsewhere for help.
Oh, audio errors usually don't cause video corruption.
