### ISSUE TITLE
gmtime_r and asctime_r defined by mingw

### ISSUE THREAD

**Issue by abakum** [mbunkus/mkvtoolnix#1688]
In:

    MINGW32_NT-6.1 x 2.5.0(0.297/5/3) 2016-04-12 13:21 i686 Msys

Error:

    $ ./drake
             CXX src/info/mkvinfo.cpp
    src/info/mkvinfo.cpp: In function 'tm* gmtime_r(const time_t*, tm*)':
    src/info/mkvinfo.cpp:386:1: error: redefinition of 'tm* gmtime_r(const time_t*, tm*)'
     gmtime_r(const time_t *timep,
     ^
    compilation terminated due to -Wfatal-errors.

Fixed:

    382:#if defined(COMP_MSC) //|| defined(COMP_MINGW) gmtime_r and asctime_r defined by mingw

**Comment by mbunkus** [comment]
I'm sorry, but I don't support compilation on msys directly, only cross-compilation from Linux with a mingw cross compiler (e.g. the [MXE project](http://mxe.cc/)). This means that I won't spend time on this myself. However, I'd happily apply patches if you can come up with some.

**Comment by mbunkus** [comment]
Oh, and what you've written as a "fix" isn't a fix as it breaks compilation with aforementioned mingw cross compiler.

**Comment by abakum** [comment]
fix only for msys2 :)

**Comment by abakum** [comment]
May be for Linux computer with a mingw cross compiler define COMP_MXE, but for windows computer with mingw use COMP_MINGW

**Comment by mbunkus** [comment]
Like I said, I won't spend the time to get this working. I'd still welcome patches that are tested on both MSYS and on Linux with mingw-cross.

**Comment by abakum** [comment]
I did it! It works on windows through MSYS2 (shareable) and on linux through MXE(static).
[MSYS2.zip](https://github.com/mbunkus/mkvtoolnix/files/258924/MSYS2.zip)

**Comment by abakum** [comment]
Fixed:
#if defined(MINGW32_SUPPORTS_MT_EH) && (defined(COMP_MSC) || defined(COMP_MINGW))

**Comment by abakum** [comment]
For MXE
[setup_cross_compilation_env.sh.zip](https://github.com/mbunkus/mkvtoolnix/files/259072/setup_cross_compilation_env.sh.zip)

**Comment by abakum** [comment]
Patch for MXE
[setup_cross_compilation_env.sh.zip](https://github.com/mbunkus/mkvtoolnix/files/259082/setup_cross_compilation_env.sh.zip)

**Comment by abakum** [comment]
Patch for MXE
[setup_cross_compilation_env.sh.zip](https://github.com/mbunkus/mkvtoolnix/files/259141/setup_cross_compilation_env.sh.zip)

**Comment by abakum** [comment]
Patch for README.Windows.md

[README.Windows.md.zip](https://github.com/mbunkus/mkvtoolnix/files/259208/README.Windows.md.zip)

**Comment by mbunkus** [comment]
Thanks for the additional work. After thinking about those `#ifdefs` some more I've decided to throw out the entire section and to use Boost's Date/Time library that I'm using in other parts of MKVToolNix anyway. I'll push the corresponding change in a moment which should close this issue as fixed again. Please give that fix a try.

I've also applied the changes to `setup_cross_compilation_env.sh`; thanks for that.

I haven't applied the changes to the `README.Windows.md` file yet as I'm still unsure whether or not I want such information there. Even stating that a method isn't supported may not be enough for me as I dislike providing information that I don't verify to be correct (and which will therefore grow stale over time). Maybe I'll put it up in a wiki article, maybe I'll include it, maybe neither. I'll have to think about it some more.

**Comment by abakum** [comment]
Thanks. It worked.

**Comment by mbunkus** [comment]
Thanks for the confirmation.
