### ISSUE TITLE
MKVExtract gets stuck

### ISSUE THREAD

**Issue by psychonaut25** [mbunkus/mkvtoolnix#1691]
Trying to open .mkv files in MKVExtract via right clicking them in Win Explorer and using the context menu to go to "open with" does not seem to work anymore.  In addition, if I start MKVExtract from the Start Menu and open the MKV file I want, it gets stuck on "Executing mkvinfo" and just stays that way indefinitely.

Windows 7 Pro x64 here, using MKVExtract 2.2.2.9 "Resurrection"
Any suggestions?

**Comment by mbunkus** [comment]
I'm pretty sure you mean MKVExtractGUI2 which is not one of my programs. See #1636.
