### ISSUE TITLE
"Enable all" and "Disable all" options under the right click menu for attachments.

### ISSUE THREAD

**Issue by this-username-is-already-taken** [mbunkus/mkvtoolnix#1698]
"Enable all" and "Disable all" options under the right click menu for attachments.
The old GUI had dedicated buttons for that sort of thing. The new GUI requires multiple menu opening and clicking, first to select all attachments, then to enable or disable them. "Enable all" and "Disable all" options under the right click menu would save a little time and a few mouse clicks.

Thanks.

**Comment by mbunkus** [comment]
Like I said on Doom9 I won't implement this as I consider it duplication of functionality for the sake of saving two mouse clicks tops.

**Comment by mbunkus** [comment]
As said in the discussion on Doom9: I misunderstood the original intent. Splitting "select all" into "enable all" and "disable all" doesn't lose existing functionality, it is useful to the user and easy to implement. Therefore I will do so.
