### ISSUE TITLE
Deleting the language property from a stream sets it to its default.

### ISSUE THREAD

**Issue by occivink** [mbunkus/mkvtoolnix#1699]
Hi,

I'm editing an mkv like so:
`mkvpropedit --edit track:v1 --delete language video.mkv`
but instead of removing the language property (which is not mandatory) from the stream, it sets it to the default 'eng'.

Using the latest 9.1.0 version.

**Comment by mbunkus** [comment]
That's not a bug, it's the intended behavior. If an element is not present in a Matroska file then that element's default value must be used. The default value for the track language is "eng".

Matroska doesn't support something like" the language is not set". You can use "und" ("undefined") if the language isn't known or "zxx" ("no linguistic content") where appropriate.

**Comment by occivink** [comment]
Ah I see. I was assuming that the property could be unset because I had some files for which ffmpeg was not reporting any stream language, but now I see that it's what happens when the property is set to 'und'.

Thanks you very much.

**Comment by mbunkus** [comment]
You’re welcome.
