### ISSUE TITLE
Test 'ParseDurationNumberWithUnitSecondUnitsFloats' fails on certain 32bit architectures

### ISSUE THREAD

**Issue by drstacey** [mbunkus/mkvtoolnix#1705]
For Cygwin 32-bit, the latter three tests in 'ParseDurationNumberWithUnitSecondUnitsFloats' fail. These tests rely on the accuracy of double precision arithmetic, which cannot be guaranteed, especially on 32-bit platforms.

One solution is to increase the accuracy of the function being tested. In parse_duration_number_with_unit(), change the declaration of 'd_value' to a 'long double'. (src/common/strings/parsing.cpp line 228) as in this patch [9.2.0-floating_point_parsing.patch.txt](https://github.com/mbunkus/mkvtoolnix/files/288020/9.2.0-floating_point_parsing.patch.txt). This works for Cygwin 32-bit. However, since there is no guarantee that 'long double' is any more accurate than 'double', you may prefer to alter the tests to allow some tolerance in the values returned.

**Comment by mbunkus** [comment]
Thanks for the report. I don't support compilation/testing on Cygwin, therefore I won't spend time on this myself. Using `long double` isn't acceptable to me as using that led to problems on other platforms in the past, platforms which I cannot easily test on as I don't have access to them.

I'd be grateful it you could come up with another way to fix this.

**Comment by drstacey** [comment]
I quite understand about you having to support a variety of platforms. It's probably better to adjust the test to accept a range of values, rather than test for absolute equality. See https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#floating-point-comparison

This patch [9.2.0-floating_point_test.patch.txt](https://github.com/mbunkus/mkvtoolnix/files/293764/9.2.0-floating_point_test.patch.txt) changes the test to use `EXPECT_NEAR` which allows a small tolerance on the values returned. Is this better?

**Comment by rathann** [comment]
This is reproducible on Fedora 23+ when building for i686, i.e. under `mock -r fedora-rawhide-i386`:
```
[ RUN      ] StringsParsing.ParseDurationNumberWithUnitSecondUnitsFloats
tests/unit/common/strings_parsing.cpp:32: Failure
Value of: value
  Actual: 12345677
Expected: 12345678ll
Which is: 12345678
tests/unit/common/strings_parsing.cpp:35: Failure
Value of: value
  Actual: 12345677999
Expected: 12345678000ll
Which is: 12345678000
tests/unit/common/strings_parsing.cpp:38: Failure
Value of: value
  Actual: 12345677999999
Expected: 12345678000000ll
Which is: 12345678000000
```

**Comment by rathann** [comment]
FYI, this seems to be limited to 32bit x86, because a build on ARMv7 (32bit, HFP) has just completed successfully and the tests passed. It may be worth updating the title to reflect the fact that this is not limited to Cygwin.

**Comment by mbunkus** [comment]
Thanks for the confirmation, @rathann. I do have Fedora 32bit installations around (and I highly suspect others like Debian and Ubuntu are affected as well) and will look into it.
