### ISSUE TITLE
Wrong cursor position after pasting quoted text into 'Output file' field in Windows version

### ISSUE THREAD

**Issue by OlegPliss** [mbunkus/mkvtoolnix#1709]
Enter some text (i.e. a file path) into Output file field. Copy some text enclosed in double quotes into clipboard. Paste it into that field in any but the last position. The cursor should be set right after the pasted text but moves one character further to the right.

**Comment by mbunkus** [comment]
Thanks for the report.

**Comment by mbunkus** [comment]
After looking at the code and thinking about the amount of time I'd have to spend to fix this properly I've decided not to do so; the investment is not worth it to me. I'm sorry.
