### ISSUE TITLE
mkvmerge breaks non-ascii subtitle when LANG=C

### ISSUE THREAD

**Issue by facundobatista** [mbunkus/mkvtoolnix#1710]
Hello!

First of all, thanks for mkvtoolnix and mkvmerge, they are GREAT tools!!

I found a bug when merging a movie and a subtitle together. The subtitle has non "7 bit ascii" characters (it's in Spanish), and it's already encoded in UTF-8.

The LANG in my environment is "es_AR.UTF-8". I'm using mkvmerge v8.8.0 64bit.

If I just run ```mkvmerge -o out.mkv input.mkv input.srt```, then I see the movie with the subtitles OK.

But if I run ```LANG=C mkvmerge -o out.mkv input.mkv input.srt```, then I see the movie with the subtitles broken (the non-ascii chars are missing).

NOTE: I'm using mplayer to watch the movie, with the ```utf8=yes``` config.

Any doubt or question, just let me know, happy to help you debugging.

Thanks!

**Comment by mbunkus** [comment]
This is not a bug. If a text subtitle file starts with a byte order mark then mkvmerge will use its information for the encoding. If it doesn't it uses the system's locale setting. If you signal `C` as the locale then you're also signalling ASCII as the character set (that's what `C` implies about the encoding).

You can ovveride that with the `--sub-charset` option, of course.

**Comment by facundobatista** [comment]
Awesome, thanks!
