### ISSUE TITLE
Suggestion: Remove FLAC-padding and seektable

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1712]
Hello,

currently mkvmerge writes the complete FLAC-header into the corresponding codec private field (i.e. it literally does what is written on [matroska.org](https://matroska.org/technical/specs/codecid/index.html)). But upon inspecting the behaviour of the [FLAC reference encoder](https://xiph.org/flac/download.html) I came to the conclusion that one should not do so: Aforementioned encoder (and probably most of the flac-files in circulation emanate from this encoder (directly or by relying on it as backend)) writes an index named [seektable](https://xiph.org/flac/format.html#metadata_block_seektable) into the header and a [padding block](https://xiph.org/flac/format.html#metadata_block_padding) (so that one can add new metadata later without a need to completely rewrite the file). The seektable is as unnecessary in matroska (with its own index/cues) as are the Access Unit Delimiters in H264 (in matroska); and the padding field in matroska, too: Someone who wants to add new metadata should do so before muxing to matroska. Anyone remuxing to matroska is willing to completely rewrite the file anyway.
The size of the padding field changes from file to file; it's size apparently increases with the length of the file although I don't know the exact relationship. But one file (converted from a movie TrueHD-soundtrack) contained 65536 padding bytes and a seektable with length 12258. In this case the codec private field had a length of 77932 B. In a normal flac-file emanating from one track of an audio CD the padding field usually occupies 8192 B.
If you want to check this, you might consider the metaflag-tool from the FLAC-authors themselves.

Grüße
Andi

**Comment by mbunkus** [comment]
Thanks for the suggestion. I'm not a big fan of altering an existing storage format, but I don't think there are a lot of tools actually handling FLAC in Matroska. mkvextract is likely the only one for extraction, and players should not have a problem with the seek table missing. I may look into it.

**Comment by mbunkus** [comment]
I've decided against implementing this. I simply don't want to spend time on FLAC. Its design is very hostile against embedding it in other containers, its libraries are very hard to integrate and use in programs that don't want to/cannot hand control over reading files over to libFLAC and mkvmerge already has enough problems with FLAC (e.g. appending/splitting is completely broken and won't be fixed either).

**Comment by bumblebritches57** [comment]
@mkver A recently found a file with over 130,000 padding bytes while writing ModernFLAC (for a standard song, to boot)

I completely agree that padding should be stripped.

**Comment by mbunkus** [comment]
Patches are welcome, I just won't spend time on FLAC myself.
