### ISSUE TITLE
Forward/rewind impossible on MKV and mkvmerge 5.8 doesnt fix

### ISSUE THREAD

**Issue by buchodeq** [mbunkus/mkvtoolnix#1713]
I have created a mkv file (video h264, ac3 audio and sub) with mkvmerge 8.3, my player Sony bdps480 plays well the file but cannot forward or rewind inside the video, now I've just tried to remake the file with mkvmerge 5.8 but the player doesn't open it, it appears as a black screen with no sounds. Is there a solution?

**Comment by mbunkus** [comment]
Try again with the latest release, v9.2.0. Also try files created by 9.2.0 with a proper software player (VLC, MPC-HC). You should also look into [this wiki article](https://github.com/mbunkus/mkvtoolnix/wiki/Improving-playback-compatibility-with-players).

**Comment by mkver** [comment]
Should this doesn't work either, you can try e.g. [mkclean](https://www.matroska.org/downloads/mkclean.html). Or you can try to mux with only one or two of the three streams and see which files work and which don't. Or you can give us the detailled output of mkvinfo for these files.

**Comment by mbunkus** [comment]
I'm going to close this issue as hardware-specific problems can usually solved by the options mentioned on the wiki page, and if they can't then it's usually not mkvmerge's fault but bad/incomplete Matroska implementations in the hardware devices.
