### ISSUE TITLE
Track Info for EIA-608 (Closed Captions)

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#1717]
Hello, is it possible to add the appropriate track information for closed captions (EIA-608) embedded in a mpeg2 stream?  Specifically, is there a way to **manually** add closed captioning information to the mkv container either with mkvmerge during muxing or afterward with mkvpropedit?

Currently, the closed captioning (CC) data seemingly disappears, since it gets masked-out after muxing to mkv, even though the CC data still exists -- since it's still embedded inside the mpeg2 stream.  For example, I wish to add the information for the CC track (displayed below by mediainfo under the 'Text' heading) as "Track ID 3" to the original mkv, or, if necessary, when remuxed to a new mkv.  Is this possible?  If so, how?  Thank you for your help.

`$ mkvmerge -i mpeg2_movie.mkv`
>File 'mpeg2_movie.mkv': container: Matroska
Track ID 0: video (MPEG-1/2)
Track ID 1: audio (AC-3/E-AC-3)
Track ID 2: audio (AC-3/E-AC-3)
Chapters: 33 entries

`$ mkvextract tracks mpeg2_movie.mkv 0:raw.m2k`
`$ mkvmerge -i raw.m2k`
>File 'raw.m2k': container: MPEG video elementary stream
Track ID 0: video (MPEG-1/2)

`$ mediainfo raw.m2k`
>General
Complete name                            : raw.m2k
Format                                   : MPEG Video
Format version                           : Version 2
File size                                : 3.16 GiB
Overall bit rate mode                    : Variable

>Video
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Bit rate mode                            : Variable
Maximum bit rate                         : 9 800 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 (24000/1001) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Scan order                               : 2:3 Pulldown
Compression mode                         : Lossy
Time code of first frame                 : 00:59:58;00

>Text
ID                                       : CC3
Format                                   : EIA-608
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)

P.S. - I know I can extract the CC track to SRT using ffmpeg and remux with the SRT, but the CC data will **still** be embedded in the mpeg2 stream and should be represented as a selectable subtitle track in the resulting mkv -- after all, it still exists.

`$ ffmpeg -f lavfi -i "movie=mpeg2_movie.mkv[out0+subcc]" -map s mpeg2_movie.cc`
`$ awk 'BEGIN {RS=ORS=""; FS=OFS="\n"}{print $1,$2,$3; for (i=4;i<=NF;i++) printf " %s", $i; print "\n\n"}' mpeg2_movie.cc |sed 's/^M//g' > mpeg2_movie.srt`
`$ head mpeg2_movie.srt `
>1
00:00:17,551 --> 00:00:18,641
(THUNDER RUMBLING)

>2
00:00:42,709 --> 00:00:45,709
(RAIN PATTERING MUSICALLY)

>3
00:00:53,220 --> 00:00:55,220

**Comment by mbunkus** [comment]
mkvmerge doesn't support closed-captioning information (neither does Matroska in general if certain pieces of information must be stored at the container level), and I have no plans to work on that. Sorry.

**Comment by optimiz** [comment]
Thanks for the quick response.  That's unfortunate.  I had hoped closed captions were merely missing from the [technical specs for subtitles at Matroska.org](https://matroska.org/technical/specs/subtitles/index.html) -- or, still "_under construction_," like the USF specs.  Oh well, conversion to SRT it'll have to be.
