### ISSUE TITLE
Split by Timecodes Not Accurate

### ISSUE THREAD

**Issue by seanfrisbey** [mbunkus/mkvtoolnix#1718]
I don't know how to get a log, so please let me know if one exists so I can show you what might be happening.  I've got files that are approximately 22 minutes long.  I am trying to split after timecode 00:11:09 (I've tried this with all of them), and it keeps splitting it at 00:11:12.  A certain range of entered values keeps splitting at THAT timestamp, and certain ranges of other values seem to split at another timestamp.

**Comment by mbunkus** [comment]
mkvmerge can only split on key frames. This is intentional and not a bug. See [its documentation about splitting](https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.description.split).

**Comment by seanfrisbey** [comment]
Ahh, I see.  Does this mean that I have to transcode the video and include more keyframes?  If I'm going that far, I should just transcode the durations that I need, haha.

**Comment by seanfrisbey** [comment]
Also, is there a forum to discuss this instead of submitting it as a bug?  Thanks!

**Comment by mbunkus** [comment]
If you have to split at a non-key frame position the re-encoding is the way to go. Depending on the codecs and container formats involved there are tools out there that can re-encode only the frames up to the next key frame, but I have no experience with such programs either.

There are many very knowledgeable people on the [Doom9 forum](forum.doom9.org/showthread.php?t=155732) where you can ask such questions.

**Comment by seanfrisbey** [comment]
Thanks a bunch for the help AND the swift responses!  Regardless of the limitations of the codecs (out of your hands), this utility has been a Godsend.  Thank you so much!
