### ISSUE TITLE
Update Wavpack

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1720]
Hello,

currently mkvmerge does not support Wavpack version 4.16. But according to the [file format specification](http://www.wavpack.com/file_format.txt) the currently valid versions are 4.02-4.16. I tracked the error down. It is [in this if-clause](https://github.com/mbunkus/mkvtoolnix/blob/06725a38daad6bcec2dbf331ef115409947fe67d/src/common/wavpack.cpp#L85). Instead of `sp[4] <= 0xf` one needs `sp[4] <= 0x10`. In order to be sure not to break something I also looked at the [source code](http://www.wavpack.com/sources.zip) of the Wavpack programs on which the wavpack implementation in MkvToolNix is based. The relevant file is open_utils.c. They added a few more checks in order to eliminate false positives; mkvmerge should probably add them, too:

    if (*sp++ == 'w' && *sp == 'v' && *++sp == 'p' && *++sp == 'k' &&
            !(*++sp & 1) && sp [2] < 16 && !sp [3] && (sp [2] || sp [1] || *sp >= 24) && sp [5] == 4 &&
            sp [4] >= (MIN_STREAM_VERS & 0xff) && sp [4] <= (MAX_STREAM_VERS & 0xff) && 
            sp [18] < 3 && !sp [19]) {
                memcpy (wphdr, buffer, sizeof (*wphdr));
                WavpackLittleEndianToNative (wphdr, WavpackHeaderFormat);
                return bytes_skipped;
            }
Given that the header has a length of 32 B, the length of the packet-8 field needs to bigger than 24, hence `sp [2] || sp [1] || *sp >= 24`. The restrictions on `sp[18]` and `sp[19]` emanate from the restriction of one block to 131072=2^17 samples.
I have only checked the code on which the `read_next_header` is based.
A sample file may be found [in Wavpack's collection of test files](http://www.rarewares.org/wavpack/test_suite.zip). It's `false_stereo.wv`.
This collection contains another file that doesn't work: `win_executable.wv`. It's possible to create wavpack files which contain a wavpack decoder: Upon renaming the file to *.exe the file becomes a Windows 32 executable that decodes the music in the file to *.wav. This file is currently not recognized. Probably the [initial probe](https://github.com/mbunkus/mkvtoolnix/blob/65e4d9c0820bf3cabba8152e8ea2a97c129b943d/src/merge/reader_detection_and_creation.cpp#L185) fails (in the first case, it fails [at a later stage](https://github.com/mbunkus/mkvtoolnix/blob/65e4d9c0820bf3cabba8152e8ea2a97c129b943d/src/merge/reader_detection_and_creation.cpp#L387)). In order to detect files like these you probably need to increase the size of the part of the file to be probed. This is of course only important if you want to support these files. If you want, you have to decide if you want to keep the decoder or just the audio (I prefer the latter: Both VLC and MPC-HC can't handle these files so there will probably be issues if they are put into matroska.).
By the way, the [comment](https://github.com/mbunkus/mkvtoolnix/blob/06725a38daad6bcec2dbf331ef115409947fe67d/src/common/wavpack.h#L30) in this line is outdated: As already mentioned, 0x402 to 0x410 are currently valid for decode. The same applies to [the wavpack specification on matroska.org](https://matroska.org/technical/specs/codecid/wavpack.html).

Grüße
Andi

PS: This is the first time that I ever directly came in touch with C/C++. I decided to investigate this issue myself because the code has been written by Steve Lhomme so that you are probably not familiar with it. For this I read various tutorials on the net, but this doesn't make me a real programmer. So have mercy with me if I did something wrong above.

**Comment by mbunkus** [comment]
Thanks for another comprehensive report. I'll look into it.

**Comment by mkver** [comment]
Thanks for the update. Do you stop checking the minor version in order to future-proof mkvmerge (i.e. so that you won't have to update it again when 4.17 comes out)? That's understandable, but is it really safe (and useful) to omit the check whether the version is at least 4.02? (Honestly, I have never seen a file with a version <4.02.)
PS: As already mentioned, the [wavpack specification on maroska.org](https://matroska.org/technical/specs/codecid/wavpack.html) also includes a statement "0x403 for now". Can you update this, too?

**Comment by mbunkus** [comment]
For most formats I do much less rigorous checks for validity. There's really no big need to check the minor version field as, from the container's perspective, there's no difference between the various formats in WavPack4. The versions solely differ in the content of the packets, not the packet structure, and unlike decoders containers only care about the structure.

I'll update the web site in a minute.
