### ISSUE TITLE
Incorrect video lenght

### ISSUE THREAD

**Issue by MagicGreenDragon** [mbunkus/mkvtoolnix#1721]
Hi!
I found a bug in mkvmerge (version 9.2.0).

My OS: Windows 7 Professional x64

I see that, when I merge an ASS and an FLV files, the resulting MKV file has a video track that is longer than the source track into FLV file.
FLV length = 23:40
MKV length = 24:00

If I create the MKV file with only the FLV file, the final length is correct, but with the ASS file, it is wrong.

Why it happens?

Thanks in advance.

**Comment by mbunkus** [comment]
This is not a bug. The length of a Matroska is the difference between the highest timestamp+duration and the lowest timestamp of all blocks in the file. This includes subtitle blocks.
