### ISSUE TITLE
Problem with subtitles

### ISSUE THREAD

**Issue by frojasg1** [mbunkus/mkvtoolnix#1722]
When adding two subtitle tracks, the first one is always selected and cannot be deactivated.
It neither lets change to the second language subtitle track

**Comment by mbunkus** [comment]
> the first one is always selected and cannot be deactivated

I'm not entirely sure but I think you're referring to your player always playing the first one? That's likely due to the player's interpretation of the "default track" flag. See [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/Default-and-forced-flags-and-default-yes-no-in-the-GUI) about that flag and what it means. The handling of this flag is not a bug in mkvmerge.

> It neither lets change to the second language subtitle track

Which "it" are you referring here?

**Comment by frojasg1** [comment]
Hello Moritz,

 

                You are right.

                The movie was created ok with all tracks of subtitles.

 

                By mistake I did not switch the correct option on the Blue-Ray player.

 

                Today I have tested it on media player classic, and the tracks of subtitles were well created and could be selected without any problem.

                After that, I have returned to my Blue-Ray player and I have found the correct option to switch the subtitles.

 

                Thank you very much for your fast answer.

 

                I think you are doing a great job with mkvtoolnix. It is amazing :)

                Thank you very much and good luck !!

 

kind regards,

Fran.

 

De: Moritz Bunkus [mailto:notifications@github.com] 
Enviado el: lunes, 13 de junio de 2016 22:37
Para: mbunkus/mkvtoolnix <mkvtoolnix@noreply.github.com>
CC: frojasg1 <frojasg1@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [mbunkus/mkvtoolnix] Problem with subtitles (#1722)

 

the first one is always selected and cannot be deactivated

I'm not entirely sure but I think you're referring to your player always playing the first one? That's likely due to the player's interpretation of the "default track" flag. See this FAQ entry <https://github.com/mbunkus/mkvtoolnix/wiki/Default-and-forced-flags-and-default-yes-no-in-the-GUI>  about that flag and what it means. The handling of this flag is not a bug in mkvmerge.

It neither lets change to the second language subtitle track

Which "it" are you referring here?

**Comment by mbunkus** [comment]
Thanks for the confirmation & for your praise :) I'll close the report.
