### ISSUE TITLE
Import chapter names : feature request 

### ISSUE THREAD

**Issue by Kid-C** [mbunkus/mkvtoolnix#1723]
New feature request

The new MKVToolnix gui allows chapters to be created when appending files (e.g., mkvs, wavs). 

A useful feature in that same respect would be to allow the importing of chapter names from a very simple plain text file. In this regard, only one chapter name entry would be allowed on each line. Blank lines should be skipped. Lines that are prefixed with a comment token should be skipped. If the number of chapter entries matches the number of entries in the file to be imported, the chapter names should be updated. Otherwise, throw a message dialog highlighting the mismatch, and do nothing. 

The reason I thought this could be a useful feature is bc most people keep a simple playlist or text file with this kind of summary information about the media in question (e.g., film, music recording, etc). It would allow users to forgo updating chapter names manually, either through the edit chapters gui or by editing raw xml.

**Comment by mbunkus** [comment]
Thanks for the suggestion. I'll think about it, though I currently tend not to implement this.

**Comment by mbunkus** [comment]
I won't implement such a feature. Sorry.
