### ISSUE TITLE
Duplicated AAC hint in mkvmerge manpage

### ISSUE THREAD

**Issue by basicmaster** [mbunkus/mkvtoolnix#1724]
The hint

    If mkvmerge wrongfully detects that an AAC file is SBR then you can add ':0' to the track ID.

of the `mkvmerge` option `--aac-is-sbr` is repeated for the option `--reduce-to-core`.

This does not seem to be intended to me: One could remove the SBR extension from AAC files to just get the core which has half the sample rate - but the explanation to `--aac-is-sbr` states that mkvmerge will never contain an AAC decoder, which would be necessary for detecting/removing the SBR extension.

**Comment by mbunkus** [comment]
Thanks. SBR warnings only apply to AAC, of course. That the man page mentions it in the description of `--reduce-to-core` is simply me failing to cut & paste properly. I'll remove it.
