### ISSUE TITLE
mkvinfo -g foo.mkv crash

### ISSUE THREAD

**Issue by marillat** [mbunkus/mkvtoolnix#1725]
Hi Moritz,

I've received this bug related to a mkvinfo crash.
https://bugs.debian.org/827869

From my machine with a 12 MB file
````
$ mkvinfo -g sample.old_handbrake.mkv 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
zsh: abort      mkvinfo -g sample.old_handbrake.mkv
````
I've a lot of memory 
````
$ free
              total        used        free      shared  buff/cache   available
Mem:       16596740     1094244     5218488      453800    10284008    14981948
````
Here is the gdb backtrace from my machine 
````
Thread 1 "mkvinfo" received signal SIGABRT, Aborted.
0xb7fdbb68 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7fdbb68 in __kernel_vsyscall ()
#1  0xb67a4e26 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xb67a63f7 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xb6a1128f in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#4  0xb6a0ee34 in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#5  0xb6a0eead in std::terminate() () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#6  0xb6a0f160 in __cxa_throw () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#7  0xb6b8a716 in qBadAlloc() () from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#8  0xb6bf4639 in QListData::detach(int) () from /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5
#9  0x080c0dc9 in ?? ()
#10 0x080bc640 in ?? ()
#11 0x080bea35 in ?? ()
#12 0x080644c6 in ?? ()
#13 0xb6791517 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#14 0x08097d29 in ?? ()
````

**Comment by mbunkus** [comment]
Thanks for forwarding the bug. I can reproduce it here on Arch with totally unrelated files and will fix it.

**Comment by mbunkus** [comment]
Backporting the linked commit should suffice to fix the issue. It was solely a problem in the UI part and independent of the Matroska files in question. That it didn't occur before is most likely due to changes in the compiler's behavior, but the bug itself was definitely mine.

If you or the reporting user encounters crashes even with the commit applied then simply reply here, please.

**Comment by marillat** [comment]
Bug fixed for i386 and amd64 architectures.

Do you intent to release 9.3.0 soon ?

**Comment by mbunkus** [comment]
I've set myself a milestone for July 9, though I won't have much time for coding within the next two weeks. Therefore it's likely that it'll be more like four to six weeks until the next release.

**Comment by marillat** [comment]
OK. Then I'm uploading a new package to Debian with the fix in this bug report.
