### ISSUE TITLE
Documentation about cues outdated

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1729]
Hello,

the [mkvmerge documentation](https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.description.cues) currently contains the following statement: "The default is 'iframes' for video tracks and 'none' for all others." That's wrong since version 5.9 (since then cues (with CueRelativePosition and CueDuration) have been written for subtitle tracks).

Grüße
Andi

**Comment by mbunkus** [comment]
Thanks. I'll fix it.

**Comment by mkver** [comment]
Did you forget to update the documentation on the website or will it be automatically updated when 9.3 comes out (or is there just some caching involved (I emptied my cache so it's not mine))?

**Comment by mbunkus** [comment]
The documentation on the web site reflects the latest release. It's only updated when a new release is made.
