### ISSUE TITLE
How to extract only forced subtitles with a batch muxing?

### ISSUE THREAD

**Issue by davboc** [mbunkus/mkvtoolnix#1730]
Hi all!

There is an option to extract only forced subtitles using a windows script and mkvmerge.exe?

Now i use this script

for %%A IN (*.mkv) do (
"C:/Program Files/mkvtoolnix\mkvmerge.exe" -o "remux-%%~nA.mkv" -a ita "%%~A"
)

that extract only audio track with Italian language, but I can't find the way to extract only forced subtitles.

Thanks

**Comment by mbunkus** [comment]
No such option exists, and I don't plan on adding one. Sorry.
