### ISSUE TITLE
Suggestion: Allow flexible header removal compression

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1732]
Hello,

I know that you once included header removal compression as a default and later deactivated it for most tracks because of lacking support by players. And as long as I only used the header removal compression implemented in version 5.9 and older, I could understand this because the gains are not that big. But then I found the "analyze_header_removal" compression method that is not explained in the documentation but can be found via [code inspection](https://github.com/mbunkus/mkvtoolnix/blob/master/src/merge/mkvmerge.cpp#L1055) or by trying an invalid compression method (the [resulting error message](https://github.com/mbunkus/mkvtoolnix/blob/master/src/merge/mkvmerge.cpp#L1073) contains 'analyze_header_removal') and I found out that there is one type of stream for which header removal offers anything but tiny amounts of size reduction: DTS tracks. Your old implementation only got rid of the 4 B syncword in every packet. But for ordinary 5.1 channel DTS tracks one can remove 42 B per packet resulting in 3937.5 B/s which are saved (I exclude the tiny amount of extra data in the header). For a 1.5h DTS track this amounts to savings of more than 20 MB. For stereo DTS it seems to be 25 B per packet, a bit lower, but not negligible.
I'm of course completely aware that mkvmerge does not use a first pass to analyze the files before muxing in earnest. So mkvmerge doesn't know what the optimal number of bytes to strip is. Here is my proposal: You let the user willing to use header removal compression (i.e. by default, header removal compression should be deactivated.) choose a number (say n) of bytes to try to strip. During muxing mkvmerge checks whether the first n bytes really coincide (i.e. checks whether n is too big). If yes, then it strips the first n bytes and writes the file. If the answer is no, then mkvmerge aborts and reports how many first bytes were equal up to the packet at which it aborted. Should remuxing turn out to be successfull mkvmerge could additionally report whether n was optimal or whether a bigger number would have been possible, too.
Thanks in advance.

Andi

PS: The documentation still refers to the BZ2 and LZO compression methods, although support for them has been removed a long time ago. And the 'analyze_header_removal' method (which is not found in the documentation) currently creates invalid files: They have the ContentEncodings and the ContentEncoding ebml-tag, but nothing else. (6D 80 83 62 40 80 in hex; 6D 80 means ContentEncodings, 83 means that the next three bytes belong to the data of ContentEncodings; 62 40 stands for ContentEncoding and 80 means that the size of the data of ContentEncoding is 0. According to the specs this means that ContentEncodingType is 0 (i.e. compression, not encryption). But then a ContentCompression entry is mandatory, but lacking.)

**Comment by mbunkus** [comment]
The method `analyze_header_removal` is a development tool. It is not meant to be used by end users, and it is not supposed to create valid files. Its use is to determine which bytes are common among all frames. As such it cannot guarantee that the files created are valid: if splitting is active then it couldn't fix the track headers in all but the last file. Therefore I won't document it.

I also won't extend header removal compression. Support for it on the player's side was much too lacking, and extending support now would send the wrong message to users who would expect features to work. Sorry.
