### ISSUE TITLE
Delay-Start Audio Tracks Undetected

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#1734]
Hello, thank you for your hard work on mkvtoolnix, it's appreciated.  Audio tracks that delay start are undetected by mkvmerge v9.2; only tracks that start in sync with the video are properly detected and converted.  Is it possible to increase the track scan duration (like ffmpeg's analyzeduration and probesize options) so delay-start tracks can be automatically discovered and included?

This example has one audio track (0x82) that starts playing in sync with the video and three audio tracks (0x80,0x81,0x83) that start 16.590 seconds later.  Essentially, one commentary track starts commenting alongside the distributor's marquee cards, while the surround, stereo, and secondary commentary track start with the feature's title cards 16.590 seconds later.  Mkvmerge only detects audio track 0x82, ignoring the other three.

`$ ffprobe -analyzeduration 2147483647 -probesize 2147483647 -i video.vob`
>ffprobe version 2.8.7 Copyright (c) 2007-2016 the FFmpeg developers
Input #0, mpeg, from 'video.vob':
  Duration: 01:25:43.60, start: 0.060000, bitrate: 6390 kb/s
    Stream #0:0[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, bt470bg), 720x480 [SAR 8:9 DAR 4:3], max. 8500 kb/s, 29.97 fps, 59.94 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x82]: Audio: ac3, 48000 Hz, mono, fltp, 96 kb/s
    Stream #0:2[0x81]: Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Stream #0:3[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:4[0x83]: Audio: ac3, 48000 Hz, mono, fltp, 96 kb/s

`$ mkvmerge -o video.mkv video.vob`
>mkvmerge v9.2.0 ('Photograph') 64bit
'video.vob': Using the demultiplexer for the format 'MPEG program stream'.
'video.vob' track 0: Using the output module for the format 'MPEG-1/2'.
'video.vob' track 1: Using the output module for the format 'AC-3'.
The file 'video.mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Muxing took 2 minutes 16 seconds.

`$ mediainfo video.mkv`
>General
Format                                   : Matroska
Format version                           : Version 4 / Version 2
Writing application                      : mkvmerge v9.2.0 ('Photograph') 64bit
Writing library                          : libebml v1.3.3 + libmatroska v1.4.4

>Video
[_...unnecessary output edited/removed..._]

>Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 25mn
Bit rate mode                            : Constant
Bit rate                                 : 96.0 Kbps
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Stream size                              : 58.9 MiB (2%)
Default                                  : Yes
Forced                                   : No

P.S. - My current workaround is to extract all audio tracks and combine separately with an appropriate offset, which of course works...once the offset is discovered.  But.  Finding the offset can take quite a while.  Thanks for hearing me out.

`$ for channel in {0..3}; do tcextract -i video.vob -x ac3 -a $channel > "audio$channel.ac3" ;done`
`$ mkvmerge -o video.mkv --default-language en -A video.vob -y 0:+16590 audio2.ac3 -y 0:+16590 audio1.ac3 audio3.ac3 -y 0:16590 audio4.ac3`

`$ mediainfo video.mkv `
>General
Format                                   : Matroska
Format version                           : Version 4 / Version 2
Writing application                      : mkvmerge v9.2.0 ('Photograph') 64bit
Writing library                          : libebml v1.3.3 + libmatroska v1.4.4

>Video
[_...unnecessary output edited/removed..._]

>Audio 1
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 25mn
Bit rate mode                            : Constant
Bit rate                                 : 448 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Delay relative to video                  : 16s 590ms
Stream size                              : 274 MiB (7%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

>Audio 2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 25mn
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Delay relative to video                  : 16s 590ms
Stream size                              : 117 MiB (3%)
Language                                 : English
Default                                  : No
Forced                                   : No

>Audio 3
ID                                       : 4
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 25mn
Bit rate mode                            : Constant
Bit rate                                 : 96.0 Kbps
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Stream size                              : 58.9 MiB (2%)
Language                                 : English
Default                                  : No
Forced                                   : No

>Audio 4
ID                                       : 5
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 25mn
Bit rate mode                            : Constant
Bit rate                                 : 96.0 Kbps
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Delay relative to video                  : 16s 590ms
Stream size                              : 58.7 MiB (2%)
Language                                 : English
Default                                  : No
Forced                                   : No

**Comment by mbunkus** [comment]
Thanks for the comprehensive report. Yes, this is a known limitation mkvmerge currently has. I'll look into adding an option to expand the probe range. Currently it's size-based, not time-based, and I'm not sure whether I should change that to time-based or not.

No matter how that decision ends up I will implement an option to extend that range.

**Comment by mkver** [comment]
Is the insufficient probesize also the reason for mkvmerge not finding subtitles in vob-files even when they are there?

**Comment by mbunkus** [comment]
Yes. MPEG program streams (that's what VOBs are) don't have track headers or some other kind of directory of what kind of tracks are present. You have to read the whole file, and the tracks you encounter along the way are the ones that are present.

DVDs do contain more information in their IFO files but mkvmerge cannot parse those (and most likely never will).

**Comment by optimiz** [comment]
Adding a probe-range option is a wonderful long-term solution.  If I had a preference, it would be time-based, since _that_ is the essential issue: time delay offsets.  But, I realize size-based processing is easier.  So.  Perhaps changing the current size-based approach to percent-of-input would be the best of both worlds?  For example, a probe size of 5% of input size would include 4.5 minutes of a 90 minute video whether the input was a 3Gb DVD or 20Gb BR.  Thanks for the quick response.

**Comment by mbunkus** [comment]
5% of a 20 GB Blu-ray would also require parsing 1 GB of data (and a lot of Blu-rays are more in the region of 30 to 40 GB), which would cause a very noticeable delay both during file type identification as well as when starting to mux.

I'm leaning more in the direction of changing the probing range to be time-based, to use something between ten and 20 seconds as the default and to make that changeable via options in both mkvmerge and the GUI. Such a default is more in line with what mkvmerge does at the moment — and defaults are usually chosen to apply to most common situations, not to capture all possible cases.

**Comment by optimiz** [comment]
Sounds good.  Since mkvtoolnix already covers nearly all of my use cases, one more is icing on the cake.  Thanks again.

P.S. - 5% was just an easy-math example for the percent-of-file-size proposal, I didn't mean for that percentage to be used directly.  After all, the longest delay-start audio discrepancy I've encountered is ~40 seconds, which is even under 1% of a 90-minute video.  Sorry for the confusion.

**Comment by mbunkus** [comment]
I've reconsidered about the time-based approach to detection. As far as I can tell only two formats would actually benefit from a setting allowing the user to fine-tune the detection range: MPEG program streams (e.g. VOBs) and MPEG transport streams (e.g. .m2ts on a Blu-ray).

MPEG PS does lend itself nicely to a time-based approach. However, MPEG TS does not due to two issues:

1. In MPEG TS a demuxer must first look for a PAT (program allocation table) and a PMT (program map table). Without those tables a demuxer doesn't know whether a stream it finds actually contains timestamps (this is a simplification). The point is: a demuxer can only look for timestamps after both PAT and PMT have been found, but the search for PAT and PMT should also be bounded by a probing range — and that range can only be a size-based range.
2. A lot of MPEG TS files come from very bad sources (e.g. TV broadcasts). It's not unusual for such files to have timestamps that are all over the place. For example, in one of my test files the first three timestamps are 12:23:45, 07:12:41 and 25:38:10. Only after a couple of MB do the timestamps stabilize and start sequently from somewhere around 21:30:25. This is a span of over eight hours. Using a time-based probing range on such files would make detection fail right at the start of the file.

What I'm going to do is to let the user specify a percentage of the file size to probe. Additionally mkvmerge will have built-in, unchangeable, absolute minimums (e.g. at least 5 MB or whatever percentage the user has specified, whichever is larger).

What the default for this percentage will be is debatable. Let's take a look at the higher end of files we're likely to encounter: e.g. the Blu-ray for "The Force awakens". The main title is 37.4 GB big with a runtime of 2:18:07 amounting to 37.4 GB * 1024 MB/GB / (2h * 3600s/h + 18m * 60s/m + 7s) = 38,297.6 MB/8,287s = 4.621 MB/s . If we we would like to scan roughly 20 seconds by default then the this would correspond to a size of 20s * 4.621 MB/s = 92.42 MB. This is 92.42MB * 100 / 38,297.6 MB = 0.24%. So maybe 0.25% might make a nice default.

The built-in absolute minimum would probably be somewhere around 2 to 5 MB. This is to ensure the user doesn't shoot herself in the foot too much.

**Comment by optimiz** [comment]
That's great news, thank you for your diligence and effort.  After using the MKV format for so long, I'd forgotten how bad PTS timings can be directly from commercial discs and broadcasters.  I'm glad you're well aware of your inputs and able keep well-intentioned but misguided people like me honest.

0.24% is a good default starting point.  Using your 92Mb example coupled with an average of 30-50Mbps I/O from a (non-SSD) hard drive, it'll be ~3 seconds of probe time.  Basically unnoticeable in the scheme of things considering it'll take much more time to perform the actual conversion.  For me, the fastest conversion to MKV for a 5Gb file from hard drive is ~3.5 minutes, so adding even 10 seconds to that (scripted) workflow is inconsequential.**  In my mind, the duration of any analyze or probe time is secondary to the completeness of the final output -- that's why I choose to max ffprobe's analyze and probe size values in the first place.

Thanks again.  I appreciate and value your software and talent.

**_My thought process is... Time-wise, conversion to MKV is front-end loaded: Perform once and you're done.  So ultimately, conversion time ends up not mattering in the long run.  Especially, when I consider the time spent recording or recovering data, or re-encoding.  From that perspective, conversion to MKV happens at warp speed -- and would seem so even if it took 10, 20 or even 30 seconds longer to process as a percentage of the total file size.  Personally, I never remember how long any particular conversion took when later playing/viewing, or almost any other subsequent back-end purpose._

**Comment by mbunkus** [comment]
New [pre-builds](https://mkvtoolnix.download/windows/pre/) that include the fix are available.
