### ISSUE TITLE
MKVMerge feature request:  turn file names into chapter titles

### ISSUE THREAD

**Issue by nitz01** [mbunkus/mkvtoolnix#1737]
Hi.  Please consider adding the ability to use the file names of the input files as the chapter names of the output file when joining audio tracks into a single MKA file as follows.

`mkvmerge -o OUTPUT.mka --generate-chapters when-appending INPUT1.opus + INPUT2.opus`

This would be _very_ useful in assembling audio books out of separate audio tracks.  Thanks!

**Comment by mbunkus** [comment]
Thanks for posting it here, too.

**Comment by mbunkus** [comment]
Oops, wrong issue. Hasn't been implemented yet.

**Comment by mbunkus** [comment]
The feature has been implemented as two new variables in the chapter generation name template, `<FILE_NAME>` and `<FILE_NAME_WITH_EXT>`. New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include the functionality have been uploaded. See the tool tip for the "name template" input on the "output" tab in the GUI.

**Comment by nitz01** [comment]
Wow, that was fast -- you make it seem so easy.  I'll try it out tonight using one of my audio-book CDs.  Thank you very much.

Date: Sun, 10 Jul 2016 11:38:21 -0700

**Comment by nitz01** [comment]
Tested and confirmed as working.  Thanks again; this will save several steps when converting books-on-CD into audiobooks for my phone.  (If anyone's interested, here's the batch file I'll be using to do it.)

```
@echo off
echo Muxing Audio Files -- Please Wait
set exePath=C:\Program Files\MKVToolnix
set CHAPTERS=--generate-chapters-name-template ^"^<FILE_NAME^>^" --generate-chapters when-appending
for %%* in (.) do set FOLDER=%%~n*
for /f "tokens=*" %%g in ('dir /b *.opus') do call :STITCH "%%g"
"%exePath%\mkvmerge.exe" -o "%FOLDER%.mka" %CHAPTERS% %PHRASE% > nul
exit

:STITCH
  set NAME="%~n1
  if defined PHRASE (set PHRASE=%PHRASE% + %NAME%.opus") else set PHRASE=^%NAME%.opus"
```
