### ISSUE TITLE
The GUI opens a superfluous tab for an .mtxcfg file when dropping it onto a blank tab in the merge tool

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1738]
Actually I'm not sure whether it is a bug or maybe I should assign it as a feature request, but I would like to share with you about interesting behaviour that I have noticed recently. Personally I consider it as a thing which should be fixed because it's really inconvenient (especially when you drop many configuration files). But let's cut to the chase:

**Run the GUI and go to the merge tool. You will see a blank (empty) tab. Now drag and drop your _.mtxcfg_ file onto that blank tab → you will see that your configuration file will be open in a separate tab. The previous tab will stay empty of course = ridiculous.**

Hence I would like to ask you to prevent opening a superfluous tab when dropping a configuration file onto a blank tab in the merge tool. To put it more simply: the GUI should add such a file to that blank tab, not to create a new (superfluous) tab for it.

Thank you very much for implementing this.

**Comment by mbunkus** [comment]
I'll look into it — shouldn't be too hard to change. Note, though, that "empty" is relative. I will only consider a tab empty if all of its controls are set to the same settings they're set to right after you open new mux settings. This will be using the same checks that determine whether or not the tab has been changed and should be saved.

**Comment by remuxer32** [comment]
Yes, I know that "empty" is relative. In this case I mean a tab that doesn't contain any file(s) and, of course, a tab where mux settings are completely new = pristine. So, yes, I fully agree with you :)
