### ISSUE TITLE
Probe range % error on merging

### ISSUE THREAD

**Issue by sirius4k** [mbunkus/mkvtoolnix#1742]
Started with 9.3.0
When I try to merge a BD disc to mkv, I get errors like this: The probe range percentage '4.47003e-316' is invalid (With Default Probe range % of 0.30)
Tried to set Probe range % to 0.40 and got: The probe range percentage '3.9783e-316' is invalid.
With Probe range % set to 50.0 I got: The probe range percentage '4.39907e-316' is invalid.

**Comment by mbunkus** [comment]
Duplicate of #1741.
