### ISSUE TITLE
automatic output file name adjustment broken

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1743]
Since v9.3.0 the automatic adjustment of the suggested output file name is broken on Windows. This may be due to the change displaying the file names with backslashes instead of slashes on Windows.

This bug affects at least but not exclusively:

- changing the extension based on the track types selected for muxing
- changing the extension based on the "WebM" output mode
- adding suffixes for avoiding overwriting existing files

**Comment by mbunkus** [comment]
New [pre-builds with the fix included](https://mkvtoolnix.download/windows/pre/) are available.

**Comment by remuxer32** [comment]
**@Mosu**

Thanks for the quick fix. I've just downloaded the latest pre-build and confirm that your fix works great. Good job :)
