### ISSUE TITLE
Problem to cut file longer than 24 hours

### ISSUE THREAD

**Issue by Bobolecoco** [mbunkus/mkvtoolnix#1744]
When you try to cut the output file after time-codes, the files are correctly written until your reach 24 hours, then, it leaves a unique file. For example :
I have à 48 hours long video ;
I want to cut it in 8 hours files ;
I obtain 3 [001, 002, 003] "8 hours" files (for the 24 first hours) and 1 [004] "24 hours" file.

**Comment by mbunkus** [comment]
Thanks for the report. Please tell me exactly the mux settings you've used. The easiest way is to set up the mux configuration the way you had it. Then go to "Merge" → "Show command line" and copy & paste the command line shown here.

**Comment by Bobolecoco** [comment]
Here it is : 
$MKVTOOLNIXPATH/mkvtoolnix\mkvmerge.exe --ui-language fr --output ^"$FILEPATH\SGDQ [2-5].mkv^" --language 0:und --language 1:und ^"^(^" ^"$FILEPATH\SGDQ [2-5].mp4^" ^"^)^" --split duration:08:00:00 --track-order 0:0,0:1

**Comment by Bobolecoco** [comment]
And here is the "log" (in french) : 
--- Rapport de la tâche « Fusion vers le fichier « SGDQ [2-5].mkv » dans le dossier « $FILEPATH » » lancée le 2016-07-17 23:37:08 ---
mkvmerge v9.3.1 ('Mask Machine') 64bit
« Z:\Enregistrements\SGDQ [2-5].mp4 » : Utilisation du démultiplexeur pour le format « Flux de transport MPEG ».
« Z:\Enregistrements\SGDQ [2-5].mp4 » piste 0 : Utilisation du module de sortie pour le format « AAC ».
« Z:\Enregistrements\SGDQ [2-5].mp4 » piste 1 : Utilisation du module de sortie pour le format « AVC/H.264 (sans trame) ».
Le fichier « Z:\Enregistrements\SGDQ [2-5]-001.mkv » est ouvert en écriture.
Les entrées CUE (l'index) sont en cours d'écriture…
Le fichier « Z:\Enregistrements\SGDQ [2-5]-002.mkv » est ouvert en écriture.
Les entrées CUE (l'index) sont en cours d'écriture…
Le fichier « Z:\Enregistrements\SGDQ [2-5]-003.mkv » est ouvert en écriture.
Les entrées CUE (l'index) sont en cours d'écriture…
Le fichier « Z:\Enregistrements\SGDQ [2-5]-004.mkv » est ouvert en écriture.
Les entrées CUE (l'index) sont en cours d'écriture…
--- Le multiplexage a pris 37 minutes 5 secondes. ---

**Comment by Bobolecoco** [comment]
Those results were obtained in "Windows 10" with "Version 9.3.1 « Mask Machine »".

Same thing happens in Debian Jessie with v7.3.0 ('Nouages') : 

Command line : 
mkvmerge --output "$FILEPATH/SGDQ [2-5].mkv" --language 0:und --language 1:und "/media/pi/4AAC2DEDAC2DD3EB/SGDQ [2-5].mp4" --split duration:08:00:00 --track-order 0:0,0:1

Output : 
mkvmerge v7.3.0 ('Nouages') 32bit built on Nov  3 2014 16:34:23
'/media/pi/4AAC2DEDAC2DD3EB/SGDQ [2-5].mp4' : utilisation du démultiplexeur pour le format 'Flux de transport MPEG'.
'/media/pi/4AAC2DEDAC2DD3EB/SGDQ [2-5].mp4' piste 0 : utilisation du module de sortie pour le format 'AAC'.
'/media/pi/4AAC2DEDAC2DD3EB/SGDQ [2-5].mp4' piste 1 : utilisation du module de sortie pour le format 'AVC/h.264 (unframed)'.
Le fichier '$FILEPATH/SGDQ [2-5]-001.mkv' est ouvert en écriture.
Progression : 16%
Les entrées d'index sont créées...
Le fichier '$FILEPATH/SGDQ [2-5]-002.mkv' est ouvert en écriture.
Progression : 33%
Les entrées d'index sont créées...
Le fichier '$FILEPATH/SGDQ [2-5]-003.mkv' est ouvert en écriture.
Progression : 50%
Les entrées d'index sont créées...
Le fichier '$FILEPATH/SGDQ [2-5]-004.mkv' est ouvert en écriture.
Processus arrêté%

**Comment by Bobolecoco** [comment]
And the "mkvinfo" of the files : 

mkvinfo $FILEPATH/SGDQ\ \[2-5\]-001.mkv 
+ En-tête EBML
|+ Version EBML : 1
|+ Version EBML lue : 1
|+ Longueur maximale de l'identifiant EBML : 4
|+ Longueur maximale de la taille EBML : 8
|+ Type de document : matroska
|+ Version du type de document : 4
|+ Version lue du type de document : 2
+ Segment, taille 2510333928
|+ En-tête de recherche (sous-entrées ignorées)
|+ EbmlVoid (taille : 4027)
|+ Informations sur le segment
| + Coefficient temporel : 1000000
| + Application de multiplexage : libebml v1.3.0 + libmatroska v1.4.1
| + Application d'écriture : mkvmerge v7.3.0 ('Nouages') 32bit built on Nov  3 2014 16:34:23
| + Durée : 28802.056s (08:00:02.056)
| + Date : Sun Jul 17 23:30:41 2016 UTC
| + UID de segment : 0xa7 0x56 0x0b 0x22 0x13 0xaf 0xc8 0xb4 0x24 0xf5 0x8b 0xac 0x42 0x8e 0x53 0x50
|+ Pistes du segment
| + Une piste
|  + Numéro de piste : 1 (identifiant de piste pour mkvmerge & mkvextract : 0)
|  + UID de piste : 14485875724373995298
|  + Type de piste : audio
|  + Identifiant du codec : A_AAC
|  + Données de codec privées, longueur 2
|  + Durée par défaut : 23.220ms (43.066 images/champs par seconde pour une piste vidéo)
|  + Langue : und
|  + Audio track
|   + Fréquence d'échantillonnage : 44100
|   + Canaux : 2
| + Une piste
|  + Numéro de piste : 2 (identifiant de piste pour mkvmerge & mkvextract : 1)
|  + UID de piste : 9340274705854448367
|  + Type de piste : video
|  + Marque de laçage : 0
|  + Cache minimum : 1
|  + Identifiant du codec : V_MPEG4/ISO/AVC
|  + Langue : und
|  + Piste vidéo
|   + Largeur (pixels) : 852
|   + Hauteur (pixels) : 480
|   + Largeur à l'écran : 852
|   + Hauteur à l'écran : 480
|  + Données de codec privées, longueur 38 (profil h.264 : Main @L3.0)
|  + Durée par défaut : 33.000ms (30.303 images/champs par seconde pour une piste vidéo)
|+ EbmlVoid (taille : 1043)
|+ Cluster


mkvinfo $FILEPATH/SGDQ\ \[2-5\]-002.mkv 
+ En-tête EBML
|+ Version EBML : 1
|+ Version EBML lue : 1
|+ Longueur maximale de l'identifiant EBML : 4
|+ Longueur maximale de la taille EBML : 8
|+ Type de document : matroska
|+ Version du type de document : 4
|+ Version lue du type de document : 2
+ Segment, taille 2541810236
|+ En-tête de recherche (sous-entrées ignorées)
|+ EbmlVoid (taille : 4027)
|+ Informations sur le segment
| + Coefficient temporel : 1000000
| + Application de multiplexage : libebml v1.3.0 + libmatroska v1.4.1
| + Application d'écriture : mkvmerge v7.3.0 ('Nouages') 32bit built on Nov  3 2014 16:34:23
| + Durée : 28800.064s (08:00:00.064)
| + Date : Sun Jul 17 23:30:41 2016 UTC
| + UID de segment : 0x2c 0xfb 0xf4 0xc8 0x7e 0x72 0x7b 0xc4 0xf6 0x51 0x92 0x5e 0x84 0xb3 0x9c 0xb5
|+ Pistes du segment
| + Une piste
|  + Numéro de piste : 1 (identifiant de piste pour mkvmerge & mkvextract : 0)
|  + UID de piste : 14485875724373995298
|  + Type de piste : audio
|  + Identifiant du codec : A_AAC
|  + Données de codec privées, longueur 2
|  + Durée par défaut : 23.220ms (43.066 images/champs par seconde pour une piste vidéo)
|  + Langue : und
|  + Audio track
|   + Fréquence d'échantillonnage : 44100
|   + Canaux : 2
| + Une piste
|  + Numéro de piste : 2 (identifiant de piste pour mkvmerge & mkvextract : 1)
|  + UID de piste : 9340274705854448367
|  + Type de piste : video
|  + Marque de laçage : 0
|  + Cache minimum : 1
|  + Identifiant du codec : V_MPEG4/ISO/AVC
|  + Langue : und
|  + Piste vidéo
|   + Largeur (pixels) : 852
|   + Hauteur (pixels) : 480
|   + Largeur à l'écran : 852
|   + Hauteur à l'écran : 480
|  + Données de codec privées, longueur 38 (profil h.264 : Main @L3.0)
|  + Durée par défaut : 33.000ms (30.303 images/champs par seconde pour une piste vidéo)
|+ EbmlVoid (taille : 1093)
|+ Cluster


mkvinfo $FILEPATH/SGDQ\ \[2-5\]-003.mkv 
+ En-tête EBML
|+ Version EBML : 1
|+ Version EBML lue : 1
|+ Longueur maximale de l'identifiant EBML : 4
|+ Longueur maximale de la taille EBML : 8
|+ Type de document : matroska
|+ Version du type de document : 4
|+ Version lue du type de document : 2
+ Segment, taille 2416223646
|+ En-tête de recherche (sous-entrées ignorées)
|+ EbmlVoid (taille : 4027)
|+ Informations sur le segment
| + Coefficient temporel : 1000000
| + Application de multiplexage : libebml v1.3.0 + libmatroska v1.4.1
| + Application d'écriture : mkvmerge v7.3.0 ('Nouages') 32bit built on Nov  3 2014 16:34:23
| + Durée : 28801.844s (08:00:01.844)
| + Date : Sun Jul 17 23:30:41 2016 UTC
| + UID de segment : 0xfb 0xb4 0xc0 0x5a 0x8b 0xa4 0xf7 0xaa 0xfd 0xa1 0xde 0xb8 0x71 0x3b 0x03 0xe2
|+ Pistes du segment
| + Une piste
|  + Numéro de piste : 1 (identifiant de piste pour mkvmerge & mkvextract : 0)
|  + UID de piste : 14485875724373995298
|  + Type de piste : audio
|  + Identifiant du codec : A_AAC
|  + Données de codec privées, longueur 2
|  + Durée par défaut : 23.220ms (43.066 images/champs par seconde pour une piste vidéo)
|  + Langue : und
|  + Audio track
|   + Fréquence d'échantillonnage : 44100
|   + Canaux : 2
| + Une piste
|  + Numéro de piste : 2 (identifiant de piste pour mkvmerge & mkvextract : 1)
|  + UID de piste : 9340274705854448367
|  + Type de piste : video
|  + Marque de laçage : 0
|  + Cache minimum : 1
|  + Identifiant du codec : V_MPEG4/ISO/AVC
|  + Langue : und
|  + Piste vidéo
|   + Largeur (pixels) : 852
|   + Hauteur (pixels) : 480
|   + Largeur à l'écran : 852
|   + Hauteur à l'écran : 480
|  + Données de codec privées, longueur 38 (profil h.264 : Main @L3.0)
|  + Durée par défaut : 33.000ms (30.303 images/champs par seconde pour une piste vidéo)
|+ EbmlVoid (taille : 1093)
|+ Cluster


mkvinfo $FILEPATH/SGDQ\ \[2-5\]-004.mkv 
+ En-tête EBML
|+ Version EBML : 1
|+ Version EBML lue : 1
|+ Longueur maximale de l'identifiant EBML : 4
|+ Longueur maximale de la taille EBML : 8
|+ Type de document : matroska
|+ Version du type de document : 4
|+ Version lue du type de document : 2
+ Segment, taille 0
|+ EbmlVoid (taille : 4096)

**Comment by mbunkus** [comment]
Thanks for the additional information. I cannot reproduce this at the moment, but I don't have an MP4 file handy here either. I've created a file ~47.5 hours long and used your `--split duration:08:00:00`. This produced six files of which the first five had a duration of ~8 hours and one contained the remaining ~7.5 hours. Looks fine so far.

Can you please try to merge the file into one huge Matroska file (= without splitting) and see if this produces a file with all the content? It's possible that mkvmerge aborts the process somewhere, and I'ld like to make sure it can read the whole file fine.

**Comment by Bobolecoco** [comment]
VLC doesn't seems to be able to read the file, so the problem comes from it (and any other file downloaded from twitch.tv [with livestreamer ou JDownloader 2]) 

Command line : 
mkvmerge --output "$FILEPATH/SGDQ [2-5].mkv" --language 0:und --language 1:und "/media/pi/4AAC2DEDAC2DD3EB/SGDQ [2-5].mp4" --track-order 0:0,0:1

Output : 
mkvmerge v7.3.0 ('Nouages') 32bit built on Nov  3 2014 16:34:23
'/media/pi/4AAC2DEDAC2DD3EB/SGDQ [2-5].mp4' : utilisation du démultiplexeur pour le format 'Flux de transport MPEG'.
'/media/pi/4AAC2DEDAC2DD3EB/SGDQ [2-5].mp4' piste 0 : utilisation du module de sortie pour le format 'AAC'.
'/media/pi/4AAC2DEDAC2DD3EB/SGDQ [2-5].mp4' piste 1 : utilisation du module de sortie pour le format 'AVC/h.264 (unframed)'.
Le fichier '/home/pi/Freebox/Enregistrements/SGDQ [2-5].mkv' est ouvert en écriture.
Processus arrêté%

mkvinfo $FILEPATH/SGDQ\ \[2-5\].mkv 
+ En-tête EBML
|+ Version EBML : 1
|+ Version EBML lue : 1
|+ Longueur maximale de l'identifiant EBML : 4
|+ Longueur maximale de la taille EBML : 8
|+ Type de document : matroska
|+ Version du type de document : 4
|+ Version lue du type de document : 2
+ Segment, taille 0
|+ EbmlVoid (taille : 4096)

Final size of the file : 8,51 Go (9 143 587 025 octets)

**Comment by mbunkus** [comment]
Alright. Thanks for testing & for keeping me updated.
