### ISSUE TITLE
Handle filename with '\' in MKVToolnix "Merge" section.

### ISSUE THREAD

**Issue by PiroXiline** [mbunkus/mkvtoolnix#1746]
Adding a file to "Merge" section produce an error window:
>Unrecognized file format
>The file was not recognized as a supported format (exit code: 2).
![screenshot_2016-07-18_15-23-09](https://cloud.githubusercontent.com/assets/3512530/16914622/b67f6bf6-4cfb-11e6-953f-259000020ffa.png)

Cause: '\' in filename.

File handles normally in "Edit headers", "Edit chapters" sections.

Additional: MKVToolNix GUI v9.1.0 "Little Earthquakes" on Arch Linux. Issue tested on FSs Ext4 and ZFS.

Suggest:
a) add handling, maybe from "Edit headers", "Edit chapters" sections.
b) add more informative error message. Spend some time figuring-out.
[sample.zip](https://github.com/mbunkus/mkvtoolnix/files/368860/sample.zip)

**Comment by mbunkus** [comment]
Thanks for the report. I'll look into it.

**Comment by mbunkus** [comment]
I cannot reproduce this with 9.3.1 (I'm using and developing on Arch Linux, too), neither with a couple of files created by myself nor with the sample you've provided. Please update to v9.3.1 and try again.

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
