### ISSUE TITLE
mkvinfo and MKVToolNix determine FLAC 24-bit streams as 32-bit

### ISSUE THREAD

**Issue by PiroXiline** [mbunkus/mkvtoolnix#1747]
[24-bit.zip](https://github.com/mbunkus/mkvtoolnix/files/368933/24-bit.zip)

MKVToolNix in "Merge" section in "Tracks, chapters and tags:" display for every FLAC 24-bit stream Properties:
> ..., 32 bits per sample
> ![flac 24-bit](https://cloud.githubusercontent.com/assets/3512530/16914758/afc7ff20-4cfc-11e6-81ea-2a709c5dd3b6.png)

This is, probably, due to determination in mkvinfo:

>|+ Segment tracks
>|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
>|  + Codec ID: A_FLAC
>|  + Audio track
>|   + Bit depth: 32

MKV 24-bit tags stream seems to be present in container.

Additional:
This is probably legacy "feature". As number of years ago there was a mixed bag of FLAC encoder things about 24-bit streams. As 24-bit float was encoded as 32-bit strict for many ears.

MKVToolNix GUI v9.1.0 "Little Earthquakes" on Arch Linux.

**Comment by mbunkus** [comment]
mkvmerge reports what's in the container headers and trusts those over the bitstream. Therefore this doesn't seem to be a bug; if the Matroska file you've added says the track has 32bits then that's what's shown. Sorry.
