### ISSUE TITLE
compatibility tricks don't work, player don't recognize mkv

### ISSUE THREAD

**Issue by buchodeq** [mbunkus/mkvtoolnix#1748]
Hi everybody, My player sony bdps480 cannot recognize a mkv file, on the screen "altered files or unsupported" appears, but at the same time, the player opens and plays very well similar mkv with the same format and features. I cannot understand the way to solve it. I've tried all tricks suggested without improving. I usually use mkvtool 8.3. Thanks for the help
the mkv info:

General
Unique ID                                : 212248741334706514774291686822945500215 (0x9FAD9EE38A83A8DE91209ADBC2EC2C37)
Complete name                            : D:\dvd\Bla - la fine
Format                                   : Matroska
Format version                           : Version 2
File size                                : 1.24 GiB
Duration                                 : 1h 12mn
Overall bit rate                         : 2 458 Kbps
Movie name                               : Bla - la fine
Encoded date                             : UTC 2016-07-18 05:20:05
Writing application                      : mkvmerge v8.3.0 ('Over the Horizon') 32bit
Writing library                          : libebml v1.3.1 + libmatroska v1.4.2
DURATION                                 : 01:08:38.761000000
NUMBER_OF_FRAMES                         : 42
NUMBER_OF_BYTES                          : 1979
_STATISTICS_WRITING_APP                  : mkvmerge v8.3.0 ('Over the Horizon') 32bit
_STATISTICS_WRITING_DATE_UTC             : 2016-07-18 05:20:05
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High 10@L3.0
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1h 12mn
Bit rate                                 : 2 089 Kbps
Width                                    : 768 pixels
Height                                   : 504 pixels
Display aspect ratio                     : 3:2
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.225
Stream size                              : 1.06 GiB (85%)
Title                                    : ano hi ni kaeritai
Writing library                          : x264 core 116 r2074 2641b9e
Encoding settings                        : cabac=1 / ref=3 / deblock=1:-2:-2 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / psy_rd=0.90:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc=crf / mbtree=0 / crf=17.0 / qcomp=0.60 / qpmin=15 / qpmax=67 / qpstep=4 / ip_ratio=1.40 / pb_ratio=1.30 / aq=1:0.90
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No
DURATION                                 : 01:12:24.553000000
NUMBER_OF_FRAMES                         : 104165
NUMBER_OF_BYTES                          : 1163583690
_STATISTICS_WRITING_APP                  : mkvmerge v8.3.0 ('Over the Horizon') 32bit
_STATISTICS_WRITING_DATE_UTC             : 2016-07-18 05:20:05
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Audio #1
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 12mn
Bit rate mode                            : Constant
Bit rate                                 : 128 Kbps
Channel count                            : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 66.3 MiB (5%)
Title                                    : audio ita
Language                                 : Italian
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 1h 12mn
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel count                            : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 99.4 MiB (8%)
Title                                    : audio jap
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Text #1
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : sub ita
Language                                 : Italian
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 5
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : parti censurate
Language                                 : Italian
Default                                  : No
Forced                                   : No

**Comment by mbunkus** [comment]
I'm sorry, but I cannot really help with playback issues. The players are at fault here, they only support limited subsets of Matroska and break often if they encounter elements they don't know about (the Matroska specs explicitly state that players must ignore elements unknown to them, but players often simply break).

Apart from "try the latest release" and "try all the methods listed [here](https://github.com/mbunkus/mkvtoolnix/wiki/Improving-playback-compatibility-with-players)" I cannot offer more, and I won't spend time on such issues. Sorry.

**Comment by mbunkus** [comment]
You might want to try asking on the [Doom9 forum](http://forum.doom9.org/showthread.php?t=155732). A lot of knowledgeable people read and post there, and it's quite possible one of them has the same player you have. No guarantees, though.

**Comment by mkver** [comment]
At first I wanted to write: "Try a different muxer." And I wanted to refer you to mkclean. But then I found something: Your file is a 10bit file! No wonder that your player can't play it. All Blurays and DVDs only have a bit depth of 8bit and the hardware players only support it. The only exception to this rule is the new Ultra-HD-Bluray. So this is not a container/Matroska thing.
