### ISSUE TITLE
v9.3.1 on OS X (10.11.6): "Open With..." in Finder does not open file

### ISSUE THREAD

**Issue by iipamonkey** [mbunkus/mkvtoolnix#1751]
Sincere apologies if I've duplicated an issue; I searched as much as I could through open and closed issues to see if anyone else reported this, but couldn't find one.

As indicated above, when I'm browsing files in the Finder and use "Open With..." -> mkvtoolnix (latest version for Mac from fosshub), it simply opens the mkvtoolnix GUI without loading the file. Drag and drop works fine. "Open With..." on Windows works fine. Is there some limitation on OS X that prevents it from working with just this particular tool? I use other canned and compiled tools on OS X for which "Open With..." works fine.

Thanks!

**Comment by mbunkus** [comment]
I'm sorry, but I don't support Mac OS. I provide binaries, but I'm not a user of the platform, I cannot test issues, and I generally just don't know how Mac or the Finder works.
