### ISSUE TITLE
OggVP8 demuxer broken

### ISSUE THREAD

**Issue by jamrial** [mbunkus/mkvtoolnix#1754]
A couple issues make mkvtoolnix generate broken matroska files when remuxing vp8 streams stored in Ogg.
The following quotes are from the spec https://people.freedesktop.org/~slomo/ogg-vp8/ogg-vp8.pdf

> Every Ogg page has a single granule position value, which corresponds to the last complete packet in this Ogg page.

In your code, frames_since_granulepos_change increases by one per frame. This is wrong since it assumes the pts in granulepos is for the first frame in the page, and messes up pts/frame_num calculation, especially in combination with the following.

> InvCnt : Number of invisible VP8 frames since the last visible frame. A visible frame gets the special value -1 (in two’s complement).

InvCnt, while extracted correctly from granulepos in line https://github.com/mbunkus/mkvtoolnix/blob/master/src/input/r_ogm.cpp#L1561 is then handled wrong in pts/frame_num calculation two lines below that.
This means that you're subtracting 3 from pts on every visible frame (-1 in 2bit two's complement), and 0 on invisible frames.

> The BOS page might be followed by a single additional header page containing VORBISCOMMENT  metadata for that logical stream

Your code assumes the VorbisComment packet is required, when it's in fact optional. Mkvtoolnix even warns about said packet missing and wrongly reports the file as broken.

Try muxing https://people.freedesktop.org/~slomo/ogg-vp8/ogg-vp8-without-tags.ogv and https://0x0.st/a_V.ogv (this one has vorbiscomment packet). In both cases it will drop the first frame (a key frame) and also mess up frame timestamps.
I recommend you using liboggz's oggz-validator, oggz-info and oggz-dump to verify and analyze OggVP8 files. Also a current ffmpeg git snapshot, which has both a demuxer and muxer, or gstreamer.

**Comment by mbunkus** [comment]
Thanks for the report & the analysis. I'll look into it.

**Comment by mbunkus** [comment]
Interestingly the one file you've pointed out, `ogg-vp8-without-tags.ogv`, violates the spec:

```
[0 mosu@sweet-chili /ftp/pub/rip/mkv/bugs/1754_oggvp8_demuxer_broken] oggz-validate ogg-vp8-without-tags.ogv
ogg-vp8-without-tags.ogv: Error:
serialno 1460730967: Terminal header page contains non-header packet
[1 mosu@sweet-chili /ftp/pub/rip/mkv/bugs/1754_oggvp8_demuxer_broken]
```

mkvmerge doesn't care about that now; it simply muxes it and ignores that there's no comment header.

**Comment by jamrial** [comment]
Are you using liboggz 1.1.1? VP8 support wasn't added until after the latest release of liboggz. 
Try using oggz-validate from a git head compilation of liboggz from https://git.xiph.org/?p=liboggz.git, and it will report the file as valid.

```
$ oggz-info.exe ogg-vp8-without-tags.ogv
Content-Duration: 00:00:10.000

VP8: serialno 1460730967
        301 packets in 77 pages, 3.9 packets/page, 0.700% Ogg overhead
        VP8-Mapping-Version: 1.0
        Video-Framerate: 30.000 fps
        Video-Width: 320
        Video-Height: 240

$ oggz-validate.exe ogg-vp8-without-tags.ogv

$ 
```

**Comment by mbunkus** [comment]
I see. Yes, it's 1.1.1 on my end. I don't really care whether or not `oggz-validate` says the file is valid; I just thought it curious. It has no impact on mkvmerge either way.

**Comment by jamrial** [comment]
Alright. Thanks for the fix for the matter.

I'll see if i can find or make a file with actual invisible frames, either in the middle of a page or at the end (so the granulepos value corresponds to it) to test some more.

**Comment by mbunkus** [comment]
It's quite possible that invisible frames at the end of the page won't have the correct timestamp as I didn't really understand how that's supposed to be handled just from reading the spec. ffmpeg doesn't seem to take the invisible frames counter into account at all when reading VP8 in Ogg, so mkvmerge doesn't either now.

**Comment by remuxer32** [comment]
**@jamrial**

New pre-builds for Windows, that contain the fix, are available here: https://mkvtoolnix.download/windows/pre/
