### ISSUE TITLE
Clusters and keyframes during appending

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1757]
Normally mkvmerge starts new clusters so that video keyframes are at the beginning of their clusters (or at least not far away from it (think of open GOP)). But this is not true during appending: The keyframes of the first file are put into new clusters; but for all subsequent files, the keyframe criterion is ignored and new clusters are started based upon the remaining limits (by filesize, by time or by number of cluster).
This (unsurprisingly) does not happen with the "add as additional part" mode.
I uploaded the files s.mkv and "s (1).mkv" to your ftp server. The latter file has been created by appending the former one to itself. But this can actually reprocudec with any file.

**Comment by mbunkus** [comment]
Thanks. I have a pretty good idea why this is happening and will look into it.
