### ISSUE TITLE
User Interface : Chapter frame size with very long chapter names

### ISSUE THREAD

**Issue by Kid-C** [mbunkus/mkvtoolnix#1760]
Issue (user interface/cosmetic):
When selecting extremely long chapter names in the mkvtoolnix 9.3.1 chapter editor, the left-pane that displays the chapter structure auto-sizes to a very thin width. The frame width cannot be dragged/changed. 

Example chapter name (len=~350):
21 Part Two - Condemnation and Crucifixion (Verurteilung und Kreuzikung) -- 33-39 Rezitativ und Chor (Evangelist, Pilatus, Jesus, Chor): “Und die Kriegsknechte flochten eine Krone” - “Sei gegrußet, lieber Judenkönig” - “Und gaben ihm Backenstreiche” - “Kreuzige, kreuzige” - “Pilatus sprach zu ihnen” - “Wir haben ein Gesetz” - “Da Pilatus das Wort hörete”

Screen shot:
https://www.dropbox.com/s/ah7pxvzmo9kk3jv/09_mmg_notes---chapter_col_size.gif?dl=0

**Comment by mbunkus** [comment]
Heh :) Thanks for the report. I'll fix that.
