### ISSUE TITLE
MKV with DTS@192KHz muxes as DTS@48KHz

### ISSUE THREAD

**Issue by Kid-C** [mbunkus/mkvtoolnix#1762]
Initially reported on Doom9.

Issue:
When muxing an mkv file with a DTS-HD MA audio track @ 192KHZ, the resultant DTS-HD MA audio track has a sample rate @ 48KHz. v9.3.1/win10.

Other tools (viz., handbrake; ffmpeg; tsmuxer) also exhibit the problem. The problem is not in mkvtoolnix, but perhaps in some other common library used by these same tools.

I am documenting the problem here so that the information can be directed to the appropriate people.

---------------

Process:
1. Used MakeMkv 1.10.0 to rip a blu ray audio disc that contains a DTS-HD MA 5.1 audio track sampled at 192KHz. The BDA also has an "Auro-3d" audio track.
2. Used Mkvtoolnix 9.2.0 to mux. Mkvtoolnix shows the DTS-HD MA 5.1 audio track as 192KHz. (screen shot link below)
3. Used Mkvtoolnix 9.2.0 to open the muxed file. DTS-HD MA 5.1 audio track now at 48KHz. (screen shot link below)

I used unix split(1) to create a 25mb sample file. None of the other typical tools could split a sample: handbrake; ffmpeg; tsmuxer; mkvtoolnix.

Note: logs and screen shots are from 9.2.0, but problem is re-produced similarily in 9.3.1.

---------------

Work-arounds:
1. Do no additional post-processing on files created in MakeMKV. Name all chapters and audio tracks, set languages, etc.
2. Use the flac profile in MakeMKV; this will losslessly encode the audio, and subsequent muxes and extracts with MKVToolNix work fine.

---------------

sample (25mb - opens in MkvToolnix 9.3.1 as dts@192khz):
https://www.dropbox.com/s/lkmm7ddlqy972aw/DTSHD_sampling_issue_001.mkv?dl=1

pre-mux: dts 5.1@192khz
https://www.dropbox.com/s/7g24fznde9ms8m6/02%20mkvtoolnix%209.3.0%2C%20DTS-HD%20MA%20%40%20192khz.jpg?dl=0

post-mux: dts 5.1@48khz
https://www.dropbox.com/s/yfe2y01obwuxpou/04%20mkvtoolnix%209.3.0%2C%20DTS-HD%20MA%20%40%2048khz.jpg?dl=0

MakeMKV thread link:
http://www.makemkv.com/forum2/viewtopic.php?f=8&t=14739

mkvtoolnix options

```
--ui-language
en
--output
C\c\\1\\Part_II_t00_30secs.mkv
--language
0\ceng
--compression
0\cnone
--language
1\ceng
--track-name
1\cSurround\s5.1
--default-track
1\cyes
--compression
1\cnone
--language
2\ceng
--track-name
2\cSurround\s5.1
--compression
2\cnone
--language
3\cmis
--track-name
3\cSurround\s5.1
--compression
3\cnone
--language
4\cmis
--track-name
4\cSurround\s5.1
--compression
4\cnone
--language
5\cmis
--track-name
5\cSurround\s7.1
--compression
5\cnone
--language
6\cmis
--track-name
6\cSurround\s5.1
--compression
6\cnone
--language
7\cmis
--track-name
7\cStereo
--compression
7\cnone
(
C\c\\1\\Part_II_t00.mkv
)
--split
timecodes\c30s
--title
Part_II
--track-order
0\c0,0\c1,0\c2,0\c3,0\c4,0\c5,0\c6,0\c7
```

mkvtoolnix log

```
--- Output of job 'merging to file "Part_II_t00_30secs.mkv" in directory "C:/1"' started on 2016-07-13 21:41:10 ---
mkvmerge v9.3.0 ('Second Sight') 64bit
'C:\1\Part_II_t00.mkv': Using the demultiplexer for the format 'Matroska'.
'C:\1\Part_II_t00.mkv' track 0: Using the output module for the format 'AVC/h.264'.
'C:\1\Part_II_t00.mkv' track 1: Using the output module for the format 'DTS'.
'C:\1\Part_II_t00.mkv' track 2: Using the output module for the format 'DTS'.
'C:\1\Part_II_t00.mkv' track 3: Using the output module for the format 'DTS'.
'C:\1\Part_II_t00.mkv' track 4: Using the output module for the format 'DTS'.
'C:\1\Part_II_t00.mkv' track 5: Using the output module for the format 'DTS'.
'C:\1\Part_II_t00.mkv' track 6: Using the output module for the format 'DTS'.
'C:\1\Part_II_t00.mkv' track 7: Using the output module for the format 'PCM'.
The file 'C:\1\Part_II_t00_30secs-001.mkv' has been opened for writing.
The cue entries (the index) are being written...
The file 'C:\1\Part_II_t00_30secs-002.mkv' has been opened for writing.
The cue entries (the index) are being written...
Muxing took 7 minutes 45 seconds.
```

**Comment by mbunkus** [comment]
Judging from the information you've provided I'd say that MakeMKV is doing something wrong here, not the other tools. The "sample rate" header field in the Matroska container usually only contains the base sample rate, not the ones provided by extensions. This is comparable to HE-AAC where audio is stored as e.g. 24000 Hz whereas it will be 48000 Hz after decoding. For such files the corresponding Matroska header field is set to 24000, not 48000.

As for the difference in what the GUI shows between the file created by MakeMKV and the one created by mkvmerge: the GUI only reports what's currently stored in the container's header field. Therefore in the first case it reports what MakeMKV wrote.

mkvmerge on the other hand will re-derive such track parameters from the bitstream and set the sample rate to the 48000 Hz it detects in the DTS core frame.

I don't think there's a bug in mkvmerge or any of the tools you've listed here; instead MakeMKV should not write 196000 Hz in the first place.

**Comment by mbunkus** [comment]
That being said, I'll look into it some more before deciding what to do with it.

**Comment by mbunkus** [comment]
The underlying issue is that mkvmerge cannot parse XLL extensions properly yet. There has been some work on this by @KonaBlend in pull request #1629, but that work has stalled.

**Comment by Kid-C** [comment]
After I posted, I ran the BDA through MakeMkv 1.10.0 with the flac profile. I thought it would work, but it gave flac "thread emulation" errors when I checked this morning. That means it's a MakeMkv issue, as you noted above, and I've posted the relevant information for them here:

http://www.makemkv.com/forum2/viewtopic.php?f=8&t=14739

I'll post back here if the MakeMkv code gets updated and the issue is resolved - he usually releases every couple of months. Thanks for your insights about headers.

**Comment by mbunkus** [comment]
Actually I'm not entirely certain what the right thing to do here is. The situation does seem to be a bit different than the HE-AAC case. ffmpeg, for example, reports that file as 192000 Hz. On top of that mkvmerge does already use the information from extensions for the setting the number of channels. It should probably set the sample rate from the extension, too.

Changing this is rather easy, BTW. mkvmerge can already read enough from the XLL extensions to determine its sample rate.

I'll think about this some more.

**Comment by Kid-C** [comment]
MakeMkv reponded back at the link I included above. MakeMkv doesn't see this as a problem. 

He's thinking the flac rips are clean, so I'll try that route (again) , and the put it through some testing.

**Comment by Kid-C** [comment]
I checked a DTSHDMA audio track @ 192khz with mkvtoolnix 9.4.0.

The tests I conducted were clean; it works fine, as does the previous flac method I suggested.

Here are the logs from the successful mux with DTSHDMA@192khz.

https://www.dropbox.com/s/sz3nnak52y....0%29.zip?dl=1

(I realize you did a .1 and .2 release.)
