### ISSUE TITLE
Teletext subtitles not recognized

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1763]
Hello,

I know that you have already said that [you do not want to spend time on transport streams/teletext](https://github.com/mbunkus/mkvtoolnix/issues/1662#issuecomment-212573085), but for the record I have uploaded an ARD recording (00007.ts) which has German teletext on page 150 and Danish teletext on page 799 ([here](https://de-de.facebook.com/UntertitelPflicht/posts/371556589539381) is an explanation for the existence of the Danish teletext) and neither is recognized by MKVToolNix (not even if I increase the probe percentage to 99.99). 
CCExtractor detects that both pages possibly contain subtitles and by default extracts the first page for which a packet is detected; but CCExtractor lets you choose other pages to extract, too. I think that this would be a good idea for MKVToolNix, too: If you notice that a file contains teletext, you could let the user choose a list of pages to convert to subtitles. This would be especially good as teletext seems to be a neverending work in progress.

Grüße
Andi

**Comment by mbunkus** [comment]
The file you've uploaded does not contain teletext subtitles. It contains a teletext stream, that's true, but those are real teletext pages, not subtitles. Give it a try yourself: open the file in VLC and you'll see two entries in the "Subtitle" → "Sub track" menu: "DVB subtitles: hearing impaired" and "Teletext". Activate the second one and you'll see that those are real teletext pages.

The first subtitle track is "DVB subtitles", also called "VobSub" in other circles. Those aren't text subtitles, and mkvmerge can indeed not handle those at the moment. The stream type is known to mkvmerge, but it just cannot parse them; basically because I haven't ever really been interested.

**Comment by mbunkus** [comment]
Ah, switching to page 799 does indeed show Danish subtitles. Hmm… sorry, but mkvmerge won't support that.

In MPEG transport streams each stream's presence is signaled via an entry in the PMT (program map table). For your file that table contains one entry for the teletext track, for program ID 5104. Teletext tracks contain further information in the PMT about their type: if they're real teletext pages (type 1), if they're subtitles (type 2 and 5) etc. Additionally they contain language selectors with one selector for each sub-stream contained in that stream.

Your file's single teletext stream is of type 1 = real teletext pages, not subtitles. Therefore mkvmerge skips it. However, even if mkvmerge didn't skip it would still not know about the Danish sub-stream's presence as there's only a single language selector for stream 5106: "deu" = German.

Let's assume for a moment I changed mkvmerge to accept telext streams of type 1, too. That would mean that mkvmerge would suddenly offer to mux actual teletext pages for all files out there. Users would be highly annoyed by such a change, and rightfully so.

Even with such a change mkvmerge wouldn't know about the Danish sub-stream as its presence isn't indicated by the PMT at all. mkvmerge cannot accept arbitrary sub-streams not present in the PMT either: I have way too many files where such unlisted sub-streams exist and where they contain solely garbage. Again, users would be highly annoyed.

For such specialized circumstances I highly suggest you use specialized tools for pre-processing them. I won't implement support for such cases in mkvmerge.

**Comment by mbunkus** [comment]
Additional information: mkvmerge does already support multiple teletext subtitle sub-streams in different pages within the same TS stream as long as they're properly signaled via the PMT. In such a case mkvmerge will expose each signaled sub-stream as a separate track the user can select via normal track selection means.

**Comment by mkver** [comment]
So in your nomenclature a teletext page is only a teletext subtitle if it is properly exposed as a substream of type 2 or 5 in the PMT? Otherwise it's just teletext. I was not aware of that distinction. (The reasoning behind my verbiage was that it was teletext and a subtitle, so I called it a teletext subtitle.)
I can understand your motivation not to include my proposed feature. I will just use CCExtractor instead. Now I wonder how CCExtractor knows (or probably guesses) which pages contain subtitles. Probably the short and fast changing ones.
When you mentioned PID 5106, you actually meant 5104? (5106 is an audio track.)

**Comment by mbunkus** [comment]
The format of the teletext descriptor for the PMT is described in [EN 300 468: Digital Video Broadcasting (DVB)](http://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.11.01_60/en_300468v011101p.pdf) (section 6.2.43 "Teletext descriptor"). Table 94 lists the defined values with 1 being "initial teletext page", 2 "teletext subtitle page" and 5 "teletext subtitle page for hearing impaired people". So yes, only 2 and 5 are for actual subtitles, 1 is used for [regular teletext pages](https://en.wikipedia.org/wiki/Teletext#/media/File:ARDtext_100.png).

I did indeed mean PID 5104.
