### ISSUE TITLE
Adding tags on a track erases existing tags on that track.

### ISSUE THREAD

**Issue by kevinlekiller** [mbunkus/mkvtoolnix#1764]
When for example, adding tags on audio track 1 (`mkvpropedit --tags track:a1:/tmp/test.xml test.mkv`), the existing tags are replaced by the new ones.

In the [manual](https://mkvtoolnix.download/doc/mkvpropedit.html) it states `Add or replace tags in the file with the ones from filename or remove them if filename is empty.`

This is a bit vague to me, does replace mean add new tags and replace tags that are already there, or does it mean remove all existing tags and replace them with the new tags, and does add mean new tags, but don't change existing tags?

Thanks.

Steps to reproduce:

Example video: https://0x0.st/BG7.mkv
Example xml tags file 1: https://0x0.st/BGh.xml
Example xml tags file2: https://0x0.st/BGF.xml

Apply xml file 1 to mkv audio track 1: `mkvpropedit --tags track:a1:BGh.xml BG7.mkv`
Read tags on audio track 1: `ffprobe BG7.mkv`

As we can see, audio track 1 has `EXAMPLETAG : EXAMPLE`

Now we apply xml file 2 to mkv audio track 1:  `mkvpropedit --tags track:a1:BGF.xml BG7.mkv`
Read tags: `ffprobe BG7.mkv`

"EXAMPLETAG: EXAMPLE" is now gone.

**Comment by mbunkus** [comment]
It will remove the existing tags for the track specified by the selector and add the ones for that track from the file you've specified. It won't touch existing tags for other tracks.

This is how the other operations work, too, e.g. replacing chapters.

**Comment by mbunkus** [comment]
Additionally: if no tags exist for that track it will add new ones, hence the wording "add or replace": "add" if no tags exist and "replace" if they do.

**Comment by kevinlekiller** [comment]
Alright, thanks @mbunkus

**Comment by mbunkus** [comment]
You're welcome.
