### ISSUE TITLE
Corrupt MKV when remerging MKVcleaver extracted AVI

### ISSUE THREAD

**Issue by isidroco** [mbunkus/mkvtoolnix#1765]
After extracting AVI and Audio, when regenerating MKV with mkvmerge v9.3.1, resulting AVI shows image as old TVs Horizontal loose (diagonal lines), AVI alone is viewable, extracted with vdub a test.avi with first few frames with same results. Command line:
C:\DVD\MKVToolNix\mkvmerge.exe -o "f:\B\test.mkv" --forced-track 0:no -d 0 -A -S -T --no-global-tags --no-chapters = "f:\B\test.avi" --forced-track 0:no -a 0 -D -S -T --no-global-tags --no-chapters = "f:\B\test.WAV" --track-order 0:0,1:0

[test.ZIP](https://github.com/mbunkus/mkvtoolnix/files/425822/test.ZIP)

**Comment by mbunkus** [comment]
Thanks for the report. Can you please also provide the Matroska file you've extracted the AVI from in the first place? Thanks.

**Comment by isidroco** [comment]
Original is quite big, will have to generate a new test. Error happened with all those files. And seems related to final MKV height being 1088 instead of 1080.

**Comment by isidroco** [comment]
Seems a MKVleaver bug, which the author doesn't want to correct:
http://blogs.sapib.ca/apps/bugs-requests/avi-converter-wrong-picture-height/

**Comment by mbunkus** [comment]
Alright, that's good to know. So the bug isn't in MKVToolNix, and I'll close this issue again.
