### ISSUE TITLE
Build mkvtoolnix w/o GUI on Windows 

### ISSUE THREAD

**Issue by abakum** [mbunkus/mkvtoolnix#1766]
Look: https://msdn.microsoft.com/en-us/commandline/wsl/about#
Successfully build:
apt-get install ruby
apt-get install autoconf
apt-get install libboost-dev libboost-filesystem-dev libboost-regex-dev libboost-date-time-dev libboost-system-dev
apt-get install libmagic-dev
apt-get install libogg-dev
apt-get install libvorbis-dev
apt-get install libbz2-dev liblzo2-dev zlib1g-dev
apt-get install libflac-dev
apt-get install libcurl4-gnutls-dev

cd ~
git clone git://github.com/mbunkus/mkvtoolnix.git
cd mkvtoolnix
./autogen.sh
git submodule init
git submodule update
./configure --with-boost=/usr
./drake && ./drake install

root@WIN64:~# mkvmerge -V
mkvmerge v9.3.1 ('Mask Machine') 64bit

**Comment by mbunkus** [comment]
Interesting, but nothing I'm going to support.
