### ISSUE TITLE
Edit Headers, Selecting Default CC can result in 2 defaults flags

### ISSUE THREAD

**Issue by jimva** [mbunkus/mkvtoolnix#1767]
Fairly simple bug.

1. open mkv edit headers select file with multiple CC or ST. 
2. change default CC language.

The result is 2 defaults.

Edit headers does not automatically switch other "yes" default flag to "no" as it does in mkv merge.

**Comment by mbunkus** [comment]
That's correct, and I'm not quite sure whether or not I want to add such functionality. The header editor (just like mkvpropedit) is a tool that is supposed to allow the user to modify the header values in almost arbitrary ways, also to facilitate the creation of unusual files (e.g. for testing and development purposes). For example, it allows several tracks to have the same UID. The user is supposed to know what she's doing. 

I'll think about this some more, but it's likely that I won't change it.

**Comment by jimva** [comment]
Oh ok.

Thanks for the reply, and I use this almost daily great program thanks!

**Comment by mbunkus** [comment]
I've decided not to change this behavior.
