### ISSUE TITLE
error executing mkvmerge

### ISSUE THREAD

**Issue by quiricada** [mbunkus/mkvtoolnix#1769]
The JSON output generated by mkvmerge could not be parsed (parser's error message: parse error - unexpected end of input).

Version 9.3.1 "Mask Machine"
Linux dingo 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid

**Comment by mbunkus** [comment]
What exactly were you doing when that happened (my guess is: when you tried to add a file in the GUI)?

Can you please post the full output of the following commands:

```
find / -type f -name mkvmerge
ls -l /usr/bin/mkvmerge
mkvmerge --identification-format json --identify YOUR-FILE-NAME
```

Replace `YOUR-FILE-NAME` with the full path to the file you've tried to add.

Thanks.

**Comment by quiricada** [comment]
hi,
excellent program.
nothing special, in pcmanfm (lxde file manager), right click on an mkv file and open with mkvtoolnix gui, then program opens and the error dialog pops up right away.

thanksd

**Comment by mbunkus** [comment]
You've only answered my first question. That doesn't help me much. Please also provide the output of the three commands as I've asked for in my first comment. Thanks.

**Comment by quiricada** [comment]
find / -type f -name mkvmerge

"still out to lunch"
cursor isn't back yet


ls -l /usr/bin/mkvmerge
-rwxr-xr-x 1 root root 4676488 Jul 14 15:20 /usr/bin/mkvmerge



sorry for the long file name!!
mkvmerge --identification-format json --identify Butch.Cassidy.And.The.Sundance.Kid.1969.1080p.Bluray.x264.mkv
mkvmerge: symbol lookup error: mkvmerge: undefined symbol: _ZN11libmatroska14KaxVideoColour10ClassInfosE

**Comment by quiricada** [comment]
for the find (first command)

...
find: ‘/etc/ssl/private’: Permission denied
/usr/bin/mkvmerge
find: ‘/usr/share/doc/google-chrome-stable’: Permission denied
...

**Comment by mbunkus** [comment]
Thanks. That linker error should not happen. How did you install MKVToolNix? Where do the packages come from? It looks like MKVToolNix was compiled with a newer version of libMatroska than the version that's installed on your system — and that won't work, obviously.

**Comment by quiricada** [comment]
just synaptic for mkvtoolnix and mkvtoolnix-guiboth version 9.3.1-1+b1
libmatroska6v5version 1:1.4.4-dmo1

**Comment by quiricada** [comment]
sources.list
deb ftp://ftp.us.debian.org/debian/ sid contrib non-free main
deb-src ftp://ftp.us.debian.org/debian/ sid main non-free contribdeb http://download.virtualbox.org/virtualbox/debian/ jessie contrib

**Comment by mbunkus** [comment]
Those version numbers indicate that the packages are from Debian and not the ones that I provide myself. This is a packaging bug in said packages, and I don't support the official packages myself. You'll have to raise this issue on Debian's bug tracker.

**Comment by quiricada** [comment]
SOLVED!!
you mentioned libmatroska, the dmo version looked fishy, so i used synaptic to check the package force version, there's a version 1.4.5-1, so i forced it, and solved!
thanks muchd

**Comment by mbunkus** [comment]
You're welcome. However, it's still a packaging bug if MKVToolNix v9.3.1 can be installed with libMatroska v1.4.4. You should still report this to Debian.

**Comment by quiricada** [comment]
ok.
thanksd
