### ISSUE TITLE
Allow configure to use system libs for ebml and matroska

### ISSUE THREAD

**Issue by Justinzobel** [mbunkus/mkvtoolnix#1772]
--with-boost-system exists but not others.

When building in a networkless environment it isn't possible to git submodule init and git submodule update

**Comment by mbunkus** [comment]
configure only uses the included versions of the library if it cannot find system versions of both or if those are too old. it uses `pkg-config` for that. It's likely that your system versions are not recent enough - MKVToolNix often requires very new versions.
