### ISSUE TITLE
Unexpected Negative Sync Behavior on Video Tracks in VOB

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#1774]
Hello, when specifying a _negative_ value lower than or equal to -143911 ms in the `--sync` option on the video track of a VOB container, mkvmerge stops muxing at the _positive_ value of +143911 ms (02:24.032).

Example 1: `--sync` of -143911 stops muxing at +143911...

`$ mkvmerge -o offset-issue.mkv -y 0:-143911 sample.vob `
>mkvmerge v9.2.0 ('Photograph') 64bit
'sample.vob': Using the demultiplexer for the format 'MPEG program stream'.
'sample.vob' track 0: Using the output module for the format 'MPEG-1/2'.
The file 'offset-issue.mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Muxing took 2 seconds.

$ ffprobe offset-issue.mkv
>Input #0, matroska,webm, from 'offset-issue.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-08-31 18:11:18
  Duration: 00:02:24.03, start: 0.000000, bitrate: 1980 kb/s
    Stream #0:0: Video: mpeg2video, none(tv), 720x480, SAR 8:9 DAR 4:3, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      BPS             : 5372560
      BPS-eng         : 5372560
      DURATION        : 00:00:00.200000000
      DURATION-eng    : 00:00:00.200000000
      NUMBER_OF_FRAMES: 6
      NUMBER_OF_FRAMES-eng: 6
      NUMBER_OF_BYTES : 134314
      NUMBER_OF_BYTES-eng: 134314
    Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      BPS             : 256000
      BPS-eng         : 256000
      DURATION        : 00:02:24.032000000
      DURATION-eng    : 00:02:24.032000000

Example 2: `--sync` of -143910 muxes as expected (same input file)...

`$ mkvmerge -o offset-issue.mkv -y 0:-143910 sample.vob`
>mkvmerge v9.2.0 ('Photograph') 64bit
'sample.vob': Using the demultiplexer for the format 'MPEG program stream'.
'sample.vob' track 0: Using the output module for the format 'MPEG-1/2'.
The file 'offset-issue.mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Muxing took 3 minutes 55 seconds.

TESTING NOTES:

- Positive `--sync` values work on _audio and video_ tracks from VOB.
- Negative and positive `--sync` values work on _audio_ tracks from VOB.
- Negative and positive `--sync` values work on _audio and video_ from MKV.
- Only VOB input seems effected -- MKV and MP4 container inputs work fine.

Since negative and positive values work on the video track when read from MKV input, my workaround is to mux the VOB to a temporary MKV with no sync offset, then remux that temporary MKV with the negative sync desired to a final MKV.  (I came across this behavior when attempting an offset of -165000 (2m45s00ms) directly from a VOB source.)

Thank you all the time and effort you put into all your software, I value and respect it.

**Comment by mbunkus** [comment]
Thanks for the detailed report. I can reproduce such behavior here with a VOB from a random DVD. I'll look into it.

**Comment by mbunkus** [comment]
I've just fixed this in e06d80f70b564ef130de8eee53f551b80d91da31.

**Comment by optimiz** [comment]
Thank you.  The process and data flow you describe in the patch commit notes was very informative.
