### ISSUE TITLE
Incorrect chapter name for the first chapter when appening video files (v9.4.0)

### ISSUE THREAD

**Issue by damocles-git** [mbunkus/mkvtoolnix#1777]
Hi,

I am trying to append several files but I finish getting an extraneous sequence of chapter names

<pre>
$ mkvmerge --generate-chapters when-appending  \[ 1.mkv 2.mkv 3.mkv \] -o a.mkv
mkvmerge v9.4.0 ('Knurl') 64bit
'1.mkv': Using the demultiplexer for the format 'Matroska'.
'2.mkv': Using the demultiplexer for the format 'Matroska'.
'3.mkv': Using the demultiplexer for the format 'Matroska'.
'1.mkv' track 0: Using the output module for the format 'AVC/h.264'.
'1.mkv' track 1: Using the output module for the format 'AC-3'.
'2.mkv' track 0: Using the output module for the format 'AVC/h.264'.
'2.mkv' track 1: Using the output module for the format 'AC-3'.
'3.mkv' track 0: Using the output module for the format 'AVC/h.264'.
'3.mkv' track 1: Using the output module for the format 'AC-3'.
No append mapping was given for the file no. 1 ('2.mkv'). A default mapping of 1:0:0:0,1:1:0:1 will be used instead. Please keep that in mind if mkvmerge aborts with an error message regarding invalid '--append-to' options.
No append mapping was given for the file no. 2 ('3.mkv'). A default mapping of 2:0:1:0,2:1:1:1 will be used instead. Please keep that in mind if mkvmerge aborts with an error message regarding invalid '--append-to' options.
Using the track with the ID 0 from the file '1.mkv' as the reference for chapter generation.
The file 'a.mkv' has been opened for writing.
Appending track 0 from file no. 1 ('2.mkv') to track 0 from file no. 0 ('1.mkv').
Appending track 1 from file no. 1 ('2.mkv') to track 1 from file no. 0 ('1.mkv').
Appending track 0 from file no. 2 ('3.mkv') to track 0 from file no. 1 ('2.mkv').
Appending track 1 from file no. 2 ('3.mkv') to track 1 from file no. 1 ('2.mkv').
Progress: 100%
The cue entries (the index) are being written...
Muxing took 1 second.
</pre>

now the output file has a first chapter repeated with a chapter name out of the sequence (Chapter 1, Chapter 01, Chapter 02, Chapter 03):

```
$ mkvextract chapters a.mkv                                                                                              ﻿
<?xml version="1.0"?>
<!-- <!DOCTYPE Chapters SYSTEM "matroskachapters.dtd"> -->
<Chapters>
  <EditionEntry>
    <EditionFlagDefault>1</EditionFlagDefault>
    <EditionFlagHidden>0</EditionFlagHidden>
    <EditionUID>5168704202739204323</EditionUID>
    <ChapterAtom>
      <ChapterUID>12977615496947933149</ChapterUID>
      <ChapterTimeStart>00:00:00.000000000</ChapterTimeStart>
      <ChapterTimeEnd>00:03:23.360000000</ChapterTimeEnd>
      <ChapterFlagHidden>0</ChapterFlagHidden>
      <ChapterFlagEnabled>1</ChapterFlagEnabled>
      <ChapterDisplay>
        <ChapterString>Chapter 1</ChapterString>
        <ChapterLanguage>und</ChapterLanguage>
      </ChapterDisplay>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterUID>4580086024253532689</ChapterUID>
      <ChapterTimeStart>00:00:00.000000000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Chapter 01</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
      <ChapterFlagHidden>0</ChapterFlagHidden>
      <ChapterFlagEnabled>1</ChapterFlagEnabled>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterUID>16156650568925760313</ChapterUID>
      <ChapterTimeStart>00:03:23.424000000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Chapter 02</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
      <ChapterFlagHidden>0</ChapterFlagHidden>
      <ChapterFlagEnabled>1</ChapterFlagEnabled>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterUID>6395527282933742412</ChapterUID>
      <ChapterTimeStart>00:06:59.520000000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Chapter 03</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
      <ChapterFlagHidden>0</ChapterFlagHidden>
      <ChapterFlagEnabled>1</ChapterFlagEnabled>
    </ChapterAtom>
  </EditionEntry>
</Chapters>
```

is it a bug or I am missing something?

**Comment by mbunkus** [comment]
mkvmerge's default naming scheme for chapters is "Chapter %02d",meaning that the chapter numbers are two digits long and left padded with 0 if they're below 10. I suspect that one of the source files contains chapters and that the entry "Chapter 1" (the one without the leading 0) originates from those.

**Comment by mbunkus** [comment]
To clarify: please verify whether or not the three input files contains chapters. I highly doubt what you're seeing is actually a bug.

**Comment by damocles-git** [comment]
Unfortunatelly I deleted the original files.

Now I created them again with Handbrake and the output file is correct. I should have done something wrong. Thank you.

**Comment by mbunkus** [comment]
Alright. Thanks for the feedback.
