### ISSUE TITLE
Suggestion: Consolidate cues

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1779]
Hello,

since version 5.9 mkvmerge writes cues for subtitles by default. I just noticed (using a srt-subtitle with information for the hearing impaired and a srt-subtitle from which the information for the hearing impaired has been removed) that the cues take more bytes than needed because some elements are unnecessarily duplicated:
`+ Indexmarke an 5763241430
|  + Indexzeitstempel: 21.371s an 5763241432
|  + Indexspurpositionen an 5763241436
|   + Indexspurnummer: 3 an 5763241438
|   + Index-Cluster-Position: 24578622 an 5763241441
|   + Indexelement »relative Position«: 175436 an 5763241447
|   + Indexelement »Dauer«: 00:00:02.152000000 an 5763241452
| + Indexmarke an 5763241456
|  + Indexzeitstempel: 21.371s an 5763241458
|  + Indexspurpositionen an 5763241462
|   + Indexspurnummer: 4 an 5763241464
|   + Index-Cluster-Position: 24578622 an 5763241467
|   + Indexelement »relative Position«: 175397 an 5763241473
|   + Indexelement »Dauer«: 00:00:02.152000000 an 5763241478`
According to [your specification](https://lists.matroska.org/pipermail/matroska-devel/2012-September/004291.html) it is possible to add multiple CueTrackPositions entries (one for each track) which should save six bytes in the above example.

Grüße
Andi

**Comment by mbunkus** [comment]
True, but I think I remember having actually tried that and having hit problems with certain players. The gain was so minimal that I didn't think it worth while, and that view hasn't really changed. I won't implement this. Sorry.
