### ISSUE TITLE
S24 added to DTS audio tracks label

### ISSUE THREAD

**Issue by whitesnakeftw** [mbunkus/mkvtoolnix#1784]
I apologize in case this was intentional and so not an issue, or if not directly related with mkvmerge.

Since release 9.2.0 (9.1.0 doesn't have this problem) when muxing files with a DTS track in them, in Windows explorer (with Icaros Property Handler) I get for example "DTS **S24** 5.1 [Eng]" instead of "DTS 5.1 [Eng]" as seen in the screenshot below.

![dts](https://cloud.githubusercontent.com/assets/9657324/18555441/25fb7b9c-7b68-11e6-99c7-050149eae210.jpg)

I can of course provide a sample if need be. Thanks for your time.

**Comment by mkver** [comment]
This is a consequence of the change relating to issue #1680. I don't see a problem here.

**Comment by mbunkus** [comment]
Indeed. This is not a bug.

**Comment by whitesnakeftw** [comment]
Thanks for the explanation, have a good one.

And thanks for this great piece of software.
