### ISSUE TITLE
Cannot see fonts when adding to attachments

### ISSUE THREAD

**Issue by ChronoSX007** [mbunkus/mkvtoolnix#1785]
Currently using MKVToolNix GUI v9.4.2 ("So High") 64bit
My OS: Windows 7 (64bit)

I have just updated my old MKVToolNix (the one with the old GUI) up to the latest version and during dragging of fonts in the attachments tab i don't see the fonts but its definitely present because after muxing my video i dragged the video file in the input tab then switched to attachments tab the fonts are now visible. 

is this a bug? or I'm i doing something wrong cuz I'm still adapting to the new GUI.

**Comment by mbunkus** [comment]
On the "attachments" tab there are two lists. The upper one contains attachments that are already present in source files you've added on the "input" tab. The lower list contains attachments that you want to add. Therefore files you're dragging & dropping onto the "attachments" tab will show up in the lower of the two lists.
