### ISSUE TITLE
Feature Request: Ability to Change/Edit IDs

### ISSUE THREAD

**Issue by TwistedFaith84** [mbunkus/mkvtoolnix#1786]
I'm hoping that this is actually possible but the ability to change/edit the IDs # would be a good help to reduce the number of errors the program gets when adding new subs, audio, and/or videos. I run in to this problem just about every other time I use the mkvtoolnix. After I add new subs or audio when there is already subs or audio in the container file it  make those newly added items as ID 0, or 1 (ect) and then I wind up with errors and sometimes the newly added items dont even work when I play the mkv in a player.

**Comment by mbunkus** [comment]
I honestly don't understand which IDs you mean. Can you elaborate? Show some examples?

**Comment by TwistedFaith84** [comment]
I'm trying to upload a jpg and its not working.

**Comment by TwistedFaith84** [comment]
But when you add a video file to mkvtoolnix in the bottom window where the Tracks, Chapters, and Tags show up it list IDs (you may have to scroll that window to the right if you can't see then). Well if there are already Subs or Audio (a course there is Audio) in the file that you want to mux and you add Subs or Audio the IDs for your newly added items start back at 0 and count up from there (not sure if its per item or per item type (ie subs, audio, or video)). Well when that happens it cause MKVToolnix to read alot of errors (and most times (for me anyways) those added items dont work when I go to activate them on my video player.

**Comment by mkver** [comment]
1. The ids that you see in the list you're mentioning are the ids of this tracks in their respective input files. So if you have more than one input file, you usually have more than one track with id 0 in this list (there are exceptions -- the ids in transport streams usually don't start at zero).
2. The ids of your track in your output file are not determined by the ids in your input file. They are determined by the listing of the respective track in the list: The first (from the top) item in the list that you select to mux will get the lowest id and will be the first track and so on.
3. What errors are you talking about? What player has problems playing these files? Are you using the most recent version of MKVToolNix? What files were you trying to remux (you might want to upload them to Moritz' ftp server)? Can you give the command-line of your job? (When using the GUI you can see the underlying command line by clicking on "Merge" and then on "Show command line".)

**Comment by mbunkus** [comment]
As @mkver has explained those IDs are the ones that the GUI and mkvmerge use to communicate which track to modify. It's perfectly fine that different files use the same ID for tracks as the IDs are only file-specific and not global. See [the documentation](https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.track_ids) for more details.

Therefore "let the user edit/change the IDs" doesn't really make sense.

I'm going to close this issue as it's way too vague and based on a thorough misunderstanding of how MKVToolNix works. If you have a concrete case of where your TV doesn't play a file then that might be an issue in MKVToolNix, though in 99% of all cases it isn't; it's usually a bug or missing feature in the Matroska implementation of the TV in question. See [this article](https://github.com/mbunkus/mkvtoolnix/wiki/Improving-playback-compatibility-with-players) for several settings to be applied during muxing that possibly affect whether or not hardware devices can read a file.
