### ISSUE TITLE
Remove Muxer and Writer Fields

### ISSUE THREAD

**Issue by zx2c4** [mbunkus/mkvtoolnix#1788]
```c++
DEFINE_MKX_UNISTRING(KaxMuxingApp, 0x4D80, 2, KaxInfo, "MuxingApp");
DEFINE_MKX_UNISTRING(KaxWritingApp, 0x5741, 2, KaxInfo, "WritingApp");
```

`mkvpropedit` does not currently give a way (that I'm aware of) of removing or modifying these fields. I'd like to remove them. What is the best solution for this?

**Comment by mbunkus** [comment]
At the moment neither mkvmerge nor mkvpropedit offer functionality for that. I don't have plans on adding that either, but I'd be open to patches.

**Comment by zx2c4** [comment]
40 minutes later I've added support for this to mkvpropedit. It appears to work well.

**Comment by mbunkus** [comment]
Note that both elements are mandatory according to the Matroska specs. Therefore removing them completely is out of the question. Neither mkvpropedit nor the GUI's header editor will allow you to remove them, but you can set them empty.

For similar reasons I won't implement options for modifying those elements in mkvmerge after all.

I haven't merged your pull request but used your diff as the basis for my implementation (I wanted slightly different element names and a slightly more verbose description). Thanks for the pull request anyway.
