### ISSUE TITLE
Language elements not present after muxing

### ISSUE THREAD

**Issue by mkvGuy** [mbunkus/mkvtoolnix#1792]
After muxing a file, Language file

elements not present after muxing.  Without these fields, programs like wincatalog have problems indexing the files properly.  Please fix. See screenshot.  I setup a .bat file to make sure those fields are set post muxing. but it would be nice to have them set during muxing, even if they don't exist in the original file.

![screenshot](https://cloud.githubusercontent.com/assets/13073022/19022338/c77aee90-889b-11e6-8a5b-738bd9e06dd9.jpg)

Also please look into trimming.  No matter how accurate I set the splitting fields it never crops more accurate the +- about a second

Thanx

PS Truly great work,

**Comment by mbunkus** [comment]
This is not a bug in mkvmerge. Matroska has default values for certain elements. If an element is not present in the file then its default value comes into play. A conforming Matroska reader must use that default value in such a case. If it doesn't then it's a bug in that reading application.

[This FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/Elements-not-showing-up-in-output-file) explains this in greater detail.

Note that including all elements in the output file (even those set to their default values) also triggers bugs in players and is therefore not a workaround I'm willing to implement. It only shifts the problem.

**Comment by mbunkus** [comment]
About splitting: mkvmerge can only split on key frames; for anything else it would have to include decoders & encoders for all known video codecs — again nothing that I'm willing to do. That's why you're seeing the actual split point being off from what you specify.

**Comment by mkvGuy** [comment]
The file shown in the screenshot was muxed using MKVToolnix, with the default values set to eng.  Yet after muxing and reopening the file in MKVToolsnix header editor, it shows the language field not present.

Please fix

**Comment by mbunkus** [comment]
You don't seem to understand what I mean. If the language field isn't present in the file then a regular player that wants to interpret the language must use "eng". Therefore mkvmerge not writing that field is perfectly OK and compliant with the specs.

The GUI's header editor, on the other hand, is not a "regular player". Instead it is supposed to present the user with an accurate view of which elements are present in the file and which are not.

And "language element not present" simply means "the language English is in effect".

Again, this is not a bug. There is nothing to fix.

**Comment by mkvGuy** [comment]
So when I remux a file using MKVToolnix and set the language fields to Eng, MKVToolnix won't create the fields in the final file, and set them to Eng?

**Comment by mkvGuy** [comment]
Thanx.  Keep up the great work.
