### ISSUE TITLE
Problem with UTF-8 .srt subs

### ISSUE THREAD

**Issue by Slava46** [mbunkus/mkvtoolnix#1793]
If subs .srt have encoding UTF-8 (without BOM) and have UTF-8 symbols, when muxing it to .mkv with MKVToolNix, subs in final .mkv file will be corrupted.
But if .srt file of subs with UTF-8 symbols was in encoding just UTF-8 all will be OK.
It is on some last version (don't know about older). Now I'm using last 9.4.2.

**Comment by mbunkus** [comment]
mkvmerge assumes that text subtitles that don't have a BOM use the same character set as the system. For Windows this is never UTF-8 but something else, e.g. CP1250 on a German Windows.

Therefore you simply have to select the correct encoding in the GUI.
