### ISSUE TITLE
Feature Request: Add option to remove languages from the list

### ISSUE THREAD

**Issue by Marc66** [mbunkus/mkvtoolnix#1796]
I love MKVtoolnix but there one thing which bugs me: when I set the language for tracks, I have my 2 favourite languages (EN, FR) but on my Mac, the interface shows me the entire list of languages and of course my favourites are way at the top.

The list is very exhaustive and I am sure everyone can find the languages he is looking for but I am also sure many are like me and never use 80% of the languages listed there. 
I searched various files and config files to see if I could manually edit that list and it seems to be part of the binaries, so no luck to remove those additional languages I never use.

Would it be possible to have an option to select which languages actually appear in the selection list?

Thank you

**Comment by mbunkus** [comment]
Thanks for the suggestion. I can definitely see its use.

The problem with it is that it'd take a huge amount of work to implement. Why? At the moment all language selections in the program use the same list of languages that's generated exactly once. They're filled only when the GUI starts up or when the GUI's language is changed.

Now If I implemented an option to hide most of those entries I'd have the problem of what to do with scenarios where an existing language must be selected that normally isn't supposed to be displayed. For example when you open an existing file in the header editor and visit the track language element then that combo box must include not only your favorite languages but also the one the track's language is currently set to.

This gets even trickier in the merge tool where you can select multiple tracks at once. In such a situation all of the currently set languages must be included, too.

That's a lot of functionality to implement and test, a lot of time I'm not too eager to spend. I'm not really dismissing it yet, but I'm leaning towards "won't fix".

**Comment by mbunkus** [comment]
Additionally when the language combo box is in the middle of nowhere you can easily jump to the top by pressing your home key.

Note that the "popular languages" are actually included twice in the list: once at the top and once where they sort alphabetically.

**Comment by Marc66** [comment]
Thank your for your reply. Unfortunately, I don't have a Home key on my Mac wireless keyboard, so I'll have to live with this "feature". Too bad... in the previous GUI version (up to 7.9.0), I didn't have this issue.

**Comment by mbunkus** [comment]
The previous GUI used a different GUI toolkit library. I don't have much influence over how keyboard handling of combo boxes is done (neither did I have that with the old GUI toolkit where large combo boxes were mostly unusable on Linux, for example).

**Comment by mbunkus** [comment]
Something else you can try:

- Open the language combo box
- Press "a"

If you're somewhere in the middle of the whole list then this just focus on the first entry starting with "a" (at least it does so on Mavericks). This'll be near the top of the whole list.

Or just press "e" and jump to the first entry starting with "e"; from there it shouldn't take too long to find "English".

**Comment by mbunkus** [comment]
I've implemented this feature. I will create a pre-build MacOS disk image for you to test within the next couple of days.

**Comment by mbunkus** [comment]
You can get a pre-build DMG for MacOS [here](https://mkvtoolnix.download/macos/pre/).

**Comment by Marc66** [comment]
Excellent!!
It works like a charm and I like the approach with the tick box: simple and efficient. In fact, it is much easier to manage than having multiple preference screens

**Comment by mbunkus** [comment]
Thanks for the feedback. Glad you like it.
