### ISSUE TITLE
State at 100% Indicated Completion.

### ISSUE THREAD

**Issue by DaveCheltenham** [mbunkus/mkvtoolnix#1798]
Not a problem as such but RAM memory is used (as available) and before the new .mkv file is fully written, 100% completion is indicated although job is still running. There may be no way round this? Still a great program.

**Comment by mbunkus** [comment]
This is not the usual way things work; it's almost certainly due to the file in question. If you want me to investigate then I need access to the source file(s). Please upload them to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server).

**Comment by DaveCheltenham** [comment]
Thanks for the quick reply. I agree that it doesn’t always happen and have tracked it down to a source file which is on a from an .iso. This is usually a backup a decrypted blu-ray disc which can be watched from my NAS round the house. Others that have been edited with PowerDirector act normally. Another clue is that the resulting .mkv does not always play although the original did. All this confirms your assertion that it is down to the file in question. Because the files are big (8GB) I will do some more research and report back.

 

It is not a great problem but the read process when it happens is into ram memory but on the start of write, 100% is indicated together job running.

 

Thanks again for a great program.

 

Regards David Bennoson

  _____  

 



 <http://en.wikipedia.org/wiki/Pittville_Pump_Room> The Pittville Pump Room was the last and largest of the spa buildings to be built in Cheltenham.


>> from Cheltenham, UK<<


 <mailto:David@Bennoson.me.uk> David@Bennoson.me.uk

**Comment by DaveCheltenham** [comment]
This seems very file specific and as it happens very infrequently so suggest the phenomenon should be noted and I will close the issue.

Regards and thanks again - DaveCheltenham

**Comment by mbunkus** [comment]
Alright. Thanks for the feedback.

**Comment by techguymaxc** [comment]
I have the same issue with a file, also a Blu-ray ripped to ISO.  It's a 42GB file though, uploading is not feasible.  Have cleaned the disc and re-ripped it, same issue.  Progress indicates 100%, status says "running".  I have a rather large Blu-ray library (600+ discs) and am about 75% through ripping them, every once in awhile I get a file like this.  I have 2 others in my stack waiting to be muxed with similar issues where they get to a certain percentage and never progress from there nor error out.

**Comment by mbunkus** [comment]
Unless you're also using the chapter generation feature you're hitting a totally different issue. Most likely it's the already-fixed #1801.

Generally please don't just post in other people's bug reports unless you're 100% certain it's the same issue. It's preferable to open new reports and let the developers decide whether or not it's a new issue. Thanks.

**Comment by techguymaxc** [comment]
I have run the latest debug build and it has resolved the issue.  Thank you for your efforts.  I apologize for posting in the wrong issue report thread, though in my defense the original poster's report makes no mention of the use of a the chapter generation tool, thus his symptoms appeared to align with mine completely.  

Thank you again for your efforts.

**Comment by DaveCheltenham** [comment]
I can also report my problem (#1798) has been fixed with mkvtoolnix-64bit-9.5.0-build20161112-01323-d5f2e8e-setup. Thank you again.

**Comment by mbunkus** [comment]
Meh, I mixed up this and another issue when complaining about not posting in unrelated bug reports. Sorry for that.
