### ISSUE TITLE
MKVToolNix GUI v9.5.0 - High-DPI scaling issue.

### ISSUE THREAD

**Issue by ProTofik** [mbunkus/mkvtoolnix#1799]
Hello,
To begin with, this is my setup:
-Windows 10 v1607
-1x UltraHD monitor with 200% scaling
-1x 19" 1280x1024 monitor with 100% scaling

On my UHD monitor, MKVToolNix looks perfect, but it does not resize itself properly when being moved to my 100% scaled monitor. It appears that only fonts are being scaled down, but the rest of the interface reminds at 200%.

On 200%:
![200precent](https://cloud.githubusercontent.com/assets/11578396/19812581/10b682d0-9d2e-11e6-9324-f6654a5f4f4d.png)

Same windows dragged to 100% monitor:
![100 percent](https://cloud.githubusercontent.com/assets/11578396/19812582/10b7008e-9d2e-11e6-924c-33c30c4a1238.png)

Hope this is something you guys can look into.

**Comment by mbunkus** [comment]
Unfortunately this is handled completely by the GUI toolkit, Qt. I have no control over this. Such issues may or may not be resolved whenever I update Qt, but don't bet on it. Sorry.

**Comment by vidarak** [comment]
Possible workaround:
![2016-10-28 19_21_22-mkvtoolnix](https://cloud.githubusercontent.com/assets/4713602/19815569/d121f0c6-9d43-11e6-94ce-f18c28831f0a.png)

**Comment by mbunkus** [comment]
I've created [new pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that link use a newer version of Qt (5.7.0 instead of 5.5.1). Maybe they'll fix this DPI issue.
