### ISSUE TITLE
MKVtoolnix get stuck at muxing Blu-ray playlists

### ISSUE THREAD

**Issue by Murksmux** [mbunkus/mkvtoolnix#1801]
I've tried it a several times now and it always gets stuck at muxing.
The same movie stopps muxing at the same percentage. I've tried different movies.
Nothing happens. 
Two day ago it worked without Problems. I dont know what happened.

There are no errors. It just stops working, but it seems as if its still muxing, but it doesnt.

What could be the problem? Any ideas? I already reinstalled it. Same problem.

Thanks!

**Comment by mbunkus** [comment]
Are you trying to append files? Does this happen with all sources or just with one special source?

**Comment by Murksmux** [comment]
I'm trying to mux my Blurays by adding a playlist file. It happens with all Blus now. I dont know what has changed. Some day ago it worked without any problems....

**Comment by mbunkus** [comment]
This sounds like a known issue in versions 9.4.2 and 9.5.0 that I've fixed over the weekend. You can give the [latest debug builds](https://mkvtoolnix.download/windows/debug/) a try.

**Comment by Murksmux** [comment]
Thank you so much! It seems to work now!

**Comment by mbunkus** [comment]
Great. Thanks for the feedback.

**Comment by remuxer32** [comment]
Fixed in 3cd1618.
