### ISSUE TITLE
GUI does not start

### ISSUE THREAD

**Issue by eba869** [mbunkus/mkvtoolnix#1805]
Hi, mkvtoolnix-gui does not start at all. I have read through a previous issue and ensured that the folder is not a 'read-only' folder. It still does not start. Can you help, please?
Many thanks!

**Comment by mkver** [comment]
You should give more information if you want help on this issue: What is your OS? What version of MKVToolNix do you use? You aren't mixing different versions, are you? Did older versions work for you? (I mean a version older than the current one, but still new enough to include the GUI based on qt; everything after version 8.0 includes the new GUI if I'm not mistaken.)

**Comment by mbunkus** [comment]
First of all make sure that it's not your Anti Virus program that's preventing the execution. I've had several reports over the last couple of weeks of people who haven't been able to run one of my programs because their AV solution wrongly identified my programs as malicious. After whitelisting `mkvtoolnix-gui.exe` and `mkvmerge.exe` things magically started working again.

**Comment by eba869** [comment]
Hi,

Sorry to take so long to thank you for your reply and to provide more info. I have been fishing around trying to solve this to no avail. However, I have seen to that the program is allowed on my machine and I run Windows 10.


Initially the version of MKVToolNix I had was working fine and the day after it did not. So I uninstalled it and installed the latest version 9.5.0 from the website. That did not help. Actually - I have uninstalled and reinstalled twice, last time was today. I ensured everything was gone before I reinstalled. But still - it does not open.


I checked Windows updates too in case something changed the accessablity there but there was no update after 30/10 at the time so that is not the issue either.


So, what else can I do?


Thank you for helping me.


Eva


________________________________

**Comment by mbunkus** [comment]
Alright. Please follow the steps laid out in [this FAQ entry](/mbunkus/mkvtoolnix/wiki/Debugging-GUI-startup-problems). Thanks.

**Comment by eba869** [comment]
Hi, so I have one file that was created. How do I get it to you? I tried server as stated in the FAQ but it just says 'This site can't be reached'. 

Thanks

Eva

**Comment by mbunkus** [comment]
You can send me the file via email to moritz@bunkus.org

**Comment by mbunkus** [comment]
Thanks for the log file.

1. First please make sure that no other process named `mkvtoolnix-gui.exe` is running (via the task manager → "details" tab).
2. Now  make sure that the following directory actually exists: `C:\Users\eba86\AppData\Local\Temp`.
3. Next make sure that the directory is owned by the user `eba86` and that the user `eba86` has full access (especially write permission) to that directory.
4. If there's a file called `MKVToolNix-GUI-Instance-Communicator.lock` Inside that directory, remove it.
5. Start `DebugView.exe` again and set up logging to a file just like before.
6. Now try to start the GUI again (the debug build, please). If it comes up then one of the steps before has solved your issue. If not send me the file created in step 5.

**Comment by eba869** [comment]
Hi again,

1. Done

2. It dies

3. Not sure about this one. For some reason there are "EVA" and "eba869@hotmail.com" :

[cid:dd63b771-65d8-4b64-b358-41dc6ae95d7b]

Does this screen tell you anything useful?
4. Nope, I cannot find a file with that name.
5. Sending the log file but since I didn't do any changes......

Thank you again [😊]

Eva
________________________________

**Comment by mbunkus** [comment]
Github doesn't show the screenshot you seem to have sent, therefore I cannot comment. Please drag & drop the screenshot into the web GUI to upload it properly.

I'm almost certain that the permissions on the folder are wrong. What's the user name you're using to log into Windows?

**Comment by mbunkus** [comment]
eba869 wrote via email:

> So I contacted Microsoft to see if they could check permissions but
> mainly tell me why I have two usernames. Anyway, the permissions are
> now sorted out but MKVToolNix still doesn't work. Anymore ideas of
> what I can do?

**Comment by mbunkus** [comment]
Well, you can follow the procedure with DebugView I've outlined above once more, but my guess is that the GUI can still not write into your temporary directory due to wrong permissions. MKVToolNix isn't the only program that requires the temp directory to be present and writable.

**Comment by eba869** [comment]
Well, the same version of MKVToolNix worked perfectly with the same permissions before so something else has changed but I lack the knowledge to figure out what.

**Comment by mbunkus** [comment]
Alright, please follow these steps:

1. Make sure no instance of MKVToolNix GUI is running by either looking at the task manager or by simply rebooting.
2. Download and install the new [debug build](https://mkvtoolnix.download/windows/debug/) I've just uploaded.
3. Go do `C:\Users\<yourUsername>\AppData\Local\Temp` and remove any file whose name starts with `MKVToolNix`.
4. Start DebugView.
5. Try starting the new debug build you've just installed.
6. Send me the output generated in DebugView if the GUI doesn't come up.

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
