### ISSUE TITLE
mkvtoolnix GUI feature request: subtitles, auto-detect language by file path

### ISSUE THREAD

**Issue by pkar70** [mbunkus/mkvtoolnix#1808]
When I add SRT file to "source files", it is added as "language: undetermined".
But frequently files has names as "filename.en.srt", "filename.english.srt" - so language could easily be determined.

Also sometimes subtitles are in separate folder tree, with "english", "heairing impaired", etc., somewhere in path.
So, it is possible to add whole tree of folders with SRT _and_ autodetect all languages.

**Comment by mkver** [comment]
Moritz has considered and rejected it. [Here](https://github.com/mbunkus/mkvtoolnix/wiki/Detecting-track-language-from-filename) is his rationale.

**Comment by mbunkus** [comment]
Like @mkver has said I have no plans for implementing such a feature.
