### ISSUE TITLE
mkvtoolnix GUI feature request: source files / tracks list crossselect

### ISSUE THREAD

**Issue by pkar70** [mbunkus/mkvtoolnix#1809]
When I add several files to "source files", all tracks are recognized and added to "tracks".
But I don't know which track is from which file.

Maybe, but this is radical change, make "source files" and "tracks" same tree control, with tracks inside file node?
As:

```
[-] filename.mkv
   | - video
   |- audio
   |- chapters
   |- subtitle 1
[-] filename.srt
   |- subtitle 2
...
```

Or, at least, some way of cross-reference between source files and tracks.
E.g., when file is selected, select also all tracks from this file. And when track is selected, select file with this track. It should be very simple to implement (but I don't know about portability of such change).

**Comment by mbunkus** [comment]
The reason why there are two controls and not just one is that you can change the order of tracks regarding appended files rather freely. It would simply not map well to a combined file/track tree structure.

Additionally there is already a way to identify which file a track comes from: the `source file` column in thee track list.

**Comment by pkar70** [comment]
No, there is no way to identify - there is only filename, and sometimes I
get tree of subtitles with same names:

**Comment by mbunkus** [comment]
Right. You can give the just-introduced feature "select all tracks from the currently selected source files" a try if you want by downloading the [latest pre-build for Windows](https://mkvtoolnix.download/windows/pre/). Maybe that'll help you achieve whatever it is you want to achieve.

**Comment by pkar70** [comment]
(I hope picture from previous email reaches you)
Now if I want to add subtitles, I had to add every file step by step - add
file, select track (track window, subtitle with UND as language), change
language, add file, select track, change language...
I can add folder "subtitles", and all files under it is added to "source
files", and all tracks from these files to "tracks", but as every subtitle
file has same name, I'm unable to determine which track (subtitle) is from
which file, so I cannot properly determine language.

**Comment by mbunkus** [comment]
No, when you reply via email then pictures won't show up in Github and therefore not reach me.

Anyway, you can drag & drop folders onto the GUI (e.g. from Windows Explorer) and the GUI will add files recursively.

**Comment by mbunkus** [comment]
BTW, there's a rather easy fix that you can implement yourself: don't use identical file names. It's not what you want, but I don't want to spend time on this either. Sorry.

**Comment by pkar70** [comment]
This is picture :)
File is simple torrent, of course.

![mkvtoolnik-tree](https://cloud.githubusercontent.com/assets/23451507/20268141/255d92d4-aa7e-11e6-988c-0b5193c0d495.jpg)
