### ISSUE TITLE
Aspect Ratio/Playback on Opp

### ISSUE THREAD

**Issue by Krawk** [mbunkus/mkvtoolnix#1811]
Hoping I don't have a dead cause here, it's a very odd issue and I suspect it is with the header itself in the media file and am hoping there is a way to simply touch the header with updated info.
Situation: Some User Created Media file is not recognized on Oppo 103D BD Player.
After ripping some dvds with MakeMKV and re-encoding them to H264 with Handbrake, sometimes the Oppo 103D will not recognize the media as valid.
Best I can tell this happens more often when the aspect ratio is not stored correctly and then I have to use MKVToolnix to set the display width to 853. Media file header seems to look identical to all other media, Windows plays it just fine. I do not necessarily blame makemkv or as I suspect the affected discs contain the AR info in an IFO file rather than the data stream itself.
If you pass the MPEG2 source file into handbrake it either says 4:3 (1.33) or 16:9 - Where is this specific data retrieved from and how do we change it?
Does someone know more about how the Oppo is reading the MKV format and what it might be complaining about? If I select the media file in the Oppo it won't even list the resolution of the file like it normally does, so what is it not seeing?

**Comment by mkver** [comment]
1. This is a forum for reporting bugs/improvement requests/various issues with MKVToolNix. It's not a forum about Matroska in general; and it's not a forum for limitations of some hardware devices. What you have reported doesn't sound like a bug in MKVToolNix to me.
2. There are two places where the display aspect ratios are stored in a matroska-file: In the matroska-header and in the bitstream (more precisely, it is one of the VUI parameters that may be included in sequence parameter sets; see annex E of the H.264 standard for more information).
3. What was originally in your MPEG2-source is irrelevant for the question whether your Oppo player is able to play this file. (It's of course relevant if you want to make sure that your reencoded file has the correct aspect ratio.) Of course this also applies to the question where this data is retrieved from and how to change it (you can change the matroska aspect ratio of MPEG2-tracks via MKVToolNix in the same way you do it for other video tracks).
4. The matroska file format allows more than one way to describe the aspect ratio. The version with pixels seems to be the most widespread, but you can also prescribe a ratio. Maybe Handbrake uses the version with ratios and Oppo can't handle these files? (The other possible source of errors could be a mismatch between what is in the H.264 bitstream and the container AR. And maybe Handbrake's muxer does something else (not AR-related) that Oppo doesn't like and MKVToolNix changes that? (This does not necessarily mean that Handbrake's muxer are not specs-compliant.))
5. You can use e.g. mkvinfo to see the container aspect ratio of your video tracks.

**Comment by Krawk** [comment]
I appreciate the feedback.

As there is a possible header issue or is related to aspect ratio data then I am hoping it is something that can be looked at by MKVToolnix. Maybe a "repair headers" or some such feature? I see nowhere in toolnix an actual aspect ratio field.

Supposedly the Oppo fields off the strict MKV standard and if there is a variance somewhere it just chokes. Much like forced subtitles, the Oppo does not support that flag because they claim it is not part of the MKV SDK.

Mmuch like the fix to Handbrake's issue with how it numbers and store chapters. Thanks by the way for fixing that issue.

**Comment by mkver** [comment]
1. If you have selected a video track, you can set the container aspect ratio on the right; it's part of "video properties".
2. If you want to investigate this issue, you should look at the matroska header and see what MKVToolNix has changed. As already mentioned, this can be done with mkvinfo.

**Comment by mbunkus** [comment]
The file most likely doesn't need to be repaired as it isn't broken in the first place. The bug is almost certainly in Oppo's Matroska implementation. Therefore there's nothing for me to do here.

Additionally I don't cater to broken hardware implementations. There are way too many of those out there, I have access to none of them.
