### ISSUE TITLE
Mkvtoolnix GUI 9.5.0: Mux never finishes when generating chapters in fixed intervals

### ISSUE THREAD

**Issue by r0lZ** [mbunkus/mkvtoolnix#1813]
When the option to generate chapters in fixed intervals (with 10ms as interval) is selected in the Merge -> Output tab, the merge operation works fine up to 100%.  The "The cue entries (the index) are being written..." message is then written, but then nothing changes.  The "Muxing took * seconds." is never displayed, and the status bar tells that there is still 1 running job.  The job must be aborted, and the resulting MKV is not playable.
Removing the option to generate chapters in fixed intervals solves the problem.

I don't know if the problem occurs with all video files, or just with mine.

**Comment by mbunkus** [comment]
I cannot reproduce this in a couple of tests I've done here. Furthermore I haven't received other reports about it either. Therefore it's likely that it depends on the source file(s) you're multiplexing. If you want me to look into it, I need access to the file(s) in question as well as to the multiplex settings. Please upload them to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by r0lZ** [comment]
Sorry, but I can't get your FTP site to work.  I can log in, but it doesn't accept the transfer.  But you can download the requested files here:
http://download.videohelp.com/r0lZ/Bugs/test_chapters_bug.mtxcfg
http://download.videohelp.com/r0lZ/Bugs/test_chapters_bug_src.mkv
(Please let me know when you will have downloaded them.  I need to delete them.)

I've tried to process several input files, and I have always the same problem.  Mkvmerge stays blocked when (or after) it writes the cue entries.  I've therefore uploaded a relatively short MKV, that should be sufficient to reproduce the bug.

I'm using the 64-bit version of Mkvtoolnix, under Windows 7 SP1, if that matters.

**Comment by mbunkus** [comment]
I've downloaded the files. I'll get back to you later.

**Comment by mbunkus** [comment]
Well, muxing works just fine and doesn't hang indefinitely. It just takes a lot of time due to the settings you've used: one chapter every 10ms. The test video file you've uploaded is 25m03s long. Therefore mkvmerge will create `(25min * 60s/min + 3s) * 1000ms/s / 10ms/chapter = 150.300` chapters.

Writing those entries to disk is what mkvmerge is doing at the end. Due to how the underlying Matroska library works this takes quite some time. You'll just have to wait it out.

**Comment by r0lZ** [comment]
Oops, sorry!  I did not understand that "ms" means "microseconds".  For me, it was obviously "**m**inute**s**", because specifying a chapter interval in ms doesn't make much sense, since anyway the chapters will probably not be exactly at scene changes.

IMO, a simple way to specify a number of minutes is missing.  It's usually what peoples want.  OK, it is already possible to specify it with the syntax HH:MM:SS, but it's somewhat complex and since there is already the possibility to specify a number of seconds with 's', it is logical to add also a number of minutes.  So, I suggest to add the 'm' unit.  That will certainly clarify things.

Of course, the problem is solved, and you can close the bug.

**Comment by r0lZ** [comment]
Yes, I agree that "ms" should have been obvious for me.  But if it wasn't, it's probably because "m" is missing.
Thanks for considering my suggestion.  :-)
