### ISSUE TITLE
Split function - First file defective

### ISSUE THREAD

**Issue by kybos** [mbunkus/mkvtoolnix#1814]
Test file used:
http://www.sample-videos.com/index.php#sample-mkv-video
Download this sample on this page: 5 	mkv 	360x240 	Download

c:\bin>mkvmerge --version
mkvmerge v9.5.0 ('Quiet Fire') 64bit

mkvmerge t.mkv -o split.mkv --split timecodes:00:00:10.000,00:00:16.000

The first file created displays only artifacts when played, the other two are OK (cut at nearby i-frames, as expected).
ffprobe shows that there is no i-frame at the beginning of the first file.

**Comment by mbunkus** [comment]
Interesting, but this is nothing I can really fix. If the stream doesn't contain an I frame before the split point then mkvmerge cannot simply re-encode something; it doesn't contain any encoder functionality (and that's also not its purpose; it's simply not a full-blown video editor). This is simply one of the limitations of mkvmerge's approach.

**Comment by kybos** [comment]
Sorry, I now see that it was my mistake.
The original file has an i-frame at the beginning but the corresponding timestamp seems to be missing.
After splitting this file with mkvmerge, the first partial file does not have the i-frame at the beginning at all (possibly it was removed by the split function just because it's defective.
I was confused by the fact that the original file could be played without issues but the first split file could not.
Thanks for the fast reaction and sorry again for bothering you.

**Comment by mkver** [comment]
Actually, there is an I-frame at the beginning of your file and MPC-HC plays it perfectly fine here: It is invalid Matroska; the blocks at the beginning have negative timestamps which makes them invalid according to the Matroska-specification. The I-frame at the beginning is invalid, too, but MPC-HC seems to ignore that. It even gets the duration right; VLC on the other hand is something in between: It plays the stream from timecode 0:00 on, without decoding errors (i.e. the invalid blocks were not shown, but used to decode the valid blocks).
Interestingly, MKVExtract extracts the whole stream and does not care about some blocks being invalid. This is actually against the Matroska specification.
Possible solution: A switch which tells MKVMerge not to treat blocks with negative timestamps as invalid (one of these "engage"-things).

**Comment by mkver** [comment]
A few more observations: 
1. Audio packets with negative timestamps are not discarded at all. MKVMerge treats the stream as if it began at 00:00:00. This is against the specs. It also results in A/V asynchronity after remuxing.
2. If I delay the track by 3000ms (the first block is at -2280ms) the first video frames are not discarded (again against the specs), but begin at 720ms. But surprisingly all the video frames that had a non-positive timecode in the input file are marked as keyframes (and have cue entries).
