### ISSUE TITLE
Unable move last item in the list of tracks, chapters and tags of a file

### ISSUE THREAD

**Issue by vanowm** [mbunkus/mkvtoolnix#1817]
Attempting drag last item in the tracks, chapters and tags list starts selecting other items in the list instead of moving the item.
Can't confirm if it's actual last item or chapters item that can't be moved.

Windows 10
mkvtoolnix v9.6.0 x64

**Comment by mbunkus** [comment]
Several _types_ of items cannot be dragged & dropped. This is intentional as the underlying program, mkvmerge, doesn't allow re-ordering such tracks. Therefore the GUI doesn't allow that either in order not to give the user the wrong impression.

**Comment by vanowm** [comment]
Mmmmm...I'm not sure how not allowing move an item makes any sense when you can move everything else around unmovable item, essentially "emulating" moving the unmovable item.
The only time you can't "emulate" moving unmovable item is when you have two of them, like from two different files.
