### ISSUE TITLE
Feature Request: Add Absolute Path support for mkvtoolnix 

### ISSUE THREAD

**Issue by jaw20** [mbunkus/mkvtoolnix#1818]
As absolute paths are not supported by mkvtoolnix  paths that have too many characters are cut off by windows after 260 characters. This leads to situations where it is impossible to work with a file due to its name and/or location. Being able to use `\\?\` (this is used as a header for absolute path on Windows)  is the only way to use mkvmerge in situations when the files path has more than 260 characters. An example of python code being unable to run because of the path being cut short due to it not being a unicode is here : https://github.com/einstein95/crunchy-xml-decoder/issues/107 and although the error is not from mkvmerge the reason for the error is the same as mentioned above and would most likely affect mkvmerge or any other mkvtoolnix tool as well.

**Comment by mbunkus** [comment]
mkvmerge does support UNC paths:

![unc-paths](https://cloud.githubusercontent.com/assets/414282/20828040/d9908518-b875-11e6-875a-c5e8c7cbf441.png)

The paths in the example is 303 characters long (excluding the `\\?\` prefix).

**Comment by mbunkus** [comment]
I'll close this as it obviously works. If you have an example where it doesn't work, please show me, and I'll re-open the issue.
