### ISSUE TITLE
Issue splitting mkv via timecodes

### ISSUE THREAD

**Issue by possent888** [mbunkus/mkvtoolnix#1820]
Had an mkv file that needed to have the audio track removed and one from a different source added. they were out of sync by 43 seconds approx. So tried using MKVToolNix GUI (latest) to split into two files and discard the first, then add audio to the main one. Setting "After Specific Timecodes" with setting 00:00:43.0000 it was 1 sec out of sync - sound playing first. Whereas 00:00:43.10000 it was 1 sec out of sync - video playing first. I went down as far as 00:00:43.0800005 with same result.  I could never achive getting them to sync. And since I am down into nano seconds, this is possibly a bug.

**Comment by mbunkus** [comment]
mkvmerge does not contain encoders or decoders and can therefore only split on key frames. That's the inaccuracy you're seeing. It's not a bug, it's a limitation of its design.

Additionally the splitting option is not supposed to be used for fixing synchronization issues. Use the "delay (in ms)" option in the GUI (corresponding command line option: `--sync`) for the affected track instead.
