### ISSUE TITLE
Default subtitle track isn't default when played

### ISSUE THREAD

**Issue by VincentYuHK** [mbunkus/mkvtoolnix#1822]
Used mkvtoolnix-gui to merge srt eng subtitle with existing mkv and setting the new subtitle as default. The resulting mkv played with the old pgs subtitle as default although mediainfo shows the new subtitle as default. mkvtoolnix@9.6.0

**Comment by mbunkus** [comment]
That's a problem in your player, not in MKVToolNix. Nothing I can do about that.
