### ISSUE TITLE
Merging video file (mkv or mp4) and secondary audio file (aac, mp3 or m4a) little bug

### ISSUE THREAD

**Issue by Vortaka** [mbunkus/mkvtoolnix#1823]
Hi,
When I merge a video (deselecting the audio track) and an audio file (that I edited with goldwave), it leaves a "sound handler aac..." secondary audo track (that I don't want/need/use).  To fix it, I open the MKV created and save it again (name with a (1)), without changing anything...

Replicating this is very easy...  Take one video file, extract the audio.  Merge the video file, deselecting it's audio track, with the audio file you extracted!

If you need any more info, please contract me by email (since I don't check my GitHub account regularly...)

P.S.  Love the program, keep up the excellent work!

**Comment by mkver** [comment]
I don't think that the file actually has two audio tracks; the file you created probably has a name so similar that some media players (notably MPC-HC if you are using its default settings (the relevant options is Options>Playback>"Auto-load audio files")) automatically show this external track as if it were part of the file. Open your file with mkvinfo (or mediainfo) to see that it actually has only one audio track.

**Comment by Vortaka** [comment]
Thank you for the quick reply!  And, as you stated, it only has one track...  And your MPC-HC tricked worked...  Wow...  Hum...  This is awkward!  :p


So, the only reason that the dual audio is showing is because it sees an external audio file with the same name (different extension), huh?  Ahum...  Well, sorry for the trouble!  I do think you can remove this now fake bug report from the list!

Sorry for the trouble!  And thank you very much for the quick and straight to the point answer!

Happy holidays!

Vortaka

________________________________

**Comment by mkver** [comment]
Yes, you understood this correctly. And the added " (1)" made MPC-HC think the external audio file not to belong to the remuxed file.
This issue will be tagged as invalid and closed (and thereby removed from the list of active issues), it won't be deleted.

**Comment by mbunkus** [comment]
Thanks for the analysis, @mkver.
