### ISSUE TITLE
Need MKVExtract for Mac

### ISSUE THREAD

**Issue by Rycho** [mbunkus/mkvtoolnix#1827]
I love MKVToolnix!! 

**Would you kindly improve it by building a Mac version of MKVExtract (and the other Win-only tools) please?** 

Thanks in advance. Keep up the great work!

**Comment by mbunkus** [comment]
The Mac DMG contains all programs including `mkvextract`, `mkvpropedit` and `mkvinfo`. There are no Windows-only programs. However, they're command-line only applications. Therefore there is no icon for them.

Just mount the DMG and look for them somewhere in the DMG (don't remember the exact path, though).
