### ISSUE TITLE
Seg Fault in Ubuntu 14.04

### ISSUE THREAD

**Issue by RealPariah** [mbunkus/mkvtoolnix#1829]
Not sure why as I am not getting a ton of info on the reason behind it, but ever since I upgraded from the ubuntu provided version of MKVtoolnix to 9.6.0 (following the install instructions provided by Bunkus) it no longer loads.  At first I would get a System error message noting QT and seg fault.  I made sure to go install QT 5.7.0 and now I can get the MKVinfo to run via terminal, but anytime I attempt to run the gui I get no messages at all.  If I call mkvtoolnix-gui directly via command line it does answer back right away with "Segmentation fault (core dumped)", but does not provide me with any more info.  I am using xUbuntu 14.04 LTS and as I mentioned it ran before the upgrade just fine and I use it quite often.  I can provide info from the dump file I saw before the install of QT as that is bbout only thing I could get.  I thought github could accept the file, but only a screenshot.  Since it is long if you would like any of the info please let me know.

It does mention: Crashed with SIGSERV in QPlatformIntegrationFactory::create()

I did install QT 5.7.0 after seeing this.

I have attached the HookError piece as that may be handy:
![mkvtool-gui crash-error](https://cloud.githubusercontent.com/assets/925332/21195926/d5d13ae8-c203-11e6-9a61-638d2caeed90.png)

**Comment by RealPariah** [comment]
If there are any logs I can pull or other info I can provide I will be happy to do my best.  I am pretty knowledgeable, and know my way around Linux very well.

**Comment by mbunkus** [comment]
I'm sorry, but I'm not going to spend time with this. For several reasons:

1. There are several known issues with the Qt 5 version supplied with Ubuntu 14.04. See e.g. #1775.
2. My Ubuntu packages are built against the Qt version supplied with Ubuntu. Therefore manually installing another version (the 5.7.0 you've mentioned) doesn't help; most likely the opposite.
3. Both mkvinfo's GUI and MKVToolNix GUI run fine on my up-to-date Ubuntu 14.04 test installation.
4. Starting with the next release of MKVToolNix I won't support Ubuntu 14.04 anymore anyway as I've started using features of the C++14 standard that the gcc version supplied with Ubuntu 14.04 doesn't support.

BTW: That screenshot is an error message from inside apport, a program that's not part of MKVToolNix. Such an error in apport itself wouldn't help me, even if I were to investigate it.

**Comment by RealPariah** [comment]
LoL, up to you, but obviously I used the provided QT before installing anything, and it was your notes that lead me to install QT 5 as it directly states to install at least 5.2.0.  Thanks for at least replying, and even if 14.04 does not supply a c++ 14 out of the box it is Linux and you could probably install it.  Worst that would be needed is a note stating that one of the deps is to install the c++ that's needed.  

The info I provided was all I could get since MKVtoolnix would not load there were no debug logs to supply as it died before starting anything.  If there were something else that could help you I would be happy to look for it.
