### ISSUE TITLE
mkvmerge can't read TTA files with APEv2 tags

### ISSUE THREAD

**Issue by jamrial** [mbunkus/mkvtoolnix#1833]
mkvmerge seems to handle only ID3v2 tags and bails out if it finds APEv2 tags at the end of the file, reporting the bogus error "The seek table in this TTA file seems to be broken."
FFMpeg writes APEv2 tags to TTA files, as the spec mentions it's supported (http://tausoft.org/wiki/True_Audio_Codec_Format).

Sample: http://0x0.st/934.tta

**Comment by mbunkus** [comment]
That's correct. APEv2 tags aren't supported anywhere at the moment. I don't have plans for adding support for them for the time being.

**Comment by jamrial** [comment]
I have no problem with that, but i think that in the meantime mkvmerge should ignore said tags and proceed with the remuxing instead of bailing out with a bogus error.

**Comment by mbunkus** [comment]
That's what I meant by "adding support for". Patches are more than welcome.

**Comment by jamrial** [comment]
Oh, my bad. I thought you meant adding support for reading APEv2 tags.

**Comment by mbunkus** [comment]
No. mkvmerge doesn't read ID3 tags either; it just skips them. The same level of support is what I meant for APE(v2) tags.

**Comment by mbunkus** [comment]
Implemented via #1834.
