### ISSUE TITLE
Not working on Windows 10 Spanish OS Language

### ISSUE THREAD

**Issue by FerdariStudios** [mbunkus/mkvtoolnix#1836]
Error when opening file on the newer GUI of MKVtoolnix:

> The JSON output generated by mkvmerge could not be parsed (parser's error message: parse error - unexpected 'd')

It happens only in the new GUI v8.6+ and a Spanish OS Windows 10 and 10 Anniversary edition.

**Comment by mbunkus** [comment]
Please ses [this Wiki entry](https://github.com/mbunkus/mkvtoolnix/wiki/JSON-output-could-not-be-parsed).
