### ISSUE TITLE
MKVToolNix GUI: Error in input file structure is not reported as muxing error

### ISSUE THREAD

**Issue by Dark-SoniC** [mbunkus/mkvtoolnix#1842]
If you mux a mkv file that happens to have an Error in the Matroska file structure, the job finishes without warnings or errors in the status bar. The Warings and Errors output sections in the Job output Tab are also empty. 
Only in the Normal Output section of the Job Output Tab you will notice the issue. 

Please report such errors during the muxing process also in the status bar and error output log of the Job Output. Thanks a lot!

Example Output in "Normal Output" Section of the Job Output Tab:

```
c:\whatever.mkv: Error in the Matroska file structure at position 107346888. Resyncing to the next level 1 element.
The last timecode processed before the error was encountered was 00:01:45.856000000.
Resyncing successful at position 108858765.
The first cluster timecode after the resync is 00:01:46.624000000.
The cue entries (the index) are being written...
Multiplexing took 4 seconds.
```

**Comment by mbunkus** [comment]
I can make it a warning, but not an error. For mkvmerge an actual error is something that aborts the muxing progress.

**Comment by Dark-SoniC** [comment]
A Warning is fine as well. Thanks a lot!

**Comment by mbunkus** [comment]
You're welcome. Thanks for the suggestion in the first place.
