### ISSUE TITLE
Convert .ts to .mkv : subtitles dropped

### ISSUE THREAD

**Issue by GingkoFr** [mbunkus/mkvtoolnix#1843]
Hello,

I have an issue when I want to use **MKVToolNix** (v9.7.1) to convert Mpeg **.ts** transport stream files (with usually one H264 video, multiple E-AC3 audio tracks, and multiple DVBSUB subtitles tracks).

When converting, I get the new **.mkv** correctly with all of its sound tracks, but _all subtitle tracks are lost_ (MKVToolNix doesn't even see them on opening).

However, if I first convert these very same **.ts** files to **.mkv** using another software (that is, [VideoReDo TVSuite](http://www.videoredo.com/en/Products_TVSuite_V5.html)), and next if I open the resulting **.mkv** files with MKVToolNix, I get the very same video and audio tracks, but that time _all subtitles tracks are present and working_.

The **.ts** files that I use as input are raw recordings of **.ts** DVB-T TV broadcasts, without no changes excepting hard filtering of the **TS** packets not concerning the channel I want to record (as there are up to 6 TV channels in one of these broadcast multiplex), selected on their PIDs. I am myself the developer of the recording software.

Would it be possible to fix this ? If MKVToolNix is able to handle these subtitles tracks in **.mkv** files, I think it shouldn't be very hard to find them in a **.ts** file.

I can eventually provide **.ts** files if requested.

Regards

**Comment by GingkoFr** [comment]
Ok. I will prepare this, likely later today.

Nevertheless, you just said that **mkvmerge** doesn't handle DVBSUBs _(or **MKVToolNix**? What difference between **mkvmerge** and **MKVToolNix**? I actually use **MKVToolNix GUI**)_.

But **MKVToolNix** obviously recognize them as **S_DVBSUB** in the track list if read from **.mkv**, and can recopy them in the newly generated files. This implies at least a tiny existing support, isn't it?

![mkvtoolnix_dvbsub](https://cloud.githubusercontent.com/assets/18695746/21561918/db8a28ec-ce73-11e6-81f2-0c6fd749780e.gif)

Regards,
Gingko

**Comment by mbunkus** [comment]
mkvmerge is the program doing the actual work. The GUI only queries mkvmerge for the tracks and later instructs mkvmerge how to multiplex.

There's a difference between reading from TS and from Matroska files. When mkvmerge reads from any container other than Matroska it must know how to convert the storage format used in the source container to the storage format used in Matroska. This is not the case for DVBSUB, therefore those tracks aren't recognized when mkvmerge reads the TS file.

When mkvmerge reads from a Matroska file it can use a special "pass-through" mode for codecs that it doesn't support otherwise. The reason is that the data is already stored the way it's supposed to be, and mkvmerge can simply keep it intact. That's what's happening here. It doesn't know how to handle DVBSUBs in general and uses the pass-through mode for that track when reading it from Matroska files.

**Comment by GingkoFr** [comment]
Ok. I just uploaded 4 files in the **/upload/bug_1843 folder**.
There are two **.ts** files, each being one minute excerpts from captured movies, along with their **.mkv** counterparts after conversion by VideoReDo (the one minute **.ts** extractions were also made using VideoRedo).

- The file **sample1_hv.ts** has three audio tracks (**fra**=French, **qad**=Audio description, **qaa**=Original language) and two DVBSUB tracks (_French for hearing impaired_ and _French_).
- The file **sample1_hv.mkv** is the counterpart of **sample1_hv.ts** after conversion using VideoRedo.
- The file **sample2_sm.ts** has four audio tracks (same as previous plus **deu**=German) and three DVBSUB tracks (same as previous plus one German, but this latter one seems to be actually empty).
- The file **sample2_sm.mkv** is the counterpart of **sample2_sm.ts** after conversion using VideoRedo.

By the way, your FTP server seems to be quite hard to use without using FileZilla (I tried first with the FireFTP extension for Firefox, but I finally used the command line **ftp** client from my own Linux server).

Regards,
Gingko

**Comment by mbunkus** [comment]
I've implemented support for DVB subtitles. I've also written a [pull request](Matroska-Org/matroska-specification#77) for the Matroska specification that adds the storage format used with `S_DVBSUB` to the official specs.

**Comment by mbunkus** [comment]
If you want to give it a try, download the [latest pre-builds for Windows](https://mkvtoolnix.download/windows/pre/). Build numbers 01390 and higher container the feature.

**Comment by GingkoFr** [comment]
Hello Moritz,

Thank you very much, that looks great !
I just tried it, and it seems working very well.
Note that after your comments, I checked and indeed this seems to be not very well implemented so far.
Actually the only software that I have and that is able to display these subtitles is [MPC HC](https://mpc-hc.org/).
Even [VLC](http://www.videolan.org/vlc/) doesn't work properly with these subtitles _(although it can display DVBSUB if read from a **.ts** file; but when opening a **.mkv** with DVBSUB, it gives an error message)_.
And in **VideoRedo**, [some comments in their forum](http://www.videoredo.net/msgBoard/showthread.php?35679-Mkv-dvb-sub) lets me thinking this is actually quite experimental.

There is something that puzzles me a little, however.
If I open a video converted by **VideoRedo** with **MKVToolNix**, there are some lines named “_tags_” at the end of the stream list which can be modified if a remux the video and reopen it. But if I convert a **.ts** file to **.mkv** using your software, none of these tags are present, even if I reopen a remuxed video.
What are these tags, exactly? What difference does it made if they are present or not present? Why could I want to have them, or to discard them in a given video?

Regards,
Gingko

**Comment by mbunkus** [comment]
Tags are user-supplied, textual descriptions about the content, e.g. which actors played in a movie, a plot summary or whatever else you want. Some programs write tags automatically. VideoRedo's includes the track's language as tags as well even though that's completely superfluous as the track headers contain that property already.

**Comment by ZexaronS** [comment]
Many many thanks for adding DVB Subtitle support for this key tool, part of my occasional archival process, I tend to do good slow encodes with x265, now lets hope Handbrake follows suit.
