### ISSUE TITLE
Feature Request: New tab + in mkvtoolnix-gui

### ISSUE THREAD

**Issue by begna112** [mbunkus/mkvtoolnix#1845]
Feature: Add a "+" sign to open new file tabs, like in most browsers. Duplicate the ctrl+N functionality to the button to avoid needing to use menus. 

Reason: Trust issues with ctrl+commands and avoids menus. Would also make setting a default "dropped file" default easier.

**Comment by mbunkus** [comment]
Thanks for the suggestion, but I won't spend time on this myself. I would accept patches that add such a feature, though.
