### ISSUE TITLE
local language code

### ISSUE THREAD

**Issue by PaulGlagla** [mbunkus/mkvtoolnix#1848]
The [iso 639-2 standard](http://www.loc.gov/standards/iso639-2/php/English_list.php) defines among the language codes, the codes **qaa** to **qtz** as "_Reserved for local use_". In France these codes are used by TV broadcasters for audio tracks that designate the original version of the movie (**qaa**) or an Audio Description (**qad**).
MKVToolNix does not recognize these codes and sets **und** instead. It should keep these codes in mkvmerge when merging these tracks, and even allow mkvpropedit to set such a code as language.

**Comment by mbunkus** [comment]
Yeah, I know, but I won't add support for that myself. It'd take a considerable amount of time to implement proper support for it. At the moment everything relies on a big list of valid codes and their (English) representation. The list is already very long and unwieldy at nearly 500 entries. Unconditionally adding yet another dump of 512 entries would for options that the overwhelming amount of users would never have a use for would make for bad user experience.

So another method of testing for the validity would have to be added, requiring tons of changes to both mkvmerge and mkvpropedit.

The most time-consuming work would have to be done in the GUI, though. Each language combo box would have to be converted to an editable combo box, validity checks would have to be added, error handling would have to be implemented in a way that makes it obvious to the user what was wrong. And a solution would need to be found for managing the list of favorite languages in the preferences.

I'm therefore closing this as "won't fix" for the time being. I'd be more than happy to accept patches that implement such a solution, though, but they would have to address all of the points listed above — fixing only mkvmerge would not be enough and not acceptable to me either.

**Comment by PaulGlagla** [comment]
Thank you for your reply. I appreciate your comments and understand your position. MKVToolNix is a great product and the high level of user experience should not be weakened. 
Actually, I do not know if all codes from **qaa**  to **qtz** are widely used in different parts of the world. In France, only 2 codes are common, namely **qaa** and **qad**. If a complete patch according to your requirements is not possible in the short term, it would have been of great help to add just these 2 codes to the list of 500 existing. The editable name for these languages generally keeps the words "qaa" and "qad", for instance in vlc when I open a ts file with such languages. But never mind...
