### ISSUE TITLE
MkvMerge: Error message 112 (There is not enough space on the disk.) printed twice

### ISSUE THREAD

**Issue by elgonzo** [mbunkus/mkvtoolnix#1850]
I consider this mostly a minor cosmetic issue. 

When muxing a video with MkvMerge to a target drive which does not have enough space available, MkvMerge will print the error message `Error: Could not write to the destination file: 112 (There is not enough space on the disk.)`  twice. This will also cause the MKVToolNix GUI to report two errors in its status bar, although only one error happened.

Double-printing of the error message seems to be specific to this particular error (and perhaps to other write-related errors, i guess). I tested writing to a non-writable target (DVD drive), and in that case the error message ("open file error") was given only once, as one would expect. 

My setup:
mkvmerge v9.7.1 ('Pandemonium') 64bit
Windows 7 Pro x64, english

**Comment by mbunkus** [comment]
Thanks. I'll look into it.
