### ISSUE TITLE
mkvtoolnix

### ISSUE THREAD

**Issue by deccy37** [mbunkus/mkvtoolnix#1855]
under properties then the options nothing is highlighted I cannot remove subtitles this has just suddenly happened please help

**Comment by mkver** [comment]
You have to select the track first (the lower of the two lists) before you can change its options (on the right).

**Comment by deccy37** [comment]
I just done that and I did see everything highlighted by unchecked the subtitles then it gave me a red circle obviously obviously that tells me that subtitles will be removed when I went to the video subtitles were still there it did seem to do it a lot faster than before when I hit the button start multiplexing never ever had a problem before first time and I am running the latest version any help would be much appreciated as it has never happened before

**Comment by mkver** [comment]
1. Please post the command line implicity used to do what you did (go to Multiplexer -> Show command line).
2. If I understood you correctly (and your post is really hard to understand: Can't you use puntuation?), you have unchecked the subtitles and remuxed, but the subtitles are still being shown if you play the newly created file. 
a) Are you really playing the newly created file? Not the old one?
b) Video players often autoload subtitles of they have a very similar name to the video file (or if they are in a subfolder (relative to your video file) named "sub" or "subs"). Are you sure that the subtitles that are displayed are really embedded in the file and not autoloaded?
3. You can add a screenshot by simpl dragging and dropping them onto your answer.

**Comment by mbunkus** [comment]
@mkver has already said everything there is to say about this. It's practically impossible that this is a bug in MKVToolNix, and it's almost certainly either intentional behavior on the player's side or a user error.

To make sure the subtitle tracks aren't present in the file, open the output file you've created with the header editor in MKVToolNix.

**Comment by deccy37** [comment]
there are subtitles present in the file but what I did notice about the TV show that I normally do it on notice that the subtitles were only on one person that spoke and I think it was because when the guy talks he is hard to understand so they put subtitles just for him they are not embedded subtitles so what I did was download a whole movie with Japanese subtitles run the program and it worked perfectly but previously on the TV show one it would completely remove the subtitle and did not show up even when the guy was mumbling so not sure what is going on there but thank you very much for your help it is very much appreciated
