### ISSUE TITLE
CueRelativePosition for video tracks

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1856]
Mkvmerge currently writes `CueRelativePosition`-elements for the main video track, although the blocks the cues refer to already are at the beginning of their respective clusters so that this is an unnecessary waste of a few bytes.
Moreover if one uses the `--engage no_cue_relative_position`, but not the `--engage no_cue_duration`-switch, a file without subtitles (or a file with subtitles without duration field) usually is only Matroska version 2, but [this](https://github.com/mbunkus/mkvtoolnix/blob/87caecc71e08f9d631fb9bea60f83651b5d1fe23/src/merge/output_control.cpp#L480) implies that it will be flagged as version four.

**Comment by mbunkus** [comment]
I won't change either. The first is purely an insignificant waste of space, the second is something that I actually don't want to fix. For example, if you split a file, don't have a subtitle entry in the first file but one in the second file, then both files would end up with different versions. I don't see an upside to such a situation.

If you (or any other user) want to make sure that a player can read your file, then use the appropriate `--engage` options. That way mkvmerge makes sure it doesn't use those features.
