### ISSUE TITLE
mkvtoolnix gui Chapters

### ISSUE THREAD

**Issue by darkarrow** [mbunkus/mkvtoolnix#1861]
I decided to try my hand at making chapters in some recent videos and subtitle files I started muxing. I am using the chapter creator of mkvtoolnix gui and vlc media player to check the chapters of the completed mkv file and am having some issues with it. First for the edition I didn't have "ordered" selected, frankly I'm still not 100% sure what this is but I have some idea, and when I open the resulting mkv file in vlc it shows only the first chapter I created for the whole video. Then I tried selecting "ordered" for the edition and that made the chapters show up seemingly correct in vlc, though I did notice vlc was reporting a shortened length of the video by a few seconds, however if I tried to use the next chapter button it would freeze the program. Here's a snippet of the chapters I have setup: http://i.imgur.com/oXjLZUi.png

**Comment by mbunkus** [comment]
Those are issues with how VLC treats the chapters, not how MKVToolNix GUI works. Please seek support for such things with the VLC folks — I cannot help you with it.
