### ISSUE TITLE
Website not up-to-date

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1862]
The website is not up-to-date. See for example the [NEWS.md](https://mkvtoolnix.download/doc/NEWS.md) or the [README](https://mkvtoolnix.download/doc/README). Is this delay normal after releasing a new version?

**Comment by mbunkus** [comment]
They should have been updated automatically during by the build process. I don't know exactly why not. I've triggered the appropriate section of the build process again, and they're up to date now. Thanks for noticing.
