### ISSUE TITLE
Small issue during install

### ISSUE THREAD

**Issue by marco44** [mbunkus/mkvtoolnix#1865]
Hi, I'm maintaining the mktoolnix-git archlinux aur package. I get this during make install. I guess there is something wrong somewhere in the rake configuration, but as I don't know rake… :)

/usr/bin/install -c -m 644 doc/man/ca/mkvmerge.1 /home/marc/aur/mkvtoolnix-git/pkg/mkvtoolnix-git//usr/share/man/ca/man1/mkvmerge.1
/usr/bin/install: cannot stat 'doc/man/ca/mkvmerge.1': No such file or directory

It's not that big an issue, but I have to put bandaid to ignore the return code of rake install for now, which is not good.

What information can I provide ?

Regards

**Comment by mbunkus** [comment]
Up until and including release 9.8.0 I used to keep the translated man pages in the git repository even though they can be generated automatically by the build process if the right tools are installed. After release 9.8.0 I decided to remove those pre-built man pages.

The error message you're seeing means that you do not have those tools installed. You need:

* `xsltproc`
* DocBook's XSL stylesheets for man pages
* `po4a`

On Arch the required packages are `libxslt`, `po4a` and `docbook-xsl`.

**Comment by mbunkus** [comment]
Some more points:

* I don't consider this to be a bug in the build system as the next release source code tarballs will all include the pre-built man pages. You won't need the aforementioned packages when you're building a release tarball.
* I still have to update my documentation both in the package as well as on the web site.

**Comment by marco44** [comment]
Well, I feel that having rake install error on trying to install something that hasn't been built (with no error on this step) is a bug, but I won't argue, it's your projet. I know how to solve my problem, that's ok for me.

Thanks

**Comment by mbunkus** [comment]
There are basically three options for the build system in such a case:

1. check for all required tools and abort if they're not found,
2. like 1. but only if you're not building a release.
3. check for all required tools and silently disable building and installation of affected files if the tools aren't found.

The first option is inacceptable as it would impact release versions as well even though the release version already comes with the pre-built files, and therefore the user doesn't need those tools.

The second option is kind of hard to implement, and such a detection would most certainly contain bugs of its own.

The third option could be used, but I don't like it very much. However, I'll think about implementing it.

**Comment by mbunkus** [comment]
I've reconsidered. `xsltproc` and the DocBook XSL stylesheets are now mandatory requirements. `po4a` remains an optional requirement. However, if it isn't present then the translated man pages will neither be built nor installed.
