### ISSUE TITLE
Only 1s muxed when trying to mux an MP4 created by Apple QuickTime

### ISSUE THREAD

**Issue by stevek123** [mbunkus/mkvtoolnix#1867]
I have a screen recording that was recorded on the latest OSX with the built in tool, but only 1s gets muxed when I try to multiplex it. There is no error message or anything. If you want, I can send you the mp4 file. I'm using the latest 64bit version (9.8.0) on Win10

**Comment by stevek123** [comment]
I have uploaded it.

**Comment by mbunkus** [comment]
Thanks. I'll look into it, but I cannot give you an ETA.

**Comment by mbunkus** [comment]
This was quite an interesting case. The file hit no less than four bugs in mkvmerge's MP4 reader. They've all been fixed. Muxing your sample file works fine now, the duration is OK, the content is OK, and seeking works.

New [pre-builds for WIndows](https://mkvtoolnix.download/windows/pre/) are currently being built and will be available shortly. Build numbers 01420 and higher will include the fixes.

**Comment by stevek123** [comment]
Thank you for fixing it!
