### ISSUE TITLE
After Jobs Completion Settings

### ISSUE THREAD

**Issue by zero77** [mbunkus/mkvtoolnix#1868]
Can you add options on what should happen once all jobs have been completed.
Like shutdown computer, close program, delete old files.
Thanka

**Comment by mkver** [comment]
Are you aware that MKVToolNix already has such a feature? Go to your preferences, select "Executing programs" on the left and add, what you want it to do, and select "after the job queue has stopped".

**Comment by mbunkus** [comment]
As @mkver has said, you can easily implement that yourself with the existing functionality.

**Comment by zero77** [comment]
How would you remove the old files using the "Executing programs" meathead

**Comment by mbunkus** [comment]
Clicking on the `Add variable` button shows that there's a variable called `<MTX_SOURCE_FILE_NAMES>` you can use for such a purpose.
