### ISSUE TITLE
IMDB Artwork Search Capability

### ISSUE THREAD

**Issue by zero77** [mbunkus/mkvtoolnix#1869]
Can you add an option to search IMDB and import artwork for TV shows and films.
As this would help speed up and automate the process of adding thumbnails to files.
Thanks

**Comment by mbunkus** [comment]
I'll think about it.

**Comment by mbunkus** [comment]
I won't add such functionality because it would violate [IMDb's terms of service](http://www.imdb.com/help/show_leaf?usedatasoftware).

Using [omdbapi](http://www.omdbapi.com/) as an alternative wouldn't be much use either as their poster search API is only available to paying users.

**Comment by zero77** [comment]
As IMDB and omdbapi aunt suitable would you be able to add an alternative service.
