### ISSUE TITLE
HDMV PGS subtitles with duration

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1878]
Hello,

as you are well aware, HDMV PGS subtitles [may be put into blocks with `BlockDuration` elements indicating their length](https://github.com/Matroska-Org/matroska-specification/blob/master/subtitles.md), hence eliminating the need for the empty subtitle segments whose only purpose is to end the last subtitle packet. I have created such a file by manually editing an existing mks-file with a hex editor (I have also eliminated the empty subtitle segments to find out how much space one saves. (Usually 51 bytes per empty subtitle segment deleted (including the savings from having one cue entry less, but one `CueDuration` more); if a subtitle segment ends not with an empty subtitle segment, but with a really new segment, the `BlockDuration` approach actually costs bytes))  and ran into some issues:
First and foremost, mkvmerge drops the durations during normal remuxing completely and puts the data in ordinary simpleblocks. And although it doesn't write the duration for the last packet any more, said duration is still used for determining the duration of the whole matroska segment and of the track (for the statistics tags). Moreover, it writes the `CueDuration` elements (which is the only place where the duration of the blocks survive the remuxing). The only way to make mkvmerge retain the durations is by using `--engage force_passthrough_packetizer`. Even `--engage no_simpleblocks` created just blocks without durations.
And secondly, the sup-files created by mkvextract upon extracting said track don't contain any information regarding the durations any more; to solve this, mkvextract needs to include empty subtitle segments with the right pts. Strangely, there seems to be more than one way to create empty subtitle segments (even within the same subtitle).
[Here](https://www.dropbox.com/s/0b5z0oa18aspkrr/PGS.zip?dl=0) is the sample (it contains the original file, the file after manipulating with a hex editor and the file after remuxing with the passthrough packetizer).

Greetings
Andi

**Comment by mbunkus** [comment]
I don't think I'm going to fix any of the issues you've pointed out.

PGS subtitles are a somewhat complex beast. How long something is visible isn't as easy to determine, and it doesn't have to span from the current PGS segment to the next one either. For example, a PGS segment may come along that only updates the palette but doesn't change what's currently being displayed. Therefore Matroska's Block Duration element doesn't provide a good model for such type of subtitle stream.

Additionally a PGS packet that basically says "stop displaying what you're currently displaying" is not just a simple "end of display" PGS segment (those would only be three bytes long), it usually also contains a "presentation composition segment" and an "interactive composition segment", maybe even more. Those would have to be re-created during extraction if they're missing, but how that data should be guessed is unsolved.

The current way of playback works, and I'm not willing to invest time here for pretty much no observable gain.
