### ISSUE TITLE
Embedded fonts are not used for subtitle playback

### ISSUE THREAD

**Issue by emk2203** [mbunkus/mkvtoolnix#1880]
Problem: Embedded font files are not used, the players (latest `mpv` 0.23.0, latest `PotPlayer` and `MPC-HC` on Windows 10) don't show the subs at all. If I put the font file in the root folder of the media files, the media players play the files correctly with subtitles and use the font specified in the subtitle track (ASS).

I have read the wiki entry https://github.com/mbunkus/mkvtoolnix/wiki/Embedded-fonts-dont-work to troubleshoot. Basically, I assume the default MIME type used should be compatible with the players.

From `mkvinfo`, I get

- Dateianhänge
   - Dateianhang
      - Dateiname: respub.ttf
      - MIME-Typ: **application/x-truetype-font**
      - Dateiinhalt, Größe: 57240
      - Datei-UID: 5384663235372111177

so the MIME type is already using the proposed MIME type.

The files were muxed from video+audio files, subtitle files and the font .ttf file, default settings. The result looks okay to me (video, audio, subtitle track, attachment). Is this a bug, or user error on my part?

Example file information:
[mkvinfo.txt](https://github.com/mbunkus/mkvtoolnix/files/743416/mkvinfo.txt)
[mediainfo.txt](https://github.com/mbunkus/mkvtoolnix/files/743420/mediainfo.txt)

**Comment by mbunkus** [comment]
I really cannot help you with this. You should ask the developers of the respective players or at a place dedicated to arbitrary audio/video questions such as [Doom9](http://forum.doom9.org/index.php).

**Comment by emk2203** [comment]
Sorry that I have not been clear enough. Shouldn't `mkvtoolnix` generate files which are compliant with the requirement of the major media players on two platforms? Could the default MIME type for `.ttf` be changed to these requirements if you use the default options or just drag and drop?

**Comment by mbunkus** [comment]
> Shouldn't mkvtoolnix generate files which are compliant with the requirement of the major media players on two platforms?

No, MKVToolNix generates files that are compliant with the Matroska specification, as should players.

Additionally how attachments are named, which MIME type to use etc., is fully up to the user. MKVToolNix is not preventing you from shooting yourself in the foot.
