### ISSUE TITLE
Request: Wildcard Support For CLI

### ISSUE THREAD

**Issue by zero77** [mbunkus/mkvtoolnix#1881]
Can you add wildcard support for when you are working with multiple files in the CLI: 
input file *.mkv  attachment *.jpg output *(1).mkv 

For example, all mkv files will be the input file, and all jpg with the same name as the input will be attached, and the output will be the original name with a (1) at the end.

Thanks,

**Comment by mbunkus** [comment]
No, sorry. You should use a proper scripting language for automation tasks.
