### ISSUE TITLE
mkvinfo not displaying languages with newer files

### ISSUE THREAD

**Issue by demonbane** [mbunkus/mkvtoolnix#1882]
I've been going through and converting a lot of my old media to Matroska, and it looks like any files created using mkvmerge 9.8.0 contain the language codes I set per track (as reported by `mkvmerge --identify -F json`), but don't show any language codes when I use mkvinfo.

Not sure if this is a feature or a bug, but it's definitely confusing. To reproduce, just do something along the lines of: `mkvmerge -o foo.mkv --language 0:eng --language 1:eng foo.avi`. Checking foo.mkv with mkvmerge will show `"language": "eng"`, while checking it with mkvinfo won't display any language data.

**Comment by mbunkus** [comment]
This is not a bug. Please see [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/Understanding-mkvinfo's-output).
