### ISSUE TITLE
No/Erratic sound, out-of-sync subtitles with 9.6.0+ (tried with 9.8.0 too)

### ISSUE THREAD

**Issue by frusgit** [mbunkus/mkvtoolnix#1883]
Hi,
When I mux my files ANY version above 9.6.0 (which seems to be the last version working fine) appear to mess up sound and subtitles.

I uploaded 2 files here:
https://dailyuploads.net/eig9gogbam5k
https://dailyuploads.net/lg2try0n08gd

Try muxing them and you should see and replicate.

**Comment by mbunkus** [comment]
Thanks, but I cannot reproduce that issue with the files you've provided. I've muxed them with v9.8.0 and the current development version and used VLC for playback. Both files have smooth playback, sound plays normally, and subtitles are in sync with the audio.

**Comment by frusgit** [comment]
I'm using BS Player (don't have VLC, stopped using it long time ago after I found out about BS Player) and it's definitely something off with builds since I have a second machine (my work machine... which can be considered 'virgin', no games, etc...) it has BS player installed as well and it did not play right there neither.

What radically changed from 9.6.0 to next version(s) to cause this, do you have any idea?

Btw, I just installed latest VLC, same issue, no sound (sometimes you get sound when you move to say half of the file, but subtitles are always off sync)

After VLC doing same thing, I also tried to play both versions (9.6.0 and 9.8.0) on PopcornHour media player, exact same issue. Popcorn is known to play anything you throw at it generally (at least for me up to this date).
In Popcorn subtitles immediately appeared (correctly I would say) but no sound and no video. When I pressed 3 (goes to %30 of the movie), screen came but lost subtitles, still no sound. When I pressed 5, (yes, going to %50 of the movie), sound came but off sync and no subtitles.

It's clear that MKVtoolnix's muxing is causing this but only you would know what radically changed from 9.6.0 to next version(s) which causes this.

I REALLY love MKVtoolnix and in fact I'm using it everyday to build my archives.Now that it's broken and I'm forced to use 9.6.0 last good version.

I should not be the only one with above issue(s). Since nothing has been changed in my machines, both work and play machines, and popcorn is a machine many years old, I appreciate if you assist in 'deciphering' this thing.

Greetings.

**Comment by mbunkus** [comment]
Well, there are tons of changes between versions. Unfortunately no single change comes to mind. So far you are the only one to report such behavior.

Can you please post the full command line for of those multiplex jobs? If you're using the GUI, you can let it show you the command line via `Multiplexer` → `Show command line`.

Which operating system are you running MKVToolNix on? I assume Windows based on your mention of BS Player, but I'd like to make sure.

Are you writing the result to a USB-connected device?

**Comment by mkver** [comment]
I can reproduce this with 9.8 and with the latest pre-release. Both video and audio of the output files start at 15:22.337 which explains that the internal subtitles are out of sync with A/V. (But if one doesn't mux the subtitles at all, then the players renormalize the timeline, i.e. they treat the point 15:22.337 as 0:00 and therefore audio and video are in sync with the external subtitles (which do not get shifted).)
There seem to be other issues. I'll continue my analysis.

**Comment by frusgit** [comment]
Sure, here is the command line:
"C:/Program Files (x86)/MKVtoolnix\mkvmerge.exe" --ui-language en --output ^"C:\X\Oliver.Stones.Untold.History.Of.The.United.States.Series.1.01of10.World.War.II.720p.HDTV.x264.AAC.MVGroup.org.mkv^" --language 0:eng --default-track 0:yes --language 1:eng --default-track 1:yes ^"^(^" ^"G:\Zip\M\MKVToolnix 9.8.0\ZZZ TRIAL\Oliver.Stones.Untold.History.Of.The.United.States.Series.1.01of10.World.War.II.720p.HDTV.x264.AAC.MVGroup.org.mp4^" ^"^)^" --language 0:eng --default-track 0:yes ^"^(^" ^"G:\Zip\M\MKVToolnix 9.8.0\ZZZ TRIAL\Oliver.Stones.Untold.History.Of.The.United.States.Series.1.01of10.World.War.II.720p.HDTV.x264.AAC.MVGroup.org.eng.srt^" ^"^)^" --track-order 0:0,0:1,1:0

My 'play' machine is on Windows 7 Ultimate, my work machine is on Windows 8.1 Single language.

...no, I transfer the resulting MKV to my NAS from which Popcorn reads file from and plays. No USB is used in any step.

**Comment by mbunkus** [comment]
Hmm, so far I've only tried muxing & playback on Linux (as I'm still at work). I'll try again on Windows tomorrow.

**Comment by frusgit** [comment]
Thank you for looking into this. I was going bananas.

I initially thought it was a codec issue (in my Win7 machine), then I understood it wasn't since the resulting file didn't play correctly in win8.1 'work' machine and in popcornhour.

Many many thanks again for looking into this.

**Comment by frusgit** [comment]
If it gives any clue (maybe?) the only thing I always do is set the "default track flag" to yes on original language the source is on.

For ex. for this English is original video, audio and subs, so I set them all to "Yes" for default track flag.

**Comment by mbunkus** [comment]
Changing the default track should have absolutely no affect on the timestamps.

**Comment by mbunkus** [comment]
Based on the tests I've done so far my current guess is that it's a Windows-specific bug somewhere — e.g. an integer overflow that's not triggered on Linux as certain integer types are wider on 64bit Linux than they're on 64bit Windows. I'll look further into this over the next couple of days. But please be patient; I have a packed schedule ahead.

**Comment by mkver** [comment]
Probably, but it can't be the reason that from pre-build 1420 on both tracks from the mp4 get the same id. This happens by the way with all mp4s I checked.

**Comment by mbunkus** [comment]
I can reproduce it on Windows, but not on Linux. On Linux 9.6.0, 9.8.0 and the current development branch are all OK. Looking further into it.

**Comment by mbunkus** [comment]
The issue wasn't caused by a commit, but by me changing compiler versions after the release of 9.6.0 (from gcc 4.9.x to 6.2.0). This is going to be difficult to debug.

**Comment by frusgit** [comment]
> The issue wasn't caused by a commit, but by me changing compiler versions after the release of 9.6.0 (from gcc 4.9.x to 6.2.0). This is going to be difficult to debug.

That should probably be an important clue. (based on my novice programming skills)

Thank you very much for looking into this Mr.Bunkus.
I'm pretty sure I should not be the only one affected by this though, as everything on my machines are pretty standard stuff. (especially on my 'work' machine). Others probably are lazy/busy/etc, to report.

Popcornhour failing to play resulting MKV correctly made me report this to you indeed. Means the effect is cross-platform too, once MKV is created in Windows.

It appears it's a Windows-related bug for sure. You'd know much much better of course.

Also no worries, I know very well what a 'packed schedule' means from my situation!, THE most scarce thing is time for me nowadays, I wish I had 8 hands like an octopus!

I really do appreciate you looking into this. MKVToolnix is the only muxer I use and love! (and recommend too!)
Have a great weekend.

**Comment by mbunkus** [comment]
New pre-builds for Windows that include the fix [are available here](https://mkvtoolnix.download/windows/pre/).

**Comment by mbunkus** [comment]
Seems there's still a secondary issue.

**Comment by mbunkus** [comment]
Oh forget it; the issue is indeed fixed. My last test was done with the wrong compilation.

**Comment by frusgit** [comment]
Thank you Mr.Bunkus!

**Comment by mbunkus** [comment]
You're weclome. And thanks fore reporting it in the first place.

**Comment by frusgit** [comment]
mkvtoolnix-64bit-9.8.0-build20170211-01428-901aaea1e-setup.exe 
I used this one. (appaered latest one in PRE dir.)

Unfortunately similar issues.
BSPlayer crashes. Doesn't even play.
VLC player plays with no sound, but with screen shows with subtitles appearing correctly.
Shall I try with Popcornhour as well?

**Comment by frusgit** [comment]
Sorry :(

**Comment by mbunkus** [comment]
No need to be sorry. I can reproduce it, though it's quite strange — in certain situations audio is created normally, in others it's missing from the file completely.

**Comment by mkver** [comment]
Actually, the audio is not missing with pre-build 1428. But since pre-build 1420 (so this is not purely because of the change in the compiler used) both audio and video read from the same mp4 file get the same id (I only tested with files which have exactly one audio and one video track; and it happened on all of them). The id is used consistently (i.e. both the header and the simpleblocks always use the same id).

**Comment by mbunkus** [comment]
Good catch. That does happen on Linux, too. However, it only happens when the `--track-order 0:0,0:1` parameters are used (as added by the GUI). Leaving them out (which should be equivalent to providing those exact arguments) makes the process work again.

I'm in the middle of figuring out why this happens.

**Comment by frusgit** [comment]
I wish I could offer you a nice cup of Capuccino! (still mastering/perfecting its making, not trivial though, 26secs exrtaction time, precise measures, etc.... too many parameters in effect indeed for consistency)

**Comment by mbunkus** [comment]
The other issue had nothing to do with what you've reported initially. It's been fixed, too, though. New pre-builds are currently being built and will be [available](https://mkvtoolnix.download/windows/pre/) in a couple of minutes (build numbers 01430 and higher).

**Comment by mkver** [comment]
Works fine here. Did you find out what made gcc 6.2 behave differently? Is it a bug in the compiler or on your side?

**Comment by mbunkus** [comment]
It was a bug in my code regarding corner cases of overflow handling that just happen to behave differently on Windows & Linux due to certain integer types having different sizes.

**Comment by mkver** [comment]
But why don't you always use integers that have the same size on all platforms (i.e. long long instead of long)?

**Comment by frusgit** [comment]
Just a quick confirmation that 1430 works fine in all systems.

I also tried another one, with more languages/subtitles, seems to work fine.

Thank you very much Mr.Bunkus!!
Have a great weekend.

**Comment by mbunkus** [comment]
@mkver C and C++ are rather confusing regarding their implicit type conversions. Adding the use of `auto` instead of explicit types exacerbates that confusion, though it does lead to more readable code. Getting it always right is rather hard.

The thing with overflows is that signed integer overflow is undefined behavior. So compilers are free to optimize places where that may happen in whatever way they see fit. And implementing multiplication (or addition) in overflow-safe ways without triggering undefined behavior in C/C++ is very, very hard.

Saying "why don't you do X" is rather easy, but they indicate that you lack a certain depth of experience with these things.
