### ISSUE TITLE
Tag Duration Wrong

### ISSUE THREAD

**Issue by ndjamena** [mbunkus/mkvtoolnix#1885]
```
Duration : 20 min 47 s 
```
-----
```
SplitMode: split by parts based on timecodes

5:00-10:00,+15:00-20:00
```
-----
```
Duration : 10 min 1 s 
```
But Lo!
```
    <Simple>
      <Name>DURATION</Name>
      <TagLanguage>eng</TagLanguage>
      <DefaultLanguage>1</DefaultLanguage>
      <String>00:15:02.193000000</String>
    </Simple>
```
On all the tracks.

**Comment by mbunkus** [comment]
I'll need sample files.

**Comment by ndjamena** [comment]
I just grabbed a random file from my harddrive for that example, I discovered the bug via my tv recordings, that was an x264 encode.

I guess I could encode several seconds of blank clip for you to play with...

Oh, I just tried it on an AAC mka and it worked...  Are you sure you need a sample?  As far as I can tell any Matroska file will do.

**Comment by mbunkus** [comment]
I can trigger the same issue here with that split specification. Sample files are indeed not needed. Sorry.

**Comment by mbunkus** [comment]
[Pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) including the fix are available.
