### ISSUE TITLE
Add fill end times option to chapter editor

### ISSUE THREAD

**Issue by ndjamena** [mbunkus/mkvtoolnix#1887]
Add an option to the chapter editor to fill in the "end timecodes" fields of each of the chapters with the start time of the next chapter (chronologically speaking).

If the chapters aren't attached to an MKV the option could be disabled or the last chapters end time could simply be left blank.

Some people fill them in because they think it's a good idea, some people add them because they mistakenly think they're supposed to.  The option would also help when end times are already included in the chapters and a user is repositioning the chapters.  Otherwise they'd need to endlessly copy/paste the start times into the end times to keep them up to date.

When I was attempting to write a chapter editor it automatically set the end times to the start time of the next chapter when "ordered chapters" was disabled.  A similar option in the MKVToolnix GUI might be useful but not required.  It also showed chapter duration.

An option to wipe the end times could also be a possibility.

I don't know if it's possible but adding the option for some visual clue on the "start time" field when its timecode occurs before the next physical chapter might be useful in some situations.  (I'm aware Matroska chapters don't need to be in order.)

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include this are available (build numbers 01527 and higher).
