### ISSUE TITLE
I'd like to add a voice to the video.

### ISSUE THREAD

**Issue by oklokl** [mbunkus/mkvtoolnix#1888]
I'd like to add a voice to the video.
I'd like to add additional updates to the existing audio.
Speak easily ..
With traditional music.I want to have my voice eumseong.
I have an audio file that I made earlier.
The image has background music.
Together with these two things simultaneously ...
I want to print it at the same time.
Is there any way?

Two audio pieces ...
One, I'd like to make it.
http://zilzu.tistory.com/61
https://www.goldwave.com/
(Audio integrated program)

I would like to mix up the sounds.(In the video ...)
The background is ...
And my voice ...

**Comment by mbunkus** [comment]
This is a bug tracker, not a forum to ask general questions how to achieve arbitrary things. Please ask such questions in a place more appropriate, e.g. [Doom9's forum](http://forum.doom9.org/) or the [VideoHelp forum](http://forum.videohelp.com/).
