### ISSUE TITLE
mp4 timeline for tracks without edit lists

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1889]
Hello,

it seems that tracks in mp4-files that don't have an edit list always start at zero even when the first sample does not have a composition timestamp of zero. This is possible when there is a Composition Time to Sample Box (ctts), but no edit list and it leads to sync issues between the tracks that come from this mp4-file. In contrast, both the edit list and the ctts are taken into account when a track contains an edit list.
Let me explain: According to the specification (explicitly the fifth edition of ISO/IEC 14496-12) the first sample of a track does not automatically have a composition timestamp of zero: "In either version of this box, but particularly under version 0, if it is desired that the media start at track time 0, and the first media sample does not have a composition time of 0, an edit list may be used to ‘shift’ the media to time 0." (from 8.6.1.3.1, the definition of the Composition Time to Sample Box) 
Furthermore from the definition of Edit Box (8.6.5.1): "An Edit Box maps the presentation time‐line to the media time‐line as it is stored in the file. The Edit Box is a container for the edit lists.
The Edit Box is optional. In the absence of this box, there is an implicit one‐to‐one mapping of these time‐lines, and the presentation of a track starts at the beginning of the presentation. An empty edit is used to offset the start time of a track." Note that the beginning of the presentation of a track does not need to coincide with the beginning of the presentation of the first sample of the track. The explanation in 8.6.6.1 and the warning about undefined behaviour in 8.6.1.4.1 imply this.
In my [first test file](http://nrodl.zdf.de/none/tivi/15/12/151208_aufsager1_blog_jss_2328k_p35v11.mp4) the first frame of the video track has a decoding timestamp of 0 (as always) and an offset of 40ms according to the ctts. There is no edit list, so the composition of this track should begin at 40ms; the audio track of this track has no ctts atom and no edit list, so its composition starts at 0ms. Yet MKVToolNix starts both tracks at 0.
My [second test file](http://ondemand.mdr.de/mp4dyn/c/FCMS-c7ad86d3-f92e-45ef-860c-7c65a7432248-c7cca1d51b4b_c7.mp4) has a video track whose first sample has a composition time equivalent to 40ms according to ctts. The audio has an offset of 1920 samples according to ctts and an edit list that declares the start to be at 1600 samples; hence the first 320 samples of this tracks composition timeline are empty. This amounts to 6 2/3ms or a relative delay of 33 1/3ms between the tracks (with audio being shown first). Yet after remuxing with MKVToolNix video starts at zero and audio at 7ms.

Grüße
Andi

PS: [This line](https://github.com/mbunkus/mkvtoolnix/blob/master/src/input/r_qtmp4.cpp#L2218) refers to and speaks of pts, but the sizes fit only when it is interpreted as dts. Is this supposed to happen?

**Comment by mbunkus** [comment]
Looking at the code I can see that the data from CTTS is again [offset by the first CTTS value](https://github.com/mbunkus/mkvtoolnix/blob/master/src/input/r_qtmp4.cpp#L2051) if (and only if) the track is an [AVC/h.264 or an HEVC/h.265](https://github.com/mbunkus/mkvtoolnix/blob/master/src/input/r_qtmp4.cpp#L2022) track. This change is quite old and was likely done to counter the processing via edit lists (mkvmerge's CTTS support is much older than its edit list support). So the CTTS is taken into account (you can see that in the second video frame's timestamp: 0ms, 80ms, 40ms… instead of the 0ms, 40ms, 80ms… it'd be without CTTS) but shifted, therefore only slightly wrong instead of completely wrong.

But wrong is still wrong, of course. I'll fix it.

**Comment by mbunkus** [comment]
After reading ISO 14496-12 some more I concur with your assessment of how to calculate the PTS, and what the PTS should be for both files.

I've completely rewritten the code for calculating timestamps in MP4 files, especially regarding the `ctts` and `elst` atoms. The result is that multiplexing your two test files works fine. I still have to test on other files.

What's frustrating is that ffmpeg doesn't seem to handle your second test file properly. I've modified ffmpeg's MP4 demultiplexer (`libavformat/mov.c`) to dump the calculated PTS & DTS right before handing the frame over to the main code. The video frame PTS are OK at 40, 200, 80, 120, 160… (DTS 0, 40, 80, 120, 160…). The audio PTS aren't, though: 0, 21, 42, 64, 85… (DTS -40, -18, 2, 24, 45…). This indicates a relative difference of 40ms between the two tracks. It seems that the `ctts` offset is applied to the audio track, but the edit list offset isn't.

I haven't been able to figure out where (or even if) ffmpeg is wrong. I'd say it is wrong in this case, and that means I cannot easily get values that are known to be good for comparison.

I'll continue working on this over the next days.

Just as a preview: here's what mkvmerge produces for `151208_aufsager1_blog_jss_2328k_p35v11.mp4`:

    Track 1: video, codec ID: V_MPEG4/ISO/AVC…
    Track 2: audio, codec ID: A_AAC…
    I frame, track 2, timecode 0 (00:00:00.000), size 342, adler 0x431b312e
    I frame, track 2, timecode 21 (00:00:00.021), size 421, adler 0x6e91d1cc
    I frame, track 1, timecode 40 (00:00:00.040), size 87358, adler 0x6c512380
    I frame, track 2, timecode 43 (00:00:00.043), size 357, adler 0x8e94a254
    I frame, track 2, timecode 64 (00:00:00.064), size 331, adler 0xf04fa937
    I frame, track 2, timecode 85 (00:00:00.085), size 333, adler 0x0a12a425
    I frame, track 2, timecode 107 (00:00:00.107), size 340, adler 0x30c3b28e
    P frame, track 1, timecode 120 (00:00:00.120), size 15210, adler 0xc8e3c29c
    B frame, track 1, timecode 80 (00:00:00.080), size 1361, adler 0x743096d2
    I frame, track 2, timecode 128 (00:00:00.128), size 338, adler 0x34ffba13
    I frame, track 2, timecode 149 (00:00:00.149), size 343, adler 0x0d7eaf44
    I frame, track 2, timecode 171 (00:00:00.171), size 340, adler 0x07feadb3
    I frame, track 2, timecode 192 (00:00:00.192), size 333, adler 0xa1b5add8

And this is what it writes for `FCMS-c7ad86d3-f92e-45ef-860c-7c65a7432248-c7cca1d51b4b_c7.mp4`:

    Track 1: video, codec ID: V_MPEG4/ISO/AVC…
    Track 2: audio, codec ID: A_AAC…
    I frame, track 2, timecode 0 (00:00:00.000), size 505, adler 0xddb905ab
    I frame, track 2, timecode 21 (00:00:00.021), size 505, adler 0x64002e73
    I frame, track 1, timecode 33 (00:00:00.033), size 146554, adler 0xe7ee4547
    I frame, track 2, timecode 43 (00:00:00.043), size 505, adler 0x279e3a3f
    I frame, track 2, timecode 64 (00:00:00.064), size 505, adler 0x7c0b3436
    I frame, track 2, timecode 85 (00:00:00.085), size 505, adler 0xa9b22efd
    I frame, track 2, timecode 107 (00:00:00.107), size 505, adler 0xd5f137de
    I frame, track 2, timecode 128 (00:00:00.128), size 505, adler 0x683f3f23
    I frame, track 2, timecode 149 (00:00:00.149), size 505, adler 0x9c753c0b
    I frame, track 2, timecode 171 (00:00:00.171), size 505, adler 0x05b93114
    I frame, track 2, timecode 192 (00:00:00.192), size 505, adler 0x816b3653
    P frame, track 1, timecode 193 (00:00:00.193), size 13174, adler 0x1119a936
    B frame, track 1, timecode 73 (00:00:00.073), size 1515, adler 0x9907eb53

**Comment by mkver** [comment]
Yeah, I also noticed that ffmpeg's timestamps are pretty weird. Here is the beginning of the output of `ffmpeg -debug_ts -report -i "MDR um 11-Gebärde des Tages vom 9. Februar 2017-1757205976.mp4" -t 1 -c copy -f framehash -hash adler32 i:\mdr.txt` (the input file is the second file):
```#format: frame checksums
#version: 2
#hash: adler32
#extradata 0,                              53, 3e800dd7
#extradata 1,                               2, 00b400a2
#software: Lavf57.66.102
#tb 0: 1/25000
#media_type 0: video
#codec_id 0: h264
#dimensions 0: 960x540
#sar 0: 1/1
#tb 1: 1/48000
#media_type 1: audio
#codec_id 1: aac
#sample_rate 1: 48000
#channel_layout 1: 3
#channel_layout_name 1: stereo
#stream#, dts,        pts, duration,     size, hash
1,      -1920,      -1920,     1024,      505, ddb905ab
1,       -896,       -896,     1024,      505, 64002e73
0,          0,       1000,     1000,   146554, e7ee4547
1,        128,        128,     1024,      505, 279e3a3f
1,       1152,       1152,     1024,      505, 7c0b3436
0,       1000,       5000,     1000,    13174, 1119a936
1,       2176,       2176,     1024,      505, a9b22efd
1,       3200,       3200,     1024,      505, d5f137de
0,       2000,       2000,     1000,     1515, 9907eb53
1,       4224,       4224,     1024,      505, 683f3f23
1,       5248,       5248,     1024,      505, 9c753c0b
0,       3000,       3000,     1000,     2948, e0eda35f
1,       6272,       6272,     1024,      505, 05b93114
1,       7296,       7296,     1024,      505, 816b3653
0,       4000,       4000,     1000,     2108, 10bb18bf
1,       8320,       8320,     1024,      505, 04b5361a
1,       9344,       9344,     1024,      505, fa633d69
```
Again, the video timestamps are fine; but the audio dts and pts are wrong. And they are wrong in a different way than you say: According to this log, the first audio pts is -40. If I remux this file to matroska with ffmpeg, audio starts at 0 and video at 80ms, so the difference is preserved. (If I use the matroska muxer with the option `-avoid_negative_ts disabled`, then the first audio packet has a pts of -40 (which is actually invalid) and video starts at 40ms.)
Contrary to you, I don't have the abilities to modify ffmpeg's mp4 demultiplexer, but luckily ffmpeg brings its own tool to debug timestamps with it (see the above commandline). But looking at [the log](https://github.com/mbunkus/mkvtoolnix/files/789646/ffmpeg-20170221-081845.txt) didn't really enlighten me.
Here are some lines from the report with comments by me (the first few lines come from the part where ffmpeg probes the input file; afterwards it begins the real muxing):
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000000578020] Offset DTS by ctts[0].duration: 1920 [why do they offset the DTS by this amount? The DTS always starts at 0 and the ctts is used to offset the cts. Anyway, now we at least know why ffmpeg thinks that the dts of the first audio packet is negative.]
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000000578020] Processing st: 1, edit list 0 - media time: 1600, duration: 364992 [Although it claims to process the edit list, it doesn't seem to do so.]
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000000578020] shifted frame pts, curr_cts: 0 @ 0, ctts: 1920, ctts_count: 1 [Does ffmpeg normalize the track so that its cts begins at 0? If DTS is -1920, then at least the offset between cts and dts for this track is valid. And as I said: Apparently the edit lists isn't used at all. There are lots of lines like these for the audio track. I omitted them.]
[h264 @ 0000000000454ee0] nal_unit_type: 7, nal_ref_idc: 1 [Strangely there aren't lines like the above one for the video track. Just some like this one.]
cur_dts is invalid (this is harmless if it occurs once at the start per stream) [This is the first line of the actual muxing section.]
cur_dts is invalid (this is harmless if it occurs once at the start per stream)
demuxer -> ist_index:1 type:audio next_dts:NOPTS next_dts_time:NOPTS next_pts:NOPTS next_pts_time:NOPTS pkt_pts:0 pkt_pts_time:0 pkt_dts:-1920 pkt_dts_time:-0.04 off:0 off_time:0 [I assume that NOPTS means that the timestamp is unknown/unset, but this is strange. After all the mp4 files are properly timestamped. By giving explicit values to dts they are even better timestamped than matroska. It's also strange that decoding timestamps get a value "NOPTS". I'd expect NODTS.]
demuxer+ffmpeg -> ist_index:1 type:audio pkt_pts:0 pkt_pts_time:0 pkt_dts:-1920 pkt_dts_time:-0.04 off:0 off_time:0 [At this point the timestamps agree with what you said that the mp4 demultiplexer output. It's still wrong, of course.]
muxer <- type:audio pkt_pts:-1920 pkt_pts_time:-0.04 pkt_dts:-1920 pkt_dts_time:-0.04 size:505 [Why does the framehash-muxer touch the pts? I don't get it.]
cur_dts is invalid (this is harmless if it occurs once at the start per stream) [Given that this is the third time we have such a warning, I don't think that it is harmless any more.]
demuxer -> ist_index:1 type:audio next_dts:-18667 next_dts_time:-0.018667 next_pts:-18667 next_pts_time:-0.018667 pkt_pts:1024 pkt_pts_time:0.0213333 pkt_dts:-896 pkt_dts_time:-0.0186667 off:0 off_time:0 
demuxer+ffmpeg -> ist_index:1 type:audio pkt_pts:1024 pkt_pts_time:0.0213333 pkt_dts:-896 pkt_dts_time:-0.0186667 off:0 off_time:0 [This is just shifted by 1024 samples compared to the audio packet preceding it. Uninteresting and expected.]
muxer <- type:audio pkt_pts:-896 pkt_pts_time:-0.0186667 pkt_dts:-896 pkt_dts_time:-0.0186667 size:505 [Again just shifted.]
cur_dts is invalid (this is harmless if it occurs once at the start per stream) [Again!? Doesn't sound good.]
demuxer -> ist_index:0 type:video next_dts:NOPTS next_dts_time:NOPTS next_pts:NOPTS next_pts_time:NOPTS pkt_pts:1000 pkt_pts_time:0.04 pkt_dts:0 pkt_dts_time:0 off:0 off_time:0 [The video timestamps look good.]
demuxer+ffmpeg -> ist_index:0 type:video pkt_pts:1000 pkt_pts_time:0.04 pkt_dts:0 pkt_dts_time:0 off:0 off_time:0 [Still looking good.]
muxer <- type:video pkt_pts:1000 pkt_pts_time:0.04 pkt_dts:0 pkt_dts_time:0 size:146554 [Looks still good.]
```
If I just remux the mp4-file to another mp4 file (using `-c copy` of course), the resulting file has the following properties:

- The first frame has cts 40ms. According to the edit list, the presentation of the video track is preceded by 40ms of "nothing" (i.e. undefined); afterwards the presentation shall show the video track from 40ms onwards (i.e. after the 40ms of nothing the first video frame should be shown right away).
- The audio track doesn't have a ctts atom at all, i.e. cts=dts. It does have an edit list which says that the presentation of the track shall begin at once with sample 1920 (i.e. 40ms). This means that the complete first and most of the second packet should not be output. And it means that the A/V offset is 80ms, in line with what the framehash-output has said.
- And now framehash's output for this file:
```
#format: frame checksums
#version: 2
#hash: adler32
#extradata 0,                              53, 3e800dd7
#extradata 1,                               2, 00b400a2
#software: Lavf57.66.102
#tb 0: 1/25000
#media_type 0: video
#codec_id 0: h264
#dimensions 0: 960x540
#sar 0: 1/1
#tb 1: 1/48000
#media_type 1: audio
#codec_id 1: aac
#sample_rate 1: 48000
#channel_layout 1: 3
#channel_layout_name 1: stereo
#stream#, dts,        pts, duration,     size, hash
1,      -1024,      -1024,     1024,      505, ddb905ab, S=1,       10, 002e0005
1,          0,          0,     1024,      505, 64002e73
0,        467,       1467,     1000,   146554, e7ee4547
1,       1024,       1024,     1024,      505, 279e3a3f
1,       2048,       2048,     1024,      505, 7c0b3436
0,       1467,       5467,     1000,    13174, 1119a936
1,       3072,       3072,     1024,      505, a9b22efd
1,       4096,       4096,     1024,      505, d5f137de
0,       2467,       2467,     1000,     1515, 9907eb53
1,       5120,       5120,     1024,      505, 683f3f23
```
Where does this 467 come from? 467/25000=0.01868. Somewhere ffmpeg has probably calculated 40ms-21.333...ms (the latter being the length of one audio packet). So this time my analysis of the file agrees with framehash regarding A/V offset.

If I remux the file created by ffmpeg again, the result looks as follows:

- The first frame has a cts of 40ms. The edit list tells us that the presentation begins with 58ms of nothing and then shows the first frame.
- The audio track has no ctts atom, i.e. cts=dts. But it does have an edit list which says that the presentation shall begin right away at sample 1024 (i.e. after the first audio packet). This means that now we have an A/V offset of 58ms-1024/48000 s which is about 80ms. For some reason ffmpeg used a movie-timescale of 1000 so the offset is not exactly 80ms (the 58ms are in movie-timescale units).
- Apart from rounding issues (instead of 467 we have 450) framehash's output looks the same.

Remuxing this file again doesn't change anything any more. At least ffmpeg is pretty consistent about the A/V offset.

**Comment by mbunkus** [comment]
Thanks for that analysis. I guess this means that I'll have to disregard ffmpeg's calculated timestamps.

Do you know of any other program that can read MP4 files and that I can extract timestamps from? I don't mind modifying the source. I guess I can take a look at the gstreamer framework.

**Comment by mkver** [comment]
No. I use Elecard video format analyzer to parse the files (i.e. tell me what is in the ctts tables etc.), but the actual analysis has always been performed manually.

**Comment by mbunkus** [comment]
I've implemented what I consider to be a fix for the issue. There are new [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) available. I'd appreciate some testing & feedback from your end before closing the issue.

**Comment by mkver** [comment]
It seems to work as expected. But somehow lots of muxers in the mp4 ecosystem seem to get this wrong: I have seen files where the duration of audio and video is nearly the same so that they looked like a completely normal file if it weren't for the offset for the video track derived from ctts and decoding delay. Probably both tracks were meant to start at the same time and either the user was unable to handle his software or said software is buggy.
