### ISSUE TITLE
Audio track not importing

### ISSUE THREAD

**Issue by vertigo220** [mbunkus/mkvtoolnix#1890]
Just ran into an issue with v9.8.0 x64 portable build on Win7 x64 Ultimate. When I add a file, the audio track is not importing. This happens with both the playlist file and the .m2ts file. The file definitely has an audio track, as it not only plays when playing the file, but it also shows up in MediaInfo and BDInfo, and it imports into Xin1Generator and tsMuxeR. For reference, it's the last track (03983.m2ts) on the 'Now You See Me 2' bluray. I used tsMuxeR to mux the streams into 03983.m2ts on the desktop after which it imported into mkvtoolnix properly. This is from a rip using AnyDVD. I tried importing the track from the actual bluray but I get a "The file was not recognized as a supported format (exit code 0)" error, which I also get for the other tracks which import fine from the iso.

**Comment by mbunkus** [comment]
I'll need a sample file for which this happens. Please upload one to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by vertigo220** [comment]
Done, under issue #1890

**Comment by mbunkus** [comment]
Thanks. I'll look into it.

**Comment by mbunkus** [comment]
The current development version of mkvmerge handles that AC-3 track just fine. Therefore I consider this issue fixed.

You can give [the latest pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) a try if you want.
