### ISSUE TITLE
mkvmerge 9.8.0, parameter -i aborts with message boost::too_few_args

### ISSUE THREAD

**Issue by wjoost** [mbunkus/mkvtoolnix#1894]
The command "mkvmerge -i x.mkv" aborts with the message:
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::io::too_few_args> >'
  what():  boost::too_few_args: format-string referred to more arguments than were passed
Aborted (core dumped)
The mkv file has been created by tvheadend. mkvmerge version 9.7.1 works without problems and shows the output:
File 'x.mkv': container: Matroska
Track ID 0: video (MPEG-4p10/AVC/h.264)
Track ID 1: audio (MP2)
Track ID 2: audio (MP2)
Track ID 3: subtitles (S_DVBSUB)
Track ID 4: audio (AC-3/E-AC-3)
Track ID 5: audio (MP2)
Track ID 6: subtitles (S_DVBSUB)
Track ID 7: subtitles (S_DVBSUB)
Global tags: 5 entries

boost library has version 1.63.0-1. Distribution: arch, architecture x86_64.

**Comment by mbunkus** [comment]
Can you please upload the first 10 MB of that file to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server), please? Thanks.

**Comment by wjoost** [comment]
I uploaded the file crash-mkvmerge-i.mkv
