### ISSUE TITLE
Website not up-to-date

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1896]
The website is not up-to-date. See for example the [NEWS.md](https://mkvtoolnix.download/doc/NEWS.md) or the [README](https://mkvtoolnix.download/doc/README). This has happened [before](https://github.com/mbunkus/mkvtoolnix/issues/1862).

**Comment by mbunkus** [comment]
Thanks. Happened due to a bug in my automated build system.
