### ISSUE TITLE
Audio and video not properly interleaved

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1897]
Hello,

I tried to remux a transport stream with errors today. mkvmerge gave A/V asynchronity (including the message warning me about this); therefore I tried to remux to matroska with ffmpeg which worked. Then I wanted to postprocess the file with MKVToolNix which didn't work (I wanted to cut it, but the resulting file had no audio). Simply remuxing the whole file without cutting revealed what was happening: There is an video packet with an obviously wrong timestamp (namely 03:18:39.965 right inbetween packets with timestamp 00:15.373 and 00:15.646) in the input file. This somehow led mkvmerge to write the first few seconds of the output file properly interleaved, then write all the audio and then write all the video (without audio). I have uploaded ffmpeg's file just in case you want to harden mkvmerge against this kind of error. If not, well, no problem.

Greetings
Andi

PS: This happens with earlier versions of mkvmerge, too. It's not a bug introduced in #1893.

**Comment by mbunkus** [comment]
This is nothing that I'm going to fix. Wrong data is wrong data; mkvmerge cannot mind read which timestamp it would actually have to use. Sorry.

**Comment by remuxer32** [comment]
**@mkver** 

Hmmm, interesting case. Maybe I'm wrong, but I suppose that your issue might be similar (or even the same?) like here: https://forum.doom9.org/showthread.php?p=1797463#post1797463 reported by **ndjamena**. In both cases remultiplexing via FFmpeg worked.

**Comment by mbunkus** [comment]
Those two cases have almost certainly nothing to do with each other.
