### ISSUE TITLE
last windows/xp working version

### ISSUE THREAD

**Issue by 17drago** [mbunkus/mkvtoolnix#1899]
Hello, can u tell me the last working version on windows xp?
thanks for ur work

**Comment by mkver** [comment]
I can tell you that version 9.2 (which is not officially supported on Windows XP) runs on it. At least the portable version does (for a short period of time, MKVToolNix didn't run on Windows XP, but #1229 changed this (which does not mean that Windows XP has been reclassified as supported at this time)). Maybe even the portable version of 9.9 does?

**Comment by mbunkus** [comment]
I cannot answer this question as I simply don't know the answer.

**Comment by mkver** [comment]
It appears that the portable 32 bit version runs fine on 32 bit Windows XP. (I haven't tested the installed version and I have only remuxed a few transport streams, but it works. mkvinfo (including the gui) works, too.)

**Comment by morenop3** [comment]
It appers that the 10.0.0 portable 32 bits version (mkvtoolnix-32bit-10.0.0.7z) runs fine on 32 bit Windows XP. 11.0.0 and later does not run.
