### ISSUE TITLE
Mux fails when writing to a gvfs samba share

### ISSUE THREAD

**Issue by thodt-md** [mbunkus/mkvtoolnix#1900]
Using PPA version 9.9.0 on Xubuntu 16.04 (`Linux hostname 4.8.0-39-generic #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`).

When the destination file is on a GVFS samba mountpoint, mkvmerge terminates unexpectedly:
```
user@hostname:/tmp$ /usr/bin/mkvmerge --ui-language en_US --output /var/run/user/1000/gvfs/smb-share:server=remote,share=incoming/temp/vsshort-aac.mkv --language 0:und --default-track 0:yes --language 1:und --default-track 1:yes '(' /tmp/vsshort-aac.mkv ')' --track-order 0:0,0:1
mkvmerge v9.9.0 ('Pick Up') 64bit
'/tmp/vsshort-aac.mkv': Using the demultiplexer for the format 'Matroska'.
'/tmp/vsshort-aac.mkv' track 0: Using the output module for the format 'VfW compatible video'.
'/tmp/vsshort-aac.mkv' track 1: Using the output module for the format 'AAC'.
The file '/var/run/user/1000/gvfs/smb-share:server=remote,share=incoming/temp/vsshort-aac.mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Error: An exception occurred when writing the destination file. The drive may be full. Exception details: reading from/writing to the file error; Operation not supported
```
I can confirm, that the destination drive has enough space, so the problem cannot be due to a full drive. The input used is https://mkvtoolnix.download/samples/vsshort-aac.mkv A few kilobytes are in fact written (5,553 bytes to be exact) before mkvmerge terminates.
On larger files an additional error appears:
```
Warning: kax_reader_c::read(): an unknown exception occurred. This usually indicates a damaged file structure. The file will not be processed further.
```
With local destinations the mux proceeds as usual, even if the source is on a samba share.

Any advice how to solve this?

**Comment by mbunkus** [comment]
mkvmerge requires several basic features in a file system: being able to seek to arbitrary positions including the end of the file, overwriting existing parts of a file, truncating files... It looks like GVFS doesn't provide those basics for Samba shares.

I won't spend any time on this particular issue as I don't consider it to be a bug; your setup is simply not meeting the requirements.

You can try several workarounds, e. g. mounting that Samba share via [`mount.cifs`](https://wiki.samba.org/index.php/Mounting_samba_shares_from_a_unix_client). My basic advice is not to use gvfs with mkvmerge.

**Comment by thodt-md** [comment]
I forgot to mention, that the issue didn't happen with mkvmerge version 9.6.0 on Xubuntu 14.04. Can you at least confirm that there have been changes to the code dealing with file writing since that version, that could have made my setup incompatible?

**Comment by mbunkus** [comment]
Interesting. I cannot think of any change in particular that's changed in the code writing Matroska files, especially not in the part that's active when the error occurs. That code has been stable and mostly unchanged for several years now.

The error also explicitly mentions the error code from the operating system: `Operation not supported`. At that point that can only be: seeking, writing to the end of the file, writing to somewhere in the middle of the file, truncating the file. Looks like gvfs simply doesn't support one of those operations (anymore).

**Comment by thodt-md** [comment]
Downgraded to 9.6.0, the problem persists, this time mkvmerge even crashes with segmentation fault. I guess it has to do something with newer GVFS in 16.04 and/or other libraries mkvmerge uses. Thanks for the help in isolating the issue to my setup.

**Comment by mbunkus** [comment]
A crash in 9.6.0 might be due to the exception not being caught correctly. I seem to remember something in that direction.

Just for the record: mkvmerge uses the standard glibc routines for file access such as `fopen`, `fseek`, `fwrite` etc. No third party library involved apart from glibc, GVfs and FUSE.
