### ISSUE TITLE
--no-global-tags not removing "title" tag

### ISSUE THREAD

**Issue by Skaronator** [mbunkus/mkvtoolnix#1902]
I'm trying to remove the title tag via mkvmerge but it doesn't work.

![image](https://cloud.githubusercontent.com/assets/2886913/23553542/84796718-0021-11e7-98ce-572b91d9c711.png)

Here is my command line:
```
[
'mkvmerge', '-o', 'D:\\Recording\\GoT S01\\Remux\\Game of Thrones\\Season 01\\Game of Thrones - S01E02 - [1080p, AVC].mkv', 
'--default-track', '2', '--audio-tracks', '2, 1', 
'--no-subtitles', '--track-order', '0:0, 0:2, 0:1',
 '--no-track-tags', '--no-global-tags', '--no-attachments', '--no-buttons',
 'D:\\Recording\\GoT S01\\Game of Thrones\\GoT - S01E02.mkv',

'--forced-track', '0', '--default-track', '0', '--language', '0:ger',
 'D:\\Recording\\GoT S01\\Game of Thrones\\GoT - S01E02_de.srt',

'--forced-track', '0', '--language', '0:eng', 
'D:\\Recording\\GoT S01\\Game of Thrones\\GoT - S01E02_en.srt']
```

**Comment by mbunkus** [comment]
The movie name is not stored in tags but in a header field called "title" that you can edit on the "output" tab.

**Comment by Skaronator** [comment]
I didn't said, that I am using the mkvmerge CLI.

Shouldn't `--no-global-tags` remove all unnecessary global tags and `--no-track-tags` remove all unnecessary track tags?

**Comment by mbunkus** [comment]
It should and it does, but it only affects real tags, and like I said, that piece of information is simply not stored in the tags.

The corresponding command line option to remove the title is `--title ""`

**Comment by Skaronator** [comment]
Oh gotcha!

Is there a way to remove it from audio tracks as well?

**Comment by mbunkus** [comment]
Tracks can have names. Use `--track-name... ` for changing those.

**Comment by Skaronator** [comment]
Okay works, thanks!

**Comment by mbunkus** [comment]
You're quite welcome.

**Comment by Skaronator** [comment]
Just one more question: I rotate the eng and ger audio track via `'--track-order', '0:0, 0:2, 0:1'` this change the track id but not the track uid.

**Comment by mbunkus** [comment]
Yeah, so? The UID is supposed to be stable across remuxing so that resources that refer to those UIDs remain valid (e. g. chapters or tags).

**Comment by Skaronator** [comment]
Alright I'll leave it as it is.
