### ISSUE TITLE
audio pause

### ISSUE THREAD

**Issue by chetvitinh** [mbunkus/mkvtoolnix#1903]
I add a 2nd audio track to a karaoke clip, when I delay(in ms second) the audio track it's pause a little(pause after playing the first few second for about a second) when playing, pls findout, thanks
btw, it's happen on all version

**Comment by mbunkus** [comment]
Your bug report is not very clear. Please provide sample files (the files you've use as source files, not the Matroska file created), and upload them to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). I'll also need the command line you've used. If you're using the GUI, then you can let the GUI tell you the corresponding command line via the `Multiplexing` -> `Show command line` menu option.

Thanks.

**Comment by mbunkus** [comment]
Closing due to lack of feedback and generally insufficient level of detail in the original report.
