### ISSUE TITLE
split by duration on PGS subtitles splitting at totally wrong time

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1904]
I have a "sample.sup" PGS subtitle with line #3 ending at 00:00:40,917 and line #4 starting at 00:00:41,626. If cut only "sample.sup" (no other tracks) using --split timecodes:41s it correctly cuts between those two lines. If I cut using --split durations:41s (--split-max-files 2) I would expect the same result but mkvmerge actually cuts between line #9 and #10.

**Comment by mbunkus** [comment]
A file's duration is the difference between its highest timestamp+duration and its lowest timestamp. Therefore `--split timecodes:41s` and `--split duration:41s` aren't equivalent.

In your file the first frame is at 31.352. That's the lowest timestamp. 31.352 + 41 (the duration you want to split after) = 01:12.352. And that's exactly between lines 9 (at 01:09.820) and 10 (01:14.491).

Subtitle-only files do have these little oddities. If you add a video track, then both split points would probably have been the same as the video track usually has a frame at timestamp 0. Therefore the lowest timestamp would have been 0.

**Comment by sneaker2** [comment]
I see. Similar seems to happen to the second part, i.e. its first timecode becomes 0. The information about the time delta [end_of_line_#3]<[beginning_of_line_#4] is lost. So I guess splitting subtitles using mkvmerge is not without pitfalls (yet again).
