### ISSUE TITLE
How join many mp4 files if their track ids are different?

### ISSUE THREAD

**Issue by Vazgen7788** [mbunkus/mkvtoolnix#1905]
I have two mp4 videos. 
mkvmerge -i v1.mp4
```
File 'v1.mp4': container: Matroska
Track ID 0: audio (Opus)
Track ID 1: video (VP8)
```

mkvmerge -i v2.mp4
```
File 'v2.mp4': container: Matroska
Track ID 0: video (VP8)
Track ID 1: audio (Opus)
```
Because track ids are different I can't merge them. 
Can't find the solution. please help .

**Comment by mbunkus** [comment]
Use the option `--append-to` to tell mkvmerge which track to append to which track. See mkvmerge's documentation. And please don't ask such usage questions here; this is a bug tracker. Places such as [Doom9's forum](http://forum.doom9.org/) or the [Matroska mailing lists](https://lists.matroska.org) are more appropriate.

**Comment by Vazgen7788** [comment]
Ok. Thank you very much.
