### ISSUE TITLE
mkvmerge generates unusable HEVC track.

### ISSUE THREAD

**Issue by trumpet205** [mbunkus/mkvtoolnix#1907]
I have a perfectly playable mkv file with HEVC track. When using mkvextract to extract the video track and later remux it, the output file is unplayble.

However if I were to use mkvtoolnix GUI, open the source mkv file directly, and remux it that way, the output file is perfectly playable.

I have uploaded the source mkv file and the unplayble mkv file in folder "issue1907". Please keep in mind I spliced the source file to the first 90 frames to keep the size down.

**Comment by mbunkus** [comment]
Thanks for the report. I'll look into it, but I have to ask for patience as I will be out of town for several weeks.

**Comment by mbunkus** [comment]
My analysis shows that mkvextract is not at fault. Parts of the h.265 data in the sequence parameter set (to be more precise: the "default display window" in the "VUI parameters") are invalid. This confuses mkvmerge as it follows the h.265 spec, which in turn leads to wrong handling of the rest of the SPS data.

ffmpeg has a workaround for this kind of invalid data. I've implemented the same workaround in mkvmerge, and with that workaround in place the provided file can be re-muxed from the extracted elementary stream successfully.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) are up. Build numbers 01443 and higher contain the fix.
