### ISSUE TITLE
Transport stream timestamps

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1908]
Hello,

I have just uploaded a part of a file where mkvmerge produces incorrect timestamps during remuxing, leading to A/V synchronisation issues.
In more detail, the file has a video and an audio track (and a teletext track in which MKVToolNix finds nothing worthwhile; and it also has several programms, but only one of them contain data (MKVToolNix finds the right one, so I don't think that this is the reason for the asynchronity)). The first TS packet corresponding to the first audio packet that gets muxed into matroska (with timestamp 0) begins at offset 67116 and follows:
``
47 4D D5 1A 00 00 01 C0 0F C8 80 80 05 29 DE 61 0F AB FF FD A4 04 88 44 43 55 45 32 34 54 44 33 43 69 B6 DB 00 00 00 00 00 00 00 00 AA AB BA A4 9A EF A5 A4 51 71 C7 5C 6D B7 21 89 F9 A7 96 59 A0 9A 58 62 9A 39 E5 92 79 66 A2 7A 65 96 5A A5 AA 59 6E 89 A1 7D 99 1C 2E 92 71 24 C2 B4 22 C2 84 1B 91 C6 41 12 E6 F5 23 6D CD E2 8B 5B 18 E2 62 89 BC 92 E2 4E A2 51 26 32 DA 71 B8 A4 91 D6 D3 71 5B 13 60 E5 39 27 86 20 D9 AD 55 F1 1B 74 3B 25 4A DA D9 69 28 52 EB 60 A6 0D 4B A2 89 65 1D 26 9B 6D 36 9B 8D BB AD 06 4B 77 AC 4D 66 9D 51 7D 9D C9 9A 15 0F A9 C3 DD A8 28
``
The pts is contained in the PES-header, namely in ``29 DE 61 0F AB``. This stands for 5.227.677.653 after the irrelevant seven bits have been stripped out.
The first TS packet that belongs to the first real keyframe of the video stream ("real" keyframe because mkvmerge has the tendency to find and mux undecodable garbage frames before the first keyframe in the file) begins at 746736 and reads:
``
47 4D D4 38 07 70 9B CC 8F DE FE 75 00 00 01 E0 00 00 84 D0 0D 39 DE 6B FD D7 19 DE 6B 38 F7 80 70 F3 00 00 00 01 09 10 00 00 00 01 67 64 00 28 AD 84 3F FF 90 87 FF F2 10 FF FF FF FF FF FF FF FF 08 7F FF FF FF FF FF FF FF 2C C5 01 E0 11 1F 78 0A 10 10 10 14 00 00 03 00 04 00 00 03 00 CA 50 00 00 00 01 68 EE 37 27 00 00 01 06 00 01 C0 06 01 84 01 09 1B 04 00 00 03 00 00 03 00 00 40 64 08 84 08 02 10 64 11 B2 12 04 0A B5 00 31 44 54 47 31 41 F8 FF 80 00 00 01 41 88 86 C3 C0 47 FF A8 9C 53 89 D0 1F 01 AE 5A 2B 66 34 8E 17 F8 47 5E FF B6 0E C4 7C E5 10 43 2F FF
``
This packet contains three timestamps: Namely PCR data (the video stream is the "master stream" for this program) inside ``9B CC 8F DE FE 75`` that is equivalent to 5.227.749.309+117/300. And pts and dts timestamps inside the PES header, actually inside ``39 DE 6B FD D7 19 DE 6B 38 F7``. This implies a pts of 5.227.871.979 and a dts of 5.227.846.779. Based upon this, this keyframe should get a timestamp of (5.227.871.979-5.227.677.653)/90000Hz=2159ms (rounded). This is what ffmpeg does and what results in A/V synchronity. But the actual timestamp given to this frame is 1839ms. This is close to the timestamp that would be assigend if the dts were used: (5.227.846.779-5.227.677.653)/90.000Hz=1879ms (rounded). The difference is 40ms which looks suspicious given that this is PAL content. If the PCR data were used, one would expect (5.227.749.309-5.227.677.653)/90.000Hz=796ms (rounded). So I don't think that the PCR data has anything to do with it. (is it even used at all? I haven't found it in your code.)
I have also checked some older versions of MKVToolNix. They all behaved the same.

Greetings
Andi

**Comment by mbunkus** [comment]
At the moment mkvmerge doesn't handle the PCR (program clock reference) fields at all.

I'll look into it, but as I've written in another report, I'll be out of town for several weeks, and development will probably not continue during that time.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) are up. Build numbers 01439 and higher contain the fix.

**Comment by mkver** [comment]
Thanks. That was a lot quicker than I expected. It works as intended; I could not find any unwanted side-effects.
