### ISSUE TITLE
Error: Files cannot be appended to themselves

### ISSUE THREAD

**Issue by dfsommer** [mbunkus/mkvtoolnix#1910]
Hello - I'm receiving the following error when attempting to append 2 mkv files together:
Files cannot be appended to themselves. The argument for '--append-to' was invalid.

I've previously used this tool to append mkv's in the past, but while attempting this with a couple of files recently I've received this error. Unfortunately, multiple searches I've conducted haven't produced much for me to look into. Any help would be greatly appreciated!
Thanks in advance!

**Comment by mbunkus** [comment]
Show me a screenshot of the "input" tab where as much content of the files & tracks lists are visible. Also paste the corresponding command line here ("Multiplexing" → "Show command line").

**Comment by dfsommer** [comment]
![mkverror](https://cloud.githubusercontent.com/assets/26489900/24055822/f705c8b6-0b17-11e7-924d-e3ef107cff14.png)

`"C:/Program Files/MKVToolNix\mkvmerge.exe" --ui-language en --output ^"A:\shares\Holding Folder\Ben_Hur_50th_Anniversary_UCE_t01 ^(1^).mkv^" --language 0:eng --language 1:eng --track-name ^"1:Surround 5.1^" --default-track 1:yes --language 2:eng --track-name ^"2:Surround 5.1^" --language 3:eng --track-name 3:Stereo --language 4:eng --track-name 4:Stereo --language 5:eng ^"^(^" ^"A:\shares\Holding Folder\Ben_Hur_50th_Anniversary_UCE_t01.mkv^" ^"^)^" + ^"^(^" ^"A:\shares\Holding Folder\Ben Hur Disc 2.mkv^" ^"^)^" --title ^"Ben Hur: 50th Anniversary UCE^" --track-order 0:0,0:1,0:2,0:3,0:4,0:5 --append-to 1:0:0:0,1:1:0:1,1:2:0:2,1:3:0:3,1:4:0:4,1:5:1:4,1:6:0:5,1:7:1:6,1:8:1:7,1:9:1:8,1:10:1:9,1:11:1:10,1:12:1:11,1:13:1:12,1:14:1:13,1:15:1:14,1:16:1:15,1:17:1:16,1:18:1:17,1:19:1:18,1:20:1:19,1:21:1:20,1:22:1:21,1:23:1:22,1:24:1:23,1:25:1:24,1:26:1:25,1:27:1:26,1:28:1:27`

**Comment by mbunkus** [comment]
The second file contains at least one more audio track than the first file. Check the "source file" column and you should realize where that's the case. The GUI is a bit dumb about such situations — it simply assigns the superfluous tracks from the second file to the last audio track from the first file, creating the situation you're in.

You can fix this by deselecting the superfluous audio tracks from file two where more than one audio track from file two is a child node of an audio track of file one.

The same applies to the subtitle tracks; in fact, it's worse here as there seem to be a ton of subtitle tracks in file two but only one in file one.

mkvmerge doesn't support such situation. It requires that each appended track in file two has a corresponding track in file one.
