### ISSUE TITLE
mkvmerge appends old input extension into output's filename

### ISSUE THREAD

**Issue by rhazor** [mbunkus/mkvtoolnix#1911]
This is a snippet of my batch file:

`for /r %%i in (*.%format%) do call mkvmerge -o %%i.mkv %%i`

Everything works, problem is that output file ends up with two extensions.
E.g. if input is `file.mp4` then output ends up being `file.mp4.mkv` which is wrong and should be `file.mkv`. I don't know why it snatches and appends input extension into a filename.

**Comment by mbunkus** [comment]
mkvmerge does NOT add anything to the output file name you're giving it; it uses the output file name argument verbatim. If you end up with multiple extensions, then that's the result of your batch snippet.
