### ISSUE TITLE
please make documentation generation optional at build time

### ISSUE THREAD

**Issue by rofl0r** [mbunkus/mkvtoolnix#1912]
the docbook stuff is a very heavy build time dependency, and a user might only be interested into building the tools. i'd really appreciate if one could just --disable-docs and lessen the burden on people wanting to build their tools from source.

**Comment by mbunkus** [comment]
I can understand that wish, but I don't really want to spend the time here. Patches would be welcome, though.

**Comment by mbunkus** [comment]
I've decided to close this as WONTFIX. If you're only interested in building the programs, then just execute `rake apps` (and for installation `rake install:programs install:shared`). That way no parts of the documentation will be built.

**Comment by rofl0r** [comment]
wait, isn't rake some ruby on rails stuff ? i.e. it would mean trading off the burden for building/installing the docbook stuff for ruby ?
i was more concerned about the cmake build.
usually documentation is (or at least should) be built as part of the make dist process when the maintainer creates a tarball for release.
so the generated documentation ends up in the release, and the user doesn't have to care about having all those tools and templates.

**Comment by mbunkus** [comment]
rake is a general purpose build system written in Ruby. It is used by MKVToolNix and Rails, among others,. It is certainly not Rails-specific.

MKVToolNix does not use cmake.

> so the generated documentation ends up in the release, and the user doesn't have to care about having all those tools and templates.

Sure, might be useful, but like I've said I have no intention of spending time on this.

**Comment by rofl0r** [comment]
> MKVToolNix does not use cmake.

i corrected this after a minute to "autoconf". see above.

> rake is a general purpose build system written in Ruby. It is used by MKVToolNix and Rails, among others

i hope not many others, because i certainly don't want yet another scripting language dependency in the build chain. it's bad enough that ppl use perl and python for that purpose, instead of keeping the dependencies to the bare minimum.

> Sure, might be useful, but like I've said I have no intention of spending time on this.

so you'd accept a PR ?

**Comment by mbunkus** [comment]
I'd accept a PR that introduces such an option to `configure`. It would have to disable all corresponding `configure` checks and all corresponding build targets in the `Rakefile`.

**Comment by rofl0r** [comment]
the autoconf build system works without invoking rake/ruby, right ?

**Comment by mbunkus** [comment]
No. The MKVToolNix build process consists of two stages:

1. The `configure` run. This is a standard, `autoconf`-based `configure` script.
2. The actual build process driven by `rake` with a self-made set of build rules contained in `Rakefile` (`rake`'s equivalent of `Makefile` for `make`).

Both stages have to be adjusted if building the documentation is to be made optional.
