### ISSUE TITLE
Sync Function on Chapter Files

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#1915]
Hello, **mkvtoolnix** is very useful and your efforts are respected and appreciated.  The `--sync` function does not adjust chapter time codes as expected. The command is accepted; however, no adjustment occurs and no error is given.

_An example, using the following chapter excerpt..._
$ cat example.chapters
>CHAPTER01=00:00:00.000
CHAPTER01NAME=Chapter 01
CHAPTER02=00:02:06.235
CHAPTER02NAME=Chapter 02
CHAPTER03=00:05:34.435
CHAPTER03NAME=Chapter 03
CHAPTER04=00:08:34.668
CHAPTER04NAME=Chapter 04
[...]

This particular example had an audio/video desync of 1.380s and began with 8.975s of pure black frames and audio silence for 2.340s; so, a `--sync` of -7595 for the video track and `--sync` -2340 for the audio tracks would synchronize the audio and video. Preferably, chapters should be adjusted by -7595 as well...

_Command line is accepted and processes without error..._
`$ mkvmerge -o "remuxed.mkv" --no-chapters -a 1,4 -y 0:-7595 -y 1:-2340 -y 4:-2340 "example.mkv" -y 0:-7595 --chapters "example.chapters"`
>[...]
The file 'remuxed.mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Muxing took 2 minutes 4 seconds.
[...]

As expected, video was cut to nearest ref frame and audio is appropriately offset (within A/V sync tolerance, per [ITU-R BT.1359](https://www.itu.int/rec/R-REC-BT.1359/en)); however, chapter times remain unchanged...

`$ mediainfo remuxed.mkv`
>[...]
Audio # 1
Delay relative to video                  : 15 ms
[...]
Audio # 2
Delay relative to video                  : 15 ms
[...]
Menu
00:00:00.000                             : en:Chapter 01
00:02:06.235                             : en:Chapter 02
00:05:34.435                             : en:Chapter 03
00:08:34.668                             : en:Chapter 04
[...]

Can chapters be included in the use of the `--sync` function? Please advise, thank you.

**Comment by mbunkus** [comment]
Chapter files are not normal input files, and especially they're not tracks. Options such as `--sync` only work on tracks.

If you need to adjust all chapter timestamps, then I suggest you use the GUI's chapter editor to do so. It has a function for adjusting all timestamps (right-click on a chapter in the tree, select "additional modifications").

**Comment by optimiz** [comment]
Will do, thanks for the quick response. (I've actually never used the GUI, so I was unaware it had that function, sorry for the trouble.)
