### ISSUE TITLE
Can I use mkvmerge on the fly?

### ISSUE THREAD

**Issue by czarina** [mbunkus/mkvtoolnix#1918]
Hi,

I am livestreaming video with a Raspberry Pi camera, and I need to add timestamps into it. I'm currently using raspivid to generate the video and timestamp files, and mkvmerge to merge them. 

Because I'm livestreaming, I need to add timestamps to the video on-the-fly. I am not using pre-recorded video. I want to pass the video output of raspivid to mkvmerge as a FIFO pipe or as stdin. I have read this is not possible: https://github.com/mbunkus/mkvtoolnix/wiki/Use-FIFOs-stdin-stdout

Is it possible for me to use mkvmerge for this problem? Or is there another library you recommend? Thanks!

**Comment by mbunkus** [comment]
No.

I cannot give you a recommendation as I've never done this myself. Maybe ffmpeg can do that, but that's just a guess.
