### ISSUE TITLE
Sort alphabetically when column is clicked in MKVToolnix GUI

### ISSUE THREAD

**Issue by grenzor** [mbunkus/mkvtoolnix#1919]
Currently it looks like clicking on a column doesn't do anything in MKVToolnix GUI . Is it possible so users can sort by columns i.e. Codec, Type, Language etc. when clicked will sort by alphabetical ascending or descending order. Maybe something like: 1st click: sort by asc, 2nd click: sort by desc, 3rd click: go back to original order as they were before. Would be very useful and convenient!

**Comment by mbunkus** [comment]
Both views are tree views, and the relationship between the elements (which element occurs before which other element, and which element is a child of which other element) signals important information about how the entries will be processed. Sorting them after other columns wouldn't make much sense if any at all and lead to much confusion. I'm not willing to implement that.

**Comment by grenzor** [comment]
I'm not sure if we're talking about the same things:

I'm suggesting sorting within a column e.g.

Codec:
FLAC
AC3
FLAC

will sort alphabetically to 

Codec:
AC3
FLAC
FLAC

**Comment by mbunkus** [comment]
I know what you mean. However, the order in which tracks are laid out in the output file corresponds with the order the tracks are shown in the GUI. Therefore sorting by any one of those columns would either affect the track order (which wouldn't make much sense), or it would suddenly cause the display not to correspond with the track order in the file anymore at all, and dragging & dropping would lose all meaning.

It'd be much more confusing than it would help. Therefore, like I said: no.
