### ISSUE TITLE
Preferences for "Warnings" do not save

### ISSUE THREAD

**Issue by J-Wo** [mbunkus/mkvtoolnix#1920]
In MKVTooNix GUI v10.0.0, the Preferences under "Warnings" do not save.  For example, if I uncheck the warning for "Warn before closing modified files" and press OK, the next time I launch MKVToolNix GUI this warning is checked off again.

On a similar note, why does MKVToolNix GUI think that a file is modified if I simply open it and then try and close the program?  That's the main reason I want to uncheck this warning, and have the program remember this setting.

**Comment by mbunkus** [comment]
I cannot reproduce such a problem. This sounds like MKVToolNix GUI doesn't have write access to the preferences file. See [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/Location-of-settings,-job-queue,-cache-folder) for information where they're stored.

A typical case is using the portable version and placing it in `c:\program files\...`. Don't do that.

**Comment by mbunkus** [comment]
Like I've said: I've verified that modifying that setting is saved properly both with the installed version as well as the portable version as long as the program has write access to the location of the `mkvtoolnix-gui.ini` file. You should make sure that this is the case for the location where you've placed MKVToolNix.
