### ISSUE TITLE
DTS-HDMA to DTS Core

### ISSUE THREAD

**Issue by Genie01** [mbunkus/mkvtoolnix#1921]
Hello, Need a Tutorial to Extract DTS Core from DTS-HDMA
Any Programm Or Method Do That. I See Option in MKVToolNix "Reduced to Core"
![reduce dts core](https://cloud.githubusercontent.com/assets/26716106/24360785/3b26deaa-1300-11e7-9c9d-4f0b9de4f9c7.jpg)

What You Mean. Thanks

**Comment by remuxer32** [comment]
Hello.

It's very simple. First, you need to have a file that contains a DTS-HD Master audio track. Then you have to select that track and check the checkbox "**Reduce to core**". See my screenshot, please: 

![dts core](https://cloud.githubusercontent.com/assets/10992208/24363669/d288d3e2-1310-11e7-9c26-94b20d69e522.png)

**Comment by mbunkus** [comment]
This is a bug tracker, not a support forum for general help requests.
