### ISSUE TITLE
MKVCleaver 0.6.0.8 issue

### ISSUE THREAD

**Issue by baraka17360** [mbunkus/mkvtoolnix#1922]
MKVCleaver 0.6.0.8 is crashing (i.e. cannot extract subtitles) when updated MKVtoolnix to 10.0.0 64x. MKVExtract GUI works fine

**Comment by mbunkus** [comment]
This is a bug in mkvcleaver. Report it there.

**Comment by mbunkus** [comment]
See also [here](https://forum.doom9.org/showthread.php?p=1802028#post1802028).
