### ISSUE TITLE
Problem remuxing a mkv(hevc) file

### ISSUE THREAD

**Issue by Selur** [mbunkus/mkvtoolnix#1924]
I got a file (TEST-CLIP.mkv -> https://drive.google.com/drive/folders/0B_WxUS1XGCPAUTlILW54VThMTFU?usp=sharing)
from which I extract the video stream using:
`mkvextract tracks "C:\Users\Selur\Desktop\TEST-CLIP.mkv" 0:"H:\Temp\test_05_31_20_5510_01.265"`
then I use
`mkvmerge --ui-language en -o "C:\Users\Selur\Desktop\test.mkv" --global-tags "H:\Temp\test_05_31_20_5510__02.xml" -d 0 --default-track 0:yes --default-duration 0:24000/1001fps --aspect-ratio-factor 0:1/1 --no-chapters --compression -1:none --forced-track 0:yes --no-audio --no-subtitles "H:\Temp\test_05_31_20_5510_01.265"`
to remux the video stream into a new container. 
(using mkvmerge and mkvextract from mkvtoolnix 10.0)
Problem is the output isn't playable in any media player. (input plays fine)

Any help is appreciated. Thanks.

**Comment by mkver** [comment]
Your file contains the encoder information (where x265 stores its version and encoding settings) in the codec private of the H.265 track. It is therefore rather long, namely 947 Bytes. I don't think that this is the right place for it (i.e. your original file is maybe against specs even if it plays fine with media players). At least mkvextract can't handle this: Extracting the H.265 stream with mkvextract gives an elementary track that doesn't contain the encoding parameters at all. ffmpeg can extract the stream and include the encoding parameters, but if I remux this elementary stream with MKVToolNix, I get an unplayable file again.
Just for the record: ffmpeg's error message upon (not) playing the files is: "Overread SPS by 8 bit" and "SPS 0 does not exist".

**Comment by Selur** [comment]
Since mediainfo reports:
`Writing library                          : Lavf57.25.100 / Lavf57.25.100`
my guess is that the file was created with Avidemux. (Background: user reported an issue with Hybrid creating broken output which I then traced to mkvtoolnix. I only use mkvmerge to multiplex to mkv and either ffmpeg or mkvextract to extract from mkv.)
Funny thing is, when I:
extract the .265 stream with mkvextract the output plays fine in MPC-HC
When I remux that stream to mp4 using MP4Box the output plays fine.
When I remux the stream to mkv using mkv merge and the above call the output isn't playable.

**Comment by mbunkus** [comment]
Thanks. I'll look into it, but I cannot give you an ETA.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include the fix are up.
