### ISSUE TITLE
mkvtoolnix-9.8.0 and newer ignores user-specified CXXFLAGS

### ISSUE THREAD

**Issue by rathann** [mbunkus/mkvtoolnix#1925]
It looks like d7b691b6f53a855955efd6dc98b654746319134f accidentally removed `#{c(:USER_CXXFLAGS)}"` from cxxflags. Please add it back.

**Comment by mbunkus** [comment]
Oops… Sorry for that. I'll fix it.

**Comment by rathann** [comment]
No problem. I only noticed because I looked at the build log when building 10.0.0 and noticed that Fedora build system default CXXFLAGS weren't appearing in the log. Thanks for the lightning-fast fix.

**Comment by mbunkus** [comment]
Thanks for reporting it, and you're welcome.
