### ISSUE TITLE
Add muxing ability "sbtl:tx3g" subtitle format to mkvtoolnix

### ISSUE THREAD

**Issue by Endoro** [mbunkus/mkvtoolnix#1928]
Hi mosu,
do you see any possibility to mux the "sbtl:tx3g" subtitle format to mkv files? 
I added a file with three normal and one forced subtitle track(s) of these subs to your ftp server.
The file name is '20170331 original.mp4'.

Thanks for your attention and time,

Regards, Endoro

**Comment by mbunkus** [comment]
I've looked into this in the past, but I decided back then not to spend time on it. I don't think I'll reconsider. Sorry.
