### ISSUE TITLE
mkvpropedit --delete language sets language to English

### ISSUE THREAD

**Issue by ptr727** [mbunkus/mkvtoolnix#1929]
[Sample.zip](https://github.com/mbunkus/mkvtoolnix/files/891467/Sample.zip)
When I delete a language attribute from a track using mkvpropedit, the language is not deleted, but changed to eng.
If I delete the language attribute from a track with no language, the language is changed to eng.

```
mkvmerge.exe --identify "AAC Surround.mkv" --identification-format json
{
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 17,
      "date_local": "2009-05-16T19:49:36-07:00",
      "date_utc": "2009-05-17T02:49:36Z",
      "duration": 71655000000,
      "is_providing_timecodes": true,
      "muxing_application": "libebml v0.7.7 + libmatroska v0.8.1",
      "segment_uid": "8939b5689274a3c192fe33e2e88b08c3",
      "writing_application": "mkvmerge v2.1.0 ('Another Place To Fall') built on Aug 19 2007 13:40:07"
    },
    "recognized": true,
    "supported": true,
    "type": "Matroska"
  },
  "errors": [],
  "file_name": "..\\..\\Plex\\Samples\\AAC Surround.mkv",
  "global_tags": [],
  "identification_format_version": 6,
  "track_tags": [],
  "tracks": [
    {
      "codec": "MPEG-4p10/AVC/h.264",
      "id": 0,
      "properties": {
        "codec_id": "V_MPEG4/ISO/AVC",
        "codec_private_data": "0164001effe100176764001eac34ec0b435a10000007d0000176a8f162d38001000468eebcb0",
        "codec_private_length": 38,
        "default_duration": 41708333,
        "default_track": true,
        "display_dimensions": "720x416",
        "enabled_track": true,
        "forced_track": false,
        "language": "und",
        "minimum_timestamp": 0,
        "number": 1,
        "packetizer": "mpeg4_p10_video",
        "pixel_dimensions": "720x416",
        "uid": 672299673
      },
      "type": "video"
    },
    {
      "codec": "AAC",
      "id": 1,
      "properties": {
        "audio_channels": 6,
        "audio_sampling_frequency": 48000,
        "codec_id": "A_AAC",
        "codec_private_data": "11b04a554e4b0010000041766964",
        "codec_private_length": 14,
        "default_duration": 21333333,
        "default_track": true,
        "enabled_track": true,
        "forced_track": false,
        "language": "und",
        "minimum_timestamp": 0,
        "number": 2,
        "uid": 150421934
      },
      "type": "audio"
    }
  ],
  "warnings": []
}
```

```
mkvpropedit.exe  "AAC Surround.mkv" --edit track:@1 --delete language 
The file is being analyzed.
The changes are written to the file.
Done.
```

```
mkvmerge.exe --identify "AAC Surround.mkv" --identification-format json
{
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 17,
      "date_local": "2009-05-16T19:49:36-07:00",
      "date_utc": "2009-05-17T02:49:36Z",
      "duration": 71655000000,
      "is_providing_timecodes": true,
      "muxing_application": "libebml v0.7.7 + libmatroska v0.8.1",
      "segment_uid": "8939b5689274a3c192fe33e2e88b08c3",
      "writing_application": "mkvmerge v2.1.0 ('Another Place To Fall') built on Aug 19 2007 13:40:07"
    },
    "recognized": true,
    "supported": true,
    "type": "Matroska"
  },
  "errors": [],
  "file_name": "..\\..\\Plex\\Samples\\AAC Surround.mkv",
  "global_tags": [],
  "identification_format_version": 6,
  "track_tags": [],
  "tracks": [
    {
      "codec": "MPEG-4p10/AVC/h.264",
      "id": 0,
      "properties": {
        "codec_id": "V_MPEG4/ISO/AVC",
        "codec_private_data": "0164001effe100176764001eac34ec0b435a10000007d0000176a8f162d38001000468eebcb0",
        "codec_private_length": 38,
        "default_duration": 41708333,
        "default_track": true,
        "display_dimensions": "720x416",
        "enabled_track": true,
        "forced_track": false,
        "language": "eng",
        "minimum_timestamp": 0,
        "number": 1,
        "packetizer": "mpeg4_p10_video",
        "pixel_dimensions": "720x416",
        "uid": 672299673
      },
      "type": "video"
    },
    {
      "codec": "AAC",
      "id": 1,
      "properties": {
        "audio_channels": 6,
        "audio_sampling_frequency": 48000,
        "codec_id": "A_AAC",
        "codec_private_data": "11b04a554e4b0010000041766964",
        "codec_private_length": 14,
        "default_duration": 21333333,
        "default_track": true,
        "enabled_track": true,
        "forced_track": false,
        "language": "und",
        "minimum_timestamp": 0,
        "number": 2,
        "uid": 150421934
      },
      "type": "audio"
    }
  ],
  "warnings": []
}
```

This is using version 10.0 on Windows 10 from PowerShell.
Sample file attached, (before any attributes are deleted)

**Comment by mkver** [comment]
This is not a bug. The reason for this behaviour is that the default value for the language attribute is English and this means that a track which doesn't contain a language attribute is English by definition. If you want a track with an undefined language, you have to specify it as undefined.
[Here](https://github.com/mbunkus/mkvtoolnix/wiki/Elements-not-showing-up-in-output-file) you can find more on this.

**Comment by mbunkus** [comment]
@mkver has already said everything I would have said. The only thing left to add is that there are two relevant language codes you can use:

* `und` for "undefined" where the track does have lingual content but the language isn't known, or it's nonsensical
* `zxx` which stands for "no linguistic content", e.g. for video tracks

**Comment by ptr727** [comment]
Hi, thank you for the reply, but, I feel you are mixing the ability to edit with the interpretation of data.

I understand that there is a default convention, but I feel you should allow me to edit editable content regardless of how the reading application will treat defaults.

I also feel the current implementation is not consistent, again something that can be remedied separating editing of content, from interpretation of content.

E.g. in v10, that should default to eng on missing language:

I can mkvmerge an existing MKV that has no language defined and the output language would be undefined in JSON, not English. This is counter to your statement that a missing language would be treated as english, see the JSON output, language : und. Btw, I am doing all this to remedy tracks with no language to make Plex happy, for it interprets a missing language as undefined, not English.

I am not able to set a language as undefined, when I call set language=specify, I get an error that und is not an ISO language code. I.e. no way to get a player to follow a default, once a language is set, it can never be unset, I have to remux, because mkvmerge does not enforce this convention.

When I JSON print a subtitle track with no language, the language tag is completely missing, unlike audio or video that sets the tag to und. (this causes problems in my code that expects the language tag to be present)

I appreciate that you want to enforce standards, but with the mixing of intent and editor is problematic.

**Comment by mbunkus** [comment]
> I am not able to set a language as undefined, when I call set language=und, I get an error that und is not an ISO language code.

I'm pretty sure you're doing something wrong in your command line. Here's how it should look like:

```
[0 mosu@sweet-chili ~/prog/video/data] mkvmerge -J v.mkv|grep -i language
        "language": "ger",
        "language": "ger",
[0 mosu@sweet-chili ~/prog/video/data] mkvpropedit v.mkv --edit track:1 --set language=und
The file is being analyzed.
The changes are written to the file.
Done.
[0 mosu@sweet-chili ~/prog/video/data] mkvmerge -J v.mkv|grep -i language
        "language": "und",
        "language": "ger",
[0 mosu@sweet-chili ~/prog/video/data]
```

> When I JSON print a subtitle track with no language, the language tag is completely missing

I strongly doubt that. Do you have an example file for which `mkvmerge -J filename.mkv` does not output a `language` property for a track? If so, I'd like to take a look at it. Please upload such a file to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server).

The rest of your comment doesn't convince me to, though. Directly editing stuff in a file is powerful and dangerous at the same time. The purpose of mkvpropedit is to be a powerful tool, not a fool-proof one, but that also means that the user has to know what he/she is doing.

**Comment by ptr727** [comment]
You are right, setting the language to und does delete the tag, I looked at my test script, I incorrectly used language=unk instead of und, I can now set language as und and mediainfo will show the language tag as missing and output to json will show it as und.. 

Here is an example of a file with no language tag being emitted in JSON for a subtitle track:
I cannot access anything other than 80, 443, and 21 from my office network, so no SFTP upload to 2222 until I get home, here is a OneDrive link for now: https://1drv.ms/u/s!AqeqhT0NczrNhcMXSUFVNPEIxrVb8w
```
.\MKVToolNix\mkvmerge.exe --identify "..\..\Plex\Samples\Foo.mkv" --identification-format json
...
 {
   "codec": "SubRip/SRT",
   "id": 2,
   "properties": {
     "codec_id": "S_TEXT/UTF8",
     "codec_private_length": 0,
     "default_track": false,
     "enabled_track": true,
     "forced_track": false,
     "number": 3,
     "text_subtitles": true,
     "uid": 2864556437
   },
   "type": "subtitles"
 }
...
```

My last thoughts on editor vs. interpreter vs. enforcer of standards, then I'll leave it alone :)
In my mind an editor should let me add, change, and delete values, while maintaining core data integrity, an interpreter should interpret the value as set, or default to values for any not defined, or fail if the structure is undefined. It is noble to attempt to say und = English, but that is not reality, e.g. Plex treats a missing language tag as undefined, the Plex community has long asked for und to be treated as the default UI language, or a predefined language. So und = English is probably not a good choice as there is no correlation between no language tag set and assuming it is English.

**Comment by mbunkus** [comment]
Thanks for the file. This looks like a bug — mkvmerge should always output the language. I'll look into it.

> It is noble to attempt to say und = English

You misunderstood. No one is trying to define that. The semantics are:

* If the language element is present and to to `eng`, or if the language element is absent: semantically the track language is English
* In any other case the track language is whatever the language element is set to, and that includes the code `und` = "undetermined".

The absence of the element is not `und` = undetermined, deleting the element does not lead to "undetermined" either.

**Comment by mbunkus** [comment]
Addition: if present, the element must be set to a valid ISO 639-2 language code. Therefore: the situation "element present but set to an empty string" would be a violation of the specification.

**Comment by ptr727** [comment]
Thanks.

**Comment by mbunkus** [comment]
I've downloaded the file. You can delete it.

My hunch was correct. That subtitle track does contain a "language" element, but it is set to an empty string. Like I said, that is a violation of the specs.

However, mkvmerge's behavior isn't exactly how I would like it to be. It should treat such a situation the same as if the element weren't present in the first place and output `eng` as the language attribute. I'll fix that.

**Comment by mbunkus** [comment]
Or maybe treat it as `und`, which would make more sense semantically, I guess.

**Comment by ptr727** [comment]
und please, same behavior as with audio and video tracks, else I would have no way of knowing if it is undefined or really english.

**Comment by mbunkus** [comment]
I've already decided to use `und`, yes.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) are available that include the fixes.
