### ISSUE TITLE
mkvtoolnix-gui.exe too many subtitles, remux , out of sync

### ISSUE THREAD

**Issue by k21689** [mbunkus/mkvtoolnix#1934]
After searching this issue, found nothing.
Use mkvtoolnix-gui.exe to remux flies
If I put too many subtitles(10+ in my case) in the re-muxing, all subtitles are out of sync.
Reducing number of subtitles solves the problem.

Just a FYI and possible solution, probably not worth the trouble/effort to trace the bugs.

**Comment by mbunkus** [comment]
If you want me to look into this, I'll need access to _all_ of the source files used in the case when the desync occurs. Please upload those files somewhere, e.g. to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by optimiz** [comment]
I'm fairly certain what you describe is _not_ an **MKV** or **mkvtoolnix** bug.  Instead, it's a media player or device (access/read/latency) issue.  In other words, your media player must be able to read your file (with many subtitles or subtracks) from the storage medium, parse and display within an appropriate access time/latency. If not, common symptoms are dropped frames and/or audio/subtitle desync.

For example, the following file has 11 subtitle tracks (7 SRT and 4 VOBSUB) and requires an overall bitrate of 1,305 kb/s; it easily plays with video, audio and subtitles in sync (and no dropped frames).

`$ mkvmerge -I example.mkv`
>File 'example.mkv': container: Matroska [container_type:17 date_local:2017-04-14T18\c15\c04-07\c00 date_utc:2017-04-15T01\c15\c04Z duration:8951440000000 is_providing_timecodes:1 muxing_application:libebml\sv1.3.3\s+\slibmatroska\sv1.4.4 segment_uid:5d3f4423aeaa6ce417dccabb8a175bbe writing_application:mkvmerge\sv9.2.0\s('Photograph')\s64bit]
Track ID 0: video (MPEG-4p2) [codec_id:V_MS/VFW/FOURCC codec_private_data: [...] codec_private_length:40 default_duration:40000000 default_track:1 display_dimensions:576x320 enabled_track:1 forced_track:0 language:und minimum_timestamp:0 number:1 pixel_dimensions:576x320 uid:2506305099786472619]
Track ID 1: audio (AC-3/E-AC-3) [audio_channels:2 audio_sampling_frequency:48000 codec_id:A_AC3 codec_private_length:0 default_duration:32000000 default_track:1 enabled_track:1 forced_track:0 language:ger minimum_timestamp:80000000 number:2 uid:6567204789147583251]
Track ID 2: subtitles (SubRip/SRT) [codec_id:S_TEXT/UTF8 codec_private_length:0 default_track:1 enabled_track:1 forced_track:0 language:eng number:3 text_subtitles:1 uid:11266174902962965263]
Track ID 3: subtitles (SubRip/SRT) [codec_id:S_TEXT/UTF8 codec_private_length:0 default_track:0 enabled_track:1 forced_track:0 language:cze number:4 text_subtitles:1 uid:6991059662365323957]
Track ID 4: subtitles (SubRip/SRT) [codec_id:S_TEXT/UTF8 codec_private_length:0 default_track:0 enabled_track:1 forced_track:0 language:dut number:5 text_subtitles:1 uid:17807041041863566783]
Track ID 5: subtitles (SubRip/SRT) [codec_id:S_TEXT/UTF8 codec_private_length:0 default_track:0 enabled_track:1 forced_track:0 language:gre number:6 text_subtitles:1 uid:11582464355382113699]
Track ID 6: subtitles (SubRip/SRT) [codec_id:S_TEXT/UTF8 codec_private_length:0 default_track:0 enabled_track:1 forced_track:0 language:pol number:7 text_subtitles:1 uid:6701161010316428100]
Track ID 7: subtitles (SubRip/SRT) [codec_id:S_TEXT/UTF8 codec_private_length:0 default_track:0 enabled_track:1 forced_track:0 language:spa number:8 text_subtitles:1 uid:15830490324286783749]
Track ID 8: subtitles (SubRip/SRT) [codec_id:S_TEXT/UTF8 codec_private_length:0 default_track:0 enabled_track:1 forced_track:0 language:heb number:9 text_subtitles:1 uid:16977743845516635373]
Track ID 9: subtitles (VobSub) [codec_id:S_VOBSUB codec_private_data: [...] codec_private_length:348 content_encoding_algorithms:0 default_track:0 enabled_track:1 forced_track:0 language:dan number:10 uid:18143899129601774960]
Track ID 10: subtitles (VobSub) [codec_id:S_VOBSUB codec_private_data: [...] codec_private_length:348 content_encoding_algorithms:0 default_track:0 enabled_track:1 forced_track:0 language:swe number:11 uid:9464656182907732734]
Track ID 11: subtitles (VobSub) [codec_id:S_VOBSUB codec_private_data: [...]codec_private_length:348 content_encoding_algorithms:0 default_track:0 enabled_track:1 forced_track:0 language:nor number:12 uid:1047501911267995702]
Track ID 12: subtitles (VobSub) [codec_id:S_VOBSUB codec_private_data: [...] codec_private_length:348 content_encoding_algorithms:0 default_track:0 enabled_track:1 forced_track:0 language:fin number:13 uid:4556059300842547677]

You can test your particular environment by playing a file similar to the example above: with light access/parse requirements.  If it plays in sync, you have your diagnosis.  Alternatively, increase your media players' read cache to exceed the drive access and parse time on your particular equipment: whether you catch up to realtime and start desyncing again, or not -- either way, you have your diagnosis.

**Comment by k21689** [comment]
Yes, I was wrong to jump to the wrong conclusion in a rush. Since it was a 10+GB file, I deleted it and moved on. I tried to duplicate the errors with other smaller files and with my argument. I failed. This case was a false alarm. I am sorry for your trouble.
