### ISSUE TITLE
when use mkvmerge split the 1080i video, it change the fps from 25 to 50, how I can keep the original fps?

### ISSUE THREAD

**Issue by pennypf** [mbunkus/mkvtoolnix#1935]
when I split a 1080i file using mkvmerge based on file size, It changed the video fps from 25 to 50, I what to know how can I keep the original value?  
First, I check the input video with ffmpeg， the following info can see:
Input #0, mpegts, from 'infile.ts':
  Duration: 00:13:12.36, start: 2.040000, bitrate: 7684 kb/s
  Program 1
    Stream #0:0[0x810]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x814](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 256 kb/s

Using the cmd line to split: mkvmerge  -o split%03d.ts --split 100m infile.ts

After splitting, I check the split files info with ffmpeg:
Input #0, matroska,webm, from 'split001.ts':
  Metadata:
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2017-04-08 08:32:49
  Duration: 00:03:52.01, start: 0.000000, bitrate: 7258 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      BPS             : 6998893
      BPS-eng         : 6998893
      DURATION        : 00:03:52.000000000
      DURATION-eng    : 00:03:52.000000000
      NUMBER_OF_FRAMES: 11600
      NUMBER_OF_FRAMES-eng: 11600
      NUMBER_OF_BYTES : 202967910
      NUMBER_OF_BYTES-eng: 202967910
      _STATISTICS_WRITING_APP: mkvmerge v9.5.0 ('Quiet Fire') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.5.0 ('Quiet Fire') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-04-08 08:32:49
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-04-08 08:32:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: mp2, 48000 Hz, stereo, s16p, 256 kb/s (default)
    Metadata:
      BPS             : 256000
      BPS-eng         : 256000
      DURATION        : 00:03:52.008000000
      DURATION-eng    : 00:03:52.008000000
      NUMBER_OF_FRAMES: 9667
      NUMBER_OF_FRAMES-eng: 9667
      NUMBER_OF_BYTES : 7424256
      NUMBER_OF_BYTES-eng: 7424256
      _STATISTICS_WRITING_APP: mkvmerge v9.5.0 ('Quiet Fire') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.5.0 ('Quiet Fire') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-04-08 08:32:49
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-04-08 08:32:49
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

I just want to split the file with mkvmerge, but change nothing of the video parameters. Pls help with me!

**Comment by mbunkus** [comment]
That's simply how Matroska works for interlaced content. It's not a bug. See [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/Wrong-frame-rate-displayed).
