### ISSUE TITLE
--split parts-frames: removes Writing library information

### ISSUE THREAD

**Issue by rhazor** [mbunkus/mkvtoolnix#1936]
I run `--split parts-frames:200-` on a .mkv file that has first 200 frames of commercials and the file ends up with no more writing library information, e.g. MediaInfo does not show information that its x264 and etc.

As I understand the information is kept at the beginning of the file? And I trim first 200 frames.

In this https://github.com/mbunkus/mkvtoolnix/wiki/All-tracks-vanished-after-mkvpropedit,-the-header-or-chapter-editors it say you can write information to end of the file, but doesn't say how.

**Comment by mbunkus** [comment]
That FAQ entry has nothing to do with what you're observing. If you want me to look into it, then I'll need the source file(s). Please upload them to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server).

**Comment by rhazor** [comment]
It's up.

**Comment by mbunkus** [comment]
Thanks. However, this is nothing I'm going to fix. Sorry.

The information you mean (the SEI NALU) is stored in the very first frame. And you're throwing that frame away. Of course one could look for and extract the SEI NALU and then re-add it in a later frame, but mkvmerge's code is simply not designed that way. The whole bitstream handling is done long before decisions about splitting and discarding is made. Changing that would require major rewrites. I don't consider this use case important enough for such an investment.

**Comment by rhazor** [comment]
I tried to split frames 1-2 and it keeps the info but it's inaccurate output, it gives 3 second long total of 90 frames file.

**Comment by mbunkus** [comment]
Yes, because mkvmerge can only split right on key frames.

**Comment by rhazor** [comment]
Solved https://www.videohelp.com/software/MKV-Cutter cuts from frame 0 at exact frames and keeps all the infos. No reencoding.

**Comment by mkver** [comment]
For the record: MKV-Cutter reencodes, but it only reencodes the frames that need to be reencoded. And actually it, too, deletes the x264-options (if you cut the first frame away) and replaces them with other ones (the ones used to reencode) -- except in the unlikely case that it does what Moritz doesn't want to do: analyze the bitstream for SEI messages and act accordingly if found --, but these new ones are choosen to be compatible with the old ones (but this doesn't mean that they are the same!).

**Comment by rhazor** [comment]
You are right. It did change information of a constant CBR bitrate encode into CRF value 19 encode, I didn't understand at first.

Damn, stuck again at such simple task.
