### ISSUE TITLE
Issue with DVB-T2 recordings

### ISSUE THREAD

**Issue by ChristophRadtke** [mbunkus/mkvtoolnix#1938]
Hi Moritz,

I uploaded a sample file and a more detailed description of the issues I am facing with the new DVB-T2 recordings.
mergemkv is producing unplayable output without showing any error message.

It would be great if you could look at the files I uploaded to your SFTP server.

Danke und viele Grüße

Christoph

**Comment by mbunkus** [comment]
Unplayable how? Which players have you actually tried? What exactly was the result?

**Comment by ChristophRadtke** [comment]
I tried Media Player Classic HomeCinema, VLC and my sat receiver I create the recordings with. While all of them can play the untouched TS neither of them can play (some of) converted MKVs.
Depending on the file MPHC does not play at all (no error message) or plays with jittery audio . VLC either complaints that it cannot render the codecs used ("hevc" and "aac" that VLC can play without issues before converting to MKV) or sometimes it plays the background audio channels instead of the front channels.
If you try and convert the file I uploaded I hope you can see what happens to the output.

**Comment by mbunkus** [comment]
Thanks for the report & the sample file, BTW. New pre-builds for WIndows that include the fix are currently being compiled and should become [available](https://mkvtoolnix.download/windows/pre/) within the next ten minutes.

**Comment by ChristophRadtke** [comment]
Excellent work! Almost all of the DVB-T2 files could be convert with the new build! Thanks a lot!
Only one issue remains for the rest of the files. The conversion starts and then...

Error: memory.cpp/safemalloc() called from file src/common/memory.h, line 209: malloc() returned nullptr for a size of 4294967287 bytes.

...is displayed. I've uploaded another recording that causes mkvmerge to crash.

**Comment by mbunkus** [comment]
Thanks. I've opened a separate issue #1941 for that. Let's continue the discussion there.
