### ISSUE TITLE
mkvmerge safemalloc failure on certain MPEG transport streams

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mkvtoolnix#1941]
@ChristophRadtke reported this in #1938:

> Only one issue remains for the rest of the files. The conversion starts and then...
>
> Error: memory.cpp/safemalloc() called from file src/common/memory.h, line 209: malloc() returned nullptr for a size of 4294967287 bytes.
>
> ...is displayed. I've uploaded another recording that causes mkvmerge to crash.

**Comment by mbunkus** [comment]
New [pre-builds](https://mkvtoolnix.download/windows/pre/) are up.

**Comment by ChristophRadtke** [comment]
Works like a charm! Thank you!
