### ISSUE TITLE
Subtitle demuxing error with v10.0.0

### ISSUE THREAD

**Issue by phaze-phusion** [mbunkus/mkvtoolnix#1943]
### My setup
**OS :** Windows 7 64bit Professional
**Muxer :** MKVToolNix-64bit-10.0.0
**Demuxer :** MKVCleaver-64bit-0.6.0.8

### To recreate error
1. Using v10.0.0 mux an MP4/MKV file together with 1 (or more) SRT subtitle files
2. Take the resulting matroska file from step 1 and extract the subtitle using MKVCleaver
3. You'll get an error similar to the one bellow (error found in MKVCleaver log)

I don't know if the problem is with MKVCleaver or with MKVToolNix, so for the time being I've rolled back one version. Files muxed with v9.9.0 doesn't produce the same error when demuxed (see success message below)

### Notes
* There's no difference in the MediaInfo readout of the files created by the two versions
* The SRT subtitle track(s) is encoded in UTF-8-BOM
* Cleaver error message **_Track02.srt could not be opened for reading: open file error.**

## ERROR
    Extraction started on 04/15/2017 at 15:11:49
      20170315_100418 [muxed with 10.0.0].mkv : 
        Extracting Items - subtitles subtitles (error); attachments (ok);
        Codec is not V_MPEG4/ISO/AVC. Not converting to AVI
        Error: (mkvextract) The file 'F:\demuxed\20170315_100418 [muxed with 10.0.0].mkv--no-ogg 2:F:\demuxed\20170315_100418 [muxed with 10.0.0]_Track02.srt' could not be opened for reading: open file error.
      Extraction failed
    Extraction finished on 04/15/2017 at 15:11:50
    
    ## SUCCESS
    Extraction started on 04/15/2017 at 15:17:26
      20170315_100418 [muxed with 9.9.0].mkv : 
        Extracting Items - subtitles subtitles (ok); attachments (ok);
        Codec is not V_MPEG4/ISO/AVC. Not converting to AVI
      Done
    Extraction finished on 04/15/2017 at 15:18:08

**Comment by mbunkus** [comment]
This is a [known bug](https://blogs.sapib.ca/apps/bugs-requests/errors-out-with-mkvtoolnix-10-0-0/) in MKVCleaver.

**Comment by phaze-phusion** [comment]
My apologies.
I've just tested the MKVextract command line utility and it works beautifully so I'll be using that from now on.

Kudos to you and your team for creating these wonderful MKV utilities.

**Comment by mbunkus** [comment]
Don't worry, no apologies needed. And you're welcome.
