### ISSUE TITLE
mkvmerge hangs/uses all CPU on splitting raw HEVC/H.265

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1944]
Hi,

for me mkvmerge seems to hang when trying to do a simple splitting operation on a raw HEVC file. For example:
`mkvmerge -o output.mkv --split parts:00:01-00:05 input.265`

I uploaded a small sample file to your ftp. Tested using mkvtoolnix-32bit-10.0.0-build20170415-01476 (pre).

**Comment by mbunkus** [comment]
Thanks. I'll look into it.
