### ISSUE TITLE
H.265/HEVC: Fehler beim Konvertieren von TS nach MKV

### ISSUE THREAD

**Issue by creibens** [mbunkus/mkvtoolnix#1945]
Folgende Fehlermeldung erschien gleich nach dem Start:

```
--- Fehler ausgegeben von Job »Multiplexe in Datei »Ein Tick anders.mkv« im Verzeichnis »E:\claus\Videos\Aufnahmen«« gestartet am 2017-04-16 16:43:55 ---
memory.cpp/safemalloc() aus Datei src/common/memory.h, Zeile 209 aufgerufen: malloc() hat für eine Größe von 18446744073709551607 Byte »nullptr« zurückgegeben.
```

**Comment by mkver** [comment]
This has already been reported in #1941 and fixed. [New pre-builds](https://mkvtoolnix.download/windows/pre/) already contain the fix.

**Comment by mbunkus** [comment]
It is indeed possible that this is the same issue as #1941. Please give the new pre-builds that mkver has linked a try.

**Comment by creibens** [comment]
This fix did not work for me. The
      problem still exists.
      
      Moritz Bunkus schrieb am 16.04.2017 um 18:22:
    
    
      It is indeed possible that this is the same issue as #1941. Please give the new
        pre-builds that mkver has linked a try.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mbunkus/mkvtoolnix","title":"mbunkus/mkvtoolnix","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mbunkus/mkvtoolnix"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mbunkus in #1945: It is indeed possible that this is the same issue as #1941. Please give the new pre-builds that mkver has linked a try."}],"action":{"name":"View Issue","url":"https://github.com/mbunkus/mkvtoolnix/issues/1945#issuecomment-294360397"}}}

**Comment by mkver** [comment]
Then you should upload a sample to Moritz' [ftp-server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server).
Dann sollten Sie die fragliche Datei auf Moritz [ftp-Server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server) hochladen.

**Comment by mbunkus** [comment]
As mkver has said, please upload a sample file to the FTP server so that I can take a look at what's wrong. Without a sample file fixing it would be  impossible. Thanks.

**Comment by mbunkus** [comment]
Closing this issue due to lack of feedback and lack of sample files to reproduce the issue with.
