### ISSUE TITLE
No window/taskmanager icon in Wayland session

### ISSUE THREAD

**Issue by stikonas** [mbunkus/mkvtoolnix#1948]
This can be fixed by renaming desktop file to org.bunkus.mkvtoolnix-gui.desktop.

https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

https://github.com/qt/qtwayland/blob/dev/src/client/qwaylandwindow.cpp#L160

https://cgit.kde.org/kwin.git/tree/abstract_client.cpp#n1676

https://cgit.kde.org/kwin.git/tree/shell_client.cpp#n1289

https://blog.martin-graesslin.com/blog/2015/07/porting-qt-applications-to-wayland/

**Comment by mbunkus** [comment]
Thanks for all the links to the documentation. I'll look into it, but first I need to set up a VM using Wayland, I guess. I'm still on xorg for the time being.

**Comment by stikonas** [comment]
No worries. I use X11 on a daily basis too, there are still many things that have to be fixed before wayland is usable. But it won't get fixed if things like this are not reported... Well, this is at least an easy fix...
