### ISSUE TITLE
MKVToolNix GUI's show command-line in option file format includes path to mkvmerge

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1949]
In MKVToolNix GUI "Multiplexer"->"Show command line" the two options to show the command in "option file" format include the path/command to mkvmerge itself, e.g.:
`[
  "C:/Program Files (x86)/MKVToolNix\\mkvmerge.exe",
  "--ui-language",
  "en",
  "--output",
  "",
....
`
I think it should just be 
`[
  "--ui-language",
  "en",
  "--output",
  "",
....
`
as an option file is not a batch script calling mkvmerge. Rather the option file is opened by mkvmerge. The same error applies to the old non-JSON format.

**Comment by mbunkus** [comment]
Meh, you're right. I'll fix that. Thanks.
