### ISSUE TITLE
MKVToolnix GUI files not removed

### ISSUE THREAD

**Issue by Slarty75** [mbunkus/mkvtoolnix#1954]
When adding job to queue and in prefrences 'Remove source files' is used, Input Tab is cleared but in Output Tab at least Chapter File is left intact.

**Comment by mbunkus** [comment]
That's exactly what the "remove source files" option is supposed to do. It only removes the source files (the ones on the "input" tab), and leaves all other settings intact (safe for the movie title as that's governed by other settings).

If you want to use completely empty and fresh settings, set that option to "create new settings".
