### ISSUE TITLE
Default config does not point to the default audio file

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1956]
With version 11.0.0. (64bit) on Windows 7 (64bit), the config points to ```<MTX_INSTALLATION_DIRECTORY>\sounds\finished-1.ogg```, while the file was placed by the installer in ```\data\sounds```. That results in the file not being played (of course).

I can't tell if that is due to system specific placement by the installer.

**Comment by mbunkus** [comment]
Meh. Thanks. I'll fix that.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) are compiling and should be available shortly. They'll also update existing, wrong paths in your configuration.

**Comment by bastik-tor** [comment]
Not that it would have been important in any way, but I downloaded the pre-build and it does indeed fix the issue.

BTW, I had noticed before that the input field was cleared upon canceling the selection, but I assumed that it would check if a file exists it has been configured to use and if it wouldn't exist it would clear it.

**Comment by mbunkus** [comment]
> BTW, I had noticed before that the input field was cleared upon canceling the selection, but I assumed that it would check if a file exists it has been configured to use and if it wouldn't exist it would clear it.

No, that was a straight-up bug. Canceling any file dialog should not alter anything ever. I noticed this during the investigation of the wrong audio file location and fixed it in 2a7be92d678c95c1df0d640211141c301b133412.
