### ISSUE TITLE
DVB-T2/HEVC playback issue

### ISSUE THREAD

**Issue by ChristophRadtke** [mbunkus/mkvtoolnix#1957]
Hi,

I am facing one last (I hope) issue with my HEVC recordings. The majority of the recordings now work great with the latest versions but a few recordings are ending up corrupt (unplayable or jittery) once they were processed by mkvmerge.

I've uploaded another sample and the command line parameters used.

Thanks a lot!

**Comment by mbunkus** [comment]
Thanks, I'll look into it.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) are currently being compiled and will be available shortly. Build numbers 01478 and higher contain the fix.

**Comment by ChristophRadtke** [comment]
Thanks as always for the quick fix! For some files it works now. For the remaining files we still have our old friend:

Error: memory.cpp/safemalloc() called from file src/common/memory.h, line 209: malloc() returned nullptr for a size of 4294967289 bytes.

I'll upload another sample file tonight. You want me to create another issue ?

**Comment by mbunkus** [comment]
Yes, please. It's quite possible that it's the same issue as #1945, but as I haven't received any sample files for that issue yet let's treat yours as a separate one.
