### ISSUE TITLE
extra byte added to HEVC SPS with mkvmerge 11.0.0

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1958]
I noticed mkvmerge 11.0.0 adding an extra byte (80 at 4C) to the end of the SPS (in CodecPrivate). This byte doesn't exist in the raw stream coming from x265 and isn't written by mkvmerge 10.0.0. I don't understand enough to  judge if this intended or a bug. Sample uploaded to ftp.

**Comment by mbunkus** [comment]
Thanks. I'll look into it.

**Comment by sneaker2** [comment]
I just noticed I accidetally created "mkvmerge11.mkv" using mkvtoolnix-32bit-10.0.0-build20170415-01476-15fb08c74 (pre). But the result with 11.0.0 final is the same so it might actually help in finding the change responsible quicker...

**Comment by mbunkus** [comment]
I'm already investigating this. Well, there have been a couple of bug fixes in the HEVC parser, especially how the SPS is handled, and either one of those bug fixes introduced or at least unmasked another bug.

I'll find & fix it :)

**Comment by mbunkus** [comment]
Ouch, this is one stupid mistake…

**Comment by mbunkus** [comment]
For the record: this issue is what's causing the encoding settings to be lost as well. They're not really lost, but the data stored in front of them is invalid causing parsers to abort or to parse the data in a wrong way.
