### ISSUE TITLE
Files cannot be appended to themselves

### ISSUE THREAD

**Issue by swsquish** [mbunkus/mkvtoolnix#1962]
Can someone please help?
Not sure what I am doing wrong or if it's a program issue?

--- Errors emitted by job 'Multiplexing to file "Seinfeld - s03e18 - The New Friend - Introduction by Jerry Seinfeld.mkv" in directory "S:\DVD Rip\Seinfeld\Season 03\Season 03\New folder"' started on 2017-04-23 14:58:12 ---
Files cannot be appended to themselves. The argument for '--append-to' was invalid.

![untitled 2](https://cloud.githubusercontent.com/assets/27927010/25316563/730374e0-2837-11e7-9c31-10078949973e.jpg)
![untitled](https://cloud.githubusercontent.com/assets/27927010/25316566/773fee44-2837-11e7-90dc-1f8cfab80868.jpg)

**Comment by mbunkus** [comment]
The second file contains one more audio track than the first one. The GUI will auto-assign such seemingly superfluous tracks to the last audio track from the first file. However, you have to decide which audio track to actually keep. The other one from `s03e17-18` has to be deactivated.

**Comment by swsquish** [comment]
Thank you so much for the fast response.  I duplicated the audio track in the first file so that the GUI auto-assigned the two tracks in the second file, maintaining both tracks.  Worked like a charm.  Thank you again.
