### ISSUE TITLE
Add an option to avoid adding writing time to metadata when muxing

### ISSUE THREAD

**Issue by wfwf1997** [mbunkus/mkvtoolnix#1964]
According to the specifications, the DateUTC element is optional in a matroska file. Sometimes I don't want to make it in my file for privacy or some other reasons. I think it is a good choice to add such an option in `mkvmerge`. Or I think you can just make `mkvpropedit` have the ability to modify/delete this property.

**Comment by mbunkus** [comment]
Yeah, maybe.

**Comment by remuxer32** [comment]
I fully agree with **@wfwf1997** and think it's a good idea to add an option for modifying/deleting that property. There are people who don't need to know everything about my (or anyone else) Matroska files, so I perfectly understand the need to keep privacy. It will be helpful for me, too.

**Comment by remuxer32** [comment]
New pre-builds for Windows that contain the new option have been uploaded here:
- https://mkvtoolnix.download/windows/pre/
