### ISSUE TITLE
memory.cpp/safemalloc() exception with DVB-T2/HEVC recordings

### ISSUE THREAD

**Issue by ChristophRadtke** [mbunkus/mkvtoolnix#1965]
For a few files mkvmerge still throws the known exception:

```
Error: memory.cpp/safemalloc() called from file src/common/memory.h, line 209: malloc() returned nullptr for a size of 4294967289 bytes.
```

Maybe the same as #1945. File has been uplaoded to the SFTP server.

Thanks a ton!

**Comment by mbunkus** [comment]
I cannot reproduce this error with the file you've uploaded (`Die Dasslers - Pioniere, Brüder und Rivalen (1_2) [Fernsehfilm Deutschland 2016] (ONE HD HEVC).ts`), neither on Linux nor on Windows, neither with a 32-bit build nor with a 64-bit one. Can you please verify that it happens with that file with [pre-build 01487 or 01488](https://mkvtoolnix.download/windows/pre/)?

**Comment by ChristophRadtke** [comment]
Oh no, sorry, I actually upgraded to 11 assuming that it was more recent than our previous pre-builds - which was not the case...
I'll give 01488 a try and report again. Sorry again!

**Comment by ChristophRadtke** [comment]
Mea culpa! 01488 works perfectly!

Thanks a lot!

**Comment by mbunkus** [comment]
No problem. Thanks for the confirmation.
