### ISSUE TITLE
Subtitles not copied to MKV

### ISSUE THREAD

**Issue by JJMartin1340** [mbunkus/mkvtoolnix#1969]
I am currently putting my DVD collection onto external hard drive. I extract the movie using VOB2MPG then if it has more than one part, combine them into an MKV file. Many movies have 3 or 4 soundtracks and up to 8 subtitles. The soundtracks are all copied, but all the subtitles are discarded. MediaInfo reports the subtitles on the movie I am currently working on are RLE format. Is there any way to copy these to the output file?

**Comment by mkver** [comment]
The color palette the subtitles use isn't stored in the vob-files, but in the ifo-files and mkvmerge doesn't contain a parser for ifo-files. Therefore it can't copy the subtitle tracks. And it also doesn't copy the chapters.
But there is a program that can do this: MakeMKV. It's free while in beta. (And it seems to be in beta status forever.)

**Comment by mbunkus** [comment]
@mkver has given pretty much all the relevant information. This is nothing that I'm going to fix/implement as I cannot really implement it properly: the palette information is already lost at that point, and using those subtitles without the palette information will look really, really bad for a lot of discs.

Please use some other software for converting the subtitles: either [MakeMKV](http://www.makemkv.com/) for everything-in-one-go or [Direct VobSub](https://en.wikipedia.org/wiki/DirectVobSub) for extracting only the subtitles (those can then be fed to MKVToolNix).
