### ISSUE TITLE
Extract all audio tracks without setting id?

### ISSUE THREAD

**Issue by rhazor** [mbunkus/mkvtoolnix#1970]
I run a batch file that grabs all .mkv files and remux audio from it. It's OK if all .mkv files has audio set to id:1.

But what if 10 .mkv containers has audio as id:1 and 10 as id:0?

How do you set that in cmd line? Because now if cmd line set to id:1 and actual audio is id:0 it extracts the video file and renames it as aac/m4a.

`mkvextract tracks "src.mkv" 1:audio`

This issue dates back to 2008 https://forum.doom9.org/showthread.php?t=141945

**Comment by mbunkus** [comment]
You're supposed to parse mkvmerge's identification output, specifically the output of `mkvmerge --identification-format json --identify your.mkv`. Then use that information to determine the video track ID and use that for mkvextract.

**Comment by rhazor** [comment]
You mean I have to write my own script that reads json output from file and sets correct variables? How is this res:fixed/implemented?

**Comment by mbunkus** [comment]
You asked a question and I answered it. And no, I won't add an option to "extract the first video track".

**Comment by mbunkus** [comment]
Yeah, I mixed up audio and video. Sorry for that. The point remains the same: mkvmerge's identification output allows for arbitrary scripting with arbitrary requirements, requirements that cannot be sanely expressed via command line arguments. "Sanely" as in everybody has his/her own use case, and I simply cannot add arguments for them all. Instead I'm giving you the tools to implement your own, custom-built, fit-to-purpose solution.

Here's a small Ruby script that outputs the track ID of the first audio track in a file:

```ruby
#!/usr/bin/env ruby

require "json"
require "shellwords"

command = "mkvmerge --identification-format json --identify " + Shellwords.escape(ARGV[0])
track   = JSON.load(`#{command}`)["tracks"].select { |t| t["type"] == "audio" }[0]

puts(track["id"]) if track
```

Use that together with mkvextract:

```
mkvextract tracks source.mkv $(audio_track_id.rb source.mkv):audiofile
```

**Comment by mbunkus** [comment]
And extracting all audio tracks can be scripted just as easily, something like this (untested):

```ruby
#!/usr/bin/env ruby

require "json"
require "shellwords"

def ext_by_codec codec
  # add more codec matches here
  return %r{mp3}i.match(codec) ? ".mp3" : %r{aac}.match(code) ? ".aac" : "ac3"
end

source     = Shellwords.escape(ARGV[0])
identified = JSON.load(`mkvmerge --identification-format json --identify #{source}`)
files      = identified["tracks"].
  select { |t| t["type"] == "audio" }.
  map    { |t| t["id"].to_s + ":audio" + t["id"].to_s + ext_by_codec(t["codec"]) }.
  join(" ")

system "mkvextract tracks #{source} #{files}"
```

**Comment by rhazor** [comment]
I'm on Windows. But I'm sure I can work this out with Xidel.

**Comment by mbunkus** [comment]
Ruby is available for Windows, too. But you don't have to use Ruby, of course, it's just what I prefer and am comfortable with. JSON has the nice property that easy-to-use libraries are available for it for pretty much all languages out there, and there are tons of tools on top of that.
