### ISSUE TITLE
SeekPreRoll - Opus muxing - General clustering

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1971]
Hello,

as you [probably know very well](https://lists.matroska.org/pipermail/matroska-devel/2013-June/004523.html), the `SeekPreRoll` that is used with Opus implies that audio and video should be interleaved in such a way that the video block with timestamp X is next to the audio block with timestamp X-c, where c is a constant that depends upon `SeekPreRoll` and `CodecDelay`. Contrary to you (actually: you in June 2013), I think that c is actually `SeekPreRoll-CodecDelay` (the audio with Matroska timestamp `X+CodecDelay` belongs to the video with timestamp X and in order to get audio `X+CodecDelay` you need to start decoding audio from `X+CodecDelay-SeekPreRoll` onward (of course, there is also a second restriction: video X and audio `X+CodecDelay` should be sufficiently close to each other to be played concurrently and both restrictions only work well for small values of `SeekPreRoll`)). Because one needs to have the full block with `X+CodecDelay-SeekPreRoll` available, it might even be advisable to use `X+CodecDelay-SeekPreRoll-DefaultDuration` or so (this will of course not work well if the blocks have different durations, but normal audio codecs (including opus) are covered by this).
And looking at muxed files you seem to have implemented some kind of mechanism to ensure this. The problem is: It works in the wrong direction (so muxing opus like any other codec would be better than this)! Here is a part of mkvinfo's output:
```
|+ Cluster
| + Cluster timecode: 0.000s
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.000s = 00:00:00.000)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.020s = 00:00:00.020)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.040s = 00:00:00.040)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.060s = 00:00:00.060)
|  + Frame with size 15
| + SimpleBlock (key, track number 1, 1 frame(s), timecode 0.000s = 00:00:00.000)
|  + Frame with size 1641
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.080s = 00:00:00.080)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.100s = 00:00:00.100)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.120s = 00:00:00.120)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.140s = 00:00:00.140)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.160s = 00:00:00.160)
|  + Frame with size 15
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.083s = 00:00:00.083)
|  + Frame with size 5066
| + SimpleBlock (discardable, track number 1, 1 frame(s), timecode 0.042s = 00:00:00.042)
|  + Frame with size 7470
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.180s = 00:00:00.180)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.200s = 00:00:00.200)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.220s = 00:00:00.220)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.240s = 00:00:00.240)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.260s = 00:00:00.260)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.280s = 00:00:00.280)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.300s = 00:00:00.300)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.320s = 00:00:00.320)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.340s = 00:00:00.340)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.360s = 00:00:00.360)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.380s = 00:00:00.380)
|  + Frame with size 15
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 0.400s = 00:00:00.400)
|  + Frame with size 15
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.334s = 00:00:00.334)
|  + Frame with size 1784

...

| + SimpleBlock (key, track number 2, 1 frame(s), timecode 2.400s = 00:00:02.400)
|  + Frame with size 541
| + SimpleBlock (track number 1, 1 frame(s), timecode 2.336s = 00:00:02.336)
|  + Frame with size 11684
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 2.420s = 00:00:02.420)
|  + Frame with size 605
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 2.440s = 00:00:02.440)
|  + Frame with size 556
|+ Cluster
| + Cluster timecode: 2.377s
| + SimpleBlock (key, track number 1, 1 frame(s), timecode 2.377s = 00:00:02.377)
|  + Frame with size 37788
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 2.460s = 00:00:02.460)
|  + Frame with size 643
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 2.480s = 00:00:02.480)
|  + Frame with size 714
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 2.500s = 00:00:02.500)
|  + Frame with size 583
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 2.520s = 00:00:02.520)
|  + Frame with size 582
```
Hopefully this can be fixed by changing a sign. (I disabled lacing in the above example just to be sure and in order to get a more precise picture of how audio and video are interleaved; it happens regardless of lacing.)
~~~2. It is actually good to have audio available directly after performing a seek. This is why e.g. ffmpeg puts the audio block with the highest timestamp lower or equal than the video keyframe in the same cluster as the keyframe. In issue #500 you were asked to implement the same and declared the part of #500 that I just mentioned to be a major rewrite and didn't implement it. But assuming you can solve 1. for Opus, then there is nothing standing in the way of implementing this. After all, you just have to mux audio tracks as if they were Opus with `SeekPreRoll=DefaultDuration` and the result will be as desired. Or am I missing something here?~~~

Grüße
Andi

**Comment by mbunkus** [comment]
Thanks for the analysis. I'll look into it.

Please split point 2 into its own issue as it's unrelated and a whole other category (enhancement vs bug fix). Thanks.

**Comment by mbunkus** [comment]
I disagree with your analysis.

Pre-roll means that the decoder needs to be fed an amount of data before it can output anything at all. For Opus with seek-pre-roll of 80ms this means that the first 80ms of data must be fed before the decoder emits the data for timestamp 0ms.

Let's take a look at how mkvmerge interleaves Opus & MP3, for example:

``` shell
[0 mosu@sweet-chili ~/prog/video/data] mkvinfo -s v.mkv|head
Track 1: audio, codec ID: A_OPUS, mkvmerge/mkvextract track ID: 0, language: und, sampling freq: 48000, channels: 2
Track 2: audio, codec ID: A_MPEG/L3, mkvmerge/mkvextract track ID: 1, default duration: 24.000ms (41.667 frames/fields per second for a video track), language: und, sampling freq: 48000, channels: 2
I frame, track 1, timecode 0 (00:00:00.000), size 418, adler 0x8c07d527
I frame, track 1, timecode 20 (00:00:00.020), size 224, adler 0x9fd47640
I frame, track 1, timecode 40 (00:00:00.040), size 224, adler 0x83387117
I frame, track 1, timecode 60 (00:00:00.060), size 224, adler 0x42067043
I frame, track 1, timecode 80 (00:00:00.080), size 227, adler 0xca256fa2
I frame, track 2, timecode 0 (00:00:00.000), size 672, adler 0xcdd94b8b
I frame, track 1, timecode 100 (00:00:00.100), size 227, adler 0x1b8170ef
I frame, track 2, timecode 24 (00:00:00.024), size 672, adler 0x2d144025
```

This layout ensures that the system can actually use the decoded data of both tracks for the same timestamps at the same time. By the time the first MP3 packet is encountered, the Opus decoder has been fed all of its data and is ready to emit the decoded data for timestamp 0ms.

**Comment by mkver** [comment]
I think you misunderstood my point: Look at the second cluster. The video keyframe has a timestamp of 2377ms and the first audio frame in this cluster has a timestamp of 2460ms. So apparently mkvmerge tries to use a special muxing mode for opus (one that takes SeekPreRoll into account), but it does this in the opposite direction (actually one needs the cluster with timestamp 2360ms available in order to produce valid audio for this video keyframe, but it's in the second cluster).
And your answer is in contradiction to what I have read about Opus in the long discussions about how to mux opus into Matroska: At the beginning of an Opus file, only the PreSkip/CodecDelay is invalid, not the whole 80ms. (That's because encoder and decoder both start at zero, so that the convergence is faster (or so I have read).) So you do not really need this special muxing mode at the beginning. You only need to take these 80ms into account for the other clusters. (There is an instance where the 80ms at the beginning are important: If one has chopped the beginning of an opus track away, because then one really starts at a discontinuity.)

**Comment by mbunkus** [comment]
A demuxer needs to take seek pre roll into account when seeking. Let's take your case as an example. The user wants to seek to 2377ms. The demuxer then has to check if the current audio track has a pre-roll. If it does, the muxer really needs to seek to 2377ms - pre-roll, then start decoding audio from that point and discard everything else up to 2377ms.

I've chosen that way in order to keep the amount of decoded data a player has to cache to a minimum.

Let's assume I'd reverse the order. The cluster could look something like this (fictional values):

```
video 2000ms
Opus 1920ms
Opus 1940ms
video 2040ms
Opus 1960ms
Opus 1980ms
video 2080ms
Opus 2000ms
```
The decoder would start to decode the video and be able to show the frame immediately. The audio decoder, however, would have to decode the first four Opus blocks without emitting a single decoded byte. During that time three video frames would have already been shown. By the time the first audio byte corresponding to the video frame at 2000ms is available for playback the video is ahead quite a bit, and the player would suddenly have to throttle video playback speed until the audio has caught up. That wouldn't make any sense.

**Comment by mkver** [comment]
1. I actually thought that you want mkvmerge to be a muxer that helps players play the sound right away by appropriately placing the audio blocks, but even if that's not your goal, the current way of muxing is suboptimal: If you simply muxed Opus like any other audio track, the keyframe at 2377ms would be followed by an audio block at 2380ms so that audio can be output from 2460ms+CodecDelay on. The way it is currently muxed only allows 2540ms+CodecDelay. There is also no problem regarding your objection: The only difference is that decoding, discarding and actually emitting of audio starts 80ms earlier.
2. I actually don't agree with your objection:
a) Audio decoding is not very taxing compared to video decoding nowadays so that it can be done faster than realtime.
b) Because of b-frames and the accompanying frame reordering, video has its own decoding delay. Therefore players already have to handle decoding delays.
c) Even if we assume that the playback device cannot decode faster than realtime, the proposed muxing strategy wouldn't pose any additional problems: After all, this change would only make it easier for a player that actually wants to play the right audio directly after a seek, but it doesn't force a player that doesn't want to do that to do it. If it seeks to video keyframe with timestamp x and wants to start decoding audio at timestamp x, it can still do so by discarding some audio packets (hopefully it will remember not to output the first 80ms, but it has to remember this with the current muxing strategy, too). Version 4.0 of mkvmerge was the first version that started new clusters with video keyframes, so there are completely spec-compliant files out there where the video player has to discard several audio (and video) packets after a seek because it doesn't need them. So it would be nothing new to discard some audio packets and players should therefore be expected to be able to do so (the only things that are new with Opus are CodecDelay and SeekPreRoll, but I don't think that there is a situation where a player remembers to adhere to them with the current muxing strategy (or the muxing strategy from 1.), but not with the proposed muxing strategy).
d) I don't see how your muxing strategy decreases the amount of decoded data a player has to cache: A player that is aware of the peculiarities of Opus does not need to cache the 80ms that is discarded; it just needs to decode as normal and discard the output for the first 80ms. There is no need to cache anything more than during normal playback. A player that is completely Opus-agnostic just discards the audio blocks before the video keyframe entirely and begins decoding and outputting (possibly corrupt) the audio blocks directly after the video keyframe (or maybe it starts with the audio block directly before the video keyframe...) and just plays from there on; the caching requirements are also not higher than for normal playback. The same is true for a player that partially supports SeekPreRoll and starts decoding audio at the video keyframe and discards the first 80ms of audio output (hence outputs 80ms of silence after the seek).
e) There are actually situations in which the current muxing strategy increases the amount of encoded audio data to be cached: Look at the example in the very first post. The video timestamps in decoding order are 0ms, 83ms, 42ms, 334ms,.... Between the 42ms and 334ms there are twelve audio packets of which the latter two are to be shown after the frame at beginning at 334ms has ended.

Grüße
Andi
