### ISSUE TITLE
rake failed

### ISSUE THREAD

**Issue by pras1406** [mbunkus/mkvtoolnix#1974]
[mkvtoolnix_install_rake_failed.txt](https://github.com/mbunkus/mkvtoolnix/files/973107/mkvtoolnix_install_rake_failed.txt)

**Comment by mbunkus** [comment]
Your `MATROSKA_CFLAGS` and `EBML_CFLAGS` are wrong. You have to point them to the directory where the `ebml` and `matroska` sub-directories are located in, not directly at the `ebml` and `matroska` sub-directories.

You should also not overwrite `EBML_CFLAGS` and `MATROSKA_CFLAGS` yourself. Instead, use `--with-extra-includes=…` which you're already doing for libEBML. Just do the same for libMatroska, remove `EBML_CFLAGS` & `MATROSKA_CFLAGS` and you should be good to go.

**Comment by mbunkus** [comment]
You could even just skip using external versions of both libraries as MKVToolNix includes both, and if `configure` cannot find an external one, it will use the internal one automatically. No fiddling with `--with-extra-…`, `EBML_…` or `MATROSKA_…` required for that at all.
