### ISSUE TITLE
Close changed file

### ISSUE THREAD

**Issue by Bitnugger** [mbunkus/mkvtoolnix#1976]
The file <No target file> has been modified. Do you really want to close them? All changes are lost.

This message is displayed when I want to close the GUI.

If all entries were removed from the job list, there is no target file, but the warning message above is still displayed.

Windows 10 X64
![mkvtoolnix_close_changed_file](https://cloud.githubusercontent.com/assets/27592685/25731567/8ecb6f70-3147-11e7-8cc5-df781d478ac0.png)

**Comment by optimiz** [comment]
Sounds like a duplicate of #1797, does @mbunkus's response there answer your issue?

**Comment by Bitnugger** [comment]
Yes, what @mbunkus's writes has led me to the desired settings. Thanks and forgive me that I have created a duplicate. But I am very surprised now that you could find it so fast. ;-)
