### ISSUE TITLE
Specify output filenames while splitting

### ISSUE THREAD

**Issue by yyzguy** [mbunkus/mkvtoolnix#1978]
Hi,
Using mkvmerge to split one long file into several shorter files using timecodes.

Is there a way to specify the output filenames.  It appears the only way is to let mkvmerge append -001, -002, etc to a base filename.

Ideally, I would like to be able to use the mvktools GUI and chapter editor for this (having filenames=chapter names) , but right now attempting with command line and it doesn't seem possible.

Thanks

**Comment by mbunkus** [comment]
This is not possible at the moment, and I have no plans for implementing such functionality.
