### ISSUE TITLE
Batch Command Line no longer supports filenames with spaces

### ISSUE THREAD

**Issue by noblemd00** [mbunkus/mkvtoolnix#1982]
I wrote the following Command Line which previously has always worked and now does not recognize filenames with spaces. In the specified directory the CMD Line removes subtitles and adds .x265 to the end of the filename.

```
FOR /F "delims=*" %I IN ('dir /b *.mkv') DO "C:/Program Files/MKVToolNix\mkvmerge.exe" --ui-language en --output ^"U:\~Conv Temp\x265\new\%~nI.x265.mkv^" --no-subtitles --language 0:und --default-track 0:yes --language 1:eng --default-track 1:yes ^"^(^" ^"U:\~Conv Temp\x265\%I^" ^"^)^" --title %I.x265 --track-order 0:0,0:1
```
Note: in the text above there is a backslash between "new" & "%~nI" not showing in this text editor -- other locations as well - visible when only when editing - see below - substtuted 
"(backslash)").

```
FOR /F "delims=*" %I IN ('dir /b *.mkv') DO "C:/Program Files/MKVToolNix\mkvmerge.exe" --ui-language en --output ^"U:\~Conv Temp\x265\new(backslash)%~nI.x265.mkv^" --no-subtitles --language 0:und --default-track 0:yes --language 1:eng --default-track 1:yes ^"^(^" ^"U:\~Conv Temp\x265(backslash)%I^" ^"^)^" --title %I.x265 --track-order 0:0,0:1
```

Sample output is as follows:

```
U:\~Conv Temp\x265>"C:/Program Files/MKVToolNix\mkvmerge.exe" --ui-language en --output "U:\~Conv Temp\x265\new\0106.The Monsters of the Nethermoor.x265.mkv" --no-subtitles --language 0:und --default-track 0:yes --language 1:eng --default-track 1:yes "(" "U:\~Conv Temp\x265\0106.The Monsters of the Nethermoor.mkv" ")" --title 0106.The Monsters of the Nethermoor.mkv.x265 --track-order 0:0,0:1
mkvmerge v11.0.0 ('Alive') 64bit
Error: The file 'Monsters' could not be opened for reading: open file error.
```

As you can see the filename is read properly but mkvmerge cannot open the file - only picking up the first word of the filename.

The CMD Line works if the filename is one word or if a character (such as ".") is substituted for the spaces making the filename one long string.

**Comment by mbunkus** [comment]
mkvmerge's command line parsing code hasn't changed in ages. In general it still works just fine with spaces both in the input and the output file name:

![using files with spaces](https://cloud.githubusercontent.com/assets/414282/26023477/a65015ee-37bc-11e7-9db7-62ef6bb930cf.png)

Therefore this is most likely due to your specific usage. I cannot help you with usage questions regarding `cmd.exe`. I don't know how `cmd.exe` handles variable substitutions and what the actual command line given to mkvmerge would look like.
