### ISSUE TITLE
make Ctrl+Shift+Space select/deselect current item

### ISSUE THREAD

**Issue by vanowm** [mbunkus/mkvtoolnix#1983]
A common behaviour is when application allows select multiple list items that have checkboxes (using SHIFT/CTRL keys) hitting space would check/uncheck the checkboxes of all selected items.
Currently hitting space bar in would ignore all selected items but "current" one, making multiple selection totally useless.

Even right click has no actions for the selections.
![image](https://cloud.githubusercontent.com/assets/511517/26022939/b4f62efe-377f-11e7-8878-bba600bbed03.png)

**Comment by mbunkus** [comment]
The primary purpose of mult-track-selection is applying settings on the right to all of them at once. Select a couple of tracks, then change e.g. the track language to `French` and it will be set for all selected tracks. This includes enabling or disabling them via "Copy this item" at the top. See [this short video](https://www.youtube.com/watch?v=QET-MifgJLM) as an example.

As for keyboard shortcuts: hitting return will do what you want.

**Comment by vanowm** [comment]
May I ask why enter? This is not "common" behaviour of any application I've ever seen.
(numpad enter doesn't doesn't work, btw)

Also its not possible using just keyboard select multiple list items not in sequence  (unless there is another arbitrary button I don't know that does this). Normally SHIFT + Up/Down selects items in sequence, while holding CTRL key would allow change position of "current" selection (the dotted border) without actually selecting it, then pressing space would add that item to the selection.
mkvtoolnix behaves differently CTRL + Up/Down moves selected items, SHIFT + CTRL +Up/Down changes the "current" position, however pressing SHIFT + CTRL + SPACE check/uncheck the checkbox of the "current" item only and SHIFT + CTRL + ENTER does nothing.

IMO it should be:
`current` = item with dotted border
`select` = item with blue background

 Key combination | Current action  | Proposed action
-- | -- | --
 Up/Down | move `current` and `select` single item | move `current` and `select` single item
Space | check/uncheck `current` item | check/uncheck all `selected` items
CTRL + Up/Down | move `selected` items | move `current` position
CTRL + Space | check/uncheck `current` item | `select`/`deselect` `current` item without affecting other `selected` items
CTRL + SHIFT + Up/Down | move `current` position | move `selected` items
SHIFT + Up/Down | move `current` position and add/remove this item to/from the `selection` `*` | move `current` position and add/remove this item to/from the `selection` 
SHIFT + Space | check/uncheck `current` item | check/uncheck `current` item

`*` it doesn't `deselect` items that were previously `selected` (for example via CTRL + Mouse Click)

**Comment by mbunkus** [comment]
It works how it works because it's the default Qt tree view control with its default key bindings when multi-selection is enabled. I'm not going to change that.

**Comment by vanowm** [comment]
Oh ok, but would you consider at least change behaviour of CTRL + SHIFT + SPACE = select current item without affecting previous selection?

**Comment by mbunkus** [comment]
How would that help you? You cannot move the current item without moving the selection.

**Comment by vanowm** [comment]
Yes, you can CTRL + SHIFT + Up/Down

**Comment by mbunkus** [comment]
Ah right. Yeah ok.

**Comment by vanowm** [comment]
Well, somehow the topic was changed to something wasn't discussed about at all and the fix is not related to what this topic was originally about...
Right now there is still no way check/uncheck selected items all at once with keyboard, or via mouse right click
And now CTRL+SHIFT+SPACE does exactly what CTRL+SPACE **supposed** to do

**Comment by mbunkus** [comment]
> Right now there is still no way check/uncheck selected items all at once with keyboard, or via mouse right click

This is incorrect. As I've stated above:

  * Hitting `enter` will check/uncheck all selected items at once. With a single press of said key.
  * Using the mouse you can check/uncheck all selected items at once by changing the drop down box on the right labeled "copy this item". Yes, one such change applies to all selected items.
