### ISSUE TITLE
do not force WMP

### ISSUE THREAD

**Issue by fcore117** [mbunkus/mkvtoolnix#1985]
Please do not force usage of WMP system, make it optional or make releases without WMP requirement. Thanks.

And someone spread message to QT that they should use FFMpeg for media framework not OS based codecs, more people spread word then better chance it will be.

**Comment by mbunkus** [comment]
No, sorry. You don't have to use WMP, my program doesn't use WMP, but it does use the Media Foundation framework, and that won't change.

**Comment by fcore117** [comment]
is it possible to compile myself without wmf for windows in future?

**Comment by mbunkus** [comment]
Sure it's possible, this is Open Source software, after all, but it's not trivial. You'll have to patch out the Windows-specific audio playback code and change the `configure` script not to link against Qt's multimedia framework. As I've said elsewhere, I won't spend any time on support for non-supported platforms (this includes Windows without Media Foundation); therefore I won't spend on making this any easier either.
