### ISSUE TITLE
Subtitle display issue for NeoTV

### ISSUE THREAD

**Issue by jutta-livingmiracles** [mbunkus/mkvtoolnix#1986]
Hi,

I've started using MKVToolNix only very recently. The reason I'm using it is this:

I have an external Blu-ray/DVD drive and I use MakeMKV to rip any Blu-rays I get, then run that rip through Handbrake for compression. I store my movies on a NAS (network attached storage) and play the movies through a NeoTV 550 media player. For some reason, the NeoTV doesn't play the movies that I've compressed with Handbrake, but when I remux them using MKVToolNix, the movies play fine. 

The only issue that I started noticing, however, since remuxing my movies, is that on the NeoTV, when playing the movies, the subtitles don't work properly. It seems like, when two people are talking pretty quickly in succession in the movie, the subtitles don't keep up. They show maybe the first sentence the first person is saying, then that sentence stays on the screen for a while, and the subtitles corresponding to what the second person is saying never show up at all. Same goes, when one person in the movie speaks fast or a lot at a time, then the subtitles don't keep up. This is especially unfortunate for foreign movies where I need to be able to read the English subtitles.

Note: The subtitles work just fine, when watching the movies in VLC on my computer.

Any idea what's causing this and how I may be able to fix this? I tried the different compression and indexing settings (individually, and in every combination possible) for subtitles in MKVToolNix but it didn't make a difference.

**Comment by mbunkus** [comment]
I'm sorry, but I really cannot help you with that. I don't have such a device, I've not even heard of it before. Contact the vendor's support; you've paid money that thing, after all.
