### ISSUE TITLE
mkvtoolnix fails to build against boost 1.64

### ISSUE THREAD

**Issue by alucryd** [mbunkus/mkvtoolnix#1987]
Hi guys,

Arch Linux is in the process of bumping boost to 1.64 and mkvtoolnix 11.0.0 fails to build against it. To be more specific it fails at linking mkvinfo, here is the error:

```
src/common/libmtxcommon.a(ebml_chapters_converter.o): In function `mtx::xml::ebml_chapters_converter_c::fix_display(libmatroska::KaxChapterDisplay&) const':
ebml_chapters_converter.cpp:(.text+0x3e61): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
ebml_chapters_converter.cpp:(.text+0x4063): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
src/info/mkvinfo.o: In function `handle_ebml_head(libebml::EbmlElement*, std::shared_ptr<mm_io_c>, libebml::EbmlStream*)':
mkvinfo.cpp:(.text+0xeeb4): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
```

Could you please have a look?

**Comment by mbunkus** [comment]
That error message has nothing to do with Boost. To me it looks more like your libebml has to be re-built, too.

**Comment by alucryd** [comment]
You were right, although I'm not sure why building against boost 1.63 worked with the current libebml build. Thanks for pointing me in the right direction.

**Comment by mbunkus** [comment]
You're welcome. I cannot tell you why it happened the way it did, but such errors are often indicators of having part of the object files built with a different compiler, different compiler version or different flags (e.g. `--std=…`) than other object files. Therefore re-building everything from scratch is often the best course of action.

**Comment by alucryd** [comment]
Looks like GCC 7.1.1 was pushed to our testing repository a couple days ago so that's probably the culprit then, thanks for the explanation.

**Comment by mbunkus** [comment]
That would definitely be the prime candidate for the culprit.
