### ISSUE TITLE
Warning with mp3/ac3 audio

### ISSUE THREAD

**Issue by Bazzu85** [mbunkus/mkvtoolnix#1988]
Hi,

with some files I have this warning:
"This audio track contains xxx bytes of invalid data which were skipped before timecode 00:01:00.000000000. The audio/video synchronization may have been lost."

there's a option to avoid these type of warning?

**Comment by mbunkus** [comment]
No, there isn't.

**Comment by Bazzu85** [comment]
thx for quick reply!

**Comment by mbunkus** [comment]
You're welcome.
