### ISSUE TITLE
Gapless mp3 muxing

### ISSUE THREAD

**Issue by andoruB** [mbunkus/mkvtoolnix#1989]
Is it possible to make audio muxing gapless? So far I've only encountered this problem when appending together mp3 files, but it might happen with other formats as well. When those audio files don't have a silent beginning and/or end, I can hear the gap in between the tracks in the muxed video/audio file.  
This might be related to issue #747, but the files I appended didn't give any errors in the job output.

**Comment by mkver** [comment]
With the introduction of the `DiscardPadding` element, Matroska can in principle be used for gapless playback. But my bet is that most players will ignore these elements (in particular if they appear in the middle of a file). And of course the muxers like MKVToolNix needed to be adapted, too, which is nontrivial.
If you still have the source, the safest way is to encode your music in one piece and use chapters for navigation.

**Comment by andoruB** [comment]
> If you still have the source, the safest way is to encode your music in one piece and use chapters for navigation.

Yeah, that's what I was doing previously, but that would imply I would have to transcode the mp3 files, which is never a good idea...

**Comment by mbunkus** [comment]
At the moment it isn't possible without re-encoding it before. I have no plans on working on this.
