### ISSUE TITLE
TMDb API Support

### ISSUE THREAD

**Issue by zero77** [mbunkus/mkvtoolnix#1991]
Can you add an option to search TMDB and import artwork for TV shows and films.
As this would help speed up and automate the process of adding thumbnails to files.

Additionally, I previously suggested IMDB but there APIs didn't support this or only supported it for paid users although TMDB does support this.

https://themoviedb.org/documentation/api

Thanks

**Comment by mbunkus** [comment]
Maybe. Not within the next couple of months, though, as I'll be unavailable for several weeks.

**Comment by zero77** [comment]
OK, thanks.

**Comment by remuxer32** [comment]
Fantastic idea. I fully support it. I will be using artworks from my favourite movies & TV shows, too.

**Comment by mbunkus** [comment]
I really have no interest in implementing this. Sorry.
