### ISSUE TITLE
always cover option in MKVToolNixGui?

### ISSUE THREAD

**Issue by TammysHead** [mbunkus/mkvtoolnix#1992]
Hey,
in the attachments you can add a cover.png, but i must copy it everytime for every video. Could you add a option, which allows to set a specific cover for every video i multiplex?

**Comment by mbunkus** [comment]
No, sorry. Such a requirement is a niche requirement, something unique to your situation.

You can achieve something similar by writing your own script that executes "mkvpropedit" after multiplexing and attaches an image. Then configure the GUI to execute that script after each job.

**Comment by mkver** [comment]
There actually already is such an option: Open your preferences and go to the page with the multiplexer's default values. Add the [appropriate command line](https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.attachments) for including your cover. This should do what you wanted it to do.

**Comment by TammysHead** [comment]
@mkver i tried "--attachment-mime-type image/jpeg \ --attach-file C:\Users\Administrator\Desktop\cover.png \", but it didn't work. How do i do this? :/

**Comment by mkver** [comment]
You have to delete the "\" between these two commands (that's just line continuation) and you should also set the correct mime-type for png ("image/png", not "image/jpeg").

**Comment by mbunkus** [comment]
Using the "additional command line options" for this is a good idea, @mkver.

You don't have to set the MIME type at all, BTW. mkvmerge will automatically detect it. You're more likely to get it wrong, as shown above (MIME type `image/jpeg` but file has a `.png` extension indicating `image/png`).
