### ISSUE TITLE
Direct3DCreate9Ex() call breaking compatibility of all GUI and one CLI tool(s) on Windows NT5.1 & NT5.2

### ISSUE THREAD

**Issue by GrandAdmiralThrawn** [mbunkus/mkvtoolnix#1993]
In versions 11.0.0 and 12.0.0, some tools of mkvtoolnix stopped working on Windows NT 5.1 (XP) and NT5.2 (XP x64, Server 2003). 32- and 64-bit versions are similarily affected.

This concerns all GUI tools, but also the CLI tool 'mkvinfo', because those tools now call Direct3DCreate9Ex() from d3d9.dll, a function only present since NT 6.0 (Vista, Server 2008). The mkvmerge, mkvpropedit and mkvextract CLI tools are unaffected. The legacy d3d9 version of that function would be Direct3DCreate9(), I guess.

I assume this is due to the use of Qt Multimedia since 11.0.0.

Since XP / XP x64 and Server 2003 are no longer supported, this might not get fixed, but I still wanted to report it. Maybe it can be fixed at least for mkvinfo (it shouldn't even need anything from d3d9.dll, when used without a GUI?)

**Comment by mbunkus** [comment]
No. It won't get fixed, not even for mkvinfo.

**Comment by mbunkus** [comment]
To be more precise: yes, this is due to the tools using Qt Multimedia and that using the Windows Media Foundation Framework. The Media Foundation Framework is simply a prerequisite for MKVToolNix >= v11.

**Comment by GrandAdmiralThrawn** [comment]
I see. Thank you for the clarification.
