### ISSUE TITLE
Feature request: use ANSI colors for output

### ISSUE THREAD

**Issue by basicmaster** [mbunkus/mkvtoolnix#1994]
Under Linux etc. it is possible to use [ANSI escape code colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) on the console to highlight the text output.

It would be quite useful if mkvmerge etc. used such colors where appropriate, because this way the relevant details (e.g. filenames or codecs) can be perceived faster.

**Comment by mbunkus** [comment]
This isn't something I want to spend time on.
