### ISSUE TITLE
mkvmerge MPEG-2 video in MP4 written with invalid CodecID V_MPEG70

### ISSUE THREAD

**Issue by cementboy** [mbunkus/mkvtoolnix#1995]
Hello,

I used mkvmerge 12.0.0 on an MP4-contained video file.  The input file plays perfectly well with VLC media player.  The video codec of the input file is MPEG-2.

After muxing to Matroska using mkvmerge, the resulting output file does not display video and plays as audio only.  The video format for the output file is 'V_MPEG70'.

This behaviour is reproducible with both mkvmerge gui and cli on Ubuntu 16.04.  As a workaround, I am using ffmpeg (`ffmpeg -i 01.mp4 -map 0 -c copy  01.mkv`) to ensure that everything displays correctly.  Interestingly, this only occurs with MPEG-2 in an MP4 container; muxing MKV to MKV works fine.

I've attached a short portion of the MP4 input file for reference.

Thanks.

[01.zip](https://github.com/mbunkus/mkvtoolnix/files/1027186/01.zip)

**Comment by mbunkus** [comment]
Thanks. I'll look into it, but it'll take a while as I'll be away for several weeks.

**Comment by mbunkus** [comment]
Oh, I can reproduce the issue with the same you've provided. So I shouldn't need anything else for analysis.

**Comment by remuxer32** [comment]
New pre-builds for Windows that contain the fix have been uploaded here:

- https://mkvtoolnix.download/windows/pre/
