### ISSUE TITLE
[REQ] Adding or appending file dialog box - remember previous selection

### ISSUE THREAD

**Issue by vanowm** [mbunkus/mkvtoolnix#1997]
It would be nice if "adding or appending files" window would remember previous used option and automatically default to it.
![image](https://cloud.githubusercontent.com/assets/511517/26524181/fe2a568e-42f8-11e7-89e6-c40f557cc4a8.png)

Thank you.

**Comment by hubblec4** [comment]
Nice idea! 
For my testings I use the GUI, and then I have 20 or more files which will be appended and 20 more files with the same procedure.

With the "Remember Last Action" option it would be easy for such a case.

**Comment by mbunkus** [comment]
Thanks. I'll implemented it. However, it'll take a while as I'll be unavailable for several weeks.
