### ISSUE TITLE
12.0 Windows Installer unsigned

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1999]
Hello,

I know you had [issues with the installers of 12.0](https://forum.doom9.org/showthread.php?p=1807438#post1807438), but they aren't completely solved: Currently, the installers for 12.0 are unsigned. The latest pre-builds are already signed again. I don't know if you already know this, but I wanted to inform you just in case.

Greetings
Andi

**Comment by mbunkus** [comment]
Yeah, I know. That's due to me having to rebuild the installers manually as the original installers reported the wrong version numbers.

I won't replace the existing installers with signed ones as the binaries they include are still signed.
