### ISSUE TITLE
Allow enable/disable selected tracks in input tab as with attachments

### ISSUE THREAD

**Issue by jbn-github** [mbunkus/mkvtoolnix#2000]
Currently in MKVToolnix GUI one can select one or more attachments, right-click for the context menu, and choose to enable or disable the selected set of attachments.

It would be good to have the same functionality in the context menu for selected tracks in the input tab.

In version 12.0.0 the context menu on the input tab has no choices for enabling/disabling only the selected tracks. One can enable/disable all of the tracks, select tracks of a type (video, audio, or subtitle), or open in MediaInfo.

Thanks for considering this.

**Comment by mbunkus** [comment]
You can already enable/disable all selected tracks either with the keyboard or with the mouse:

  * Hitting `enter` will check/uncheck all selected items at once. With a single press of said key.
  * Using the mouse you can check/uncheck all selected items at once by changing the drop down box on the right labeled "copy this item". Yes, one such change applies to all selected items.

See [this short video](https://www.youtube.com/watch?v=QET-MifgJLM) as a demonstration.

I don't like duplicating functionality, therefore I won't add that in the context menu.
