### ISSUE TITLE
mkvtoolnix gui complains of adding attachment of the same name, even if source attachment is disabled

### ISSUE THREAD

**Issue by jtanx** [mbunkus/mkvtoolnix#2001]
Observed with 12.0.0: I often replace source attachments with my own versions, where the replacement file often has the same name as an attachment in the source file. However, the gui complains of adding an attachment of the same name, even if the source attachment has already been disabled, e.g.:

![snip](https://cloud.githubusercontent.com/assets/5137410/26545032/83c8d554-44a7-11e7-955e-846b271411c1.png)

Ideally it should not complain about this if the source attachment has been disabled, or even an option to just completely turn off this warning would be good - I don't recall this happening in previous versions of mkvtoolnix. Thanks

**Comment by mbunkus** [comment]
Thanks. I'll fix that behavior. However, it'll take a while as I'll be unavailable for several weeks.

**Comment by remuxer32** [comment]
New pre-builds for Windows that contain the fix have been uploaded here:

- https://mkvtoolnix.download/windows/pre/

**Comment by jtanx** [comment]
Thanks, it seems to work ok 👍
