### ISSUE TITLE
mkvtoolnix GUI font-face bug

### ISSUE THREAD

**Issue by kulaLin** [mbunkus/mkvtoolnix#2003]
mkvtoolnix GUI default font is "Segoe UI",

but using this font in Chinese language OS

"Segoe UI" Chinese(CJK characters) part not fallback to sans-serif font like a "Microsoft Jhenghei UI" or "Microsoft Yahei UI"

Please fix it 
![sshot-2017-05-31- 1](https://cloud.githubusercontent.com/assets/17091825/26594206/5985ed84-4599-11e7-8797-bcab713d30e4.png)
![sshot-2017-05-31- 2](https://cloud.githubusercontent.com/assets/17091825/26594263/8ec254c4-4599-11e7-8806-572190fc2cd8.png)

Thanks.

**Comment by mbunkus** [comment]
Thanks for the report, but to be honest, I won't spend any time on this. I don't have a Chinese Windows available to test with, and I seriously lack to the time at the moment and in the foreseeable future.

**Comment by kulaLin** [comment]
Don't ignore this bug.

Please fix it.

**Comment by mbunkus** [comment]
See my comment above. Additionally you can easily change the font used in the preferences.
