### ISSUE TITLE
SSA Does Not Work

### ISSUE THREAD

**Issue by ddelella** [mbunkus/mkvtoolnix#2004]
I am attempting to merge an MP4 file with two SSA subtitles.  One of the subtitles is English, full, and the other is English, forced.  I used SubTitle Edit to make sure the SSA files are correct.  They play fine in Plex when not merged into a MKV container.  I was able to merge the SRT version of the subtitles with the MP4 but the SSA version runs successfully but does not show the subtitles.  I have tried via command line in mkvmerge and through the GUI.  I also confirmed SSA does not work with mkvmerge v11.  Here is the command line code I am using (note: it is for a batch merge).

for %x in (*.mp4) do mkvmerge -o "%~nx.mkv" "%~nx.mp4" --language "0:eng" --track-name "0:English" "%~nx.eng.ssa" --language "0:eng" --track-name "0:Forced" --forced-track "0:yes" --default-track "0:yes" "%~nx.eng.forced.ssa"

**Comment by mkver** [comment]
It would probably be helpful if you could upload a sample. And have you already tested other players than Plex (like MPC-HC or VLC)?

**Comment by mbunkus** [comment]
This is almost certainly a missing feature in your player (Plex). Try a good software player as @mkver has asked you to. I'm pretty sure the subtitles will work just fine with those players.

I'm going to close this issue as not being a bug in MKVToolNix. If neither MPC-HC nor VLC can play the SSA subtitles in Matroska, then please say so here and we can re-open it.
