### ISSUE TITLE
GUI: Invalid value in total progress bar for multiple jobs running

### ISSUE THREAD

**Issue by engycz** [mbunkus/mkvtoolnix#2005]
How to reproduce: Start two jobs simultaneously
I will fix it.
```
Progress= 92, Total Progress= 46, m_queueNumDone=0, runningProgress= 92, m_toBeProcessed.count()=2, m_queueNumDone=0
Progress= 94, Total Progress= 47, m_queueNumDone=0, runningProgress= 94, m_toBeProcessed.count()=2, m_queueNumDone=0
Progress= 95, Total Progress= 47, m_queueNumDone=0, runningProgress= 95, m_toBeProcessed.count()=2, m_queueNumDone=0
Progress= 96, Total Progress= 48, m_queueNumDone=0, runningProgress= 96, m_toBeProcessed.count()=2, m_queueNumDone=0
Progress= 97, Total Progress= 48, m_queueNumDone=0, runningProgress= 97, m_toBeProcessed.count()=2, m_queueNumDone=0
Progress= 98, Total Progress= 49, m_queueNumDone=0, runningProgress= 98, m_toBeProcessed.count()=2, m_queueNumDone=0
Progress= 99, Total Progress= 49, m_queueNumDone=0, runningProgress= 99, m_toBeProcessed.count()=2, m_queueNumDone=0
Progress=100, Total Progress= 50, m_queueNumDone=0, runningProgress=100, m_toBeProcessed.count()=2, m_queueNumDone=0
Progress=  1, Total Progress= 33, m_queueNumDone=1, runningProgress=  1, m_toBeProcessed.count()=2, m_queueNumDone=1
Progress=  2, Total Progress= 34, m_queueNumDone=1, runningProgress=  2, m_toBeProcessed.count()=2, m_queueNumDone=1
Progress=  3, Total Progress= 34, m_queueNumDone=1, runningProgress=  3, m_toBeProcessed.count()=2, m_queueNumDone=1
Progress=  4, Total Progress= 34, m_queueNumDone=1, runningProgress=  4, m_toBeProcessed.count()=2, m_queueNumDone=1
Progress=  5, Total Progress= 35, m_queueNumDone=1, runningProgress=  5, m_toBeProcessed.count()=2, m_queueNumDone=1
Progress=  6, Total Progress= 35, m_queueNumDone=1, runningProgress=  6, m_toBeProcessed.count()=2, m_queueNumDone=1
Progress=  8, Total Progress= 36, m_queueNumDone=1, runningProgress=  8, m_toBeProcessed.count()=2, m_queueNumDone=1
Progress= 10, Total Progress= 36, m_queueNumDone=1, runningProgress= 10, m_toBeProcessed.count()=2, m_queueNumDone=1
```

**Comment by remuxer32** [comment]
Thank you for your fix. At the moment Moritz Bunkus (the owner of MKVToolNix) is out of town, and he will be unavailable for several weeks, so you will have to be patient for any action from him.

About your entry in the NEWS.md: when we add an entry to the "**Bug fixes**" section, we always add the word `Fixes` before a number of an issue. For example: **Fixes #21523**. Therefore in your case the correct form should be like this: 

`MKVToolNix GUI: fixed computation of value of total progress bar for multiple jobs running. Fixes #2005.`

I know it's a trifle but very important (at least for me). Thanks to that we know which issue was fixed (the word `Fixes` helps us to localize a proper issue, and also informs us that the particular one was successfully fixed).

**Comment by engycz** [comment]
Thanks for the suggestion. Fixed.

**Comment by mbunkus** [comment]
Thanks for the report & the PR; highly appreciated. As @mkver has said I'm currently out sick. I'll take care of this (testing & merging your PR) in a couple of weeks.

**Comment by remuxer32** [comment]
> As @mkver has said I'm currently out sick.

Well, in **THIS** particular issue **@mkver** hasn't said anything; that was me, **remuxer32** (see above) ☺.

**Comment by mbunkus** [comment]
Oops, you're right, of course. Sorry :)

**Comment by mbunkus** [comment]
Works fine, merged, thanks.

**Comment by sneaker2** [comment]
For me the bar in the GUI (bottom right) now always goes empty after having completed the queue. Is this intended?
Top: 12.0.0, Bottom: 13.0.0
![mkvmerge_100perc_progress-fs8](https://user-images.githubusercontent.com/8726180/27843506-a8e1bebc-6114-11e7-811a-781cb0905627.png)

**Comment by mbunkus** [comment]
That's definitely not intentional on my party.
