### ISSUE TITLE
mkvextract -- sub replace

### ISSUE THREAD

**Issue by thezoggy** [mbunkus/mkvtoolnix#2007]
have a mkv with several subs, two of the subs have a spelling error and I want to fix it.
so right now I can extract fix then remux, doing this via cli is not fun because you have to keep track of several flags (default/forced/language/track_name/etc) to get it back to what it was before. 

is there a way to just extract sub, fix, then just insert sub back into the existing spot... so it just keeps the same settings but updates the sub?

**Comment by mkver** [comment]
If your mkv doesn't use crc elements (which enable to test whether the file has been altered (the usual presumption being that an altered file is a damaged file)) and your corrections don't change the length of the subtitles (length in bytes; Matroska uses UTF-8 to store text subtitles and not every character in UTF-8 uses the same number of bytes), the you can use an hex editor to make your corrections. You can use mkvinfo's feature to display everything to find the spot where the subtitle packet that you want to change is located. But you should be sure to make a copy of your file before you do this.
If your changes change the length in bytes of the subtitle packets, then an in-place modifier is impossible. MKVToolNix doesn't have the feature you want in-built, but someone with scripting experience should be able to automate the task you want.

**Comment by mbunkus** [comment]
@mkver has pretty much answered the question. There's indeed no functionality that keeps all of a track's settings but replaces its content. I won't implement such functionality either.
