### ISSUE TITLE
VOB audio not recognized

### ISSUE THREAD

**Issue by donglacville** [mbunkus/mkvtoolnix#2008]
Hello, I am trying to remux this VOB file below using MKVToolNix GUI v12.0.0 but the two audio tracks are not recognized and the result file couldn't be played either even though the size is still about the same as the original VOB.

https://mega.nz/#!e4tgCbzL!19_SbwbSpgSKZug1vIPtFMkG-2ZbGtLlv5uLaKfrpm0

I'm using Media Player Classic and it plays the VOB file just fine but not the MKV. I was able to get around by remuxing it first in tsMuxeR but if you could get this fixed that would be much better.

Thank you very much in advance...

**Comment by mkver** [comment]
I can reproduce this; and looking into a the remuxed file with a hex editor I found that the audio is put into video blocks; but not blocks of their own: It is put into the same blocks as video. That's why the filesize doesn't shrink and why it is completely unplayable.

**Comment by donglacville** [comment]
I see, but in that case the problem still lies at what causes MKVToolNix not recognizing the audio streams in the first place right? I didn't extract this VOB file out of a DVD (someone did and I don't know whom) so I think the way they did it might have something to do with this...

**Comment by mkver** [comment]
When I extract the audio with FFMpeg, it has some garbage at the beginning. That garbage probably triggers a bug in MKVToolNix. I don't know enough about program streams to say more. But garbage in audio tracks is sometimes used to signal a delay (it's done that way in avi because there is no easy way to signal a delay in avi); maybe this served a similar aim in this file?

**Comment by remuxer32** [comment]
New pre-builds for Windows that contain the fix have been uploaded here:

- https://mkvtoolnix.download/windows/pre/

**Comment by donglacville** [comment]
thank you!
