### ISSUE TITLE
When splitting, seek BACK to previous keyframe

### ISSUE THREAD

**Issue by mew1033** [mbunkus/mkvtoolnix#2013]
Would it be possible to, when splitting a file, choose whether to skip forward to the next keyframe (possible now), or _back to the previous keyframe_? This would help in removing commercials. I don't mind if a small bit of commercial is left in, but I don't want to miss any of the file.

**Comment by mbunkus** [comment]
That's not possible at the moment, and I have no plans for implementing it either.
