### ISSUE TITLE
about add font file

### ISSUE THREAD

**Issue by bluelovers** [mbunkus/mkvtoolnix#2015]
![2017-06-17-20-53-05-1](https://user-images.githubusercontent.com/167966/27253071-5996e576-539f-11e7-8fc3-01d109ae126d.jpg)

i try add a ttf font 
but it show as video

it that is right or something wrong?

[font.zip](https://github.com/mbunkus/mkvtoolnix/files/1082544/font.zip)

**Comment by mbunkus** [comment]
Unfortunately several video formats have a very lose structure causing frequent mis-detections. This is nothing I can really fix.

However, adding fonts in that place is the wrong thing to do anyway. You don't add fonts on the "input" tab (only video, audio, subtitle files are added there), but on the "attachments" tab.

**Comment by bluelovers** [comment]
i try drag font to attachments tab, but it make crash

**Comment by mbunkus** [comment]
See [here](https://github.com/mbunkus/mkvtoolnix/wiki/Crash-when-adding-attachments).
