### ISSUE TITLE
Error in wiki page

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2017]
Hello,

from [here](https://github.com/mbunkus/mkvtoolnix/wiki/Appending-files-vs.-adding-as-additional-parts):
"For Blu-ray discs your best option is actually not to add the .m2ts files manually but not add one of the playlist files (the .mpls from the »PLAYLISTS« sub-directory)."
It should be "but to" instead of "but not".

Grüße
Andi

**Comment by remuxer32** [comment]
Thank you for the hint. Of course you're right and that's an error, but it's not the only one; there are more things which should be fixed, e.g. missing commas, Blu-ray disc → Blu-ray Disc (it's a product name), some typos etc. I will fix it myself.

**Comment by remuxer32** [comment]
Fixed in b819ae7.

**Comment by remuxer32** [comment]
@mbunkus 

I propose to add a new label: Wiki — it will be useful for such issues where users report errors in Wiki pages. Thanks.

**Comment by mbunkus** [comment]
Thanks for fixing it. The "documentation" label suffices for wiki issues.
