### ISSUE TITLE
srt not recognised

### ISSUE THREAD

**Issue by Anddre** [mbunkus/mkvtoolnix#2018]
I get a "file format unknown" when trying to add a srt

**Comment by mkver** [comment]
Then you should upload your file. You can upload it to Moritz's ftp-server or directly to GitHub (I think you need to rename it to txt so that you can upload it).

**Comment by remuxer32** [comment]
About FTP server, here's a guide how to upload sample files:

- https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server

**Comment by mbunkus** [comment]
As @remuxer32 has said, I'll need the SRT file.

**Comment by mbunkus** [comment]
I'll state this again: please upload the SRT file in question to my FTP server. Otherwise I cannot help you and will close the issue again.

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
