### ISSUE TITLE
File fragmentation

### ISSUE THREAD

**Issue by minalGoel** [mbunkus/mkvtoolnix#2019]
The output file of mkvtoonix is always fragmented and as the videos are large files so it is definitely cool to have them lying fragmented in the harddisk. Hope you will look into this. A possible solution may take an idea from utorrent's pre-allocation for files as it stops files from getting fragmented.

**Comment by mbunkus** [comment]
I will not invest any time on this.

**Comment by sneaker2** [comment]
With torrent you have the advantage of knowing the exact size even before you write the very first byte. When writing mkv files this is more difficult.
