### ISSUE TITLE
Warning messages since v13.0

### ISSUE THREAD

**Issue by Marc66** [mbunkus/mkvtoolnix#2023]
I installed version 13.0 this morning and processed a mpeg ts from a TV recording as I normally do and got the following warnings when I loaded the file. I don't have these warnings when I do the same in version 12.0. Running OSX 10.11.6 in French language

The TS file had 1 video and 2 audio streams and no special or accented characters in its name

Could not initialize the iconv library for the conversion from ISO6937 to UTF-8. Some strings will not be converted to UTF-8 and the resulting Matroska file might not comply with the Matroska specs (error: 22, Invalid argument).
Could not initialize the iconv library for the conversion from UTF-8 to ISO6937. Some strings cannot be converted from UTF-8 and might be displayed incorrectly (error: 22, Invalid argument).
Could not initialize the iconv library for the conversion from ISO6937 to UTF-8. Some strings will not be converted to UTF-8 and the resulting Matroska file might not comply with the Matroska specs (error: 22, Invalid argument).
Could not initialize the iconv library for the conversion from UTF-8 to ISO6937. Some strings cannot be converted from UTF-8 and might be displayed incorrectly (error: 22, Invalid argument).

**Comment by mbunkus** [comment]
I'll fix that for the next release. You can ignore those warnings until then as they don't affect the resulting file, or keep using v12.

**Comment by Marc66** [comment]
Thank you mbunkus

**Comment by welwood08** [comment]
FYI, I also see these warnings on Windows 8.1 so it's not specific to macOS.

**Comment by mbunkus** [comment]
@welwood08 The workaround (it's not a fix) I've implemented should work on all operating systems where that encoding isn't supported.
