### ISSUE TITLE
Subtitle Selection

### ISSUE THREAD

**Issue by C4Wiz** [mbunkus/mkvtoolnix#2024]
is it possible to add the ability to select only the forced subtitles within a subtitle track? (like MakeMKV can)

<img width="341" alt="screen shot 2017-06-25 at 8 21 43 am" src="https://user-images.githubusercontent.com/3883521/27516878-6e0b6582-597f-11e7-8dcb-5a68a0241196.png">

**Comment by mbunkus** [comment]
No, and I have no intention of spending time on this either.
