### ISSUE TITLE
Splitting Mode function by duration is not working correctly...

### ISSUE THREAD

**Issue by jon96789** [mbunkus/mkvtoolnix#2025]
When I split a a file by duration, the set time does not work... e.g. If i split for 9 seconds, it splits at 10 seconds... Also, it does not allow you to split duration in smaller increments, such a microseconds.

**Comment by mbunkus** [comment]
This is not a bug; see [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/Splitting-imprecise).
