### ISSUE TITLE
EBML tokens in portuguese

### ISSUE THREAD

**Issue by FernandoJefferson** [mbunkus/mkvtoolnix#2027]
I'm using mkvinfoto extract information from mkv files.
Depending on which directory I am, EBML tokens appears in different languages, as can be seen below.
I would like to have the tokens always in English, since I use a table of tokens to parse the generated output.
How to force mkvinfo to produce tokens only in English?
Thanking for any information,
Fernando Jefferson

```
C:\Program Files\MKVToolNix>mkvinfo teste.mkv
+ Cabeçalho EBML
|+ Versão do EBML: 1
|+ Versão de leitura EBML: 1
|+ Extensão máxima do ID do EBML: 4
|+ Extensão máxima do tamanho do EBML: 8
|+ Tipo de documento: matroska
```

```
C:\Users\Fernando\TesteMKV>mkvinfo teste.mkv
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ EBML maximum ID length: 4
|+ EBML maximum size length: 8
|+ Doc type: matroska
```

**Comment by mbunkus** [comment]
Add `--ui-language en`.

**Comment by FernandoJefferson** [comment]
Tanks
