### ISSUE TITLE
DVD Subtitles are missing

### ISSUE THREAD

**Issue by letianxia** [mbunkus/mkvtoolnix#2030]
When I merged DVD Files from "Live On Tour 2001 - Eric Clapton", the result is subtitles are missing

**Comment by mbunkus** [comment]
Reading subtitles directly from DVD files is not supported and will never be supported.

**Comment by mkver** [comment]
Some more info: The color palette the subtitles use isn't stored in the vob-files, but in the ifo-files and mkvmerge doesn't contain a parser for ifo-files. Therefore it can't copy the subtitle tracks. And it also doesn't copy the chapters.
But there is a program that can do this: MakeMKV. It's free while in beta. (And it seems to be in beta status forever.)
