### ISSUE TITLE
suggestion: shortcuts to move to the next and previous tab

### ISSUE THREAD

**Issue by mmdd87** [mbunkus/mkvtoolnix#2032]
Dear mkvtoolnix-team,
can you add shortcuts to move to the next and previous tabs:
https://abload.de/img/reiter4vu9d.jpg

This shortcuts or alternative a batch conversion for many episodes of series would be awesome!
Special thanks in advance and greatings from Germany.

**Comment by mbunkus** [comment]
See #1972.
