### ISSUE TITLE
Change shortcuts not to clash with manual input of characters via Alt+Number keys 

### ISSUE THREAD

**Issue by JoseRivera777** [mbunkus/mkvtoolnix#2034]
On previous version I can type the character "ñ" and "Ñ", but not on this version. (I normally call the track name "Audio en Español" translate to English is "Audio in Spanish or Spanish Audio". Please fix this little error. And thanks for the great program!!!!

Note: This Characters "á, é, í, ó, ú" works perfectly fine.

**Comment by JoseRivera777** [comment]
Note I type this characters by Holding the "Control key" and typing this numbers on the numeric path on the right side of the keyboard (not the ones located on the top row of the keyboard) 
á = 160
é = 130
í = 161
ó = 162
ú = 163
ñ = 164
Ñ = 165

**Comment by mbunkus** [comment]
If that input method doesn't work, then that's likely due to the GUI library used, Qt. There's nothing I can do about that.

**Comment by mkver** [comment]
He probably means Windows' Alt (not Ctrl) method of typing CP-1252 characters. The problem is that Alt+4 and Alt+5 opens the header/chapter editor.
Possible solution: Use Ctrl+Alt+Number instead of Alt+Number to switch between multiplexer, header/chapter editor, job queue and results.

**Comment by mbunkus** [comment]
Ah, I see. I'll think about changing the shortcuts. Problem is that Ctrl+Altt+Number is used by certain Linux window managers/desktop environments by default. The shortcut space is rather crowded already...

**Comment by mkver** [comment]
Correction: If you use Windows and type Alt+three digit decimal without leading zero, you actually use codepage 850; if you use Alt+four digit decimal with leading zero, you input CP-1252. For me, somehow both input method work even if the numpad is deactivated; and in this mode, MKVToolNix' shortcuts aren't triggered so I can use this to type the characters not working for JoseRivera777. Is this only my system or is this already a solution?

**Comment by mbunkus** [comment]
I don't think that'd be the best course of action. Laptop keyboards often only have the numeric keys as numpad keys but not the numlock-off variants.

So far my research yields Ctrl+Alt+Number as the most appropriate solution.

**Comment by JoseRivera777** [comment]
Thanks for the help, but I can't find the way to use CTRL+ALT+_number_ to bring á, é, í, ó, ú, ñ, Ñ. I google it and I can't find anything related to use CTRL+ALT+_number_ key, the only one I found is ALT+_number_. Can somebody please help me, thanks for everything. (I have been thinking to use previous version of MKVtoolNIX, I think is the best option)

**Comment by mkver** [comment]
CTRL+ALT+number is not designed to produce á etc. It is designed to be used to switch between the different parts of MKVToolNix: Right now Alt+4 leads you to the header editor (except if you already were at the header editor) and so you can't type ñ by Alt+1+6+4. Now MKVToolNix' shortcuts have been changed to Ctrl+Alt+number so that they don't interfere with Windows Alt method of typing non-ASCII characters anymore.
The above is based upon my understanding of your problem and on my own experience of typing ñ. It presumes that you are actually trying to use Alt+Number right now, not Ctrl+Number as you said in your second post.
Oh, and the above change of course doesn't work for you right now: Your version of MKVToolNix doesn't have the change included.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include the fix have been uploaded (build number 01522 and higher).

**Comment by BluBb-mADe** [comment]
This "fix" broke German keyboard layout keys. It now is not possible any more to write "[" and "{" with the normal keyboard layout.

**Comment by mbunkus** [comment]
I know; see #2056. The shortcuts have already been removed which effectively solves both issues. You can use the pre-builds linked from #2056 (or build your own packages from the git repo if you aren't using Windows).

**Comment by BluBb-mADe** [comment]
My bad I should've checked the recently closed issues.

**Comment by mbunkus** [comment]
No worries.
