### ISSUE TITLE
GUI Deselcting top level Track does not deselect appended Tracks

### ISSUE THREAD

**Issue by Qowy** [mbunkus/mkvtoolnix#2039]
Hi,
I just had to append 2 times 4 mkv files into one. While doing this I deselected the video track from one of the batches of 4. However doing this I did not deselect the three following ones which lead to an error along the lines of "does not contain a track with the ID 0, or that track is not to be copied. The argument for '--append-to' was invalid." during muxing.
It took me a while to notice that I needed to deselect them, too.
Why is this the case? Is there a usecase for it (since it does not seem to work anyway)?

**Comment by mbunkus** [comment]
You're right; there's no usecase for it. I'll fit it. Thanks.

**Comment by hubblec4** [comment]
In an earlier version it was enough to deselct the "main" track. All works fine and appended tracks was still checked.
But it would be nice if in the GUI all appended tracks are deselect also.

**Comment by mbunkus** [comment]
> But it would be nice if in the GUI all appended tracks will be also deselected.

That's my plan at the moment. The only question is whether activating the main track should activate all appended ones, too, even if they're not selected. I'm leaning in the direction of "yes", for consistency's sake.

**Comment by mbunkus** [comment]
> In an earlier version it was enough to deselect the "main" track. All works fine and appended tracks was still checked.

I'm pretty sure that MKVToolNix GUI never worked that way. It was probably the old mmg in which this had been implemented properly.

**Comment by hubblec4** [comment]
> The only question is whether activating the main track should activate all appended ones, too, even if they're not selected. I'm leaning in the direction of "yes", for consistency's sake.

Yes, of course. The user will preserve the main track and so all appended tracks should be used too and also selected.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include this are available (build numbers 01527 and higher).
