### ISSUE TITLE
Audio is always out of sync

### ISSUE THREAD

**Issue by ajaxxa** [mbunkus/mkvtoolnix#2041]
Hi, I'm writing to you because with the latest versions of mkvtoolnix-gui, the movies that I collect always come with audio in advance of the video.
Audio and video are extracted from untouched films in .mkv, so they are perfectly synchronized.
I insert the video track
I insert the audio track
Start multiplexing
Audio is ahead of the video of about 125ms/130ms

Toolnix version: latest 64bit version

I apologize for my English, but I'm Italian and I'm writing with google translator

**Comment by mbunkus** [comment]
Why are you adding audio and video files? Don't you have both audio and video in a single source file?

It sounds like you're extracting the tracks from the source file into two separate files, and then you add the two extracted files to MKVToolNix. Don't do that : during extraction important information is lost: the timestamps. Without that information synchronizing both tracks automatically is impossible.

Instead just add the original file containing both audio and video to MKVToolNix.

**Comment by ajaxxa** [comment]
The fact is that the untouched movie is too big, so I have to do a lighter rip with handbrake!

The strange thing is that with the old versions of toolnix this problem did not happen!

**Comment by mbunkus** [comment]
Have you actually tried an older MKVToolNix version with the same files you're having the problem right now?

**Comment by ajaxxa** [comment]
This problem occurs with all the movies!
The fact is I do not remember what the old version did not give these problems, but it is about 4 or 5 backwards versions!

**Comment by mbunkus** [comment]
Again my question. Are you extracting the tracks into individual files? If so, there's nothing I can do about that as you're losing information during that process.

If you want to use Handbrake for recoding, then you do not have to extract the tracks first if I remember correctly.

**Comment by ajaxxa** [comment]
But handbrake unfortunately does not extract the original audio track.

**Comment by mbunkus** [comment]
That may be, but your method loses important information required for sync. There's no bug to fix in MKVToolNix.
