### ISSUE TITLE
Support Variables And Wildcards

### ISSUE THREAD

**Issue by zero77** [mbunkus/mkvtoolnix#2043]
Can you please add support for mkvtoolnix to recognise variables and wildcards.

For example:

`find /home/administrator/Desktop/*/*.mp4`
`FILE=*.mp4`

`/usr/bin/mkvmerge --output '/home/administrator/Desktop/"$FILE.mp4"' '(' '/home/administrator/Desktop/*/"$FILE.mp4"' ')' --attachment-name poster.jpg --attachment-mime-type image/jpeg --attach-file /home/administrator/Desktop/*/poster.jpg`

Thanks

**Comment by mbunkus** [comment]
No, sorry. Wildcard handling is the shell's job, and it's doing just fine in that regard. What you (probably) want to achieve can be done like this already:

```shell
for FILE in /path/to/the/sources/*.mp4 ; do 
  mkvmerge --output "${FILE%mp4}mkv" '(' "${FILE}" ')' 
done
```

I'm not sure what you really mean with that `--attach-file` example, but attaching multiple files at once can be scripted with the shell, too.

**Comment by zero77** [comment]
Ok thank you, I was trying to attach a poster.jpg to an mp4 file with an unknown name in an unknown directory and them move it to a known directory. That’s why I asked for the variables and wildcards support.
