### ISSUE TITLE
Packaging: "The mkvmerge executable was not found"

### ISSUE THREAD

**Issue by ctreleaven** [mbunkus/mkvtoolnix#2044]
Hi:  I'm updating the MacPorts packaging of mkvtoolnix.  We use the --prefix option to direct where the software should be installed (default is /opt/local but other locations are also used).  The gui, however, throws up a dialog saying "The mkvmerge executable was not found".

What do I need to patch so that the gui knows where to find this program?

**Comment by mbunkus** [comment]
The GUI looks for the mkvmerge binary in several locations:

1. the directory the GUI's executable is located in,
2. the directory that [`QCoreApplication::applicationDirPath()`](https://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath) returns,
3. the parent directory of what [`QCoreApplication::applicationDirPath()`](https://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath) returns,
4. any directory in `$PATH` or the platform's equivalent; checking is done by [`QStandardPaths::findExecutable()`](https://doc.qt.io/qt-5/qstandardpaths.html#findExecutable)

These are tried in order, and the first directory with a `mkvmerge` file in it wins.

The code that looks up that path is [`mtx::gui::Util::Settings::exeWithPath()`](https://github.com/mbunkus/mkvtoolnix/blob/master/src/mkvtoolnix-gui/util/settings.cpp#L616).

Using `--prefix` usually works just fine; I use it all the time for testing purposes. The binaries will then be `${prefix}/bin/mkvmerge` and `${prefix}/bin/mkvtoolnix-gui`. You can have override that `bin/`, too, by using `configure`'s `--bindir` argument. That argument applies to all binaries, GUIs and CLI ones.
