### ISSUE TITLE
json.hpp include path changed

### ISSUE THREAD

**Issue by marillat** [mbunkus/mkvtoolnix#2048]
Hi,

Debian force the installation of json.hpp in /usr/include when upstream is supposed to install this file in /usr/include/nlohmann

This issue should be fixed in the next Debian package and thus mkvtoolnix will not find json.hpp

Tell me if you intent to do a new release soon.

See https://bugs.debian.org/868112

**Comment by mbunkus** [comment]
I see. I'll look into it. The next version will likely be released in two, maybe three weeks.

**Comment by mbunkus** [comment]
BTW, that Debian bug talks about `$libdir/nlohmann/json.hpp`. I can only hope that this is a typo, and that `$includedir/nlohmann/json.hpp` was actually meant. The AUR package mentioned installs the file as `/usr/include/nlohnmann/json.hpp`. And that's what I'll make `configure` check for, definitely not in `/usr/lib`.

nlohmann's json.hpp is a header-only "library". Therefore talking about `$libdir` doesn't make much sense…

**Comment by marillat** [comment]
Yes, I think it is a typo in the bug report.
