### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by bigfloo** [mbunkus/mkvtoolnix#2049]
Since my windows 10 updated , i cant launch mkvtoolnix : dll error, when i have reinstall i have got this error message

Your windows installation seems to lack Microsoft "media foundation" framework

I didnt find this framework

Regards

**Comment by mkver** [comment]
Do you have an N or KN version of Windows (the ones without Windows Media Player)? In this case, you don't have the Media Foundation Framework by default. But Microsoft offers it for free if I am not mistaken.

**Comment by mbunkus** [comment]
See [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/DLLs-not-found).
