### ISSUE TITLE
Link in documentation not working

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2050]
Hello,

the documentation for mkvmerge contains this link: [https://mkvtoolnix.download/doc/mkvmerge-identification-output-schema.json](https://mkvtoolnix.download/doc/mkvmerge-identification-output-schema.json). But the actual link should probably go to [this link](https://mkvtoolnix.download/doc/mkvmerge-identification-output-schema-v8.json) for version 8 of the json identification format.

Greetings
Andi

**Comment by mbunkus** [comment]
Thanks.
