### ISSUE TITLE
GUI: file name uniqueness not checked on starting to multiplex

### ISSUE THREAD

**Issue by florincoter** [mbunkus/mkvtoolnix#2052]
Hi,
1. Unique names does not work, at least not as in the prev ver.
2. At the end of a job the status line is automatically cleared from 100% to 0%.

Thank you,
Florin.

**Comment by mbunkus** [comment]
Please give a lot more details for 1., at least a list of steps you've taken, what you've seen the GUI do, what you had expected it to do and what the content of the corresponding directory were at that point. I've verified that the feature works just fine for me.

The second bug has already been fixed.

Please don't list multiple bugs in the same issue in the future. Using separate issues for separate bugs makes tracking the resolution process much easier. Thanks.

**Comment by florincoter** [comment]
Thank you for the answer.
My error! Only one bug per issue. Sorry.
As to 1.
- Win 7 64bit.
- load avi, srt.
- start multiplexing, output dir as source dir
- modified language on srt
- start multiplexing again
- got a question overwrite or cancel. did cancel, nothing happened. then overwrite and got the same file without (1) appended. I preferences "ensure the file name is unique" is activated (v). In prev version I got no dialog, but a second file with (1) appended.
Thank you,
Florin.

**Comment by mbunkus** [comment]
Ah, I see. Thanks. Yeah, the file name is only checked on certain occasions (when you add/remove files, when you toggle tracks on/off), and your workflow manages not to hit those occasions. I'll add another check when muxing is started.

**Comment by florincoter** [comment]
That WAS fast! Thank you!

**Comment by mbunkus** [comment]
You're welcome. It was easy enough to fix; the proverbial one-line fix.
