### ISSUE TITLE
mkvtoolnix-13.0.0 fails to configure with dash

### ISSUE THREAD

**Issue by beandog** [mbunkus/mkvtoolnix#2054]
Per Gentoo bug - https://bugs.gentoo.org/show_bug.cgi?id=625936

ac/ax_docbook.m4 has the following broken code:
  for i in /usr/share/xml/docbook/stylesheet/xsl/nwalsh /usr/share/xml/docbook/stylesheet/nwalsh `ls -d /usr/share/{sg,x}ml/docbook/xsl-stylesheets* 2> /dev/null`; do

which causes this to trigger,

    AC_MSG_ERROR([DocBook XSL stylesheets are required for building.])

Simple patch:

```
--- ac/ax_docbook.m4.orig	2017-07-22 12:19:23.140459219 -0600
+++ ac/ax_docbook.m4	2017-07-22 12:20:02.957460653 -0600
@@ -8,7 +8,7 @@
 
 else
   AC_MSG_CHECKING([for DocBook XSL root directory])
-  for i in /usr/share/xml/docbook/stylesheet/xsl/nwalsh /usr/share/xml/docbook/stylesheet/nwalsh `ls -d /usr/share/{sg,x}ml/docbook/xsl-stylesheets* 2> /dev/null`; do
+  for i in /usr/share/xml/docbook/stylesheet/xsl/nwalsh /usr/share/xml/docbook/stylesheet/nwalsh `ls -d /usr/share/sgml/docbook/xsl-stylesheets* /usr/share/xml/docbook/xsl-stylesheets* 2> /dev/null`; do
     if test -f "$i/manpages/docbook.xsl"; then
       DOCBOOK_ROOT="$i"
       break
```

**Comment by mbunkus** [comment]
Thanks.

**Comment by mbunkus** [comment]
BTW, what I wanted to prevent was the shell aborting if there are no matches to the globs (e.g. zsh does that by default, bash does, too, if the `failglob` option is on.
