### ISSUE TITLE
Multiplexor source listviews, column headers position not persistant 

### ISSUE THREAD

**Issue by 791** [mbunkus/mkvtoolnix#2057]
Need to add code to save header positions. So to return to same on startup as previous.

**Comment by mbunkus** [comment]
Thanks for the suggestion, but this won't be implemented. I've tried to come up with *good* ways to make this work, but Qt (the GUI toolkit I'm using) is just not making it easy at all as there's basically no way to tell whether resizing of columns was initiated by the GUI itself or by the user.

I won't spend any more time on this.

**Comment by mbunkus** [comment]
It turned out not to be that hard after all.

**Comment by remuxer32** [comment]
New pre-builds for Windows that contain the new feature have been uploaded here:
- https://mkvtoolnix.download/windows/pre/
