### ISSUE TITLE
Default-language Precedence over Defined "Undefined" Language

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#2059]
Hello, when an MKV file has language purposefully set to "und", the `--default-language` tag does not override as expected when remuxed.

The source file...
`$ mkvmerge -J original.mkv | grep language`
>"language": "und",
"language": "und",
"language": "und",
"language": "und",

This does not work...
`$mkvmerge -o example.mkv --default-language en --language 1:fr original.mkv`

The result...
`$ mkvmerge -J example.mkv | grep language`
>"language": "und",
"language": "fre",
"language": "und",
"language": "und",

This works...
`$ mkvmerge -o example.mkv --language 1:fr --language 2:en --language 3:en original.mkv`

The result (this is what I expected originally)...
`$ mkvmerge -J example.mkv |grep language`
>"language": "und",
"language": "fre",
"language": "eng",
"language": "eng",

Is this the expected behavior?  Please advise.  Thank you.

P.S. - _Yes, I could use mkvpropedit if I was just changing the language, but what I was correcting other things too..._
`$ mkvmerge -o example.mkv --default-language en --language 1:fr -y 0:-1000 -y 1:-935 -y 2:-935 -y 3:-935 original.mkv --chapters "$title.chapters" --title "$title"`

**Comment by mbunkus** [comment]
You really have to provide more than something that's not even a full sentence. I cannot read minds and can't even make an educated guess at what you might mean.

**Comment by optimiz** [comment]
Oops.  Sorry, I pressed enter on the subject line, submitting too early!  I'm editing it now.  Hopefully it'll make more sense shortly.

**Comment by mbunkus** [comment]
Ah 😄 No problem.

**Comment by optimiz** [comment]
Not sure if it's useful to know or not, but that original MKV was created by **ffmpeg**.

**Comment by mkver** [comment]
Yes, this is expected behaviour: The --default-language is not used if the source container provides language information. Matroska is of course one of those containers that contain language information.

**Comment by optimiz** [comment]
Thanks, @mkver, to me, the language precedence expectation was...

>--language > --default_language > defined "undefined" > undefined (empty)

In other words, setting a `--default-language` should take precedence over a container's "undefined", since a source container like that is **not** providing a more definitive language selection than the chosen command line.

**Comment by mbunkus** [comment]
@mkvverge is correct. `--default-language` is not supposed to override the language the source container provides. [mkvmerge's man page](https://mkvtoolnix.download/doc/mkvmerge.html) makes this clear:

> Sets the default language code that will be used for tracks for which no language is set with the --language option and for which the source container doesn't provide a language.

mkvmerge's command line help is, unfortunately, more ambiguous, but that's due to all the descriptions having to be short or the `--help` text would be endlessly long.

If you want something like "use language XYZ for all tracks except for track 2", use `--language -1:XYZ --language 2:abc` for all affected files.

**Comment by optimiz** [comment]
I read the "_doesn't provide a language_" to be inclusive of a defined undefined, since undefined was (is?) not an actual language. An honest semantic mistake. Sorry for the trouble.

**Comment by mbunkus** [comment]
Perfectly understandable and nothing to apologize for. The GUI provides an option in the preference for that reason: it enables the GUI to set the default language for tracks whose language is set to `undefined`, too. However, that's the GUI where the user can verify the defaults set before starting to multiplex. For mkvmerge I prefer to have fewer options that do magical stuff.

Additionally there are many files where the video track's language is set to `undefined`. Switching those to a certain language is almost always an error as most video tracks don't contain any linguistic content (no written words etc.). There is a code for that: `zxx` = "no linguistic content/not applicable", but few people use it for video tracks. Again, there's an option in the GUI where the user can opt to have the default language only be applied to audio and subtitle tracks.

And again, the options are set when the file's added, and the user can verify the settings before multiplexing, but with mkvmerge verification can only occur once the file's been fully multiplexed — which can take a lot of time. Hence me not liking magic, automatically adjusting options in mkvmerge all that much. The fewer of those, the fewer opportunities for surprising the user are there.

**Comment by optimiz** [comment]
Thanks for the in-depth explanation, you make complete sense.  I'm in the minority since I usually tag the video track; especially, when it has embedded closed captions (EIA 608/708) -- as part of a workaround to the MKV container limitation you mentioned in #1717.

P.S. - _The_ `--language -1:en` _option you recommended is an excellent_ `--default-language en` _replacement for my particular workflow.  Thank you._

**Comment by mbunkus** [comment]
You're welcome. The disadvantage is that you have to repeat `--language -1:eng` for each input file. How much that annoys you depends on your workflow, of course.
