### ISSUE TITLE
Codec State hack wrongly described in the GUI

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2068]
Hello,

the GUI knows of a hack called [use_codec_state](https://github.com/mbunkus/mkvtoolnix/blob/master/src/mkvtoolnix-gui/merge/additional_command_line_options_dialog.cpp#L69), although hack is actually called [use_codec_state_only](https://github.com/mbunkus/mkvtoolnix/blob/master/src/common/hacks.cpp#L36). And codec state elements are used regardless of this hack; the difference is that the sequence headers are removed from the bitstream in case this hack is used (otherwise they are cloned into the codec state element). So the description is wrong.

Greetings Andi

**Comment by mbunkus** [comment]
Thanks. I'll fix that.

**Comment by mkver** [comment]
If I am not mistaken, your fix did not change the non-English translations of the text. Shouldn't you update the list of translatable strings so that your translators can do their work? (At least that's what you usually do in such circumstances.)

**Comment by mbunkus** [comment]
I don't always update the translations right after a commit that changes them. Often enough I simply forget about it. Other times I know I'm going to add several more strings to translate soon, and as each update is rather large in terms of git diff content, I try to keep the number of updates down a bit. I've updated the strings earlier today, though.
