### ISSUE TITLE
Update MD5 in FLAC?

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#2069]
Hello, as always, thank you for **mkvtoolnix**.  Can **mkvtoolnix** include its md5 routine during FLAC handling and update the md5 stored in STREAMINFO from both **mkvmerge** and **mkvextract**?

Example encounters...

---
1. When using a negative `--sync` value on MKV with a FLAC track, its md5 is not updated; the original FLAC md5 value is incorrectly populated into the output MKV.

`$ mkvmerge -o example1.mka -D input.mkv`
`$ mkvmerge -o example2.mka -D -y 1:-20000 input.mkv`

`$ mkvextract tracks example1.mka 0:example1.flac`
`$ mkvextract tracks example2.mka 0:example2.flac`

The stored md5 should be different...
`$ metaflac --show-md5sum example1.flac example2.flac`
>example1.flac:5f3683091622b767b01b2ddbbe754b95
example2.flac:5f3683091622b767b01b2ddbbe754b95

Testing fails...
`$ flac -t example1.flac example2.flac`
>example1.flac: ok                 
>example2.flac: ERROR, MD5 signature mismatch
---
2. When an MKV with a FLAC track is `--split`, the md5 from the original FLAC is incorrectly populated to each output file.  (Example output from `--split` basically mirrors the `--sync` example shown above.)
---
FLAC tracks extracted from these methods fail when accessed by **libFLAC**-dependent programs, like **Audacity** or **Sweep** (both fail after a partial load), and Xiph.org's own FLAC encoder/decoder (a forced reëncode hangs, while decoding fails outright).

Please advise.  Thank you.

**Comment by mbunkus** [comment]
In short: no. I'm well aware that appending and cutting invalidates the checksum. However, updating it would require decoding the whole stream, and libflac's API is atrocious to use: you're supposed to hand over control to libflac which in turn calls callback functions in your programs which must then produce data or signal "end of file". Signalling "I don't have data right now, return control to me" doesn't exist. And all that clashes badly with both mkvmerge's and mkvextract's design.

The only way to implement this would be to write my own FLAC decoder or copying libflac's code changing the API appropriately, neither of which I'm really willing to do.

I've therefore long decided not to support appending or splitting FLAC.

See also #953 of which this is a duplicate.

**Comment by optimiz** [comment]
Understood.  My search-fu failed to uncover #953, sorry about that.

**Comment by mbunkus** [comment]
Don't worry about it.

**Comment by mkver** [comment]
There are some flac encoders (FLACCL and the version of flake included in CUETools) that allow you to create flac files "without" an md5 checksum. "Without" actually means that the md5 is set to zero. This is treated as a missing md5 by the flac reference de/encoder when one tests the file (although this doesn't seem to be part of the actual file format and I don't see a reason why there shouldn't be a file with an all zero md5). So if MKVToolNix performs an operation that likely invalidates the md5 of the decoded audio data, it could set the md5 in the header to zero. That way these files would be known to not have a valid md5 instead of having a wrong md5.

**Comment by optimiz** [comment]
Good to know, @mkver, thanks.  My workaround uses **ffmpeg**, it extracts/demuxes FLAC from MKV with a corrected md5.  It's **libFLAC**-dependent, so I expected it would also hang or error out, but it _demuxes_ correctly, allowing subsequent editing/manipulation by Audacity, Sweep and sox.

For example, this outputs a usable FLAC (using the **mkvmerge** `--sync` example above as its source input)...
`$ ffmpeg -i example2.mka example2.flac`
`$ metaflac --show-md5sum example1.flac example2.flac`
>example1.flac:5f3683091622b767b01b2ddbbe754b95
example2.flac:dd9a416ed79dd7ee9f017c6f0b46fb0a

However, like **mkvmerge**, neither _remuxing_ nor _splitting_ with **ffmpeg** corrects the md5.  So, mimicking my **mkvmerge** `--sync` example with **ffmpeg** `-ss` also outputs an MKV with the same incorrect md5 copied from the source file...
`$ ffmpeg -ss 0:20 -i input.mkv -vn -acodec copy -f matroska example3.mka`
`$ mkvextract tracks example3.mka 0:example3.flac`
`$ metaflac --show-md5sum example1.flac example3.flac`
>example1.flac:5f3683091622b767b01b2ddbbe754b95
example3.flac:5f3683091622b767b01b2ddbbe754b95

At least now I know why it happens, and how interesting that it seems to be a common issue for FLAC in MKV in other programs too.

**Comment by trumpet205** [comment]
A little bit late, but if all you are doing is splitting FLAC file you can mimic it using the reference encoder  with --until and --skip function. I imagine this is how ffmpeg does it.

For more on this you can read it here: https://xiph.org/flac/documentation_tools_flac.html

If you do use mkvtoolnix to manipulate FLAC, just re-encode it with libFLAC afterward to generate a FLAC file with correct header. Yes the encoder will complain MD5 mismatch with the source file, but the generated file should be the same with corrected header.

**Comment by mbunkus** [comment]
Of course there are several things that could be done about this, but I really have no interest in including decoders / encoders in MKVToolNix.

**Comment by optimiz** [comment]
Thanks for the info, @trumpet205, it'll come in handy for some future workflow; however, the reference encoder doesn't support inputs other than WAV/FLAC/PCM, so one would need to use a different tool anyway --like **mkvtoolnix** or **ffmpeg**-- when the source FLAC is already embedded in another container.  For me, if forced to use an another tool, I'll use it 'til its capabilities are exhausted; in this particular workflow, **ffmpeg** is the most capable tool.

P.S. - _Admittedly, the examples I gave were a bit misleading, since they were selectively edited solely to demonstrate a particular issue; the actual, real-world input/output purpose was more than shown._
