### ISSUE TITLE
Install mkvtoolnix in Windows Server 2008 R2

### ISSUE THREAD

**Issue by lucobe** [mbunkus/mkvtoolnix#2073]
Hello, I installed the latest version (14) in Windows Server 2008 R2, but I could not execute because of the lack of the EVR.DLL file, I already read the explanation here in that url: https://github.com/mbunkus/mkvtoolnix/wiki/DLLs-not-found

I did not find any version of the Media Feature Pack for Windows Server 2008 R2, does it really exist? If so, please tell me the download link.

**Comment by mbunkus** [comment]
I don't think so. Which means that I don't support Windows Server 2008 R2 anymore after all — I wasn't too sure about the availability of the pack. Sorry.

**Comment by mbunkus** [comment]
A quick Google search found [this](https://support.microsoft.com/en-us/help/963697/how-to-install-windows-media-services-for-windows-server-2008-r2) which you might try. But as I said, I don't/cannot support Server 2008 R2; I don't even have access to such an installation anymore.
