### ISSUE TITLE
HE-AACv2 audiostream is flagged with LC channels and samplingrate

### ISSUE THREAD

**Issue by Klaus1189** [mbunkus/mkvtoolnix#2074]
Hi mosu,
I have several mediafiles which contain a highly compressed HE-AACv2 audiostream and my Player displays the flagged channels and samplingrate from LC "part" (?).
If I use header editor to change it from 1 Channel to 2 Channels and from 22.05 kHz to 44.1 kHz it is displayed right.
I sent you a link to a sample file.
If I did something wrong or you need more information let me know ;-)

**Comment by mbunkus** [comment]
Thanks. I'll look into it.

**Comment by Klaus1189** [comment]
The player decodes it just fine as stereo 44.1 kHz, but it displays the flagged channels and samplingrate as 22.05 kHz 1 channel in small info.

**Comment by mbunkus** [comment]
The sample rate information is most likely correct, but the channel count might not be. HE-AAC has the peculiar property that its content is sampled at half the output sampling frequency. Therefore 22.050 Hz in the track headers actually means an output of 44.100 Hz.

However, that's not the case for the channel count (though I don't know enough about HE-AACv2 yet to say for certain whether this is actually a bug or not).

**Comment by Klaus1189** [comment]
any news? :)

**Comment by mbunkus** [comment]
No.

**Comment by mbunkus** [comment]
The problem with that file is the ADTS AAC container format
itself. The ADTS container cannot contain all the information modern
AAC requires. Therefore the LOAS/LATM container was invented (M2TS is
an MPEG-2 transport stream as the outer container format, and all AAC
tracks in such a container are encapsulated in either an ADTS or a
LOAS/LATM container).

For example: in ADTS there are only two bits for the profile which
doesn't allow for signalling HE-AACv2. Another problem is the number
of channels for which only three bits are available.

ffmpeg (and thereby all players using ffmpeg's libraries for playback)
circumvents this by fully decoding an AAC frame and thereby
determining how many channels there actually are and which profile is
actually used. mkvmerge cannot do that as mkvmerge does not contain a
full AAC decoder (and it never will). So this boils down to it being a
design limitation of mkvmerge vs. a design limitation of the ADTS AAC
container format.

This bug (or rather: this design limitation) won't be fixed. If the
AAC track were encapsulated in LOAS/LATM (as DVB stations nowadays do
if they use HE-AACv2), mkvmerge would have no problem with the channel
count or the sampling frequency.
