### ISSUE TITLE
appending files, XAVC codec, Version 14, OS Windows 8.1

### ISSUE THREAD

**Issue by symiotic** [mbunkus/mkvtoolnix#2075]
Was appending files from same device ok when using another (lower quality) MP4 codec...
I switched to using a higher quality setting on my sony as200v actioncam, with XAVC implementation, it doesn't seem to be supported on mkvtoolnix as job runs and then finishes without creating new file.
So I tried, googling, doom9 forums, and guthub forum to see if supported or not, couldn't find answer, so hope you don't mind asking (if supported ever)?
Regards,
Sem.

**Comment by mbunkus** [comment]
Never heard of it, hence it's not supported, no.

**Comment by mkver** [comment]
This seems to be a standard H.264 stream inside a different container. The container format seems to be mxf and ffmpeg seems to handle this stuff; so you can use this to put the H.264 into Matroska. According to [this pdf](http://www.xavc-info.org/xavc/share/data/XAVC_SpecificationOverview_Rev2_2.pdf), this format uses quite a lot of padding that ffmpeg usually doesn't strip away. Therefore you might want to extract the H.264 stream from the Matroska file created by ffmpeg and remux it again with MKVToolNix which will get rid of the padding.
