### ISSUE TITLE
[MKVToolNix GUI:multiplexer][v14.0.0][os:Windows][type:question] IDX/SUB not recognized

### ISSUE THREAD

**Issue by aaaxx** [mbunkus/mkvtoolnix#2076]
I've got these subtitles in VobSub format that mkvtoolnix doesn't recognize. What I mean by that is they show up in the "Source files" box, but none of the tracks are displayed in the "Tracks, chapters and tags" box.

So, I thought you might want to take a look and see if you can figure out what's happening. I'll upload the file to your server, marked with the issue number.

**Comment by mbunkus** [comment]
No entries are found because all timestamps in that file are negative. There's no way for mkvmerge to translate those into positive ones automatically as the offset to use is unknown.

**Comment by aaaxx** [comment]
Ah, got it. Funny thing is, I opened the .idx file but never noticed the timecodes were negative.

For cases like this, maybe it would be a good idea to automatically try to read timecodes from the .sub file, if your vobsub parser supports it, because here they seem to be correct.

**Comment by mbunkus** [comment]
Maybe. However, such files are really rare. Yours is the first file anyone's ever sent me that has negative timecodes. I really think that other things are better to spend time on.
