### ISSUE TITLE
wrong timecodes in split mode

### ISSUE THREAD

**Issue by behroozramezani** [mbunkus/mkvtoolnix#2078]
Hello 
I split video file in CLI with  command
```
mkvmerge -o sample.mkv input.mkv --split timecodes:starttime,endtime
```
I add starting and ending time of the video part I wanna cut, to MKVMERGe But mkvmerge does not give me the output I expect from, The video output isn't exactly the same, how it cuts video isn't the one I entered in command.

**Comment by mbunkus** [comment]
This is [not a bug](https://github.com/mbunkus/mkvtoolnix/wiki/Splitting-imprecise).
