### ISSUE TITLE
MinCache in webm

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2079]
Hello,

at the moment MKVToolNix seems to set MinCache automatically for video tracks in webm (and sets it to 1). But MinCache (and MaxCache) are not allowed according to [the webm specs](https://www.webmproject.org/docs/container/).

Grüße
Andi

PS: What is the purpose of setting MinCache at all? Do players use the reference pseudo-cache system at all?

**Comment by mbunkus** [comment]
Why not? If I only wrote elements that players actually used, there would never be any kind of advancement. Heck, Matroska wouldn't exist in the first place.

**Comment by mkver** [comment]
But mkvmerge seems to always set the MinCache to 1 which is not very useful for players. There might be a useful value that could be conveyed to players using the MinCache, namely the number of reorder frames a video stream has (or what is essentially the same thing: The difference between (implicit) dts and (explicit) pts.). This is information players could actually use and that a muxer can easily calculate during muxing. (See [here](https://github.com/FFMS/ffms2/issues/301) for an issue arising from relying on guessing the number of reorder frames.) Would this be compatible with the pseudo-cache reference system (where is this system explained anyway?)?
PS: Yes, I know the above is definitely off-topic.

**Comment by mbunkus** [comment]
> But mkvmerge seems to always set the MinCache to 1…

Not entirely correct. If B frames are found, `MinCache` is set to 2. That value's not entirely useful or correct either, of course, as frames can depend on more than two frames in modern codecs.

> Would this be compatible with the pseudo-cache reference system (where is this system explained anyway?)?

I cannot answer either question. I guess it's not really explained anywhere and didn't go anywhere either. I'll just remove `MinCache` & `MaxCache` altogether.

**Comment by mbunkus** [comment]
See 52d51e78a8e4279e9746420c5c50ba7caa7d02fe

**Comment by mkver** [comment]
> Not entirely correct. If B frames are found, MinCache is set to 2. That value's not entirely useful or correct either, of course, as frames can depend on more than two frames in modern codecs.
This isn't true for all the files that I just checked: They always have `MinCache` set to 1, although they use reorder frames. I think I should add that most of these video tracks are H.264 tracks. (I know (?) that in order to make setting the fps work the H.264 packetizer itself takes care of this because of PAFF vs MBAFF stuff. Maybe this isn't set for H.264 tracks because the part with `v_bframes` isn't properly set by the H.264 output module?)
> I cannot answer either question. I guess it's not really explained anywhere and didn't go anywhere either. I'll just remove MinCache & MaxCache altogether.
Ok. The lack of explanation really explains why it isn't being used. If it isn't explained anywhere, shouldn't then the specs be updated, too?

**Comment by mbunkus** [comment]
Feel free to file bug reports against the specs.
