### ISSUE TITLE
CygWin compilation problem

### ISSUE THREAD

**Issue by gja822** [mbunkus/mkvtoolnix#2080]
I've got mkvtoolnix via git, autogen.sh, configure worked fine and even rake almost finished, but ended up with errors of missing libs:

      RANLIB src/output/libmtxoutput.a
        LINK src/mkvmerge.exe
/usr/lib/gcc/i686-pc-cygwin/5.4.0/../../../../i686-pc-cygwin/bin/ld: cannot find -lboost_filesystem
/usr/lib/gcc/i686-pc-cygwin/5.4.0/../../../../i686-pc-cygwin/bin/ld: cannot find -lFLAC
/usr/lib/gcc/i686-pc-cygwin/5.4.0/../../../../i686-pc-cygwin/bin/ld: cannot find -logg
/usr/lib/gcc/i686-pc-cygwin/5.4.0/../../../../i686-pc-cygwin/bin/ld: cannot find -lvorbis
/usr/lib/gcc/i686-pc-cygwin/5.4.0/../../../../i686-pc-cygwin/bin/ld: cannot find -logg
/usr/lib/gcc/i686-pc-cygwin/5.4.0/libstdc++.a(cow-stdexcept.o): In function `ZNSt11logic_errorC2ERKS_':
/usr/src/debug/gcc-5.4.0-1/libstdc++-v3/src/c++11/cow-stdexcept.cc:44: multiple definition of `std::logic_error::logic_error(std::logic_error const&)'
src/common/libmtxcommon.a(date_time.o):date_time.cpp:(.text$_ZNSt11logic_errorC2ERKS_[__ZNSt11logic_errorC2ERKS_]+0x0): first defined here

ogg, vorbis and boost are installed via CygWin pkg installation (and so, reside in /lib), most other libraries built manually (and are in /usr/local/lib)
CygWin is latest for x86, System is outdated but still working Vista SP2

**Comment by mbunkus** [comment]
I don't support compilation on Cygwin. The one method for compiling for Windows that I do support us cross-compilation with MXE. I simply don't have the time to support each and every possible development platform. l
