### ISSUE TITLE
MKVToolNix changes the height

### ISSUE THREAD

**Issue by Derp0** [mbunkus/mkvtoolnix#2082]
Hi.

I want to mux two h264 streams with exactly the same dimensions together, The problem is that the height of the second track is changed after muxing, even when I explicitly set the "Display width/height" values.

I have to change the height of the second track manually with the header editor.

> Video #1
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High 10@L5
Format settings, CABAC      : Yes
Format settings, RefFrames  : 16 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 1 h 58 min
Width                       : 1 280 pixels
Height                      : 692 pixels
Display aspect ratio        : 1.85:1
Frame rate mode             : Constant
Frame rate                  : 24.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Scan type                   : Progressive

> Video #2
ID                          : 2
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High 10@L3.1
Format settings, CABAC      : Yes
Format settings, RefFrames  : 5 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 1 h 58 min
Width                       : 1 280 pixels
Height                      : 704 pixels
Original height             : 692 pixels
Display aspect ratio        : 16:9
Original display aspect rat : 1.85:1
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Scan type                   : Progressive

If you need more info let me know, thanks.

**Comment by mbunkus** [comment]
mkvmerge does not and cannot change the height of a video track. Appending two video tracks with different heights is simply not supported in Matroska.

The _display_ height is another matter as that's not a property of the encoded video but rather a hint for the player to play the video at a certain height (which may involve scaling by the player). When appending video tracks there will only be one single video track, and that video track only has one display height. So if the display height of the two appended tracks were different before, they will definitely be identical after appending. That's simply how Matroska works.

If you do not mean "appending" (play video 2 after video 1) by "muxing together" but rather "have two tracks start at the same time and be able to switch between the two", then things are obviously different.

Show me the mux settings you've used (in the GUI: "Multiplexer" menu → "show command line").

**Comment by mbunkus** [comment]
Also show me the output of "mkvmerge -J video1.h264" for both video files.

**Comment by mbunkus** [comment]
And the MediaInfo output for both source video files.

**Comment by Derp0** [comment]
Sorry for the misleading title, I definitely didn't mean the actual height. No, I don't mean appending.

`"C:/Program Files/MKVToolNix\mkvmerge.exe" --ui-language en --output ^"C:\Track01.mkv^" --language 0:und --default-track 0:yes --compression 0:none ^"^(^" ^"C:\Track01.h264^" ^"^)^" --language 0:und --default-track 0:no --compression 0:none ^"^(^" ^"C:\Track02.h264^" ^"^)^" --track-order 0:0,1:0`

> {
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 4,
      "is_providing_timecodes": false
    },
    "recognized": true,
    "supported": true,
    "type": "AVC/h.264"
  },
  "errors": [],
  "file_name": "C:\\Track01.h264",
  "global_tags": [],
  "identification_format_version": 9,
  "track_tags": [],
  "tracks": [
    {
      "codec": "MPEG-4p10/AVC/h.264",
      "id": 0,
      "properties": {
        "packetizer": "mpeg4_p10_es_video"
      },
      "type": "video"
    }
  ],
  "warnings": []
}

> {
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 4,
      "is_providing_timecodes": false
    },
    "recognized": true,
    "supported": true,
    "type": "AVC/h.264"
  },
  "errors": [],
  "file_name": "C:\\Track02.h264",
  "global_tags": [],
  "identification_format_version": 9,
  "track_tags": [],
  "tracks": [
    {
      "codec": "MPEG-4p10/AVC/h.264",
      "id": 0,
      "properties": {
        "packetizer": "mpeg4_p10_es_video"
      },
      "type": "video"
    }
  ],
  "warnings": []
}

General
Complete name               : C:\Track01.h264
Format                      : AVC
Format/Info                 : Advanced Video Codec
File size                   : 555 MiB
Writing library             : x264 core 133 r2334 a3ac64b
Encoding settings           : cabac=1 / ref=16 / deblock=1:1:2 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=24.0 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / ip_ratio=1.40 / aq=1:0.60

Video
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High 10@L5
Format settings, CABAC      : Yes
Format settings, RefFrames  : 16 frames
Width                       : 1 280 pixels
Height                      : 692 pixels
Display aspect ratio        : 1.85:1
Frame rate mode             : Variable
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Scan type                   : Progressive
Writing library             : x264 core 133 r2334 a3ac64b
Encoding settings           : cabac=1 / ref=16 / deblock=1:1:2 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=24.0 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / ip_ratio=1.40 / aq=1:0.60



General
Complete name               : C:\Track02.h264
Format                      : AVC
Format/Info                 : Advanced Video Codec
File size                   : 187 MiB
Writing library             : x264 core 129 r2230+696+35 805d074 tMod [10-bit@all X86]
Encoding settings           : cabac=1 / ref=5 / deblock=1:-1:-2 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / fade_compensate=0.00 / psy_rd=2.00:0.70 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-4 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=4000 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=100 / rc=crf / mbtree=1 / crf=33.3333 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / ip_ratio=1.40 / aq=1:1.20 / zones=192,2615,b=1.666

Video
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High 10@L3.1
Format settings, CABAC      : Yes
Format settings, RefFrames  : 5 frames
Width                       : 1 280 pixels
Height                      : 692 pixels
Display aspect ratio        : 1.85:1
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Scan type                   : Progressive
Writing library             : x264 core 129 r2230+696+35 805d074 tMod [10-bit@all X86]
Encoding settings           : cabac=1 / ref=5 / deblock=1:-1:-2 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / fade_compensate=0.00 / psy_rd=2.00:0.70 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-4 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=4000 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=100 / rc=crf / mbtree=1 / crf=33.3333 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / ip_ratio=1.40 / aq=1:1.20 / zones=192,2615,b=1.666
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709

**Comment by Derp0** [comment]
Samples uploaded to FTP.

**Comment by mbunkus** [comment]
Thanks for the samples. I cannot reproduce your issue here with those samples. For both files the same height of 692 is detected and set in the output file:

```
[0 mosu@sweet-chili /ftp/pub/rip/mkv/bugs/2082_mkvtoolnix_changes_the_height] mkvmerge -o combined.mkv Track01.h264 Track02.h264
mkvmerge v15.0.0 ('Duel with the Devil') 64-bit
'Track01.h264': Using the demultiplexer for the format 'AVC/h.264'.
'Track02.h264': Using the demultiplexer for the format 'AVC/h.264'.
'Track01.h264' track 0: Using the output module for the format 'AVC/h.264 (unframed)'.
'Track02.h264' track 0: Using the output module for the format 'AVC/h.264 (unframed)'.
The file 'combined.mkv' has been opened for writing.
'Track01.h264' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1280/692.
'Track02.h264' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1280/692.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 0 seconds.
[0 mosu@sweet-chili /ftp/pub/rip/mkv/bugs/2082_mkvtoolnix_changes_the_height] mkvinfo combined.mkv|rg -i height
|   + Pixel height: 692
|   + Display height: 692
|   + Pixel height: 692
|   + Display height: 692
```

Your MediaInfo output agrees with mkvmerge's interpretation of the files. MediaInfo says that both have the same height of 692 pixels with the same display aspect ratio of 1.85:1.

So how exactly did you do to make that second video track come out with a different height?

**Comment by Derp0** [comment]
I used MKVcleaver to extract those samples. I did this with the original files and it worked (Same height). Maybe it was written to the header and MKVToolNix was reading from it ?
But I set the dimensions manually before, why didn't it overwrite any header ?

**Comment by mkver** [comment]
1. So the samples you uploaded weren't the ones that triggered this issue. You have presumably deleted those?
2. The display aspect ratio can (and usually is) stored in two places: The bitstream (i.e. the actual H.264 track in the file) and in the Matroska header, i.e. at the container level. Usually these two coincide (e.g. if you mux an elementary stream into Matroska with MKVToolNix, mkvmerrge will by default set the container aspect ratio so that it coincodes (up to rounding) with the ratio from the bitstream if available), but if they don't, the container level should take precedence. MKVToolNix usually leaves the bitstream level alone so if you set the aspect ratio during muxing, the container aspect ratio will be set accordingly, but the bitstream aspect ratio will stay as it was. And if you extract the bitstream with mkvextract (MKVcleaver uses mkvextract), it will not overwrite the bitstream aspect ratio with the one from the container level. The elementary stream does not contain the container level aspect ratio at all any more.
3. My guess is: You set the aspect ratio manually and made a mistake. But I want to note one more thing: As far as I know, Mediainfo's width and height always refers to the coded dimensions (video pixel dimensions in Matroska parlance), not the aspect ratio at all. mkvmerge doesn't offer an option to change the pixel dimensions* at all. So my refined guess is: You set the aspect ratio manually during muxing (namely to 16:9, i.e. to 1280/720) in a wrong way and then tried to repair this with the header editor, but you edited the wrong value. Anyway, I don't see any bug in MKVToolNix.

*: There is a cropping flag, though, which could be seen as a substitute, but it is unfortunately only supported by very few players.

**Comment by mbunkus** [comment]
In summary: this is not a bug.
