### ISSUE TITLE
Simplification of SSA structure

### ISSUE THREAD

**Issue by latot** [mbunkus/mkvtoolnix#2086]
Hi, i don't know if this request must be here, but lets try.

Actually SSA subtitles are very used, in fansubs is a massive example, but checking a little of how this works i found there is some uncomfortable things, is when we works with multiples fansubs or multiples RAWs.

Basically the SSA have 3 parts with bigger effect, Effects, Text and Timing, that means, if i want change a text problem we edit the file, like always.

But lets put this example, we have 2 RAWs of quality, and that means the timing probably change, we actually have the SSA of the first RAW, so if we want update the subtitles we need change only the timing in the original subtitles.

Now the second example, we have a RAW, but now we have the 2 subtitles, if we compare the must probable is the timing of both files will be the same, but if we want fix the timing we will need edit both files, and i want fix a text we will need go to the specific file and edit it.

With this examples i think now i can say the idea, i would like can insert in the MKV the subtitles splited in parts to can move easily one subtitle from one file to other and simplify in how works in the context of every video.

Lets move this to examples, Again, we have 2 RAWs and 2 fansubs, the construction of the subtitles i think can be like this:

1 timing file in both files
every RAW file will have a file with the text and effect to every timing

So, if i need fix the timing we only need update one part of the file, the same with the text but nice here is this, now we have other RAW, with their own fansub for example think is in other language (jp, rus, ex), so if i want use my subs i only need use my subs but configured to use the timing of the file, the means i can have only 1 timing file per RAW and adjust it without edit any other file, and the concept is repeated if i want change any other characteristic of the subs.

Well, i think this is the idea, is like construct the subs with the parts we can have inside the mkv, or other similar idea but with the same propose is can overwrite one "incomplete" sub file in a complete other, with that i think we can play a lot with it and we can work better with subs and moving between files (now RAWs and Subs).

Resume: split the subtitle in timing and text for example, can split concepts and facility from the user, in this example the user can download any text subs from a fansub with the current timing file and should works, or update RAWs from the user or the fansubs.

Well i feel i'm doing a lot of turns so lets finish for now.

Thx.

**Comment by mbunkus** [comment]
This is simply not how the Matroska container format works. In Matroska each frame (one dialog line in an SSA file) has a timestamp. Frames from different tracks aren't coupled at all. If you want to modify multiple entries at once, then you need other tools to do that for you, most likely when you still have those lines in external text files).

In my opinion there's pretty much zero chance that the changes that would be necessary to implement something like you want will be done in the existing programs that support Matroska, both on the producing and the consuming side. I don't have any interest in spending time on this myself either.
