### ISSUE TITLE
The output mkv file cannot play

### ISSUE THREAD

**Issue by tbago** [mbunkus/mkvtoolnix#2087]
Hi I use ffmpeg to demux  the video and audio track, and use mkvtoolnix to mux the mkv file. The old ffmpeg version works well, but when i use the new ffmpeg version, the out file cannot play. I compare the output file use mkvinfo. And find the **Seek entry (KaxCues)** is differ.
The error file mkv info is as following:

> |+ Seek head
| + Seek entry
|  + Seek ID: 0x15 0x49 0xa9 0x66 (KaxInfo)
|  + Seek position: 4099
| + Seek entry
|  + Seek ID: 0x16 0x54 0xae 0x6b (KaxTracks)
|  + Seek position: 4230
| + Seek entry
|  + Seek ID: 0x10 0x43 0xa7 0x70 (KaxChapters)
|  + Seek position: 4746
| + Seek entry
|  + Seek ID: 0x1f 0x43 0xb6 0x75 (KaxCluster)
|  + Seek position: 5872
| + Seek entry
|  + Seek ID: 0x1c 0x53 0xbb 0x6b (KaxCues)
|  + Seek position: 18446744073709551567
| + Seek entry
|  + Seek ID: 0x11 0x4d 0x9b 0x74 (KaxSeekHead)
|  + Seek position: 27615200
|+ EbmlVoid (size: 3993)

**Comment by mbunkus** [comment]
The seek position for the Cues looks wrong (seems like an integer underflow wrap-around). Please upload sample files (before they're muxed with mkvmerge!) to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by mkver** [comment]
Given that there is another seekhead at 27651200 referenced it seems that you used the `--clusters-in-meta-seek` switch, didn't you? Or did you use an ancient (and unsupported) version of MKVToolNix that created said list of clusters by default (this is also consistent with the absence of the seek entry for the tags that MKVToolNix writes for years now)? If it's the former, you should tell us if you used other nondefault command-line switches, or even better: Just tell us the command line used.

**Comment by mbunkus** [comment]
Again: please upload a sample file to my [FTP server](../../wiki/FTP-server). Without one I won't be able to do anything about this. Thanks.

**Comment by tbago** [comment]
Hi mbnkus, 
Thanks for you support. I have fixed this isssue. This is not mkvtoolnix issue.

**Comment by mbunkus** [comment]
Alright, good to hear.
