### ISSUE TITLE
libebml and libmatroska dependencies

### ISSUE THREAD

**Issue by susnux** [mbunkus/mkvtoolnix#2088]
First issue is just a very small nit: Since 15.0.0 mkvtoolnix requires libebml 1.3.5, but readme says 1.3.4.

Second issue: 15.0.0 also requires libmatroska 1.4.6 (or later), readme says 1.4.5 (also no note about this in the changelog).

If compiling with libmatroska 1.4.5 installed, it fails with:

> g++-6 -Wall -Wno-comment -Wfatal-errors -O3 -D_FILE_OFFSET_BITS=64 -DMTX_LOCALE_DIR=\"/usr/share/locale\" -DMTX_PKG_DATA_DIR=\"/usr/share/mkvtoolnix\" -DMTX_DOC_DIR=\"/usr/share/doc/mkvtoolnix\" -fstack-protector-strong -g -DDEBUG -fPIC -std=gnu++14 -Wnon-virtual-dtor -Woverloaded-virtual -Wextra -Wno-missing-field-initializers -Wno-maybe-uninitialized -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5 -I/usr/include/qt5/QtNetwork -I/usr/include/qt5 -I/usr/include/qt5/QtConcurrent -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5 -I/usr/include -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -include src/common/common_pch.h -I. -Ilib -Ilib/avilib-0.6.10 -Isrc -Ilib/utf8-cpp/source -c -MMD -MF ./rake.d/dependency.d/tmp/src_mkvtoolnix-gui_header_editor_value_page_moco.d -o src/mkvtoolnix-gui/header_editor/value_page.moco -x c++ src/mkvtoolnix-gui/header_editor/value_page.moc
> 
> src/merge/generic_packetizer.cpp: In member function 'virtual void generic_packetizer_c::set_video_projection_type(uint64_t, option_source_e)':
> src/merge/generic_packetizer.cpp:880:43: error: 'KaxVideoProjection' was not declared in this scope
>      auto &projection = GetChildEmptyIfNew<KaxVideoProjection>(GetChild<KaxTrackVideo>(m_track_entry));
>                                            ^~~~~~~~~~~~~~~~~~
> compilation terminated due to -Wfatal-errors.

**Comment by mbunkus** [comment]
Oops… indeed. Thanks, I'll fix that.
