### ISSUE TITLE
Gentoo Compilation Issue

### ISSUE THREAD

**Issue by rastio** [mbunkus/mkvtoolnix#2090]
Cannot compile media-video/mkvtoolnix-15.0.0-r1 on recently installed and now fully updated gentoo

kernel 4.12.5-gentoo x86_64
gcc version 5.4.0 (Gentoo 5.4.0-r3 p1.3, pie-0.6.5) 

previous version mkvtoolnix-13.0.0 compiled without issues (but this was July 10, multiple system updates were done since, but mkvtoolnix-13.0.0 worked until I tried to upgrade to version 15 few days ago)

Since 13.0.0 is not available in gentoo portage tree anymore, I have tried to emerge the only 'stable' version available - mkvtoolnix-9.6.0 and it compiled and runs.

Will be happy to provide any additional info requested.

Thanks

Rasto

```
src/info/mkvinfo.cpp: In function ‘void handle_video_projection(libebml::EbmlStream*&, libebml::EbmlElement*&)’:
src/info/mkvinfo.cpp:650:12: error: ‘KaxVideoProjectionType’ was not declared in this scope
     if (Is<KaxVideoProjectionType>(l5)) {
            ^
compilation terminated due to -Wfatal-errors.
```
```
src/merge/generic_packetizer.cpp: In member function ‘virtual void generic_packetizer_c::set_video_projection_type(uint64_t, option_source_e)’:
src/merge/generic_packetizer.cpp:880:43: error: ‘KaxVideoProjection’ was not declared in this scope
     auto &projection = GetChildEmptyIfNew<KaxVideoProjection>(GetChild<KaxTrackVideo>(m_track_entry));
                                           ^
compilation terminated due to -Wfatal-errors.
```

**Comment by mbunkus** [comment]
See #2088.

**Comment by rastio** [comment]
Thanks for quick support and sorry for the duplicate.
Dependencies for libmatroska are not yet fixed in gentoo portage tree, I had to manually upgrade libmatroska to 1.4.7.
Mkvtoolnix-15.0.0-r1 then compiled without errors and runs.

Rasto
