### ISSUE TITLE
AC3 Invalid Data not Stripped with Certain Delay Offsets

### ISSUE THREAD

**Issue by optimiz** [mbunkus/mkvtoolnix#2092]
Thanks for **mkvtoolnix**, it's a magnificent tool set.  When an AC3 (Dolby Digital) track has invalid data and is muxed _with video_ and a `--sync` value greater than -31ms, **mkvmerge** does not remove the invalid data before muxing.

A source file with an AC3 track with invalid bytes to use as an example...
`$ mkvmerge -i source.mkv`
File 'source.mkv': container: Matroska
Track ID 0: video (MPEG-1/2)
Track ID 1: audio (AC-3/E-AC-3)
Track ID 2: audio (FLAC)
Global tags: 1 entry
Tags for track ID 0: 1 entry
Tags for track ID 1: 1 entry
Tags for track ID 2: 2 entries

Extract the AC3 track so it can be hashed and the invalid bytes determined...
`$ mkvextract tracks source.mkv 1:invalid_data.ac3`
`$ xxd -l 1343 invalid_data.ac3`
>00000000: ed7e b65a 6568 a04d 208f 13ba 3b3d cc4d  .~.Zeh.M ...;=.M
[..._edited for brevity_...]
00000530: 73d8 8962 35ad b41d b1ad 0099 1d0b 77    s..b5.........w

The md5 hash of this above 6-channel AC3 example with 1,341 bytes of invalid data before the first sync word, and a "cleaned" version of it with the invalid bytes removed...

>4af22bc521f24a9158aa3a53b5484e56  invalid_data.ac3
db587f664109056bf48a8876881059da  cleaned.ac3

Create test MKVs with sync values from -40ms to +40ms against example source file, then demux each embedded AC3 file...
`$ for offset in {-40..40}; do mkvmerge -o test_$offset.mkv -a 1 -y 1:$offset example.mkv ; mkvextract tracks test_$offset.mkv 1:test_$offset.ac3 ; done;`
> [_This is repetitive output.  The interesting thing is here is that even when **mkvmerge** starts stripping the invalid bytes at -31ms, the invalid data warning is never displayed._] 

Each test MKV output file has an delay offset embedded; here's a small sampling of -25ms to -35ms...
`$ mediainfo test_-{25..35}.mkv |egrep -i '(name|delay)'`
>Complete name                            : test_-25.mkv
Delay relative to video                  : -57 ms
Complete name                            : test_-26.mkv
Delay relative to video                  : -58 ms
Complete name                            : test_-27.mkv
Delay relative to video                  : -59 ms
Complete name                            : test_-28.mkv
Delay relative to video                  : -60 ms
Complete name                            : test_-29.mkv
Delay relative to video                  : -61 ms
Complete name                            : test_-30.mkv
Delay relative to video                  : -62 ms
Complete name                            : test_-31.mkv
Delay relative to video                  : -34 ms
Complete name                            : test_-32.mkv
Delay relative to video                  : -35 ms
Complete name                            : test_-33.mkv
Delay relative to video                  : -36 ms
Complete name                            : test_-34.mkv
Delay relative to video                  : -37 ms
Complete name                            : test_-35.mkv
Delay relative to video                  : -38 ms

Now to compare the md5 hash of the AC3 files extracted from the MKV test files to the original invalid bytes one and its cleaned counterpart...
`$ md5sum test_*.ac3`
>4af22bc521f24a9158aa3a53b5484e56  test_40.ac3
4af22bc521f24a9158aa3a53b5484e56  test_39.ac3
4af22bc521f24a9158aa3a53b5484e56  test_38.ac3
4af22bc521f24a9158aa3a53b5484e56  test_37.ac3
4af22bc521f24a9158aa3a53b5484e56  test_36.ac3
4af22bc521f24a9158aa3a53b5484e56  test_35.ac3
4af22bc521f24a9158aa3a53b5484e56  test_34.ac3
4af22bc521f24a9158aa3a53b5484e56  test_33.ac3
4af22bc521f24a9158aa3a53b5484e56  test_32.ac3
4af22bc521f24a9158aa3a53b5484e56  test_31.ac3
4af22bc521f24a9158aa3a53b5484e56  test_30.ac3
4af22bc521f24a9158aa3a53b5484e56  test_29.ac3
4af22bc521f24a9158aa3a53b5484e56  test_28.ac3
4af22bc521f24a9158aa3a53b5484e56  test_27.ac3
4af22bc521f24a9158aa3a53b5484e56  test_26.ac3
4af22bc521f24a9158aa3a53b5484e56  test_25.ac3
4af22bc521f24a9158aa3a53b5484e56  test_24.ac3
4af22bc521f24a9158aa3a53b5484e56  test_23.ac3
4af22bc521f24a9158aa3a53b5484e56  test_22.ac3
4af22bc521f24a9158aa3a53b5484e56  test_21.ac3
4af22bc521f24a9158aa3a53b5484e56  test_20.ac3
4af22bc521f24a9158aa3a53b5484e56  test_19.ac3
4af22bc521f24a9158aa3a53b5484e56  test_18.ac3
4af22bc521f24a9158aa3a53b5484e56  test_17.ac3
4af22bc521f24a9158aa3a53b5484e56  test_16.ac3
4af22bc521f24a9158aa3a53b5484e56  test_15.ac3
4af22bc521f24a9158aa3a53b5484e56  test_14.ac3
4af22bc521f24a9158aa3a53b5484e56  test_13.ac3
4af22bc521f24a9158aa3a53b5484e56  test_12.ac3
4af22bc521f24a9158aa3a53b5484e56  test_11.ac3
4af22bc521f24a9158aa3a53b5484e56  test_10.ac3
4af22bc521f24a9158aa3a53b5484e56  test_9.ac3
4af22bc521f24a9158aa3a53b5484e56  test_8.ac3
4af22bc521f24a9158aa3a53b5484e56  test_7.ac3
4af22bc521f24a9158aa3a53b5484e56  test_6.ac3
4af22bc521f24a9158aa3a53b5484e56  test_5.ac3
4af22bc521f24a9158aa3a53b5484e56  test_4.ac3
4af22bc521f24a9158aa3a53b5484e56  test_3.ac3
4af22bc521f24a9158aa3a53b5484e56  test_2.ac3
4af22bc521f24a9158aa3a53b5484e56  test_1.ac3
4af22bc521f24a9158aa3a53b5484e56  test_0.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-1.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-2.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-3.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-4.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-5.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-6.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-7.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-8.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-9.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-10.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-11.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-12.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-13.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-14.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-15.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-16.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-17.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-18.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-19.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-20.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-21.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-22.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-23.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-24.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-25.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-26.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-27.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-28.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-29.ac3
4af22bc521f24a9158aa3a53b5484e56  test_-30.ac3
db587f664109056bf48a8876881059da  test_-31.ac3
db587f664109056bf48a8876881059da  test_-32.ac3
db587f664109056bf48a8876881059da  test_-33.ac3
db587f664109056bf48a8876881059da  test_-34.ac3
db587f664109056bf48a8876881059da  test_-35.ac3
db587f664109056bf48a8876881059da  test_-36.ac3
db587f664109056bf48a8876881059da  test_-37.ac3
db587f664109056bf48a8876881059da  test_-38.ac3
db587f664109056bf48a8876881059da  test_-39.ac3
db587f664109056bf48a8876881059da  test_-40.ac3

Please note: Even the no offset (`--sync 1:0`) MKV test and its AC3 extract still have the 1,341 invalid bytes, and exhibits a frame sync error on playback, as well...

`$ mpv --autoload-files=no test_0.mkv`
>Playing: test_0.mkv
 (+) Video --vid=1 (*) (mpeg2video)
 (+) Audio --aid=1 (*) (ac3)
[ffmpeg/audio] ac3: frame sync error
Error decoding audio.
AO: [pulse] 48000Hz 5.1 6ch float
Using hardware decoding (vdpau).
VO: [vdpau] 720x480 => 720x540 vdpau
 (+) Video --vid=1 (*) (mpeg2video)
 (+) Audio --aid=1 (*) (ac3)
     Subs  --sid=1 (eia_608)
AV: 00:00:01 / 00:05:04 (0%) A-V:  0.000
Exiting... (Quit)

While tracking this frame sync error issue down, I tested `--sync` values from -100ms to 1000ms (in 5ms increments) with the same results, -31ms was the turning point.  Please advise, thank you.

**Comment by mbunkus** [comment]
When reading audio from Matroska mkvmerge assumes that each Matroska block contains exactly one audio frame of valid data. That's how the specs say AC-3 must be stored in Matroska.

Invalid data will only be removed if the source does not already have such requirements, e.g. when reading raw AC-3 files or when reading it from MPEG transport streams (where AC-3 frames can span several MPEG PES packets or where one MPEG PES packet can contain multiple AC-3 frames).

This is a design choice. It's not a bug.

The reason that invalid data gets removed as soon as the delay exceeds a certain limit is simply that mkvmerge will only ever drop Matroska blocks if the resulting timestamp is less than 0. Your MediaInfo output suggests that the first audio block's timestamp in the source file is not at 0, but somewhere higher (~+31ms). So applying a delay of e.g. -20ms will only lower the timestamp for the first block in the output to +11ms. As there's no need to drop the packet, it will be kept (including the invalid data). As soon as your explicit delay exceeds those +31ms, the resulting timestamp of the first packet would be less than 0ms and therefore the packet is dropped.

**Comment by optimiz** [comment]
Thanks for the explanation, I understand the design choice.  And, yes, you're right, the first valid AC3 frame in the original source file starts at timestamp 62.  Sadly for me, I'll have to correct this file and the rest of its partner files in a more labor-intensive way.

`$ ffprobe -i source.mkv -show_frames -print_format csv`
>[ac3 @ 0x55cd3dccdba0] frame sync error
frame,audio,1,1,62,0.062000,62,0.062000,62,0.062000,32,0.032000,30097,1792,fltp,1536,6,5.1(side)side_data,AVMatrixEncoding,4
frame,audio,1,1,62,0.062000,62,0.062000,62,0.062000,32,0.032000,31896,1792,fltp,1536,6,5.1(side)side_data,AVMatrixEncoding,4
[...]

**Comment by mbunkus** [comment]
Write a short script that does the following:

1. Determine the timestamp offset of the first audio frame for the track via `mkvinfo -s …`.
2. Extract the audio track to a temporary file.
3. Merge the original file excluding the bad audio track with the extracted audio track from step 2 using the (positive) delay from step 1.

**Comment by optimiz** [comment]
I'll give your method a try, thanks for your help and guidance.

**Comment by mkver** [comment]
One more thing: Does the first Matroska block of  this audio track actually contain a valid AC3-frame or not? If not, then the delay should be set so that the first timestamp of the newly muxed audio track has the timestamp that the first block of the original file that contained a valid ac-3 frame had. (This would probably be 32ms more than the method just proposed would yield.)

**Comment by mbunkus** [comment]
Note that I've recently (after the release of v16) changed the AC-3 handling code to re-assemble frames if the core & the E-AC-3 extension are stored in different frames in order to fix the timestamps of such tracks being wrong. This may affect your solution to your particular issue, too. New pre-builds for WIndows that include that change are available [here](https://mkvtoolnix.download/windows/pre/).

**Comment by optimiz** [comment]
Thanks, I'll give it a try.
