### ISSUE TITLE
No Sound After Remuxing?

### ISSUE THREAD

**Issue by DDDespair** [mbunkus/mkvtoolnix#2095]
I'm trying to use MKVtoolnix Gui to split part of an mkv file and add audio & subtitles from an external file. However the resulting muxed file has no sound despite saying it contains the audio track. Same thing happens if I leave the original audio file selected instead- no audio on playback. I'm sure I must be doing something wrong but I'm not sure what. 

My setup is like the attachments show. The file does split more or less where I tell it to (I'm aware it will only split at key frames) and the subs may or may not be slightly off sync but I'm really unable to tell without the resulting file having audio. 
![mkv](https://user-images.githubusercontent.com/31939068/30402940-06903b70-98a5-11e7-8899-5c5c2a2943a2.png)
![mkv2](https://user-images.githubusercontent.com/31939068/30402957-19ed7278-98a5-11e7-8a03-88c1b579c408.png)

**Comment by mkver** [comment]
Actually you shouldn't type "--split parts:" into the field where you type the split points; you should actually get an error message for this and no file is muxed at all.

**Comment by mbunkus** [comment]
Splitting and appending FLAC is not supported at all. Sorry.

**Comment by mbunkus** [comment]
See #953 for more details why.

**Comment by mkver** [comment]
If one splits flac, one usually gets a file with a wrong md5 checksum (if one checked the checksum which normal players do not); but at least one gets a playable file with sound. But according to DDDespair's description this is not what happened, so there must be something else going on.

**Comment by mbunkus** [comment]
Maybe. Doesn't change the fact that I don't support it.

**Comment by DDDespair** [comment]
@mkver the details pane in windows explorer says the file has the flac audio. I didn't check with any application as I thought this was sufficient.

@mbunkus I thought it might be an issue with flac so I did tried wav instead and unfortunately got the same result. I'm going to guess that what mkver listed above is my actual issue so I'll have to edit my replacement audio and give it another try.

Thank you for both your help.
