### ISSUE TITLE
Strip repeating SPS/PPS away

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2096]
Hello,

would it be possible to create an option to strip repeating SPS/PPS away during muxing (from unframed content)? I have analyzed a lot of files and it seems that all ARD and ZDF channels never change their SPS/PPS. Thanks.

Grüße
Andi

PS: They also contain mostly useless SEI messages (about 40 bytes for every frame for ZDF) that do not really change from frame to frame (only the presence or absence of the recovery_frame-flag changes).

**Comment by mbunkus** [comment]
Sorry, but I'm really not interested in implementing such functionality.
