### ISSUE TITLE
File modified message when opening file over network with MKVToolNix GUI header editor

### ISSUE THREAD

**Issue by deusxanime** [mbunkus/mkvtoolnix#2097]
When opening an mkv file over the network in Header Editor, if I make a change and save, or seemingly even just after a while, and then try to save again I get message with title "File has been modified" (see screenshot for full message) and I have to close and reopen the file to make anymore changes. This gets cumbersome when editing multiple things like default/enabled/forced flags, name, language, etc like I like to do when I get new files. 

I have been able to get around this in the past by using MKVToolNix GUI directly on my file server which was previously a Windows Server 2012. By opening it directly on the local filesystem on the server I wouldn't get the file changed message no matter how many times I changed/saved it. I've just rebuilt my NAS server and now using unRAID for the OS rather than Windows, so that is no longer an option. I've seen this problem for a long time, maybe back since v8 or v9 when I first started using MKVToolNix GUI, and it still persists running v15.0.0 today.

I tried opening it via UNC path as well as mapped drive, but neither improves it.

![image](https://user-images.githubusercontent.com/11891866/30506009-f022df6a-9a3d-11e7-9e3f-c759539556aa.png)

**Comment by mbunkus** [comment]
Thanks for the report. I'll look into it. It probably is due to OS-level caching on both the client and the file server, and thereby resulting in different file modification timestamps.

At the moment I'm not sure I can reasonably check for external modification anymore, so maybe I'll just remove the check altogether.

**Comment by mbunkus** [comment]
Yeah it's due caching. Here's data from one of my tests:

1. First time "save" is called is at 12:29:46. Saving takes less than one second from the GUI's POV. Therefore it stores 12:29:46 as the last known modification time.
2. Second time "save" is called is at 12:31:39. The GUI now queries the operating system for the file's "last modification timestamp". The OS returns 12:30:05, which is higher than the timestamp remembered in step 1. Therefore the error is shown.

**Comment by remuxer32** [comment]
Fixed in `bfc4d7c`.
