### ISSUE TITLE
OPUS vbr 5.1ch with specific bitrate not played correctly

### ISSUE THREAD

**Issue by baudav** [mbunkus/mkvtoolnix#2099]
Sound vibrate each 2sec for 0.5sec after create MKV or Webm file with Opus 5.1 (but not reproduce with all Opus file).
example file created with mkvtoolnix, only VLC can read without sound problem; with all other player tested, sound is bad (MXPlayer android SW opus, KODI android,BSPlayer android; Chrome PC, all x265-opus work fine with MPC-HC, but not x264 or vp9; and firefox with webm report file corrupt; and sendto Youtube same problem)
MXPlayer android work only if use HW opus codec (but HW is limited to 2 channels)

[x265-Opus224k vbr](https://drive.google.com/open?id=0B-PnHjbdw-GwOVhxMEJuS2hOSjA)  work with MPC-HC and VLC, sound KO for all other player tested 

[x264-Opus224k vbr](https://drive.google.com/open?id=0B-PnHjbdw-GwVDZpUWNLSW00bzA) work only with VLC

[vp9-Opus224k vbr.webm](https://drive.google.com/open?id=0B-PnHjbdw-GwNlNVYXFLVzdWSWc) work only with VLC,.  firefox display file corrupt after read 1s without sound.

Not sure it's MKVtoolnix problem, if you can confirm or not...
Opus file used can be played in all player without problem, if extract it from MKV, no problem to read Opus file.

other files without problem, just use another opus bitrate.
[vp9-opus192.webm](https://drive.google.com/open?id=0B-PnHjbdw-GwQmVMSVo2WkNNT2M)
[x264-opus192](https://drive.google.com/open?id=0B-PnHjbdw-GwMXl4dFRpMnhoZ1E)
[x265-opus192](https://drive.google.com/open?id=0B-PnHjbdw-GwSE1odFNKamFIX2s)

thanks

**Comment by mbunkus** [comment]
Thanks for the report. I won't have time to look into it for a couple of weeks, though.

**Comment by mkver** [comment]
I looked into x264-Opus224k vbr and found this:
```
| + SimpleBlock (key, track number 2, 1 frame(s), timecode 1.980s = 00:00:01.980)
|  + Frame with size 576
| + SimpleBlock (track number 1, 1 frame(s), timecode 1.917s = 00:00:01.917)
|  + Frame with size 12894
| + Block group
|  + Block (track number 2, 1 frame(s), timecode 2.000s = 00:00:02.000)
|   + Frame with size 597
|  + Discard padding: 0.167ms (166667ns)
| + Block group
|  + Block (track number 2, 1 frame(s), timecode 2.020s = 00:00:02.020)
|   + Frame with size 595
|  + Discard padding: 0.167ms (166667ns)
| + Block group
|  + Block (track number 2, 1 frame(s), timecode 2.040s = 00:00:02.040)
|   + Frame with size 594
|  + Discard padding: 0.167ms (166667ns)
| + Block group
|  + Block (track number 2, 1 frame(s), timecode 2.060s = 00:00:02.060)
|   + Frame with size 588
|  + Discard padding: 0.167ms (166667ns)
| + Block group
|  + Block (track number 2, 1 frame(s), timecode 2.080s = 00:00:02.080)
|   + Frame with size 581
|  + Discard padding: 0.167ms (166667ns)
| + Block group
|  + Block (track number 2, 1 frame(s), timecode 2.100s = 00:00:02.100)
|   + Frame with size 600
|  + Discard padding: 0.167ms (166667ns)
| + Block group
|  + Block (track number 2, 1 frame(s), timecode 2.120s = 00:00:02.120)
|   + Frame with size 670
|  + Discard padding: 0.167ms (166667ns)
| + Block group
|  + Block (track number 2, 8 frame(s), timecode 2.140s = 00:00:02.140)
|   + Frame with size 587
|   + Frame with size 605
|   + Frame with size 650
|   + Frame with size 616
|   + Frame with size 606
|   + Frame with size 702
|   + Frame with size 595
|   + Frame with size 590
|  + Discard padding: 0.167ms (166667ns)
| + SimpleBlock (track number 1, 1 frame(s), timecode 2.083s = 00:00:02.083)
|  + Frame with size 3483
| + SimpleBlock (discardable, track number 1, 1 frame(s), timecode 2.000s = 00:00:02.000)
|  + Frame with size 1984
| + SimpleBlock (discardable, track number 1, 1 frame(s), timecode 1.958s = 00:00:01.958)
|  + Frame with size 1577
| + SimpleBlock (track number 1, 1 frame(s), timecode 2.042s = 00:00:02.042)
|  + Frame with size 1164
| + SimpleBlock (track number 1, 1 frame(s), timecode 2.167s = 00:00:02.167)
|  + Frame with size 3130
| + SimpleBlock (discardable, track number 1, 1 frame(s), timecode 2.125s = 00:00:02.125)
|  + Frame with size 1783
| + SimpleBlock (track number 1, 1 frame(s), timecode 2.208s = 00:00:02.208)
|  + Frame with size 40827
| + SimpleBlock (key, track number 2, 8 frame(s), timecode 2.300s = 00:00:02.300)
|  + Frame with size 592
|  + Frame with size 581
|  + Frame with size 570
|  + Frame with size 587
|  + Frame with size 585
|  + Frame with size 599
|  + Frame with size 581
|  + Frame with size 611
| + SimpleBlock (track number 1, 1 frame(s), timecode 2.250s = 00:00:02.250)
|  + Frame with size 20664
```
The opus track has blocks with DiscardPadding all over the place. This is exactly the same as [this ffmpeg ticket](https://trac.ffmpeg.org/ticket/4178). At that time @mbunkus concluded that this is not a bug in mkvmerge, but that the DiscardPadding elements are how the file should be; the implication is that the encoder is to be blamed for creating such files. This is supported by the output of opusinfo:
```
New logical stream (#1, serial: 7ae7fdb8): type opus
Encoded with unknown encoder; extracted from Matroska with mkvextract v15.0.0 ('Duel with the Devil') 64-bit
WARNING: Sample count ahead of granule (99840>99808) in stream 1
WARNING: Sample count ahead of granule (106560>106472) in stream 1
WARNING: Sample count ahead of granule (113280>113160) in stream 1
WARNING: Sample count ahead of granule (120000>119880) in stream 1
WARNING: Sample count ahead of granule (127680>127560) in stream 1
WARNING: Sample count ahead of granule (135360>135240) in stream 1
WARNING: Sample count ahead of granule (143040>142920) in stream 1
WARNING: Sample count ahead of granule (150720>150360) in stream 1
WARNING: Sample count ahead of granule (158400>157760) in stream 1
WARNING: Sample count ahead of granule (166080>165440) in stream 1
WARNING: Sample count ahead of granule (173760>173120) in stream 1
WARNING: Sample count ahead of granule (181440>180800) in stream 1
WARNING: Sample count ahead of granule (189120>188480) in stream 1
WARNING: Sample count ahead of granule (196800>196128) in stream 1
WARNING: Sample count ahead of granule (204480>203744) in stream 1
...

WARNING: Sample count ahead of granule (1579200>1572856) in stream 1
WARNING: Sample count ahead of granule (1584960>1578616) in stream 1
WARNING: Sample count ahead of granule (1589760>1583416) in stream 1
WARNING: Sample count ahead of granule (1595520>1589176) in stream 1
WARNING: Sample count ahead of granule (1601280>1594936) in stream 1
WARNING: Sample count ahead of granule (1607040>1600696) in stream 1
Opus stream 1:
	ERROR: stream 1 has interior holes or more than one page of end trimming
	WARNING: stream 1 has high muxing delay
	Pre-skip: 312
	Playback gain: 0 dB
	Channels: 6
	Original sample rate: 48000Hz
	Streams: 4, Coupled: 2
	Channel Mapping family: 1 Map: [0, 4, 1, 2, 3, 5]
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:   5100.0ms (max),  206.0ms (avg),  100.0ms (min)
	Total data length: 723144 bytes (overhead: 1.2%)
	Playback length: 0m:33.441s
	Average bitrate: 173 kb/s, w/o overhead: 170.9 kb/s
Logical stream 1 ended
```
This means that you should recapitualte exactly how these files were created and report it to the right place. (Which is probably the ffmpeg ticket already mentioned.) If you want to help to track this bug down, you should test whether you can still reproduce it with slightly changed settings (i.e. does it still happen if you directly pipe the source data into opusenc)?
Also notice that if I extract the opus track to an ogg/opus file and mux this file to Matroska with ffmpeg, there aren't any DiscardPadding elements and this file plays fine. As the opusinfo output shows this is actually a bug in ffmpeg's muxer. Also VLC seems to ignore the DiscardPadding elements which explains its "good" performance.

There might be an issue in MKVToolNix nevertheless: This file also has a lace with DiscardPadding; is it even defined what exactly should be discarded in this situation? Something at the end of every packet inside or only of the last packet? (Yes, I know that this is probably not the cause of this issue, but I wanted to mention it anyway.)

**Comment by baudav** [comment]
I not understand all.. but thanks for this analysis and detail. I understand my opus file is not good.   perhaps problem is the encoder used? and it's accentuated after use mkvtoolnix because it keeps the DiscardPadding elements  that only VLC ignore?
 I use **Xmedia Recode** to encode DTS or AC3 file to OPUS (it use opus library, if understand)

**Comment by mkver** [comment]
Yes, your files are defective; yes, MKVToolNix treats the file according to the specs whereas ffmpeg's muxer doesn't. And yes, programs that honour these DiscardPadding elements sound like garbage. At least that is my current opinion of this file.
PS: This is actually no longer appropriate for Xmedia RecodeCan you find out which version Xmedia Recode you use? And can you upload the first (say) 30 seconds of the original source file somewhere?

**Comment by baudav** [comment]
I no longer have the original file, and I have since updated xmedia recode; before I used 3.3.5.8.
I had not thought that this could come from the opus file, because reading the opus file alone is good,no problem.
thanks again for your complete analysis, and now I check my file with opusinfo before mix

**Comment by mbunkus** [comment]
Thanks @mkver for the great analysis.

@baudav If you ever run into this again, please make sure to save the original Opus file for further analysis. Thanks.

**Comment by mkver** [comment]
I'm sorry, but I think I might have made a mistake: I completely ignored the possibility that the program with which I extract the opus track from Matroska might have something to do with it. It turns out it has: If I extract it with ffmpeg, opusinfo doesn't detect any problems with the file (and if I decode both opus files with the reference decoder, the file extracted with mkvextract has distortions and is shorter than the file created by decoding the opus file extracted with ffmpeg). If I remux (with mkvmerge) the file extracted with ffmpeg, there aren't any DiscardPadding elements in the result and the file plays fine. In short: I was too fast in ruling out a bug in MKVToolNix. There might be one or it might be a defective input file. I don't think that there is a bug in mkvextract: It is supposed to use the information from the DiscardPadding, isn't it (as this information isn't stored in the bitstream level another time, isn't it?)?
I agree that we would need the original opus file to analyze this further.
Now I'll reread that ffmpeg ticket.

**Comment by mbunkus** [comment]
> I don't think that there is a bug in mkvextract: It is supposed to use the information from the DiscardPadding, isn't it (as this information isn't stored in the bitstream level another time, isn't it?)?

That is correct. The information is only available on the container level. For Opus-in-Ogg one has to compare the packet's supposed end position in samples with the Ogg page's granule position. The first one is calculated solely from the bitstream data, but the latter one (the granule position) is container-level information. The difference between the two (if any) is the discard padding, and that is stored in Matroska's `DiscardPadding` element.

**Comment by mkver** [comment]
After rereading the ffmpeg ticket I found out that only one answer is actually helpful in finding out if mkvmerge is the culprit or if the input file (i.e. the output of the encoder) is already defective: Six months ago (long after the original discussion) anthontex wrote that an opus (in ogg container) file created by ffmpeg with libopus has artifacts if muxed into matroska with ffmpeg or mkvmerge.
