### ISSUE TITLE
Bluray The Great Wall - Wrong Stream Detection (E-AC3 EX)

### ISSUE THREAD

**Issue by hubblec4** [mbunkus/mkvtoolnix#2102]
Hi Mosu

I have here this Bluray and eac3to stream detection is different to mkvmerge.
E-AC3 EX is detected as DTS, and it seems to me, that an embedded stream is not shown.
I will upload a test sample with the issue number.

**Comment by mbunkus** [comment]
Thanks. I'll look into it, but it'll be a couple of days until I'll have the time.

**Comment by mbunkus** [comment]
I don't see anything wrong here at the moment. I've compared `mkvmerge`'s identification with `ffprobe`'s (that's the identification tool from the `ffmpeg` package). Both detect the same tracks. Here are the results. I've shortened `mkvmerge`'s result to only the relevant properties, and I've left out all of the subtitle tracks in both programs' output.

`mkvmerge`'s output:

``` json
{
  "tracks": [
    { "codec": "MPEG-4p10/AVC/h.264", "properties": { "stream_id": 4113 } },
    { "codec": "TrueHD Atmos", "properties": { "audio_channels": 8, "audio_sampling_frequency": 48000, "language": "eng", "stream_id": 4352 } },
    { "codec": "AC-3/E-AC-3", "properties": { "audio_channels": 6, "audio_sampling_frequency": 48000, "language": "eng", "stream_id": 4352 } },
    { "codec": "AC-3/E-AC-3", "properties": { "audio_channels": 6, "audio_sampling_frequency": 48000, "language": "fre", "stream_id": 4353 } },
    { "codec": "AC-3/E-AC-3", "properties": { "audio_channels": 6, "audio_sampling_frequency": 48000, "language": "ger", "stream_id": 4354 } },
    { "codec": "AC-3/E-AC-3", "properties": { "audio_channels": 6, "audio_sampling_frequency": 48000, "language": "ita", "stream_id": 4355 } },
    { "codec": "AC-3/E-AC-3", "properties": { "audio_channels": 6, "audio_sampling_frequency": 48000, "language": "spa", "stream_id": 4356 } },
    { "codec": "AC-3/E-AC-3", "properties": { "audio_channels": 2, "audio_sampling_frequency": 48000, "language": "eng", "stream_id": 4357 } }
  ]
}
```

`ffprobe`'s output:

``` text
    Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1[0x1100]: Audio: truehd (AC-3 / 0x332D4341), 48000 Hz, 7.1, s32 (24 bit)
    Stream #0:2[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 640 kb/s
    Stream #0:3[0x1101]: Audio: eac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 576 kb/s
    Stream #0:4[0x1102]: Audio: eac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 576 kb/s
    Stream #0:5[0x1103]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 640 kb/s
    Stream #0:6[0x1104]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 640 kb/s
    Stream #0:7[0x1105]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 192 kb/s
```

`0x1011` is `4113`, and `0x1100` is `4352`. So the tracks match exactly.

I haven't looked at what `eac3to` does, to be honest. I consider this result to be correct, especially as there's nothing about the DTS you claim `mkvmerge` detects.

**Comment by hubblec4** [comment]
Ok, I will check it again, maybe I have made something wrong.

**Comment by hubblec4** [comment]
Mmmh, i use now v16 of MTX and all streams are shown correctly in the GUI.
Can be closed.

**Comment by hubblec4** [comment]
Hey, 

eac3to says it is E-AC3 EX with 7.1 channels, mkvmerge and ffprobe shows 5.1 channels only.
Only the Core is detected with mkvmerge and ffprobe. 
But maybe is eac3to wrong.
