### ISSUE TITLE
v.15 Progress bar for multiple files goes to 100% after only the first file is processed

### ISSUE THREAD

**Issue by Xenos71** [mbunkus/mkvtoolnix#2105]
Hello,
After installing mkvtoolnix version 15, I added three files to job queue and started multiplexing.
Then, as the first file was being processed, I noticed that the progress bars of the individual file and the total process were showing the same percentage.
When the first file finished multiplexing, the second one started and the progress bar for the individual file was reset to 0 and started το increase normally. However, the progress bar for the total process remained at 100%, wich was already wrong, since it should be just 1/3 of the whole procedure (around 33%).
When the third file started multiplexing, the progress bar for the total process still remained at 100%.
I tried a few more times with other files, but the same problem occured everytime.
I went back to v.14 just to check and it's working perfecty.
I hope you'll fix it in the next release.
Regards,
Xenos

**Comment by mbunkus** [comment]
Sorry, but I cannot reproduce this. The total progress bar updates correctly for me. It advances much slower than the current job bar, and it only reaches 100% once all three jobs have completed, just as it's supposed to be:

![muxing-100](https://user-images.githubusercontent.com/414282/31013089-cea14f16-a514-11e7-8f8f-e5bc7b55b85a.png)

Additionally there were no changes at all between v14 and v15.

Are you, really, really, really sure you're using v15 when you see such behavior?

**Comment by Xenos71** [comment]
Hi,
I have v.15.0.0 "Duel with the devil" 64bit on Windows 10.
I tested it again with four new files and the total progress bar seemed to work fine for the first two files, then when the second file finished multiplexing it suddently went up to 100% and remained there during the multiplexing of the other two files I had on queue.

![mkvtoolnix](https://user-images.githubusercontent.com/32386964/31014175-40ce89de-a522-11e7-9b1d-ffd84dd54c82.jpg)
(these are the third and the fourth file to be multiplexed)

I'll make a deep uninstall, install it again and see what happens.
Thank you for such a fast response.
Xenos

**Comment by mbunkus** [comment]
Ah! That screenshot together with your explanation gave me enough information to re-create it here. It only happens if the GUI is set to remove completed jobs automatically.

**Comment by mbunkus** [comment]
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include the fix are available.

**Comment by Xenos71** [comment]
Cool! I just tried the pre-build and it's working perfectly! 
Thanks again for taking care of this so fast.
Best regards,
Xenos
