### ISSUE TITLE
Copy - paste does not work when input language is not english

### ISSUE THREAD

**Issue by Xenos71** [mbunkus/mkvtoolnix#2106]
Hi,
I was trying to copy-paste the track name from a subtitle file to another (in the Properties window) using [Ctrl]+C and [Ctrl]+V, when I noticed that the shortkeys weren't working. I had the keyboard language set to Greek at that time.
After a few tests I found out that all shortkeys ([Ctrl] + C, V, X, Z, Y) only work when the keyboard language is set to English.
Is it possible to fix this?
Thank you in advance,
Xenos

**Comment by mbunkus** [comment]
Not really, sorry. Copy & pasting within basic UI elements is handled transparently by the GUI library I'm using, Qt. I have no influence over that, nor does my own code anything at all regarding copying & pasting.

Additionally it doesn't happen with all keyboard layouts. I can reproduce it with the Greek one, but not with the German one, for example; copying & pasting works fine with a German keyboard layout.

As a workaround you can use the mouse for copying & pasting: select the text to copy, right-click on it, select "copy" from the popup menu, navigate to and right-click in the control you want to paste into, select "paste" from the popup menu.

**Comment by mbunkus** [comment]
What actually happens with Greek keyboard layout is this:

1. When you press the key that you think is "c" Windows generates ψ.
2. Holding `Ctrl` at that moment means that the application sees the key sequence `Ctrl+ψ`.
3. Qt does not recognize that as a keyboard shortcut for the "copy" functionality.

Similar things happen with the other keys you've mentioned.

**Comment by Xenos71** [comment]
I see. Thanks for the detailed explanation, I've seen the same behavior in some other apps in the past and I never knew what was causing it.
I know everything works when I use the mouse to select an action from the menus, so it's not a real problem.
Thanks,
Xenos

**Comment by dmak** [comment]
I confirm the problem with Russian layout on v17.0.0. That is very weird, as I have another application on my PC ([GoldenDict](http://goldendict.org/)) which is built upon Qt4 and works fine.

If somebody comes across the corresponding issue for Qt, please link it from here.
