### ISSUE TITLE
Subtitles not loading

### ISSUE THREAD

**Issue by allan120791** [mbunkus/mkvtoolnix#2108]
Subtitles are not loading anymore! Just tracks and chapters. I have video files which contain subtitles, but when I open in MKVToolNix-15.0.0 the subtitles are not there

**Comment by mbunkus** [comment]
Works just fine here.

1. Please verify that the file actually contains subtitles. Check with e.g. MediaInfo. Several media players will automatically load subtitles from external files with the same name (e.g. if you have "Movie.mkv" and "Movie.srt" and you play "Movie.mkv", the player might also load and play "Movie.srt"). It's also possible that the subtitles are encoded into the video; that case they aren't separable from the video anymore.
2. Check back if the just-released v16.0.0 shows the same behavior.

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
