### ISSUE TITLE
After changing header of mkv (add name attribute) windows 10 doesn't show up anymore a preview/tile of the file

### ISSUE THREAD

**Issue by hrodeberht** [mbunkus/mkvtoolnix#2111]
Hello,

I have around 30 blurays (i own) compressed to mkv. The movie folder is automaticly from windows 10 recognized as movie folder and under properties it shows up "optimize for videos (in german) and all mkv shows up in tile view i see one picture from the movie. The subtitle tracks from the mkv files have no name attribute, these I have added with mkvtoolnix (latest version "protest"). I added just one up to two name attributes in the corresponding subtitle track with the header editor and saved.

Yet I see just the VLC-Icon over the Name over the movie/as symbol. Around 24 files I changed two are showing a movie picure as symbol and the rest the vlc symbol. I wasnt able to get the movie/tile view back.

I searched here and didn't found an answer. 

Thanks for your help

Best wishes
hrodeberht

**Comment by mbunkus** [comment]
This is a bug in Windows, not in MKVToolNix. See [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/All-tracks-vanished-after-mkvpropedit,-the-header-or-chapter-editors) for details.

Simply re-muxing the file without changing any of the settings should be a workaround to circumvent that bug.
