### ISSUE TITLE
Lack of demultiplexing in mkvtoolnix GUI and removal of mkvmerge GUI 

### ISSUE THREAD

**Issue by mkvuser** [mbunkus/mkvtoolnix#2112]
This question has been bugging me for a while: what was the point of getting rid of the older and arguably more handy GUI for merging (mkvmergeGUI), if new one, which is supposed to be covering most features of mkvtoolnix, still doesn't have the demultiplexing support?

I get it, maybe you wanted to improve batch functionality - fine, you could have done so by adding it to older GUI.

What we had for the last couple of years is a **new GUI** which is, arguably, not as handy for solo jobs as the old one, it doesn't have **demultiplexing support** (after all those years), and the **old GUI was removed entirely**.

This isn't a troll or anything, I'm legitimately asking - what was the point? I'm now sittting on 8.2.0 and presumably missing some features and a bunch of bugfixes, because versions 8.3.0 - onwards only come with new GUI

![mkv](https://user-images.githubusercontent.com/32506687/31163127-56799086-a8fa-11e7-8e78-3629c299c437.png)

**Comment by mbunkus** [comment]
Some of the reasons for the re-write are stated in [this FAQ entry](https://github.com/mbunkus/mkvtoolnix/wiki/MKVToolNix-GUI).

There's no extraction support in the GUI because there are several third-party GUIs available. Therefor there's no pressing need to provide that functionality out of the box.

**Comment by mkvuser** [comment]
Thanks for the answer. Last I checked, most of those GUI are pretty old (haven't updated in a while) and buggy. Can you recommend a good one?

**Comment by mbunkus** [comment]
BTW:

> which is, arguably, not as handy for solo jobs as the old one

You can configure MKVToolNix GUI to be much more suited to single-mux jobs, e.g. you can tell it to switch to the job output tab automatically each time you start a job. You should really give it a try, look at the options available in the preferences, mux a couple of files, and see if you can stomach switching. Yes, there were a metric shitton of bugfixes, and there are almost as many new features in current releases of MKVToolNix compared to the 8.3.0 release. You are missing out on stuff, e.g. good Blu-ray support, critical bug fixes in HEVC support etc.

> Can you recommend a good one?

gMKVExtractGUI is actively maintained. It's also just received a major update, see [these](https://forum.doom9.org/showthread.php?p=1819771#post1819771) [posts](https://forum.doom9.org/showthread.php?p=1820257#post1820257).

**Comment by mkvuser** [comment]
Cool. Any plans to add support for subtitles embedded in transport streams?

**Comment by mbunkus** [comment]
What kind of subtitles do you mean? mkvmerge supports PGS subtitles as used in Blu-ray M2TS and teletext subtitles as used in DVB M2TS. The latter functionality has received multiple important bug fixes since 8.3.0.

**Comment by mkvuser** [comment]
Hang on, I'll grab a sample video and upload it.

**Comment by mkvuser** [comment]
MPC-HC reports this stream as:

ID                             : 256 (0x100)-CC1
Menu ID                        : 1 (0x1)
Format                         : EIA-608
Muxing mode                    : SCTE 128 / DTVCC Transport
Muxing mode, more info         : Muxed in Video #1
Duration                       : 59 min 58 s
Bit rate mode                  : Constant
Stream size                    : 0.00 Byte (0%)
CaptionServiceName             : CC1

**They can be extracted with ccextractor. Tried mkvtoolnix gui 16 - it can't see them**

File is on you FTP server: /upload/1episode3.ts

![test11](https://user-images.githubusercontent.com/32506687/31164523-07739912-a901-11e7-9c56-2af13175349b.png)

**Comment by mbunkus** [comment]
Those are closed captions. I have no plans for adding support for those.

**Comment by mkvuser** [comment]
Is there a fundamental technical difference between captions and subtitles?

**Comment by mbunkus** [comment]
Well, it's one type of subtitling, but as with any format it's a completely different bitstream format, therefor it would take a lot of work to implement.

Read Wikipedia's [article](https://en.wikipedia.org/wiki/Closed_captioning) about that system if you want to know more.

Let's close this discussion, please; this is a bug tracker, after all.

**Comment by mkvuser** [comment]
OK, thanks for the answers. Guess not everything is as easy as I imagined.
