### ISSUE TITLE
VC-1 Frame rate and size

### ISSUE THREAD

**Issue by PuF777** [mbunkus/mkvtoolnix#2113]
After multiplexing files with VC-1 video codec frame width and height are always 123x123, and frame rate turns to 29 fps.

**Comment by mbunkus** [comment]
Thanks for the report. I can reproduce it. It doesn't always happen (it depends on what other types of tracks are muxed as well), but it's easy enough to trigger. I'll fix it.

**Comment by mbunkus** [comment]
New pre-builds for WIndows that include the fix are available [here](https://mkvtoolnix.download/windows/pre/).

**Comment by d2dyno** [comment]
@mbunkus can we get a build for Ubuntu/linux? Thanks!

**Comment by mbunkus** [comment]
I don't do pre-builds for Linux. Sorry. You can easily compile a package yourself, though. If you need instructions, use [these](https://mkvtoolnix.download/source.html#debian_ubuntu_package) (follow the steps that use Git instead of a release tarball).
