### ISSUE TITLE
v16 MKVtoolnix issues with VC1 w/ DTS-HD audio

### ISSUE THREAD

**Issue by CyberPunk1** [mbunkus/mkvtoolnix#2116]
OS: W7 64
MKVtoolnix: v16.0.0 x64 Portable
Issue: (w/ input: m2ts or mkv) VC1 + DTS-HD "completed ok" but is unable to be played back with MPC-HC. Version v15 works without any problems. Also VC1 + AC3 works fine with v16. I'm unsure if VC1 + TrueHD works with v16.

**Comment by mkver** [comment]
You use the release version of v16.0.0? If so, you should test the [newest pre-build](https://mkvtoolnix.download/windows/pre/64-bit/) and see if it still happens. There has been a change to the VC-1-related code (see #2113) so this might have been fixed, too. If you are using a pre-build including this fix, then this fix probably introduced a new bug and you should upload your input file (not the resulting output file) to [this ftp-server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server).

**Comment by CyberPunk1** [comment]
Yes the v16 is stable from: https://www.fosshub.com/MKVToolNix.html
I used the "newest pre-build" link you provided and it has solved the issue!
Thank you!
