### ISSUE TITLE
Feature request: daemon/server mode

### ISSUE THREAD

**Issue by OneCDOnly** [mbunkus/mkvtoolnix#2117]
Love this app. Nice work. 

Just wondered if there are any plans for a daemon or server-mode to process the job queue? 

To explain: my video files are stored on my headless file-server (Debian 9). But to process videos, I run **mkvtoolnix** GUI on my workstation (also Debian 9). 

It would be great to be able to hand-off the job queue to a **mkvtoolnix** daemon on the server to process all those files locally, instead of pulling them across the LAN to the workstation, then writing them back again. Paths would be a problem. Maybe if **mkvtoolnix** ran an embedded HTTP server when in daemon-mode, and the user selected the files (and required operations) via the web interface? Then all paths could be local to the server. 

It's possible to script these operations, but I'm hoping for something more user-friendly. 

Thank you.

**Comment by mbunkus** [comment]
Such functionality is not in the plans and most likely never will be (way too much work for a feature few people would use).

What others do in similar circumstances is to run a VNC server on the headless server with a light-weight desktop environment such as LXQT inside. Then connect to the VNC server from your desktop and run MKVToolNix GUI in the VNC server. You can even disconnect from the VNC server after starting a long queue.
