### ISSUE TITLE
Rounding and --default-duration

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2118]
Hello,

I just wanted to remux a file with a gap in its DTS timestamps due to #2071 with the additional `--default-duration <TID>:93.75fps` command-line option to close this gap. 93.75 (=48000/512) is the exact value for the amount of audio frames per second and it corresponds to a default duration of 10666666.66...ns; rounded to the nearest ns this is 10666667ns. But somehow mkvmerge uses the value of 10666666ns. The movie I am talking is about 2h 30m long; the last audio lace has a timestamp of 9049279ms (timestamp-scale 1000000) and there are 848370 packets before it; with the used default duration this gives a timestamp of 9049279434420ns which gives 9049279ms when rounded; with the exact value for the default-duration I get exactly 9049280ms; with the value 10666667ns it is 9.049280282790 which is nearer to the exact value and would give 9049280ms when rounded to ms precision. Why does mkvmerge round to 10666666ns in this example? (And mkvmerge uses the ns value internally, not the more exact rational number, doesn't it?)

Gruß
Andi

**Comment by mbunkus** [comment]
mkvmerge uses integer numbers internally, with ns precision. It doesn't do sub-ns rounding. That won't change.

**Comment by mkver** [comment]
But why does it round 1s/93.75 to 10666666ns and not 10666667ns?

**Comment by mbunkus** [comment]
Because there is no rounding at sub-ns, only cut-off.
