### ISSUE TITLE
Extract All Tracks

### ISSUE THREAD

**Issue by GovetaXV** [mbunkus/mkvtoolnix#2119]
How to Extract all Tracks in a MKV File??

**Comment by mbunkus** [comment]
1. Determine all track IDs by running e.g. `mkvmerge -J yourfile.mkv`
2. List all IDs with the desired output files for mkvextract, e.g. `mkvextract tracks yourfile.mkv 0:video.h264 1:english.aac 2:french.aac…`

If command line isn't your thing, then take a look at the available [third-party GUIs](https://mkvtoolnix.download/links.html).

Last, this isn't a forum for usage questions, it's a bug tracker. Please post usage questions in places such as [Doom9](https://forum.doom9.org/forumdisplay.php?f=74) or [VideoHelp](https://forum.videohelp.com/).
