### ISSUE TITLE
VC-1 encode not working with v16

### ISSUE THREAD

**Issue by nebbiolo** [mbunkus/mkvtoolnix#2120]
I used v16 to encode a few movies directly from the BD ISO and while it works fine for AVC it appears broken for VC-1.  VLC Media Player just crashes when playing the encoded mkv and mediainfo reports incorrect width, height and aspect ratio, as in:

`Video
ID                                       : 1
Format                                   : VC-1
Format profile                           : Advanced@L3
Codec ID                                 : V_MS/VFW/FOURCC / WVC1
Codec ID/Hint                            : Microsoft
Duration                                 : 42 min 49 s
Bit rate                                 : 25.4 Mb/s
Width                                    : 123 pixels
Original width                           : 1 920 pixels
Height                                   : 123 pixels
Original height                          : 1 080 pixels
Display aspect ratio                     : 1.000
Original display aspect ratio            : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
`
Notice the 123 pixels for Width and Height.  I tried changing them with mkvpropedit.exe along with aspect ration but to no avail.  Still not playing in VLC and still crashing.  Not sure what is going on.  With v15 and previous versions all is well.

**Comment by mkver** [comment]
Use [the newest pre-build](https://mkvtoolnix.download/windows/pre/64-bit/). There has been a bugfix related to VC-1 (see #2113). If this doesn't fix your problem, follow the instructions I outlined in #2116.
PS: MKVToolNix doesn't encode, it just remuxes.
PS: @mbunkus: I think one should make a new release version (16.1 or 17.0) or there will be more reports about this already fixed bug.

**Comment by nebbiolo** [comment]
Yes, the latest pre-build fixes the issue.  Thank you!  I apologize for not seeing that by default github only showed non-closed issues otherwise I would have seen that this has been addressed.  I assume we can close this issue now but I agree a new official version should come soon because breaking VC-1 is a big deal for many.  Thanks again.

**Comment by mkver** [comment]
There is no need to apologize. And you can actually close the issue yourself (I can't).
