### ISSUE TITLE
Can't Mux Some AC3 Files With UI or CLI

### ISSUE THREAD

**Issue by AYColumbia** [mbunkus/mkvtoolnix#2122]
In the last couple versions I've started seeing more of this error:
`[O] [2017-10-06] [18:41:37] Error: 'SomeAudioFile.ac3': Reading encrypted VOBs is not supported.`

If I try to add the AC3 file to the UI it rejects it with an "**Unrecognized file format**" dialog that says "**The file was not recognized as a supported format (exist code 2).**" What's strange is it seems the issue is only on files encoded at 192kbps or 384kbps. This happens with files I reencode from dts for example or those I extract directly at original bit rate of 192 or 384. I've uploaded an audio file with this issue to the ftp site. Please let me know if you need any other info. Thank you.

**Comment by mbunkus** [comment]
Thanks 😄 Already fixed in c709cf94a97a3c16629fc300c4b45c48ea35fba2. Fix is available i new [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/).

**Comment by AYColumbia** [comment]
Awesome!  Thank you for the quick turnaround.  I confirmed the fix as it loads and muxes the problem file. :)
