### ISSUE TITLE
VC-1 issues multiplexing

### ISSUE THREAD

**Issue by Jackcrn** [mbunkus/mkvtoolnix#2125]
VC-1 video files after multiplexing goes black. Happends to me with all VC-1 video only. I tried to demux but Iget the same result, track sound is the only that VLC play's MPC say: "lav external filter can't loaded".
Version 16.0.0, try to reinstall and even download and intall the beta but the issue still there. 
I downgrate to 15.0.0 and it works fine with VC-1

**Comment by mbunkus** [comment]
See #2113.
