### ISSUE TITLE
VC1 videostream broken in resulting MKV (v16)

### ISSUE THREAD

**Issue by wowdeathbringer** [mbunkus/mkvtoolnix#2126]
Whenever muxing a VC1 videostream with v16.0.0 (64bit), the video won't play from the resulting MKV, only the audio works. Tested it with v15.0.0 (64bit), and everything's working fine.

**Comment by mbunkus** [comment]
See #2113.

**Comment by mkver** [comment]
This is now the fourth duplicate of this bug. Wouldn't it be better to just ship a bugfix release 16.1 than to close more duplicates of the same bugreport?

**Comment by mbunkus** [comment]
I plan on releasing something new this weekend or the one after that, but it won't be just a bug fix for this particular issue. In the meantime closing issues is not that much of a deal, and users do have at least two workarounds (staying with v15 for the time being or getting an updated pre-build).
