### ISSUE TITLE
0 bytes file

### ISSUE THREAD

**Issue by emabia72** [mbunkus/mkvtoolnix#2128]
When I try to edit an MKV file with my iMac nothing happens.
The new file is 0 bytes and I get no error message.
Any idea about it?

**Comment by mkver** [comment]
Does this happen with every Matroska file? And what do you mean by edit? MKVToolNix is a collection of several programs and only the header editor and the chapter editor actually edit a file; but they don't produce new files, but change old ones. The muxer (mkvmerge, probably the main part of MKVToolNix) does not really edit, but creates new files. If you are muxing, you should tell us your command line (Multiplexer -> Show command line).
Do you have the necessary rights to create a new file at the desired position at all?
And if this is limited to a specific file, you should upload it (not the 0 byte file, but the input file(s)) to [the ftp-server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server).

**Comment by emabia72** [comment]
I mean that I was trying to remove an audio track and subs from a file but the new one is 0 bytes.
I'm coming from WIN10 and I've always used MKVTOOLNIX without any problem.

**Comment by mbunkus** [comment]
What's your command line? If you don't know: set up the multiplexer job the way you had it set up, open the "Multiplexer" menu and select "Show command line".

**Comment by emabia72** [comment]
Thanks
I'll check once I'm back home

**Comment by emabia72** [comment]
do you know MKVTOOLS ? 
Would it be a good alternative?

**Comment by mbunkus** [comment]
No & no idea.

BTW, I don't really support macOS; see [this FAQ entry](../wiki/Officially-supported-operating-systems-and-versions).

**Comment by emabia72** [comment]
Ok thanks anyway...I just thought that support was for the app and not specific for the OS

**Comment by mkver** [comment]
If this turns out to be a mac-specific problem, then @mbunkus may not be able to solve it; and it is likely that he won't invest a lot of time in it. But if your problem is not unique to macOS (i.e. if it can be reproduced on other systems), then it is likely that he will try to fix it.

**Comment by mbunkus** [comment]
Closing due to lack of feedback.
