### ISSUE TITLE
Timestamps problem with unframed ac-3 Matroska input

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2129]
Hello,

I found a negative side-effect of your [removal](https://github.com/mbunkus/mkvtoolnix/commit/f3ebd6ba778d95bb0403b64bca3e30075782f3c2) of the framed ac-3 mode. I have already uploaded files ("ac3 (1).mka" and "ac3.mka") to your ftp-server. As you know, ffmpeg sometimes recovers more ac3-frames from a damaged transport stream. It even writes incomplete audio frames:
```
I frame, track 1, timestamp 478336 (00:07:58.336), size 1536, adler 0x572ff4d5
I frame, track 1, timestamp 478368 (00:07:58.368), size 1536, adler 0x0811ec1e
I frame, track 1, timestamp 478400 (00:07:58.400), size 1536, adler 0x1bb7eb7a
I frame, track 1, timestamp 478432 (00:07:58.432), size 1536, adler 0xe4adf8cb
I frame, track 1, timestamp 478464 (00:07:58.464), size 368, adler 0xdc83ae6b
I frame, track 1, timestamp 478720 (00:07:58.720), size 1536, adler 0xf16bff94
I frame, track 1, timestamp 478752 (00:07:58.752), size 1536, adler 0xe100fe42
I frame, track 1, timestamp 478784 (00:07:58.784), size 1536, adler 0xa2a5f3e0
I frame, track 1, timestamp 478816 (00:07:58.816), size 1536, adler 0x7fbb028d
```
After remuxing with a pre-build without the framed mode (and without lacing and with a timestampscale of 1000000):
```
I frame, track 1, timestamp 478336 (00:07:58.336), size 1536, adler 0x572ff4d5
I frame, track 1, timestamp 478368 (00:07:58.368), size 1536, adler 0x0811ec1e
I frame, track 1, timestamp 478400 (00:07:58.400), size 1536, adler 0x1bb7eb7a
I frame, track 1, timestamp 478432 (00:07:58.432), size 1536, adler 0xe4adf8cb
I frame, track 1, timestamp 478464 (00:07:58.464), size 1536, adler 0xf16bff94
I frame, track 1, timestamp 478720 (00:07:58.720), size 1536, adler 0xe100fe42
I frame, track 1, timestamp 478752 (00:07:58.752), size 1536, adler 0xa2a5f3e0
I frame, track 1, timestamp 478784 (00:07:58.784), size 1536, adler 0x7fbb028d
```
The incomplete packed hasn't been kept, but it seems that its timestamp has not been deleted from the list of timestamps of the input file; therefore its timestamp is reused for the next complete packet and A/V sync is impaired (one gets a warning to this effect from mkvmerge (together with the time)). This loss of sync is additive: My file has four incomplete packets and the remuxed file is 128ms shorter (the very last packet was complete and has not been stripped away).

Gruß
Andi

PS: Does mkvmerge actually verify the crc checksums in ac-3?
PPS: Of course, the input file can be laced.

**Comment by mbunkus** [comment]
Thanks for the report. I'll look into it.

> PS: Does mkvmerge actually verify the crc checksums in ac-3?

No.

**Comment by mkver** [comment]
Thanks for the quick answer. Hint: The removal of the framed mode happened after the 16.0 release, so shouldn't this get the "vGit/Pre"-label instead of v16.0.0?

**Comment by mbunkus** [comment]
Yeah, you're right.
