### ISSUE TITLE
16.0.0 fails to mux VC-1 video properly.  15.0.0 works fine.

### ISSUE THREAD

**Issue by Qaenos** [mbunkus/mkvtoolnix#2130]
Tried to mux a video using 16.0.0 and the resulting video won't play properly in MPC-HC.  I uninstalled 16.0.0 and reinstalled 15.0.0, retired the muxing and it works fine.  Must be an issue in 16.0.0

Here's some details

-Video was VC-1
-Audio was FLAC
-Two sets of subtitles in PGS form
-Chapters

Everything except the FLAC was taken directly from a Blu-ray playlist.

**Comment by remuxer32** [comment]
VC-1 issue has been fixed. See here #2113 for more details.
