### ISSUE TITLE
Plex and VOBSUB question

### ISSUE THREAD

**Issue by ptr727** [mbunkus/mkvtoolnix#2131]
Hi, not really a MKVToolNix issue, but I'd appreciate some advice.

Plex on Shield TV has problems with some VOBSUB tracks, see:
https://forums.plex.tv/discussion/290723/long-wait-time-before-playing-some-content-player-says-directplay-server-says-transcoding

This original VOBSUB track has problems:
```
<track type="General">
<UniqueID_String>298627364693878339732767490375415421861 (0xE0A989D3C762ACC3D7CB9A35C0FADBA5)</UniqueID_String>
<CompleteName>\\STORAGE\Media\Troublesome\ShieldTV - Transcode - 50 First Dates (2004).mkv</CompleteName>
<Format>Matroska</Format>
<Format_Version>Version 4 / Version 2</Format_Version>
<FileSize_String>1.13 GiB</FileSize_String>
<Duration_String>1 h 39 min</Duration_String>
<OverallBitRate_String>1 630 kb/s</OverallBitRate_String>
<Encoded_Date>UTC 2017-05-10T21:35:53Z</Encoded_Date>
<Encoded_Application_String>HandBrake 1.0.7 2017040900</Encoded_Application_String>
<Encoded_Library_String>Lavf57.7.2</Encoded_Library_String>
</track>

<track type="Text">
<ID_String>3</ID_String>
<Format>VobSub</Format>
<CodecID>S_VOBSUB</CodecID>
<CodecID_Info>Picture based subtitle format used on DVDs</CodecID_Info>
<Language_String>English</Language_String>
<Default_String>No</Default_String>
<Forced_String>No</Forced_String>
</track>
```

This remuxed version using mkvmerge v16 works fine:
```
<track type="General">
<UniqueID_String>203236287978716899385269312862667556131 (0x98E5E2A1BD0694609329A67D0E024523)</UniqueID_String>
<CompleteName>\\STORAGE\Media\Troublesome\ShieldTV - Transcode - 50 First Dates (2004) (ReMux).mkv</CompleteName>
<Format>Matroska</Format>
<Format_Version>Version 4 / Version 2</Format_Version>
<FileSize_String>1.13 GiB</FileSize_String>
<Duration_String>1 h 39 min</Duration_String>
<OverallBitRate_String>1 627 kb/s</OverallBitRate_String>
<Encoded_Date>UTC 2017-10-14 03:12:46 / UTC 2017-05-10T21:35:53Z</Encoded_Date>
<Encoded_Application_String>mkvmerge v16.0.0 (&apos;Protest&apos;) 64-bit</Encoded_Application_String>
<Encoded_Library_String>libebml v1.3.5 + libmatroska v1.4.8 / Lavf57.7.2</Encoded_Library_String>
</track>

<track type="Text">
<ID_String>3</ID_String>
<Format>VobSub</Format>
<MuxingMode>zlib</MuxingMode>
<CodecID>S_VOBSUB</CodecID>
<CodecID_Info>Picture based subtitle format used on DVDs</CodecID_Info>
<Language_String>English</Language_String>
<Default_String>No</Default_String>
<Forced_String>No</Forced_String>
<Statistics_Tags_Issue>mkvmerge v16.0.0 (&apos;Protest&apos;) 64-bit 2017-10-14 03:12:46 / mkvmerge v16.0.0 (&apos;Protest&apos;) 64-bit 2017-10-14 03:12:46 / UTC 2017-05-10T21:35:53Z</Statistics_Tags_Issue>
<FromStats_BitRate>5532</FromStats_BitRate>
<FromStats_Duration>01:30:04.929000000</FromStats_Duration>
<FromStats_FrameCount>1303</FromStats_FrameCount>
<FromStats_StreamSize>3737750</FromStats_StreamSize>
</track>
```

While I wait for Plex to fix this, which can take forever or never, I want to fix my media library.
I've written a tool that inspects files, and either re-encodes them using Handbrake, or Re-muxes them using MKVMerge, with the logic being based on various file attributes, that I've experimented with to allow DirectPlay on my favorite playback devices.

So, question, should I look for a missing tag in the VOBSUB track and remux, e.g. <MuxingMode>, or should I look for the MKV muxing app version, e.g. <Encoded_Application_String>?

Advice?

**Comment by mbunkus** [comment]
This is not a general audio/video forum. It's a bug tracker for MKVToolNix. Your post is way offtopic, and I couldn't give advice on that even if I wanted to.

**Comment by mkver** [comment]
Weird guess: ffmpeg is (as far as I know) unable to parse a DVD's ifo files and therefore it's VOBSUB subtitles lack the color palette stored in the codec private (the colors often look awful because of that); actually, the codec private is missing for such tracks (against the spec). Upon remuxing mkvmerge uses a standard color palette for said streams and writes them in the codec private (the colors will probably still be garbage though). Maybe the lack of a codec private confuses plex. You can inspect the files with mkvinfo to find out.
