### ISSUE TITLE
mkvextract with --raw option extract track from previous container

### ISSUE THREAD

**Issue by stealzy** [mbunkus/mkvtoolnix#2133]
1. mkvtoolnix-64-bit-16.0.0-setup.exe
3. I use CLI, not GUI.
I have 2 .webm file, and extract audio from them (sorry for my wrong verbs tenses):
`mkvextract.exe tracks "C:\Users\A\Desktop\video2.webm" --raw 0:TP.ogg`
It worked correct, but then I try to do such with second file
`mkvextract.exe tracks "C:\Users\A\Desktop\video.webm" --raw 0:ghost.ogg`
i got the same track from the first video2.webm file.
I remove video2.webm and resulting .ogg file, and try again with same result.
But without --raw or --fullraw option it work correct - take track from specified file!
I suspect mkvextract have a cache or temp dir or something like this, so bug appears even after deleting first file.

**Comment by mbunkus** [comment]
No, mkvextract does not have any kind of cache. I also cannot reproduce your issue, neither on Linux nor on Windows. I highly suspect you've confused something in your analysis; e.g. you've used the same source file in both commands, or both source files actually do contain the same audio data, or you haven't compared the extracted files properly.

If you're really sure there is something fishy, then I'll need sample files for this happens (the two WebM files you're trying to extract stuff from). Please upload them to my [FTP server](../wiki/FTP-server) and provide the exact `mkvextract` commands you've used, not generic examples.

Note that track ID 0 is normally a video track, not an audio track. Note further that using `--raw` means that the audio data will be written without encapsulating it in a container. For Vorbis and Opus this means the resulting file won't be an Ogg file but raw Vorbis/Opus data which is likely unplayable by any player out there.

**Comment by mkver** [comment]
What exactly is the bug? Do you expect the two extracted tracks to be different? (Why?) And have you checked whether the first track of these files is an audio track at all? (If this is indeed an opus track inside Matroska, then it will be unplayable if extracted with the --raw option.) Can you at least give us the output of mediainfo regarding these files?
For the record: It is entirely possible for two tracks to coincide when extracted with the --raw option although they don't really coincide when extracted normally.

**Comment by mbunkus** [comment]
My guess at what happened is: you have two WebM files from the same source which contain the same audio and video content encoded with different settings/codecs (e.g. two downloads from the same Youtube video). Both files contain the same video track but different audio encodings. You wanted to extract audio as you stated originally, but you used track ID 0 which is usually the video track. As both source files contain the same encoded video, both extracted files are the same.

Don't just use any kind of track ID you think is correct. Use `mkvmerge --identify yourfile.webm` instead which will tell you which ID belongs to which track.

**Comment by stealzy** [comment]
Sorry, I mistake because my audio player not recognize resulting audio file, if --raw option is using.
However, I belive ID number is correct, there is no video inside .webm container, also I check ID with mkvinfo (do not work in new version even in CLI, because EVR.dll).
