### ISSUE TITLE
Unicode don't work for Global tags

### ISSUE THREAD

**Issue by evolfox** [mbunkus/mkvtoolnix#2135]
Hello,

Unicode global tags no longer work on newer versions but it's work on v10.0

v17.0 on mediainfo https://i.imgur.com/UdeMPeI.jpg

v10.0 on mediainfo https://i.imgur.com/7PJO6XB.jpg

Thanks

**Comment by mbunkus** [comment]
I need a sample file of the tags you're trying to add and that don't work.

**Comment by evolfox** [comment]
Here it is : https://www.dropbox.com/s/srjwr6u69kyhzbx/global_tags.xml?dl=1

**Comment by mbunkus** [comment]
Thanks. And you're right, the header announces a different encoding than the one that was actually used. The difference why v10 handled this seemingly better is that mkvmerge simply ignored the encoding specified in the header — which was a bug, obviously.
