### ISSUE TITLE
subtitle character set not selectable

### ISSUE THREAD

**Issue by Kalix1** [mbunkus/mkvtoolnix#2136]
Since version 17.0.0 (on Linux mint 64 bits) the choice of character set is no longer available for subtitles but still available for chapters.
![capture du 2017-10-17](https://user-images.githubusercontent.com/32858574/31644602-917150be-b2f7-11e7-969d-d7b8e017a992.png)

**Comment by mbunkus** [comment]
This is not a bug. See #2055.
