### ISSUE TITLE
mkvtoolnix-17.0.0 build failure

### ISSUE THREAD

**Issue by tgurr** [mbunkus/mkvtoolnix#2138]
I've a problem to build the latest 17.0.0 release and I'm afraid I've no idea why. I'm attaching the build log. Side note, just renaming the build script back to 16.0.0 it works without any problems so it has to be some kind of change from 16.0.0 to 17.0.0.

[mkvtoolnix-17.0.0.build.log](https://github.com/mbunkus/mkvtoolnix/files/1391819/mkvtoolnix-17.0.0.build.log)

Our CI also hit the same build failure:
https://galileo.mailstation.de/jenkins/job/media/2361/console
https://galileo.mailstation.de/gerrit/#/c/10321/

**Comment by tgurr** [comment]
I found the switch for the verbose output, attached is a new log:
[mkvtoolnix-17.0.0-build-verbose.log](https://github.com/mbunkus/mkvtoolnix/files/1391865/mkvtoolnix-17.0.0-build-verbose.log)

**Comment by mbunkus** [comment]
This is basically your own fault:

1. You're deactivating the check for `pandoc` by removing the inclusion of the corresponding `m4` file from `configure.ac`.
2. With that change the `@PANDOC@` pattern is not replaced anymore in `build-config.in` as `AC_SUBST(PANDOC)` isn't called.
3. Therefore `PANDOC = @PANDOC@` is set in `build-config` which is treated as "yes, `pandoc` is present and can be called".
4. As the file `doc/development.html` was removed from the source code archive in release 17 and as `PANDOC` is non-empty, the build system tries to build `doc/development.html` from `doc/development.md` by running `@PANDOC@ -o doc/development.html …`.
5. No file named `@PANDOC@` exists, obviously, therefore the build fails.

The solution is simple: leave `configure.ac` alone and don't remove the `pandoc` check from it.

**Comment by mbunkus** [comment]
What I forgot to add: `pandoc` is purely an optional dependency. If it isn't present, then the HTML development documentation won't be built. So just leave the check in; the build system works just fine if it isn't present.

**Comment by tgurr** [comment]
Thanks you very much for figuring that out and of course it fixes the problem, sorry for the noise.

However the reason for us patching configure.ac regarding pandoc is because currently it is automagic which is always a major hassle for source-based distributions since you want to build a binary by specifying the build flags and not because something might be installed on the host or not.

So could you please take this as (long overdue, sorry again) feature request to add some kind of configure switch to disable the pandoc dependency?

**Comment by mbunkus** [comment]
No, I won't, sorry, as there's really no need to do that. The file `doc/development.html` is not installed via `drake install`. It's not packaged. It's only useful for development.

If you really, really want to prevent anything with `pandoc`, then just replace `PANDOC = @PANDOC@` in `build-config.in` with `PANDOC =`. Then it doesn't matter whether or not `pandoc` is detected.

**Comment by tgurr** [comment]
Thanks, that makes sense. For now I've added your comments to the version bump commit message and removed the pandoc hack from our package. If someone wants it back he/she can apply the workaround you suggested.

Thank you very much for elaborating this in such a detail and for spending so much time to answer an "invalid" bug report, very much appreciated!

**Comment by mbunkus** [comment]
You're quite welcome.
