### ISSUE TITLE
WebVTT support broken

### ISSUE THREAD

**Issue by robUx4** [mbunkus/mkvtoolnix#2139]
I have a simple video file and want to mux it with a WebVTT file. The resulting output file doesn't contain the WebVTT track blocks, even though the WebVTT is listed in the trackinfo.

```
WEBVTT

00:00.980 --> 00:04.580
You want Ide Kirara? You aren't considering the songs, are you?!

00:04.580 --> 00:06.720
She can't sing, can she now?

00:06.720 --> 00:06.730
There was a disclaimer saying she can't sing!

00:06.730 --> 00:09.730
Cosplay negotiable
No singing please
Note:

00:09.730 --> 00:11.280
This is a major issue!
```

**Comment by Klaus1189** [comment]
Hi Steve, 
I just muxed with 17.0.0 on Win10 Pro 1709 a videofile with WebVTT subtitle and it plays fine. Also MediaInfo lists the WebVTT stream.

**Comment by mbunkus** [comment]
Thanks, Steve. I can reproduce it with the sample you've provided. It's likely due to the hours not being present in the timestamps. That is spec-compliant, therefore it's a bug in mkvmerge.
