### ISSUE TITLE
DVBSUB timestamps and duration

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#2140]
Hello,

I'm experiencing a weird issue with DVBSUB timestamps and durations. From a point onward, every second DVBSUB packet (namely those packets that actually contain a subtitle, not those that just indicate the end of a subtitle) has a gigantic duration:
```
I frame, track 1, timestamp 3792102 (01:03:12.102), duration 2160.000, size 2396, adler 0x282a954b
I frame, track 1, timestamp 3794262 (01:03:14.262), duration 2720.000, size 55, adler 0x98141639
I frame, track 1, timestamp 3796982 (01:03:16.982), duration 3380.000, size 3531, adler 0x257fae87
I frame, track 1, timestamp 3800362 (01:03:20.362), duration 53340.000, size 54, adler 0x46f6131f
I frame, track 1, timestamp 3853702 (01:04:13.702), duration 95445040.000, size 1948, adler 0xfc7ec1d3
I frame, track 1, timestamp 99298740 (27:34:58.740), duration 460.000, size 54, adler 0x464b1325
I frame, track 1, timestamp 99299200 (27:34:59.200), duration 95445120.000, size 4099, adler 0xdbea0502
I frame, track 1, timestamp 194744317 (54:05:44.317), duration 500.000, size 54, adler 0x4c4d1366
I frame, track 1, timestamp 194744817 (54:05:44.817), duration 95445576.000, size 3604, adler 0xc9ece815
I frame, track 1, timestamp 290190395 (80:36:30.395), duration 2300.000, size 54, adler 0x447f1257
I frame, track 1, timestamp 290192695 (80:36:32.695), duration 95445520.000, size 1715, adler 0x8ea65280
I frame, track 1, timestamp 385638213 (107:07:18.213), duration 3280.000, size 54, adler 0x4b7f1397
I frame, track 1, timestamp 385641493 (107:07:21.493), duration 95445176.000, size 1943, adler 0xb184dd1c
I frame, track 1, timestamp 481086671 (133:38:06.671), duration 11900.000, size 55, adler 0x924615d7
I frame, track 1, timestamp 481098571 (133:38:18.571), duration 95445920.000, size 3190, adler 0x16b64802
```
Some more info: My recording device splits the files it creates into about 1 GiB pieces. The above issue happens in the sixth file; but if I remux this file alone, everything's fine. If I add files 3-6 to the second file as additional part, the issue doesn't show up. But if I add the sixth file to the first one (as additional part) it does happen (even when I omit the files in between). Therefore I am uploading the first and the sixth file first; if you can already reproduce it, then I might not need to upload the rest.
mkvmerge isn't the only tool that shows weird timestamps: SubtitleEdit gives the first entry a timestamp of 26:27:19.218 and wraps around during the first file:
![se](https://user-images.githubusercontent.com/18448094/32135423-ab60c702-bbee-11e7-8c56-64bdf0a2d2cb.png)
I tested this on Windows 7 x64. Maybe it's an overflow affecting only Window as has already happened in #1883.

Grüße
Andi

PS: During transmission of the first file the FileZilla showed the following error message: "Fehler:	Incoming packet was garbled on decryption
Fehler:	Dateiübertragung fehlgeschlagen nach Übertragung von 551.616.512 Bytes in 3610 Sekunden". Given that FileZilla was aware of this error, it could probably correct it by retransmitting the data. Just to be sure: The CRC64 of 00000.ts is CD828EB1505376A2; for 00005.ts it is 12904FD309D00976.
[Edit]: I have now uploaded the first and sixth file and am currently uploading the second one, although I don't think that it is needed.

**Comment by mbunkus** [comment]
I haven't looked at the files yet as I'm sorely lacking in time, but TS files and timestamps are often posing problems. TS streams often don't start at 00:00:00 but at arbitrary other timestamps. mkvmerge tries to zero-base them by reading the first couple of MB of the file and subtracting the lowest timestamp found from all timestamps.

It does this independently for each file it considers an input file (normal files and appended files, but not additional parts as additional parts are logically part of another input file).

So if your "additional part" uses timestamps that are vastly different from the ones in the file you've added it as an additional part to, then I'm not surprised you're running into problems.

I will take a closer look at your files, but likely not within the next couple of weeks. It's also highly probable that this ends up as "won't fix".

**Comment by mkver** [comment]
Actually, the files come from one recording so the timestamps should be about an hour away from each other (that's the time that has elapsed between the beginning of the first and the sixth file; I have btw uploaded the first six files by now). But the durations above are very close to 26.5h so they are nearly the wraparound value for transport streams. If the timestamps are vastly different, then the only likely cause I can think of is this wraparound.

**Comment by mbunkus** [comment]
This looks due to mkvmerge's handling of other types of broken subtitle timestamps in transport stream files. As this is a big mess already and as fixing your particular issue would most likely cause other broken files (that mkvmerge now handles fine) to become broken again, I won't spend more time on this. It will remain unfixed. Sorry.

**Comment by mkver** [comment]
I already expected such a thing. Thanks for taking your time to investigate it.
