### ISSUE TITLE
24p setting results in 48p file

### ISSUE THREAD

**Issue by 7ABt6kB** [mbunkus/mkvtoolnix#2142]
I have used mkvtoolnix to slow down pal sources back to 24p with no problems. I have having an issue with one file, selected 24p and yet the output file is 48p. I have tried with and without 'fix bitstream timing info' box checked. Appreciate any help, thanks everyone.

**Comment by mbunkus** [comment]
You'll need to provide the source file so that I can actually take a look at what's happening if you want help. Please upload it to my [FTP server](../wiki/FTP-server).

**Comment by mbunkus** [comment]
Closing due to lack of feedback.

**Comment by 7ABt6kB** [comment]
I tried a different file today and the 24p setting resulted in a 12p file. Since the problem occurs with different input files, what is the next step?

**Comment by 7ABt6kB** [comment]
nvm, I found this. Didn't you write it mbunkus?

https://github.com/mbunkus/mkvtoolnix/wiki/Wrong-frame-rate-displayed
