### ISSUE TITLE
mkvpropedit --delete date overwrites rather than deletes?

### ISSUE THREAD

**Issue by aeschweik** [mbunkus/mkvtoolnix#2143]
Hello,

I am trying to create multiple Matroska files that generate the same checksums for testing purposes. I'm using FFmpeg to do so, which creates UIDs that I need to remove. When I remove the UID using the command: `mkvpropedit --delete segment-uid`, the resulting file is assigned an encoding date and time corresponding to the time that I run that command. Attempting to remove this encoding date using the command: `mkvpropedit --delete date` just overwrites it with a new encoding date - the time that I run THAT command.

The files as they're created don't have an encoding date, but I need to remove the UID so can't leave them as-is. (And for what it's worth, `mkvpropedit --delete date` appears to assign an encoding date whenever it's run, including on files already without dates.) 

Is there a way to remove both the UID and encoding time completely with mkvpropedit?

Thanks!

**Comment by mkver** [comment]
This is not an answer to your question regarding mkvpropedit, but why don't you use the 'bitexact" flag for ffmpeg's Matroska muxer? It doesn't write a segment-UID at all in the first place.

**Comment by mbunkus** [comment]
Thanks for reporting it. This is indeed a bug in code that's supposed to ensure that all mandatory elements are actually present. The thing with the date is that the element isn't actually mandatory — therefore it shouldn't be added automatically if it isn't present or if it's removed.

Should be easy to fix.

**Comment by mbunkus** [comment]
New [pre-build for Windows](https://mkvtoolnix.download/windows/pre/) that include the fix are available.

**Comment by aeschweik** [comment]
Awesome, thanks!

**Comment by mbunkus** [comment]
You're quite welcome.
