### ISSUE TITLE
How to programmatically download the latest released version

### ISSUE THREAD

**Issue by ptr727** [mbunkus/mkvtoolnix#2145]
I am trying to compare my previously downloaded tools vs. latest released versions of ffmpeg and mkvtoolnix, as used by my own tools.

For ffmpeg I found a latest released link, and I can compare it with what I have:
http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.7z

For mkvtoolnix, I need to parse the HTML page or the MD file for the version number, and then find the right build to download:
https://www.fosshub.com/MKVToolNix.html
https://mkvtoolnix.download/doc/NEWS.md
https://www.fosshub.com/MKVToolNix.html/mkvtoolnix-64-bit-17.0.0.7z

Can you please consider publishing packages for the latest released builds, and please ask fosshub for the same for windows?
Or publish an easy to parse file with the latest released version number, so I can easily build the file name to download?
Or is there another way to do this?

Thank you

**Comment by mbunkus** [comment]
All prior Windows releases are available [here](https://mkvtoolnix.download/windows/).

**Comment by ptr727** [comment]
Ok, thank you, but, can you provide a **reliable** way to know what the **current** release is?
I.e. how do I know to look in the "https://mkvtoolnix.download/windows/releases/17.0.0/" folder?

**Comment by mbunkus** [comment]
I already [do](https://mkvtoolnix.download/latest-release.xml.gz).

**Comment by ptr727** [comment]
Thank you, that is exactly what I need.

**Comment by mbunkus** [comment]
You're welcome.

If you want to download older releases, too, then you should be aware that the naming scheme's changed several times in the past. I cannot give you a mapping between version numbers and naming scheme, unfortunately. I don't have any plans for changing the naming scheme in the future, though, so the current scheme should stay stable for a long time.

**Comment by ptr727** [comment]
As FYI.

I started implementing the download logic, but it turns out that fosshub is implementing a form of direct download protection.

I download the gz file, I crack it open, I get the version: 18.0.0.
I create the URL:
```
https://www.fosshub.com/MKVToolNix.html/mkvtoolnix-64-bit-18.0.0.7z
```

If I download the file using .NET WebClient or PS Invoke-WebReqest, I get a HTML file, not a 7z file
If I open the same URL in a web browser, JS invokes a DIV with a custom URL, and starts the file download, e.g.:
```
https://download.fosshub.com/Protected/expiretime=1234;badurl=abcd=/abcd1234/MKVToolNix/mkvtoolnix-64-bit-18.0.0.7z
```
If I parse the HTML, crack out that URL, then I can directly downloaded the file.

So just an FYI, not as simple as it seemed.

**Comment by mbunkus** [comment]
I never claimed it was easy to download from FossHub via any kind of automated process. In fact, they try to prevent such use. That's why I provided you with the link to my server.

**Comment by ptr727** [comment]
Ah, forgot that little important detail, I should have used your server, much easier.
