### ISSUE TITLE
Error with variable frame rate

### ISSUE THREAD

**Issue by Muk9** [mbunkus/mkvtoolnix#2146]
Hi there,

MKVToolNix looks very promising indeed. It looks like it may just be what I have been looking for for a couple of weeks now. Unfortunately though it doesn't work with the video files (*.264) coming from my Ip camera (IeGeek). I can select the source files in mkvtoolnix-gui.exe, so it seems to be a supported format, but after pressing "start multiplexing" I get the following error in the job output:
**__This AVC/h.264 track's timing information indicates that it uses a variable frame rate. However, no default duration nor an external timestamp file has been provided for it, nor does the source container provide timestamps. The resulting timestamps may not be useful._**
An output file is created but I can't play it. I can upload a sample file to demo the issue. 
The source files (*.264) only play in the player that ships with the camera, not even in VLC or any other player I have tried. That's why I wanted to convert it - but no converter I have tried so far can read this video format.
My aim is therefore to convert and merge the many small videos that my IP camera creates into one big video file that I can then play back in a normal video player, such as VLC, and I was hoping mkvtoolnix would help me with that (as nothing else seems to work :( 
Your help would be greatly appreciated !!

**Comment by mkver** [comment]
If you (or your input files) don't provide timecodes (or ones that are probably wrong like 100000fps or so), then MKVToolNix will use 25fps (constant frame rate) by default. So it is probably something else. Maybe your camera produces streams that don't have any keyframes declared as keyframes. In this case the output file size is very small (just a few KB) because MKVToolNix discards any video frames before the first keyframe and the output file contains no video and is therefore unplayable in players. You can try the `--engage all_i_slices_are_key_frames` switch (if you use the GUI you can go to output and add in the Additional options field said option; you don't have to type it yourself, you can use the button to the right of this field).
If this doesn't change anything, then you should upload samples to [the ftp server described here](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). And maybe you should also try to decode both your input files and the created output file with ffmpeg and see what error message you get.
FYI: VLC can't play elementary H.264 streams. Try e.g. MPC-HC instead to check if the input files can be read by standard players.
Additional remark: There is a difference between appending files vs. adding them as additional parts. See [here](https://github.com/mbunkus/mkvtoolnix/wiki/Appending-files-vs.-adding-as-additional-parts) for an explanation. In the case of elementary streams it is best to use "add as additional part".

**Comment by Muk9** [comment]
Thanks very much for your prompt answer !!
I tried using the "--engage all_i_slices_are_key_frames switch" ... no difference. The source files are about 2MB each. I tried playing with the settings (picture attached) to change frame rate, key rate = every second etc ... nothing helped. 
![settings](https://user-images.githubusercontent.com/33578197/32693528-7334f3c6-c724-11e7-9a65-22fbe794d22d.png)

I had also tried MPC-HC already - it shows error "Cannot Render the file"
I tried uploading a sample file (and will probably upload the player that came shipped with the camera as well) but I get an "incorrect login using upload and only and creditials in the WinSCP ftp client. So I haven't been able to upload any files. Will try tomorrow again. 

Here is the excerpt from the WinSCP Log:
! 2017-11-11 21:11:57.433 Using username "upload".
. 2017-11-11 21:11:57.542 Server offered these authentication methods: keyboard-interactive,password
. 2017-11-11 21:11:57.542 Attempting keyboard-interactive authentication
. 2017-11-11 21:11:57.574 Prompt (keyboard interactive, "SSH server authentication", "Using keyboard-interactive authentication.", "Password: ")
. 2017-11-11 21:11:57.574 Using stored password.
. 2017-11-11 21:11:57.683 Network error: Software caused connection abort
* 2017-11-11 21:11:57.699 (EFatal) Network error: Software caused connection abort
* 2017-11-11 21:11:57.699 Authentication log (see session log for details):
* 2017-11-11 21:11:57.699 Using username "upload".
* 2017-11-11 21:11:57.699 
* 2017-11-11 21:11:57.699 Authentication failed.

**Comment by mkver** [comment]
It would probably be enough if you uploaded to an easy-to-use filehoster like dropbox.

**Comment by Muk9** [comment]
Thanks. I have uploaded the video and the player here:
https://www.dropbox.com/sh/5z4nqmtdc8gzftl/AAAsMtK36XSL14xAtqmdbykFa?dl=0
Hope that works.

**Comment by mkver** [comment]
This is not a real H.264 elementary stream: it seems to be a form of a container packetization of an H.264 stream and as such is not supported by MKVToolNix.
The packetizations seems to be built in the following way: Each header of a packet is 16 bytes long; the first four bytes are a keyword; the next four are a little-endian number indicating the length of the actual packet (excluding the header). I don't know the meaning of the last 8 bytes.
0x 48 58 56 53 (HXVS): It is right at the start and exists only once. It also does not abide by what I just said about the length field (it's length field is 0x00 05 00 00 indicating a length of 1280 bytes (of payload)).
0x48 58 41 46 (HXAF): Padding (?). Seems to have a length field of A4 (i.e. header+padding have a length of 180 bytes).
0x48 58 56 46 (HXVF): Ordinary NAL (i.e. this indicates a real payload)
I stripped a few of these headers away; then it could be played by MPC-HC.

**Comment by mkver** [comment]
I wrote a little Powershell-script to strip the unwanted headers away:
```
[byte[]]$HXVS = 0x48, 0x58, 0x56, 0x53
[byte[]]$HXVF = 0x48, 0x58, 0x56, 0x46
[byte[]]$HXAF = 0x48, 0x58, 0x41, 0x46
[byte[]]$HXFI = 0x48, 0x58, 0x46, 0x49
#Input: A filename (string -- complete Path) in the variable $filename.
#Output: A file named $output.

$Input           = [System.IO.File]::OpenRead($filename)
[byte[]]$header  = @(0)*16
[byte[]]$payload = @(0)*1048576
$out   = [System.IO.File]::Create($output)


While (($Input.Position+16) -le $Input.Length)
{
    $Null = $Input.Read($header,0,16)
    $length = [System.BitConverter]::ToUInt32($header,4)
    if (($header[0] -eq $HXVF[0]) -and ($header[1] -eq $HXVF[1]) -and ($header[2] -eq $HXVF[2]) -and ($header[3] -eq $HXVF[3]))
    {
        $Null   = $Input.Read($payload,0,$length)
        if (-not(($payload[0] -eq [byte]0x00) -and ($payload[1] -eq [byte]0x00) -and (($payload[2] -eq [byte]0x01) -or (($payload[2] -eq [byte]0x00) -and ($payload[3] -eq [byte]0x01)))))
        {
            Write-Error "No valid H.264 start code found at position ($Input.Position)."
            $Input.Close
            $out.Close
            Break
        }
        $out.Write($payload,0,$length)
    }
    elseif (($header[0] -eq $HXAF[0]) -and ($header[1] -eq $HXAF[1]) -and ($header[2] -eq $HXAF[2]) -and ($header[3] -eq $HXAF[3]))
    {
        $Input.Position += $length # Padding
    }
    elseif (($header[0] -eq $HXFI[0]) -and ($header[1] -eq $HXFI[1]) -and ($header[2] -eq $HXFI[2]) -and ($header[3] -eq $HXFI[3]))
    {
        Break
    }
    elseif (($header[0] -ne $HXVS[0]) -or ($header[1] -ne $HXVS[1]) -or ($header[2] -ne $HXVS[2]) -or ($header[3] -ne $HXVS[3]))
    {
        Write-Error "Unknown header found at position ($Input.Position-16). Header:"+([System.BitConverter]::ToString($header))
        Break
    }
}
$Input.Close()
$out.Close()
```
Works with your sample. Might break with others.

**Comment by Muk9** [comment]
Wow !! What a detailed analysis. That's very impressive. Very disappointing about the non standard video codes this manufacturer seems to be using. I have contacted them and requested to use a standard format. 
In the meantime I have tried your script, but I have to admit I haven't used Powershell before and I didn't get very far executing it. I've saved the script as Correct.ps1 and then run it in various combinations. In light of all your in depth analysis I am almost embarrassed to ask this trivial question .. How do I execute that script ?
![image](https://user-images.githubusercontent.com/33578197/32697187-46f20362-c783-11e7-8fdf-6880672ebc44.png)
![image](https://user-images.githubusercontent.com/33578197/32697201-8e72d6bc-c783-11e7-86fc-cf563fedc72b.png)
![image](https://user-images.githubusercontent.com/33578197/32697212-b579c4e6-c783-11e7-9e7d-e1386b44fb2f.png)
![image](https://user-images.githubusercontent.com/33578197/32697222-d9ef44e0-c783-11e7-963f-cc486b8a5ea9.png)

**Comment by mbunkus** [comment]
As stated by @mkver this is not a format supported by MKVToolNix. It's not something I will spend time on. 

@Muk9 modify the script and insert the two variables `$filename` and `$output` at the front, setting them to the file names you want to read from respectively write to. The script doesn't take those as command line parameters.

**Comment by Muk9** [comment]
OK thanks guys for your help.
