### ISSUE TITLE
Missing codec details for MSMPEG4v3

### ISSUE THREAD

**Issue by ptr727** [mbunkus/mkvtoolnix#2147]
Hi, I noticed MKVMerge --identify is showing a hex codec name for MSMPEG4v3 video.

MediaInfo: 
```
<Format>MPEG-4 Visual</Format>
<CodecID>V_MS/VFW/FOURCC / DIV3</CodecID>
```

FFProbe:
```
"codec_name": "msmpeg4v3",
"codec_long_name": "MPEG-4 part 2 Microsoft variant version 3",
"codec_tag_string": "DIV3",
```

MKVMerge:
```
"codec": "0x44495633 \"DIV3\"",
"properties": {
    "codec_id": "V_MS/VFW/FOURCC",
```

It would be nice of the codec name would be nicely formatted.
As always, thank you for making great tools.

Example file: https://1drv.ms/u/s!AqeqhT0NczrNh9MaydgwbsA8_yrHzQ

**Comment by mbunkus** [comment]
No, sorry. mkvmerge outputs the data that's present in the headers. What is present is the FourCC code, and that's what mkvmerge emits as `codec`. It does not and should not attempt to map that FourCC to other names that may or may not be official, recognized or widely used.
