### ISSUE TITLE
How to trim not split output?

### ISSUE THREAD

**Issue by ptr727** [mbunkus/mkvtoolnix#2149]
I feel like I'm missing something obvious, but for the life of me I can't find how to create a trimmed output, vs. splitting the output into multiple files?
I searched google, the FAQ, issues, I found others with the same question, and they say use other tools, right now I'm using ffmpeg, but I'd like to split MKV's using mkvmerge.

Maybe this is a feature request?
I'd like the ability to trim the output, maybe similar in function to split, but with the ability to also specify start and stop locations or times or sizes.

**Comment by mkver** [comment]
You can already do so -- choose the Split mode "By parts based on timestamps". You should also be aware that the restriction regarding keyframes (mkvmerge can only split at keyframes) applies here, too.

**Comment by mbunkus** [comment]
Thanks for answering this one, mkver.

**Comment by ptr727** [comment]
Ah, got it, it was not obvious from the docs, and google was no help, I did find similar questions with people reverting to other tools.
May I suggest you add a comment saying this can be used to "trim" or "cut" parts of a file.
Thanks
