### ISSUE TITLE
Progressbar don't show the progress numbers, in a special case

### ISSUE THREAD

**Issue by hubblec4** [mbunkus/mkvtoolnix#2150]
Hi Mosu

I found a small issue. Its not really an issue, I think.

I use the Bluray "Die glorreichen Sieben". The movie is split into multiple m2ts files.
I have to demux the streams, otherwise you have this issue 
https://github.com/mbunkus/mkvtoolnix/issues/2051

For the muxing process I use only 2 subtitle streams from the Bluray (ger and eng),
all other streams (Audio, Video, forced sups) are external streams.

Now I start muxing and the progress bar still stands on 0%.
After a long, long time the progress number changes to 1%.

The muxed mkv is OK and all works, but the last progress number is 5%.

I have added an mtxcfg file.
[test.zip](https://github.com/mbunkus/mkvtoolnix/files/1474597/test.zip)

**Comment by mbunkus** [comment]
Thanks for the report. I'll try to reproduce it.

**Comment by mbunkus** [comment]
No luck so far. I've tried different Blu-rays, re-creating similar jobs to the one you've uploaded the settings file for.

Could you upload the relevant source files?

**Comment by hubblec4** [comment]
I have tested with another Bluray-content and streams from HDD. It works. (One m2ts file for the movie)
So I guess you could close this issue.
Its maybe to special for these Bluray(Die glorrecihen Sieben). Maybe it is important that the m2ts file are splited in multiple parts.

When I found a new Bluray with the same issue I can report it.

**Comment by mbunkus** [comment]
Yeah, I did try it with two Blu-rays where a playlist uses multiple M2TS files. No luck with those two cases.

I'll close the issue for the time being. Feel free to get back to me if you find another such disc.
