### ISSUE TITLE
Sync option not working

### ISSUE THREAD

**Issue by smegadeth** [mbunkus/mkvtoolnix#2155]
Tried to use the delay option under audio settings in mkvtoolnix and it keeps giving me an error 'Invalid sync option specified in '--sync 1:1.273'..'  I want to delay the audio by 1.273, but it only seems to accept whole values, not decimals.

**Comment by mkver** [comment]
You can only use whole numbers for the delay. The numbers correspond to ms, so if by 1.273 you mean 1.273s, then you can just use --sync 1:1273 for the delay.

**Comment by smegadeth** [comment]
I see the error in my ways. Didn't pay attention to seconds in VLC when I found the amount of delay.  Thank You...
