### ISSUE TITLE
Seriously?

### ISSUE THREAD

**Issue by qtwigg** [mbunkus/mkvtoolnix#2157]
I have no idea what happened but if mkvtoolnix did not take so long to mux, I would not ended up having an error but it is okay, I try to use is this application has intended just to get fucked over and now I'll reencode my entire video all over again. Stupid Russians.

**Comment by kieranjol** [comment]
What Russians and what is the issue?

**Comment by mbunkus** [comment]
Please either contribute in a positive manner or don't contribute at all. Thank you.
