### ISSUE TITLE
Header editor: some entries in a non-English language aren't transformed automatically to another language

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#2159]
### **Full issue title: some entries in a non English language aren't transformed automatically to another language after setting such (another) a language as the GUI language.**

First of all: this strange behaviour applies to the header editor primarily. But I also noticed the same in the Job queue tool as well as in the Job output tool.

And now let's get to the point. If your interface language is English, everything is fine. For example: if you want to edit a Matroska file in the header editor and at the same time you want to change the interface language, then **ALL** of the English strings will be transformed automatically to your favourite/native language (e.g. German, Polish, Spanish, French, etc.). But if your default language is a **non-English** language, and you want to change that language to another (it can be English for example), then some entries won't be transformed automatically. As you can see here:

![1](https://user-images.githubusercontent.com/10992208/33231962-7031adec-d1fe-11e7-8638-630d4bb3ae8b.png)

some German entries haven't been transformed automatically into English. I have to add that this bug is not easy to re-create, so you need to reproduce my steps very precisely. Here are my steps to reproduce it:

**1. Run the GUI and make sure that your interface language is a **non-English** language. But if your language is English, then change it to another (I recommend German as it's 100% translated), close the GUI and run the GUI again (it's very important).**

**2. Go to the header editor and add a Matroska file that contains at least one video track and one audio track.**

**3. Expand all tree nodes.**

**4. Now go to the preferences dialog and change the current (non-English) language to another (for example: English).**

That's it. If all of the steps above were reproduced correctly, you should see that some non-English entries haven't been transformed automatically (as it's shown in the screenshot above).

As I mentioned at the beginning, I noticed the same behaviour in the Job queue and the Job output tool. See, please:

![2](https://user-images.githubusercontent.com/10992208/33232174-ae84dd96-d201-11e7-87d6-e184d9cbe4c7.png)

![3](https://user-images.githubusercontent.com/10992208/33232175-b5121ade-d201-11e7-9674-dea90a96dc68.png)

In order to reproduce that, you have to wait until multiplexing process is finished, and then change the interface language (in this particular case it doesn't matter whether your language is a non-English language or English).

**Comment by mbunkus** [comment]
> First of all: this strange behaviour applies to the header editor primarily.

I can reproduce this, thanks. I'll fix it.

> As I mentioned at the beginning, I noticed the same behaviour in the Job queue and the Job output tool. 

This is not a bug (I've actually explained why it isn't one before). What you've highlighted is the job's description. The job's description is a free-text string set by the user the moment a job is added to the queue. Afterwards it isn't re-translated, even if the GUI auto-sets the job title — because it's still a free-form, user-supplied string. And those simply cannot be translated in a meaningful way.

**Comment by remuxer32** [comment]
> This is not a bug (I've actually explained why it isn't one before).

Ah, indeed, now I remember your explanation. Sorry for repeating the same. But on the other hand my repeat and your explanation here will be useful for users reading this issue who don't know currently why the job's description cannot be translated (as well as the normal output which cannot be re-translated, too).
