### ISSUE TITLE
When adding an SRT I get the error "The file was not recognized as a supported format exit code 0"

### ISSUE THREAD

**Issue by Wolfeman0101** [mbunkus/mkvtoolnix#2160]
I'm trying to add an SRT file and I get the error "The file was not recognized as a supported format exit code 0".  I believe everything is formatted properly.

https://pastebin.com/RpUig9nN

**Comment by mbunkus** [comment]
Well, after downloading the content from that pastebin mkvmerge recognizes it as SRT just fine. There's probably something getting lost. Please upload the original, unmodified file somewhere where I can download it from, e.g. to my [FTP server](../wiki/FTP-server). Thanks.

**Comment by Wolfeman0101** [comment]
I've uploaded the SRT to your FTP.

**Comment by mbunkus** [comment]
Thanks. I can reproduce the issue and will fix it.

**Comment by remuxer32** [comment]
New pre-builds for Windows that contain the fix have been uploaded here:
- https://mkvtoolnix.download/windows/pre/

**Comment by Wolfeman0101** [comment]
The pre-build fixed the issue.
