### ISSUE TITLE
AVILIB: out of mem (size = 36958675440)

### ISSUE THREAD

**Issue by clbr** [mbunkus/mkvtoolnix#2161]
When trying to convert an AVI file to MKV, "mkvmerge -o test.mkv test.avi", the following error is printed:
mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
'TF2017.HC.HDRip.XviD.AC3-EVO.avi': Using the demultiplexer for the format 'AVI'.
AVILIB: out of mem (size = 36958675440)

This is the second time I've encountered such a file, so clearly some muxer thinks that is a valid AVI. Download links for that one can be found at http://rlsbb.ru/the-foreigner-2017-hc-hdrip-xvid-ac3-evo/

**Comment by clbr** [comment]
Mplayer crashes when trying to play it as-is, but telling mplayer to rebuild the index the file plays correctly.

**Comment by mbunkus** [comment]
I'm sorry, but I won't fix this. The index is indeed invalid, and I simply lack the time and the motivation to code up an index-fixing code. Use other programs like ffmpeg or mplayer to remux first, then use mkvmerge on the result, please.
