### ISSUE TITLE
GUI: multiplexer: "character set" option for MP4 embedded chapter doesn't actually get used

### ISSUE THREAD

**Issue by fireattack** [mbunkus/mkvtoolnix#2165]
Repro:

1. Open an MP4 file with ANSI charset (in my case, encoding = Shift-JIS).
2. Choose corresponding item and set charset like this:

![image](https://user-images.githubusercontent.com/4130991/33643879-3c58ff8c-da07-11e7-91f4-a7b724faae29.png)

Bugs:

1) The charset is not saved. Everytime I toggle to other item and toggle back, the charset setting is gone
2) It never shows up here:

![image](https://user-images.githubusercontent.com/4130991/33643903-5c58e9b4-da07-11e7-83b5-60735df06d07.png)

3) It doesn't show up in command line (should have an `--chapter-charset` switch)

4) Most importantly, in the result MKV file, the chapter text is not correctly decoded since my system locale is not shift-JIS

**Comment by mbunkus** [comment]
Thanks for reporting it. I'll look into it, but it'll probably take a couple of days as I'll be out of town for a while.

**Comment by mbunkus** [comment]
A new pre-build with the fix included has been [uploaded](https://mkvtoolnix.download/windows/pre/) (64-bit build is up, 32-bit one will be in a couple of minutes).

**Comment by fireattack** [comment]
Verified it's fixed in mkvtoolnix-64-bit-18.0.0-build20171206-01599-6d6241915.7z build. 

Thanks!
