### ISSUE TITLE
mkvextract: very slow processing with high CPU usage in case of local SSD drives

### ISSUE THREAD

**Issue by Grauhaar** [mbunkus/mkvtoolnix#2166]
I use the latest MKVtoolnix Windows 64bit version (18.0.0). The problem also occures in lower versions.
MKVextract works very (extremly) slow if proceesing an local file on SDD drives. I simple subtitle or audio extract from a 5GB file (makes no difference if from DVD or Blu-ray) takes serval minutes. During this time very less I/O activities (Task Manager) but high CPU (about 100% in one of the n logical CPUs) is reported. But, very strange, the problem does not occure if the same extract is done from an NAS device over an SMB connection. The NAS file is processed with approx. 800Mbit/s and the extract completes very fast.

**Comment by gabriellluz** [comment]
The same doesn't happen to me. Did you try updating the drivers?

**Comment by mbunkus** [comment]
It's likely that the behavior depends on specific content of the file you are trying to extract from. Can you please upload a sample file for which this happens to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server)? Thanks.

**Comment by Grauhaar** [comment]
Unfortunately the Filezilla connection failes with:
Status:	Verbinde mit ftp.bunkus.org:2222...
Antwort:	fzSftp started, protocol_version=8
Befehl:	open "upload@ftp.bunkus.org" 2222
Befehl:	Pass: ****
Fehler:	Network error: Software caused connection abort
Fehler:	Herstellen der Verbindung zum Server fehlgeschlagen

On the first try, an security warning with the key comes up. I select always trust. 

A ping works:
ping ftp.bunkus.org
Ping wird ausgeführt für cenedra.bunkus.org [2a01:4f8:190:8147::102:1] mit 32 Bytes Daten:
Antwort von 2a01:4f8:190:8147::102:1: Zeit=15ms

Disable Kaspersky AV does not change anything. Windows Defender is not activ. Any idea how to solve this.

**Comment by mbunkus** [comment]
That was due to a server-side problem. Sorry for the confusion. I've fixed the issue and confirmed that both WinSCP and FileZilla work fine now. Please try again.

**Comment by mbunkus** [comment]
BTW, please also provide the command line arguments you've run `mkvextract` with. Thanks.

**Comment by Grauhaar** [comment]
Sorry for the delay, was off for some days :-)
I've uploaded the file "Der Mann, der die Frauen liebte [1977 DVD $~-#= 1.54.09].mkv" and this file can be used for both tickes. (The slow processing during Extract and the Header Edit issue).

Test case 1 on PC under Win 10 64bit and SSD devices - Extract one Track - Local:
Runtime to extract an empty subtitle track is approx. 2:24min for the 1,5GB file 
CMD used: "C:\Program Files (x86)\MKVToolNix64\mkvextract.exe" tracks "s:\video\testsave\Der Mann, der die Frauen liebte [1977 DVD $~-#= 1.54.09].mkv" 2:subs.sup

Test case 2 on NAS (Synlogy) coonect over Gigabit - Extract one Track - NAS Device:
Runtime to extract an empty subtitle track is approx. 25sec for the 1,5GB file, transferrate is about 800Mbit/s 
CMD used: "C:\Program Files (x86)\MKVToolNix64\mkvextract.exe" tracks "\\synology_film\mymedia1\Liebe\Liebesdrama\Der Mann, der die Frauen liebte [1977 DVD $~-#= 1.54.09].mkv" 2:subs.sup

Test case 3 on PC under Win 10 64bit and two SDD devices - Remux using MKVToolnix GUI:
Runtime to remux is about 5sec to read the file on SSD 1 and write it to SSD 2

With this infos, I whould say, that there is no problem with the SSD devices for the file itself, because MkkvToolNix GUI processes the file very feast and in case of using mkvextract in cobination with the NSA server, it is also fast. Looks like that the problem is only if mkvextract works with the local file.

**Comment by mbunkus** [comment]
No worries, and thank you for the file & the info. I'll look into it over the next couple of days but have to ask for patience due to lack of free time at the moment.

**Comment by mbunkus** [comment]
New builds for Windows that include the fix [will be available shortly](https://mkvtoolnix.download/windows/pre/).

**Comment by Grauhaar** [comment]
Hey, thanks for fixing this issue. Just downloaded and tested it. Runs now very fast (old over 2min, now 4sec). Good work :-)
