### ISSUE TITLE
Header editor: Show/Edit Header data: incorrect info box that the data has been changed

### ISSUE THREAD

**Issue by Grauhaar** [mbunkus/mkvtoolnix#2167]
I'm using the latest MKVtoolnix version 18.0.0 for Windows 64bit. 
Using mkvmerge GUI to show Header data and if nothing is changed, now the file should be closed(red x button), in some cases an dialog box pops up which says, that the data has been changed. But this is not true, the file was only selected and nothing was changed. I tested it with serval files, some brings this notification, others not. 
An older version of MKVmerge GUI (not sure which version I used before 18.0.0) does not show this effect.

**Comment by mbunkus** [comment]
Can you please upload a sample file for which this happens to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server)? Thanks.

BTW: the program is called "MKVToolNix GUI". The other one, "mkvmerge GUI", does not exist anymore.

**Comment by Grauhaar** [comment]
Sorry for the delay, was off for some days :-)
I've uploaded the file "Der Mann, der die Frauen liebte [1977 DVD $~-#= 1.54.09].mkv" and this file can be used for both tickets. (The slow processing during Extract and the Header Edit issue).

Opening this file with the Header Editor in MKVToolNix Gui shows all content, but in case of no changes, during close (click red x) an popup windows says, somthing has be changed. 
This occures on many other files, but not on all. Some closes without popup, others brings the popup box.

**Comment by mbunkus** [comment]
Same as in the other issue: thanks, I'll get to it soonish.

**Comment by mbunkus** [comment]
New builds for Windows that include the fix [are available](https://mkvtoolnix.download/windows/pre/).

**Comment by Grauhaar** [comment]
Just tested, it works as expected. Thanks for fixing.
